[package]
name = "iroha_schema"
autotests = false

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true

[lints]
workspace = true

[dependencies]
iroha_schema_derive = { path = "../iroha_schema_derive" }

[dev-dependencies]
norito = { workspace = true, default-features = false, features = ["base-codec"] }
impls = { workspace = true }

[features]
default = []

[[test]]
name = "schema"
path = "tests/schema.rs"
