[package]
name = "stream-check"
version = "0.0.0"
edition = "2024"

[workspace]

[dependencies]
axum = { version = "0.8.9", features = ["ws"] }
displaydoc = "0.2.5"
futures = "0.3.31"
iroha_logger = { path = "../crates/iroha_logger" }
norito = { path = "../crates/norito" }
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["full"] }
tungstenite = "0.28.0"

