/**
 * Entry point for the experimental Iroha JS SDK.
 *
 * Native bindings (Norito + crypto) are provided via the required `iroha_js_host`
 * module.
 */
export {
  KotodamaCompilerClient,
  compileKotodamaProgram,
} from "./kotodamaCompiler/index.js";
export {
  AccountAddress,
  AccountAddressError,
  AccountAddressErrorCode,
  decodeI105AccountAddress,
  encodeI105AccountAddress,
  inspectAccountId,
  configureCurveSupport,
} from "./address.js";
export { normalizeIdentifierInput } from "./normalizers.js";
export {
  KotodamaDecimal,
  KotodamaInt,
  KotodamaQuantity,
  NumericV1,
  NumericV1Error,
} from "./numericV1.js";
export {
  computeIvmArtifactHashes,
  IVM_ARTIFACT_MAX_BYTES,
  IVM_PROGRAM_HEADER_LENGTH,
} from "./ivmArtifact.js";
export {
  assetReferencesMatch,
  composeAssetHoldingId,
  ensureCanonicalAccountId,
  extractAssetDefinitionId,
  normalizeAccountAliasFqn,
  normalizeAssetAliasFqn,
  normalizeAssetDefinitionId,
  normalizeI105AccountId,
  normalizeToriiAccountReference,
  tryExtractAssetDefinitionId,
  tryNormalizeAccountAliasFqn,
  tryNormalizeAssetAliasFqn,
  tryNormalizeAssetDefinitionId,
  tryNormalizeI105AccountId,
} from "./normalizers.js";
export { MultisigSpecBuilder, MultisigSpec } from "./multisig.js";
export {
  VALIDATION_FEE_CURRENT_POLICY_PROOF_PATH,
  VALIDATION_FEE_LEDGER_BINDING_SCHEMA,
  VALIDATION_FEE_POLICY_PROOF_MAX_RESPONSE_BYTES,
  VALIDATION_FEE_REQUIRED_BRIDGE_ABI_VERSION,
  VALIDATION_FEE_VERIFIED_POLICY_PROJECTION_SCHEMA,
  encodeValidationFeeCurrentPolicyProofRequestV1,
  normalizeValidationFeeCheckpointV1,
  normalizeValidationFeeLedgerBindingV1,
  verifyValidationFeeCurrentPolicyProofV1,
} from "./validationFeeConsensus.js";
export {
  computeValidationFeePayoutLifecycleProposalFingerprintV1,
  computeValidationFeePolicyProposalFingerprintV1,
} from "./validationFeeProposal.js";
export { ValidationError, ValidationErrorCode } from "./validationError.js";
export {
  ToriiClient,
  TransactionStatusError,
  TransactionTimeoutError,
  TransactionBatchAdmissionAmbiguousError,
  IsoMessageTimeoutError,
  ToriiDataModelMismatchError,
  ToriiHttpError,
  extractPipelineStatusKind,
  decodePdpCommitmentHeader,
  buildConnectWebSocketUrl,
  encryptIdentifierInputForPolicy,
  hashIdentifierEncryptedInput,
  encodeIdentifierResolutionReceiptAttestation,
  encodeIdentifierResolutionReceiptPayload,
  buildIdentifierRequestForPolicy,
  getIdentifierBfvPublicParameters,
  openConnectWebSocket,
  verifyIdentifierResolutionReceipt,
} from "./toriiClient.js";
export {
  ToriiBrowserClient,
  ToriiBrowserHttpError,
  ToriiBrowserStreamGapError,
} from "./toriiBrowserClient.js";
export {
  KAGEMUSHA_MANIFEST_VERSION,
  KAGEMUSHA_MAX_HOPS,
  KAGEMUSHA_REDEEM_REQUEST_MAX_BYTES,
  KAGEMUSHA_REQUIRED_BRIDGE_ABI_VERSION,
  KAGEMUSHA_TOP_UP_REQUEST_MAX_BYTES,
  normalizeKagemushaAssetSelector,
  normalizeKagemushaOperationId,
  normalizeKagemushaOperationReference,
  normalizeKagemushaOperationStatus,
  normalizeKagemushaRedeemRequestV4,
  normalizeKagemushaReadinessV4,
  normalizeKagemushaTopUpRequestV4,
} from "./kagemushaOffline.js";
export { NoritoRpcClient, NoritoRpcError } from "./noritoRpcClient.js";
export {
  CRYPTO_ALGORITHMS,
  SUPPORTED_CRYPTO_ALGORITHMS,
  supportedCryptoAlgorithms,
  normalizeCryptoAlgorithm,
  generateKeyPair,
  loadKeyPair,
  publicKeyFromPrivate,
  sign,
  verify,
  signEd25519,
  verifyEd25519,
  normalizeRecoveryPhrase,
  validateRecoveryPhrase,
  generateRecoveryPhrase,
  entropyToRecoveryPhrase,
  recoveryPhraseToEntropy,
  deriveEd25519SeedFromRecoveryPhrase,
  ed25519SeedToRecoveryPhrase,
  publicKeyMultihash,
  privateKeyMultihash,
  deriveConfidentialKeyset,
  deriveConfidentialKeysetFromHex,
  deriveConfidentialDiversifierV2,
  deriveConfidentialOwnerTagV2,
  deriveConfidentialReceiveAddressV2,
  deriveConfidentialNoteV2,
  deriveConfidentialNullifierV2,
  generateSm2KeyPair,
  deriveSm2KeyPairFromSeed,
  loadSm2KeyPair,
  signSm2,
  verifySm2,
  sm2PublicKeyMultihash,
  buildKaigiRosterJoinProof,
  PRIVACY_CAPABILITY_VALIDATION_STATUS_V1,
  PRIVACY_NATIVE_ARCHIVE_MAX_BYTES,
  PRIVACY_REQUIRED_BRIDGE_ABI_VERSION,
  isPrivacyNativeAvailable,
  privacyCapabilitiesV1,
  SM2_PRIVATE_KEY_LENGTH,
  SM2_PUBLIC_KEY_LENGTH,
  SM2_SIGNATURE_LENGTH,
  SM2_DEFAULT_DISTINGUISHED_ID,
  sm2FixtureFromSeed,
} from "./crypto.js";
export {
  canonicalQueryString,
  canonicalRequestMessage,
  canonicalRequestSignatureMessage,
  buildCanonicalRequestHeaders,
  buildCanonicalJsonRequest,
} from "./canonicalRequest.js";
export {
  assembleSoracloudAppInfraRequest,
  assembleSoracloudHfDeployRequest,
  buildSoracloudAppInfraDraft,
  buildSoracloudPrivateUploadedModelExecuteRequest,
  buildSoracloudPrivateUploadedModelReceiptQuery,
  buildSoracloudHfDeployDraft,
  deploySoracloudAppInfraInstruction,
  privateUploadedModelReceiptInstruction,
  upgradeSoracloudAppInfraInstruction,
} from "./soracloud.js";
export {
  buildTouchManifest,
  buildAxtDescriptor,
  normalizeAxtRejectContext,
  buildHandleRefreshRequest,
  computeAxtBinding,
} from "./axt.js";
export {
  encodeAccountIdNoritoValue,
  encodeAssetDefinitionIdNoritoValue,
  encodeCancelAssetLockV1,
  encodeQuantityNoritoValue,
  decodeCancelAssetLockV1,
  noritoDecodeBlockProofs,
  noritoEncodeInstruction,
  noritoDecodeInstruction,
  inspectSubscriptionTriggerAction,
  noritoEncodeOpenVerifyEnvelope,
  noritoDecodeOpenVerifyEnvelope,
  noritoEncodeContractManifestSignaturePayload,
  noritoEncodeTransactionPayloadBatch,
  noritoEncodeSorafsBillingAcknowledgementProofV1,
  noritoEncodeMultisigProposeRequest,
  noritoEncodeMultisigContractCallProposeRequest,
  noritoEncodeMultisigContractCallApproveRequest,
  SORAFS_BILLING_ACKNOWLEDGEMENT_PROOF_MAX_BYTES_V1,
  SORAFS_BILLING_ACKNOWLEDGEMENT_PROOF_SCHEMA_NAME_V1,
  verifyBlockMerkleProof,
  verifyBlockProofs,
  validateNoritoFrame,
  validateSorafsReplicationOrderPayloadV1,
} from "./norito.js";
export {
  buildGatewayRequest,
  computePayloadHashLiteral,
  loadComputeFixtures,
  simulateCompute,
  validatePayloadHash,
} from "./compute.js";
export {
  laneRelayEnvelopeSample,
  verifyLaneRelayEnvelope,
  verifyLaneRelayEnvelopeJson,
  verifyLaneRelayEnvelopes,
  decodeLaneRelayEnvelope,
  laneSettlementHash,
} from "./nexus.js";
export {
  NexusAppClient,
  NexusAppError,
  NexusSignatureAlgorithmEd25519,
  nexusPayloadHashHex,
} from "./nexusApp.js";
export {
  hashSignedTransaction,
  hashSignedTransactionPayload,
  decodeSignedTransaction,
  encodeContractArgumentRecord,
  hashInstructionBatch,
  resignSignedTransaction,
  feePaymentIntentToNoritoJson,
  buildRegisterDomainTransaction,
  buildExecutableBatchTransaction,
  buildExecutableBatchTransactionPayload,
  buildTransaction,
  buildTransactionPayload,
  signQuotedTransactionPayload,
  quoteAndSignTransaction,
  buildRegisterPinManifestInstruction,
  buildRegisterPinManifestTransaction,
  buildIvmProvedTransactionPayload,
  signQuotedIvmProvedTransactionPayload,
  buildIvmProvedTransaction,
  submitIvmProvedContractCall,
  buildApplySccpRouteGovernanceInstruction,
  buildApplySccpRouteGovernanceTransaction,
  buildMintAssetTransaction,
  buildBurnAssetTransaction,
  buildBurnTriggerTransaction,
  buildMintTriggerTransaction,
  buildMintAndTransferTransaction,
  buildRegisterDomainAndMintTransaction,
  buildRegisterAccountAndTransferTransaction,
  buildRegisterAssetDefinitionAndMintTransaction,
  buildRegisterAssetDefinitionMintAndTransferTransaction,
  buildRegisterMultisigTransaction,
  buildTransferAssetTransaction,
  buildTransferAssetDefinitionTransaction,
  buildTransferDomainTransaction,
  buildTransferNftTransaction,
  buildRegisterRwaTransaction,
  buildTransferRwaTransaction,
  buildMergeRwasTransaction,
  buildRedeemRwaTransaction,
  buildFreezeRwaTransaction,
  buildUnfreezeRwaTransaction,
  buildHoldRwaTransaction,
  buildReleaseRwaTransaction,
  buildForceTransferRwaTransaction,
  buildSetRwaControlsTransaction,
  buildSetRwaKeyValueTransaction,
  buildRemoveRwaKeyValueTransaction,
  buildCreateKaigiTransaction,
  buildPrivateKaigiFeeSpend,
  buildConfidentialTransferProofV2,
  buildConfidentialAssetHiddenTransferProofV1,
  buildConfidentialUnshieldProofV2,
  buildConfidentialUnshieldProofV3,
  buildPrivateCreateKaigiTransaction,
  buildJoinKaigiTransaction,
  buildPrivateJoinKaigiTransaction,
  buildLeaveKaigiTransaction,
  buildEndKaigiTransaction,
  buildPrivateEndKaigiTransaction,
  buildRecordKaigiUsageTransaction,
  buildSetKaigiRelayManifestTransaction,
  buildRegisterKaigiRelayTransaction,
  buildRegisterSmartContractCodeTransaction,
  buildRegisterSmartContractBytesTransaction,
  buildRemoveSmartContractBytesTransaction,
  buildProposeDeployContractTransaction,
  buildProposeSccpRouteGovernanceTransaction,
  buildCastZkBallotTransaction,
  buildCastPlainBallotTransaction,
  buildEnactReferendumTransaction,
  buildFinalizeReferendumTransaction,
  buildPersistCouncilForEpochTransaction,
  buildRegisterZkAssetTransaction,
  buildScheduleConfidentialPolicyTransitionTransaction,
  buildCancelConfidentialPolicyTransitionTransaction,
  buildShieldTransaction,
  buildZkTransferTransaction,
  buildUnshieldTransaction,
  buildCreateElectionTransaction,
  buildSubmitBallotTransaction,
  buildFinalizeElectionTransaction,
  buildTimeTriggerAction,
  buildPrecommitTriggerAction,
  submitSignedTransaction,
  submitTransactionEntrypoint,
} from "./transaction.js";
export {
  BrowserTransactionCodecError,
  browserSignedTransactionHashHex,
  browserTransactionCodec,
  browserTransactionPayloadHashHex,
  buildBrowserExecutableBatchPayload,
  buildBrowserInstructionTransactionPayload,
  buildBrowserTransferPayload,
  finalizeBrowserExecutableBatchTransaction,
  finalizeBrowserInstructionTransaction,
  finalizeBrowserSignedTransaction,
  validateBrowserExecutableBatchSignable,
  validateBrowserInstructionTransactionSignable,
  validateBrowserTransferSignable,
} from "./transactionCodec.js";
export {
  SMART_CONTRACT_CODE_CHUNK_BYTES,
  deploySmartContractBrowser,
  deriveContractAddress,
  prepareBrowserContractArtifact,
} from "./smartContractDeployment.js";
export {
  IVM_ARTIFACT_ADMISSION_MAX_INPUT_BYTES,
  instantiateIvmArtifactAdmissionWasm,
  verifyIvmContractArtifactAdmission,
} from "./ivmArtifactAdmissionWasm.js";
export {
  buildBurnAssetInstruction,
  buildCancelAssetLockInstruction,
  buildSetAssetTransferAvailabilityInstruction,
  ASSET_TRANSFER_AVAILABILITY_MAX_REASON_BYTES_V1,
  CANCEL_ASSET_LOCK_MAX_LOCK_ID_UTF8_BYTES_V1,
  buildMintAssetInstruction,
  buildMintTriggerRepetitionsInstruction,
  buildBurnTriggerRepetitionsInstruction,
  SORAFS_REPLICATION_ORDER_MAX_PAYLOAD_BYTES_V1,
  buildIssueReplicationOrderInstruction,
  buildCompleteReplicationOrderInstruction,
  buildExpireReplicationOrderInstruction,
  buildRegisterDomainInstruction,
  buildRegisterAccountInstruction,
  buildRegisterAssetDefinitionInstruction,
  buildGrantAccountPermissionInstruction,
  buildSetAccountKeyValueInstruction,
  buildSetAssetDefinitionAliasInstruction,
  buildExecuteTriggerInstruction,
  buildExecuteTriggerNorito,
  buildMultisigTriggerArgs,
  isMultisigSignerAuthorized,
  buildMultisigExecuteTriggerInstruction,
  buildMultisigExecuteTriggerNorito,
  buildRegisterMultisigInstruction,
  buildProposeMultisigInstruction,
  buildProposeMultisigExecuteTriggerInstruction,
  buildProposeMultisigExecuteTriggerNorito,
  buildMultisigProposeRequest,
  buildMultisigContractCallProposeRequest,
  buildMultisigContractCallApproveRequest,
  buildTransferAssetInstruction,
  buildTransferDomainInstruction,
  buildTransferAssetDefinitionInstruction,
  buildTransferNftInstruction,
  buildRegisterRwaInstruction,
  buildTransferRwaInstruction,
  buildMergeRwasInstruction,
  buildRedeemRwaInstruction,
  buildFreezeRwaInstruction,
  buildUnfreezeRwaInstruction,
  buildHoldRwaInstruction,
  buildReleaseRwaInstruction,
  buildForceTransferRwaInstruction,
  buildSetRwaControlsInstruction,
  buildSetRwaKeyValueInstruction,
  buildRemoveRwaKeyValueInstruction,
  buildCreateKaigiInstruction,
  buildJoinKaigiInstruction,
  buildLeaveKaigiInstruction,
  buildEndKaigiInstruction,
  buildRecordKaigiUsageInstruction,
  buildSetKaigiRelayManifestInstruction,
  buildRegisterKaigiRelayInstruction,
  buildRegisterSmartContractCodeInstruction,
  buildRegisterSmartContractBytesInstruction,
  buildUploadSmartContractCodeChunkInstruction,
  buildFinalizeSmartContractCodeUploadInstruction,
  buildCancelSmartContractCodeUploadInstruction,
  buildCommitContractDeploymentInstruction,
  buildRemoveSmartContractBytesInstruction,
  buildProposeDeployContractInstruction,
  buildProposeSccpRouteGovernanceInstruction,
  buildCastZkBallotInstruction,
  buildCastPlainBallotInstruction,
  buildEnactReferendumInstruction,
  buildFinalizeReferendumInstruction,
  buildPersistCouncilForEpochInstruction,
  buildSubmitAgendaProposalInstruction,
  buildClaimTwitterFollowRewardInstruction,
  buildSendToTwitterInstruction,
  buildCancelTwitterEscrowInstruction,
  buildRegisterAssetHiddenZkPoolInstruction,
  buildRegisterZkAssetInstruction,
  buildScheduleConfidentialPolicyTransitionInstruction,
  buildCancelConfidentialPolicyTransitionInstruction,
  buildShieldInstruction,
  buildZkTransferInstruction,
  buildAssetHiddenZkTransferInstruction,
  buildUnshieldInstruction,
  buildCreateElectionInstruction,
  buildSubmitBallotInstruction,
  buildFinalizeElectionInstruction,
  encodeInstruction,
  normalizeAccountId,
  normalizeAssetId,
  normalizeAssetHoldingId,
  normalizeRwaId,
} from "./instructionBuilders.js";
export {
  resolveToriiClientConfig,
  extractToriiFeatureConfig,
  extractConfidentialGasConfig,
  DEFAULT_TORII_CLIENT_CONFIG,
  DEFAULT_RETRY_PROFILE_PIPELINE,
  DEFAULT_RETRY_PROFILE_STREAMING,
} from "./config.js";
export {
  buildDaIngestRequest,
  deriveDaChunkerHandle,
  generateDaProofSummary,
  buildDaProofSummaryArtifact,
  emitDaProofSummaryArtifact,
} from "./dataAvailability.js";
export {
  buildPacs008Message,
  buildPacs009Message,
  buildSamplePacs008Message,
  buildSamplePacs009Message,
  buildCamt052Message,
  buildCamt056Message,
  buildSampleCamt052Message,
  buildSampleCamt056Message,
} from "./isoBridge.js";
export {
  SCCP_DOMAIN_SORA,
  SCCP_DOMAIN_ETH,
  SCCP_DOMAIN_BSC,
  SCCP_DOMAIN_SOLANA,
  SCCP_DOMAIN_TRON,
  SCCP_CODEC_CANONICAL_TEXT,
  SCCP_CODEC_EVM_ADDRESS20,
  SCCP_CODEC_TRON_ADDRESS21,
  SCCP_CODEC_SOLANA_PUBKEY32,
  SCCP_CODEC_KEYS,
  SCCP_PAYLOAD_KINDS,
  SCCP_SOLANA_TESTNET_GENESIS_HASH,
  SCCP_NETWORK_PROFILES,
  normalizeSccpCodecValue,
  sccpSourceEventDigest,
  normalizeSccpCapabilities,
  normalizeSccpSoraOutboundMaterial,
  normalizeSccpRegistry,
  normalizeSccpRouteGovernanceAction,
  normalizeSccpRecentMessages,
  canonicalSccpTransferPayloadBytes,
  canonicalSccpPayloadBytes,
  sccpPayloadHash,
  sccpLaneIdHash,
  sccpMessageId,
  sccpHubCommitmentFromPayload,
  canonicalSccpHubCommitmentBytes,
  sccpCommitmentLeafHash,
  canonicalSccpMerkleProofBytes,
  sccpMerkleRootFromCommitment,
  canonicalTairaSccpMessageBundleBytes,
  canonicalSccpMessagePublicInputsBytes,
  deriveSccpSolanaDestinationHashesV1,
  deriveSccpSolanaNativeVerifierConfigHashV1,
  deriveSccpSolanaSourceIdentityHashesV1,
  normalizeSccpMessageBundle,
  normalizeSccpProofRequest,
  normalizeBridgeProofSubmitPayload,
  normalizeBridgeMessageSubmitPayload,
  normalizeSccpBridgeSubmitResponse,
  parseSccpBridgeSubmitResponseJson,
  parseSccpJsonObject,
} from "./sccp.js";
export {
  decodeReplicationOrder,
  SORAFS_FIXTURE_BUNDLE_MAX_PAYLOADS_V1,
  SORAFS_FIXTURE_BUNDLE_PAYLOAD_KINDS,
  SORAFS_GOVERNANCE_DAG_CID_BYTES_V1,
  ORDERBOOK_OWNER_ACCOUNT_MAX_BYTES_V1,
  SORAFS_GOVERNANCE_DAG_MAX_BLOCKS_V1,
  SORAFS_ORDERBOOK_PAYLOAD_KINDS,
  SORAFS_PDP_PAYLOAD_KINDS,
  SORAFS_REFERENCE_MAX_INPUT_BYTES_V1,
  SORAFS_REFERENCE_MAX_LABEL_BYTES_V1,
  SorafsGatewayFetchError,
  validateFixtureBundle,
  validateGovernanceLogNode,
  validateGovernanceDagBlock,
  validateGovernanceDagHeadChain,
  validatePdpBundle,
  validatePdpChallengeProof,
  validatePdpCommitmentChallenge,
  validatePdpPayload,
  validateAppealFinanceCancelAssetLock,
  validateOrderbookPayload,
  signOrderbookPayload,
  deriveOrderbookOrderId,
  buildSignedOrderbookOrderRequest,
  buildSignedOrderbookOrderCancel,
  buildSignedOrderbookSettlementReceipt,
  sorafsGatewayFetch,
} from "./sorafs.js";
export {
  queryOracleFeeds,
  queryOracleFeedHistory,
  getLatestDefiOracleAttestation,
} from "./soracles.js";
export { ConnectRetryPolicy } from "./connectRetryPolicy.js";

import * as toriiNamespace from "./toriiClient.js";
import * as noritoNamespace from "./norito.js";
import * as cryptoNamespace from "./crypto.js";

export const Torii = toriiNamespace;
export const Norito = noritoNamespace;
export const Crypto = cryptoNamespace;
export {
  ConnectError,
  ConnectErrorCategory,
  connectErrorFrom,
  ConnectQueueError,
} from "./connectError.js";
export {
  generateConnectSid,
  createConnectSessionPreview,
} from "./connectSession.js";
export { bootstrapConnectPreviewSession } from "./connectPreviewFlow.js";
export {
  appendConnectQueueMetric,
  defaultConnectQueueRoot,
  deriveConnectSessionDirectory,
  exportConnectQueueEvidence,
  readConnectQueueSnapshot,
  updateConnectQueueSnapshot,
  writeConnectQueueSnapshot,
} from "./connectQueueDiagnostics.js";
export { ConnectQueueJournal } from "./connectQueueJournal.js";
export {
  ConnectDirection,
  ConnectJournalRecord,
  ConnectJournalError,
} from "./connectJournalRecord.js";
export {
  SoranetPuzzleClient,
  SoranetPuzzleError,
} from "./soranetPuzzleClient.js";
export {
  deriveGatewayHosts as deriveSoradnsGatewayHosts,
  hostPatternsCoverDerivedHosts,
  canonicalGatewaySuffix,
  prettyGatewaySuffix,
  tairaMonPrettyGatewaySuffix,
  canonicalGatewayWildcard,
} from "./soradns.js";
export {
  captureSumeragiTelemetrySnapshot,
  appendSumeragiTelemetrySnapshot,
} from "./telemetryReplay.js";
