//! Immutable compiler-captured identities for this source owner’s existing codecs.

const CASES: &[crate::captured_schema_tests::Case] = &[
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationModelEngineV1>(
        "iroha_data_model::sorafs::moderation::ModerationModelEngineV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationFeatureProfileV1>(
        "iroha_data_model::sorafs::moderation::ModerationFeatureProfileV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationCalibrationKnotV1>(
        "iroha_data_model::sorafs::moderation::ModerationCalibrationKnotV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationModelArtifactV1>(
        "iroha_data_model::sorafs::moderation::ModerationModelArtifactV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationModelScoreV1>(
        "iroha_data_model::sorafs::moderation::ModerationModelScoreV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationReproManifestV1>(
        "iroha_data_model::sorafs::moderation::ModerationReproManifestV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationReproBodyV1>(
        "iroha_data_model::sorafs::moderation::ModerationReproBodyV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationModelFingerprintV1>(
        "iroha_data_model::sorafs::moderation::ModerationModelFingerprintV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationSeedMaterialV1>(
        "iroha_data_model::sorafs::moderation::ModerationSeedMaterialV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationThresholdsV1>(
        "iroha_data_model::sorafs::moderation::ModerationThresholdsV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationReproSignatureV1>(
        "iroha_data_model::sorafs::moderation::ModerationReproSignatureV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationReproManifestSummary>(
        "iroha_data_model::sorafs::moderation::ModerationReproManifestSummary",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationTrustPolicyV1>(
        "iroha_data_model::sorafs::moderation::ModerationTrustPolicyV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationTrustPolicyBodyV1>(
        "iroha_data_model::sorafs::moderation::ModerationTrustPolicyBodyV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationTrustedSignerV1>(
        "iroha_data_model::sorafs::moderation::ModerationTrustedSignerV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationTrustPolicySignatureV1>(
        "iroha_data_model::sorafs::moderation::ModerationTrustPolicySignatureV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationSignedScreeningResultV1>(
        "iroha_data_model::sorafs::moderation::ModerationSignedScreeningResultV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationSignedScreeningBodyV1>(
        "iroha_data_model::sorafs::moderation::ModerationSignedScreeningBodyV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationTrustPolicySummaryV1>(
        "iroha_data_model::sorafs::moderation::ModerationTrustPolicySummaryV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationCommitteeMemberV1>(
        "iroha_data_model::sorafs::moderation::ModerationCommitteeMemberV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationCommitteeAggregateV1>(
        "iroha_data_model::sorafs::moderation::ModerationCommitteeAggregateV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationProvenancePayloadV1>(
        "iroha_data_model::sorafs::moderation::ModerationProvenancePayloadV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationProvenanceEntryV1>(
        "iroha_data_model::sorafs::moderation::ModerationProvenanceEntryV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationProvenanceLogV1>(
        "iroha_data_model::sorafs::moderation::ModerationProvenanceLogV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SoraFsModerationVoteChoice>(
        "iroha_data_model::sorafs::moderation::SoraFsModerationVoteChoice",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SoraFsModerationBallotContextV1>(
        "iroha_data_model::sorafs::moderation::SoraFsModerationBallotContextV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SoraFsModerationBallotCommitV1>(
        "iroha_data_model::sorafs::moderation::SoraFsModerationBallotCommitV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SoraFsModerationBallotRevealV1>(
        "iroha_data_model::sorafs::moderation::SoraFsModerationBallotRevealV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AdversarialCorpusManifestV1>(
        "iroha_data_model::sorafs::moderation::AdversarialCorpusManifestV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AdversarialPerceptualFamilyV1>(
        "iroha_data_model::sorafs::moderation::AdversarialPerceptualFamilyV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AdversarialPerceptualVariantV1>(
        "iroha_data_model::sorafs::moderation::AdversarialPerceptualVariantV1",
    ),
];

#[test]
fn captured_codec_schema_identities() {
    for case in CASES {
        case.check();
    }
}
