//! Typed frame identities captured before the canonical codec cutover.

#[path = "../../../fixtures/sdk/frame_identity_assertions.rs"]
mod captured;
pub(crate) use captured::{assert_bidirectional, assert_serialize};

#[test]
fn original_package_observations_are_complete() {
    captured::assert_package_complete("iroha_sccp", 93, 185);
}

#[test]
fn captured_public_frame_identities() {
    assert_bidirectional::<crate::bsc_native::BscNativeValidatorV1>(
        "iroha_sccp::bsc_native::BscNativeValidatorV1",
    );
    assert_bidirectional::<crate::bsc_native::BscNativeRecentProposerV1>(
        "iroha_sccp::bsc_native::BscNativeRecentProposerV1",
    );
    assert_bidirectional::<crate::bsc_native::BscNativeJustificationV1>(
        "iroha_sccp::bsc_native::BscNativeJustificationV1",
    );
    assert_bidirectional::<crate::bsc_native::BscNativeVoteContextV1>(
        "iroha_sccp::bsc_native::BscNativeVoteContextV1",
    );
    assert_bidirectional::<crate::bsc_native::BscNativePendingEpochV1>(
        "iroha_sccp::bsc_native::BscNativePendingEpochV1",
    );
    assert_bidirectional::<crate::bsc_native::BscNativeParliaAnchorV1>(
        "iroha_sccp::bsc_native::BscNativeParliaAnchorV1",
    );
    assert_bidirectional::<crate::bsc_native::BscNativeFinalityProofV1>(
        "iroha_sccp::bsc_native::BscNativeFinalityProofV1",
    );
    assert_bidirectional::<crate::bsc_native::BscNativeReceiptProofV1>(
        "iroha_sccp::bsc_native::BscNativeReceiptProofV1",
    );
    assert_bidirectional::<crate::bsc_native::BscNativeEmitterStateProofV1>(
        "iroha_sccp::bsc_native::BscNativeEmitterStateProofV1",
    );
    assert_bidirectional::<crate::bsc_native::BscNativeSourceProofV1>(
        "iroha_sccp::bsc_native::BscNativeSourceProofV1",
    );
    assert_bidirectional::<crate::ethereum_source::EthereumNativeForkV1>(
        "iroha_sccp::ethereum_source::EthereumNativeForkV1",
    );
    assert_bidirectional::<crate::ethereum_source::EthereumNativeForkActivationV1>(
        "iroha_sccp::ethereum_source::EthereumNativeForkActivationV1",
    );
    assert_bidirectional::<crate::ethereum_source::EthereumNativeForkScheduleV1>(
        "iroha_sccp::ethereum_source::EthereumNativeForkScheduleV1",
    );
    assert_bidirectional::<crate::ethereum_source::EthereumNativeBeaconHeaderV1>(
        "iroha_sccp::ethereum_source::EthereumNativeBeaconHeaderV1",
    );
    assert_bidirectional::<crate::ethereum_source::EthereumNativeCapellaExecutionHeaderV1>(
        "iroha_sccp::ethereum_source::EthereumNativeCapellaExecutionHeaderV1",
    );
    assert_bidirectional::<crate::ethereum_source::EthereumNativeDenebExecutionHeaderV1>(
        "iroha_sccp::ethereum_source::EthereumNativeDenebExecutionHeaderV1",
    );
    assert_bidirectional::<crate::ethereum_source::EthereumNativeExecutionHeaderV1>(
        "iroha_sccp::ethereum_source::EthereumNativeExecutionHeaderV1",
    );
    assert_bidirectional::<crate::ethereum_source::EthereumNativeLightClientHeaderV1>(
        "iroha_sccp::ethereum_source::EthereumNativeLightClientHeaderV1",
    );
    assert_bidirectional::<crate::ethereum_source::EthereumNativeSyncCommitteeV1>(
        "iroha_sccp::ethereum_source::EthereumNativeSyncCommitteeV1",
    );
    assert_bidirectional::<crate::ethereum_source::EthereumNativeLightClientBootstrapV1>(
        "iroha_sccp::ethereum_source::EthereumNativeLightClientBootstrapV1",
    );
    assert_bidirectional::<crate::ethereum_source::EthereumNativeLightClientUpdateV1>(
        "iroha_sccp::ethereum_source::EthereumNativeLightClientUpdateV1",
    );
    assert_bidirectional::<crate::ethereum_source::EthereumNativeTrustedAnchorV1>(
        "iroha_sccp::ethereum_source::EthereumNativeTrustedAnchorV1",
    );
    assert_bidirectional::<crate::ethereum_source::EthereumNativeMptProofV1>(
        "iroha_sccp::ethereum_source::EthereumNativeMptProofV1",
    );
    assert_bidirectional::<crate::ethereum_source::EthereumNativeFinalizedExecutionV1>(
        "iroha_sccp::ethereum_source::EthereumNativeFinalizedExecutionV1",
    );
    assert_bidirectional::<crate::ethereum_source::EthereumNativeSourceProofV1>(
        "iroha_sccp::ethereum_source::EthereumNativeSourceProofV1",
    );
    assert_bidirectional::<crate::TransferPayloadV1>("iroha_sccp::TransferPayloadV1");
    assert_bidirectional::<crate::SccpPayloadV1>("iroha_sccp::SccpPayloadV1");
    assert_bidirectional::<crate::SccpHubMessageKind>("iroha_sccp::SccpHubMessageKind");
    assert_bidirectional::<crate::SccpHubCommitmentV1>("iroha_sccp::SccpHubCommitmentV1");
    assert_bidirectional::<crate::SccpMerkleStepV1>("iroha_sccp::SccpMerkleStepV1");
    assert_bidirectional::<crate::SccpMerkleProofV1>("iroha_sccp::SccpMerkleProofV1");
    assert_bidirectional::<crate::TairaSccpMessageProofV1>("iroha_sccp::TairaSccpMessageProofV1");
    assert_bidirectional::<crate::SccpMessagePublicInputsV1>(
        "iroha_sccp::SccpMessagePublicInputsV1",
    );
    assert_bidirectional::<crate::SccpDestinationCallTargetV1>(
        "iroha_sccp::SccpDestinationCallTargetV1",
    );
    assert_bidirectional::<crate::SccpVerifiedBn254DestinationMaterialV1>(
        "iroha_sccp::SccpVerifiedBn254DestinationMaterialV1",
    );
    assert_bidirectional::<crate::SccpVerifiedDestinationMaterialV1>(
        "iroha_sccp::SccpVerifiedDestinationMaterialV1",
    );
    assert_bidirectional::<crate::SccpGroth16Bn254PublicSignalsV1>(
        "iroha_sccp::SccpGroth16Bn254PublicSignalsV1",
    );
    assert_bidirectional::<crate::SccpNormalizedCodecValueV1>(
        "iroha_sccp::SccpNormalizedCodecValueV1",
    );
    assert_bidirectional::<crate::SccpTransferProjectionV1>("iroha_sccp::SccpTransferProjectionV1");
    assert_bidirectional::<crate::SccpPayloadProjectionV1>("iroha_sccp::SccpPayloadProjectionV1");
    assert_bidirectional::<crate::SccpGroth16Bn254ProofRequestV1>(
        "iroha_sccp::SccpGroth16Bn254ProofRequestV1",
    );
    assert_bidirectional::<crate::SccpGroth16Bn254ProofResultV1>(
        "iroha_sccp::SccpGroth16Bn254ProofResultV1",
    );
    assert_bidirectional::<crate::SccpGroth16Bn254ProofArtifactV1>(
        "iroha_sccp::SccpGroth16Bn254ProofArtifactV1",
    );
    assert_bidirectional::<crate::SccpBls12381G1CompressedV1>(
        "iroha_sccp::SccpBls12381G1CompressedV1",
    );
    assert_bidirectional::<crate::SccpBls12381G2CompressedV1>(
        "iroha_sccp::SccpBls12381G2CompressedV1",
    );
    assert_bidirectional::<crate::SccpGroth16Bls12381ProofV1>(
        "iroha_sccp::SccpGroth16Bls12381ProofV1",
    );
    assert_bidirectional::<crate::SccpGroth16Bls12381PublicSignalsV1>(
        "iroha_sccp::SccpGroth16Bls12381PublicSignalsV1",
    );
    assert_bidirectional::<crate::SccpTonGroth16Bls12381ProofRequestV1>(
        "iroha_sccp::SccpTonGroth16Bls12381ProofRequestV1",
    );
    assert_bidirectional::<crate::SccpTonGroth16Bls12381ProofResultV1>(
        "iroha_sccp::SccpTonGroth16Bls12381ProofResultV1",
    );
    assert_bidirectional::<crate::SccpTonGroth16Bls12381ProofArtifactV1>(
        "iroha_sccp::SccpTonGroth16Bls12381ProofArtifactV1",
    );
    assert_bidirectional::<crate::SccpVerifiedTonDestinationMaterialV1>(
        "iroha_sccp::SccpVerifiedTonDestinationMaterialV1",
    );
    assert_bidirectional::<crate::native_admission::SccpNativeSourceProofV1>(
        "iroha_sccp::native_admission::SccpNativeSourceProofV1",
    );
    assert_bidirectional::<crate::native_admission::SccpNativeSourceProofEnvelopeV1>(
        "iroha_sccp::native_admission::SccpNativeSourceProofEnvelopeV1",
    );
    assert_bidirectional::<crate::native_admission::SccpNativeInboundMessageProofV1>(
        "iroha_sccp::native_admission::SccpNativeInboundMessageProofV1",
    );
    assert_bidirectional::<crate::native_admission::SccpNativeFinalityPointV1>(
        "iroha_sccp::native_admission::SccpNativeFinalityPointV1",
    );
    assert_bidirectional::<crate::native_admission::ValidatedSccpNativeInboundMessageV1>(
        "iroha_sccp::native_admission::ValidatedSccpNativeInboundMessageV1",
    );
    assert_bidirectional::<crate::replay_archive::SccpReplayArchiveFinalityV1>(
        "iroha_sccp::replay_archive::SccpReplayArchiveFinalityV1",
    );
    assert_bidirectional::<crate::replay_archive::SccpReplayArchiveLeafV1>(
        "iroha_sccp::replay_archive::SccpReplayArchiveLeafV1",
    );
    assert_bidirectional::<crate::replay_archive::SccpReplayArchiveSnapshotV1>(
        "iroha_sccp::replay_archive::SccpReplayArchiveSnapshotV1",
    );
    assert_bidirectional::<crate::replay_archive::SccpReplayArchiveReplicaBindingV1>(
        "iroha_sccp::replay_archive::SccpReplayArchiveReplicaBindingV1",
    );
    assert_bidirectional::<crate::replay_archive::SccpReplayArchiveReplicaPolicyV1>(
        "iroha_sccp::replay_archive::SccpReplayArchiveReplicaPolicyV1",
    );
    assert_bidirectional::<crate::replay_archive::SccpReplayArchiveCheckpointBodyV1>(
        "iroha_sccp::replay_archive::SccpReplayArchiveCheckpointBodyV1",
    );
    assert_bidirectional::<crate::replay_archive::SccpReplayArchiveReplicaAttestationV1>(
        "iroha_sccp::replay_archive::SccpReplayArchiveReplicaAttestationV1",
    );
    assert_bidirectional::<crate::replay_archive::SccpReplayArchiveSignedCheckpointV1>(
        "iroha_sccp::replay_archive::SccpReplayArchiveSignedCheckpointV1",
    );
    assert_bidirectional::<crate::replay_archive::SccpReplayArchiveHeadFinalityV1>(
        "iroha_sccp::replay_archive::SccpReplayArchiveHeadFinalityV1",
    );
    assert_bidirectional::<crate::replay_archive::SccpReplayArchiveSorafsManifestV1>(
        "iroha_sccp::replay_archive::SccpReplayArchiveSorafsManifestV1",
    );
    assert_bidirectional::<crate::replay_archive::SccpReplayArchiveCheckpointSetEntryV1>(
        "iroha_sccp::replay_archive::SccpReplayArchiveCheckpointSetEntryV1",
    );
    assert_bidirectional::<crate::replay_archive::SccpReplayArchiveCheckpointSetBodyV1>(
        "iroha_sccp::replay_archive::SccpReplayArchiveCheckpointSetBodyV1",
    );
    assert_bidirectional::<crate::replay_archive::SccpReplayArchiveSignedCheckpointSetV1>(
        "iroha_sccp::replay_archive::SccpReplayArchiveSignedCheckpointSetV1",
    );
    assert_bidirectional::<crate::replay_archive::SccpReplayRootResponseV1>(
        "iroha_sccp::replay_archive::SccpReplayRootResponseV1",
    );
    assert_bidirectional::<crate::replay_archive::SccpReplayWitnessResponseV1>(
        "iroha_sccp::replay_archive::SccpReplayWitnessResponseV1",
    );
    assert_bidirectional::<crate::ton_native::TonBlockIdExtV1>(
        "iroha_sccp::ton_native::TonBlockIdExtV1",
    );
    assert_bidirectional::<crate::ton_native::TonValidatorV1>(
        "iroha_sccp::ton_native::TonValidatorV1",
    );
    assert_bidirectional::<crate::ton_native::TonValidatorSetV1>(
        "iroha_sccp::ton_native::TonValidatorSetV1",
    );
    assert_bidirectional::<crate::ton_native::TonValidatorConfigV1>(
        "iroha_sccp::ton_native::TonValidatorConfigV1",
    );
    assert_bidirectional::<crate::ton_native::TonNativeAnchorV1>(
        "iroha_sccp::ton_native::TonNativeAnchorV1",
    );
    assert_bidirectional::<crate::ton_native::TonValidatorSignatureV1>(
        "iroha_sccp::ton_native::TonValidatorSignatureV1",
    );
    assert_bidirectional::<crate::ton_native::TonOrdinaryBlockSignaturesV1>(
        "iroha_sccp::ton_native::TonOrdinaryBlockSignaturesV1",
    );
    assert_bidirectional::<crate::ton_native::TonSimplexBlockSignaturesV1>(
        "iroha_sccp::ton_native::TonSimplexBlockSignaturesV1",
    );
    assert_bidirectional::<crate::ton_native::TonBlockSignaturesV1>(
        "iroha_sccp::ton_native::TonBlockSignaturesV1",
    );
    assert_bidirectional::<crate::ton_native::TonMasterchainBlockProofV1>(
        "iroha_sccp::ton_native::TonMasterchainBlockProofV1",
    );
    assert_bidirectional::<crate::ton_native::TonNativeFinalityProofV1>(
        "iroha_sccp::ton_native::TonNativeFinalityProofV1",
    );
    assert_bidirectional::<crate::ton_native::TonShardEventProofV1>(
        "iroha_sccp::ton_native::TonShardEventProofV1",
    );
    assert_bidirectional::<crate::ton_native::TonNativeSourceProofV1>(
        "iroha_sccp::ton_native::TonNativeSourceProofV1",
    );
    assert_bidirectional::<crate::ton_native::TonAccountStateOpeningV1>(
        "iroha_sccp::ton_native::TonAccountStateOpeningV1",
    );
    assert_bidirectional::<crate::ton_native::SccpTonBreakerObservationProofV1>(
        "iroha_sccp::ton_native::SccpTonBreakerObservationProofV1",
    );
    assert_bidirectional::<crate::tron_native::TronNativeWitnessV1>(
        "iroha_sccp::tron_native::TronNativeWitnessV1",
    );
    assert_bidirectional::<crate::tron_native::TronNativeDposAnchorV1>(
        "iroha_sccp::tron_native::TronNativeDposAnchorV1",
    );
    assert_bidirectional::<crate::tron_native::TronNativeSignedHeaderV1>(
        "iroha_sccp::tron_native::TronNativeSignedHeaderV1",
    );
    assert_bidirectional::<crate::tron_native::TronNativeFinalityProofV1>(
        "iroha_sccp::tron_native::TronNativeFinalityProofV1",
    );
    assert_bidirectional::<crate::tron_native::TronNativeTransactionProofV1>(
        "iroha_sccp::tron_native::TronNativeTransactionProofV1",
    );
    assert_bidirectional::<crate::tron_native::TronNativeSourceProofV1>(
        "iroha_sccp::tron_native::TronNativeSourceProofV1",
    );
}
