//! Positive access observers and independently literal source-event/byte admission boundaries.
use super::*;
use std::{
    cell::{Cell, RefCell},
    error::Error as _,
    panic::{AssertUnwindSafe, catch_unwind},
};

fn strategy(work: u64, capacity: usize, pool: &AllocationBudget) -> CheckedStrategy {
    CheckedStrategy {
        work: Work::new(work),
        counts: ChargedBuffer::new(capacity, pool).unwrap(),
    }
}
// A test-only enclosing serializer calls the shipping typed-hash boundary. It emits
// no bytes itself; the original generated bytecode field's nested measurement
// consumes the inherited count allowance. No replacement hash or codec is used.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
struct DescriptorSnapshot {
    category: std::mem::Discriminant<norito::Error>,
    resource: Option<norito::core::DecodeResourceError>,
    io: Option<std::io::ErrorKind>,
    exact: [u64; 3],
    context: Option<&'static str>,
}
impl From<&HashFailureDescriptor> for DescriptorSnapshot {
    fn from(descriptor: &HashFailureDescriptor) -> Self {
        Self {
            category: descriptor.category,
            resource: descriptor.resource,
            io: descriptor.io,
            exact: descriptor.exact,
            context: descriptor.context,
        }
    }
}
struct LookupProbe<'a> {
    checked: RefCell<&'a mut CheckedStrategy>,
    blob: &'a IvmBytecode,
    catch_refusal: bool,
    calls: Cell<usize>,
    hash: Cell<Option<HashOf<IvmBytecode>>>,
    descriptor: Cell<Option<DescriptorSnapshot>>,
    retained: RefCell<Option<TriggerContractError>>,
}
impl<'a> LookupProbe<'a> {
    fn new(checked: &'a mut CheckedStrategy, blob: &'a IvmBytecode, catch_refusal: bool) -> Self {
        Self {
            checked: RefCell::new(checked),
            blob,
            catch_refusal,
            calls: Cell::new(0),
            hash: Cell::new(None),
            descriptor: Cell::new(None),
            retained: RefCell::new(None),
        }
    }
}
impl norito::core::SerializePayload for LookupProbe<'_> {
    fn serialize(&self, _writer: &mut norito::core::Encoder<'_>) -> Result<(), norito::Error> {
        self.calls.set(self.calls.get() + 1);
        match self.checked.borrow_mut().lookup_hash(self.blob) {
            Ok(hash) => {
                self.hash.set(Some(hash));
                Ok(())
            }
            Err(TriggerContractError::Hash(failure)) => {
                self.descriptor
                    .set(Some(DescriptorSnapshot::from(&failure.descriptor)));
                if self.catch_refusal {
                    *self.retained.borrow_mut() = Some(TriggerContractError::Hash(failure));
                    Ok(())
                } else {
                    // The exact original cause moves to the caller, without cloning it.
                    Err(failure.original)
                }
            }
            Err(_) => panic!("only the actual inherited codec refusal is expected"),
        }
    }
}
struct Access<'a> {
    calls: &'a Cell<usize>,
    terminal: bool,
}
impl Iterator for Access<'_> {
    type Item = u32;
    fn next(&mut self) -> Option<u32> {
        self.calls.set(self.calls.get() + 1);
        if self.terminal { None } else { Some(7) }
    }
}
#[test]
fn native_next_and_terminal_are_admitted_before_the_observed_call() {
    for terminal in [false, true] {
        for amount in [CURSOR_NEXT - 1, CURSOR_NEXT, CURSOR_NEXT + 1] {
            let calls = Cell::new(0);
            let mut rows = Access {
                calls: &calls,
                terminal,
            };
            let mut work = Work::new(amount);
            let result = work.next(&mut rows);
            if amount < CURSOR_NEXT {
                assert_eq!(result, Err(TriggerContractError::WorkLimit));
                assert_eq!(calls.get(), 0);
                assert_eq!(work.observed.next, 0);
            } else {
                assert_eq!(result, Ok(if terminal { None } else { Some(7) }));
                assert_eq!(calls.get(), 1);
                assert_eq!(work.observed.next, 1);
            }
        }
    }
}
#[test]
fn setup_refuses_before_native_construction_and_has_independent_positive_control() {
    let rows: mv::storage::Storage<TriggerId, u32> =
        [("a".parse().unwrap(), 1)].into_iter().collect();
    let view = rows.try_committed_view_nonblocking().unwrap();
    for amount in [CURSOR_SETUP - 1, CURSOR_SETUP, CURSOR_SETUP + 1] {
        let mut work = Work::new(amount);
        let result = work.setup();
        if amount < CURSOR_SETUP {
            assert_eq!(result, Err(TriggerContractError::WorkLimit));
            assert_eq!(work.observed.setup, 0);
        } else {
            result.unwrap();
            let native = view.current_entries();
            assert_eq!(native.len(), 1);
            assert_eq!(work.observed.setup, 1);
        }
    }
    assert_eq!(CURSOR_SETUP, 29 * usize::BITS as u64 + 44);
    assert_eq!(CURSOR_NEXT, 17 * usize::BITS as u64 + 26);
}
#[test]
fn complete_utf8_comparison_bytes_and_hash_comparison_refuse_before_eq() {
    let left: TriggerId = "α".parse().unwrap();
    let right: TriggerId = "β".parse().unwrap();
    // Each UTF8 label has two bytes:7 events+4 full operand bytes, not scalar count.
    for amount in [10, 11, 12] {
        let mut work = Work::new(amount);
        let result = left.compare(&right, &mut work);
        if amount == 10 {
            assert_eq!(result, Err(TriggerContractError::WorkLimit));
            assert_eq!(work.observed.compare, 0);
        } else {
            assert_eq!(result, Ok(left.cmp(&right)));
            assert_eq!(work.observed.compare, 1);
        }
    }
    let (_, hash) = super::tests::fixture();
    for amount in [66, 67, 68] {
        let mut work = Work::new(amount);
        let result = work.hash_equal(&hash, &hash);
        if amount == 66 {
            assert_eq!(result, Err(TriggerContractError::WorkLimit));
            assert_eq!(work.observed.compare, 0);
        } else {
            assert_eq!(result, Ok(true));
            assert_eq!(work.observed.compare, 1);
        }
    }
}
#[test]
fn typed_and_deployable_hash_capsules_bind_the_actual_canonical_hashes() {
    let blob = IvmBytecode::from_compiled(vec![1, 2, 3]);
    let pool = AllocationBudget::new(0);
    // L3:3 metadata +42+6+2 =53; deploy3+36+3=42. The domain is31 bytes.
    for amount in [52, 53, 54] {
        let mut checked = strategy(amount, 0, &pool);
        let result = checked.lookup_hash(&blob);
        if amount == 52 {
            assert_eq!(result, Err(TriggerContractError::WorkLimit));
            assert_eq!(checked.work.observed.typed, 0);
        } else {
            assert_eq!(result, Ok(HashOf::new(&blob)));
            assert_eq!(checked.work.observed.typed, 1);
        }
    }
    for amount in [41, 42, 43] {
        let mut checked = strategy(amount, 0, &pool);
        let result = checked.code_hash(&blob);
        if amount == 41 {
            assert_eq!(result, Err(TriggerContractError::WorkLimit));
            assert_eq!(checked.work.observed.deploy, 0);
        } else {
            assert_eq!(result, Ok(ivm::contract_code_hash(blob.as_ref())));
            assert_eq!(checked.work.observed.deploy, 1);
        }
    }
    assert_eq!(pool.peak_reserved_bytes(), 0);
}
#[test]
fn fixed_counter_search_pays_after_a_match_and_before_terminal_or_increment() {
    let (_, key) = super::tests::fixture();
    let other = HashOf::new(&IvmBytecode::from_compiled(vec![9]));
    let pool = AllocationBudget::new(4096);
    //3 opening +2*79 full cells +1 remembered branch +19 increment=181.
    for amount in [180, 181, 182] {
        let mut checked = strategy(amount, 2, &pool);
        checked.counts.push_reserved(CounterCell {
            hash: key,
            count: 1,
        });
        checked.counts.push_reserved(CounterCell {
            hash: other,
            count: 1,
        });
        let result = checked.increment(&key);
        assert_eq!(checked.work.observed.compare, 2);
        if amount == 180 {
            assert_eq!(result, Err(TriggerContractError::WorkLimit));
            assert_eq!(checked.counts.as_slice()[0].count, 1);
        } else {
            assert_eq!(result, Ok(()));
            assert_eq!(checked.counts.as_slice()[0].count, 2);
        }
    }
    assert_eq!(pool.reserved_bytes(), 0);
}
#[test]
fn fixed_counter_removal_and_empty_scan_pay_every_consumed_cell() {
    let (_, key) = super::tests::fixture();
    let other = HashOf::new(&IvmBytecode::from_compiled(vec![9]));
    let pool = AllocationBudget::new(4096);
    //3 opening+158 tail+28 count outcome=189. Empty3+2*11=25.
    for amount in [188, 189, 190] {
        let mut checked = strategy(amount, 2, &pool);
        checked.counts.push_reserved(CounterCell {
            hash: key,
            count: 1,
        });
        checked.counts.push_reserved(CounterCell {
            hash: other,
            count: 0,
        });
        let result = checked.count_matches(&key, &NonZeroU64::MIN);
        assert_eq!(checked.work.observed.compare, 2);
        if amount == 188 {
            assert_eq!(result, Err(TriggerContractError::WorkLimit));
            assert_eq!(checked.counts.as_slice()[0].count, 1);
        } else {
            assert_eq!(result, Ok(true));
            assert_eq!(checked.counts.as_slice()[0].count, 0);
        }
    }
    for amount in [24, 25, 26] {
        let mut checked = strategy(amount, 2, &pool);
        checked.counts.push_reserved(CounterCell {
            hash: key,
            count: 1,
        });
        checked.counts.push_reserved(CounterCell {
            hash: other,
            count: 0,
        });
        if amount == 24 {
            assert_eq!(checked.empty(), Err(TriggerContractError::WorkLimit));
        } else {
            assert_eq!(checked.empty(), Ok(false));
        }
    }
    assert_eq!(pool.reserved_bytes(), 0);
}
#[test]
fn original_codec_cause_and_descriptor_remain_distinct_from_semantic_and_work() {
    struct Depths(Vec<norito::core::EncodeValueDepthGuard>);
    impl Drop for Depths {
        fn drop(&mut self) {
            while let Some(guard) = self.0.pop() {
                drop(guard);
            }
        }
    }
    let inherited = norito::core::DecodeFlagsGuard::enter(0);
    let mut guards = Depths(Vec::new());
    while let Ok(guard) = norito::core::EncodeValueDepthGuard::enter() {
        guards.0.push(guard);
    }
    let pool = AllocationBudget::new(0);
    let blob = IvmBytecode::from_compiled(vec![1]);
    let mut checked = strategy(1000, 0, &pool);
    let error = checked.lookup_hash(&blob).unwrap_err();
    let TriggerContractError::Hash(ref failure) = error else {
        panic!("actual canonical encoder refusal required");
    };
    assert!(matches!(
        failure.original(),
        norito::Error::NestingDepthExceeded {
            context: "encode budget",
            ..
        }
    ));
    assert!(failure.source().unwrap().is::<norito::Error>());
    assert_ne!(error, TriggerContractError::WorkLimit);
    assert_ne!(
        error,
        TriggerContractError::Semantic(SemanticFailure::Lookup)
    );
    assert_eq!(norito::core::get_decode_flags(), 0);
    drop(guards);
    assert_eq!(checked.lookup_hash(&blob), Ok(HashOf::new(&blob)));
    assert_eq!(norito::core::get_decode_flags(), 0);
    drop(inherited);
    assert_eq!(pool.peak_reserved_bytes(), 0);
}

#[test]
fn actual_inherited_hash_measurement_budget_retains_io_and_sticky_length_refusals() {
    let inherited = norito::core::DecodeFlagsGuard::enter(0);
    let pool = AllocationBudget::new(0);
    let blob = IvmBytecode::from_compiled(vec![1, 2, 3]);
    let expected = HashOf::new(&blob);
    // The original Vec<u8> measurement writes an eight-byte length and three
    // body bytes. HashWriter's actual digest writes are not a counting sink.
    for catch_refusal in [false, true] {
        for maximum in [10, 11, 12] {
            let mut checked = strategy(1000, 0, &pool);
            let probe = LookupProbe::new(&mut checked, &blob, catch_refusal);
            let result = norito::core::encoded_payload_len_bounded(&probe, maximum);
            assert_eq!(probe.calls.get(), 1);
            assert_eq!(probe.checked.borrow().work.observed.typed, 1);
            assert_eq!(norito::core::get_decode_flags(), 0);
            if maximum == 10 {
                let descriptor = probe.descriptor.get().unwrap();
                assert_eq!(descriptor.io, Some(std::io::ErrorKind::Other));
                assert_eq!(probe.hash.get(), None);
                if catch_refusal {
                    assert!(matches!(result, Err(norito::Error::LengthMismatch)));
                    let retained = probe.retained.borrow();
                    let Some(TriggerContractError::Hash(failure)) = retained.as_ref() else {
                        panic!("actual typed-hash cause must remain owned");
                    };
                    assert!(matches!(failure.original(), norito::Error::Io(_)));
                    assert_eq!(DescriptorSnapshot::from(&failure.descriptor), descriptor);
                    assert!(failure.source().unwrap().is::<norito::Error>());
                    assert_ne!(retained.as_ref().unwrap(), &TriggerContractError::WorkLimit);
                } else {
                    let Err(norito::Error::Io(error)) = result else {
                        panic!("the original counting writer I/O cause must propagate");
                    };
                    assert_eq!(error.kind(), std::io::ErrorKind::Other);
                    assert!(probe.retained.borrow().is_none());
                }
            } else {
                assert_eq!(result.unwrap(), 0);
                assert_eq!(probe.hash.get(), Some(expected));
                assert_eq!(probe.descriptor.get(), None);
                assert!(probe.retained.borrow().is_none());
            }
        }
    }
    // Failed scopes above have dropped: this fresh original scope is usable.
    let mut checked = strategy(1000, 0, &pool);
    let probe = LookupProbe::new(&mut checked, &blob, false);
    assert_eq!(
        norito::core::encoded_payload_len_bounded(&probe, 11).unwrap(),
        0
    );
    assert_eq!(probe.hash.get(), Some(expected));
    assert_eq!(norito::core::get_decode_flags(), 0);
    assert_eq!(pool.reserved_bytes(), 0);
    assert_eq!(pool.peak_reserved_bytes(), 0);
    drop(inherited);
}

#[test]
fn nested_hash_measurement_and_unwind_restore_original_parent_scope_and_flags() {
    struct Nested<'a, 'probe> {
        probe: &'a LookupProbe<'probe>,
        maximum: usize,
        child_io: Cell<Option<std::io::ErrorKind>>,
        later_write: Cell<bool>,
    }
    impl norito::core::SerializePayload for Nested<'_, '_> {
        fn serialize(&self, writer: &mut norito::core::Encoder<'_>) -> Result<(), norito::Error> {
            if let Err(error) = norito::core::encoded_payload_len_bounded(self.probe, self.maximum)
            {
                let norito::Error::Io(error) = error else {
                    panic!("the actual nested measurement must preserve its I/O cause");
                };
                self.child_io.set(Some(error.kind()));
            }
            // Catching the child error cannot evade the parent's sticky refusal.
            self.later_write.set(writer.write_all(&[7]).is_ok());
            Ok(())
        }
    }
    struct PanicAfterLookup<'a, 'probe>(&'a LookupProbe<'probe>);
    impl norito::core::SerializePayload for PanicAfterLookup<'_, '_> {
        fn serialize(&self, writer: &mut norito::core::Encoder<'_>) -> Result<(), norito::Error> {
            norito::core::SerializePayload::serialize(self.0, writer)?;
            panic!("unwind after the actual typed-hash measurement");
        }
    }
    let inherited = norito::core::DecodeFlagsGuard::enter(0);
    let pool = AllocationBudget::new(0);
    let blob = IvmBytecode::from_compiled(vec![1, 2, 3]);
    let expected = HashOf::new(&blob);
    for maximum in [10, 11] {
        let mut checked = strategy(1000, 0, &pool);
        let probe = LookupProbe::new(&mut checked, &blob, false);
        let nested = Nested {
            probe: &probe,
            maximum,
            child_io: Cell::new(None),
            later_write: Cell::new(false),
        };
        // Eleven measurement bytes plus the enclosing serializer's one real byte.
        let result = norito::core::encoded_payload_len_bounded(&nested, 12);
        assert_eq!(probe.calls.get(), 1);
        if maximum == 10 {
            assert!(matches!(result, Err(norito::Error::LengthMismatch)));
            assert_eq!(nested.child_io.get(), Some(std::io::ErrorKind::Other));
            assert!(!nested.later_write.get());
            assert_eq!(probe.hash.get(), None);
        } else {
            assert_eq!(result.unwrap(), 1);
            assert_eq!(nested.child_io.get(), None);
            assert!(nested.later_write.get());
            assert_eq!(probe.hash.get(), Some(expected));
        }
        assert_eq!(norito::core::get_decode_flags(), 0);
    }
    let mut checked = strategy(2000, 0, &pool);
    let probe = LookupProbe::new(&mut checked, &blob, false);
    let result = catch_unwind(AssertUnwindSafe(|| {
        let _ = norito::core::encoded_payload_len_bounded(&PanicAfterLookup(&probe), 11);
    }));
    assert!(result.is_err());
    assert_eq!(probe.calls.get(), 1);
    assert_eq!(probe.hash.get(), Some(expected));
    assert_eq!(norito::core::get_decode_flags(), 0);
    assert_eq!(
        norito::core::encoded_payload_len_bounded(&probe, 11).unwrap(),
        0
    );
    assert_eq!(probe.calls.get(), 2);
    assert_eq!(probe.checked.borrow().work.observed.typed, 2);
    assert_eq!(norito::core::get_decode_flags(), 0);
    assert_eq!(pool.reserved_bytes(), 0);
    assert_eq!(pool.peak_reserved_bytes(), 0);
    drop(inherited);
}
#[test]
fn actual_fixed_backing_refuses_before_validation_and_refunds_on_unwind() {
    let (set, _) = super::tests::fixture();
    let pool = AllocationBudget::new(0);
    assert!(matches!(
        super::super::CheckedContracts::capture(&set, u64::MAX, &pool),
        Err(TriggerContractError::Admission(_))
    ));
    assert_eq!(pool.peak_reserved_bytes(), 0);
    pool.set_limit_bytes(16 * 1024 * 1024);
    let result = catch_unwind(AssertUnwindSafe(|| {
        let checked = super::super::CheckedContracts::capture(&set, u64::MAX, &pool).unwrap();
        assert!(pool.reserved_bytes() >= std::mem::size_of::<CounterCell>());
        std::hint::black_box(&checked);
        panic!("held checked owner unwind");
    }));
    assert!(result.is_err());
    assert_eq!(pool.reserved_bytes(), 0);
}
#[test]
fn singleton_and_empty_literals_cover_actual_geometry_native_terminals_and_reset() {
    let (set, _) = super::tests::fixture();
    let data = set.data_triggers.try_committed_view_nonblocking().unwrap();
    let pipeline = set
        .pipeline_triggers
        .try_committed_view_nonblocking()
        .unwrap();
    let time = set.time_triggers.try_committed_view_nonblocking().unwrap();
    let by_call = set
        .by_call_triggers
        .try_committed_view_nonblocking()
        .unwrap();
    let contracts = set.contracts.try_committed_view_nonblocking().unwrap();
    let sources = NativeSources {
        data: &data,
        pipeline: &pipeline,
        time: &time,
        by_call: &by_call,
        contracts: &contracts,
    };
    let pool = AllocationBudget::new(16 * 1024 * 1024);
    // Independent fixed-control sum1004, plus23 native setups and19 next calls.
    let exact = 23 * (29 * usize::BITS as u64 + 44) + 19 * (17 * usize::BITS as u64 + 26) + 1004;
    if usize::BITS == 64 {
        assert_eq!(exact, 65870);
        assert_eq!(
            TRIGGER_CONTRACT_BASE_WORK + TRIGGER_CONTRACT_ROW_WORK,
            70000
        );
    }
    for amount in [exact - 1, exact, exact + 1] {
        let mut checked = CheckedStrategy::prepare(&sources, amount, &pool).unwrap();
        let result = checked.validate(&sources);
        if amount < exact {
            assert_eq!(result, Err(TriggerContractError::WorkLimit));
        } else {
            assert_eq!(result, Ok(()));
            assert_eq!(checked.work.remaining, amount - exact);
            assert_eq!(checked.work.observed.setup, 23);
            assert_eq!(checked.work.observed.next, 19);
            assert_eq!(checked.work.observed.typed, 2);
            assert_eq!(checked.work.observed.deploy, 2);
            assert_eq!(checked.work.observed.reset, 1);
        }
    }
    assert_eq!(pool.reserved_bytes(), 0);
    let empty = Set::default();
    let checked = super::super::CheckedContracts::capture(
        &empty,
        23 * CURSOR_SETUP + 15 * CURSOR_NEXT + 81,
        &pool,
    )
    .unwrap();
    drop(checked);
    assert_eq!(pool.reserved_bytes(), 0);
}
#[test]
fn original_zero_action_bad_code_keeps_phase_prefix_and_zero_counter_backing() {
    let set = Set::default();
    let bytes = IvmBytecode::from_compiled(vec![1, 2, 3]);
    let key = HashOf::new(&bytes);
    let mut block = set.block();
    block.contracts.insert(
        key,
        IvmBytecodeEntry {
            original_contract: bytes,
            code_hash: Hash::new(b"wrong"),
            count: NonZeroU64::MIN,
        },
    );
    block.commit();
    let pool = AllocationBudget::new(0);
    let prefix = 13 * CURSOR_SETUP + 5 * CURSOR_NEXT + 277;
    if usize::BITS == 64 {
        assert_eq!(prefix, 30547);
    }
    assert!(matches!(
        super::super::CheckedContracts::capture(&set, prefix - 1, &pool),
        Err(TriggerContractError::WorkLimit)
    ));
    for amount in [prefix, prefix + 1] {
        assert!(matches!(
            super::super::CheckedContracts::capture(&set, amount, &pool),
            Err(TriggerContractError::Semantic(SemanticFailure::Code))
        ));
    }
    assert_eq!(pool.reserved_bytes(), 0);
    assert_eq!(pool.peak_reserved_bytes(), 0);
}
#[test]
fn reset_precedes_retirement_and_reuses_the_same_funded_capacity() {
    let pool = AllocationBudget::new(4096);
    let (_, hash) = super::tests::fixture();
    for amount in [2, 3, 4] {
        let mut checked = strategy(amount, 1, &pool);
        checked.counts.push_reserved(CounterCell { hash, count: 0 });
        let original = checked.counts.as_slice().as_ptr();
        let reserved = pool.reserved_bytes();
        if amount == 2 {
            assert_eq!(checked.reset(), Err(TriggerContractError::WorkLimit));
            assert_eq!(checked.counts.as_slice().len(), 1);
            assert_eq!(checked.work.observed.reset, 0);
        } else {
            assert_eq!(checked.reset(), Ok(()));
            assert_eq!(checked.work.observed.reset, 1);
            assert_eq!(pool.reserved_bytes(), reserved);
            checked.counts.push_reserved(CounterCell { hash, count: 1 });
            assert_eq!(checked.counts.as_slice().as_ptr(), original);
        }
        drop(checked);
        assert_eq!(pool.reserved_bytes(), 0);
    }
}
#[test]
fn canonical_typed_bytes_preserve_flags_schema_and_complete_deployable_domain() {
    for (length, prefix) in [
        (0usize, vec![8]),
        (3, vec![11]),
        (119, vec![127]),
        (120, vec![128, 1]),
    ] {
        let body = vec![0x55; length];
        let value = IvmBytecode::from_compiled(body.clone());
        let mut expected = prefix;
        expected.extend_from_slice(&(length as u64).to_le_bytes());
        expected.extend_from_slice(&body);
        let mut actual = Vec::new();
        norito::codec::encode_adaptive_into(&value, &mut actual).unwrap();
        assert_eq!(actual, expected);
        assert_eq!(
            Hash::from(HashOf::try_new(&value).unwrap()),
            Hash::new(&expected)
        );
        assert_eq!(
            norito::schema::identity::nominal_name::<IvmBytecode>(),
            "iroha_data_model::transaction::executable::model::IvmBytecode"
        );
        let mut deployable = b"iroha:ivm:contract-artifact:v1\0".to_vec();
        assert_eq!(deployable.len(), 31);
        deployable.extend_from_slice(&body);
        assert_eq!(ivm::contract_code_hash(&body), Hash::new(&deployable));
    }
}

fn assert_allocator_census_positive_control() {
    use crate::test_allocations::allocations_during;
    assert_eq!(allocations_during(|| {}), 0);
    assert_eq!(
        allocations_during(|| drop(std::hint::black_box(Box::new([42_u8; 64])))),
        1
    );
}

#[test]
fn cold_and_warm_original_native_cursors_and_full_history_tails_do_not_allocate() {
    use crate::test_allocations::allocations_during;
    let (mut set, hash) = super::tests::fixture();
    set.data_triggers = [
        ("a".parse().unwrap(), super::tests::action(hash)),
        ("c".parse().unwrap(), super::tests::action(hash)),
        ("e".parse().unwrap(), super::tests::action(hash)),
    ]
    .into_iter()
    .collect();
    let mut block = set.data_triggers.block();
    block.get_mut(&"a".parse().unwrap()).unwrap().repeats = Repeats::Exactly(7);
    block.remove("c".parse().unwrap());
    block.insert("b".parse().unwrap(), super::tests::action(hash));
    // Equal-value publication and absent removal remain genuine physical tails.
    block.get_mut(&"e".parse().unwrap()).unwrap().repeats = Repeats::Indefinitely;
    block.remove("d".parse().unwrap());
    block.commit();
    let view = set.data_triggers.try_committed_view_nonblocking().unwrap();
    let pool = AllocationBudget::new(0);
    let mut checked = strategy(u64::MAX, 0, &pool);
    assert_allocator_census_positive_control();
    // These are the first and repeated observed native traversals of this held
    // read owner. Reader acquisition and all fixture/backing setup are outside.
    for _warm in [false, true] {
        for image in [Image::Current, Image::Predecessor] {
            checked.work = Work::new(u64::MAX);
            let mut actual: [Option<(&str, Repeats)>; 3] = [None; 3];
            let mut length = 0;
            let mut outcome = None;
            let allocations = allocations_during(|| {
                outcome = Some(visit_original(
                    &view,
                    image,
                    &mut checked,
                    |key, value, _| {
                        actual[length] = Some((key.name().as_ref(), value.repeats));
                        length += 1;
                        Ok(())
                    },
                ));
            });
            assert_eq!(allocations, 0);
            assert_eq!(outcome.unwrap(), Ok(()));
            assert_eq!(length, 3);
            match image {
                Image::Current => {
                    assert_eq!(
                        actual,
                        [
                            Some(("a", Repeats::Exactly(7))),
                            Some(("b", Repeats::Indefinitely)),
                            Some(("e", Repeats::Indefinitely)),
                        ]
                    );
                    assert_eq!(checked.work.observed.setup, 1);
                    assert_eq!(checked.work.observed.next, 4);
                }
                Image::Predecessor => {
                    assert_eq!(
                        actual,
                        [
                            Some(("a", Repeats::Indefinitely)),
                            Some(("c", Repeats::Indefinitely)),
                            Some(("e", Repeats::Indefinitely)),
                        ]
                    );
                    assert_eq!(checked.work.observed.setup, 2);
                    // All three current and all five undo rows, plus both terminals.
                    assert_eq!(checked.work.observed.next, 10);
                }
            }
        }
    }
    assert_eq!(view.current().len(), 3);
    assert_eq!(view.undo().len(), 5);
    assert_eq!(
        view.undo()
            .iter()
            .filter(|(_, value)| value.is_none())
            .count(),
        2
    );
    assert_eq!(
        view.undo()
            .iter()
            .filter(|(_, value)| value.is_some())
            .count(),
        3
    );
    assert_eq!(
        view.undo()
            .get(&"e".parse().unwrap())
            .unwrap()
            .as_ref()
            .unwrap()
            .repeats,
        view.current().get(&"e".parse().unwrap()).unwrap().repeats
    );
    assert_eq!(pool.reserved_bytes(), 0);
    assert_eq!(pool.peak_reserved_bytes(), 0);
}

#[test]
fn cold_and_warm_borrowed_key_comparisons_and_fixed_counter_tails_do_not_allocate() {
    use crate::test_allocations::allocations_during;
    let left: TriggerId = "α".repeat(64).parse().unwrap();
    let right: TriggerId = "β".repeat(64).parse().unwrap();
    let hash =
        HashOf::<IvmBytecode>::from_untyped_unchecked(Hash::from_marked_bytes([1; 32]).unwrap());
    let other =
        HashOf::<IvmBytecode>::from_untyped_unchecked(Hash::from_marked_bytes([3; 32]).unwrap());
    let pool = AllocationBudget::new(16 * 1024 * 1024);
    let mut checked = strategy(u64::MAX, 2, &pool);
    checked.counts.push_reserved(CounterCell { hash, count: 1 });
    checked.counts.push_reserved(CounterCell {
        hash: other,
        count: 1,
    });
    let pointer = checked.counts.as_slice().as_ptr();
    let exact_backing = std::alloc::Layout::array::<CounterCell>(2).unwrap().size();
    assert_eq!(pool.reserved_bytes(), exact_backing);
    assert_allocator_census_positive_control();
    for _warm in [false, true] {
        // Complete UTF8 128+128 and seven events, plus three full hash comparisons.
        let mut work = Work::new(464);
        let mut comparisons = None;
        let allocations = allocations_during(|| {
            comparisons = Some((
                left.compare(&right, &mut work),
                hash.compare(&other, &mut work),
                work.hash_equal(&hash, &hash),
                work.hash_equal(&hash, &other),
            ));
        });
        assert_eq!(allocations, 0);
        assert_eq!(
            comparisons.unwrap(),
            (Ok(Ordering::Less), Ok(Ordering::Less), Ok(true), Ok(false))
        );
        assert_eq!(work.observed.compare, 4);
        assert_eq!(work.remaining, 0);

        // Two full cells after an early match:181 increment+189 consume+25 empty.
        checked.work = Work::new(395);
        checked.counts.as_mut_slice()[0].count = 1;
        checked.counts.as_mut_slice()[1].count = 1;
        let expected = NonZeroU64::new(2).unwrap();
        let mut outcomes = None;
        let allocations = allocations_during(|| {
            outcomes = Some((
                checked.increment(&hash),
                checked.count_matches(&hash, &expected),
                checked.empty(),
            ));
        });
        assert_eq!(allocations, 0);
        assert_eq!(outcomes.unwrap(), (Ok(()), Ok(true), Ok(false)));
        assert_eq!(checked.work.observed.compare, 4);
        assert_eq!(checked.work.remaining, 0);
        assert_eq!(checked.counts.as_slice()[0].count, 0);
        assert_eq!(checked.counts.as_slice()[1].count, 1);
        assert_eq!(checked.counts.as_slice().as_ptr(), pointer);
        assert_eq!(pool.reserved_bytes(), exact_backing);
    }
    drop(checked);
    assert_eq!(pool.reserved_bytes(), 0);
}

#[test]
fn cold_and_warm_shipping_typed_and_deployable_hashes_do_not_allocate() {
    use crate::test_allocations::allocations_during;
    // No fixture or expected hash runs on either measured thread before its
    // first shipping call. Each worker reuses the same strategy for its warm call.
    let typed_blob = IvmBytecode::from_compiled(vec![1, 2, 3]);
    std::thread::spawn(move || {
        assert!(
            !norito::debug_trace_enabled(),
            "allocator control requires ordinary tracing off"
        );
        let pool = AllocationBudget::new(0);
        let mut checked = strategy(u64::MAX, 0, &pool);
        assert_allocator_census_positive_control();
        let mut actual = [None, None];
        for (index, slot) in actual.iter_mut().enumerate() {
            let mut outcome = None;
            let allocations = allocations_during(|| {
                outcome = Some(checked.lookup_hash(&typed_blob));
            });
            assert_eq!(allocations, 0);
            *slot = Some(outcome.unwrap().unwrap());
            assert_eq!(checked.work.observed.typed, index + 1);
            assert_eq!(checked.work.observed.deploy, 0);
        }
        // Only now may the expected canonical hash perform the same codec work.
        let expected = HashOf::new(&typed_blob);
        assert_eq!(actual, [Some(expected), Some(expected)]);
        assert_eq!(pool.reserved_bytes(), 0);
        assert_eq!(pool.peak_reserved_bytes(), 0);
    })
    .join()
    .unwrap();
    let deployable_blob = IvmBytecode::from_compiled(vec![1, 2, 3]);
    std::thread::spawn(move || {
        let pool = AllocationBudget::new(0);
        let mut checked = strategy(u64::MAX, 0, &pool);
        assert_allocator_census_positive_control();
        let mut actual = [None, None];
        for (index, slot) in actual.iter_mut().enumerate() {
            let mut outcome = None;
            let allocations = allocations_during(|| {
                outcome = Some(checked.code_hash(&deployable_blob));
            });
            assert_eq!(allocations, 0);
            *slot = Some(outcome.unwrap().unwrap());
            assert_eq!(checked.work.observed.deploy, index + 1);
            assert_eq!(checked.work.observed.typed, 0);
        }
        let expected = ivm::contract_code_hash(deployable_blob.as_ref());
        assert_eq!(actual, [Some(expected), Some(expected)]);
        assert_eq!(pool.reserved_bytes(), 0);
        assert_eq!(pool.peak_reserved_bytes(), 0);
    })
    .join()
    .unwrap();
}

#[test]
fn exact_counter_backing_allocator_refusal_refunds_and_retries_the_original_pool() {
    use crate::test_allocations::refuse_one_layout_during;
    let (set, _) = super::tests::fixture();
    let data = set.data_triggers.try_committed_view_nonblocking().unwrap();
    let pipeline = set
        .pipeline_triggers
        .try_committed_view_nonblocking()
        .unwrap();
    let time = set.time_triggers.try_committed_view_nonblocking().unwrap();
    let by_call = set
        .by_call_triggers
        .try_committed_view_nonblocking()
        .unwrap();
    let contracts = set.contracts.try_committed_view_nonblocking().unwrap();
    let sources = NativeSources {
        data: &data,
        pipeline: &pipeline,
        time: &time,
        by_call: &by_call,
        contracts: &contracts,
    };
    let pool = AllocationBudget::new(16 * 1024 * 1024);
    let layout = std::alloc::Layout::array::<CounterCell>(1).unwrap();
    let (outcome, observed) = refuse_one_layout_during(layout, || {
        CheckedStrategy::prepare(&sources, u64::MAX, &pool)
    });
    assert!(observed);
    match outcome {
        Err(TriggerContractError::Allocator { requested_bytes }) => {
            assert_eq!(requested_bytes, layout.size());
        }
        _ => panic!("the exact admitted CounterCell allocation must be refused"),
    }
    assert_eq!(pool.reserved_bytes(), 0);
    assert_eq!(pool.peak_reserved_bytes(), layout.size());
    // The exact refusal guard has dropped: a genuine retry retains the same pool.
    let retry = CheckedStrategy::prepare(&sources, u64::MAX, &pool).unwrap();
    assert_eq!(retry.counts.capacity(), 1);
    assert_eq!(pool.reserved_bytes(), layout.size());
    assert_eq!(pool.peak_reserved_bytes(), layout.size());
    drop(retry);
    assert_eq!(pool.reserved_bytes(), 0);
    assert_allocator_census_positive_control();
}
