//! Immutable compiler-captured identities for this source owner’s existing codecs.

#[test]
fn captured_codec_schema_identities() {
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyReleaseStageV1>(
        "iroha_data_model::privacy::release_manifest::PrivacyReleaseStageV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyReleaseExecutableKindV1>(
        "iroha_data_model::privacy::release_manifest::PrivacyReleaseExecutableKindV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyReleaseSdkConsumerV1>(
        "iroha_data_model::privacy::release_manifest::PrivacyReleaseSdkConsumerV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyReleaseHardwareBackendV1>(
        "iroha_data_model::privacy::release_manifest::PrivacyReleaseHardwareBackendV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyReleaseAuditClassV1>(
        "iroha_data_model::privacy::release_manifest::PrivacyReleaseAuditClassV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyReleaseSignatureRoleV1>(
        "iroha_data_model::privacy::release_manifest::PrivacyReleaseSignatureRoleV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyReleaseSourceIdentityV1>(
        "iroha_data_model::privacy::release_manifest::PrivacyReleaseSourceIdentityV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyReleaseExecutableArtifactV1>(
        "iroha_data_model::privacy::release_manifest::PrivacyReleaseExecutableArtifactV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyReleaseProtocolBindingV1>(
        "iroha_data_model::privacy::release_manifest::PrivacyReleaseProtocolBindingV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyReleaseStageReceiptV1>(
        "iroha_data_model::privacy::release_manifest::PrivacyReleaseStageReceiptV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyReleaseProofArtifactV1>(
        "iroha_data_model::privacy::release_manifest::PrivacyReleaseProofArtifactV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyReleaseSdkPackageV1>(
        "iroha_data_model::privacy::release_manifest::PrivacyReleaseSdkPackageV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyReleaseHardwareResultV1>(
        "iroha_data_model::privacy::release_manifest::PrivacyReleaseHardwareResultV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyAcceptedMediumDispositionV1>(
        "iroha_data_model::privacy::release_manifest::PrivacyAcceptedMediumDispositionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyReleaseAuditV1>(
        "iroha_data_model::privacy::release_manifest::PrivacyReleaseAuditV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyReleaseSignatureV1>(
        "iroha_data_model::privacy::release_manifest::PrivacyReleaseSignatureV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyExact12ReleaseManifestV1>(
        "iroha_data_model::privacy::release_manifest::PrivacyExact12ReleaseManifestV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyDeploymentActivationV1>(
        "iroha_data_model::privacy::release_manifest::PrivacyDeploymentActivationV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyDeploymentValidatorCanaryV1>(
        "iroha_data_model::privacy::release_manifest::PrivacyDeploymentValidatorCanaryV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::PrivacyDeploymentValidatorSignatureV1,
    >("iroha_data_model::privacy::release_manifest::PrivacyDeploymentValidatorSignatureV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::PrivacyExact12DeploymentQualificationV1,
    >("iroha_data_model::privacy::release_manifest::PrivacyExact12DeploymentQualificationV1");
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyExact12QualificationRecordV1>(
        "iroha_data_model::privacy::release_manifest::PrivacyExact12QualificationRecordV1",
    );
    crate::captured_schema_tests::assert_serialize::<super::ReleaseSignaturePayloadV1>(
        "iroha_data_model::privacy::release_manifest::ReleaseSignaturePayloadV1",
    );
    crate::captured_schema_tests::assert_serialize::<super::AuditSignaturePayloadV1>(
        "iroha_data_model::privacy::release_manifest::AuditSignaturePayloadV1",
    );
    crate::captured_schema_tests::assert_serialize::<super::MediumDispositionSignaturePayloadV1>(
        "iroha_data_model::privacy::release_manifest::MediumDispositionSignaturePayloadV1",
    );
    crate::captured_schema_tests::assert_serialize::<super::DeploymentSignaturePayloadV1>(
        "iroha_data_model::privacy::release_manifest::DeploymentSignaturePayloadV1",
    );
}
