//! Immutable compiler-captured identities for this source owner’s existing codecs.

const CASES: &[crate::captured_schema_tests::Case] = &[
    crate::captured_schema_tests::Case::bidirectional::<super::CreateParliamentGovernanceAttemptV1>(
        "iroha_data_model::isi::governance::parliament::CreateParliamentGovernanceAttemptV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ParliamentEscalateRiskV1>(
        "iroha_data_model::isi::governance::parliament::ParliamentEscalateRiskV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<
        super::ParliamentSortitionRequestRegistrationV1,
    >("iroha_data_model::isi::governance::parliament::ParliamentSortitionRequestRegistrationV1"),
    crate::captured_schema_tests::Case::bidirectional::<super::ParliamentRegisterSortitionRequestV1>(
        "iroha_data_model::isi::governance::parliament::ParliamentRegisterSortitionRequestV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<
        super::ParliamentConsumeSortitionPulseBatchV1,
    >("iroha_data_model::isi::governance::parliament::ParliamentConsumeSortitionPulseBatchV1"),
    crate::captured_schema_tests::Case::bidirectional::<super::ParliamentBeginInvitationAcceptanceV1>(
        "iroha_data_model::isi::governance::parliament::ParliamentBeginInvitationAcceptanceV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ParliamentFailBodyElectionNoRosterV1>(
        "iroha_data_model::isi::governance::parliament::ParliamentFailBodyElectionNoRosterV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ParliamentInvitationDecisionV1>(
        "iroha_data_model::isi::governance::parliament::ParliamentInvitationDecisionV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ParliamentRecordInvitationResponseV1>(
        "iroha_data_model::isi::governance::parliament::ParliamentRecordInvitationResponseV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ParliamentSealBodyRosterV1>(
        "iroha_data_model::isi::governance::parliament::ParliamentSealBodyRosterV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ParliamentAdvanceBodyPhaseV1>(
        "iroha_data_model::isi::governance::parliament::ParliamentAdvanceBodyPhaseV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ParliamentRecordAttemptAbsenceV1>(
        "iroha_data_model::isi::governance::parliament::ParliamentRecordAttemptAbsenceV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ParliamentEndorsePublicFindingV1>(
        "iroha_data_model::isi::governance::parliament::ParliamentEndorsePublicFindingV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ParliamentFailPublicFindingNoResultV1>(
        "iroha_data_model::isi::governance::parliament::ParliamentFailPublicFindingNoResultV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ParliamentRegisterBallotAttemptV1>(
        "iroha_data_model::isi::governance::parliament::ParliamentRegisterBallotAttemptV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ParliamentRegisterBallotParticipantV1>(
        "iroha_data_model::isi::governance::parliament::ParliamentRegisterBallotParticipantV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ParliamentCloseBallotRegistrationV1>(
        "iroha_data_model::isi::governance::parliament::ParliamentCloseBallotRegistrationV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ParliamentRecordBallotDropoutV1>(
        "iroha_data_model::isi::governance::parliament::ParliamentRecordBallotDropoutV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ParliamentFreezeBallotSurvivorsV1>(
        "iroha_data_model::isi::governance::parliament::ParliamentFreezeBallotSurvivorsV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ParliamentFreezeTimedOvnCorpusV1>(
        "iroha_data_model::isi::governance::parliament::ParliamentFreezeTimedOvnCorpusV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ParliamentBeginBallotOpeningBatchV1>(
        "iroha_data_model::isi::governance::parliament::ParliamentBeginBallotOpeningBatchV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ParliamentFailBallotNoResultV1>(
        "iroha_data_model::isi::governance::parliament::ParliamentFailBallotNoResultV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ParliamentTleFinalReleaseSignatureV1>(
        "iroha_data_model::isi::governance::parliament::ParliamentTleFinalReleaseSignatureV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ParliamentFinalizeOpenedBallotV1>(
        "iroha_data_model::isi::governance::parliament::ParliamentFinalizeOpenedBallotV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ParliamentAutomaticSupersededV1>(
        "iroha_data_model::isi::governance::parliament::ParliamentAutomaticSupersededV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ParliamentAutomaticExecutionFailedV1>(
        "iroha_data_model::isi::governance::parliament::ParliamentAutomaticExecutionFailedV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ParliamentAutomaticExecutionOutcomeV1>(
        "iroha_data_model::isi::governance::parliament::ParliamentAutomaticExecutionOutcomeV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ParliamentLifecycleTransitionV1>(
        "iroha_data_model::isi::governance::parliament::ParliamentLifecycleTransitionV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ParliamentLifecycleTransitionKindV1>(
        "iroha_data_model::isi::governance::parliament::ParliamentLifecycleTransitionKindV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SubmitParliamentLifecycleTransitionV1>(
        "iroha_data_model::isi::governance::parliament::SubmitParliamentLifecycleTransitionV1",
    ),
];

#[test]
fn captured_codec_schema_identities() {
    for case in CASES {
        case.check();
    }
}
