[package]
name = "zk_ace_prover"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
iroha_model_base = { workspace = true }
iroha_core_privacy = { workspace = true, default-features = false, features = ["zk-stark"] }
iroha_crypto = { workspace = true, features = ["consensus", "json", "gost", "sm"], default-features = false }
iroha_data_model = { workspace = true, features = ["application-model", "transparent_api", "governance", "http"], default-features = false }
norito = { workspace = true, default-features = false, features = ["node-codec"] }
