//! Immutable compiler-captured identities for this source owner’s existing codecs.

#[test]
fn captured_codec_schema_identities() {
    crate::captured_schema_tests::assert_bidirectional::<super::DeploySoracloudService>(
        "iroha_data_model::isi::soracloud::DeploySoracloudService",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::UpgradeSoracloudService>(
        "iroha_data_model::isi::soracloud::UpgradeSoracloudService",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::DeploySoracloudAppInfra>(
        "iroha_data_model::isi::soracloud::DeploySoracloudAppInfra",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::UpgradeSoracloudAppInfra>(
        "iroha_data_model::isi::soracloud::UpgradeSoracloudAppInfra",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::RollbackSoracloudService>(
        "iroha_data_model::isi::soracloud::RollbackSoracloudService",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SetSoracloudServiceConfig>(
        "iroha_data_model::isi::soracloud::SetSoracloudServiceConfig",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::DeleteSoracloudServiceConfig>(
        "iroha_data_model::isi::soracloud::DeleteSoracloudServiceConfig",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SetSoracloudServiceSecret>(
        "iroha_data_model::isi::soracloud::SetSoracloudServiceSecret",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::DeleteSoracloudServiceSecret>(
        "iroha_data_model::isi::soracloud::DeleteSoracloudServiceSecret",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MutateSoracloudState>(
        "iroha_data_model::isi::soracloud::MutateSoracloudState",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::RegisterSoracloudFhePolicy>(
        "iroha_data_model::isi::soracloud::RegisterSoracloudFhePolicy",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::RotateSoracloudFhePolicy>(
        "iroha_data_model::isi::soracloud::RotateSoracloudFhePolicy",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::RevokeSoracloudFhePolicy>(
        "iroha_data_model::isi::soracloud::RevokeSoracloudFhePolicy",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::RunSoracloudFheJob>(
        "iroha_data_model::isi::soracloud::RunSoracloudFheJob",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::RecordSoracloudDecryptionRequest>(
        "iroha_data_model::isi::soracloud::RecordSoracloudDecryptionRequest",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::JoinSoracloudHfSharedLease>(
        "iroha_data_model::isi::soracloud::JoinSoracloudHfSharedLease",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::LeaveSoracloudHfSharedLease>(
        "iroha_data_model::isi::soracloud::LeaveSoracloudHfSharedLease",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::RenewSoracloudHfSharedLease>(
        "iroha_data_model::isi::soracloud::RenewSoracloudHfSharedLease",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AdvertiseSoracloudInrouHost>(
        "iroha_data_model::isi::soracloud::AdvertiseSoracloudInrouHost",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::WithdrawSoracloudInrouHost>(
        "iroha_data_model::isi::soracloud::WithdrawSoracloudInrouHost",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ReconcileSoracloudInrouPlacements>(
        "iroha_data_model::isi::soracloud::ReconcileSoracloudInrouPlacements",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::DeploySoracloudAgentApartment>(
        "iroha_data_model::isi::soracloud::DeploySoracloudAgentApartment",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::RenewSoracloudAgentLease>(
        "iroha_data_model::isi::soracloud::RenewSoracloudAgentLease",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::RestartSoracloudAgentApartment>(
        "iroha_data_model::isi::soracloud::RestartSoracloudAgentApartment",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::RevokeSoracloudAgentPolicy>(
        "iroha_data_model::isi::soracloud::RevokeSoracloudAgentPolicy",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::RequestSoracloudAgentWalletSpend>(
        "iroha_data_model::isi::soracloud::RequestSoracloudAgentWalletSpend",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ApproveSoracloudAgentWalletSpend>(
        "iroha_data_model::isi::soracloud::ApproveSoracloudAgentWalletSpend",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::EnqueueSoracloudAgentMessage>(
        "iroha_data_model::isi::soracloud::EnqueueSoracloudAgentMessage",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AcknowledgeSoracloudAgentMessage>(
        "iroha_data_model::isi::soracloud::AcknowledgeSoracloudAgentMessage",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AllowSoracloudAgentAutonomyArtifact>(
        "iroha_data_model::isi::soracloud::AllowSoracloudAgentAutonomyArtifact",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::RunSoracloudAgentAutonomy>(
        "iroha_data_model::isi::soracloud::RunSoracloudAgentAutonomy",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::RecordSoracloudAgentAutonomyExecution,
    >("iroha_data_model::isi::soracloud::RecordSoracloudAgentAutonomyExecution");
    crate::captured_schema_tests::assert_bidirectional::<super::StartSoracloudTrainingJob>(
        "iroha_data_model::isi::soracloud::StartSoracloudTrainingJob",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::CheckpointSoracloudTrainingJob>(
        "iroha_data_model::isi::soracloud::CheckpointSoracloudTrainingJob",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::RetrySoracloudTrainingJob>(
        "iroha_data_model::isi::soracloud::RetrySoracloudTrainingJob",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::RegisterSoracloudModelArtifact>(
        "iroha_data_model::isi::soracloud::RegisterSoracloudModelArtifact",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::RegisterSoracloudModelWeight>(
        "iroha_data_model::isi::soracloud::RegisterSoracloudModelWeight",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PromoteSoracloudModelWeight>(
        "iroha_data_model::isi::soracloud::PromoteSoracloudModelWeight",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::RollbackSoracloudModelWeight>(
        "iroha_data_model::isi::soracloud::RollbackSoracloudModelWeight",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::RegisterSoracloudUploadedModelBundle>(
        "iroha_data_model::isi::soracloud::RegisterSoracloudUploadedModelBundle",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FinalizeSoracloudUploadedModelBundle>(
        "iroha_data_model::isi::soracloud::FinalizeSoracloudUploadedModelBundle",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AdvanceSoracloudRollout>(
        "iroha_data_model::isi::soracloud::AdvanceSoracloudRollout",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SetSoracloudRuntimeState>(
        "iroha_data_model::isi::soracloud::SetSoracloudRuntimeState",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SetSoracloudInrouReplicaRuntimeState>(
        "iroha_data_model::isi::soracloud::SetSoracloudInrouReplicaRuntimeState",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::ClearSoracloudInrouReplicaRuntimeState,
    >("iroha_data_model::isi::soracloud::ClearSoracloudInrouReplicaRuntimeState");
    crate::captured_schema_tests::assert_bidirectional::<super::ReportSoracloudServiceLeaseUsage>(
        "iroha_data_model::isi::soracloud::ReportSoracloudServiceLeaseUsage",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::RecordSoracloudMailboxMessage>(
        "iroha_data_model::isi::soracloud::RecordSoracloudMailboxMessage",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::RecordSoracloudRuntimeReceipt>(
        "iroha_data_model::isi::soracloud::RecordSoracloudRuntimeReceipt",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ApplySoracloudOrderedMailboxResult>(
        "iroha_data_model::isi::soracloud::ApplySoracloudOrderedMailboxResult",
    );
}
