//! Immutable compiler-captured identities for this source owner’s existing codecs.

const CASES: &[crate::captured_schema_tests::Case] = &[
    crate::captured_schema_tests::Case::bidirectional::<super::DeploySoracloudService>(
        "iroha_data_model::isi::soracloud::DeploySoracloudService",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::UpgradeSoracloudService>(
        "iroha_data_model::isi::soracloud::UpgradeSoracloudService",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::DeploySoracloudAppInfra>(
        "iroha_data_model::isi::soracloud::DeploySoracloudAppInfra",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::UpgradeSoracloudAppInfra>(
        "iroha_data_model::isi::soracloud::UpgradeSoracloudAppInfra",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RollbackSoracloudService>(
        "iroha_data_model::isi::soracloud::RollbackSoracloudService",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SetSoracloudServiceConfig>(
        "iroha_data_model::isi::soracloud::SetSoracloudServiceConfig",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::DeleteSoracloudServiceConfig>(
        "iroha_data_model::isi::soracloud::DeleteSoracloudServiceConfig",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SetSoracloudServiceSecret>(
        "iroha_data_model::isi::soracloud::SetSoracloudServiceSecret",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::DeleteSoracloudServiceSecret>(
        "iroha_data_model::isi::soracloud::DeleteSoracloudServiceSecret",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MutateSoracloudState>(
        "iroha_data_model::isi::soracloud::MutateSoracloudState",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RegisterSoracloudFhePolicy>(
        "iroha_data_model::isi::soracloud::RegisterSoracloudFhePolicy",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RotateSoracloudFhePolicy>(
        "iroha_data_model::isi::soracloud::RotateSoracloudFhePolicy",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RevokeSoracloudFhePolicy>(
        "iroha_data_model::isi::soracloud::RevokeSoracloudFhePolicy",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RunSoracloudFheJob>(
        "iroha_data_model::isi::soracloud::RunSoracloudFheJob",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RecordSoracloudDecryptionRequest>(
        "iroha_data_model::isi::soracloud::RecordSoracloudDecryptionRequest",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::JoinSoracloudHfSharedLease>(
        "iroha_data_model::isi::soracloud::JoinSoracloudHfSharedLease",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::LeaveSoracloudHfSharedLease>(
        "iroha_data_model::isi::soracloud::LeaveSoracloudHfSharedLease",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RenewSoracloudHfSharedLease>(
        "iroha_data_model::isi::soracloud::RenewSoracloudHfSharedLease",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AdvertiseSoracloudInrouHost>(
        "iroha_data_model::isi::soracloud::AdvertiseSoracloudInrouHost",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::WithdrawSoracloudInrouHost>(
        "iroha_data_model::isi::soracloud::WithdrawSoracloudInrouHost",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ReconcileSoracloudInrouPlacements>(
        "iroha_data_model::isi::soracloud::ReconcileSoracloudInrouPlacements",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::DeploySoracloudAgentApartment>(
        "iroha_data_model::isi::soracloud::DeploySoracloudAgentApartment",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RenewSoracloudAgentLease>(
        "iroha_data_model::isi::soracloud::RenewSoracloudAgentLease",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RestartSoracloudAgentApartment>(
        "iroha_data_model::isi::soracloud::RestartSoracloudAgentApartment",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RevokeSoracloudAgentPolicy>(
        "iroha_data_model::isi::soracloud::RevokeSoracloudAgentPolicy",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RequestSoracloudAgentWalletSpend>(
        "iroha_data_model::isi::soracloud::RequestSoracloudAgentWalletSpend",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ApproveSoracloudAgentWalletSpend>(
        "iroha_data_model::isi::soracloud::ApproveSoracloudAgentWalletSpend",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::EnqueueSoracloudAgentMessage>(
        "iroha_data_model::isi::soracloud::EnqueueSoracloudAgentMessage",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AcknowledgeSoracloudAgentMessage>(
        "iroha_data_model::isi::soracloud::AcknowledgeSoracloudAgentMessage",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AllowSoracloudAgentAutonomyArtifact>(
        "iroha_data_model::isi::soracloud::AllowSoracloudAgentAutonomyArtifact",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RunSoracloudAgentAutonomy>(
        "iroha_data_model::isi::soracloud::RunSoracloudAgentAutonomy",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RecordSoracloudAgentAutonomyExecution>(
        "iroha_data_model::isi::soracloud::RecordSoracloudAgentAutonomyExecution",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::StartSoracloudTrainingJob>(
        "iroha_data_model::isi::soracloud::StartSoracloudTrainingJob",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::CheckpointSoracloudTrainingJob>(
        "iroha_data_model::isi::soracloud::CheckpointSoracloudTrainingJob",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RetrySoracloudTrainingJob>(
        "iroha_data_model::isi::soracloud::RetrySoracloudTrainingJob",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RegisterSoracloudModelArtifact>(
        "iroha_data_model::isi::soracloud::RegisterSoracloudModelArtifact",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RegisterSoracloudModelWeight>(
        "iroha_data_model::isi::soracloud::RegisterSoracloudModelWeight",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::PromoteSoracloudModelWeight>(
        "iroha_data_model::isi::soracloud::PromoteSoracloudModelWeight",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RollbackSoracloudModelWeight>(
        "iroha_data_model::isi::soracloud::RollbackSoracloudModelWeight",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RegisterSoracloudUploadedModelBundle>(
        "iroha_data_model::isi::soracloud::RegisterSoracloudUploadedModelBundle",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::FinalizeSoracloudUploadedModelBundle>(
        "iroha_data_model::isi::soracloud::FinalizeSoracloudUploadedModelBundle",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AdvanceSoracloudRollout>(
        "iroha_data_model::isi::soracloud::AdvanceSoracloudRollout",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SetSoracloudRuntimeState>(
        "iroha_data_model::isi::soracloud::SetSoracloudRuntimeState",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SetSoracloudInrouReplicaRuntimeState>(
        "iroha_data_model::isi::soracloud::SetSoracloudInrouReplicaRuntimeState",
    ),
    crate::captured_schema_tests::Case::bidirectional::<
        super::ClearSoracloudInrouReplicaRuntimeState,
    >("iroha_data_model::isi::soracloud::ClearSoracloudInrouReplicaRuntimeState"),
    crate::captured_schema_tests::Case::bidirectional::<super::ReportSoracloudServiceLeaseUsage>(
        "iroha_data_model::isi::soracloud::ReportSoracloudServiceLeaseUsage",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RecordSoracloudMailboxMessage>(
        "iroha_data_model::isi::soracloud::RecordSoracloudMailboxMessage",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RecordSoracloudRuntimeReceipt>(
        "iroha_data_model::isi::soracloud::RecordSoracloudRuntimeReceipt",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ApplySoracloudOrderedMailboxResult>(
        "iroha_data_model::isi::soracloud::ApplySoracloudOrderedMailboxResult",
    ),
];

#[test]
fn captured_codec_schema_identities() {
    for case in CASES {
        case.check();
    }
}
