[Unit]
Requires=sorafs-external-software-signer@proof-outcome.service
Requires=sorafs-external-software-signer@repair.service
Requires=sorafs-external-software-signer@reserve.service
Requires=sorafs-external-software-signer@orderbook.service
After=sorafs-external-software-signer@proof-outcome.service
After=sorafs-external-software-signer@repair.service
After=sorafs-external-software-signer@reserve.service
After=sorafs-external-software-signer@orderbook.service

[Service]
ReadOnlyPaths=/etc/sorafs/signers /run/sorafs-signers
