use manyhow::{Emitter, emit};
use proc_macro2::TokenStream;
use quote::{ToTokens, quote};
use syn::{Attribute, parse_quote};
/// Implementation of the `#[model]` attribute.
pub fn impl_model(emitter: &mut Emitter, input: &syn::ItemMod) -> TokenStream {
    let syn::ItemMod {
        attrs,
        vis,
        mod_token,
        ident,
        content,
        semi,
        ..
    } = input;
    if *vis != syn::Visibility::Inherited {
        emit!(
            emitter,
            input,
            "The `model` attribute can only be used on private modules",
        );
        return quote!();
    }
    if ident != "model" {
        emit!(
            emitter,
            input,
            "The `model` attribute can only be used on the `model` module",
        );
    }
    let items_code = if let Some((_, items)) = content {
        items
            .iter()
            .map(|item| process_item(item.clone()))
            .collect::<Vec<_>>()
    } else {
        Vec::new()
    };
    quote! {
        #(#attrs)*
        #[doc = "Public model items generated by the `#[model]` attribute."]
        #mod_token #ident {
            use ::norito::json::{JsonDeserialize, JsonSerialize};
            #(#items_code)*
        }#semi
    }
}
pub fn process_item(item: syn::Item) -> TokenStream {
    let mut input: syn::DeriveInput = match item {
        syn::Item::Struct(item_struct) => item_struct.into(),
        syn::Item::Enum(item_enum) => item_enum.into(),
        syn::Item::Union(item_union) => item_union.into(),
        other => return other.into_token_stream(),
    };
    // Expose items so that they can be re-exported.
    input.vis = parse_quote!(pub);
    process_pub_item(input)
}
fn process_pub_item(input: syn::DeriveInput) -> TokenStream {
    let ident = input.ident;
    let attrs = input.attrs;
    let generics = input.generics;
    match input.data {
        syn::Data::Struct(item) => process_struct(item, &ident, &generics, attrs),
        syn::Data::Enum(item) => process_enum(item, &ident, &generics, attrs),
        syn::Data::Union(item) => process_union(item, &ident, &generics, attrs),
    }
}
fn process_struct(
    mut item: syn::DataStruct,
    ident: &syn::Ident,
    generics: &syn::Generics,
    mut attrs: Vec<syn::Attribute>,
) -> TokenStream {
    let (impl_generics, _, where_clause) = generics.split_for_impl();
    ensure_doc(
        &mut attrs,
        format!("Model struct `{ident}` exported via `#[model]`."),
    );
    match &mut item.fields {
        syn::Fields::Named(fields) => {
            for field in &mut fields.named {
                let name = field
                    .ident
                    .as_ref()
                    .map_or_else(|| "field".to_owned(), ToString::to_string);
                ensure_doc(&mut field.attrs, format!("Field `{name}` for `{ident}`."));
                if matches!(field.vis, syn::Visibility::Public(_))
                    && !cfg!(feature = "transparent_api")
                {
                    field.vis = parse_quote!(pub(crate));
                }
            }
            let fields = &fields.named;
            let item = quote! {
                pub struct #ident #impl_generics #where_clause {
                    #fields
                }
            };
            emit_with_attrs(&attrs, &item)
        }
        syn::Fields::Unnamed(fields) => {
            for (idx, field) in fields.unnamed.iter_mut().enumerate() {
                ensure_doc(&mut field.attrs, format!("Field #{idx} for `{ident}`."));
                if matches!(field.vis, syn::Visibility::Public(_))
                    && !cfg!(feature = "transparent_api")
                {
                    field.vis = parse_quote!(pub(crate));
                }
            }
            let fields = &fields.unnamed;
            let item = quote! {
                pub struct #ident #impl_generics( #fields ) #where_clause;
            };
            emit_with_attrs(&attrs, &item)
        }
        syn::Fields::Unit => {
            let item = quote! {
                pub struct #ident #impl_generics #where_clause;
            };
            emit_with_attrs(&attrs, &item)
        }
    }
}
fn process_enum(
    mut item: syn::DataEnum,
    ident: &syn::Ident,
    generics: &syn::Generics,
    mut attrs: Vec<syn::Attribute>,
) -> TokenStream {
    let (impl_generics, _, where_clause) = generics.split_for_impl();
    ensure_doc(
        &mut attrs,
        format!("Model enum `{ident}` exported via `#[model]`."),
    );
    for variant in &mut item.variants {
        ensure_doc(
            &mut variant.attrs,
            format!("Variant `{}` of `{ident}`.", variant.ident),
        );
        ensure_field_docs(&mut variant.fields, ident, Some(&variant.ident));
    }
    let variants = item.variants;
    let item = quote! {
        pub enum #ident #impl_generics #where_clause {
            #variants
        }
    };
    emit_with_attrs(&attrs, &item)
}
fn process_union(
    mut item: syn::DataUnion,
    ident: &syn::Ident,
    generics: &syn::Generics,
    mut attrs: Vec<syn::Attribute>,
) -> TokenStream {
    let (impl_generics, _, where_clause) = generics.split_for_impl();
    ensure_doc(
        &mut attrs,
        format!("Model union `{ident}` exported via `#[model]`."),
    );
    for field in &mut item.fields.named {
        if matches!(field.vis, syn::Visibility::Public(_)) && !cfg!(feature = "transparent_api") {
            field.vis = parse_quote!(pub(crate));
        }
        let name = field
            .ident
            .as_ref()
            .map_or_else(|| "field".to_owned(), ToString::to_string);
        ensure_doc(
            &mut field.attrs,
            format!("Field `{name}` for union `{ident}`."),
        );
    }
    let fields = item.fields.named.iter();
    let item = quote! {
        pub union #ident #impl_generics #where_clause {
            #(#fields),*
        }
    };
    emit_with_attrs(&attrs, &item)
}
fn emit_with_attrs(attrs: &[syn::Attribute], item: &TokenStream) -> TokenStream {
    quote! {
        #(#attrs)*
        #item
    }
}
fn ensure_doc(attrs: &mut Vec<Attribute>, default: impl AsRef<str>) {
    let has_doc = attrs.iter().any(|attr| attr.path().is_ident("doc"));
    if !has_doc {
        let doc = default.as_ref();
        attrs.push(parse_quote!(#[doc = #doc]));
    }
}
fn ensure_field_docs(fields: &mut syn::Fields, owner: &syn::Ident, variant: Option<&syn::Ident>) {
    match fields {
        syn::Fields::Named(named) => {
            for field in &mut named.named {
                let name = field
                    .ident
                    .as_ref()
                    .map_or_else(|| "field".to_owned(), ToString::to_string);
                let context = variant.map_or_else(
                    || format!("`{owner}`"),
                    |variant| format!("variant `{variant}` in `{owner}`"),
                );
                ensure_doc(&mut field.attrs, format!("Field `{name}` for {context}."));
            }
        }
        syn::Fields::Unnamed(unnamed) => {
            for (idx, field) in unnamed.unnamed.iter_mut().enumerate() {
                let context = variant.map_or_else(
                    || format!("`{owner}`"),
                    |variant| format!("variant `{variant}` in `{owner}`"),
                );
                ensure_doc(&mut field.attrs, format!("Field #{idx} for {context}."));
            }
        }
        syn::Fields::Unit => {}
    }
}
#[cfg(test)]
mod tests {
    use super::*;
    use syn::{
        Attribute, Expr, Item, ItemEnum, ItemStruct, ItemUnion, Lit, Visibility, parse_quote,
    };
    fn doc_strings(attrs: &[Attribute]) -> Vec<String> {
        attrs
            .iter()
            .filter_map(|attr| match &attr.meta {
                syn::Meta::NameValue(meta) if meta.path.is_ident("doc") => {
                    if let Expr::Lit(expr) = &meta.value
                        && let Lit::Str(lit) = &expr.lit
                    {
                        return Some(lit.value());
                    }
                    None
                }
                _ => None,
            })
            .collect()
    }
    #[test]
    fn model_json_traits_use_the_protocol_owner_without_feature_gates() {
        let input: syn::ItemMod = parse_quote! {
            mod model {
                struct Value(u32);
            }
        };
        let mut emitter = Emitter::new();
        let output: syn::ItemMod =
            syn::parse2(impl_model(&mut emitter, &input)).expect("model expansion");
        let items = output.content.expect("inline model module").1;
        let Item::Use(import) = &items[0] else {
            panic!("the model injects its JSON traits from their owner");
        };
        assert!(
            import.attrs.is_empty(),
            "protocol imports must be unconditional"
        );
        assert!(import.leading_colon.is_some());
        assert_eq!(
            import.tree.to_token_stream().to_string(),
            quote!(norito::json::{JsonDeserialize, JsonSerialize}).to_string()
        );
    }
    #[test]
    fn struct_fields_documented_and_restricted() {
        let input: syn::DeriveInput = parse_quote! {
            pub struct Sample<'a> {
                pub visible: &'a str,
                hidden: bool,
                pub(crate) crate_visible: u16,
                pub(super) parent_visible: u8,
            }
        };
        let tokens = process_pub_item(input);
        let output: ItemStruct = syn::parse2(tokens).expect("struct output");
        assert!(
            doc_strings(&output.attrs)
                .iter()
                .any(|doc| doc.contains("Model struct `Sample` exported via `#[model]`.")),
            "struct doc missing"
        );
        let fields = match output.fields {
            syn::Fields::Named(fields) => fields.named,
            _ => panic!("expected named fields"),
        };
        assert_eq!(fields.len(), 4);
        for field in fields {
            let name = field.ident.expect("named field").to_string();
            let docs = doc_strings(&field.attrs);
            let expected_fragment = format!("`{name}` for `Sample`");
            assert!(
                docs.iter().any(|doc| doc.contains(&expected_fragment)),
                "missing doc for {name}"
            );
            let expected: Visibility = match name.as_str() {
                "visible" => expected_public_field_visibility(),
                "hidden" => Visibility::Inherited,
                "crate_visible" => parse_quote!(pub(crate)),
                "parent_visible" => parse_quote!(pub(super)),
                _ => panic!("unexpected field {name}"),
            };
            assert_eq!(field.vis, expected, "unexpected visibility for {name}");
        }
    }
    fn expected_public_field_visibility() -> Visibility {
        if cfg!(feature = "transparent_api") {
            parse_quote!(pub)
        } else {
            parse_quote!(pub(crate))
        }
    }
    #[test]
    fn tuple_fields_documented_with_exact_visibility_policy() {
        let input: syn::DeriveInput = parse_quote! {
            pub struct Tuple(pub u32, bool, pub(crate) u16, pub(super) u8);
        };
        let output: ItemStruct = syn::parse2(process_pub_item(input)).expect("tuple output");
        assert!(
            doc_strings(&output.attrs)
                .iter()
                .any(|doc| doc.contains("Model struct `Tuple` exported via `#[model]`.")),
            "tuple doc missing"
        );
        let syn::Fields::Unnamed(fields) = output.fields else {
            panic!("expected tuple fields");
        };
        let expected = [
            expected_public_field_visibility(),
            Visibility::Inherited,
            parse_quote!(pub(crate)),
            parse_quote!(pub(super)),
        ];
        assert_eq!(fields.unnamed.len(), expected.len());
        for (index, (field, expected)) in fields.unnamed.iter().zip(expected).enumerate() {
            assert_eq!(
                field.vis, expected,
                "unexpected tuple field visibility at {index}"
            );
            assert!(
                doc_strings(&field.attrs)
                    .iter()
                    .any(|doc| doc.contains(&format!("Field #{index} for `Tuple`."))),
                "missing tuple field doc at {index}"
            );
        }
    }
    #[test]
    fn enum_variants_and_fields_documented() {
        let input: syn::DeriveInput = parse_quote! {
            pub enum Event {
                Unit,
                Tuple(u32),
                Struct { flag: bool },
            }
        };
        let tokens = process_pub_item(input);
        let output: ItemEnum = syn::parse2(tokens).expect("enum output");
        for variant in &output.variants {
            let docs = doc_strings(&variant.attrs);
            let expected = format!("Variant `{}` of `Event`.", variant.ident);
            assert!(
                docs.iter().any(|doc| doc.contains(&expected)),
                "missing doc for {}",
                variant.ident
            );
        }
        let tuple = output
            .variants
            .iter()
            .find(|variant| variant.ident == "Tuple")
            .expect("Tuple variant");
        match &tuple.fields {
            syn::Fields::Unnamed(fields) => {
                let docs = doc_strings(&fields.unnamed[0].attrs);
                assert!(
                    docs.iter()
                        .any(|doc| doc.contains("Field #0 for variant `Tuple` in `Event`.")),
                    "missing tuple field doc"
                );
            }
            _ => panic!("expected unnamed fields"),
        }
        let named = output
            .variants
            .iter()
            .find(|variant| variant.ident == "Struct")
            .expect("Struct variant");
        match &named.fields {
            syn::Fields::Named(fields) => {
                let docs = doc_strings(&fields.named[0].attrs);
                assert!(
                    docs.iter()
                        .any(|doc| doc.contains("Field `flag` for variant `Struct` in `Event`.")),
                    "missing struct field doc"
                );
            }
            _ => panic!("expected named fields"),
        }
    }
    #[test]
    fn union_fields_documented_and_restricted() {
        let input: syn::DeriveInput = parse_quote! {
            pub union Buffer {
                pub first: u32,
                second: u64,
                pub(crate) crate_visible: u16,
                pub(super) parent_visible: u8,
            }
        };
        let tokens = process_pub_item(input);
        let output: ItemUnion = syn::parse2(tokens).expect("union output");
        assert!(
            doc_strings(&output.attrs)
                .iter()
                .any(|doc| doc.contains("Model union `Buffer` exported via `#[model]`.")),
            "union doc missing"
        );
        assert_eq!(output.fields.named.len(), 4);
        for field in &output.fields.named {
            let name = field.ident.as_ref().expect("named field").to_string();
            let docs = doc_strings(&field.attrs);
            assert!(
                docs.iter()
                    .any(|doc| doc.contains(&format!("Field `{name}` for union `Buffer`."))),
                "missing doc for {name}"
            );
            let expected: Visibility = match name.as_str() {
                "first" => expected_public_field_visibility(),
                "second" => Visibility::Inherited,
                "crate_visible" => parse_quote!(pub(crate)),
                "parent_visible" => parse_quote!(pub(super)),
                _ => panic!("unexpected union field {name}"),
            };
            assert_eq!(
                field.vis, expected,
                "unexpected union visibility for {name}"
            );
        }
    }
}
