use manyhow::{Emitter, emit};
use proc_macro2::TokenStream;
use quote::{ToTokens, quote};
use syn::{Attribute, Meta, Token, parse_quote, punctuated::Punctuated};

/// Implementation of the `#[model]` attribute.
pub fn impl_model(emitter: &mut Emitter, input: &syn::ItemMod) -> TokenStream {
    let syn::ItemMod {
        attrs,
        vis,
        mod_token,
        ident,
        content,
        semi,
        ..
    } = input;

    if *vis != syn::Visibility::Inherited {
        emit!(
            emitter,
            input,
            "The `model` attribute can only be used on private modules",
        );
        return quote!();
    }

    if ident != "model" {
        emit!(
            emitter,
            input,
            "The `model` attribute can only be used on the `model` module",
        );
    }

    let items_code = if let Some((_, items)) = content {
        items
            .iter()
            .map(|item| process_item(item.clone()))
            .collect::<Vec<_>>()
    } else {
        Vec::new()
    };

    quote! {
        #(#attrs)*
        #[doc = "Public model items generated by the `#[model]` attribute."]
        #mod_token #ident {
            #[cfg(feature = "json")]
            use crate::{JsonDeserialize, JsonSerialize};
            #(#items_code)*
        }#semi
    }
}

pub fn process_item(item: syn::Item) -> TokenStream {
    let mut input: syn::DeriveInput = match item {
        syn::Item::Struct(item_struct) => item_struct.into(),
        syn::Item::Enum(item_enum) => item_enum.into(),
        syn::Item::Union(item_union) => item_union.into(),
        other => return other.into_token_stream(),
    };

    // Expose items so that they can be re-exported.
    input.vis = parse_quote!(pub);

    process_pub_item(input)
}

fn process_pub_item(input: syn::DeriveInput) -> TokenStream {
    let ident = input.ident;
    let attrs = input.attrs;
    let generics = input.generics;

    match input.data {
        syn::Data::Struct(item) => process_struct(item, &ident, &generics, attrs),
        syn::Data::Enum(item) => process_enum(item, &ident, &generics, attrs),
        syn::Data::Union(item) => process_union(item, &ident, &generics, attrs),
    }
}

fn process_struct(
    mut item: syn::DataStruct,
    ident: &syn::Ident,
    generics: &syn::Generics,
    mut attrs: Vec<syn::Attribute>,
) -> TokenStream {
    let (impl_generics, _, where_clause) = generics.split_for_impl();

    ensure_doc(
        &mut attrs,
        format!("Model struct `{ident}` exported via `#[model]`."),
    );

    match &mut item.fields {
        syn::Fields::Named(fields) => {
            for field in &mut fields.named {
                let name = field
                    .ident
                    .as_ref()
                    .map_or_else(|| "field".to_owned(), ToString::to_string);
                ensure_doc(&mut field.attrs, format!("Field `{name}` for `{ident}`."));
                if matches!(field.vis, syn::Visibility::Public(_))
                    && !cfg!(feature = "transparent_api")
                {
                    field.vis = parse_quote!(pub(crate));
                }
            }
            let fields = &fields.named;
            let item = quote! {
                pub struct #ident #impl_generics #where_clause {
                    #fields
                }
            };
            expose_ffi(attrs, &item)
        }
        syn::Fields::Unnamed(fields) => {
            for (idx, field) in fields.unnamed.iter_mut().enumerate() {
                ensure_doc(&mut field.attrs, format!("Field #{idx} for `{ident}`."));
                if matches!(field.vis, syn::Visibility::Public(_))
                    && !cfg!(feature = "transparent_api")
                {
                    field.vis = parse_quote!(pub(crate));
                }
            }
            let fields = &fields.unnamed;
            let item = quote! {
                pub struct #ident #impl_generics( #fields ) #where_clause;
            };
            expose_ffi(attrs, &item)
        }
        syn::Fields::Unit => {
            let item = quote! {
                pub struct #ident #impl_generics #where_clause;
            };
            expose_ffi(attrs, &item)
        }
    }
}

fn process_enum(
    mut item: syn::DataEnum,
    ident: &syn::Ident,
    generics: &syn::Generics,
    mut attrs: Vec<syn::Attribute>,
) -> TokenStream {
    let (impl_generics, _, where_clause) = generics.split_for_impl();
    ensure_doc(
        &mut attrs,
        format!("Model enum `{ident}` exported via `#[model]`."),
    );
    for variant in &mut item.variants {
        ensure_doc(
            &mut variant.attrs,
            format!("Variant `{}` of `{ident}`.", variant.ident),
        );
        ensure_field_docs(&mut variant.fields, ident, Some(&variant.ident));
    }
    let variants = item.variants;
    let item = quote! {
        pub enum #ident #impl_generics #where_clause {
            #variants
        }
    };
    expose_ffi(attrs, &item)
}

fn process_union(
    mut item: syn::DataUnion,
    ident: &syn::Ident,
    generics: &syn::Generics,
    mut attrs: Vec<syn::Attribute>,
) -> TokenStream {
    let (impl_generics, _, where_clause) = generics.split_for_impl();
    ensure_doc(
        &mut attrs,
        format!("Model union `{ident}` exported via `#[model]`."),
    );
    for field in &mut item.fields.named {
        if matches!(field.vis, syn::Visibility::Public(_)) && !cfg!(feature = "transparent_api") {
            field.vis = parse_quote!(pub(crate));
        }
        let name = field
            .ident
            .as_ref()
            .map_or_else(|| "field".to_owned(), ToString::to_string);
        ensure_doc(
            &mut field.attrs,
            format!("Field `{name}` for union `{ident}`."),
        );
    }
    let fields = item.fields.named.iter();
    let item = quote! {
        pub union #ident #impl_generics #where_clause {
            #(#fields),*
        }
    };
    expose_ffi(attrs, &item)
}

fn expose_ffi(attrs: Vec<syn::Attribute>, item: &TokenStream) -> TokenStream {
    let (ffi_type, attrs) = match extract_ffi_type(attrs) {
        Ok(extracted) => extracted,
        Err(error) => return error.into_compile_error(),
    };
    let Some(ffi_type) = ffi_type else {
        return quote! {
            #(#attrs)*
            #item
        };
    };

    let ffi_type: Option<Attribute> = match ffi_type {
        // A bare marker opts the model item into FFI generation. It is not a
        // valid helper attribute for the generated `FfiType` derive.
        Meta::Path(_) => None,
        ffi_type @ Meta::List(_) => Some(parse_quote!(#[#ffi_type])),
        ffi_type @ Meta::NameValue(_) => {
            return syn::Error::new_spanned(
                ffi_type,
                "`ffi_type` must be bare or use list-form representation arguments",
            )
            .into_compile_error();
        }
    };

    quote! {
        #[cfg(all(not(feature = "ffi_export"), not(feature = "ffi_import")))]
        #(#attrs)*
        #item

        #[cfg(all(feature = "ffi_export", not(feature = "ffi_import")))]
        #[derive(iroha_ffi::FfiType)]
        #[iroha_ffi::ffi_export]
        #ffi_type
        #(#attrs)*
        #item

        #[cfg(feature = "ffi_import")]
        iroha_ffi::ffi! {
            #[iroha_ffi::ffi_import]
            #ffi_type
            #(#attrs)*
            #item
        }
    }
}

/// Extract the `ffi_type` helper attribute consumed by the generated
/// `FfiType` derive.
///
/// Model declarations gate this helper with `cfg_attr` so it is not visible
/// when neither FFI feature is enabled. The model macro owns that feature
/// split, so it removes the wrapper and restores the helper only in the export
/// and import branches.
fn extract_ffi_type(attrs: Vec<Attribute>) -> syn::Result<(Option<Meta>, Vec<Attribute>)> {
    let mut ffi_type = None;
    let mut retained = Vec::with_capacity(attrs.len());

    for attr in attrs {
        if attr.path().is_ident("ffi_type") {
            set_ffi_type(&mut ffi_type, attr.meta)?;
            continue;
        }

        if attr.path().is_ident("cfg_attr") {
            let nested = attr.parse_args_with(Punctuated::<Meta, Token![,]>::parse_terminated)?;
            let mut nested = nested.into_iter();
            let Some(predicate) = nested.next() else {
                retained.push(attr);
                continue;
            };

            let mut remaining = Punctuated::<Meta, Token![,]>::new();
            let mut extracted = None;
            for meta in nested {
                if meta.path().is_ident("ffi_type") {
                    set_ffi_type(&mut extracted, meta)?;
                } else {
                    remaining.push(meta);
                }
            }

            if let Some(extracted) = extracted {
                let ffi_features: [Meta; 2] = [
                    parse_quote!(any(feature = "ffi_export", feature = "ffi_import")),
                    parse_quote!(any(feature = "ffi_import", feature = "ffi_export")),
                ];
                if !ffi_features.contains(&predicate) {
                    return Err(syn::Error::new_spanned(
                        predicate,
                        "`ffi_type` on a model item must be gated by \
                         `any(feature = \"ffi_export\", feature = \"ffi_import\")`",
                    ));
                }
                set_ffi_type(&mut ffi_type, extracted)?;
                if !remaining.is_empty() {
                    retained.push(parse_quote!(#[cfg_attr(#predicate, #remaining)]));
                }
                continue;
            }
        }

        retained.push(attr);
    }

    Ok((ffi_type, retained))
}

fn set_ffi_type(slot: &mut Option<Meta>, ffi_type: Meta) -> syn::Result<()> {
    if slot.is_some() {
        return Err(syn::Error::new_spanned(
            ffi_type,
            "a model item may declare `ffi_type` only once",
        ));
    }
    *slot = Some(ffi_type);
    Ok(())
}

fn ensure_doc(attrs: &mut Vec<Attribute>, default: impl AsRef<str>) {
    let has_doc = attrs.iter().any(|attr| attr.path().is_ident("doc"));
    if !has_doc {
        let doc = default.as_ref();
        attrs.push(parse_quote!(#[doc = #doc]));
    }
}

fn ensure_field_docs(fields: &mut syn::Fields, owner: &syn::Ident, variant: Option<&syn::Ident>) {
    match fields {
        syn::Fields::Named(named) => {
            for field in &mut named.named {
                let name = field
                    .ident
                    .as_ref()
                    .map_or_else(|| "field".to_owned(), ToString::to_string);
                let context = variant.map_or_else(
                    || format!("`{owner}`"),
                    |variant| format!("variant `{variant}` in `{owner}`"),
                );
                ensure_doc(&mut field.attrs, format!("Field `{name}` for {context}."));
            }
        }
        syn::Fields::Unnamed(unnamed) => {
            for (idx, field) in unnamed.unnamed.iter_mut().enumerate() {
                let context = variant.map_or_else(
                    || format!("`{owner}`"),
                    |variant| format!("variant `{variant}` in `{owner}`"),
                );
                ensure_doc(&mut field.attrs, format!("Field #{idx} for {context}."));
            }
        }
        syn::Fields::Unit => {}
    }
}

#[cfg(test)]
mod tests {
    use syn::{
        Attribute, Expr, File, Item, ItemEnum, ItemStruct, ItemUnion, Lit, Visibility, parse_quote,
    };

    use super::*;

    fn doc_strings(attrs: &[Attribute]) -> Vec<String> {
        attrs
            .iter()
            .filter_map(|attr| match &attr.meta {
                syn::Meta::NameValue(meta) if meta.path.is_ident("doc") => {
                    if let Expr::Lit(expr) = &meta.value
                        && let Lit::Str(lit) = &expr.lit
                    {
                        return Some(lit.value());
                    }
                    None
                }
                _ => None,
            })
            .collect()
    }

    #[test]
    fn struct_fields_documented_and_restricted() {
        let input: syn::DeriveInput = parse_quote! {
            pub struct Sample<'a> {
                pub visible: &'a str,
                hidden: bool,
            }
        };

        let tokens = process_pub_item(input);
        let output: ItemStruct = syn::parse2(tokens).expect("struct output");

        assert!(
            doc_strings(&output.attrs)
                .iter()
                .any(|doc| doc.contains("Model struct `Sample` exported via `#[model]`.")),
            "struct doc missing"
        );

        let fields = match output.fields {
            syn::Fields::Named(fields) => fields.named,
            _ => panic!("expected named fields"),
        };

        let mut restricted_seen = false;
        for field in fields {
            let name = field.ident.expect("named field").to_string();
            let docs = doc_strings(&field.attrs);
            let expected_fragment = format!("`{name}` for `Sample`");
            assert!(
                docs.iter().any(|doc| doc.contains(&expected_fragment)),
                "missing doc for {name}"
            );

            if name == "visible" {
                restricted_seen = matches!(field.vis, Visibility::Restricted(_));
            }
        }
        assert!(
            restricted_seen,
            "public field visibility was not restricted"
        );
    }

    #[test]
    fn enum_variants_and_fields_documented() {
        let input: syn::DeriveInput = parse_quote! {
            pub enum Event {
                Unit,
                Tuple(u32),
                Struct { flag: bool },
            }
        };

        let tokens = process_pub_item(input);
        let output: ItemEnum = syn::parse2(tokens).expect("enum output");

        for variant in &output.variants {
            let docs = doc_strings(&variant.attrs);
            let expected = format!("Variant `{}` of `Event`.", variant.ident);
            assert!(
                docs.iter().any(|doc| doc.contains(&expected)),
                "missing doc for {}",
                variant.ident
            );
        }

        let tuple = output
            .variants
            .iter()
            .find(|variant| variant.ident == "Tuple")
            .expect("Tuple variant");
        match &tuple.fields {
            syn::Fields::Unnamed(fields) => {
                let docs = doc_strings(&fields.unnamed[0].attrs);
                assert!(
                    docs.iter()
                        .any(|doc| doc.contains("Field #0 for variant `Tuple` in `Event`.")),
                    "missing tuple field doc"
                );
            }
            _ => panic!("expected unnamed fields"),
        }

        let named = output
            .variants
            .iter()
            .find(|variant| variant.ident == "Struct")
            .expect("Struct variant");
        match &named.fields {
            syn::Fields::Named(fields) => {
                let docs = doc_strings(&fields.named[0].attrs);
                assert!(
                    docs.iter()
                        .any(|doc| doc.contains("Field `flag` for variant `Struct` in `Event`.")),
                    "missing struct field doc"
                );
            }
            _ => panic!("expected named fields"),
        }
    }

    #[test]
    fn union_fields_documented_and_restricted() {
        let input: syn::DeriveInput = parse_quote! {
            pub union Buffer {
                pub first: u32,
                second: u64,
            }
        };

        let tokens = process_pub_item(input);
        let output: ItemUnion = syn::parse2(tokens).expect("union output");

        assert!(
            doc_strings(&output.attrs)
                .iter()
                .any(|doc| doc.contains("Model union `Buffer` exported via `#[model]`.")),
            "union doc missing"
        );

        for field in &output.fields.named {
            let name = field.ident.as_ref().expect("named field").to_string();
            let docs = doc_strings(&field.attrs);
            assert!(
                docs.iter()
                    .any(|doc| doc.contains(&format!("Field `{name}` for union `Buffer`."))),
                "missing doc for {name}"
            );

            if name == "first" {
                assert!(
                    matches!(field.vis, Visibility::Restricted(_)),
                    "public union field visibility was not restricted"
                );
            }
        }
    }

    #[test]
    fn wrapped_ffi_type_expands_for_default_export_and_import() {
        let input: syn::DeriveInput = parse_quote! {
            #[cfg_attr(any(feature = "ffi_export", feature = "ffi_import"), ffi_type)]
            pub struct Sample;
        };

        let output: File = syn::parse2(process_pub_item(input)).expect("FFI model output");
        assert!(
            matches!(
                output.items.as_slice(),
                [Item::Struct(_), Item::Struct(_), Item::Macro(_)]
            ),
            "expected default, export, and import branches"
        );

        let rendered = output.to_token_stream().to_string();
        assert!(
            !rendered.contains("cfg_attr"),
            "the source-only cfg_attr wrapper leaked into generated output"
        );
        assert_eq!(
            rendered.matches("ffi_type").count(),
            0,
            "a bare marker is a sentinel and must not reach the FFI derive"
        );
        assert!(rendered.contains("iroha_ffi :: FfiType"));
        assert!(rendered.contains("iroha_ffi :: ffi_export"));
        assert!(rendered.contains("iroha_ffi :: ffi_import"));
    }

    #[test]
    fn wrapped_ffi_type_preserves_all_representation_policies() {
        assert_ffi_policy(
            parse_quote! {
                #[cfg_attr(any(feature = "ffi_import", feature = "ffi_export"), ffi_type(opaque))]
                pub struct Opaque;
            },
            parse_quote!(#[ffi_type(opaque)]),
        );
        assert_ffi_policy(
            parse_quote! {
                #[cfg_attr(any(feature = "ffi_export", feature = "ffi_import"), ffi_type(local))]
                pub struct Local;
            },
            parse_quote!(#[ffi_type(local)]),
        );
        assert_ffi_policy(
            parse_quote! {
                #[cfg_attr(
                    any(feature = "ffi_export", feature = "ffi_import"),
                    ffi_type(unsafe { robust })
                )]
                pub struct Robust;
            },
            parse_quote!(#[ffi_type(unsafe { robust })]),
        );
    }

    fn assert_ffi_policy(input: syn::DeriveInput, expected: Attribute) {
        let output: File = syn::parse2(process_pub_item(input)).expect("FFI model output");
        let rendered = output.to_token_stream().to_string();
        let expected = expected.into_token_stream().to_string();

        assert_eq!(
            rendered.matches(&expected).count(),
            2,
            "FFI policy `{expected}` was not preserved in export and import branches:\n{rendered}"
        );
        assert!(
            !rendered.contains("cfg_attr"),
            "the source-only cfg_attr wrapper leaked into generated output: {rendered}"
        );
    }
}
