//! SoraNet VPN cell layout, control-plane metadata, and billing receipts.
//!
//! This module pins the fixed 1024-byte cell format used by the native SoraNet
//! VPN overlay so that control-plane surfaces, SDKs, and harnesses share the
//! same framing. Cells carry a compact header (flow label + sequence/ack +
//! padding budget) followed by a padded payload. Control-plane envelopes
//! describe DNS/route pushes, guard/exit selection, and metering receipts so
//! exit gateways can emit deterministic Norito payloads for governance.

use core::fmt;
#[cfg(feature = "json")]
use core::fmt::Write as FmtWrite;
use std::net::{Ipv4Addr, Ipv6Addr};

use blake3;
use iroha_schema::IntoSchema;
use norito::codec::{Decode, Encode};
#[cfg(feature = "json")]
use norito::json;

use super::RelayId;

/// Fixed-length cell size used by the VPN tunnel.
pub const VPN_CELL_LEN: usize = 1_024;
/// Magic prefix used by helper-authenticated VPN tickets.
pub const VPN_HELPER_TICKET_MAGIC: &[u8; 8] = b"SVPNHT1\0";
/// Fixed byte length of a helper-authenticated VPN ticket.
pub const VPN_HELPER_TICKET_LEN: usize = 64;
/// Default MTU advertised to Sora VPN clients and local tunnel helpers.
pub const VPN_DEFAULT_TUNNEL_MTU_BYTES: u16 = 1_280;

/// Header serialization length (bytes).
const VPN_HEADER_LEN: usize = 42;
const VPN_SESSION_IPV4_BASE: u32 = u32::from_be_bytes([10, 208, 0, 0]);
const VPN_SESSION_IPV4_SUBNET_COUNT: u32 = 1 << 18;
const VPN_SESSION_IPV6_BASE: u128 = 0xfd53_7261_6574_0000_0000_0000_0000_0000u128;

/// Deterministic per-session address plan shared by Torii, relays, and local tunnel helpers.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VpnSessionAddressPlanV1 {
    /// Tunnel addresses assigned to the exit/backend side of the point-to-point link.
    pub server_tunnel_addresses: Vec<String>,
    /// Tunnel addresses assigned to the client/helper side of the point-to-point link.
    pub client_tunnel_addresses: Vec<String>,
    /// Session-local subnet routes that should point at the tunnel interface on the backend.
    pub session_routes: Vec<String>,
}

/// Enumeration of supported cell classes.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Decode, Encode, IntoSchema)]
pub enum VpnCellClassV1 {
    /// User traffic tunneled through the circuit.
    Data,
    /// Cover cell generated by the scheduler.
    Cover,
    /// Liveness probe without user payload.
    KeepAlive,
    /// Control-plane update (route push, key rotation).
    Control,
}

impl VpnCellClassV1 {
    /// Returns the on-wire tag for the class.
    #[must_use]
    pub const fn tag(self) -> u8 {
        match self {
            Self::Data => 0,
            Self::Cover => 1,
            Self::KeepAlive => 2,
            Self::Control => 3,
        }
    }
}

/// Bitfield describing cell handling hints.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Decode, Encode, IntoSchema)]
pub struct VpnCellFlagsV1 {
    bits: u8,
}

impl VpnCellFlagsV1 {
    /// Allowed flag mask (all known flags).
    pub const ALLOWED_MASK: u8 =
        Self::COVER | Self::REQUIRE_ACK | Self::MIGRATION | Self::KEY_ROTATION;
    /// Flag indicating that the frame carries cover traffic.
    pub const COVER: u8 = 0x01;
    /// Flag indicating that the frame should elicit an ACK.
    pub const REQUIRE_ACK: u8 = 0x02;
    /// Flag indicating that the cell belongs to a path-migration handshake.
    pub const MIGRATION: u8 = 0x04;
    /// Flag indicating a key rotation hint for the guard/exit.
    pub const KEY_ROTATION: u8 = 0x08;

    /// Construct a new flag bitfield from raw bits.
    #[must_use]
    pub const fn from_bits(bits: u8) -> Self {
        Self { bits }
    }

    /// Construct a new flag bitfield from individual hints.
    #[must_use]
    #[allow(clippy::fn_params_excessive_bools)]
    pub const fn new(cover: bool, require_ack: bool, migration: bool, key_rotation: bool) -> Self {
        let mut bits = 0;
        if cover {
            bits |= Self::COVER;
        }
        if require_ack {
            bits |= Self::REQUIRE_ACK;
        }
        if migration {
            bits |= Self::MIGRATION;
        }
        if key_rotation {
            bits |= Self::KEY_ROTATION;
        }
        Self { bits }
    }

    /// Returns the raw bitfield.
    #[must_use]
    pub const fn bits(self) -> u8 {
        self.bits
    }

    /// Returns `true` when any unknown flag bits are set.
    #[must_use]
    pub const fn has_unknown_bits(self) -> bool {
        (self.bits & !Self::ALLOWED_MASK) != 0
    }

    /// Returns `true` when the cover flag is set.
    #[must_use]
    pub const fn is_cover(self) -> bool {
        (self.bits & Self::COVER) != 0
    }
}

#[cfg(feature = "json")]
impl json::JsonSerialize for VpnCellFlagsV1 {
    fn json_serialize(&self, out: &mut String) {
        let _ = FmtWrite::write_fmt(out, format_args!("{}", self.bits));
    }
}

#[cfg(feature = "json")]
impl json::JsonDeserialize for VpnCellFlagsV1 {
    fn json_deserialize(parser: &mut json::Parser<'_>) -> Result<Self, json::Error> {
        let value = u64::json_deserialize(parser)?;
        if value > u64::from(u8::MAX) {
            return Err(json::Error::Message("flag value exceeds u8".into()));
        }
        let bits = u8::try_from(value)
            .map_err(|_| json::Error::Message("flag value exceeds u8".into()))?;
        Ok(Self::from_bits(bits))
    }
}

/// Flow label assigned to a tunnel.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Decode, Encode, IntoSchema)]
pub struct VpnFlowLabelV1 {
    /// Three-byte flow label encoded in network byte order.
    pub bytes: [u8; 3],
}

impl VpnFlowLabelV1 {
    /// Maximum allowed flow label value (24 bits).
    pub const MAX: u32 = 0x00FF_FFFF;
    /// Maximum supported flow label width.
    pub const MAX_BITS: u8 = 24;

    /// Construct a new flow label from a 24-bit integer.
    ///
    /// # Errors
    ///
    /// Returns [`VpnCellError::FlowLabelOverflow`] when `value` exceeds 24 bits.
    pub const fn from_u32(value: u32) -> Result<Self, VpnCellError> {
        if value > Self::MAX {
            return Err(VpnCellError::FlowLabelOverflow {
                value,
                max_bits: Self::MAX_BITS,
            });
        }
        let bytes = value.to_be_bytes();
        Ok(Self {
            bytes: [bytes[1], bytes[2], bytes[3]],
        })
    }

    /// Construct a new flow label bounded by `bits` (1–24).
    ///
    /// # Errors
    ///
    /// Returns [`VpnCellError::InvalidFlowLabelBits`] when `bits` exceeds the
    /// supported width or [`VpnCellError::FlowLabelOverflow`] when `value` does
    /// not fit into the requested width.
    pub fn from_u32_with_bits(value: u32, bits: u8) -> Result<Self, VpnCellError> {
        let max = Self::max_value_for_bits(bits)?;
        if value > max {
            return Err(VpnCellError::FlowLabelOverflow {
                value,
                max_bits: bits,
            });
        }
        let bytes = value.to_be_bytes();
        Ok(Self {
            bytes: [bytes[1], bytes[2], bytes[3]],
        })
    }

    /// Returns the maximum representable flow label for the supplied width.
    ///
    /// # Errors
    /// Returns [`VpnCellError::InvalidFlowLabelBits`] when `bits` is zero or exceeds
    /// the supported width.
    pub fn max_value_for_bits(bits: u8) -> Result<u32, VpnCellError> {
        if bits == 0 || bits > Self::MAX_BITS {
            return Err(VpnCellError::InvalidFlowLabelBits(bits));
        }
        if bits == Self::MAX_BITS {
            return Ok(Self::MAX);
        }
        Ok((1u32 << bits) - 1)
    }

    /// Ensures the flow label fits inside the supplied bit width.
    ///
    /// # Errors
    /// Returns [`VpnCellError::FlowLabelOverflow`] when the label exceeds the provided bit width.
    pub fn ensure_width(self, bits: u8) -> Result<(), VpnCellError> {
        let max = Self::max_value_for_bits(bits)?;
        if self.to_u32() > max {
            return Err(VpnCellError::FlowLabelOverflow {
                value: self.to_u32(),
                max_bits: bits,
            });
        }
        Ok(())
    }

    /// Decode the flow label into a 24-bit integer.
    #[must_use]
    pub const fn to_u32(self) -> u32 {
        u32::from_be_bytes([0, self.bytes[0], self.bytes[1], self.bytes[2]])
    }
}

#[cfg(feature = "json")]
impl json::JsonSerialize for VpnFlowLabelV1 {
    fn json_serialize(&self, out: &mut String) {
        let _ = FmtWrite::write_fmt(out, format_args!("{}", self.to_u32()));
    }
}

#[cfg(feature = "json")]
impl json::JsonDeserialize for VpnFlowLabelV1 {
    fn json_deserialize(parser: &mut json::Parser<'_>) -> Result<Self, json::Error> {
        let value = u32::json_deserialize(parser)?;
        let flow = Self::from_u32(value)
            .map_err(|err| json::Error::Message(format!("invalid flow label: {err}")))?;
        Ok(flow)
    }
}

/// Fixed header carried by every VPN cell.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Decode, Encode, IntoSchema)]
pub struct VpnCellHeaderV1 {
    /// Protocol version (currently `1`).
    pub version: u8,
    /// Cell class.
    pub class: VpnCellClassV1,
    /// Handling flags.
    pub flags: VpnCellFlagsV1,
    /// Circuit identifier derived from the route directory entry.
    #[cfg_attr(feature = "json", norito(with = "crate::json_helpers::fixed_bytes"))]
    pub circuit_id: [u8; 16],
    /// Flow label (24 bits).
    pub flow_label: VpnFlowLabelV1,
    /// Monotonic sequence number for replay protection.
    pub sequence: u64,
    /// Acknowledgement number (0 when unused).
    pub ack: u64,
    /// Padding budget in milliseconds for this cell.
    pub padding_budget_ms: u16,
    /// Payload length prior to padding.
    pub payload_len: u16,
}

impl VpnCellHeaderV1 {
    /// Returns the serialized header length.
    #[must_use]
    pub const fn serialized_len() -> usize {
        VPN_HEADER_LEN
    }
}

/// VPN cell with payload (unpadded).
#[derive(Debug, Clone, PartialEq, Eq, Decode, Encode, IntoSchema)]
pub struct VpnCellV1 {
    /// Cell header.
    pub header: VpnCellHeaderV1,
    /// Raw payload carried by the cell.
    #[cfg_attr(feature = "json", norito(with = "crate::json_helpers::bytes"))]
    pub payload: Vec<u8>,
}

impl VpnCellV1 {
    /// Maximum payload length (bytes) permitted in a single cell.
    #[must_use]
    pub const fn max_payload_len() -> usize {
        VPN_CELL_LEN - VPN_HEADER_LEN
    }

    /// Pad the cell into a fixed-length frame suitable for transport.
    ///
    /// # Errors
    ///
    /// Returns [`VpnCellError::PayloadTooLarge`] if the payload exceeds the
    /// available space after accounting for the header, or
    /// [`VpnCellError::PayloadLengthMismatch`] when `payload_len` would be
    /// truncated.
    pub fn into_padded_frame(mut self) -> Result<VpnPaddedCellV1, VpnCellError> {
        let max_payload = Self::max_payload_len();
        if self.payload.len() > max_payload {
            return Err(VpnCellError::PayloadTooLarge {
                max: max_payload,
                actual: self.payload.len(),
            });
        }
        let payload_len =
            u16::try_from(self.payload.len()).map_err(|_| VpnCellError::PayloadLengthMismatch {
                declared: u16::MAX,
                actual: self.payload.len(),
            })?;

        self.header.payload_len = payload_len;

        let mut frame = [0u8; VPN_CELL_LEN];
        let mut cursor = 0;
        frame[cursor] = self.header.version;
        cursor += 1;
        frame[cursor] = self.header.class.tag();
        cursor += 1;
        frame[cursor] = self.header.flags.bits();
        cursor += 1;
        frame[cursor..cursor + 16].copy_from_slice(&self.header.circuit_id);
        cursor += 16;
        frame[cursor..cursor + 3].copy_from_slice(&self.header.flow_label.bytes);
        cursor += 3;
        frame[cursor..cursor + 8].copy_from_slice(&self.header.sequence.to_be_bytes());
        cursor += 8;
        frame[cursor..cursor + 8].copy_from_slice(&self.header.ack.to_be_bytes());
        cursor += 8;
        frame[cursor..cursor + 2].copy_from_slice(&self.header.padding_budget_ms.to_be_bytes());
        cursor += 2;
        frame[cursor..cursor + 2].copy_from_slice(&self.header.payload_len.to_be_bytes());
        cursor += 2;

        frame[cursor..cursor + usize::from(payload_len)].copy_from_slice(&self.payload);

        Ok(VpnPaddedCellV1 { bytes: frame })
    }
}

/// Fixed-length padded cell frame.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VpnPaddedCellV1 {
    /// Raw frame bytes (always [`VPN_CELL_LEN`] long).
    pub bytes: [u8; VPN_CELL_LEN],
}

impl AsRef<[u8]> for VpnPaddedCellV1 {
    fn as_ref(&self) -> &[u8] {
        &self.bytes
    }
}

impl VpnPaddedCellV1 {
    /// Parse a padded cell frame back into the header and payload components.
    ///
    /// # Errors
    ///
    /// Returns [`VpnCellError::FrameLengthMismatch`] if the frame length differs
    /// from the pinned cell size, [`VpnCellError::UnsupportedVersion`] or
    /// [`VpnCellError::InvalidClass`] for malformed headers,
    /// [`VpnCellError::InvalidFlags`] for unsupported flag bits, or
    /// [`VpnCellError::PayloadOverrun`] when the declared payload length exceeds
    /// the available bytes.
    pub fn parse(&self) -> Result<VpnCellV1, VpnCellError> {
        Self::parse_bytes(&self.bytes)
    }

    /// Parse a padded cell frame and enforce a maximum flow-label width.
    ///
    /// # Errors
    ///
    /// Returns [`VpnCellError::FlowLabelOverflow`] when the flow label exceeds
    /// `max_flow_label_bits`.
    pub fn parse_with_flow_label_bits(
        &self,
        max_flow_label_bits: u8,
    ) -> Result<VpnCellV1, VpnCellError> {
        Self::parse_bytes_with_flow_label_bits(&self.bytes, max_flow_label_bits)
    }

    /// Parse an arbitrary byte slice into a VPN cell with flow-label validation.
    ///
    /// # Errors
    ///
    /// Returns [`VpnCellError::FlowLabelOverflow`] when the flow label exceeds
    /// `max_flow_label_bits`.
    pub fn parse_bytes_with_flow_label_bits(
        bytes: &[u8],
        max_flow_label_bits: u8,
    ) -> Result<VpnCellV1, VpnCellError> {
        let cell = Self::parse_bytes(bytes)?;
        cell.header.flow_label.ensure_width(max_flow_label_bits)?;
        Ok(cell)
    }

    /// Parse an arbitrary byte slice into a VPN cell, expecting a full padded frame.
    ///
    /// # Errors
    /// Returns [`VpnCellError`] when the frame length, header, flags, payload length,
    /// or padding are invalid.
    pub fn parse_bytes(bytes: &[u8]) -> Result<VpnCellV1, VpnCellError> {
        if bytes.len() != VPN_CELL_LEN {
            return Err(VpnCellError::FrameLengthMismatch {
                expected: VPN_CELL_LEN,
                actual: bytes.len(),
            });
        }

        let version = bytes[0];
        if version != 1 {
            return Err(VpnCellError::UnsupportedVersion(version));
        }

        let class = match bytes[1] {
            0 => VpnCellClassV1::Data,
            1 => VpnCellClassV1::Cover,
            2 => VpnCellClassV1::KeepAlive,
            3 => VpnCellClassV1::Control,
            other => return Err(VpnCellError::InvalidClass(other)),
        };
        let flags = VpnCellFlagsV1::from_bits(bytes[2]);
        let cover_flag = flags.is_cover();
        if cover_flag != (class == VpnCellClassV1::Cover) {
            return Err(VpnCellError::FlagClassMismatch { class, flags });
        }
        if flags.has_unknown_bits() {
            return Err(VpnCellError::InvalidFlags {
                bits: flags.bits(),
                allowed: VpnCellFlagsV1::ALLOWED_MASK,
            });
        }

        let mut circuit_id = [0u8; 16];
        circuit_id.copy_from_slice(&bytes[3..19]);

        let flow_label = VpnFlowLabelV1 {
            bytes: [bytes[19], bytes[20], bytes[21]],
        };

        let sequence = u64::from_be_bytes(bytes[22..30].try_into().expect("slice length"));
        let ack = u64::from_be_bytes(bytes[30..38].try_into().expect("slice length"));
        let padding_budget_ms = u16::from_be_bytes(bytes[38..40].try_into().expect("slice length"));
        let payload_len = u16::from_be_bytes(bytes[40..42].try_into().expect("slice length"));
        let available_payload = bytes.len().saturating_sub(VPN_HEADER_LEN);
        let payload_len_usize = usize::from(payload_len);
        if payload_len_usize > VpnCellV1::max_payload_len() {
            return Err(VpnCellError::PayloadTooLarge {
                max: VpnCellV1::max_payload_len(),
                actual: payload_len_usize,
            });
        }
        if payload_len_usize > available_payload {
            return Err(VpnCellError::PayloadOverrun {
                declared: payload_len_usize,
                available: available_payload,
            });
        }

        let payload_end = VPN_HEADER_LEN + payload_len_usize;
        if payload_end < bytes.len()
            && let Some((offset, value)) = bytes[payload_end..]
                .iter()
                .copied()
                .enumerate()
                .find(|(_, byte)| *byte != 0)
        {
            return Err(VpnCellError::NonZeroPadding {
                index: payload_end + offset,
                value,
            });
        }
        let payload = bytes[VPN_HEADER_LEN..payload_end].to_vec();

        Ok(VpnCellV1 {
            header: VpnCellHeaderV1 {
                version,
                class,
                flags,
                circuit_id,
                flow_label,
                sequence,
                ack,
                padding_budget_ms,
                payload_len,
            },
            payload,
        })
    }
}

/// Cover traffic scheduler parameters.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Decode, Encode, IntoSchema)]
pub struct VpnCoverScheduleV1 {
    /// Ratio of cover cells to data cells expressed in permille (0–1000).
    pub cover_to_data_per_mille: u16,
    /// Heartbeat cadence for keepalives (milliseconds).
    pub heartbeat_ms: u16,
    /// Maximum burst of cover cells permitted per scheduling window.
    pub max_cover_burst: u16,
    /// Maximum jitter applied to cover spacing (milliseconds).
    pub jitter_ms: u16,
}

impl VpnCoverScheduleV1 {
    /// Generate a deterministic cover/data plan using the provided seed.
    #[must_use]
    pub fn plan(self, seed: [u8; 32], frames: usize) -> Vec<VpnCoverPlanEntryV1> {
        let mut prng = DeterministicPrng::new(seed);
        let mut entries = Vec::with_capacity(frames);
        let mut cover_streak = 0u16;
        for idx in 0..frames {
            let threshold = u16::try_from(prng.next_below(1_000)).unwrap_or(0);
            let mut is_cover = threshold < self.cover_to_data_per_mille;
            if is_cover {
                if cover_streak >= self.max_cover_burst {
                    is_cover = false;
                    cover_streak = 0;
                } else {
                    cover_streak = cover_streak.saturating_add(1);
                }
            } else {
                cover_streak = 0;
            }

            let jitter = u64::from(self.jitter_ms);
            let jitter_offset = if jitter == 0 {
                0
            } else {
                prng.next_below(jitter + 1)
            };
            let slot_ms = u64::from(self.heartbeat_ms);
            let slot_start = slot_ms.saturating_mul(idx as u64);
            let scheduled_ms = slot_start + jitter_offset;

            entries.push(VpnCoverPlanEntryV1 {
                slot_ms: scheduled_ms,
                is_cover,
            });
        }
        entries
    }
}

/// Deterministic PRNG seeded by a 32-byte buffer.
///
/// The generator streams bytes from a BLAKE3 XOF so all seed bits influence the
/// schedule while keeping the output stable across platforms.
struct DeterministicPrng {
    reader: blake3::OutputReader,
}

impl DeterministicPrng {
    fn new(seed: [u8; 32]) -> Self {
        let mut hasher = blake3::Hasher::new();
        hasher.update(b"soranet-vpn-cover-prng");
        hasher.update(&seed);
        Self {
            reader: hasher.finalize_xof(),
        }
    }

    fn next_u64(&mut self) -> u64 {
        let mut buf = [0u8; 8];
        self.reader.fill(&mut buf);
        u64::from_le_bytes(buf)
    }

    fn next_below(&mut self, upper: u64) -> u64 {
        if upper == 0 {
            return 0;
        }
        self.next_u64() % upper
    }
}

/// A scheduled cell emitted by the cover/data planner.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Decode, Encode, IntoSchema)]
pub struct VpnCoverPlanEntryV1 {
    /// Start time (milliseconds since plan epoch).
    pub slot_ms: u64,
    /// Whether the slot carries cover traffic instead of user data.
    pub is_cover: bool,
}

/// Exit class advertised for billing/telemetry.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Decode, Encode, IntoSchema)]
pub enum VpnExitClassV1 {
    /// Standard exit class (balanced latency/bandwidth).
    Standard,
    /// Low-latency exit class.
    LowLatency,
    /// High-security exit class (higher cover, slower).
    HighSecurity,
}

/// Errors returned when parsing exit-class labels from config/client inputs.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
#[error("unknown VPN exit class label: {label}")]
pub struct VpnExitClassParseError {
    /// The label that failed validation.
    pub label: String,
}

impl VpnExitClassV1 {
    /// Parse a human-readable exit-class label into the enum, accepting the
    /// canonical labels and their hyphen/underscore variants.
    ///
    /// # Errors
    /// Returns [`VpnExitClassParseError`] when the label is unknown.
    pub fn try_from_label(label: &str) -> Result<Self, VpnExitClassParseError> {
        match label.to_ascii_lowercase().as_str() {
            "standard" => Ok(Self::Standard),
            "low-latency" | "low_latency" => Ok(Self::LowLatency),
            "high-security" | "high_security" => Ok(Self::HighSecurity),
            other => Err(VpnExitClassParseError {
                label: other.to_string(),
            }),
        }
    }

    /// Canonical hyphenated label for the exit class.
    #[must_use]
    pub const fn as_label(self) -> &'static str {
        match self {
            Self::Standard => "standard",
            Self::LowLatency => "low-latency",
            Self::HighSecurity => "high-security",
        }
    }
}

/// Control-plane envelope used to push DNS/routes and guard/exit choices.
#[derive(Debug, Clone, PartialEq, Eq, Decode, Encode, IntoSchema)]
pub struct VpnControlPlaneV1 {
    /// Entry relay selected for the tunnel.
    pub entry_guard: RelayId,
    /// Exit relay selected for the tunnel.
    pub exit_guard: RelayId,
    /// DNS servers pushed to the `PacketTunnel` client.
    pub dns_servers: Vec<String>,
    /// Routes installed on the client.
    pub routes: Vec<VpnRouteV1>,
    /// Exit class advertised by the control plane.
    pub exit_class: VpnExitClassV1,
    /// Lease duration for the control-plane assignment (seconds).
    pub lease_seconds: u32,
}

/// Route entry pushed to a VPN client.
#[derive(Debug, Clone, PartialEq, Eq, Decode, Encode, IntoSchema)]
pub struct VpnRouteV1 {
    /// CIDR string describing the route.
    pub cidr: String,
    /// Optional next-hop for the route.
    pub via: Option<String>,
    /// Optional metric controlling route ordering.
    pub metric: Option<u16>,
}

/// Derive the deterministic point-to-point address plan for a VPN session.
#[must_use]
pub fn derive_vpn_session_address_plan_v1(session_id: [u8; 16]) -> VpnSessionAddressPlanV1 {
    let digest = blake3::hash(&session_id);
    let digest_bytes = digest.as_bytes();

    let v4_index = u32::from_be_bytes([
        digest_bytes[0],
        digest_bytes[1],
        digest_bytes[2],
        digest_bytes[3],
    ]) % VPN_SESSION_IPV4_SUBNET_COUNT;
    let v4_network = VPN_SESSION_IPV4_BASE + (v4_index << 2);
    let v4_route = format!("{}/30", Ipv4Addr::from(v4_network));
    let v4_server = format!("{}/30", Ipv4Addr::from(v4_network + 1));
    let v4_client = format!("{}/30", Ipv4Addr::from(v4_network + 2));

    let mut low = [0u8; 8];
    low.copy_from_slice(&digest_bytes[8..16]);
    let v6_subnet = u128::from(u64::from_be_bytes(low) >> 2);
    let v6_network = VPN_SESSION_IPV6_BASE | (v6_subnet << 2);
    let v6_route = format!("{}/126", Ipv6Addr::from(v6_network));
    let v6_server = format!("{}/126", Ipv6Addr::from(v6_network | 1));
    let v6_client = format!("{}/126", Ipv6Addr::from(v6_network | 2));

    VpnSessionAddressPlanV1 {
        server_tunnel_addresses: vec![v4_server, v6_server],
        client_tunnel_addresses: vec![v4_client, v6_client],
        session_routes: vec![v4_route, v6_route],
    }
}

/// Billing and telemetry receipt emitted by an exit gateway.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Decode, Encode, IntoSchema)]
pub struct VpnSessionReceiptV1 {
    /// Session identifier (client-assigned, 16 bytes).
    #[cfg_attr(feature = "json", norito(with = "crate::json_helpers::fixed_bytes"))]
    pub session_id: [u8; 16],
    /// Total ingress bytes (user payloads only).
    pub ingress_bytes: u64,
    /// Total egress bytes (user payloads only).
    pub egress_bytes: u64,
    /// Total cover bytes emitted for the session.
    pub cover_bytes: u64,
    /// Session uptime in seconds.
    pub uptime_secs: u32,
    /// Exit class applied for billing.
    pub exit_class: VpnExitClassV1,
    /// Hash of the meter manifest applied to this session.
    #[cfg_attr(feature = "json", norito(with = "crate::json_helpers::fixed_bytes"))]
    pub meter_hash: [u8; 32],
}

/// Helper-authenticated ticket carried by the local VPN controller when opening a relay session.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct VpnHelperTicketV1 {
    /// Session identifier bound to the tunnel runtime.
    pub session_id: [u8; 16],
    /// Absolute expiry time in milliseconds since the Unix epoch.
    pub expires_at_ms: u64,
}

impl VpnHelperTicketV1 {
    /// Serialize the helper ticket into its fixed-length on-wire representation.
    #[must_use]
    pub fn to_bytes(&self, secret: &[u8; 32]) -> [u8; VPN_HELPER_TICKET_LEN] {
        let mut bytes = [0u8; VPN_HELPER_TICKET_LEN];
        bytes[..VPN_HELPER_TICKET_MAGIC.len()].copy_from_slice(VPN_HELPER_TICKET_MAGIC);
        let mut cursor = VPN_HELPER_TICKET_MAGIC.len();
        bytes[cursor..cursor + self.session_id.len()].copy_from_slice(&self.session_id);
        cursor += self.session_id.len();
        bytes[cursor..cursor + 8].copy_from_slice(&self.expires_at_ms.to_be_bytes());
        cursor += 8;
        let mac = helper_ticket_mac(secret, &bytes[..cursor]);
        let mac_bytes = mac.as_bytes();
        bytes[cursor..cursor + mac_bytes.len()].copy_from_slice(mac_bytes);
        bytes
    }

    /// Serialize the helper ticket as hex for transport through JSON control-plane payloads.
    #[must_use]
    pub fn to_hex(&self, secret: &[u8; 32]) -> String {
        hex::encode(self.to_bytes(secret))
    }

    /// Return `true` when the supplied bytes look like a helper-auth ticket.
    #[must_use]
    pub fn looks_like(bytes: &[u8]) -> bool {
        bytes.len() == VPN_HELPER_TICKET_LEN && bytes.starts_with(VPN_HELPER_TICKET_MAGIC)
    }

    /// Parse and verify a helper-authenticated ticket.
    ///
    /// # Errors
    /// Returns an error when the frame length, magic prefix, MAC, or expiry are invalid.
    pub fn parse(
        bytes: &[u8],
        secret: &[u8; 32],
        now_ms: u64,
    ) -> Result<Self, VpnHelperTicketError> {
        if bytes.len() != VPN_HELPER_TICKET_LEN {
            return Err(VpnHelperTicketError::InvalidLength {
                expected: VPN_HELPER_TICKET_LEN,
                actual: bytes.len(),
            });
        }
        if !bytes.starts_with(VPN_HELPER_TICKET_MAGIC) {
            return Err(VpnHelperTicketError::InvalidMagic);
        }
        let mut cursor = VPN_HELPER_TICKET_MAGIC.len();
        let mut session_id = [0u8; 16];
        session_id.copy_from_slice(&bytes[cursor..cursor + 16]);
        cursor += 16;
        let mut expires = [0u8; 8];
        expires.copy_from_slice(&bytes[cursor..cursor + 8]);
        cursor += 8;
        let expected_mac = helper_ticket_mac(secret, &bytes[..cursor]);
        if expected_mac.as_bytes() != &bytes[cursor..] {
            return Err(VpnHelperTicketError::InvalidMac);
        }
        let expires_at_ms = u64::from_be_bytes(expires);
        if expires_at_ms <= now_ms {
            return Err(VpnHelperTicketError::Expired {
                expires_at_ms,
                now_ms,
            });
        }
        Ok(Self {
            session_id,
            expires_at_ms,
        })
    }

    /// Parse and verify a helper-authenticated ticket encoded as hex.
    ///
    /// # Errors
    /// Returns an error when the hex input or the decoded ticket is invalid.
    pub fn parse_hex(
        hex_ticket: &str,
        secret: &[u8; 32],
        now_ms: u64,
    ) -> Result<Self, VpnHelperTicketError> {
        let decoded = hex::decode(hex_ticket).map_err(VpnHelperTicketError::Hex)?;
        Self::parse(&decoded, secret, now_ms)
    }
}

fn helper_ticket_mac(secret: &[u8; 32], payload: &[u8]) -> blake3::Hash {
    let mut hasher = blake3::Hasher::new_keyed(secret);
    hasher.update(b"soranet-vpn-helper-ticket-v1");
    hasher.update(payload);
    hasher.finalize()
}

/// Errors surfaced while parsing or verifying helper-authenticated VPN tickets.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum VpnHelperTicketError {
    /// Ticket length did not match the pinned helper-ticket size.
    InvalidLength {
        /// Expected fixed helper-ticket length.
        expected: usize,
        /// Actual decoded ticket length.
        actual: usize,
    },
    /// Helper ticket did not carry the expected versioned magic prefix.
    InvalidMagic,
    /// Helper ticket MAC did not verify against the shared secret.
    InvalidMac,
    /// Helper ticket expired before verification completed.
    Expired {
        /// Ticket expiry timestamp in milliseconds since the Unix epoch.
        expires_at_ms: u64,
        /// Current verifier clock in milliseconds since the Unix epoch.
        now_ms: u64,
    },
    /// Hex decoding failed before ticket verification.
    Hex(hex::FromHexError),
}

impl fmt::Display for VpnHelperTicketError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidLength { expected, actual } => {
                write!(
                    f,
                    "vpn helper ticket length must be {expected} bytes (got {actual})"
                )
            }
            Self::InvalidMagic => f.write_str("vpn helper ticket magic prefix is invalid"),
            Self::InvalidMac => f.write_str("vpn helper ticket MAC verification failed"),
            Self::Expired {
                expires_at_ms,
                now_ms,
            } => write!(
                f,
                "vpn helper ticket expired at {expires_at_ms}ms (current time {now_ms}ms)"
            ),
            Self::Hex(error) => write!(f, "vpn helper ticket hex decode failed: {error}"),
        }
    }
}

impl std::error::Error for VpnHelperTicketError {}

/// Errors surfaced while building or validating VPN cells.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum VpnCellError {
    /// Flow label exceeded 24-bit bounds.
    FlowLabelOverflow {
        /// Flow label value that exceeded the allowed width.
        value: u32,
        /// Configured bit width.
        max_bits: u8,
    },
    /// Flow label width exceeded the supported range (1–24 bits).
    InvalidFlowLabelBits(u8),
    /// Frame length did not match the pinned cell length.
    FrameLengthMismatch {
        /// Expected padded frame length in bytes.
        expected: usize,
        /// Actual frame length in bytes.
        actual: usize,
    },
    /// Unsupported protocol version encountered while parsing.
    UnsupportedVersion(u8),
    /// Unknown cell class tag encountered while parsing.
    InvalidClass(u8),
    /// Unsupported flag bits were present in the frame header.
    InvalidFlags {
        /// Flags observed in the header.
        bits: u8,
        /// Mask of permitted flag bits.
        allowed: u8,
    },
    /// Payload too large for a single cell.
    PayloadTooLarge {
        /// Maximum payload size permitted for a single cell.
        max: usize,
        /// Actual payload size provided by the caller.
        actual: usize,
    },
    /// Declared payload length exceeded the available bytes in the frame.
    PayloadOverrun {
        /// Payload length declared in the header.
        declared: usize,
        /// Payload bytes available after the header.
        available: usize,
    },
    /// Payload length could not be represented in the header.
    PayloadLengthMismatch {
        /// Payload length that could be encoded into the header field.
        declared: u16,
        /// Actual payload size provided by the caller.
        actual: usize,
    },
    /// Padding bytes after the payload were not zeroed.
    NonZeroPadding {
        /// Index of the first non-zero padding byte.
        index: usize,
        /// Value observed in the padding slot.
        value: u8,
    },
    /// Flags did not align with the advertised cell class.
    FlagClassMismatch {
        /// Advertised class.
        class: VpnCellClassV1,
        /// Flags present on the cell.
        flags: VpnCellFlagsV1,
    },
    /// Padding budget did not match the configured value.
    PaddingBudgetMismatch {
        /// Expected padding budget (milliseconds).
        expected: u16,
        /// Padding budget carried in the header.
        actual: u16,
    },
}

impl fmt::Display for VpnCellError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::FlowLabelOverflow { value, max_bits } => {
                write!(f, "flow label {value:#x} exceeds {max_bits}-bit width")
            }
            Self::InvalidFlowLabelBits(bits) => {
                write!(f, "flow label bits must be between 1 and 24 (got {bits})")
            }
            Self::FrameLengthMismatch { expected, actual } => write!(
                f,
                "padded frame length {actual}B does not match expected {expected}B"
            ),
            Self::UnsupportedVersion(version) => {
                write!(f, "unsupported VPN cell version {version}")
            }
            Self::InvalidClass(tag) => {
                write!(f, "invalid VPN cell class tag {tag}")
            }
            Self::InvalidFlags { bits, allowed } => {
                write!(
                    f,
                    "unsupported VPN flag bits set: {bits:#x} (allowed mask {allowed:#x})"
                )
            }
            Self::PayloadTooLarge { max, actual } => {
                write!(f, "payload {actual}B exceeds cell capacity {max}B")
            }
            Self::PayloadOverrun {
                declared,
                available,
            } => write!(
                f,
                "payload length {declared}B exceeds remaining frame bytes ({available}B available)"
            ),
            Self::PayloadLengthMismatch { declared, actual } => write!(
                f,
                "payload length {actual}B exceeds header field (declared {declared})"
            ),
            Self::NonZeroPadding { index, value } => {
                write!(
                    f,
                    "padding byte at offset {index} was not zeroed (found {value:#x})"
                )
            }
            Self::FlagClassMismatch { class, flags } => write!(
                f,
                "cell flags {:#04x} are inconsistent with class {class:?}",
                flags.bits()
            ),
            Self::PaddingBudgetMismatch { expected, actual } => write!(
                f,
                "padding budget {actual}ms does not match configured {expected}ms"
            ),
        }
    }
}

impl std::error::Error for VpnCellError {}

#[cfg(test)]
mod tests {
    use std::{fs, path::PathBuf};

    use hex::FromHex;
    use norito::{
        derive::{JsonDeserialize, JsonSerialize},
        json::{self, to_string_pretty},
    };

    use super::*;

    const FIXTURE_PATH: &str = "../../IrohaSwift/Tests/IrohaSwiftTests/Fixtures/vpn_vectors.json";

    #[test]
    fn flow_label_roundtrip_respects_bounds() {
        let label = VpnFlowLabelV1::from_u32(0xABCDE).expect("flow label within bounds");
        assert_eq!(0xABCDE, label.to_u32());
        let overflow = VpnFlowLabelV1::from_u32(VpnFlowLabelV1::MAX + 1);
        assert!(matches!(
            overflow,
            Err(VpnCellError::FlowLabelOverflow { max_bits: 24, .. })
        ));
    }

    #[test]
    fn flow_label_respects_requested_width() {
        let narrow = VpnFlowLabelV1::from_u32_with_bits(0xFF, 8).expect("label fits");
        assert_eq!(0xFF, narrow.to_u32());
        let too_wide = VpnFlowLabelV1::from_u32_with_bits(0x1FF, 8);
        assert!(matches!(
            too_wide,
            Err(VpnCellError::FlowLabelOverflow { max_bits: 8, .. })
        ));
    }

    #[test]
    fn parse_rejects_flow_label_overflow_for_width() {
        let mut frame = [0u8; VPN_CELL_LEN];
        // version + class + flags
        frame[0] = 1;
        frame[1] = VpnCellClassV1::Data.tag();
        frame[2] = 0;
        // circuit id
        frame[3..19].copy_from_slice(&[0x11; 16]);
        // flow label set to 0x1FF (9 bits)
        frame[19] = 0;
        frame[20] = 0x01;
        frame[21] = 0xFF;
        // sequence/ack
        frame[22..30].copy_from_slice(&7u64.to_be_bytes());
        frame[30..38].copy_from_slice(&0u64.to_be_bytes());
        // padding budget and payload length = 0
        frame[38..40].copy_from_slice(&1u16.to_be_bytes());
        frame[40..42].copy_from_slice(&0u16.to_be_bytes());

        let result = VpnPaddedCellV1 { bytes: frame }.parse_with_flow_label_bits(8);
        assert!(matches!(
            result,
            Err(VpnCellError::FlowLabelOverflow { max_bits: 8, .. })
        ));
    }

    #[test]
    fn helper_ticket_roundtrips_and_verifies_mac() {
        let secret = [0x42; 32];
        let ticket = VpnHelperTicketV1 {
            session_id: [0xAB; 16],
            expires_at_ms: 1_700_000_000_000,
        };
        let bytes = ticket.to_bytes(&secret);
        assert!(VpnHelperTicketV1::looks_like(&bytes));

        let parsed = VpnHelperTicketV1::parse(&bytes, &secret, 1_699_999_999_000)
            .expect("helper ticket should verify");
        assert_eq!(ticket, parsed);

        let hex = ticket.to_hex(&secret);
        let parsed_hex = VpnHelperTicketV1::parse_hex(&hex, &secret, 1_699_999_999_000)
            .expect("helper ticket hex should verify");
        assert_eq!(ticket, parsed_hex);
    }

    #[test]
    fn helper_ticket_rejects_tampering() {
        let secret = [0x24; 32];
        let ticket = VpnHelperTicketV1 {
            session_id: [0x11; 16],
            expires_at_ms: 55_000,
        };
        let mut bytes = ticket.to_bytes(&secret);
        bytes[VPN_HELPER_TICKET_MAGIC.len() + 3] ^= 0xFF;
        let err = VpnHelperTicketV1::parse(&bytes, &secret, 1).expect_err("tamper must fail");
        assert_eq!(VpnHelperTicketError::InvalidMac, err);
    }

    #[test]
    fn helper_ticket_rejects_expired_ticket() {
        let secret = [0x99; 32];
        let ticket = VpnHelperTicketV1 {
            session_id: [0x77; 16],
            expires_at_ms: 999,
        };
        let bytes = ticket.to_bytes(&secret);
        let err = VpnHelperTicketV1::parse(&bytes, &secret, 1_000).expect_err("expiry must fail");
        assert_eq!(
            VpnHelperTicketError::Expired {
                expires_at_ms: 999,
                now_ms: 1_000,
            },
            err
        );
    }

    #[test]
    fn session_address_plan_is_deterministic_and_split_by_role() {
        let session_id = [0xA5; 16];
        let first = derive_vpn_session_address_plan_v1(session_id);
        let second = derive_vpn_session_address_plan_v1(session_id);
        assert_eq!(first, second);
        assert_eq!(first.server_tunnel_addresses.len(), 2);
        assert_eq!(first.client_tunnel_addresses.len(), 2);
        assert_eq!(first.session_routes.len(), 2);
        assert_ne!(first.server_tunnel_addresses, first.client_tunnel_addresses);
        assert!(first.server_tunnel_addresses[0].ends_with("/30"));
        assert!(first.client_tunnel_addresses[1].ends_with("/126"));
        assert!(first.session_routes[0].ends_with("/30"));
        assert!(first.session_routes[1].ends_with("/126"));
    }

    #[test]
    fn session_address_plan_changes_with_session_id() {
        let first = derive_vpn_session_address_plan_v1([0x01; 16]);
        let second = derive_vpn_session_address_plan_v1([0x02; 16]);
        assert_ne!(
            first.client_tunnel_addresses,
            second.client_tunnel_addresses
        );
        assert_ne!(first.session_routes, second.session_routes);
    }

    #[test]
    fn padded_cell_serializes_header_and_payload() {
        let header = VpnCellHeaderV1 {
            version: 1,
            class: VpnCellClassV1::Data,
            flags: VpnCellFlagsV1::new(false, true, false, false),
            circuit_id: [0xAA; 16],
            flow_label: VpnFlowLabelV1::from_u32(0x00A5_A5A5).expect("flow label"),
            sequence: 42,
            ack: 17,
            padding_budget_ms: 15,
            payload_len: 0,
        };
        let payload = vec![0xBB; 32];
        let cell = VpnCellV1 { header, payload };
        let padded = cell.into_padded_frame().expect("frame padded");
        assert_eq!(VPN_CELL_LEN, padded.bytes.len());
        assert_eq!(1, padded.bytes[0]);
        assert_eq!(VpnCellClassV1::Data.tag(), padded.bytes[1]);
        assert_eq!(VpnCellFlagsV1::REQUIRE_ACK, padded.bytes[2]);
        assert_eq!(&[0xAA; 16], &padded.bytes[3..19]);
        assert_eq!(&[0xA5, 0xA5, 0xA5], &padded.bytes[19..22]);
        assert_eq!(42u64.to_be_bytes(), padded.bytes[22..30]);
        assert_eq!(17u64.to_be_bytes(), padded.bytes[30..38]);
        assert_eq!(15u16.to_be_bytes(), padded.bytes[38..40]);
        assert_eq!(32u16.to_be_bytes(), padded.bytes[40..42]);
        assert_eq!(&[0xBB; 32], &padded.bytes[42..74]);
        assert!(padded.bytes[74..].iter().all(|byte| *byte == 0));
    }

    #[test]
    fn padded_cell_rejects_oversized_payload() {
        let header = VpnCellHeaderV1 {
            version: 1,
            class: VpnCellClassV1::Data,
            flags: VpnCellFlagsV1::new(false, false, false, false),
            circuit_id: [0x11; 16],
            flow_label: VpnFlowLabelV1::from_u32(1).expect("flow label"),
            sequence: 1,
            ack: 0,
            padding_budget_ms: 5,
            payload_len: 0,
        };
        let payload = vec![0u8; VpnCellV1::max_payload_len() + 1];
        let cell = VpnCellV1 { header, payload };
        let result = cell.into_padded_frame();
        assert!(matches!(result, Err(VpnCellError::PayloadTooLarge { .. })));
    }

    #[test]
    fn padded_cell_parses_roundtrip() {
        let header = VpnCellHeaderV1 {
            version: 1,
            class: VpnCellClassV1::KeepAlive,
            flags: VpnCellFlagsV1::new(false, true, false, false),
            circuit_id: [0x22; 16],
            flow_label: VpnFlowLabelV1::from_u32(0x0001_0203).expect("flow label"),
            sequence: 7,
            ack: 6,
            padding_budget_ms: 9,
            payload_len: 0,
        };
        let payload = vec![0xCC; 8];
        let cell = VpnCellV1 {
            header,
            payload: payload.clone(),
        };
        let padded = cell.clone().into_padded_frame().expect("frame padded");
        let parsed = padded.parse().expect("frame parsed");

        assert_eq!(cell.header.version, parsed.header.version);
        assert_eq!(cell.header.class, parsed.header.class);
        assert_eq!(cell.header.flags, parsed.header.flags);
        assert_eq!(cell.header.circuit_id, parsed.header.circuit_id);
        assert_eq!(cell.header.flow_label, parsed.header.flow_label);
        assert_eq!(cell.header.sequence, parsed.header.sequence);
        assert_eq!(cell.header.ack, parsed.header.ack);
        assert_eq!(
            cell.header.padding_budget_ms,
            parsed.header.padding_budget_ms
        );
        assert_eq!(payload.len(), usize::from(parsed.header.payload_len));
        assert_eq!(payload, parsed.payload);
    }

    #[test]
    fn parse_rejects_invalid_class() {
        let header = VpnCellHeaderV1 {
            version: 1,
            class: VpnCellClassV1::Data,
            flags: VpnCellFlagsV1::new(false, false, false, false),
            circuit_id: [0x77; 16],
            flow_label: VpnFlowLabelV1::from_u32(5).expect("flow label"),
            sequence: 1,
            ack: 0,
            padding_budget_ms: 5,
            payload_len: 0,
        };
        let payload = vec![0x12; 4];
        let mut padded = VpnCellV1 { header, payload }
            .into_padded_frame()
            .expect("frame padded");
        padded.bytes[1] = 9;
        let parsed = padded.parse();
        assert!(matches!(parsed, Err(VpnCellError::InvalidClass(9))));
    }

    #[test]
    fn parse_rejects_non_zero_padding() {
        let header = VpnCellHeaderV1 {
            version: 1,
            class: VpnCellClassV1::Data,
            flags: VpnCellFlagsV1::new(false, false, false, false),
            circuit_id: [0x55; 16],
            flow_label: VpnFlowLabelV1::from_u32(5).expect("flow label"),
            sequence: 1,
            ack: 0,
            padding_budget_ms: 3,
            payload_len: 0,
        };
        let mut padded = VpnCellV1 {
            header,
            payload: vec![0x01; 4],
        }
        .into_padded_frame()
        .expect("frame");
        // Scribble a non-zero padding byte beyond the payload length.
        padded.bytes[VPN_HEADER_LEN + 4] = 0xAA;
        let parsed = padded.parse();
        assert!(matches!(
            parsed,
            Err(VpnCellError::NonZeroPadding { index, value })
            if index == VPN_HEADER_LEN + 4 && value == 0xAA
        ));
    }

    #[test]
    fn parse_rejects_unknown_flag_bits() {
        let header = VpnCellHeaderV1 {
            version: 1,
            class: VpnCellClassV1::Control,
            flags: VpnCellFlagsV1::new(false, false, false, false),
            circuit_id: [0x33; 16],
            flow_label: VpnFlowLabelV1::from_u32(9).expect("flow label"),
            sequence: 7,
            ack: 0,
            padding_budget_ms: 3,
            payload_len: 0,
        };
        let payload = vec![0xAB; 2];
        let mut padded = VpnCellV1 { header, payload }
            .into_padded_frame()
            .expect("frame padded");
        // Set a reserved flag bit.
        padded.bytes[2] = 0x80;

        let parsed = padded.parse();
        assert!(matches!(
            parsed,
            Err(VpnCellError::InvalidFlags { bits, .. }) if bits == 0x80
        ));
    }

    #[test]
    fn parse_rejects_payload_overrun() {
        let header = VpnCellHeaderV1 {
            version: 1,
            class: VpnCellClassV1::Data,
            flags: VpnCellFlagsV1::new(false, false, false, false),
            circuit_id: [0x33; 16],
            flow_label: VpnFlowLabelV1::from_u32(9).expect("flow label"),
            sequence: 2,
            ack: 0,
            padding_budget_ms: 5,
            payload_len: 0,
        };
        let payload = vec![0xEF; 4];
        let mut padded = VpnCellV1 { header, payload }
            .into_padded_frame()
            .expect("frame padded");
        let overrun = u16::try_from(VpnCellV1::max_payload_len() + 1).expect("fits in u16");
        padded.bytes[40..42].copy_from_slice(&overrun.to_be_bytes());
        let parsed = padded.parse();
        assert!(matches!(parsed, Err(VpnCellError::PayloadTooLarge { .. })));
    }

    #[test]
    fn parse_rejects_short_frame() {
        let short_frame = vec![0u8; VPN_HEADER_LEN];
        let parsed = VpnPaddedCellV1::parse_bytes(&short_frame);
        assert!(matches!(
            parsed,
            Err(VpnCellError::FrameLengthMismatch { .. })
        ));
    }

    #[test]
    fn parse_rejects_non_zero_padding_trailing() {
        let header = VpnCellHeaderV1 {
            version: 1,
            class: VpnCellClassV1::Data,
            flags: VpnCellFlagsV1::new(false, false, false, false),
            circuit_id: [0x11; 16],
            flow_label: VpnFlowLabelV1::from_u32(1).expect("flow"),
            sequence: 0,
            ack: 0,
            padding_budget_ms: 5,
            payload_len: 0,
        };
        let payload = vec![0xAB; 4];
        let mut frame = VpnCellV1 { header, payload }
            .into_padded_frame()
            .expect("frame");
        let last = VPN_CELL_LEN - 1;
        frame.bytes[last] = 1;

        let parsed = frame.parse();
        assert!(matches!(
            parsed,
            Err(VpnCellError::NonZeroPadding { index, value })
                if index == last && value == 1
        ));
    }

    #[test]
    fn parse_rejects_flag_class_mismatch() {
        let header = VpnCellHeaderV1 {
            version: 1,
            class: VpnCellClassV1::Cover,
            flags: VpnCellFlagsV1::new(false, false, false, false),
            circuit_id: [0x22; 16],
            flow_label: VpnFlowLabelV1::from_u32(3).expect("flow"),
            sequence: 0,
            ack: 0,
            padding_budget_ms: 2,
            payload_len: 0,
        };
        let frame = VpnCellV1 {
            header,
            payload: vec![],
        }
        .into_padded_frame()
        .expect("frame");

        let parsed = frame.parse();
        assert!(matches!(
            parsed,
            Err(VpnCellError::FlagClassMismatch {
                class: VpnCellClassV1::Cover,
                ..
            })
        ));
    }

    #[test]
    fn cover_schedule_is_deterministic() {
        let schedule = VpnCoverScheduleV1 {
            cover_to_data_per_mille: 250,
            heartbeat_ms: 500,
            max_cover_burst: 3,
            jitter_ms: 10,
        };
        let seed = [0xAB; 32];
        let plan = schedule.plan(seed, 5);
        let expected = [
            (1, false),
            (507, false),
            (1_005, false),
            (1_506, true),
            (2_005, true),
        ];
        for (entry, (slot, cover)) in plan.iter().zip(expected) {
            assert_eq!(slot, entry.slot_ms);
            assert_eq!(cover, entry.is_cover);
        }
    }

    #[test]
    fn cover_schedule_consumes_full_seed() {
        let schedule = VpnCoverScheduleV1 {
            cover_to_data_per_mille: 250,
            heartbeat_ms: 500,
            max_cover_burst: 3,
            jitter_ms: 10,
        };
        let seed_a = [0xAB; 32];
        let mut seed_b = seed_a;
        seed_b[31] ^= 0xFF;
        let plan_a = schedule.plan(seed_a, 5);
        let plan_b = schedule.plan(seed_b, 5);
        assert_ne!(plan_a, plan_b);
    }

    #[test]
    fn cover_schedule_resets_after_burst_cap() {
        let schedule = VpnCoverScheduleV1 {
            cover_to_data_per_mille: 1_000,
            heartbeat_ms: 1,
            max_cover_burst: 2,
            jitter_ms: 0,
        };
        let plan = schedule.plan([0x11; 32], 6);
        let expected = [true, true, false, true, true, false];
        for (entry, cover) in plan.iter().zip(expected) {
            assert_eq!(cover, entry.is_cover);
        }
    }

    #[test]
    fn exit_class_accepts_known_labels() {
        let standard = VpnExitClassV1::try_from_label("standard").expect("standard parsed");
        assert_eq!(VpnExitClassV1::Standard, standard);
        assert_eq!("standard", standard.as_label());

        let low = VpnExitClassV1::try_from_label("LOW-LATENCY").expect("low-latency parsed");
        assert_eq!(VpnExitClassV1::LowLatency, low);
        assert_eq!("low-latency", low.as_label());

        let high = VpnExitClassV1::try_from_label("high_security").expect("high_security parsed");
        assert_eq!(VpnExitClassV1::HighSecurity, high);
        assert_eq!("high-security", high.as_label());
    }

    #[test]
    fn exit_class_rejects_unknown_labels() {
        let err = VpnExitClassV1::try_from_label("ultra-fast").expect_err("label rejected");
        assert_eq!("ultra-fast", err.label);
    }

    #[derive(Debug, Clone, PartialEq, Eq, JsonSerialize, JsonDeserialize)]
    struct VpnVectorFixtureFile {
        flow_label_bits: u8,
        vectors: Vec<VpnVectorFixture>,
    }

    #[derive(Debug, Clone, PartialEq, Eq, JsonSerialize, JsonDeserialize)]
    struct VpnVectorFixture {
        name: String,
        class: String,
        flags: u8,
        circuit_id_hex: String,
        flow_label: u32,
        sequence: u64,
        ack: u64,
        padding_budget_ms: u16,
        payload_hex: String,
        frame_hex: String,
    }

    impl VpnVectorFixtureFile {
        fn path() -> PathBuf {
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(FIXTURE_PATH)
        }

        fn load() -> Self {
            let expected = sample_fixture();
            let path = Self::path();
            let data = fs::read_to_string(&path).unwrap_or_else(|error| {
                panic!(
                    "failed to read vpn vector fixture {}: {error}",
                    path.display()
                )
            });
            let actual: VpnVectorFixtureFile =
                json::from_str(&data).expect("vpn vector fixture should parse");
            if actual != expected {
                let value = json::to_value(&expected)
                    .expect("vpn vector fixture should convert to json value");
                let mut rendered =
                    to_string_pretty(&value).expect("vpn vector fixture should render to json");
                rendered.push('\n');
                fs::write(&path, rendered).expect("failed to refresh vpn vector fixture");
                return expected;
            }
            actual
        }

        #[allow(dead_code)]
        fn render() -> String {
            let fixture = sample_fixture();
            let value =
                json::to_value(&fixture).expect("vpn vector fixture should convert to json value");
            let mut rendered =
                to_string_pretty(&value).expect("vpn vector fixture should render to json");
            rendered.push('\n');
            rendered
        }
    }

    impl VpnVectorFixture {
        fn class(&self) -> VpnCellClassV1 {
            match self.class.as_str() {
                "data" => VpnCellClassV1::Data,
                "cover" => VpnCellClassV1::Cover,
                "keep-alive" => VpnCellClassV1::KeepAlive,
                "control" => VpnCellClassV1::Control,
                other => panic!("unknown class label in fixture: {other}"),
            }
        }

        fn circuit_id(&self) -> [u8; 16] {
            let bytes = <Vec<u8>>::from_hex(&self.circuit_id_hex)
                .expect("fixture circuit id hex should decode");
            bytes
                .try_into()
                .expect("fixture circuit id must be 16 bytes")
        }

        fn payload(&self) -> Vec<u8> {
            <Vec<u8>>::from_hex(&self.payload_hex).expect("fixture payload hex should decode")
        }

        fn frame_bytes(&self) -> [u8; VPN_CELL_LEN] {
            let bytes =
                <Vec<u8>>::from_hex(&self.frame_hex).expect("fixture frame hex should decode");
            assert_eq!(
                bytes.len(),
                VPN_CELL_LEN,
                "fixture frame length mismatch: expected {}, found {}",
                VPN_CELL_LEN,
                bytes.len()
            );
            let mut frame = [0u8; VPN_CELL_LEN];
            frame.copy_from_slice(&bytes);
            frame
        }

        fn to_cell(&self) -> VpnCellV1 {
            let flow_label =
                VpnFlowLabelV1::from_u32(self.flow_label).expect("fixture flow label is valid");
            let header = VpnCellHeaderV1 {
                version: 1,
                class: self.class(),
                flags: VpnCellFlagsV1::from_bits(self.flags),
                circuit_id: self.circuit_id(),
                flow_label,
                sequence: self.sequence,
                ack: self.ack,
                padding_budget_ms: self.padding_budget_ms,
                payload_len: 0,
            };
            VpnCellV1 {
                header,
                payload: self.payload(),
            }
        }
    }

    fn sample_fixture() -> VpnVectorFixtureFile {
        let vectors = vec![
            build_vector(
                "data-require-ack",
                VpnCellClassV1::Data,
                VpnCellFlagsV1::new(false, true, false, false),
                [0x11; 16],
                0x00_00_07,
                7,
                0,
                15,
                b"hello-soranet".to_vec(),
            ),
            build_vector(
                "cover-empty",
                VpnCellClassV1::Cover,
                VpnCellFlagsV1::new(true, false, false, false),
                [0x22; 16],
                0x00_02_03,
                4,
                1,
                10,
                Vec::new(),
            ),
            build_vector(
                "control-rotation",
                VpnCellClassV1::Control,
                VpnCellFlagsV1::new(false, true, true, true),
                [0x33; 16],
                0x00_C0_FF_EE,
                42,
                2,
                20,
                b"control-plane-lease".to_vec(),
            ),
        ];
        VpnVectorFixtureFile {
            flow_label_bits: VpnFlowLabelV1::MAX_BITS,
            vectors,
        }
    }

    #[allow(clippy::too_many_arguments)]
    fn build_vector(
        name: &str,
        class: VpnCellClassV1,
        flags: VpnCellFlagsV1,
        circuit_id: [u8; 16],
        flow_label: u32,
        sequence: u64,
        ack: u64,
        padding_budget_ms: u16,
        payload: Vec<u8>,
    ) -> VpnVectorFixture {
        let flow_label =
            VpnFlowLabelV1::from_u32(flow_label).expect("fixture flow label should fit into 24b");
        let header = VpnCellHeaderV1 {
            version: 1,
            class,
            flags,
            circuit_id,
            flow_label,
            sequence,
            ack,
            padding_budget_ms,
            payload_len: 0,
        };
        let cell = VpnCellV1 { header, payload };
        let frame = cell
            .clone()
            .into_padded_frame()
            .expect("fixture frame should pad");
        VpnVectorFixture {
            name: name.to_string(),
            class: class_label(class),
            flags: flags.bits(),
            circuit_id_hex: hex::encode(circuit_id),
            flow_label: flow_label.to_u32(),
            sequence,
            ack,
            padding_budget_ms,
            payload_hex: hex::encode(&cell.payload),
            frame_hex: hex::encode(frame.as_ref()),
        }
    }

    fn class_label(class: VpnCellClassV1) -> String {
        match class {
            VpnCellClassV1::Data => "data",
            VpnCellClassV1::Cover => "cover",
            VpnCellClassV1::KeepAlive => "keep-alive",
            VpnCellClassV1::Control => "control",
        }
        .to_string()
    }

    #[test]
    fn vpn_vector_fixture_matches_generator() {
        let expected = sample_fixture();
        let actual = VpnVectorFixtureFile::load();
        assert_eq!(expected, actual, "vpn vector fixture content drifted");
    }

    #[test]
    fn vpn_vector_fixture_roundtrips() {
        let fixture = VpnVectorFixtureFile::load();
        for vector in fixture.vectors {
            let cell = vector.to_cell();
            cell.header
                .flow_label
                .ensure_width(fixture.flow_label_bits)
                .expect("flow label width should match fixture expectation");
            let frame = cell
                .clone()
                .into_padded_frame()
                .expect("fixture frame should pad");
            assert_eq!(
                vector.frame_hex,
                hex::encode(frame.as_ref()),
                "encoded frame did not match fixture for {}",
                vector.name
            );

            let parsed = VpnPaddedCellV1 {
                bytes: vector.frame_bytes(),
            }
            .parse()
            .expect("fixture frame should parse");

            assert_eq!(
                1, parsed.header.version,
                "version mismatch for {}",
                vector.name
            );
            assert_eq!(
                cell.header.class, parsed.header.class,
                "class mismatch for {}",
                vector.name
            );
            assert_eq!(
                cell.header.flags.bits(),
                parsed.header.flags.bits(),
                "flags mismatch for {}",
                vector.name
            );
            assert_eq!(
                cell.header.circuit_id, parsed.header.circuit_id,
                "circuit_id mismatch for {}",
                vector.name
            );
            assert_eq!(
                cell.header.flow_label, parsed.header.flow_label,
                "flow_label mismatch for {}",
                vector.name
            );
            assert_eq!(
                cell.header.sequence, parsed.header.sequence,
                "sequence mismatch for {}",
                vector.name
            );
            assert_eq!(
                cell.header.ack, parsed.header.ack,
                "ack mismatch for {}",
                vector.name
            );
            assert_eq!(
                cell.header.padding_budget_ms, parsed.header.padding_budget_ms,
                "padding budget mismatch for {}",
                vector.name
            );
            assert_eq!(
                cell.payload.len(),
                usize::from(parsed.header.payload_len),
                "payload_len mismatch for {}",
                vector.name
            );
            assert_eq!(
                cell.payload, parsed.payload,
                "payload mismatch for {}",
                vector.name
            );
        }
    }
}
