[package]
name = "mint_rose_trigger_data_model"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(feature, values("compact-len"))',
    'cfg(feature, values("packed-struct"))',
    'cfg(feature, values("schema-structural"))',
] }

[dependencies]
iroha_data_model = { workspace = true, default-features = false, features = ["application-model"] }
norito = { workspace = true, default-features = false, features = ["base-codec"] }

[features]
default = []
json = []
