[package]
name = "mint_rose_trigger_data_model"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true

[dependencies]
iroha_data_model = { workspace = true, default-features = false, features = ["application-model"] }
norito = { workspace = true, default-features = false, features = ["base-codec"] }
