//! Generate lexical tables from the normative Kotodama V1 lexical grammar.

use std::{collections::BTreeSet, env, fmt::Write as _, fs, path::PathBuf};

fn regex_escape_literal(spelling: &str) -> String {
    let mut escaped = String::with_capacity(spelling.len().saturating_mul(2));
    for character in spelling.chars() {
        if matches!(
            character,
            '\\' | '.' | '^' | '$' | '|' | '?' | '*' | '+' | '(' | ')' | '[' | ']' | '{' | '}'
        ) {
            escaped.push('\\');
        }
        escaped.push(character);
    }
    escaped
}

fn markdown_code(spelling: &str) -> String {
    format!("`{}`", spelling.replace('|', "\\|"))
}

fn main() {
    const SPEC_PATH: &str = "grammar/v1.lex";
    println!("cargo:rerun-if-changed={SPEC_PATH}");
    let spec = fs::read_to_string(SPEC_PATH).expect("read normative Kotodama V1 lexical grammar");
    let mut keywords = Vec::<(String, String)>::new();
    let mut operators = Vec::<(String, String)>::new();
    let mut seen_spellings = BTreeSet::new();

    for (line_index, raw_line) in spec.lines().enumerate() {
        let line = raw_line.trim();
        if line.is_empty() || line.starts_with("//") {
            continue;
        }
        let columns = raw_line.split('\t').collect::<Vec<_>>();
        match columns.as_slice() {
            ["keyword", spelling, variant] => {
                assert!(
                    !spelling.is_empty(),
                    "empty keyword on line {}",
                    line_index + 1
                );
                assert!(
                    variant
                        .chars()
                        .all(|character| character.is_ascii_alphanumeric())
                        && variant
                            .chars()
                            .next()
                            .is_some_and(|character| character.is_ascii_uppercase()),
                    "invalid token variant `{variant}` on line {}",
                    line_index + 1
                );
                assert!(
                    seen_spellings.insert((*spelling).to_owned()),
                    "duplicate lexical spelling `{spelling}` on line {}",
                    line_index + 1
                );
                keywords.push(((*spelling).to_owned(), (*variant).to_owned()));
            }
            ["operator", spelling, variant] => {
                assert!(
                    !spelling.is_empty(),
                    "empty operator on line {}",
                    line_index + 1
                );
                assert!(
                    variant
                        .chars()
                        .all(|character| character.is_ascii_alphanumeric())
                        && variant
                            .chars()
                            .next()
                            .is_some_and(|character| character.is_ascii_uppercase()),
                    "invalid syntax kind `{variant}` on line {}",
                    line_index + 1
                );
                assert!(
                    seen_spellings.insert((*spelling).to_owned()),
                    "duplicate lexical spelling `{spelling}` on line {}",
                    line_index + 1
                );
                operators.push(((*spelling).to_owned(), (*variant).to_owned()));
            }
            _ => panic!(
                "invalid lexical grammar record on line {}: expected tab-separated `keyword<TAB>spelling<TAB>TokenVariant` or `operator<TAB>spelling<TAB>SyntaxKind`",
                line_index + 1
            ),
        }
    }

    for (variant, expected) in [
        ("Seiyaku", ["seiyaku", "誓約"]),
        ("Kotoage", ["kotoage", "言挙げ"]),
        ("Hajimari", ["hajimari", "始まり"]),
        ("Kaizen", ["kaizen", "改善"]),
    ] {
        let actual = keywords
            .iter()
            .filter_map(|(spelling, current_variant)| {
                (current_variant == variant).then_some(spelling.as_str())
            })
            .collect::<Vec<_>>();
        assert_eq!(
            actual.as_slice(),
            expected.as_slice(),
            "the `{variant}` feature must have exactly its romanized and Japanese spellings"
        );
    }
    for forbidden in ["contract", "entry", "init", "upgrade"] {
        assert!(
            !keywords.iter().any(|(spelling, _)| spelling == forbidden),
            "English compatibility alias `{forbidden}` must not enter Kotodama V1"
        );
    }

    let mut generated = String::from(
        "// @generated by crates/kotodama_lang/build.rs from grammar/v1.lex.\n\
         // Do not edit this file directly.\n\n\
         define_v1_keywords! {\n",
    );
    for (spelling, variant) in &keywords {
        writeln!(&mut generated, "    {spelling:?} => {variant},")
            .expect("write generated keyword table");
    }
    generated.push_str("}\n\n");
    generated.push_str(
        "/// Canonical V1 operator and punctuation spellings generated for language tooling.\n\
         pub const V1_OPERATORS: &[&str] = &[\n",
    );
    for (spelling, _) in &operators {
        writeln!(&mut generated, "    {spelling:?},").expect("write generated operator table");
    }
    generated.push_str("];\n\n");

    let mut sorted_operator_kinds = operators.clone();
    sorted_operator_kinds.sort_unstable_by(|left, right| {
        right
            .0
            .len()
            .cmp(&left.0.len())
            .then_with(|| left.0.cmp(&right.0))
    });
    generated.push_str(
        "/// Longest-first scanner table generated from the normative V1 grammar.\n\
         pub(crate) const V1_PUNCTUATION_KINDS: &[(&str, SyntaxKind)] = &[\n",
    );
    for (spelling, variant) in &sorted_operator_kinds {
        writeln!(&mut generated, "    ({spelling:?}, SyntaxKind::{variant}),")
            .expect("write generated punctuation scanner table");
    }
    generated.push_str("];\n\n");

    let keyword_pattern = format!(
        r"(?<![\p{{L}}\p{{N}}_])(?:{})(?![\p{{L}}\p{{N}}_])",
        keywords
            .iter()
            .map(|(spelling, _)| regex_escape_literal(spelling))
            .collect::<Vec<_>>()
            .join("|")
    );
    let operator_pattern = format!(
        "(?:{})",
        sorted_operator_kinds
            .iter()
            .map(|(spelling, _)| regex_escape_literal(spelling))
            .collect::<Vec<_>>()
            .join("|")
    );
    writeln!(
        &mut generated,
        "/// Generated TextMate/LSP matcher for canonical V1 keywords.\npub const V1_KEYWORD_EDITOR_PATTERN: &str = {keyword_pattern:?};"
    )
    .expect("write generated keyword editor pattern");
    writeln!(
        &mut generated,
        "/// Generated TextMate/LSP matcher for canonical V1 operators.\npub const V1_OPERATOR_EDITOR_PATTERN: &str = {operator_pattern:?};"
    )
    .expect("write generated operator editor pattern");

    let mut keyword_docs = String::from("| Spelling | Token |\n| --- | --- |\n");
    for (spelling, variant) in &keywords {
        writeln!(
            &mut keyword_docs,
            "| {} | `{variant}` |",
            markdown_code(spelling)
        )
        .expect("write generated keyword documentation");
    }
    let mut operator_docs = String::from("| Spelling |\n| --- |\n");
    for (spelling, _) in &operators {
        writeln!(&mut operator_docs, "| {} |", markdown_code(spelling))
            .expect("write generated operator documentation");
    }
    writeln!(
        &mut generated,
        "/// Generated normative Markdown keyword table.\npub const V1_KEYWORD_DOC_TABLE: &str = {keyword_docs:?};"
    )
    .expect("write generated keyword documentation constant");
    writeln!(
        &mut generated,
        "/// Generated normative Markdown operator table.\npub const V1_OPERATOR_DOC_TABLE: &str = {operator_docs:?};"
    )
    .expect("write generated operator documentation constant");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("Cargo supplies OUT_DIR"));
    fs::write(out_dir.join("kotodama_v1_lexical.rs"), generated)
        .expect("write generated Kotodama lexical tables");
}
