//! Immutable compiler-captured identities for this source owner’s existing codecs.

#[test]
fn captured_codec_schema_identities() {
    crate::captured_schema_tests::assert_bidirectional::<super::NameSelectorV1>(
        "iroha_data_model::sns::NameSelectorV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::NameRecordV1>(
        "iroha_data_model::sns::NameRecordV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::NameStatus>(
        "iroha_data_model::sns::NameStatus",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::NameFrozenStateV1>(
        "iroha_data_model::sns::NameFrozenStateV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::NameTombstoneStateV1>(
        "iroha_data_model::sns::NameTombstoneStateV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::TokenValue>(
        "iroha_data_model::sns::TokenValue",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::NameAuctionStateV1>(
        "iroha_data_model::sns::NameAuctionStateV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AuctionKind>(
        "iroha_data_model::sns::AuctionKind",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::NameControllerV1>(
        "iroha_data_model::sns::NameControllerV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ControllerType>(
        "iroha_data_model::sns::ControllerType",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PriceTierV1>(
        "iroha_data_model::sns::PriceTierV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ReservedNameV1>(
        "iroha_data_model::sns::ReservedNameV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SuffixFeeSplitV1>(
        "iroha_data_model::sns::SuffixFeeSplitV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SuffixStatus>(
        "iroha_data_model::sns::SuffixStatus",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SuffixPolicyV1>(
        "iroha_data_model::sns::SuffixPolicyV1",
    );
}
