//! Compiler-captured identities for this module’s existing codecs.

/// Check each `super` codec type against its `iroha_crypto::fhe_bfv::` capture row.
macro_rules! assert_captured {
    ($check:ident: $($ty:ident),+ $(,)?) => {
        $(crate::captured_schema_tests::$check::<super::$ty>(concat!(
            "iroha_crypto::fhe_bfv::",
            stringify!($ty)
        ));)+
    };
}

#[test]
fn captured_bidirectional_codec_schema_identities() {
    assert_captured!(assert_bidirectional:
        RamLfeBfvProfileV1,
        BfvProductionSupportBlockerV1,
        BfvParameters,
        BfvRnsModulusChain,
        BfvRnsPolynomial,
        BfvSecretKey,
        BfvPublicKey,
        BfvRelinearizationKeyEntry,
        BfvRelinearizationKey,
        BfvGaloisKey,
        BfvRotationKey,
        BfvBootstrapKeyMode,
        BfvFullBootstrapCircuitMaterialV1,
        BfvFullBootstrapCircuitArtifactRoleV1,
        BfvFullBootstrapCircuitArtifactPayloadV1,
        BfvFullBootstrapExecutionProofBoundModeV1,
        BfvFullBootstrapExecutionProofClaimV1,
        BfvFullBootstrapArithmeticTraceProfileV1,
        BfvFullBootstrapArithmeticTraceMaterialV1,
        BfvFullBootstrapArithmeticAirEvaluationMaterialV1,
        BfvFullBootstrapArithmeticTracePublicOpeningMaterialV1,
        BfvFullBootstrapProofPublicInputSchemaV1,
        BfvFullBootstrapReleaseProverContractMaterialV1,
        BfvFullBootstrapProofKeyV1,
        BfvFullBootstrapNativeProofKeyMaterialV1,
        BfvFullBootstrapNativeGeneratedCircuitBodyV1,
        BfvFullBootstrapNativeStarkFriTransparentProverPayloadV1,
        BfvFullBootstrapNativeStarkFriVerifyingKeyPayloadV1,
        BfvFullBootstrapProofKeyMaterialEnvelopeV1,
        BfvFullBootstrapLinearTransformDiagonalV1,
        BfvFullBootstrapLinearTransformV1,
        BfvFullBootstrapBlindRotationStepV1,
        BfvFullBootstrapBlindRotationKeyV1,
        BfvFullBootstrapSampleExtractionV1,
        BfvFullBootstrapSampleExtractionSwitchKeyCoefficientV1,
        BfvFullBootstrapSampleExtractionSwitchKeyV1,
        BfvFullBootstrapRawExtractedSampleV1,
        BfvFullBootstrapExecutionPrefixTraceV1,
        BfvFullBootstrapExecutionPrefixTraceBoundsV1,
        BfvFullBootstrapAccumulatorV1,
        BfvFullBootstrapCircuitArtifactBundleV1,
        BfvFullBootstrapReleaseAuditProofProfileV1,
        BfvFullBootstrapReleaseAuditKeyEvidenceV1,
        BfvFullBootstrapReleaseAuditEvidenceV1,
        BfvFullBootstrapReleaseAuditSignoffPayloadV1,
        BfvFullBootstrapReleaseAuditSignoffV1,
        BfvFullBootstrapReleaseAuditRecordV1,
        BfvFullBootstrapReleaseAuditVerdictV1,
        BfvFullBootstrapReleaseAuditManifestV1,
        BfvFullBootstrapReleaseAuditPackageV1,
        BfvBootstrapKey,
        BfvEvaluationKeyBundle,
        BfvFullBootstrapMaterialProofInputMaterialV1,
        BfvFullBootstrapExecutionWitnessDigestMaterialV1,
        BfvFullBootstrapExecutionProofInputMaterialV1,
        BfvFullBootstrapExecutionProverInputMaterialV1,
        BfvFullBootstrapArithmeticAirConstraintSystemMaterialV1,
        BfvCiphertext,
        BfvExactResidualPublicKeyProofInputMaterialV1,
        BfvExactResidualCiphertextProofInputMaterialV1,
        BfvBoundedNoisePublicKeyProofInputMaterialV1,
        BfvBoundedNoiseCiphertextProofInputMaterialV1,
        BfvIdentifierPublicParameters,
        BfvIdentifierCiphertext,
        BfvAffineCircuit,
    );
}

#[test]
fn captured_serialize_only_codec_schema_identities() {
    assert_captured!(assert_serialize:
        BfvRotationKeyTranscriptDigestMaterial,
        BfvBootstrapKeyTranscriptDigestMaterial,
        BfvPublicKeyDigestMaterial,
        BfvCiphertextDigestMaterial,
        BfvPublicKeyProofStatementMaterial,
        BfvCiphertextProofStatementMaterial,
        BfvRefreshTranscriptDigestMaterial,
        BfvBootstrapKeyProofStatementMaterial,
        BfvBootstrapKeyTranscriptProofStatementMaterial,
        BfvFullBootstrapMaterialProofStatementMaterial,
        BfvFullBootstrapExecutionProofStatementMaterial,
        BfvFullBootstrapCircuitArtifactBundleDigestMaterialV1,
        BfvFullBootstrapEvaluatorArtifactSetDigestMaterialV1,
        BfvFullBootstrapNativeProofCircuitFingerprintMaterialV1,
    );
}
