//! Compiler-captured identities for this module’s existing codecs.

#[test]
fn captured_codec_schema_identities() {
    crate::captured_schema_tests::assert_bidirectional::<super::RamLfeBfvProfileV1>(
        "iroha_crypto::fhe_bfv::RamLfeBfvProfileV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::BfvProductionQualificationBlockerV1>(
        "iroha_crypto::fhe_bfv::BfvProductionQualificationBlockerV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::BfvParameters>(
        "iroha_crypto::fhe_bfv::BfvParameters",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::BfvRnsModulusChain>(
        "iroha_crypto::fhe_bfv::BfvRnsModulusChain",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::BfvRnsPolynomial>(
        "iroha_crypto::fhe_bfv::BfvRnsPolynomial",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::BfvSecretKey>(
        "iroha_crypto::fhe_bfv::BfvSecretKey",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::BfvPublicKey>(
        "iroha_crypto::fhe_bfv::BfvPublicKey",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::BfvRelinearizationKeyEntry>(
        "iroha_crypto::fhe_bfv::BfvRelinearizationKeyEntry",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::BfvRelinearizationKey>(
        "iroha_crypto::fhe_bfv::BfvRelinearizationKey",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::BfvGaloisKey>(
        "iroha_crypto::fhe_bfv::BfvGaloisKey",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::BfvRotationKey>(
        "iroha_crypto::fhe_bfv::BfvRotationKey",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::BfvBootstrapKeyMode>(
        "iroha_crypto::fhe_bfv::BfvBootstrapKeyMode",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::BfvFullBootstrapCircuitMaterialV1>(
        "iroha_crypto::fhe_bfv::BfvFullBootstrapCircuitMaterialV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapCircuitArtifactRoleV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapCircuitArtifactRoleV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapCircuitArtifactPayloadV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapCircuitArtifactPayloadV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapExecutionProofBoundModeV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapExecutionProofBoundModeV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapExecutionProofClaimV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapExecutionProofClaimV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapArithmeticTraceProfileV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapArithmeticTraceProfileV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapArithmeticTraceMaterialV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapArithmeticTraceMaterialV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapArithmeticAirEvaluationMaterialV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapArithmeticAirEvaluationMaterialV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapArithmeticTracePublicOpeningMaterialV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapArithmeticTracePublicOpeningMaterialV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapProofPublicInputSchemaV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapProofPublicInputSchemaV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapReleaseProverContractMaterialV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapReleaseProverContractMaterialV1");
    crate::captured_schema_tests::assert_bidirectional::<super::BfvFullBootstrapProofKeyV1>(
        "iroha_crypto::fhe_bfv::BfvFullBootstrapProofKeyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapNativeProofKeyMaterialV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapNativeProofKeyMaterialV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapNativeGeneratedCircuitBodyV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapNativeGeneratedCircuitBodyV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapNativeStarkFriTransparentProverPayloadV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapNativeStarkFriTransparentProverPayloadV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapNativeStarkFriVerifyingKeyPayloadV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapNativeStarkFriVerifyingKeyPayloadV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapProofKeyMaterialEnvelopeV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapProofKeyMaterialEnvelopeV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapLinearTransformDiagonalV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapLinearTransformDiagonalV1");
    crate::captured_schema_tests::assert_bidirectional::<super::BfvFullBootstrapLinearTransformV1>(
        "iroha_crypto::fhe_bfv::BfvFullBootstrapLinearTransformV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::BfvFullBootstrapBlindRotationStepV1>(
        "iroha_crypto::fhe_bfv::BfvFullBootstrapBlindRotationStepV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::BfvFullBootstrapBlindRotationKeyV1>(
        "iroha_crypto::fhe_bfv::BfvFullBootstrapBlindRotationKeyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::BfvFullBootstrapSampleExtractionV1>(
        "iroha_crypto::fhe_bfv::BfvFullBootstrapSampleExtractionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapSampleExtractionSwitchKeyCoefficientV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapSampleExtractionSwitchKeyCoefficientV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapSampleExtractionSwitchKeyV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapSampleExtractionSwitchKeyV1");
    crate::captured_schema_tests::assert_bidirectional::<super::BfvFullBootstrapRawExtractedSampleV1>(
        "iroha_crypto::fhe_bfv::BfvFullBootstrapRawExtractedSampleV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapExecutionPrefixTraceV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapExecutionPrefixTraceV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapExecutionPrefixTraceBoundsV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapExecutionPrefixTraceBoundsV1");
    crate::captured_schema_tests::assert_bidirectional::<super::BfvFullBootstrapAccumulatorV1>(
        "iroha_crypto::fhe_bfv::BfvFullBootstrapAccumulatorV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapCircuitArtifactBundleV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapCircuitArtifactBundleV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapReleaseAuditProofProfileV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapReleaseAuditProofProfileV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapReleaseAuditKeyEvidenceV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapReleaseAuditKeyEvidenceV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapReleaseAuditEvidenceV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapReleaseAuditEvidenceV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapReleaseAuditSignoffPayloadV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapReleaseAuditSignoffPayloadV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapReleaseAuditSignoffV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapReleaseAuditSignoffV1");
    crate::captured_schema_tests::assert_bidirectional::<super::BfvFullBootstrapReleaseAuditRecordV1>(
        "iroha_crypto::fhe_bfv::BfvFullBootstrapReleaseAuditRecordV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapReleaseAuditVerdictV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapReleaseAuditVerdictV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapReleaseAuditManifestV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapReleaseAuditManifestV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapReleaseAuditPackageV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapReleaseAuditPackageV1");
    crate::captured_schema_tests::assert_bidirectional::<super::BfvBootstrapKey>(
        "iroha_crypto::fhe_bfv::BfvBootstrapKey",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::BfvEvaluationKeyBundle>(
        "iroha_crypto::fhe_bfv::BfvEvaluationKeyBundle",
    );
    crate::captured_schema_tests::assert_serialize::<super::BfvRotationKeyTranscriptDigestMaterial>(
        "iroha_crypto::fhe_bfv::BfvRotationKeyTranscriptDigestMaterial",
    );
    crate::captured_schema_tests::assert_serialize::<super::BfvBootstrapKeyTranscriptDigestMaterial>(
        "iroha_crypto::fhe_bfv::BfvBootstrapKeyTranscriptDigestMaterial",
    );
    crate::captured_schema_tests::assert_serialize::<super::BfvPublicKeyDigestMaterial>(
        "iroha_crypto::fhe_bfv::BfvPublicKeyDigestMaterial",
    );
    crate::captured_schema_tests::assert_serialize::<super::BfvCiphertextDigestMaterial>(
        "iroha_crypto::fhe_bfv::BfvCiphertextDigestMaterial",
    );
    crate::captured_schema_tests::assert_serialize::<super::BfvPublicKeyProofStatementMaterial>(
        "iroha_crypto::fhe_bfv::BfvPublicKeyProofStatementMaterial",
    );
    crate::captured_schema_tests::assert_serialize::<super::BfvCiphertextProofStatementMaterial>(
        "iroha_crypto::fhe_bfv::BfvCiphertextProofStatementMaterial",
    );
    crate::captured_schema_tests::assert_serialize::<super::BfvRefreshTranscriptDigestMaterial>(
        "iroha_crypto::fhe_bfv::BfvRefreshTranscriptDigestMaterial",
    );
    crate::captured_schema_tests::assert_serialize::<super::BfvBootstrapKeyProofStatementMaterial>(
        "iroha_crypto::fhe_bfv::BfvBootstrapKeyProofStatementMaterial",
    );
    crate::captured_schema_tests::assert_serialize::<
        super::BfvBootstrapKeyTranscriptProofStatementMaterial,
    >("iroha_crypto::fhe_bfv::BfvBootstrapKeyTranscriptProofStatementMaterial");
    crate::captured_schema_tests::assert_serialize::<
        super::BfvFullBootstrapMaterialProofStatementMaterial,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapMaterialProofStatementMaterial");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapMaterialProofInputMaterialV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapMaterialProofInputMaterialV1");
    crate::captured_schema_tests::assert_serialize::<
        super::BfvFullBootstrapExecutionProofStatementMaterial,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapExecutionProofStatementMaterial");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapExecutionWitnessDigestMaterialV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapExecutionWitnessDigestMaterialV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapExecutionProofInputMaterialV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapExecutionProofInputMaterialV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapExecutionProverInputMaterialV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapExecutionProverInputMaterialV1");
    crate::captured_schema_tests::assert_serialize::<
        super::BfvFullBootstrapCircuitArtifactBundleDigestMaterialV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapCircuitArtifactBundleDigestMaterialV1");
    crate::captured_schema_tests::assert_serialize::<
        super::BfvFullBootstrapEvaluatorArtifactSetDigestMaterialV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapEvaluatorArtifactSetDigestMaterialV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvFullBootstrapArithmeticAirConstraintSystemMaterialV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapArithmeticAirConstraintSystemMaterialV1");
    crate::captured_schema_tests::assert_serialize::<
        super::BfvFullBootstrapNativeProofCircuitFingerprintMaterialV1,
    >("iroha_crypto::fhe_bfv::BfvFullBootstrapNativeProofCircuitFingerprintMaterialV1");
    crate::captured_schema_tests::assert_bidirectional::<super::BfvCiphertext>(
        "iroha_crypto::fhe_bfv::BfvCiphertext",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvExactResidualPublicKeyProofInputMaterialV1,
    >("iroha_crypto::fhe_bfv::BfvExactResidualPublicKeyProofInputMaterialV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvExactResidualCiphertextProofInputMaterialV1,
    >("iroha_crypto::fhe_bfv::BfvExactResidualCiphertextProofInputMaterialV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvBoundedNoisePublicKeyProofInputMaterialV1,
    >("iroha_crypto::fhe_bfv::BfvBoundedNoisePublicKeyProofInputMaterialV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::BfvBoundedNoiseCiphertextProofInputMaterialV1,
    >("iroha_crypto::fhe_bfv::BfvBoundedNoiseCiphertextProofInputMaterialV1");
    crate::captured_schema_tests::assert_bidirectional::<super::BfvIdentifierPublicParameters>(
        "iroha_crypto::fhe_bfv::BfvIdentifierPublicParameters",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::BfvIdentifierCiphertext>(
        "iroha_crypto::fhe_bfv::BfvIdentifierCiphertext",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::BfvAffineCircuit>(
        "iroha_crypto::fhe_bfv::BfvAffineCircuit",
    );
}
