//! Joint publication keeps both original maps and identity ahead of cleanup.

use super::*;
use crate::allocation::{AllocationBudget, AllocationCharge, AllocationReservation};
use concread::bptree::{
    AllocationDemand, ClonePlanning, NodeCloning, NodeFunding, PlanningError, Prepaid,
};
use std::{
    alloc::Layout,
    future::Future,
    sync::{
        Arc, Mutex,
        atomic::{AtomicUsize, Ordering::SeqCst},
    },
    task::{Context, Poll, Wake, Waker},
};

fn replacement_fixture(
    budget: &AllocationBudget,
) -> (Storage<u64, u64, Prepaid<Policy>>, Arc<Records>) {
    let records = Arc::new(Records {
        live: Mutex::new(Vec::new()),
        panic_on: AtomicUsize::new(usize::MAX),
    });
    let provider = |reservation| Policy {
        reservation,
        records: Arc::clone(&records),
        component: 0,
    };
    let storage = Storage::try_new_with_node_custody(budget, provider).unwrap();
    budget.with_deferred_refund_notifications(|| {
        let mut block = storage.try_block_admitted(budget, provider).unwrap();
        let mut tx = block.try_transaction().unwrap();
        for (key, value) in [(1, 10), (2, 20), (4, 40)] {
            tx.try_insert_admitted(key, value, budget, provider)
                .unwrap();
        }
        tx.apply();
        block.commit();
        let mut block = storage.try_block_admitted(budget, provider).unwrap();
        let mut tx = block.try_transaction().unwrap();
        assert_eq!(
            tx.try_remove_admitted(&1, budget, provider).unwrap(),
            Some(10)
        );
        tx.try_insert_admitted(2, 21, budget, provider).unwrap();
        tx.try_insert_admitted(3, 30, budget, provider).unwrap();
        tx.apply();
        block.commit();
    });
    (storage, records)
}

#[test]
fn admitted_replacement_retains_mode_and_restored_preimages_through_detachment() {
    let budget = AllocationBudget::new(1 << 20);
    let (storage, records) = replacement_fixture(&budget);
    let provider = |reservation| Policy {
        reservation,
        records: Arc::clone(&records),
        component: 0,
    };
    let current = storage.blocks.read();
    let undo = storage.revert.read();
    let predecessor = storage.publication.capture();
    budget.with_deferred_refund_notifications(|| {
        let mut block = storage
            .try_block_and_revert_admitted(&budget, provider)
            .unwrap();
        assert_eq!(block.mode(), BlockMode::Replace);
        assert!(block.is_dirty());
        assert_eq!(
            block.iter().map(|(k, v)| (*k, *v)).collect::<Vec<_>>(),
            [(1, 10), (2, 20), (4, 40)]
        );
        assert!(block.revert_map().is_empty());
        let mut tx = block.try_transaction().unwrap();
        tx.try_insert_admitted(2, 22, &budget, provider).unwrap();
        tx.try_insert_admitted(3, 33, &budget, provider).unwrap();
        tx.apply();
        assert_eq!(block.get_before_block(&2), Some(&20));
        assert_eq!(block.get_before_block(&3), None);
        let detached = block.try_detach(|_| Ok::<_, ()>(())).unwrap();
        assert_eq!(detached.mode(), BlockMode::Replace);
        let prepared = detached
            .try_prepare_publication(&storage, |_, _| Ok::<_, ()>(()))
            .unwrap_or_else(|_| panic!("same original roots"));
        let detached = prepared.abort();
        assert_eq!(
            predecessor.try_check_current::<()>(&storage.publication),
            Ok(())
        );
        assert_eq!(current.get(&2), Some(&21));
        assert_eq!(undo.get(&2), Some(&Some(20)));
        let prepared = detached
            .try_prepare_publication(&storage, |_, _| Ok::<_, ()>(()))
            .unwrap_or_else(|_| panic!("abort retains exact original successors"));
        prepared.publish();
        assert_eq!(
            storage
                .blocks
                .read()
                .iter()
                .map(|(k, v)| (*k, *v))
                .collect::<Vec<_>>(),
            [(1, 10), (2, 22), (3, 33), (4, 40)]
        );
        assert_eq!(
            storage
                .revert
                .read()
                .iter()
                .map(|(k, v)| (*k, *v))
                .collect::<Vec<_>>(),
            [(2, Some(20)), (3, None)]
        );
        // Replacing the replacement starts from its own predecessor, not from
        // the discarded block or a preimage generated by the rollback itself.
        let next = storage
            .try_block_and_revert_admitted(&budget, provider)
            .unwrap();
        assert_eq!(
            next.iter().map(|(k, v)| (*k, *v)).collect::<Vec<_>>(),
            [(1, 10), (2, 20), (4, 40)]
        );
        drop(next);
    });
    assert_eq!(current.get(&2), Some(&21));
    assert_eq!(undo.get(&1), Some(&Some(10)));
    drop(current);
    drop(undo);
    drop(storage);
    assert_eq!(budget.reserved_bytes(), 0);
}

#[test]
fn admitted_replacement_contention_names_only_the_original_held_writer() {
    for hold_undo in [false, true] {
        let budget = AllocationBudget::new(1 << 20);
        let (storage, records) = replacement_fixture(&budget);
        let provider = |reservation| Policy {
            reservation,
            records: Arc::clone(&records),
            component: 0,
        };
        budget.with_deferred_refund_notifications(|| {
            // Different value types prevent one guard variable; retain each
            // original owner in its own optional slot instead.
            let undo = hold_undo.then(|| storage.try_block_admitted(&budget, provider).unwrap());
            let current = (!hold_undo).then(|| {
                storage.blocks_released.poisoning_guard(
                    storage
                        .blocks
                        .try_write_admitted(|demand| {
                            Ok::<_, ()>(provider(budget.try_reserve_bytes(demand.bytes()).unwrap()))
                        })
                        .unwrap(),
                )
            });
            let expected = if hold_undo {
                storage.revert_released.observe()
            } else {
                storage.blocks_released.observe()
            };
            let predecessor = storage.publication.capture();
            let before = budget.reserved_bytes();
            let error = storage
                .try_block_and_revert_admitted(&budget, |_| {
                    panic!("held writer refuses before allocation")
                })
                .err()
                .unwrap();
            let admitted::StorageAdmissionError::Busy(wait) = error else {
                panic!("expected original release dependency");
            };
            assert_eq!(wait, expected);
            assert_eq!(budget.reserved_bytes(), before);
            assert_eq!(
                predecessor.try_check_current::<()>(&storage.publication),
                Ok(())
            );
            let mut future = std::pin::pin!(wait.wait_for_release());
            assert!(
                future
                    .as_mut()
                    .poll(&mut Context::from_waker(Waker::noop()))
                    .is_pending()
            );
            drop(undo);
            drop(current);
            assert!(
                future
                    .as_mut()
                    .poll(&mut Context::from_waker(Waker::noop()))
                    .is_ready()
            );
            let block = storage
                .try_block_and_revert_admitted(&budget, provider)
                .unwrap();
            assert_eq!(block.get(&1), Some(&10));
            assert_eq!(block.get(&2), Some(&20));
            assert!(block.get(&3).is_none());
            drop(block);
        });
        drop(storage);
        assert_eq!(budget.reserved_bytes(), 0);
    }
}

#[test]
fn admitted_replacement_of_empty_undo_still_records_replace_mode() {
    let budget = AllocationBudget::new(1 << 20);
    let (storage, records) = replacement_fixture(&budget);
    let provider = |reservation| Policy {
        reservation,
        records: Arc::clone(&records),
        component: 0,
    };
    budget.with_deferred_refund_notifications(|| {
        storage
            .try_block_admitted(&budget, provider)
            .unwrap()
            .commit();
        let predecessor = storage.publication.capture();
        let block = storage
            .try_block_and_revert_admitted(&budget, provider)
            .unwrap();
        assert_eq!(block.mode(), BlockMode::Replace);
        assert!(block.is_dirty());
        assert!(block.revert_map().is_empty());
        assert_eq!(block.get(&2), Some(&21));
        block.commit();
        assert_eq!(
            predecessor.try_check_current::<()>(&storage.publication),
            Err(PublicationPreparationError::Changed)
        );
    });
    drop(storage);
    assert_eq!(budget.reserved_bytes(), 0);
}

#[test]
fn admitted_replacement_final_undo_clear_refusal_preserves_original_pair() {
    let budget = AllocationBudget::new(1 << 20);
    let (storage, records) = replacement_fixture(&budget);
    let provider = |reservation| Policy {
        reservation,
        records: Arc::clone(&records),
        component: 0,
    };
    budget.with_deferred_refund_notifications(|| {
        // The unchanged block leaves an empty undo tree. Replacement still
        // needs a newly admitted empty root before its owner can escape.
        storage
            .try_block_admitted(&budget, provider)
            .unwrap()
            .commit();
        let predecessor = storage.publication.capture();
        let before = budget.reserved_bytes();
        let mut held = None;
        let mut calls = 0;
        let error = storage
            .try_block_and_revert_admitted(&budget, |reservation| {
                calls += 1;
                if calls == 2 {
                    held = Some(
                        budget
                            .try_reserve_bytes(budget.limit_bytes() - budget.reserved_bytes())
                            .unwrap(),
                    );
                }
                provider(reservation)
            })
            .err()
            .unwrap();
        assert!(matches!(
            error,
            admitted::StorageAdmissionError::Capacity(_)
        ));
        assert_eq!(
            calls, 2,
            "the final clear refuses after both original shells"
        );
        assert_eq!(
            predecessor.try_check_current::<()>(&storage.publication),
            Ok(())
        );
        assert_eq!(storage.blocks.read().get(&2), Some(&21));
        assert!(storage.revert.read().is_empty());
        drop(held);
        assert_eq!(budget.reserved_bytes(), before);
        storage
            .try_block_and_revert_admitted(&budget, provider)
            .unwrap()
            .commit();
    });
    drop(storage);
    assert_eq!(budget.reserved_bytes(), 0);
}

#[test]
fn admitted_replacement_factory_cleanup_cannot_return_a_partial_owner() {
    struct FactoryCleanup;
    impl FactoryCleanup {
        fn retain(&self) {}
    }
    impl Drop for FactoryCleanup {
        fn drop(&mut self) {
            panic!("injected factory cleanup failure");
        }
    }
    let budget = AllocationBudget::new(1 << 20);
    let (storage, records) = replacement_fixture(&budget);
    let provider = |reservation| Policy {
        reservation,
        records: Arc::clone(&records),
        component: 0,
    };
    let before = budget.reserved_bytes();
    let predecessor = storage.publication.capture();
    budget.with_deferred_refund_notifications(|| {
        let bomb = FactoryCleanup;
        let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            let _ = storage.try_block_and_revert_admitted(&budget, move |reservation| {
                bomb.retain();
                provider(reservation)
            });
        }));
        assert!(result.is_err());
        assert_eq!(budget.reserved_bytes(), before);
        assert_eq!(
            predecessor.try_check_current::<()>(&storage.publication),
            Ok(())
        );
        assert_eq!(storage.blocks.read().get(&2), Some(&21));
        assert_eq!(storage.revert.read().get(&2), Some(&Some(20)));
        assert!(storage.revert_released.observe().is_poisoned());
        assert!(storage.blocks_released.observe().is_poisoned());
        let error = storage
            .try_block_and_revert_admitted(&budget, |_| {
                panic!("poison refuses before policy construction")
            })
            .err()
            .unwrap();
        assert!(matches!(error, admitted::StorageAdmissionError::Poisoned));
    });
    drop(storage);
    assert_eq!(budget.reserved_bytes(), 0);
}

struct Records {
    live: Mutex<Vec<(usize, bool, usize)>>,
    panic_on: AtomicUsize,
}
struct Charge {
    credit: AllocationCharge,
    id: usize,
    records: Arc<Records>,
}
impl Drop for Charge {
    fn drop(&mut self) {
        self.records.live.lock().unwrap()[self.id].1 = false;
        assert!(
            self.records
                .panic_on
                .compare_exchange(self.id, usize::MAX, SeqCst, SeqCst)
                .is_err(),
            "injected first current-map retirement panic"
        );
        // Original credit stays owned until the containing charge drops.
        let _ = self.credit.layout();
    }
}
struct Policy {
    reservation: AllocationReservation,
    records: Arc<Records>,
    component: usize,
}
impl NodeFunding for Policy {
    type Charge = Charge;
    fn take_node_charge(&mut self, layout: Layout) -> Charge {
        let mut records = self.records.live.lock().unwrap();
        let id = records.len();
        records.push((layout.size(), true, self.component));
        Charge {
            credit: self.reservation.try_split(layout).unwrap(),
            id,
            records: Arc::clone(&self.records),
        }
    }
}
impl NodeCloning<u64, u64> for Policy {
    fn clone_key(&mut self, key: &u64) -> u64 {
        *key
    }
    fn clone_value(&mut self, value: &u64) -> u64 {
        REPLACEMENT_REPLAN.with(|mode| match mode.get() {
            1 => mode.set(2),
            3 => mode.set(4),
            _ => {}
        });
        *value
    }
}
impl ClonePlanning<u64, u64> for Policy {
    fn plan_key(_: &u64, demand: &mut AllocationDemand) -> Result<(), PlanningError> {
        match REPLACEMENT_REPLAN.with(|mode| mode.get()) {
            2 => Err(PlanningError::UnsupportedPayload),
            4 => demand.add_layout(Layout::new::<u64>()),
            _ => Ok(()),
        }
    }
    fn plan_value(value: &u64, _: &mut AllocationDemand) -> Result<(), PlanningError> {
        if REFUSED_REPLACEMENT_VALUE.with(|refused| refused.get()) == Some(*value) {
            Err(PlanningError::UnsupportedPayload)
        } else {
            Ok(())
        }
    }
}

thread_local! {
    static REFUSED_REPLACEMENT_VALUE: std::cell::Cell<Option<u64>> = const { std::cell::Cell::new(None) };
    static REPLACEMENT_REPLAN: std::cell::Cell<u8> = const { std::cell::Cell::new(0) };
}

#[test]
fn admitted_replacement_second_plan_refusal_returns_a_healthy_original_pair() {
    for mode in [1, 3] {
        let budget = AllocationBudget::new(1 << 20);
        let (storage, records) = replacement_fixture(&budget);
        let provider = |reservation| Policy {
            reservation,
            records: Arc::clone(&records),
            component: 0,
        };
        let before = budget.reserved_bytes();
        let predecessor = storage.publication.capture();
        budget.with_deferred_refund_notifications(|| {
            // The first plan succeeds; incoming value cloning changes only the
            // test policy. The second plan must return its typed refusal.
            REPLACEMENT_REPLAN.with(|state| state.set(mode));
            let error = storage
                .try_block_and_revert_admitted(&budget, provider)
                .err()
                .unwrap();
            REPLACEMENT_REPLAN.with(|state| state.set(0));
            match (mode, error) {
                (
                    1,
                    admitted::StorageAdmissionError::Planning(PlanningError::UnsupportedPayload),
                )
                | (3, admitted::StorageAdmissionError::Changed) => {}
                (_, error) => panic!("replanning lost its original refusal: {error:?}"),
            }
            assert_eq!(budget.reserved_bytes(), before);
            assert_eq!(
                predecessor.try_check_current::<()>(&storage.publication),
                Ok(())
            );
            assert_eq!(storage.blocks.read().get(&2), Some(&21));
            assert_eq!(storage.revert.read().get(&2), Some(&Some(20)));
            let retry = storage
                .try_block_and_revert_admitted(&budget, provider)
                .unwrap();
            assert_eq!(retry.get(&1), Some(&10));
            assert_eq!(retry.get(&2), Some(&20));
            assert!(retry.get(&3).is_none());
            drop(retry);
        });
        drop(storage);
        assert_eq!(budget.reserved_bytes(), 0);
    }
}

#[test]
fn admitted_replacement_planning_refusal_discards_the_restored_private_prefix() {
    let budget = AllocationBudget::new(1 << 20);
    let (storage, records) = replacement_fixture(&budget);
    let provider = |reservation| Policy {
        reservation,
        records: Arc::clone(&records),
        component: 0,
    };
    let before = budget.reserved_bytes();
    let predecessor = storage.publication.capture();
    let current = storage.blocks.read();
    let undo = storage.revert.read();
    budget.with_deferred_refund_notifications(|| {
        // 20 exists only in the second undo entry. The first preimage (1, 10)
        // must already have been restored before this policy refuses.
        REFUSED_REPLACEMENT_VALUE.with(|refused| refused.set(Some(20)));
        let mut calls = 0;
        let error = storage
            .try_block_and_revert_admitted(&budget, |reservation| {
                calls += 1;
                provider(reservation)
            })
            .err()
            .unwrap();
        REFUSED_REPLACEMENT_VALUE.with(|refused| refused.set(None));
        assert!(matches!(
            error,
            admitted::StorageAdmissionError::Planning(PlanningError::UnsupportedPayload)
        ));
        assert!(calls > 2, "refusal must follow a real private restoration");
        assert_eq!(budget.reserved_bytes(), before);
        assert_eq!(
            predecessor.try_check_current::<()>(&storage.publication),
            Ok(())
        );
        assert_eq!(storage.blocks.read().get(&2), Some(&21));
        assert_eq!(storage.revert.read().get(&2), Some(&Some(20)));
        let block = storage
            .try_block_and_revert_admitted(&budget, provider)
            .unwrap();
        assert_eq!(block.get(&1), Some(&10));
        assert_eq!(block.get(&2), Some(&20));
        assert!(block.get(&3).is_none());
        drop(block);
    });
    assert_eq!(current.get(&2), Some(&21));
    assert_eq!(undo.get(&2), Some(&Some(20)));
    drop(current);
    drop(undo);
    drop(storage);
    assert_eq!(budget.reserved_bytes(), 0);
}

struct WakeCount(AtomicUsize);
impl Wake for WakeCount {
    fn wake(self: Arc<Self>) {
        self.0.fetch_add(1, SeqCst);
    }
}

// The retirement panic happened after publication released physical locks.
// Later real contention must retain its own live release observation, not a
// sticky poison hint inherited from destruction of the old retirement owner.
fn assert_healthy_contention<T>(
    storage: &Storage<u64, u64, Prepaid<Policy>>,
    budget: &AllocationBudget,
    records: &Arc<Records>,
    notification: &ReleaseNotification,
    held: T,
) {
    let expected = notification.observe();
    let wait = match storage.try_block_admitted(budget, |_| {
        panic!("a held original writer must refuse before admission")
    }) {
        Err(admitted::StorageAdmissionError::Busy(wait)) => wait,
        Err(error) => panic!("healthy held writer lost its release wait: {error:?}"),
        Ok(_) => panic!("held original writer admitted another block"),
    };
    assert_eq!(wait, expected);
    assert!(!wait.is_poisoned());
    let count = Arc::new(WakeCount(AtomicUsize::new(0)));
    let waker = Waker::from(Arc::clone(&count));
    let mut future = std::pin::pin!(wait.wait_for_release());
    assert_eq!(
        future.as_mut().poll(&mut Context::from_waker(&waker)),
        Poll::Pending
    );
    drop(held);
    assert_eq!(count.0.load(SeqCst), 1);
    assert_eq!(
        future.as_mut().poll(&mut Context::from_waker(&waker)),
        Poll::Ready(())
    );
    let retry = storage
        .try_block_admitted(budget, |reservation| Policy {
            reservation,
            records: Arc::clone(records),
            component: 0,
        })
        .unwrap();
    assert_eq!(retry.get(&7), Some(&71));
    drop(retry);
}

#[test]
fn direct_and_prepared_publication_install_whole_pair_before_charge_cleanup_panics() {
    for prepared in [false, true] {
        let budget = AllocationBudget::new(1 << 20);
        let records = Arc::new(Records {
            live: Mutex::new(Vec::new()),
            panic_on: AtomicUsize::new(usize::MAX),
        });
        let provider = |reservation| Policy {
            reservation,
            records: Arc::clone(&records),
            component: 0,
        };
        let storage =
            Storage::<u64, u64, Prepaid<Policy>>::try_new_with_node_custody(&budget, provider)
                .unwrap();
        budget.with_deferred_refund_notifications(|| {
            let mut block = storage.try_block_admitted(&budget, provider).unwrap();
            let mut tx = block.try_transaction().unwrap();
            tx.try_insert_admitted(7, 70, &budget, provider).unwrap();
            tx.apply();
            block.commit();
        });
        let old_current = storage.blocks.read();
        let old_undo = storage.revert.read();
        let predecessor = storage.publication.capture();
        budget.with_deferred_refund_notifications(|| {
            let mut block = storage.try_block_admitted(&budget, provider).unwrap();
            let first = records.live.lock().unwrap().len();
            let mut tx = block.try_transaction().unwrap();
            let mut component = 0;
            tx.try_insert_admitted(7, 71, &budget, |reservation| {
                component += 1;
                Policy {
                    reservation,
                    records: Arc::clone(&records),
                    component,
                }
            })
            .unwrap();
            tx.apply();
            // The third original reservation is the current-map edit. Its
            // first-seen buffer precedes retirement tracking; both use concrete
            // pointer-array layouts and the first is retired at commit.
            let candidates: Vec<_> = records
                .live
                .lock()
                .unwrap()
                .iter()
                .enumerate()
                .skip(first)
                .filter(|(_, (size, live, component))| {
                    *component == 3 && *size > 0 && *size <= 32 && *live
                })
                .map(|(id, _)| id)
                .collect();
            assert_eq!(candidates.len(), 2);
            let target = candidates[0];
            let result = if prepared {
                let detached = block.try_detach(|_| Ok::<_, ()>(())).unwrap();
                let publisher = detached
                    .try_prepare_publication(&storage, |_, _| Ok::<_, ()>(()))
                    .unwrap_or_else(|_| panic!("same original pair"));
                records.panic_on.store(target, SeqCst);
                std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                    publisher.publish();
                }))
            } else {
                records.panic_on.store(target, SeqCst);
                std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| block.commit()))
            };
            assert!(result.is_err());
            assert!(!records.live.lock().unwrap()[target].1);
            assert_eq!(storage.blocks.read().get(&7), Some(&71));
            assert_eq!(storage.revert.read().get(&7), Some(&Some(70)));
            assert_eq!(
                predecessor.try_check_current::<()>(&storage.publication),
                Err(PublicationPreparationError::Changed)
            );
            assert_eq!(old_current.get(&7), Some(&70));
            assert_eq!(old_undo.get(&7), Some(&None));
            let current = storage
                .blocks
                .try_write_admitted(|demand| {
                    Ok::<_, ()>(provider(budget.try_reserve_bytes(demand.bytes()).unwrap()))
                })
                .unwrap();
            assert_healthy_contention(
                &storage,
                &budget,
                &records,
                &storage.blocks_released,
                storage.blocks_released.poisoning_guard(current),
            );
            let undo = storage.try_block_admitted(&budget, provider).unwrap();
            assert_healthy_contention(&storage, &budget, &records, &storage.revert_released, undo);
        });
        drop(old_current);
        drop(old_undo);
        drop(storage);
        assert!(
            records
                .live
                .lock()
                .unwrap()
                .iter()
                .all(|(_, live, _)| !live)
        );
        assert_eq!(budget.reserved_bytes(), 0);
    }
}

#[test]
fn refused_admitted_acquisition_signals_only_the_original_released_writer() {
    use admitted::StorageAdmissionError;
    use concread::bptree::MapAdmissionError;

    let budget = AllocationBudget::new(1 << 20);
    let records = Arc::new(Records {
        live: Mutex::new(Vec::new()),
        panic_on: AtomicUsize::new(usize::MAX),
    });
    let provider = |reservation| Policy {
        reservation,
        records: Arc::clone(&records),
        component: 0,
    };
    let storage =
        Storage::<u64, u64, Prepaid<Policy>>::try_new_with_node_custody(&budget, provider).unwrap();
    budget.with_deferred_refund_notifications(|| {
        let mut block = storage.try_block_admitted(&budget, provider).unwrap();
        let mut transaction = block.try_transaction().unwrap();
        transaction
            .try_insert_admitted(7, 70, &budget, provider)
            .unwrap();
        transaction.apply();
        block.commit();

        let notification = &storage.blocks_released;
        let inner_map = BptreeMap::<u64, u64>::new();
        let inner_notification = ReleaseNotification::default();
        let inner_held = inner_notification.poisoning_guard(inner_map.write());
        let inner_wait = inner_notification.observe();
        let exhausted = AllocationBudget::new(0);
        for clear in [false, true] {
            for refuse_with in 0..3 {
                let expected = notification.observe();
                let count = Arc::new(WakeCount(AtomicUsize::new(0)));
                let waker = Waker::from(Arc::clone(&count));
                let mut registered = None;
                let mut refuse = |demand: AllocationDemand| {
                    // Register during actual raw ownership, before the refusal
                    // releases it. A competing writer cannot enter admission.
                    assert!(matches!(
                        storage
                            .blocks
                            .try_write_admitted::<StorageAdmissionError>(|_| panic!(
                                "original raw writer is held"
                            )),
                        Err(MapAdmissionError::Busy)
                    ));
                    let wait = notification.observe();
                    assert_eq!(wait, expected);
                    let mut future = wait.wait_for_release();
                    assert_eq!(
                        std::pin::Pin::new(&mut future).poll(&mut Context::from_waker(&waker)),
                        Poll::Pending
                    );
                    registered = Some(future);
                    Err::<Policy, _>(match refuse_with {
                        0 => StorageAdmissionError::Changed,
                        1 => {
                            assert!(inner_map.try_write().is_none());
                            StorageAdmissionError::Busy(inner_notification.observe())
                        }
                        2 => StorageAdmissionError::Capacity(
                            exhausted
                                .try_reserve_bytes(demand.bytes())
                                .expect_err("actual complete demand exceeds empty budget"),
                        ),
                        _ => unreachable!(),
                    })
                };
                let refused = admitted::acquire_writer(notification, || {
                    if clear {
                        storage.blocks.try_clear_admitted(&mut refuse)
                    } else {
                        storage.blocks.try_write_admitted(&mut refuse)
                    }
                });
                match (refuse_with, refused) {
                    (0, Err(MapAdmissionError::Refused(StorageAdmissionError::Changed)))
                    | (2, Err(MapAdmissionError::Refused(StorageAdmissionError::Capacity(_)))) => {}
                    (1, Err(MapAdmissionError::Refused(StorageAdmissionError::Busy(wait)))) => {
                        assert_eq!(wait, inner_wait);
                        assert_eq!(inner_notification.observe(), inner_wait);
                    }
                    _ => panic!("original callback refusal changed"),
                }
                assert_eq!(count.0.load(SeqCst), 1);
                assert!(!expected.is_poisoned());
                assert_eq!(
                    std::pin::Pin::new(registered.as_mut().expect("registered under raw writer"))
                        .poll(&mut Context::from_waker(&waker)),
                    Poll::Ready(())
                );
                assert_eq!(storage.blocks.read().get(&7), Some(&70));
            }
        }
        drop(inner_held);

        let expected = notification.observe();
        let count = Arc::new(WakeCount(AtomicUsize::new(0)));
        let waker = Waker::from(Arc::clone(&count));
        let mut future = expected.clone().wait_for_release();
        assert_eq!(
            std::pin::Pin::new(&mut future).poll(&mut Context::from_waker(&waker)),
            Poll::Pending
        );
        let held = admitted::acquire_writer(notification, || {
            storage.blocks.try_write_admitted(|demand| {
                Ok::<_, StorageAdmissionError>(provider(
                    budget.try_reserve_bytes(demand.bytes()).unwrap(),
                ))
            })
        })
        .unwrap();
        assert_eq!(count.0.load(SeqCst), 0);
        let busy = admitted::acquire_writer(notification, || {
            storage
                .blocks
                .try_write_admitted::<StorageAdmissionError>(|_| {
                    panic!("Busy must refuse before admission")
                })
        });
        assert!(matches!(busy, Err(MapAdmissionError::Busy)));
        assert_eq!(notification.observe(), expected);
        assert_eq!(count.0.load(SeqCst), 0);
        assert_eq!(
            std::pin::Pin::new(&mut future).poll(&mut Context::from_waker(&waker)),
            Poll::Pending
        );
        drop(held);
        assert_eq!(count.0.load(SeqCst), 1);
        assert!(!expected.is_poisoned());
        assert_eq!(
            std::pin::Pin::new(&mut future).poll(&mut Context::from_waker(&waker)),
            Poll::Ready(())
        );
        assert_eq!(storage.blocks.read().get(&7), Some(&70));
    });
    drop(storage);
    assert!(
        records
            .live
            .lock()
            .unwrap()
            .iter()
            .all(|(_, live, _)| !live)
    );
    assert_eq!(budget.reserved_bytes(), 0);
}

#[test]
fn prepaid_removal_matches_transaction_and_block_preimages_across_abort_and_rebalance() {
    use std::collections::{BTreeMap, BTreeSet};

    fn entries(store: &impl StorageReadOnly<u64, u64>) -> Vec<(u64, u64)> {
        store.iter().map(|(key, value)| (*key, *value)).collect()
    }
    fn touches<'a>(
        keys: impl Iterator<Item = &'a u64>,
        before: &BTreeMap<u64, u64>,
        after: &BTreeMap<u64, u64>,
    ) -> Vec<(u64, Option<u64>, Option<u64>)> {
        keys.map(|key| (*key, before.get(key).copied(), after.get(key).copied()))
            .collect()
    }
    fn row(entry: TouchedEntry<'_, u64, u64>) -> (u64, Option<u64>, Option<u64>) {
        (*entry.key, entry.before.copied(), entry.after.copied())
    }

    let budget = AllocationBudget::new(16 << 20);
    let records = Arc::new(Records {
        live: Mutex::new(Vec::new()),
        panic_on: AtomicUsize::new(usize::MAX),
    });
    let provider = |reservation| Policy {
        reservation,
        records: Arc::clone(&records),
        component: 0,
    };
    let admitted =
        Storage::<u64, u64, Prepaid<Policy>>::try_new_with_node_custody(&budget, provider).unwrap();
    let ordinary = Storage::<u64, u64>::default();
    let mut model = BTreeMap::<u64, u64>::new();
    for block_number in 0_u64..3 {
        let block_before = model.clone();
        let old = admitted.view();
        budget.with_deferred_refund_notifications(|| {
            let mut plain = ordinary.block();
            let mut prepaid = admitted.try_block_admitted(&budget, provider).unwrap();
            let mut block_touched = BTreeSet::new();
            let mut block_dirty = false;
            for phase in 0_u64..6 {
                let transaction_before = model.clone();
                let mut next = model.clone();
                let mut touched = BTreeSet::new();
                let mut dirty = false;
                let mut left = plain.try_transaction().unwrap();
                let mut right = prepaid.try_transaction().unwrap();
                let count = if phase == 0 { 4 } else { 256 };
                for step in 0..count {
                    // First keep explicit missing-key touches; then fill, empty,
                    // refill, and mix edits to cross splits and root demotion.
                    let key = match phase {
                        0 => 2048 + step % 2,
                        1..=3 => 255 - step,
                        _ => (step * 73) % 384,
                    };
                    let insert = matches!(phase, 1 | 3) || (phase >= 4 && step % 3 == 0);
                    let expected = if insert {
                        dirty = true;
                        next.insert(key, block_number * 10_000 + phase * 1000 + step)
                    } else {
                        let previous = next.remove(&key);
                        dirty |= previous.is_some();
                        previous
                    };
                    let (actual_left, actual_right) = if insert {
                        let value = block_number * 10_000 + phase * 1000 + step;
                        (
                            left.insert(key, value),
                            right
                                .try_insert_admitted(key, value, &budget, provider)
                                .unwrap(),
                        )
                    } else {
                        (
                            left.remove(key),
                            right.try_remove_admitted(&key, &budget, provider).unwrap(),
                        )
                    };
                    assert_eq!((actual_left, actual_right), (expected, expected));
                    touched.insert(key);
                    assert_eq!(
                        right.get_before_transaction(&key),
                        transaction_before.get(&key)
                    );
                    assert_eq!(right.get_before_block(&key), block_before.get(&key));
                }
                let expected_rows = touches(touched.iter(), &transaction_before, &next);
                assert_eq!(
                    left.touched_entries().map(row).collect::<Vec<_>>(),
                    expected_rows
                );
                assert_eq!(
                    right.touched_entries().map(row).collect::<Vec<_>>(),
                    expected_rows
                );
                assert_eq!(
                    entries(&left),
                    next.iter().map(|(k, v)| (*k, *v)).collect::<Vec<_>>()
                );
                assert_eq!(entries(&right), entries(&left));
                // An aborted sibling must restore both roots, first preimages,
                // dirty state and the parent's earlier successful touches.
                if phase == 4 || (phase == 2 && block_number == 1) {
                    drop(left);
                    drop(right);
                } else {
                    left.apply();
                    right.apply();
                    model = next;
                    block_touched.extend(touched);
                    block_dirty |= dirty;
                }
                let expected_rows = touches(block_touched.iter(), &block_before, &model);
                assert_eq!(
                    plain.touched_entries().map(row).collect::<Vec<_>>(),
                    expected_rows
                );
                assert_eq!(
                    prepaid.touched_entries().map(row).collect::<Vec<_>>(),
                    expected_rows
                );
                assert_eq!(plain.is_dirty(), block_dirty);
                assert_eq!(prepaid.is_dirty(), block_dirty);
                assert_eq!(entries(&prepaid), entries(&plain));
            }
            plain.commit();
            prepaid.commit();
        });
        assert_eq!(entries(&old), block_before.into_iter().collect::<Vec<_>>());
        assert_eq!(
            entries(&admitted.view()),
            model.iter().map(|(k, v)| (*k, *v)).collect::<Vec<_>>()
        );
        assert_eq!(entries(&admitted.view()), entries(&ordinary.view()));
    }
    drop(admitted);
    assert!(
        records
            .live
            .lock()
            .unwrap()
            .iter()
            .all(|(_, live, _)| !live)
    );
    assert_eq!(budget.reserved_bytes(), 0);
}
