//! Immutable compiler-captured identities for this source owner’s existing codecs.

#[test]
fn captured_codec_schema_identities() {
    crate::captured_schema_tests::assert_bidirectional::<super::ValidationFeeChargingMode>(
        "iroha_data_model::validation_fee::ValidationFeeChargingMode",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::ValidationFeeParliamentAuthorizationV1,
    >("iroha_data_model::validation_fee::ValidationFeeParliamentAuthorizationV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::ValidationFeePayoutLifecycleReferenceV1,
    >("iroha_data_model::validation_fee::ValidationFeePayoutLifecycleReferenceV1");
    crate::captured_schema_tests::assert_bidirectional::<super::ValidationFeePolicyRegistryEntryV1>(
        "iroha_data_model::validation_fee::ValidationFeePolicyRegistryEntryV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ValidationFeePolicyRegistryV1>(
        "iroha_data_model::validation_fee::ValidationFeePolicyRegistryV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::ValidationFeePolicySnapshotAvailableV1,
    >("iroha_data_model::validation_fee::ValidationFeePolicySnapshotAvailableV1");
    crate::captured_schema_tests::assert_bidirectional::<super::ValidationFeePolicySnapshotStatusV1>(
        "iroha_data_model::validation_fee::ValidationFeePolicySnapshotStatusV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::ValidationFeePolicySnapshotCommitmentV1,
    >("iroha_data_model::validation_fee::ValidationFeePolicySnapshotCommitmentV1");
    crate::captured_schema_tests::assert_bidirectional::<super::ValidationFeePolicyWitnessProofV1>(
        "iroha_data_model::validation_fee::ValidationFeePolicyWitnessProofV1",
    );
    crate::captured_schema_tests::assert_serialize::<
        super::ValidationFeePolicyProposalFingerprintEnvelopeV1,
    >("iroha_data_model::validation_fee::ValidationFeePolicyProposalFingerprintEnvelopeV1");
    crate::captured_schema_tests::assert_serialize::<
        super::ValidationFeePayoutLifecycleProposalFingerprintEnvelopeV1,
    >(
        "iroha_data_model::validation_fee::ValidationFeePayoutLifecycleProposalFingerprintEnvelopeV1",
    );
    crate::captured_schema_tests::assert_serialize::<super::ValidationFeePolicyFingerprintPayloadV1>(
        "iroha_data_model::validation_fee::ValidationFeePolicyFingerprintPayloadV1",
    );
    crate::captured_schema_tests::assert_serialize::<
        super::ValidationFeePayoutLifecycleFingerprintPayloadV1,
    >("iroha_data_model::validation_fee::ValidationFeePayoutLifecycleFingerprintPayloadV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::ValidationFeeTreasuryPayoutRecipientV1,
    >("iroha_data_model::validation_fee::ValidationFeeTreasuryPayoutRecipientV1");
    crate::captured_schema_tests::assert_bidirectional::<super::ValidationFeeTreasuryPayoutBindingV1>(
        "iroha_data_model::validation_fee::ValidationFeeTreasuryPayoutBindingV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ValidationFeePolicyV1>(
        "iroha_data_model::validation_fee::ValidationFeePolicyV1",
    );
}
