#!/usr/bin/env python3
"""Render DA threat model metrics into Markdown tables and summaries."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from textwrap import dedent

MARKER_START = "<!-- BEGIN_DA_SIM_TABLE -->"
MARKER_END = "<!-- END_DA_SIM_TABLE -->"
HEADER = "<!-- AUTO-GENERATED by scripts/docs/render_da_threat_model_tables.py; do not edit manually. -->"


def load_summary(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def format_table(summary: dict) -> str:
    aggregate = summary["aggregate"]
    pdp = aggregate["pdp"]
    potr = aggregate["potr"]
    qos = aggregate["qos"]

    rows = [
        (
            "PDP failures detected",
            f"{pdp['detected']} / {pdp['failures']} ({pdp['detection_rate']*100:.1f}%)",
            "Partitions guarantee detection; honest noise accounts for the remaining gaps.",
        ),
        (
            "PDP mean detection latency",
            f"{pdp['mean_detection_latency_epochs']:.1f} epochs",
            "Failures are surfaced within the originating epoch.",
        ),
        (
            "PoTR failures detected",
            f"{potr['detected']} / {potr['failures']} ({potr['detection_rate']*100:.1f}%)",
            "Detection fires once a node misses ≥2 PoTR windows; undetected events feed the residual-risk register.",
        ),
        (
            "PoTR mean detection latency",
            f"{potr['mean_detection_latency_epochs']:.1f} epochs",
            "Matches the configured lateness threshold for archival escalation.",
        ),
        (
            "Repair queue peak",
            f"{qos['repair_queue_peak']} manifests",
            "Backlog occurs when consecutive partitions exceed the per-epoch repair capacity.",
        ),
        (
            "Response latency p95",
            f"{int(round(qos['p95_response_ms'])):,} ms",
            "Mirrors the 30 s challenge window once jitter is normalised to milliseconds for dashboard plotting.",
        ),
    ]
    lines = [
        HEADER,
        "| Metric | Value | Notes |",
        "| --- | --- | --- |",
    ]
    lines.extend(f"| {metric} | {value} | {note} |" for metric, value, note in rows)
    return "\n".join(lines) + "\n"


def format_summary_lines(summary: dict) -> str:
    aggregate = summary["aggregate"]
    pdp = aggregate["pdp"]
    potr = aggregate["potr"]
    qos = aggregate["qos"]
    return dedent(
        f"""\
        ### DA Threat Model Snapshot

        - PDP detection rate: {pdp['detected']} / {pdp['failures']} ({pdp['detection_rate']*100:.1f}%)
        - PoTR detection rate: {potr['detected']} / {potr['failures']} ({potr['detection_rate']*100:.1f}%)
        - PDP mean detection latency: {pdp['mean_detection_latency_epochs']:.1f} epochs
        - PoTR mean detection latency: {potr['mean_detection_latency_epochs']:.1f} epochs
        - Repair queue peak: {qos['repair_queue_peak']} manifests; total repairs {qos['total_repair_events']}
        - Response latency p95: {int(round(qos['p95_response_ms'])):,} ms
        """
    )


def update_doc(path: Path, table: str) -> None:
    text = path.read_text(encoding="utf-8")
    start = text.find(MARKER_START)
    if start == -1:
        raise ValueError(f"{path} missing {MARKER_START}")
    start += len(MARKER_START)
    end = text.find(MARKER_END, start)
    if end == -1:
        raise ValueError(f"{path} missing {MARKER_END}")

    before = text[:start]
    after = text[end:]
    new = before.rstrip() + "\n" + table.strip() + "\n" + after.lstrip()
    path.write_text(new, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True, type=Path, help="Path to threat_model_report.json")
    parser.add_argument(
        "--docs",
        nargs="*",
        default=[],
        type=Path,
        help="Docs to rewrite between BEGIN/END markers",
    )
    parser.add_argument(
        "--table-out",
        type=Path,
        help="Optional path to write the generated table snippet",
    )
    parser.add_argument(
        "--summary-out",
        type=Path,
        help="Optional path to write a Markdown summary list",
    )
    args = parser.parse_args()

    summary = load_summary(args.input)
    table = format_table(summary)
    for doc in args.docs:
        update_doc(doc, table)
    if args.table_out:
        args.table_out.parent.mkdir(parents=True, exist_ok=True)
        args.table_out.write_text(table, encoding="utf-8")
    if args.summary_out:
        args.summary_out.parent.mkdir(parents=True, exist_ok=True)
        args.summary_out.write_text(format_summary_lines(summary), encoding="utf-8")


if __name__ == "__main__":
    main()
