//! Immutable compiler-captured identities for this source owner’s existing codecs.

const CASES: &[crate::captured_schema_tests::Case] = &[
    crate::captured_schema_tests::Case::bidirectional::<super::ConsensusMode>(
        "iroha_data_model::block::consensus_v2::ConsensusMode",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ValidatorPower>(
        "iroha_data_model::block::consensus_v2::ValidatorPower",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::DualQuorum>(
        "iroha_data_model::block::consensus_v2::DualQuorum",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::DataAvailabilityLayout>(
        "iroha_data_model::block::consensus_v2::DataAvailabilityLayout",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::PayloadEncoding>(
        "iroha_data_model::block::consensus_v2::PayloadEncoding",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SumeragiV2GenesisContextParameters>(
        "iroha_data_model::block::consensus_v2::SumeragiV2GenesisContextParameters",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SnapshotBootstrapAnchor>(
        "iroha_data_model::block::consensus_v2::SnapshotBootstrapAnchor",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SnapshotV2BootstrapRecord>(
        "iroha_data_model::block::consensus_v2::SnapshotV2BootstrapRecord",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::HeightContext>(
        "iroha_data_model::block::consensus_v2::HeightContext",
    ),
    crate::captured_schema_tests::Case::serialize::<super::HeightContextIdentity>(
        "iroha_data_model::block::consensus_v2::HeightContextIdentity",
    ),
    crate::captured_schema_tests::Case::serialize::<super::ParentCommitIdentity>(
        "iroha_data_model::block::consensus_v2::ParentCommitIdentity",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::HeightContextId>(
        "iroha_data_model::block::consensus_v2::HeightContextId",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ConsensusRound>(
        "iroha_data_model::block::consensus_v2::ConsensusRound",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::GlobalPhase>(
        "iroha_data_model::block::consensus_v2::GlobalPhase",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::BlockSubject>(
        "iroha_data_model::block::consensus_v2::BlockSubject",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::NativeAmxApplicationManifestMemberV1>(
        "iroha_data_model::block::consensus_v2::NativeAmxApplicationManifestMemberV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::NativeAmxApplicationManifestLeafV1>(
        "iroha_data_model::block::consensus_v2::NativeAmxApplicationManifestLeafV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MergeCarrierCommitmentV1>(
        "iroha_data_model::block::consensus_v2::MergeCarrierCommitmentV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ExecutionCommitment>(
        "iroha_data_model::block::consensus_v2::ExecutionCommitment",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::Vote>(
        "iroha_data_model::block::consensus_v2::Vote",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::VoteSignaturePayload>(
        "iroha_data_model::block::consensus_v2::VoteSignaturePayload",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::QuorumCertificateRef>(
        "iroha_data_model::block::consensus_v2::QuorumCertificateRef",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::QuorumCertificate>(
        "iroha_data_model::block::consensus_v2::QuorumCertificate",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::TimeoutVote>(
        "iroha_data_model::block::consensus_v2::TimeoutVote",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::TimeoutVoteSignaturePayload>(
        "iroha_data_model::block::consensus_v2::TimeoutVoteSignaturePayload",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::TimeoutVoteGroup>(
        "iroha_data_model::block::consensus_v2::TimeoutVoteGroup",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::TimeoutCertificate>(
        "iroha_data_model::block::consensus_v2::TimeoutCertificate",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::TimeoutCertificateRef>(
        "iroha_data_model::block::consensus_v2::TimeoutCertificateRef",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ProposalJustification>(
        "iroha_data_model::block::consensus_v2::ProposalJustification",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ParentCommitJustification>(
        "iroha_data_model::block::consensus_v2::ParentCommitJustification",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::TimeoutJustification>(
        "iroha_data_model::block::consensus_v2::TimeoutJustification",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::PayloadManifest>(
        "iroha_data_model::block::consensus_v2::PayloadManifest",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::PayloadChunk>(
        "iroha_data_model::block::consensus_v2::PayloadChunk",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::PayloadChunkSignaturePayload>(
        "iroha_data_model::block::consensus_v2::PayloadChunkSignaturePayload",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::Proposal>(
        "iroha_data_model::block::consensus_v2::Proposal",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SumeragiV2Equivocation>(
        "iroha_data_model::block::consensus_v2::SumeragiV2Equivocation",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::CertifiedBodyRequest>(
        "iroha_data_model::block::consensus_v2::CertifiedBodyRequest",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::CertifiedBodyResponse>(
        "iroha_data_model::block::consensus_v2::CertifiedBodyResponse",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::CertifiedBodyResponseSignaturePayload>(
        "iroha_data_model::block::consensus_v2::CertifiedBodyResponseSignaturePayload",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::CommitCertificateRequest>(
        "iroha_data_model::block::consensus_v2::CommitCertificateRequest",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::CommitCertificateResponse>(
        "iroha_data_model::block::consensus_v2::CommitCertificateResponse",
    ),
    crate::captured_schema_tests::Case::bidirectional::<
        super::CommitCertificateResponseSignaturePayload,
    >("iroha_data_model::block::consensus_v2::CommitCertificateResponseSignaturePayload"),
    crate::captured_schema_tests::Case::bidirectional::<super::GlobalBeaconPartialSignature>(
        "iroha_data_model::block::consensus_v2::GlobalBeaconPartialSignature",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ConsensusMessageV2Payload>(
        "iroha_data_model::block::consensus_v2::ConsensusMessageV2Payload",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ConsensusMessageV2>(
        "iroha_data_model::block::consensus_v2::ConsensusMessageV2",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SumeragiV2StatusPhase>(
        "iroha_data_model::block::consensus_v2::SumeragiV2StatusPhase",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SumeragiV2BodyState>(
        "iroha_data_model::block::consensus_v2::SumeragiV2BodyState",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SumeragiV2HeightContextStatus>(
        "iroha_data_model::block::consensus_v2::SumeragiV2HeightContextStatus",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SumeragiV2CommitQcStatus>(
        "iroha_data_model::block::consensus_v2::SumeragiV2CommitQcStatus",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SumeragiV2VoteQuorumStatus>(
        "iroha_data_model::block::consensus_v2::SumeragiV2VoteQuorumStatus",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SumeragiV2TimeoutQuorumStatus>(
        "iroha_data_model::block::consensus_v2::SumeragiV2TimeoutQuorumStatus",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SumeragiV2OutboundIntentKind>(
        "iroha_data_model::block::consensus_v2::SumeragiV2OutboundIntentKind",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SumeragiV2OutboundIntentStage>(
        "iroha_data_model::block::consensus_v2::SumeragiV2OutboundIntentStage",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SumeragiV2OutboundIntentStatus>(
        "iroha_data_model::block::consensus_v2::SumeragiV2OutboundIntentStatus",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SumeragiV2LocalWorkStage>(
        "iroha_data_model::block::consensus_v2::SumeragiV2LocalWorkStage",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SumeragiV2WorkStatus>(
        "iroha_data_model::block::consensus_v2::SumeragiV2WorkStatus",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SumeragiV2QueueKind>(
        "iroha_data_model::block::consensus_v2::SumeragiV2QueueKind",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SumeragiV2QueueStatus>(
        "iroha_data_model::block::consensus_v2::SumeragiV2QueueStatus",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SumeragiV2ProgressTransition>(
        "iroha_data_model::block::consensus_v2::SumeragiV2ProgressTransition",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SumeragiV2ProgressTransitionStatus>(
        "iroha_data_model::block::consensus_v2::SumeragiV2ProgressTransitionStatus",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SumeragiV2LivenessBlocker>(
        "iroha_data_model::block::consensus_v2::SumeragiV2LivenessBlocker",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SumeragiV2IgnoreReason>(
        "iroha_data_model::block::consensus_v2::SumeragiV2IgnoreReason",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SumeragiV2IgnoreCount>(
        "iroha_data_model::block::consensus_v2::SumeragiV2IgnoreCount",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SumeragiV2LivenessStatus>(
        "iroha_data_model::block::consensus_v2::SumeragiV2LivenessStatus",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SumeragiV2QcResponse>(
        "iroha_data_model::block::consensus_v2::SumeragiV2QcResponse",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SumeragiV2Status>(
        "iroha_data_model::block::consensus_v2::SumeragiV2Status",
    ),
];

#[test]
fn captured_codec_schema_identities() {
    for case in CASES {
        case.check();
    }
}
