//! Immutable compiler-captured identities for this source owner’s existing codecs.

const CASES: &[crate::captured_schema_tests::Case] = &[
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationLedgerPolicyV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationLedgerPolicyV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationLedgerPolicyRecord>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationLedgerPolicyRecord",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationPoPRegistrySnapshotV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationPoPRegistrySnapshotV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationAppealIntakeV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationAppealIntakeV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationJurorEligibilityClassV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationJurorEligibilityClassV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationJurorEligibilityRecordV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationJurorEligibilityRecordV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationPanelSelectionV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationPanelSelectionV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationSortitionAnchorV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationSortitionAnchorV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationJurorReplacementV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationJurorReplacementV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationAppealStatusV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationAppealStatusV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationAppealRecordV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationAppealRecordV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationCaseSpecV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationCaseSpecV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationCaseStatusV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationCaseStatusV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationCaseRecordV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationCaseRecordV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationCommitRecordV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationCommitRecordV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationRevealRecordV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationRevealRecordV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationChallengeKindV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationChallengeKindV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationChallengeDecisionV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationChallengeDecisionV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationChallengeBondV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationChallengeBondV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationChallengeRecordV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationChallengeRecordV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationVoteCountsV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationVoteCountsV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationOutcomeKindV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationOutcomeKindV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationOutcomeRecordV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationOutcomeRecordV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationNoShowKindV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationNoShowKindV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationNoShowRecordV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationNoShowRecordV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationLedgerStatusV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationLedgerStatusV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationFinalizedCursorV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationFinalizedCursorV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationFinalizedEventCursorV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationFinalizedEventCursorV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationFinalizedEventV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationFinalizedEventV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationFinalizedEventPageV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationFinalizedEventPageV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationFinalizedAppealViewV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationFinalizedAppealViewV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationFinalizedCaseViewV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationFinalizedCaseViewV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ModerationFinalizedLedgerSnapshotV1>(
        "iroha_data_model::sorafs::moderation_ledger::ModerationFinalizedLedgerSnapshotV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RepairLedgerLeaseV1>(
        "iroha_data_model::sorafs::moderation_ledger::RepairLedgerLeaseV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RepairLedgerCompletedV1>(
        "iroha_data_model::sorafs::moderation_ledger::RepairLedgerCompletedV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RepairLedgerFailedV1>(
        "iroha_data_model::sorafs::moderation_ledger::RepairLedgerFailedV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RepairLedgerEscalatedV1>(
        "iroha_data_model::sorafs::moderation_ledger::RepairLedgerEscalatedV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RepairLedgerTerminalKindV1>(
        "iroha_data_model::sorafs::moderation_ledger::RepairLedgerTerminalKindV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RepairLedgerTerminalOutcomeV1>(
        "iroha_data_model::sorafs::moderation_ledger::RepairLedgerTerminalOutcomeV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RepairLedgerActionReceiptV1>(
        "iroha_data_model::sorafs::moderation_ledger::RepairLedgerActionReceiptV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RepairLedgerSlashRecordV1>(
        "iroha_data_model::sorafs::moderation_ledger::RepairLedgerSlashRecordV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RepairLedgerAppealRecordV1>(
        "iroha_data_model::sorafs::moderation_ledger::RepairLedgerAppealRecordV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RepairLedgerTaskV1>(
        "iroha_data_model::sorafs::moderation_ledger::RepairLedgerTaskV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RepairLedgerStatusV1>(
        "iroha_data_model::sorafs::moderation_ledger::RepairLedgerStatusV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RepairFinalizedCursorV1>(
        "iroha_data_model::sorafs::moderation_ledger::RepairFinalizedCursorV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RepairFinalizedTaskV1>(
        "iroha_data_model::sorafs::moderation_ledger::RepairFinalizedTaskV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RepairFinalizedStatusV1>(
        "iroha_data_model::sorafs::moderation_ledger::RepairFinalizedStatusV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RepairLedgerTaskPageV1>(
        "iroha_data_model::sorafs::moderation_ledger::RepairLedgerTaskPageV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RepairFinalizedEventCursorV1>(
        "iroha_data_model::sorafs::moderation_ledger::RepairFinalizedEventCursorV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RepairFinalizedEventV1>(
        "iroha_data_model::sorafs::moderation_ledger::RepairFinalizedEventV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RepairFinalizedEventPageV1>(
        "iroha_data_model::sorafs::moderation_ledger::RepairFinalizedEventPageV1",
    ),
];

#[test]
fn captured_codec_schema_identities() {
    for case in CASES {
        case.check();
    }
}
