//! Immutable compiler-captured identities for this source owner’s existing codecs.

#[test]
fn captured_codec_schema_identities() {
    crate::captured_schema_tests::assert_bidirectional::<super::ReserveTier>(
        "iroha_data_model::sorafs::reserve::ReserveTier",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ReserveDuration>(
        "iroha_data_model::sorafs::reserve::ReserveDuration",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ClassRentRate>(
        "iroha_data_model::sorafs::reserve::ClassRentRate",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::DurationFactorSet>(
        "iroha_data_model::sorafs::reserve::DurationFactorSet",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ReserveTierConfig>(
        "iroha_data_model::sorafs::reserve::ReserveTierConfig",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ReservePolicyV1>(
        "iroha_data_model::sorafs::reserve::ReservePolicyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ReserveQuote>(
        "iroha_data_model::sorafs::reserve::ReserveQuote",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ReserveLedgerProjection>(
        "iroha_data_model::sorafs::reserve::ReserveLedgerProjection",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ReserveLifecycleStage>(
        "iroha_data_model::sorafs::reserve::ReserveLifecycleStage",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ReserveLifecycleProjection>(
        "iroha_data_model::sorafs::reserve::ReserveLifecycleProjection",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ReserveAuthorityPolicyV1>(
        "iroha_data_model::sorafs::reserve::ReserveAuthorityPolicyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ReserveAuthorityPolicyRecordV1>(
        "iroha_data_model::sorafs::reserve::ReserveAuthorityPolicyRecordV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ReserveProviderTermsV1>(
        "iroha_data_model::sorafs::reserve::ReserveProviderTermsV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ReserveProviderAccountV1>(
        "iroha_data_model::sorafs::reserve::ReserveProviderAccountV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ReserveMovementKindV1>(
        "iroha_data_model::sorafs::reserve::ReserveMovementKindV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ReserveMovementStatusV1>(
        "iroha_data_model::sorafs::reserve::ReserveMovementStatusV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ReserveMovementRecordV1>(
        "iroha_data_model::sorafs::reserve::ReserveMovementRecordV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ReserveAppealStatusV1>(
        "iroha_data_model::sorafs::reserve::ReserveAppealStatusV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ReserveAppealRecordV1>(
        "iroha_data_model::sorafs::reserve::ReserveAppealRecordV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ReserveFinalizedCursorV1>(
        "iroha_data_model::sorafs::reserve::ReserveFinalizedCursorV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ReserveFinalizedEventCursorV1>(
        "iroha_data_model::sorafs::reserve::ReserveFinalizedEventCursorV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ReserveFinalizedEventV1>(
        "iroha_data_model::sorafs::reserve::ReserveFinalizedEventV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ReserveFinalizedEventPageV1>(
        "iroha_data_model::sorafs::reserve::ReserveFinalizedEventPageV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ReserveProviderAccountPageV1>(
        "iroha_data_model::sorafs::reserve::ReserveProviderAccountPageV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ReserveMovementPageV1>(
        "iroha_data_model::sorafs::reserve::ReserveMovementPageV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ReserveAppealPageV1>(
        "iroha_data_model::sorafs::reserve::ReserveAppealPageV1",
    );
}
