//! Immutable compiler-captured identities for this source owner’s existing codecs.

#[test]
fn captured_codec_schema_identities() {
    crate::captured_schema_tests::assert_bidirectional::<super::Q16>(
        "iroha_data_model::hijiri::Q16",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ObserverProfileId>(
        "iroha_data_model::hijiri::ObserverProfileId",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::DelegatedAttestationClass>(
        "iroha_data_model::hijiri::DelegatedAttestationClass",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ObserverProfile>(
        "iroha_data_model::hijiri::ObserverProfile",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ObserverRegistryEntry>(
        "iroha_data_model::hijiri::ObserverRegistryEntry",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::RegistryCreditSchedule>(
        "iroha_data_model::hijiri::RegistryCreditSchedule",
    );
    crate::captured_schema_tests::assert_serialize::<super::PositiveAttestationIncentive>(
        "iroha_data_model::hijiri::PositiveAttestationIncentive",
    );
    crate::captured_schema_tests::assert_deserialize::<super::PositiveAttestationIncentiveWire>(
        "iroha_data_model::hijiri::PositiveAttestationIncentiveWire",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::EvidenceHashAlgorithm>(
        "iroha_data_model::hijiri::EvidenceHashAlgorithm",
    );
    crate::captured_schema_tests::assert_serialize::<super::EvidenceFieldCommitment>(
        "iroha_data_model::hijiri::EvidenceFieldCommitment",
    );
    crate::captured_schema_tests::assert_deserialize::<super::EvidenceFieldCommitmentWire>(
        "iroha_data_model::hijiri::EvidenceFieldCommitmentWire",
    );
    crate::captured_schema_tests::assert_serialize::<super::EvidenceHashBundle>(
        "iroha_data_model::hijiri::EvidenceHashBundle",
    );
    crate::captured_schema_tests::assert_deserialize::<super::EvidenceHashBundleWire>(
        "iroha_data_model::hijiri::EvidenceHashBundleWire",
    );
    crate::captured_schema_tests::assert_serialize::<super::FeeMultiplierBand>(
        "iroha_data_model::hijiri::FeeMultiplierBand",
    );
    crate::captured_schema_tests::assert_deserialize::<super::FeeMultiplierBandWire>(
        "iroha_data_model::hijiri::FeeMultiplierBandWire",
    );
    crate::captured_schema_tests::assert_serialize::<super::HijiriFeePolicy>(
        "iroha_data_model::hijiri::HijiriFeePolicy",
    );
    crate::captured_schema_tests::assert_deserialize::<super::HijiriFeePolicyWire>(
        "iroha_data_model::hijiri::HijiriFeePolicyWire",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::HijiriParametersV1>(
        "iroha_data_model::hijiri::HijiriParametersV1",
    );
    crate::captured_schema_tests::assert_serialize::<super::HijiriFeeQuotePreimageV1>(
        "iroha_data_model::hijiri::HijiriFeeQuotePreimageV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::HijiriAccountRiskV1>(
        "iroha_data_model::hijiri::HijiriAccountRiskV1",
    );
}
