//! Immutable compiler-captured identities for this source owner’s existing codecs.

const CASES: &[crate::captured_schema_tests::Case] = &[
    crate::captured_schema_tests::Case::bidirectional::<super::Q16>(
        "iroha_data_model::hijiri::Q16",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ObserverProfileId>(
        "iroha_data_model::hijiri::ObserverProfileId",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::DelegatedAttestationClass>(
        "iroha_data_model::hijiri::DelegatedAttestationClass",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ObserverProfile>(
        "iroha_data_model::hijiri::ObserverProfile",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ObserverRegistryEntry>(
        "iroha_data_model::hijiri::ObserverRegistryEntry",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RegistryCreditSchedule>(
        "iroha_data_model::hijiri::RegistryCreditSchedule",
    ),
    crate::captured_schema_tests::Case::serialize::<super::PositiveAttestationIncentive>(
        "iroha_data_model::hijiri::PositiveAttestationIncentive",
    ),
    crate::captured_schema_tests::Case::deserialize::<super::PositiveAttestationIncentiveWire>(
        "iroha_data_model::hijiri::PositiveAttestationIncentiveWire",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::EvidenceHashAlgorithm>(
        "iroha_data_model::hijiri::EvidenceHashAlgorithm",
    ),
    crate::captured_schema_tests::Case::serialize::<super::EvidenceFieldCommitment>(
        "iroha_data_model::hijiri::EvidenceFieldCommitment",
    ),
    crate::captured_schema_tests::Case::deserialize::<super::EvidenceFieldCommitmentWire>(
        "iroha_data_model::hijiri::EvidenceFieldCommitmentWire",
    ),
    crate::captured_schema_tests::Case::serialize::<super::EvidenceHashBundle>(
        "iroha_data_model::hijiri::EvidenceHashBundle",
    ),
    crate::captured_schema_tests::Case::deserialize::<super::EvidenceHashBundleWire>(
        "iroha_data_model::hijiri::EvidenceHashBundleWire",
    ),
    crate::captured_schema_tests::Case::serialize::<super::FeeMultiplierBand>(
        "iroha_data_model::hijiri::FeeMultiplierBand",
    ),
    crate::captured_schema_tests::Case::deserialize::<super::FeeMultiplierBandWire>(
        "iroha_data_model::hijiri::FeeMultiplierBandWire",
    ),
    crate::captured_schema_tests::Case::serialize::<super::HijiriFeePolicy>(
        "iroha_data_model::hijiri::HijiriFeePolicy",
    ),
    crate::captured_schema_tests::Case::deserialize::<super::HijiriFeePolicyWire>(
        "iroha_data_model::hijiri::HijiriFeePolicyWire",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::HijiriParametersV1>(
        "iroha_data_model::hijiri::HijiriParametersV1",
    ),
    crate::captured_schema_tests::Case::serialize::<super::HijiriFeeQuotePreimageV1>(
        "iroha_data_model::hijiri::HijiriFeeQuotePreimageV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::HijiriAccountRiskV1>(
        "iroha_data_model::hijiri::HijiriAccountRiskV1",
    ),
];

#[test]
fn captured_codec_schema_identities() {
    for case in CASES {
        case.check();
    }
}
