//! Immutable compiler-captured identities for this source owner’s existing codecs.

const CASES: &[crate::captured_schema_tests::Case] = &[
    crate::captured_schema_tests::Case::bidirectional::<super::AxtBinding>(
        "iroha_data_model::nexus::axt::AxtBinding",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AxtDescriptor>(
        "iroha_data_model::nexus::axt::AxtDescriptor",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AxtTouchSpec>(
        "iroha_data_model::nexus::axt::AxtTouchSpec",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::TouchManifest>(
        "iroha_data_model::nexus::axt::TouchManifest",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AxtTouchFragment>(
        "iroha_data_model::nexus::axt::AxtTouchFragment",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ProofBlob>(
        "iroha_data_model::nexus::axt::ProofBlob",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AxtProofEnvelope>(
        "iroha_data_model::nexus::axt::AxtProofEnvelope",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AxtFastpqBinding>(
        "iroha_data_model::nexus::axt::AxtFastpqBinding",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AxtEffectBinding>(
        "iroha_data_model::nexus::axt::AxtEffectBinding",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AxtProofFragment>(
        "iroha_data_model::nexus::axt::AxtProofFragment",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::GroupBinding>(
        "iroha_data_model::nexus::axt::GroupBinding",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::HandleBudget>(
        "iroha_data_model::nexus::axt::HandleBudget",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::HandleSubject>(
        "iroha_data_model::nexus::axt::HandleSubject",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AxtAssetIncarnationV1>(
        "iroha_data_model::nexus::axt::AxtAssetIncarnationV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AxtFinalizedSpendAnchorV1>(
        "iroha_data_model::nexus::axt::AxtFinalizedSpendAnchorV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AxtHandleIssuerContextV1>(
        "iroha_data_model::nexus::axt::AxtHandleIssuerContextV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AssetHandleIssuerPayloadV1>(
        "iroha_data_model::nexus::axt::AssetHandleIssuerPayloadV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AssetHandleDraft>(
        "iroha_data_model::nexus::axt::AssetHandleDraft",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AssetHandle>(
        "iroha_data_model::nexus::axt::AssetHandle",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AxtHandleBudgetKey>(
        "iroha_data_model::nexus::axt::AxtHandleBudgetKey",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AxtHandleBudgetRecord>(
        "iroha_data_model::nexus::axt::AxtHandleBudgetRecord",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AxtHandleCounterRecord>(
        "iroha_data_model::nexus::axt::AxtHandleCounterRecord",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SpendOp>(
        "iroha_data_model::nexus::axt::SpendOp",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RemoteSpendIntent>(
        "iroha_data_model::nexus::axt::RemoteSpendIntent",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AxtSpendNonceV1>(
        "iroha_data_model::nexus::axt::AxtSpendNonceV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AxtAnchoredSpendDraftV1>(
        "iroha_data_model::nexus::axt::AxtAnchoredSpendDraftV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AxtAnchoredSpendIssuerPayloadV1>(
        "iroha_data_model::nexus::axt::AxtAnchoredSpendIssuerPayloadV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AxtAnchoredSpendIssuerAuthorizationV1>(
        "iroha_data_model::nexus::axt::AxtAnchoredSpendIssuerAuthorizationV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AxtAnchoredSpendV1>(
        "iroha_data_model::nexus::axt::AxtAnchoredSpendV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AxtAnchoredSpendReplayKeyV1>(
        "iroha_data_model::nexus::axt::AxtAnchoredSpendReplayKeyV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AxtRemoteSpendClaimV1>(
        "iroha_data_model::nexus::axt::AxtRemoteSpendClaimV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AxtHandleFragment>(
        "iroha_data_model::nexus::axt::AxtHandleFragment",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AxtHandleReplayKey>(
        "iroha_data_model::nexus::axt::AxtHandleReplayKey",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AxtReplayRecord>(
        "iroha_data_model::nexus::axt::AxtReplayRecord",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AxtEnvelopeRecord>(
        "iroha_data_model::nexus::axt::AxtEnvelopeRecord",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AxtPolicyEntry>(
        "iroha_data_model::nexus::axt::AxtPolicyEntry",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AxtPolicyBinding>(
        "iroha_data_model::nexus::axt::AxtPolicyBinding",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AxtPolicySnapshot>(
        "iroha_data_model::nexus::axt::AxtPolicySnapshot",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AxtRejectContext>(
        "iroha_data_model::nexus::axt::AxtRejectContext",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AxtRejectReason>(
        "iroha_data_model::nexus::axt::AxtRejectReason",
    ),
];

#[test]
fn captured_codec_schema_identities() {
    for case in CASES {
        case.check();
    }
}
