chain = "00000000-0000-0000-0000-000000000000"

[confidential]
enabled = true

[genesis]
public_key = "ed01204164BF554923ECE1FD412D241036D863A6AE430476C898248B8237D77534CFC4"

[kura]
store_dir = "./storage"

[logger]
format = "pretty"
level = "INFO"

[network]
block_gossip_period_ms = 150
block_gossip_size = 4

[pipeline]
signature_batch_max_bls = 4

[snapshot]
mode = "disabled"

[sumeragi]
da_enabled = true
enable_bls = true
key_require_hsm = false
msg_channel_cap_blocks = 512
rbc_chunk_max_bytes = 262144
rbc_store_max_bytes = 67108864
rbc_store_max_sessions = 256
rbc_store_soft_bytes = 50331648
rbc_store_soft_sessions = 192
require_precommit_qc = false
require_wsv_exec_qc = false

[sumeragi.debug.rbc]
conflicting_ready_mask = 0
corrupt_ready_signature = false
corrupt_witness_ack = false
drop_validator_mask = 0
duplicate_inits = false
equivocate_chunk_mask = 0
equivocate_validator_mask = 0
partial_chunk_mask = 0
shuffle_chunks = false

[torii.rbc_sampling]
enabled = false

[torii.transport.norito_rpc]
enabled = true
stage = "ga"
