package org.hyperledger.iroha.sdk.query

import java.io.File
import java.util.AbstractMap
import org.hyperledger.iroha.sdk.json.Json
import org.hyperledger.iroha.sdk.json.JsonArray
import org.hyperledger.iroha.sdk.json.JsonBoolean
import org.hyperledger.iroha.sdk.json.JsonNumber
import org.hyperledger.iroha.sdk.json.JsonObject
import org.hyperledger.iroha.sdk.json.JsonString
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

/** The shared golden vectors in `fixtures/torii/list_query/vectors.json` (generated by Rust). */
class ListQueryGoldenVectorsTest {
    private val vectors: JsonObject = loadVectors()

    @Test
    fun fixtureVersionIsSupported() {
        assertEquals(JsonNumber.of(1L), vectors["version"])
    }

    @Test
    fun filtersParseRenderAndEncodeExactly() {
        val cases = array("filters")
        assertTrue(cases.size >= 20)
        for (case in cases) {
            case as JsonObject
            val text = string(case, "text")
            val canonical = string(case, "canonical")
            val json = case["json"]!!
            val parsed = Filter.parse(text)
            assertEquals(canonical, parsed.toString(), "canonical text of `$text`")
            assertEquals(json, parsed.toJson(), "JSON form of `$text`")
            val decoded = Filter.fromJson(json)
            assertEquals(parsed, decoded, "JSON form of `$text` decodes to the parsed tree")
            assertEquals(canonical, decoded.toString())
            assertEquals(parsed, Filter.parse(canonical), "the canonical rendering of `$text` parses back")
            assertEquals(parsed, Filter.fromJson(parsed.toJson().toJsonString()))
        }
    }

    @Test
    fun builderProducesTheVectorTrees() {
        val built = listOf(
            field("owned_by") eq "alice",
            (field("owned_by") eq "alice") and (field("quantity") gte java.math.BigDecimal("10.5")),
            field("a") eq 1,
            field("a") ne -2,
            field("a") lt java.math.BigInteger("340282366920938463463374607431768211455"),
            (field("a") lte 0) or (field("b") gt java.math.BigDecimal("1.25")),
            (field("flag") eq true) and (field("other") eq false) and (field("gone") eq Json.NULL),
            field("status").isIn("active", "paused"),
            field("tier").notIn(1, 2, 3),
            field("metadata.tier").exists(),
            field("note").isNull(),
            field("note").isNotNull(),
            !field("metadata.archived").exists(),
            (field("a") eq 1) or ((!(field("b") eq 2)) and (field("c") eq 3)),
            ((field("a") eq 1) or (field("b") eq 2)) and (field("c") eq 3),
            !((field("a") eq 1) and (field("b") eq 2)),
            !(!(field("a") eq 1)),
            field("metadata.display-name") eq "x",
            field("and") eq 1,
            field("metadata.null") eq 1,
            field("text") eq "quote \" backslash \\ newline \n unicode é",
            (field("tx_hash") eq "hash") and field("tx_status").isIn("Approved", "Rejected"),
            field("note") eq "del\u007f c1\u0085",
        )
        val cases = array("filters")
        assertEquals(cases.size, built.size)
        cases.items.zip(built).forEach { (case, filter) ->
            case as JsonObject
            assertEquals(string(case, "canonical"), filter.toString())
            assertEquals(case["json"], filter.toJson())
        }
    }

    @Test
    fun jsonFiltersDecodeToTheNormalizedTree() {
        val cases = array("json_filters")
        assertTrue(cases.size > 0)
        for (case in cases) {
            case as JsonObject
            val json = case["json"]!!
            val canonical = string(case, "canonical")
            val normalized = case["normalized"]!!
            val decoded = Filter.fromJson(json)
            assertEquals(canonical, decoded.toString(), "canonical text of $json")
            assertEquals(normalized, decoded.toJson(), "normalized JSON of $json")
            assertEquals(decoded, Filter.parse(canonical), "the canonical rendering of $json parses back")
            assertEquals(decoded, Filter.fromJson(normalized))
            val body = JsonObject(linkedMapOf("filter" to json))
            assertEquals(JsonObject(linkedMapOf("filter" to normalized)), ListQuery.fromJson(body).toJson())
        }
    }

    @Test
    fun filterErrorsReportTheSamePositionAndMessage() {
        for (case in array("filter_errors")) {
            case as JsonObject
            val text = string(case, "text")
            val error = assertFailsWith<FilterSyntaxException>("`$text` must be rejected") { Filter.parse(text) }
            assertEquals(string(case, "message"), error.reason, "message for `$text`")
            assertEquals(long(case, "line"), error.line.toLong(), "line for `$text`")
            assertEquals(long(case, "column"), error.column.toLong(), "column for `$text`")
            assertEquals("invalid_filter", error.code)
        }
    }

    @Test
    fun sortsParseRenderAndEncodeExactly() {
        for (case in array("sorts")) {
            case as JsonObject
            val keys = SortKey.parseList(string(case, "text"))
            assertEquals(string(case, "canonical"), SortKey.render(keys))
            assertEquals(case["json"], JsonArray(keys.map { JsonString(it.toString()) }))
            assertEquals(keys, SortKey.parseList(SortKey.render(keys)))
        }
    }

    @Test
    fun sortErrorsReportTheSamePositionAndMessage() {
        for (case in array("sort_errors")) {
            case as JsonObject
            val text = string(case, "text")
            val error = assertFailsWith<FilterSyntaxException>("`$text` must be rejected") { SortKey.parseList(text) }
            assertEquals(string(case, "message"), error.reason, "message for `$text`")
            assertEquals(long(case, "line"), error.line.toLong())
            assertEquals(long(case, "column"), error.column.toLong())
            assertEquals("invalid_sort", error.code)
        }
    }

    @Test
    fun queriesEncodeTheCanonicalBodyAndGetPairs() {
        val built = listOf(
            ListQuery.EMPTY,
            listQuery {
                filter((field("owned_by") eq "alice") and (field("quantity") gt 1))
                sort(SortKey.desc("quantity"), SortKey.asc("id"))
                select("id", "quantity")
                limit(25)
                includeTotal()
            },
            listQuery {
                limit(10)
                cursor("q1_abc-DEF")
            },
        )
        val cases = array("queries")
        assertEquals(cases.size, built.size)
        cases.items.zip(built).forEach { (case, query) ->
            case as JsonObject
            val body = case["body"]!!
            assertEquals(body, query.toJson())
            assertEquals(pairs(case["query_pairs"]!!), query.toQueryPairs().map { it.key to it.value })
            assertEquals(query, ListQuery.fromJson(body))
            assertEquals(query, ListQuery.fromQueryPairs(query.toQueryPairs()))
            assertEquals(
                ListQuery.MEMBERS.filter { query.toJson().containsKey(it) },
                query.toJson().keys.toList(),
                "body members are emitted in canonical order",
            )
        }
    }

    @Test
    fun invalidBodiesAreRejectedWithTheSameCode() {
        for (case in array("query_body_errors")) {
            case as JsonObject
            val error = assertFailsWith<ListQueryException>("body ${case["body"]} must be rejected") {
                ListQuery.fromJson(case["body"]!!)
            }
            assertEquals(string(case, "code"), error.code, "code for ${case["body"]}")
            assertEquals(string(case, "parameter"), error.parameter, "parameter for ${case["body"]}")
        }
    }

    @Test
    fun invalidGetPairsAreRejectedWithTheSameCode() {
        for (case in array("query_pair_errors")) {
            case as JsonObject
            val pairs = pairs(case["query_pairs"]!!).map { (key, value) -> AbstractMap.SimpleImmutableEntry(key, value) }
            val error = assertFailsWith<ListQueryException>("pairs $pairs must be rejected") {
                ListQuery.fromQueryPairs(pairs)
            }
            assertEquals(string(case, "code"), error.code, "code for $pairs")
            assertEquals(string(case, "parameter"), error.parameter, "parameter for $pairs")
        }
    }

    @Test
    fun pagesDecode() {
        for (case in array("pages")) {
            case as JsonObject
            val json = case["json"] as JsonObject
            val page = Page.fromJson(json)
            assertEquals((json["items"] as JsonArray).items, page.items)
            assertEquals((json["next_cursor"] as? JsonString)?.value, page.nextCursor)
            assertEquals((json["total"] as? JsonNumber)?.toLongExact(), page.total)
            assertEquals((case["has_more"] as JsonBoolean).value, page.hasMore())
        }
    }

    private fun array(name: String): JsonArray = vectors[name] as JsonArray

    private fun string(case: JsonObject, name: String): String = (case[name] as JsonString).value

    private fun long(case: JsonObject, name: String): Long = (case[name] as JsonNumber).toLongExact()

    private fun pairs(json: Json): List<Pair<String, String>> = (json as JsonArray).items.map { pair ->
        pair as JsonArray
        (pair[0] as JsonString).value to (pair[1] as JsonString).value
    }

    private companion object {
        fun loadVectors(): JsonObject {
            val relative = "fixtures/torii/list_query/vectors.json"
            val file = generateSequence(File(System.getProperty("user.dir"))) { it.parentFile }
                .map { File(it, relative) }
                .firstOrNull { it.isFile }
                ?: error("missing shared list-query golden vectors: $relative")
            return Json.parse(file.readBytes()) as JsonObject
        }
    }
}
