use iroha_crypto::{PublicKey, Signature};
use iroha_schema::IntoSchema;
use norito::codec::{Decode, Encode};

#[cfg(feature = "json")]
use crate::{DeriveJsonDeserialize, DeriveJsonSerialize};
use crate::{
    da::types::{
        BlobClass, BlobCodec, BlobDigest, Compression, DaRentQuote, ErasureProfile, ExtraMetadata,
        RetentionPolicy, StorageTicketId,
    },
    nexus::LaneId,
};

/// Summary of the 2D erasure layout captured in DA manifests/receipts.
#[derive(
    Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Encode, Decode, IntoSchema, Default,
)]
#[cfg_attr(feature = "json", derive(DeriveJsonSerialize, DeriveJsonDeserialize))]
#[cfg_attr(any(feature = "ffi_export", feature = "ffi_import"), ffi_type)]
pub struct DaStripeLayout {
    /// Total row stripes (data + column parity).
    pub total_stripes: u32,
    /// Total shards per stripe (data + row parity).
    pub shards_per_stripe: u32,
    /// Number of column-parity stripes across the matrix.
    #[norito(default)]
    pub row_parity_stripes: u16,
}

/// Norito payload accepted by the Torii `/v1/da/ingest` endpoint.
#[derive(Clone, Debug, PartialEq, Eq, Encode, Decode, IntoSchema)]
#[cfg_attr(feature = "json", derive(DeriveJsonSerialize, DeriveJsonDeserialize))]
#[cfg_attr(any(feature = "ffi_export", feature = "ffi_import"), ffi_type)]
pub struct DaIngestRequest {
    /// Caller-supplied blob identifier (BLAKE3 digest or equivalent).
    pub client_blob_id: BlobDigest,
    /// Nexus lane the blob is attached to.
    pub lane_id: LaneId,
    /// Epoch the blob belongs to.
    pub epoch: u64,
    /// Monotonic sequence scoped to `(lane_id, epoch)` used for replay detection.
    pub sequence: u64,
    /// Semantic classification of the blob.
    pub blob_class: BlobClass,
    /// Codec label describing the payload.
    pub codec: BlobCodec,
    /// Erasure profile requested for chunking.
    pub erasure_profile: ErasureProfile,
    /// Retention policy requested/negotiated for the blob.
    pub retention_policy: RetentionPolicy,
    /// Chunk size in bytes (power-of-two, aligned with erasure profile).
    pub chunk_size: u32,
    /// Total payload size in bytes.
    pub total_size: u64,
    /// Compression applied to the payload. Defaults to identity (no compression).
    #[norito(default)]
    pub compression: Compression,
    /// Optional pre-generated Norito manifest supplied by the caller.
    #[cfg_attr(
        feature = "json",
        norito(with = "crate::json_helpers::base64_vec::option")
    )]
    pub norito_manifest: Option<Vec<u8>>,
    /// Raw payload bytes to be chunked and replicated.
    #[cfg_attr(feature = "json", norito(with = "crate::json_helpers::base64_vec"))]
    pub payload: Vec<u8>,
    /// Additional metadata entries for governance/analytics.
    pub metadata: ExtraMetadata,
    /// Public key of the submitter.
    pub submitter: PublicKey,
    /// Signature over the canonical digest of this request.
    pub signature: Signature,
}

/// Ingest receipt returned once Torii accepts the blob.
#[derive(Clone, Debug, PartialEq, Eq, Encode, Decode, IntoSchema)]
#[cfg_attr(feature = "json", derive(DeriveJsonSerialize, DeriveJsonDeserialize))]
#[cfg_attr(any(feature = "ffi_export", feature = "ffi_import"), ffi_type)]
pub struct DaIngestReceipt {
    /// Caller-supplied blob identifier echoed back to the submitter.
    pub client_blob_id: BlobDigest,
    /// Nexus lane associated with the blob.
    pub lane_id: LaneId,
    /// Epoch recorded for the blob.
    pub epoch: u64,
    /// Blake3 digest of the raw payload.
    pub blob_hash: BlobDigest,
    /// Merkle root computed from chunk commitments.
    pub chunk_root: BlobDigest,
    /// Blake3 digest of the canonical Norito manifest.
    pub manifest_hash: BlobDigest,
    /// Storage ticket identifier issued by the orchestrator.
    pub storage_ticket: StorageTicketId,
    /// Norito-encoded PDP commitment derived from the accepted payload.
    #[cfg_attr(
        feature = "json",
        norito(with = "crate::json_helpers::base64_vec::option")
    )]
    #[norito(default)]
    pub pdp_commitment: Option<Vec<u8>>,
    /// Erasure layout summary for the admitted manifest.
    #[norito(default)]
    pub stripe_layout: DaStripeLayout,
    /// Unix timestamp (seconds) when the blob was accepted.
    pub queued_at_unix: u64,
    /// Rent and incentive breakdown quoted at ingest time.
    #[norito(default)]
    pub rent_quote: DaRentQuote,
    /// Signature generated by the Torii DA service.
    pub operator_signature: Signature,
}
