//! Immutable compiler-captured identities for this source owner’s existing codecs.

const CASES: &[crate::captured_schema_tests::Case] = &[
    crate::captured_schema_tests::Case::bidirectional::<super::MusubiResolverReleaseRowV1>(
        "iroha_data_model::musubi::MusubiResolverReleaseRowV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MusubiExactReleaseSnapshotV1>(
        "iroha_data_model::musubi::MusubiExactReleaseSnapshotV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MusubiFinalizedCursorV1>(
        "iroha_data_model::musubi::MusubiFinalizedCursorV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MusubiCursorFailureV1>(
        "iroha_data_model::musubi::MusubiCursorFailureV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MusubiVersionPageV1>(
        "iroha_data_model::musubi::MusubiVersionPageV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MusubiMaintainerPageV1>(
        "iroha_data_model::musubi::MusubiMaintainerPageV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MusubiArchiveLocationPageV1>(
        "iroha_data_model::musubi::MusubiArchiveLocationPageV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MusubiArchiveRetentionDispositionV1>(
        "iroha_data_model::musubi::MusubiArchiveRetentionDispositionV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MusubiArchiveRetentionDecisionV1>(
        "iroha_data_model::musubi::MusubiArchiveRetentionDecisionV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MusubiArchiveRetentionQueryV1>(
        "iroha_data_model::musubi::MusubiArchiveRetentionQueryV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MusubiArchiveRetentionPageV1>(
        "iroha_data_model::musubi::MusubiArchiveRetentionPageV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MusubiAliasHistoryPageV1>(
        "iroha_data_model::musubi::MusubiAliasHistoryPageV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MusubiResolverIndexPageV1>(
        "iroha_data_model::musubi::MusubiResolverIndexPageV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MusubiOrderedPackageEntryV1>(
        "iroha_data_model::musubi::MusubiOrderedPackageEntryV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MusubiOrderedPackagePageV1>(
        "iroha_data_model::musubi::MusubiOrderedPackagePageV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MusubiExactPackageQueryV1>(
        "iroha_data_model::musubi::MusubiExactPackageQueryV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MusubiExactReleaseQueryV1>(
        "iroha_data_model::musubi::MusubiExactReleaseQueryV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MusubiOrderedPrefixV1>(
        "iroha_data_model::musubi::MusubiOrderedPrefixV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MusubiPageRequestV1>(
        "iroha_data_model::musubi::MusubiPageRequestV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MusubiResolverIndexQueryV1>(
        "iroha_data_model::musubi::MusubiResolverIndexQueryV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MusubiPackagePageQueryV1>(
        "iroha_data_model::musubi::MusubiPackagePageQueryV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MusubiArchiveLocationQueryV1>(
        "iroha_data_model::musubi::MusubiArchiveLocationQueryV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MusubiAliasQueryV1>(
        "iroha_data_model::musubi::MusubiAliasQueryV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MusubiOrderedPrefixQueryV1>(
        "iroha_data_model::musubi::MusubiOrderedPrefixQueryV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MusubiSearchSnapshotV1>(
        "iroha_data_model::musubi::MusubiSearchSnapshotV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MusubiSearchCursorV1>(
        "iroha_data_model::musubi::MusubiSearchCursorV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MusubiSearchPageRequestV1>(
        "iroha_data_model::musubi::MusubiSearchPageRequestV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MusubiSearchQueryV1>(
        "iroha_data_model::musubi::MusubiSearchQueryV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MusubiSearchHitV1>(
        "iroha_data_model::musubi::MusubiSearchHitV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MusubiSearchPageV1>(
        "iroha_data_model::musubi::MusubiSearchPageV1",
    ),
];

#[test]
fn captured_codec_schema_identities() {
    for case in CASES {
        case.check();
    }
}
