//! Immutable compiler-captured identities for this source owner’s existing codecs.

#[test]
fn captured_codec_schema_identities() {
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiNamespaceV1>(
        "iroha_data_model::musubi::MusubiNamespaceV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiPackageScopeV1>(
        "iroha_data_model::musubi::MusubiPackageScopeV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiNamespaceBindingV1>(
        "iroha_data_model::musubi::MusubiNamespaceBindingV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiPackageNameV1>(
        "iroha_data_model::musubi::MusubiPackageNameV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiPackageIdV1>(
        "iroha_data_model::musubi::MusubiPackageIdV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiPackageSelectorV1>(
        "iroha_data_model::musubi::MusubiPackageSelectorV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiPrereleaseIdentifierV1>(
        "iroha_data_model::musubi::MusubiPrereleaseIdentifierV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiVersionV1>(
        "iroha_data_model::musubi::MusubiVersionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiComparatorOpV1>(
        "iroha_data_model::musubi::MusubiComparatorOpV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiVersionComparatorV1>(
        "iroha_data_model::musubi::MusubiVersionComparatorV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiMinorWildcardV1>(
        "iroha_data_model::musubi::MusubiMinorWildcardV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiVersionReqV1>(
        "iroha_data_model::musubi::MusubiVersionReqV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiArchiveCommitmentV1>(
        "iroha_data_model::musubi::MusubiArchiveCommitmentV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiArtifactDescriptorV1>(
        "iroha_data_model::musubi::MusubiArtifactDescriptorV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::MusubiArchiveRegistrationProjectionV1,
    >("iroha_data_model::musubi::MusubiArchiveRegistrationProjectionV1");
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiArchiveRecordV1>(
        "iroha_data_model::musubi::MusubiArchiveRecordV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiArchiveLocationStateV1>(
        "iroha_data_model::musubi::MusubiArchiveLocationStateV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiArchiveLocationKeyV1>(
        "iroha_data_model::musubi::MusubiArchiveLocationKeyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiPinLocationReferenceV1>(
        "iroha_data_model::musubi::MusubiPinLocationReferenceV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiProviderLocationKeyV1>(
        "iroha_data_model::musubi::MusubiProviderLocationKeyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiArchiveLocationV1>(
        "iroha_data_model::musubi::MusubiArchiveLocationV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiStorageAvailabilityV1>(
        "iroha_data_model::musubi::MusubiStorageAvailabilityV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiArchiveAvailabilityV1>(
        "iroha_data_model::musubi::MusubiArchiveAvailabilityV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiArchiveReverseReferencesV1>(
        "iroha_data_model::musubi::MusubiArchiveReverseReferencesV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiReleaseIdV1>(
        "iroha_data_model::musubi::MusubiReleaseIdV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiKotodamaEditionV1>(
        "iroha_data_model::musubi::MusubiKotodamaEditionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiAbiBindingV1>(
        "iroha_data_model::musubi::MusubiAbiBindingV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiDependencyReqV1>(
        "iroha_data_model::musubi::MusubiDependencyReqV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiDependencyKindV1>(
        "iroha_data_model::musubi::MusubiDependencyKindV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiKeywordV1>(
        "iroha_data_model::musubi::MusubiKeywordV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiReleaseMetadataV1>(
        "iroha_data_model::musubi::MusubiReleaseMetadataV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiRegistrySnapshotV1>(
        "iroha_data_model::musubi::MusubiRegistrySnapshotV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiExactDependencyEdgeV1>(
        "iroha_data_model::musubi::MusubiExactDependencyEdgeV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiVerificationNodeV1>(
        "iroha_data_model::musubi::MusubiVerificationNodeV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiVerificationLockV1>(
        "iroha_data_model::musubi::MusubiVerificationLockV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiResolutionProofV1>(
        "iroha_data_model::musubi::MusubiResolutionProofV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiSemanticReleaseManifestV1>(
        "iroha_data_model::musubi::MusubiSemanticReleaseManifestV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiReleaseManifestV1>(
        "iroha_data_model::musubi::MusubiReleaseManifestV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiPublicationV1>(
        "iroha_data_model::musubi::MusubiPublicationV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiSeedIngressReceiptBindingV1>(
        "iroha_data_model::musubi::MusubiSeedIngressReceiptBindingV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiSeedIngressReceiptPayloadV1>(
        "iroha_data_model::musubi::MusubiSeedIngressReceiptPayloadV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiSeedIngressReceiptApprovalV1>(
        "iroha_data_model::musubi::MusubiSeedIngressReceiptApprovalV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiSeedIngressReceiptV1>(
        "iroha_data_model::musubi::MusubiSeedIngressReceiptV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::MusubiProviderBundleVerificationBindingV1,
    >("iroha_data_model::musubi::MusubiProviderBundleVerificationBindingV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::MusubiProviderBundleVerificationPayloadV1,
    >("iroha_data_model::musubi::MusubiProviderBundleVerificationPayloadV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::MusubiProviderBundleVerificationApprovalV1,
    >("iroha_data_model::musubi::MusubiProviderBundleVerificationApprovalV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::MusubiProviderBundleVerificationAttestationV1,
    >("iroha_data_model::musubi::MusubiProviderBundleVerificationAttestationV1");
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiProviderBundleAttestationKeyV1>(
        "iroha_data_model::musubi::MusubiProviderBundleAttestationKeyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiProviderBundleAttestationRefV1>(
        "iroha_data_model::musubi::MusubiProviderBundleAttestationRefV1",
    );
    crate::captured_schema_tests::assert_serialize::<
        super::MusubiProviderBundleAttestationSetPreimageV1,
    >("iroha_data_model::musubi::MusubiProviderBundleAttestationSetPreimageV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::MusubiProviderBundleAttestationRecordV1,
    >("iroha_data_model::musubi::MusubiProviderBundleAttestationRecordV1");
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiNamespaceDelegationPayloadV1>(
        "iroha_data_model::musubi::MusubiNamespaceDelegationPayloadV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiNamespaceDelegationApprovalV1>(
        "iroha_data_model::musubi::MusubiNamespaceDelegationApprovalV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiNamespaceDelegationV1>(
        "iroha_data_model::musubi::MusubiNamespaceDelegationV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiPackageRevisionsV1>(
        "iroha_data_model::musubi::MusubiPackageRevisionsV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiPackageRecordV1>(
        "iroha_data_model::musubi::MusubiPackageRecordV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiMaintainerPermissionsV1>(
        "iroha_data_model::musubi::MusubiMaintainerPermissionsV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiPackageRoleV1>(
        "iroha_data_model::musubi::MusubiPackageRoleV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiPackageMemberKeyV1>(
        "iroha_data_model::musubi::MusubiPackageMemberKeyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiPackageMemberV1>(
        "iroha_data_model::musubi::MusubiPackageMemberV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiInvitationStateV1>(
        "iroha_data_model::musubi::MusubiInvitationStateV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiMaintainerInvitationV1>(
        "iroha_data_model::musubi::MusubiMaintainerInvitationV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiMaintainerDirectoryKeyV1>(
        "iroha_data_model::musubi::MusubiMaintainerDirectoryKeyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiMaintainerDirectoryEntryV1>(
        "iroha_data_model::musubi::MusubiMaintainerDirectoryEntryV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiPackageMetadataRecordV1>(
        "iroha_data_model::musubi::MusubiPackageMetadataRecordV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiReleaseYankV1>(
        "iroha_data_model::musubi::MusubiReleaseYankV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiArtifactTakedownV1>(
        "iroha_data_model::musubi::MusubiArtifactTakedownV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiArtifactGovernanceStateV1>(
        "iroha_data_model::musubi::MusubiArtifactGovernanceStateV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiReleaseSelectionStateV1>(
        "iroha_data_model::musubi::MusubiReleaseSelectionStateV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiReleaseRevisionsV1>(
        "iroha_data_model::musubi::MusubiReleaseRevisionsV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiReleaseRecordV1>(
        "iroha_data_model::musubi::MusubiReleaseRecordV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiAliasNameV1>(
        "iroha_data_model::musubi::MusubiAliasNameV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiAliasPricingPolicyV1>(
        "iroha_data_model::musubi::MusubiAliasPricingPolicyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiAliasRecordV1>(
        "iroha_data_model::musubi::MusubiAliasRecordV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiAliasHistoryActionV1>(
        "iroha_data_model::musubi::MusubiAliasHistoryActionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiAliasHistoryKeyV1>(
        "iroha_data_model::musubi::MusubiAliasHistoryKeyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiAliasHistoryEntryV1>(
        "iroha_data_model::musubi::MusubiAliasHistoryEntryV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiGovernanceDecisionV1>(
        "iroha_data_model::musubi::MusubiGovernanceDecisionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::MusubiGovernanceDecisionConsumptionV1,
    >("iroha_data_model::musubi::MusubiGovernanceDecisionConsumptionV1");
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiRecoverPackageOwnersV1>(
        "iroha_data_model::musubi::MusubiRecoverPackageOwnersV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiRetargetAliasV1>(
        "iroha_data_model::musubi::MusubiRetargetAliasV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiTakedownArtifactActionV1>(
        "iroha_data_model::musubi::MusubiTakedownArtifactActionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiSetRegistryPolicyActionV1>(
        "iroha_data_model::musubi::MusubiSetRegistryPolicyActionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MusubiParliamentActionV1>(
        "iroha_data_model::musubi::MusubiParliamentActionV1",
    );
}
