//! Immutable compiler-captured identities for this source owner’s existing codecs.

const CASES: &[crate::captured_schema_tests::Case] = &[
    crate::captured_schema_tests::Case::bidirectional::<
        super::ReputationFinalizedArchiveRetentionTargetV1,
    >("iroha_data_model::sorafs::reputation::ReputationFinalizedArchiveRetentionTargetV1"),
    crate::captured_schema_tests::Case::bidirectional::<
        super::ReputationFinalizedArchiveRetentionRequestV1,
    >("iroha_data_model::sorafs::reputation::ReputationFinalizedArchiveRetentionRequestV1"),
    crate::captured_schema_tests::Case::bidirectional::<super::ReputationJournalSourceIdV1>(
        "iroha_data_model::sorafs::reputation::ReputationJournalSourceIdV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ReputationJournalEventIdV1>(
        "iroha_data_model::sorafs::reputation::ReputationJournalEventIdV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ReputationJournalSourceKindV1>(
        "iroha_data_model::sorafs::reputation::ReputationJournalSourceKindV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ReputationJournalAuthorityPolicyV1>(
        "iroha_data_model::sorafs::reputation::ReputationJournalAuthorityPolicyV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<
        super::ReputationJournalAuthorityPolicyRecordV1,
    >("iroha_data_model::sorafs::reputation::ReputationJournalAuthorityPolicyRecordV1"),
    crate::captured_schema_tests::Case::bidirectional::<super::PorTerminalFailureKindV1>(
        "iroha_data_model::sorafs::reputation::PorTerminalFailureKindV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::PorTerminalExcludedKindV1>(
        "iroha_data_model::sorafs::reputation::PorTerminalExcludedKindV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::PorTerminalStatusV1>(
        "iroha_data_model::sorafs::reputation::PorTerminalStatusV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::PorTerminalOutcomeV1>(
        "iroha_data_model::sorafs::reputation::PorTerminalOutcomeV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ProviderDisputeKindV1>(
        "iroha_data_model::sorafs::reputation::ProviderDisputeKindV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ProviderDisputeResolutionV1>(
        "iroha_data_model::sorafs::reputation::ProviderDisputeResolutionV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ProviderDisputeStatusV1>(
        "iroha_data_model::sorafs::reputation::ProviderDisputeStatusV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ProviderDisputeEventV1>(
        "iroha_data_model::sorafs::reputation::ProviderDisputeEventV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::StreamTokenViolationKindV1>(
        "iroha_data_model::sorafs::reputation::StreamTokenViolationKindV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::StreamTokenExcludedKindV1>(
        "iroha_data_model::sorafs::reputation::StreamTokenExcludedKindV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::StreamTokenValidationStatusV1>(
        "iroha_data_model::sorafs::reputation::StreamTokenValidationStatusV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::StreamTokenExactHeaderDigestV1>(
        "iroha_data_model::sorafs::reputation::StreamTokenExactHeaderDigestV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::StreamTokenPresentationV1>(
        "iroha_data_model::sorafs::reputation::StreamTokenPresentationV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::StreamTokenCarRangeV1>(
        "iroha_data_model::sorafs::reputation::StreamTokenCarRangeV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::StreamTokenChunkRequestV1>(
        "iroha_data_model::sorafs::reputation::StreamTokenChunkRequestV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::StreamTokenRequestRouteV1>(
        "iroha_data_model::sorafs::reputation::StreamTokenRequestRouteV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::StreamTokenValidationRequestContextV1>(
        "iroha_data_model::sorafs::reputation::StreamTokenValidationRequestContextV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::StreamTokenValidationBindingV1>(
        "iroha_data_model::sorafs::reputation::StreamTokenValidationBindingV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::StreamTokenValidationOutcomeV1>(
        "iroha_data_model::sorafs::reputation::StreamTokenValidationOutcomeV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ReputationJournalPayloadV1>(
        "iroha_data_model::sorafs::reputation::ReputationJournalPayloadV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ReputationJournalEntryV1>(
        "iroha_data_model::sorafs::reputation::ReputationJournalEntryV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ReputationJournalSourceHeadV1>(
        "iroha_data_model::sorafs::reputation::ReputationJournalSourceHeadV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<
        super::ReputationJournalCommittedEventRecordV1,
    >("iroha_data_model::sorafs::reputation::ReputationJournalCommittedEventRecordV1"),
    crate::captured_schema_tests::Case::bidirectional::<super::ReputationJournalFinalizedCursorV1>(
        "iroha_data_model::sorafs::reputation::ReputationJournalFinalizedCursorV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<
        super::ReputationJournalFinalizedEventCursorV1,
    >("iroha_data_model::sorafs::reputation::ReputationJournalFinalizedEventCursorV1"),
    crate::captured_schema_tests::Case::bidirectional::<super::ReputationJournalFinalizedEventV1>(
        "iroha_data_model::sorafs::reputation::ReputationJournalFinalizedEventV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ReputationJournalFinalizedEventPageV1>(
        "iroha_data_model::sorafs::reputation::ReputationJournalFinalizedEventPageV1",
    ),
];

#[test]
fn captured_codec_schema_identities() {
    for case in CASES {
        case.check();
    }
}
