//! RS16 chunk commitment helpers for DA ingest.

use axum::http::StatusCode;
use iroha_data_model::da::{
    ingest::DaIngestRequest,
    manifest::{ChunkCommitment, ChunkRole},
    types::ChunkDigest,
};
use iroha_primitives::erasure::rs16 as erasure_rs16;
use sorafs_car::ChunkStore;

/// Smallest DA chunk accepted by the synchronous RS16 ingest path.
pub(super) const MIN_CHUNK_SIZE_BYTES: u32 = 1024;
/// Largest DA chunk accepted by the synchronous RS16 ingest path.
pub(super) const MAX_CHUNK_SIZE_BYTES: u32 = 2 * 1024 * 1024;
/// Maximum number of source chunks admitted for one DA manifest.
pub(super) const MAX_DATA_CHUNKS: usize = 1024;
/// Maximum number of source shards in one RS16 stripe.
pub(super) const MAX_DATA_SHARDS: u16 = 64;
/// Maximum number of parity shards generated for one RS16 stripe.
pub(super) const MAX_PARITY_SHARDS: u16 = 64;
/// Maximum number of cross-stripe parity rows.
pub(super) const MAX_ROW_PARITY_STRIPES: u16 = 64;
/// Maximum number of source rows accepted by a cross-stripe RS16 invocation.
pub(super) const MAX_ROW_PARITY_SOURCE_STRIPES: usize = 64;
/// Maximum decompressed payload handled by one synchronous DA ingest request.
pub(super) const MAX_CANONICAL_PAYLOAD_BYTES: u64 = 64 * 1024 * 1024;
/// Maximum parity bytes generated by one synchronous DA ingest request.
pub(super) const MAX_ERASURE_GENERATED_BYTES: u64 = 256 * 1024 * 1024;
/// Maximum transient RS16 symbol workspace admitted for one ingest request.
pub(super) const MAX_ERASURE_WORKSPACE_BYTES: u64 = 256 * 1024 * 1024;

// With at most 1,024 data chunks, 64 data/parity shards, and 64 row-parity
// stripes, the largest legal manifest contains 10,240 commitments. Keep a
// little headroom while retaining a hard allocation ceiling.
const MAX_MANIFEST_CHUNK_COMMITMENTS: usize = 16 * 1024;

/// Reject erasure layouts whose bounded dimensions still multiply into an
/// excessive CPU or memory workload.
///
/// Dimension-by-dimension limits are insufficient here: for example, 32
/// two-mebibyte source chunks with one data shard and 64 parity shards satisfy
/// every individual cap but would generate four gibibytes of parity. Keep the
/// product limits in one helper so HTTP admission and internal callers enforce
/// the same budget.
pub(super) fn validate_erasure_work_budget(
    data_chunk_count: usize,
    chunk_size: usize,
    data_shards: usize,
    parity_shards: usize,
    row_parity: usize,
) -> Result<(), &'static str> {
    if data_chunk_count == 0 {
        return Ok(());
    }
    if data_shards == 0 {
        return Err("erasure profile must include at least one data shard");
    }

    let stripes = data_chunk_count.div_ceil(data_shards) as u128;
    let data_shards = data_shards as u128;
    let parity_shards = parity_shards as u128;
    let row_parity = row_parity as u128;
    let chunk_size = chunk_size as u128;
    let columns = data_shards
        .checked_add(parity_shards)
        .ok_or("erasure work dimensions overflow")?;

    let global_parity_chunks = stripes
        .checked_mul(parity_shards)
        .ok_or("erasure work dimensions overflow")?;
    let row_parity_chunks = columns
        .checked_mul(row_parity)
        .ok_or("erasure work dimensions overflow")?;
    let generated_bytes = global_parity_chunks
        .checked_add(row_parity_chunks)
        .and_then(|chunks| chunks.checked_mul(chunk_size))
        .ok_or("erasure work dimensions overflow")?;
    if generated_bytes > u128::from(MAX_ERASURE_GENERATED_BYTES) {
        return Err("erasure profile exceeds the 256 MiB generated-parity budget");
    }

    // `encode_parity` returns a second parity vector before those symbols are
    // moved into the stripe. With row parity enabled, every completed stripe
    // remains resident and the column pass additionally clones one symbol
    // vector per stripe and materializes all parity vectors for that column.
    let global_phase_vectors = if row_parity == 0 {
        data_shards
            .checked_add(
                parity_shards
                    .checked_mul(2)
                    .ok_or("erasure work dimensions overflow")?,
            )
            .and_then(|vectors| vectors.checked_add(1))
            .ok_or("erasure work dimensions overflow")?
    } else {
        stripes
            .checked_mul(columns)
            .and_then(|vectors| vectors.checked_add(parity_shards))
            .and_then(|vectors| vectors.checked_add(1))
            .ok_or("erasure work dimensions overflow")?
    };
    let row_phase_vectors = if row_parity == 0 {
        0
    } else {
        stripes
            .checked_mul(columns)
            .and_then(|vectors| vectors.checked_add(stripes))
            .and_then(|vectors| vectors.checked_add(row_parity))
            .and_then(|vectors| vectors.checked_add(1))
            .ok_or("erasure work dimensions overflow")?
    };
    let workspace_bytes = global_phase_vectors
        .max(row_phase_vectors)
        .checked_mul(chunk_size)
        .ok_or("erasure work dimensions overflow")?;
    if workspace_bytes > u128::from(MAX_ERASURE_WORKSPACE_BYTES) {
        return Err("erasure profile exceeds the 256 MiB RS16 workspace budget");
    }

    Ok(())
}

pub(super) fn build_chunk_commitments(
    request: &DaIngestRequest,
    chunk_store: &ChunkStore,
    canonical_payload: &[u8],
) -> Result<Vec<ChunkCommitment>, (StatusCode, String)> {
    build_chunk_commitments_with_parity_observer(
        request,
        chunk_store,
        canonical_payload,
        |_index, _symbols| Ok(()),
    )
}

pub(super) fn build_chunk_commitments_with_parity_observer<F>(
    request: &DaIngestRequest,
    chunk_store: &ChunkStore,
    canonical_payload: &[u8],
    mut parity_observer: F,
) -> Result<Vec<ChunkCommitment>, (StatusCode, String)>
where
    F: FnMut(u32, &[u16]) -> Result<(), (StatusCode, String)>,
{
    let chunk_size = usize::try_from(request.chunk_size).map_err(|_| {
        (
            StatusCode::BAD_REQUEST,
            "chunk_size exceeds supported host size".into(),
        )
    })?;
    if !(MIN_CHUNK_SIZE_BYTES as usize..=MAX_CHUNK_SIZE_BYTES as usize).contains(&chunk_size)
        || chunk_size % 2 != 0
    {
        return Err((
            StatusCode::BAD_REQUEST,
            "chunk_size is outside the supported RS16 ingest range".into(),
        ));
    }

    let data_shards = usize::from(request.erasure_profile.data_shards);
    let parity_shards = usize::from(request.erasure_profile.parity_shards);
    if data_shards == 0 {
        return Err((
            StatusCode::BAD_REQUEST,
            "erasure profile must include at least one data shard".to_string(),
        ));
    }
    if data_shards > usize::from(MAX_DATA_SHARDS) || parity_shards > usize::from(MAX_PARITY_SHARDS)
    {
        return Err((
            StatusCode::BAD_REQUEST,
            "erasure profile exceeds the bounded RS16 shard limits".to_string(),
        ));
    }

    let symbol_count = chunk_size / 2;
    let chunks = chunk_store.chunks();
    if chunks.is_empty() {
        return Ok(Vec::new());
    }
    if chunks.len() > MAX_DATA_CHUNKS {
        return Err((
            StatusCode::PAYLOAD_TOO_LARGE,
            "DA manifest exceeds the bounded source-chunk limit".to_string(),
        ));
    }

    let stripes = chunks.len().div_ceil(data_shards);
    let row_parity = usize::from(request.erasure_profile.row_parity_stripes);
    if row_parity > usize::from(MAX_ROW_PARITY_STRIPES)
        || (row_parity > 0 && stripes > MAX_ROW_PARITY_SOURCE_STRIPES)
    {
        return Err((
            StatusCode::BAD_REQUEST,
            "erasure profile exceeds the bounded row-parity work budget".to_string(),
        ));
    }
    validate_erasure_work_budget(
        chunks.len(),
        chunk_size,
        data_shards,
        parity_shards,
        row_parity,
    )
    .map_err(|message| (StatusCode::BAD_REQUEST, message.to_string()))?;
    let commitment_count =
        chunk_commitment_capacity_hint(chunks.len(), data_shards, parity_shards, row_parity)?;
    let mut commitments = Vec::new();
    commitments
        .try_reserve_exact(commitment_count)
        .map_err(|_| {
            (
                StatusCode::SERVICE_UNAVAILABLE,
                "insufficient memory for bounded DA manifest commitments".into(),
            )
        })?;
    let retain_row_parity_matrix = row_parity > 0;
    let mut stripe_symbols_matrix: Vec<Vec<Vec<u16>>> = if retain_row_parity_matrix {
        let mut matrix = Vec::new();
        matrix.try_reserve_exact(stripes).map_err(|_| {
            (
                StatusCode::SERVICE_UNAVAILABLE,
                "insufficient memory for bounded DA row-parity workspace".into(),
            )
        })?;
        matrix
    } else {
        Vec::new()
    };
    let mut hash_scratch = Vec::with_capacity(symbol_count.saturating_mul(2));
    let mut next_index: u32 = 0;

    for stripe in 0..stripes {
        let mut stripe_symbols = Vec::with_capacity(data_shards + parity_shards);
        for shard_idx in 0..data_shards {
            let chunk_idx = stripe * data_shards + shard_idx;
            if let Some(chunk) = chunks.get(chunk_idx) {
                let offset = usize::try_from(chunk.offset).map_err(|_| {
                    (
                        StatusCode::BAD_REQUEST,
                        format!("chunk {chunk_idx} offset exceeds host limits"),
                    )
                })?;
                let length = usize::try_from(chunk.length).map_err(|_| {
                    (
                        StatusCode::BAD_REQUEST,
                        format!("chunk {chunk_idx} length exceeds host limits"),
                    )
                })?;
                if length > chunk_size {
                    return Err((
                        StatusCode::BAD_REQUEST,
                        format!("chunk length {length} exceeds configured chunk_size {chunk_size}"),
                    ));
                }
                let end = offset.checked_add(length).ok_or_else(|| {
                    (
                        StatusCode::BAD_REQUEST,
                        format!("chunk {chunk_idx} offset+length overflow"),
                    )
                })?;
                if end > canonical_payload.len() {
                    return Err((
                        StatusCode::BAD_REQUEST,
                        format!("chunk {chunk_idx} extends past canonical payload"),
                    ));
                }

                let symbols =
                    erasure_rs16::symbols_from_chunk(symbol_count, &canonical_payload[offset..end]);
                stripe_symbols.push(symbols.clone());

                let index = allocate_chunk_index(&mut next_index)?;
                let stripe_id = manifest_u32_index(stripe, "manifest stripe id")?;
                commitments.push(ChunkCommitment::new_with_role(
                    index,
                    chunk.offset,
                    chunk.length,
                    ChunkDigest::new(chunk.blake3),
                    ChunkRole::Data,
                    stripe_id,
                ));
            } else {
                stripe_symbols.push(vec![0u16; symbol_count]);
            }
        }

        if parity_shards == 0 {
            if retain_row_parity_matrix {
                stripe_symbols_matrix.push(stripe_symbols);
            }
            continue;
        }

        let parity_symbols: Vec<Vec<u16>> =
            erasure_rs16::encode_parity(&stripe_symbols, parity_shards).map_err(|_| {
                (
                    StatusCode::INTERNAL_SERVER_ERROR,
                    "failed to compute parity shards".into(),
                )
            })?;

        for (parity_idx, symbols) in parity_symbols.iter().enumerate() {
            let digest = digest_symbols_le(symbols, &mut hash_scratch);
            let offset = erasure_rs16::parity_offset(
                request.total_size,
                stripe,
                parity_idx,
                parity_shards,
                request.chunk_size,
            )
            .ok_or_else(|| {
                (
                    StatusCode::BAD_REQUEST,
                    "parity chunk offset exceeded supported size".into(),
                )
            })?;

            let index = allocate_chunk_index(&mut next_index)?;
            parity_observer(index, symbols)?;
            let stripe_id = manifest_u32_index(stripe, "manifest stripe id")?;
            commitments.push(ChunkCommitment::new_with_role(
                index,
                offset,
                request.chunk_size,
                ChunkDigest::new(digest),
                ChunkRole::GlobalParity,
                stripe_id,
            ));
            stripe_symbols.push(symbols.clone());
        }

        if retain_row_parity_matrix {
            stripe_symbols_matrix.push(stripe_symbols);
        }
    }

    if row_parity > 0 {
        let column_count = data_shards + parity_shards;
        let global_parity_bytes = stripes
            .checked_mul(parity_shards)
            .and_then(|count| count.checked_mul(chunk_size))
            .and_then(|bytes| u64::try_from(bytes).ok())
            .ok_or_else(|| {
                (
                    StatusCode::BAD_REQUEST,
                    "stripe parity base offset exceeded supported size".into(),
                )
            })?;
        let base_offset = request
            .total_size
            .checked_add(global_parity_bytes)
            .ok_or_else(|| {
                (
                    StatusCode::BAD_REQUEST,
                    "stripe parity base offset exceeded supported size".into(),
                )
            })?;
        for column in 0..column_count {
            // Collect the column symbols across stripes.
            let mut column_symbols = Vec::with_capacity(stripes);
            for stripe in 0..stripes {
                let stripe_row = stripe_symbols_matrix
                    .get(stripe)
                    .and_then(|row| row.get(column))
                    .cloned()
                    .unwrap_or_else(|| vec![0u16; symbol_count]);
                column_symbols.push(stripe_row);
            }

            let parity_cols: Vec<Vec<u16>> =
                erasure_rs16::encode_parity(&column_symbols, row_parity).map_err(|_| {
                    (
                        StatusCode::INTERNAL_SERVER_ERROR,
                        "failed to compute row-parity stripes".into(),
                    )
                })?;

            for (row_parity_idx, symbols) in parity_cols.iter().enumerate() {
                let digest = digest_symbols_le(symbols, &mut hash_scratch);

                let row_parity_chunk_index = row_parity_idx
                    .checked_mul(column_count)
                    .and_then(|base| base.checked_add(column))
                    .and_then(|index| u64::try_from(index).ok())
                    .ok_or_else(|| {
                        (
                            StatusCode::BAD_REQUEST,
                            "stripe parity chunk offset exceeded supported size".into(),
                        )
                    })?;
                let row_parity_bytes = row_parity_chunk_index
                    .checked_mul(u64::from(request.chunk_size))
                    .ok_or_else(|| {
                        (
                            StatusCode::BAD_REQUEST,
                            "stripe parity chunk offset exceeded supported size".into(),
                        )
                    })?;
                let offset = base_offset.checked_add(row_parity_bytes).ok_or_else(|| {
                    (
                        StatusCode::BAD_REQUEST,
                        "stripe parity chunk offset exceeded supported size".into(),
                    )
                })?;
                let index = allocate_chunk_index(&mut next_index)?;
                parity_observer(index, symbols)?;
                let column_id = manifest_u32_index(column, "manifest stripe parity column id")?;
                commitments.push(ChunkCommitment::new_with_role(
                    index,
                    offset,
                    request.chunk_size,
                    ChunkDigest::new(digest),
                    ChunkRole::StripeParity,
                    column_id,
                ));
            }
        }
    }

    Ok(commitments)
}

fn digest_symbols_le(symbols: &[u16], scratch: &mut Vec<u8>) -> [u8; 32] {
    scratch.clear();
    scratch.reserve(symbols.len().saturating_mul(2));
    for symbol in symbols {
        scratch.extend_from_slice(&symbol.to_le_bytes());
    }
    *blake3::hash(scratch.as_slice()).as_bytes()
}

fn manifest_u32_index(value: usize, label: &str) -> Result<u32, (StatusCode, String)> {
    u32::try_from(value).map_err(|_| {
        (
            StatusCode::BAD_REQUEST,
            format!("{label} exceeds supported u32 space"),
        )
    })
}

fn chunk_commitment_capacity_hint(
    data_chunk_count: usize,
    data_shards: usize,
    parity_shards: usize,
    row_parity: usize,
) -> Result<usize, (StatusCode, String)> {
    if data_chunk_count == 0 {
        return Ok(0);
    }
    if data_shards == 0 {
        return Err((
            StatusCode::BAD_REQUEST,
            "erasure profile must include at least one data shard".into(),
        ));
    }

    let stripes = data_chunk_count.div_ceil(data_shards);
    let column_count = data_shards.checked_add(parity_shards).ok_or_else(|| {
        (
            StatusCode::BAD_REQUEST,
            "manifest commitment count exceeds supported size".into(),
        )
    })?;
    let global_parity = stripes.checked_mul(parity_shards).ok_or_else(|| {
        (
            StatusCode::BAD_REQUEST,
            "manifest commitment count exceeds supported size".into(),
        )
    })?;
    let row_parity_chunks = row_parity.checked_mul(column_count).ok_or_else(|| {
        (
            StatusCode::BAD_REQUEST,
            "manifest commitment count exceeds supported size".into(),
        )
    })?;
    let total = data_chunk_count
        .checked_add(global_parity)
        .and_then(|count| count.checked_add(row_parity_chunks))
        .ok_or_else(|| {
            (
                StatusCode::BAD_REQUEST,
                "manifest commitment count exceeds supported size".into(),
            )
        })?;
    if total > MAX_MANIFEST_CHUNK_COMMITMENTS {
        return Err((
            StatusCode::BAD_REQUEST,
            "manifest would exceed the bounded commitment allocation".into(),
        ));
    }
    Ok(total)
}

fn allocate_chunk_index(counter: &mut u32) -> Result<u32, (StatusCode, String)> {
    let idx = *counter;
    *counter = counter.checked_add(1).ok_or_else(|| {
        (
            StatusCode::BAD_REQUEST,
            "manifest would exceed supported chunk index space".into(),
        )
    })?;
    Ok(idx)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn allocate_chunk_index_rejects_overflow_without_wrapping() {
        let mut counter = u32::MAX;

        let err = allocate_chunk_index(&mut counter).expect_err("exhausted index must reject");

        assert_eq!(err.0, StatusCode::BAD_REQUEST);
        assert!(
            err.1.contains("chunk index space"),
            "unexpected error: {}",
            err.1
        );
        assert_eq!(counter, u32::MAX);
    }

    #[cfg(target_pointer_width = "64")]
    #[test]
    fn manifest_u32_index_rejects_overflow_without_saturating() {
        let overflow = u32::MAX as usize + 1;

        let err = manifest_u32_index(overflow, "manifest stripe id")
            .expect_err("overflowed stripe id must reject");

        assert_eq!(err.0, StatusCode::BAD_REQUEST);
        assert!(
            err.1
                .contains("manifest stripe id exceeds supported u32 space"),
            "unexpected error: {}",
            err.1
        );
    }

    #[test]
    fn chunk_commitment_capacity_hint_counts_row_parity_once_per_column() {
        let capacity =
            chunk_commitment_capacity_hint(5, 2, 1, 2).expect("capacity math should fit");

        assert_eq!(
            capacity, 14,
            "5 data chunks + 3 global parity chunks + 2 row parity stripes across 3 columns"
        );
    }

    #[test]
    fn chunk_commitment_capacity_hint_rejects_resource_exhaustion_before_allocation() {
        let data_chunks = MAX_MANIFEST_CHUNK_COMMITMENTS;

        let err = chunk_commitment_capacity_hint(data_chunks, 1, 1, 0)
            .expect_err("commitment count over the operational limit must reject");

        assert_eq!(err.0, StatusCode::BAD_REQUEST);
        assert!(
            err.1.contains("bounded commitment allocation"),
            "unexpected error: {}",
            err.1
        );
    }

    #[test]
    fn erasure_work_budget_rejects_multiplicative_parity_amplification() {
        let err = validate_erasure_work_budget(
            32,
            MAX_CHUNK_SIZE_BYTES as usize,
            1,
            MAX_PARITY_SHARDS as usize,
            0,
        )
        .expect_err("bounded dimensions must not permit four GiB of parity work");

        assert!(err.contains("generated-parity budget"), "{err}");
    }

    #[test]
    fn erasure_work_budget_rejects_large_retained_row_matrix() {
        let err = validate_erasure_work_budget(
            32,
            MAX_CHUNK_SIZE_BYTES as usize,
            1,
            32,
            1,
        )
        .expect_err("row-parity matrix must fit the explicit workspace budget");

        assert!(err.contains("RS16 workspace budget"), "{err}");
    }
}
