// Code generated by `cargo run -p sorafs_chunker --bin export_vectors`; DO NOT EDIT.
package sorafsfixtures

type ChunkerFixture struct {
    Profile string
    ProfileAliases []string
    InputSeed string
    InputLength int
    PRNGMultiplier uint64
    PRNGIncrement uint64
    ChunkCount int
    ChunkLengths []int
    ChunkOffsets []int
    ChunkDigestSHA3_256 string
    ChunkDigestsBLAKE3 []string
}

var SF1ProfileV1 = ChunkerFixture{
    Profile: "sorafs.sf1@1.0.0",
    ProfileAliases: []string{"sorafs.sf1@1.0.0"},
    InputSeed: "0x0000000000DEC0DED",
    InputLength: 1048576,
    PRNGMultiplier: 2862933555777941757,
    PRNGIncrement: 3037000493,
    ChunkCount: 5,
    ChunkLengths: []int{
        177082,
        210377,
        403145,
        187169,
        70803,
    },
    ChunkOffsets: []int{
        0,
        177082,
        387459,
        790604,
        977773,
    },
    ChunkDigestSHA3_256: "13fa919c67e55a2e95a13ff8b0c6b40b2e51d6ef505568990f3bc7754e6cc482",
    ChunkDigestsBLAKE3: []string{
        "7789b490337d16c51b59a92e354a657ba450da4bab872c31e85e4d4fedcb3a27",
        "56397fe0ff8cc24c790e0719505fff05c49dca09289b595d17455bedcc1f7438",
        "2a2a47eedcc11effdb5d13190fe09143d6b31f959c72980bb0f2b8a5058971fd",
        "8dbb40d7a3439aa57bd69a3adfe98ff43b9043764072bc42d7dc211942e46ef8",
        "194c8180f4b90e021a86199d17092af3b2bd29792dc028e401258d903616b664",
    },
}
