//! Release-audit signoff codec assertions and fixture ownership.

use super::*;

pub(super) struct SignedRecords {
    pub(super) record: BfvFullBootstrapReleaseAuditRecordV1,
    pub(super) stale_generated_body_record: BfvFullBootstrapReleaseAuditRecordV1,
    pub(super) stale_material_for_record_builder_preflight: BfvFullBootstrapCircuitMaterialV1,
}

pub(super) fn check(
    artifact_fixture: &ArtifactFixture,
    review_fixture: &ReviewDocuments,
    signoff_authority: &SignoffFixtures,
) -> SignedRecords {
    let evidence_bytes =
        norito::to_bytes(&artifact_fixture.evidence).expect("encode audit evidence");
    let signoff_bytes = norito::to_bytes(&signoff_authority.signoff).expect("encode audit signoff");
    let_row! { evidence_digest = release_evidence_digest_v1(&artifact_fixture.evidence).expect("release audit evidence digest") };
    let_row! { decoded_signoff = norito::decode_from_bytes::<BfvFullBootstrapReleaseAuditSignoffV1>(&signoff_bytes) .expect("decode audit signoff") };
    assert_eq_row! { decoded_signoff, signoff_authority.signoff, "{}", artifact_fixture.diagnostics.static_context_at(151) };
    let_row! { safely_decoded_signoff = decode_bfv_full_bootstrap_release_audit_signoff_bytes_v1(&signoff_bytes) .expect("safe canonical release audit signoff decode") };
    assert_eq_row! { safely_decoded_signoff, signoff_authority.signoff, "{}", artifact_fixture.diagnostics.static_context_at(152) };
    let_row! { signoff_digest = bfv_full_bootstrap_release_audit_signoff_digest_v1(&signoff_authority.signoff) .expect("release audit signoff digest") };
    assert_row! { (signoff_digest) == (Hash::new_from_chunks(&[ BFV_FULL_BOOTSTRAP_RELEASE_AUDIT_SIGNOFF_DIGEST_DOMAIN, signoff_bytes.as_slice(), ])) && (signoff_digest) == (bfv_full_bootstrap_release_audit_signoff_digest_from_bytes_v1(&signoff_bytes) .expect("canonical release audit signoff byte digest")), "{}", artifact_fixture.diagnostics.group_context(153, 2), };
    let_row! { (decoded_signoff_from_digest_helper, signoff_digest_from_bytes) = bfv_full_bootstrap_release_audit_signoff_and_digest_from_bytes_v1(&signoff_bytes) .expect("canonical release audit signoff bytes decode with digest") };
    assert_row! { (decoded_signoff_from_digest_helper) == (signoff_authority.signoff) && (signoff_digest_from_bytes) == (signoff_digest), "{}", artifact_fixture.diagnostics.group_context(155, 2), };
    validate_bfv_full_bootstrap_release_audit_signoff_for_evidence_v1(
        &decoded_signoff,
        &artifact_fixture.evidence,
    )
    .expect("decoded signed release audit signoff matches evidence");
    let_row! { (decoded_evidence_bytes, decoded_signoff_bytes) = validate_bfv_full_bootstrap_release_audit_signoff_bytes_for_evidence_bytes_v1( &evidence_bytes, &signoff_bytes, ) .expect("canonical release audit evidence/signoff bytes validate together") };
    assert_row! { (decoded_evidence_bytes) == (artifact_fixture.evidence) && (decoded_signoff_bytes) == (signoff_authority.signoff), "{}", artifact_fixture.diagnostics.group_context(157, 2), };
    let_row! { (digest_decoded_evidence_bytes, digest_decoded_signoff_bytes, signoff_pair_digest) = validate_bfv_full_bootstrap_release_audit_signoff_bytes_and_digest_for_evidence_bytes_v1( &evidence_bytes, &signoff_bytes, ) .expect("canonical release audit evidence/signoff bytes validate with digest") };
    assert_row! { (digest_decoded_evidence_bytes) == (artifact_fixture.evidence) && (digest_decoded_signoff_bytes) == (signoff_authority.signoff) && (signoff_pair_digest) == (signoff_digest), "{}", artifact_fixture.diagnostics.group_context(159, 3), };
    let_row! { ( digests_decoded_evidence_bytes, digests_decoded_signoff_bytes, evidence_pair_digest, signoff_pair_digest, ) = validate_bfv_full_bootstrap_release_audit_signoff_bytes_and_digests_for_evidence_bytes_v1( &evidence_bytes, &signoff_bytes, ) .expect("canonical release audit evidence/signoff bytes validate with both digests") };
    assert_row! { (digests_decoded_evidence_bytes) == (artifact_fixture.evidence) && (digests_decoded_signoff_bytes) == (signoff_authority.signoff) && (evidence_pair_digest) == (evidence_digest) && (signoff_pair_digest) == (signoff_digest), "{}", artifact_fixture.diagnostics.group_context(162, 4), };
    let_row! { (trusted_evidence_bytes, trusted_signoff_bytes) = validate_bfv_full_bootstrap_release_audit_signoff_bytes_for_evidence_bytes_trusted_reviewer_v1( &evidence_bytes, &signoff_bytes, "sora-zk-audit-wg-2026", review_fixture.reviewer_key_pair.public_key(), ) .expect("canonical release audit evidence/signoff bytes validate against trusted reviewer") };
    assert_row! { (trusted_evidence_bytes) == (artifact_fixture.evidence) && (trusted_signoff_bytes) == (signoff_authority.signoff), "{}", artifact_fixture.diagnostics.group_context(166, 2), };
    let_row! { (trusted_digest_evidence_bytes, trusted_digest_signoff_bytes, trusted_signoff_digest) = validate_bfv_full_bootstrap_release_audit_signoff_bytes_and_digest_for_evidence_bytes_trusted_reviewer_v1( &evidence_bytes, &signoff_bytes, "sora-zk-audit-wg-2026", review_fixture.reviewer_key_pair.public_key(), ) .expect("canonical release audit evidence/signoff bytes validate against trusted reviewer with digest") };
    assert_row! { (trusted_digest_evidence_bytes) == (artifact_fixture.evidence) && (trusted_digest_signoff_bytes) == (signoff_authority.signoff) && (trusted_signoff_digest) == (signoff_digest), "{}", artifact_fixture.diagnostics.group_context(168, 3), };
    let_row! { ( trusted_digests_evidence_bytes, trusted_digests_signoff_bytes, trusted_evidence_digest, trusted_signoff_digest, ) = validate_bfv_full_bootstrap_release_audit_signoff_bytes_and_digests_for_evidence_bytes_trusted_reviewer_v1( &evidence_bytes, &signoff_bytes, "sora-zk-audit-wg-2026", review_fixture.reviewer_key_pair.public_key(), ) .expect("canonical release audit evidence/signoff bytes validate against trusted reviewer with both digests") };
    assert_row! { (trusted_digests_evidence_bytes) == (artifact_fixture.evidence) && (trusted_digests_signoff_bytes) == (signoff_authority.signoff) && (trusted_evidence_digest) == (evidence_digest) && (trusted_signoff_digest) == (signoff_digest), "{}", artifact_fixture.diagnostics.group_context(171, 4), };
    let_row! { compressed_signoff_bytes = norito::to_compressed_bytes(&signoff_authority.signoff, Some(norito::CompressionConfig::default())) .expect("encode compressed release audit signoff") };
    assert_ne_row! { compressed_signoff_bytes, signoff_bytes, "compressed release audit signoff must differ from canonical v1 bytes" };
    let_row! { decoded_compressed_signoff = decode_trusted_compressed_fixture(&compressed_signoff_bytes, &signoff_authority.signoff) .expect("compressed release audit signoff must decode structurally") };
    assert_eq_row! { decoded_compressed_signoff, signoff_authority.signoff, "{}", artifact_fixture.diagnostics.static_context_at(175) };
    assert_error_matrix_row! { artifact_fixture.diagnostics; 176; (decode_bfv_full_bootstrap_release_audit_signoff_bytes_v1(&compressed_signoff_bytes)), (bfv_full_bootstrap_release_audit_signoff_and_digest_from_bytes_v1( &compressed_signoff_bytes, )), (validate_bfv_full_bootstrap_release_audit_signoff_bytes_for_evidence_bytes_v1( &evidence_bytes, &compressed_signoff_bytes, )), (validate_bfv_full_bootstrap_release_audit_signoff_bytes_and_digest_for_evidence_bytes_v1( &evidence_bytes, &compressed_signoff_bytes, )), (validate_bfv_full_bootstrap_release_audit_signoff_bytes_and_digests_for_evidence_bytes_v1( &evidence_bytes, &compressed_signoff_bytes, )) };
    let_row! { compressed_evidence_bytes = norito::to_compressed_bytes(&artifact_fixture.evidence, Some(norito::CompressionConfig::default())) .expect("encode compressed release audit signoff evidence") };
    assert_ne_row! { compressed_evidence_bytes, evidence_bytes, "compressed release audit signoff evidence must differ from canonical v1 bytes" };
    assert_eq_row! { decode_trusted_compressed_fixture(&compressed_evidence_bytes, &artifact_fixture.evidence) .expect("compressed release audit signoff evidence must decode structurally"), artifact_fixture.evidence, "{}", artifact_fixture.diagnostics.static_context_at(181) };
    assert_error_matrix_row! { artifact_fixture.diagnostics; 182; (validate_bfv_full_bootstrap_release_audit_signoff_bytes_for_evidence_bytes_v1( &compressed_evidence_bytes, &signoff_bytes, )), (validate_bfv_full_bootstrap_release_audit_signoff_bytes_and_digest_for_evidence_bytes_v1( &compressed_evidence_bytes, &signoff_bytes, )), (validate_bfv_full_bootstrap_release_audit_signoff_bytes_and_digests_for_evidence_bytes_v1( &compressed_evidence_bytes, &signoff_bytes, )) };
    let_row! { binary_split_placeholder_signoff_bytes = b"t\xffo\xffd\xffo pending BFV full-bootstrap release audit signoff bytes".to_vec() };
    assert_error_matrix_row! { artifact_fixture.diagnostics; 185; (decode_bfv_full_bootstrap_release_audit_signoff_bytes_v1( &binary_split_placeholder_signoff_bytes, )), (bfv_full_bootstrap_release_audit_signoff_and_digest_from_bytes_v1( &binary_split_placeholder_signoff_bytes, )), (validate_bfv_full_bootstrap_release_audit_signoff_bytes_for_evidence_bytes_v1( &evidence_bytes, &binary_split_placeholder_signoff_bytes, )), (validate_bfv_full_bootstrap_release_audit_signoff_bytes_and_digest_for_evidence_bytes_v1( &evidence_bytes, &binary_split_placeholder_signoff_bytes, )), (validate_bfv_full_bootstrap_release_audit_signoff_bytes_and_digests_for_evidence_bytes_v1( &evidence_bytes, &binary_split_placeholder_signoff_bytes, )), (validate_bfv_full_bootstrap_release_audit_signoff_bytes_for_evidence_bytes_trusted_reviewer_v1( &evidence_bytes, &binary_split_placeholder_signoff_bytes, " sora-zk-audit-wg-2026", review_fixture.reviewer_key_pair.public_key(), )), (validate_bfv_full_bootstrap_release_audit_signoff_bytes_for_evidence_bytes_trusted_reviewer_v1( &evidence_bytes, &binary_split_placeholder_signoff_bytes, "sora-zk-audit-wg-2026", &signoff_authority.all_zero_reviewer_public_key, )), (validate_bfv_full_bootstrap_release_audit_signoff_bytes_and_digest_for_evidence_bytes_trusted_reviewer_v1( &evidence_bytes, &binary_split_placeholder_signoff_bytes, " sora-zk-audit-wg-2026", review_fixture.reviewer_key_pair.public_key(), )), (validate_bfv_full_bootstrap_release_audit_signoff_bytes_and_digest_for_evidence_bytes_trusted_reviewer_v1( &evidence_bytes, &binary_split_placeholder_signoff_bytes, "sora-zk-audit-wg-2026", &signoff_authority.all_zero_reviewer_public_key, )), (validate_bfv_full_bootstrap_release_audit_signoff_bytes_and_digests_for_evidence_bytes_trusted_reviewer_v1( &evidence_bytes, &binary_split_placeholder_signoff_bytes, " sora-zk-audit-wg-2026", review_fixture.reviewer_key_pair.public_key(), )), (validate_bfv_full_bootstrap_release_audit_signoff_bytes_and_digests_for_evidence_bytes_trusted_reviewer_v1( &evidence_bytes, &binary_split_placeholder_signoff_bytes, "sora-zk-audit-wg-2026", &signoff_authority.all_zero_reviewer_public_key, )) };
    let_row! { binary_split_placeholder_evidence_bytes = b"t\xffo\xffd\xffo pending BFV full-bootstrap release audit signoff evidence bytes" .to_vec() };
    assert_error_matrix_row! { artifact_fixture.diagnostics; 196; (validate_bfv_full_bootstrap_release_audit_signoff_bytes_for_evidence_bytes_v1( &binary_split_placeholder_evidence_bytes, &signoff_bytes, )), (validate_bfv_full_bootstrap_release_audit_signoff_bytes_and_digest_for_evidence_bytes_v1( &binary_split_placeholder_evidence_bytes, &signoff_bytes, )), (validate_bfv_full_bootstrap_release_audit_signoff_bytes_and_digests_for_evidence_bytes_v1( &binary_split_placeholder_evidence_bytes, &signoff_bytes, )) };
    mutation_row! { stale_signoff_evidence = artifact_fixture.evidence.clone(); stale_signoff_evidence.artifact_bundle_digest = Hash::new(b"stale-signoff-byte-pair-artifact-bundle-digest"); let_row! { stale_signoff_evidence_bytes = norito::to_bytes(&stale_signoff_evidence).expect("encode stale signoff evidence") }; assert_error_matrix_row! { artifact_fixture.diagnostics; 199; (validate_bfv_full_bootstrap_release_audit_signoff_bytes_for_evidence_bytes_v1( &stale_signoff_evidence_bytes, &signoff_bytes, )), (validate_bfv_full_bootstrap_release_audit_signoff_bytes_and_digest_for_evidence_bytes_v1( &stale_signoff_evidence_bytes, &signoff_bytes, )), (validate_bfv_full_bootstrap_release_audit_signoff_bytes_and_digests_for_evidence_bytes_v1( &stale_signoff_evidence_bytes, &signoff_bytes, )), (validate_bfv_full_bootstrap_release_audit_signoff_bytes_for_evidence_bytes_trusted_reviewer_v1( &evidence_bytes, &signoff_bytes, "sora-zk-audit-wg-2027", review_fixture.reviewer_key_pair.public_key(), )), (validate_bfv_full_bootstrap_release_audit_signoff_bytes_and_digest_for_evidence_bytes_trusted_reviewer_v1( &evidence_bytes, &signoff_bytes, "sora-zk-audit-wg-2027", review_fixture.reviewer_key_pair.public_key(), )), (validate_bfv_full_bootstrap_release_audit_signoff_bytes_and_digests_for_evidence_bytes_trusted_reviewer_v1( &evidence_bytes, &signoff_bytes, "sora-zk-audit-wg-2027", review_fixture.reviewer_key_pair.public_key(), )) }; let_row! { record = release_record_v1( &artifact_fixture.params, &artifact_fixture.material, &artifact_fixture.artifacts, review_fixture.audit_report_digest, review_fixture.audit_evidence_archive_digest, "sora-zk-audit-wg-2026", review_fixture.reviewer_key_pair.private_key(), ) .expect("build release audit record") }; assert_eq_row! { record.evidence, artifact_fixture.evidence, "{}", artifact_fixture.diagnostics.static_context_at(205) }; validate_bfv_full_bootstrap_release_audit_record_v1(&record) .expect("release audit record validates"); let_row! { stale_generated_body_record = BfvFullBootstrapReleaseAuditRecordV1 { signoff: signoff_authority.stale_generated_body_signoff.clone(), ..record.clone() } }; assert_local_diag! { artifact_fixture.diagnostics; 206 => validate_bfv_full_bootstrap_release_audit_record_v1(&stale_generated_body_record) }; };
    validate_bfv_full_bootstrap_release_audit_record_for_artifacts_v1(
        &artifact_fixture.params,
        &artifact_fixture.material,
        &artifact_fixture.artifacts,
        &record,
    )
    .expect("release audit record matches governed artifacts");
    let mut stale_material_for_record_builder_preflight = artifact_fixture.material.clone();
    stale_material_for_record_builder_preflight.circuit_id =
        "stale-bfv-full-bootstrap-circuit".to_owned();
    assert_error_matrix_row! { artifact_fixture.diagnostics; 207; (release_record_v1( &artifact_fixture.params, &stale_material_for_record_builder_preflight, &artifact_fixture.artifacts, review_fixture.audit_report_digest, review_fixture.audit_evidence_archive_digest, " sora-zk-audit-wg-2026", review_fixture.reviewer_key_pair.private_key(), )), (release_record_v1( &artifact_fixture.params, &stale_material_for_record_builder_preflight, &artifact_fixture.artifacts, Hash::prehashed([0_u8; Hash::LENGTH]), review_fixture.audit_evidence_archive_digest, "sora-zk-audit-wg-2026", review_fixture.reviewer_key_pair.private_key(), )), (release_record_v1( &artifact_fixture.params, &stale_material_for_record_builder_preflight, &artifact_fixture.artifacts, review_fixture.audit_report_digest, review_fixture.audit_evidence_archive_digest, "sora-zk-audit-wg-2026", signoff_authority.secp256k1_reviewer_key_pair.private_key(), )), (release_record_v1( &artifact_fixture.params, &stale_material_for_record_builder_preflight, &artifact_fixture.artifacts, review_fixture.audit_report_digest, review_fixture.audit_evidence_archive_digest, "sora-zk-audit-wg-2026", &signoff_authority.all_zero_reviewer_private_key, )) };
    SignedRecords {
        record,
        stale_generated_body_record,
        stale_material_for_record_builder_preflight,
    }
}
