package org.hyperledger.iroha.sdk.offline

import java.math.BigInteger
import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import org.hyperledger.iroha.sdk.client.JsonParser

/** Locks Kotlin STARK prover output to committed Rust-generated byte-exact fixtures. */
class OfflineSettlementProofsParityTest {

    @Test
    fun redeemProofsMatchRustFixtures() {
        val fixtures = loadFixtures()
        check(fixtures.isNotEmpty()) { "no fixtures loaded" }

        for (fixture in fixtures) {
            val receipts = fixture.receipts.map { (transferId, localRevision) ->
                dummyReceipt(transferId, localRevision)
            }
            val proof = OfflineSettlementProofs.buildRedeemRequestProof(
                operationId = fixture.operationId,
                accountId = fixture.accountId,
                lineageId = fixture.lineageId,
                assetDefinitionId = fixture.assetDefinitionId,
                amount = fixture.amountRaw,
                offlinePublicKey = fixture.offlinePublicKey,
                authorizationId = fixture.authorizationId,
                preStateHash = fixture.preStateHash,
                receipts = receipts,
            )
            assertEquals(fixture.expectedCommitmentHex, proof.publicInputsHex, "${fixture.name}: commitment hex mismatch")
            assertProofEquals(fixture.name, fixture.expectedProof, proof)
        }
    }

    private data class FixtureReceiptInput(val transferId: String, val localRevision: Long)

    private data class Fixture(
        val name: String,
        val operationId: String,
        val accountId: String,
        val lineageId: String,
        val assetDefinitionId: String,
        val amountRaw: String,
        val offlinePublicKey: String,
        val authorizationId: String,
        val preStateHash: String,
        val receipts: List<FixtureReceiptInput>,
        val expectedCommitmentHex: String,
        val expectedProof: OfflineRedeemRequestProof,
    )

    private fun loadFixtures(): List<Fixture> {
        val stream = requireNotNull(
            OfflineSettlementProofsParityTest::class.java.getResourceAsStream(
                "/offline/redeem_proof_fixtures.json",
            ),
        ) { "missing /offline/redeem_proof_fixtures.json" }
        val text = stream.bufferedReader(Charsets.UTF_8).readText()
        @Suppress("UNCHECKED_CAST")
        val root = JsonParser.parse(text) as Map<String, Any?>
        @Suppress("UNCHECKED_CAST")
        val rawFixtures = root["fixtures"] as List<Map<String, Any?>>
        return rawFixtures.map { entry ->
            @Suppress("UNCHECKED_CAST")
            val inputs = entry["inputs"] as Map<String, Any?>
            @Suppress("UNCHECKED_CAST")
            val rawReceipts = inputs["receipts"] as List<Map<String, Any?>>
            val receipts = rawReceipts.map { r ->
                FixtureReceiptInput(
                    r["transfer_id"] as String,
                    (r["local_revision"] as Number).toLong(),
                )
            }
            @Suppress("UNCHECKED_CAST")
            val expectedProofNode = entry["expected_proof"] as Map<String, Any?>
            val proofJson = reserializeToBytes(expectedProofNode)
            val expectedProof = OfflineJsonParser.parseRedeemRequestProof(proofJson)
            Fixture(
                name = entry["name"] as String,
                operationId = inputs["operation_id"] as String,
                accountId = inputs["account_id"] as String,
                lineageId = inputs["lineage_id"] as String,
                assetDefinitionId = inputs["asset_definition_id"] as String,
                amountRaw = inputs["amount_raw"] as String,
                offlinePublicKey = inputs["offline_public_key"] as String,
                authorizationId = inputs["authorization_id"] as String,
                preStateHash = inputs["pre_state_hash"] as String,
                receipts = receipts,
                expectedCommitmentHex = entry["expected_commitment_hex"] as String,
                expectedProof = expectedProof,
            )
        }
    }

    private fun reserializeToBytes(node: Map<String, Any?>): ByteArray {
        val encoded = org.hyperledger.iroha.sdk.client.JsonEncoder.encode(node)
        return encoded.toByteArray(Charsets.UTF_8)
    }

    private fun dummyReceipt(transferId: String, localRevision: Long): OfflineTransferReceipt {
        return OfflineTransferReceipt(
            version = 1,
            transferId = transferId,
            direction = "incoming",
            lineageId = "lineage-x",
            accountId = "account-x",
            deviceId = "device-x",
            offlinePublicKey = "",
            preBalance = "0",
            postBalance = "0",
            preLockedBalance = "0",
            postLockedBalance = "0",
            preStateHash = "",
            postStateHash = "",
            localRevision = localRevision,
            counterpartyLineageId = "lineage-y",
            counterpartyAccountId = "account-y",
            counterpartyDeviceId = "device-y",
            counterpartyOfflinePublicKey = "",
            amount = "0",
            authorization = null,
            deviceProof = OfflineCashDeviceProof("android", "k", "", "", null),
            sourcePayload = null,
            senderSignatureBase64 = "",
            createdAtMs = 0,
        )
    }

    private fun assertProofEquals(
        name: String,
        expected: OfflineRedeemRequestProof,
        actual: OfflineRedeemRequestProof,
    ) {
        assertEquals(expected.backend, actual.backend, "$name: backend")
        assertEquals(expected.circuitId, actual.circuitId, "$name: circuit_id")
        assertEquals(expected.recursionDepth, actual.recursionDepth, "$name: recursion_depth")
        assertEquals(expected.publicInputsHex, actual.publicInputsHex, "$name: public_inputs_hex")
        assertEnvelopeEquals(name, expected.envelope, actual.envelope)
    }

    private fun assertEnvelopeEquals(
        name: String,
        expected: OfflineStarkVerifyEnvelope,
        actual: OfflineStarkVerifyEnvelope,
    ) {
        assertEquals(expected.transcriptLabel, actual.transcriptLabel, "$name: transcript_label")
        assertParamsEquals(name, expected.params, actual.params)
        assertProofObjectEquals(name, expected.proof, actual.proof)
    }

    private fun assertParamsEquals(
        name: String,
        expected: OfflineStarkFriParams,
        actual: OfflineStarkFriParams,
    ) {
        assertEquals(expected.version, actual.version, "$name: params.version")
        assertEquals(expected.nLog2, actual.nLog2, "$name: params.n_log2")
        assertEquals(expected.blowupLog2, actual.blowupLog2, "$name: params.blowup_log2")
        assertEquals(expected.foldArity, actual.foldArity, "$name: params.fold_arity")
        assertEquals(expected.queries, actual.queries, "$name: params.queries")
        assertEquals(expected.merkleArity, actual.merkleArity, "$name: params.merkle_arity")
        assertEquals(expected.hashFn, actual.hashFn, "$name: params.hash_fn")
        assertEquals(expected.domainTag, actual.domainTag, "$name: params.domain_tag")
    }

    private fun assertProofObjectEquals(
        name: String,
        expected: OfflineStarkProof,
        actual: OfflineStarkProof,
    ) {
        assertEquals(expected.version, actual.version, "$name: proof.version")
        assertCommitmentsEquals(name, expected.commits, actual.commits)
        assertEquals(expected.queries.size, actual.queries.size, "$name: proof.queries.size")
        for (i in expected.queries.indices) {
            val e = expected.queries[i]
            val a = actual.queries[i]
            assertEquals(e.size, a.size, "$name: proof.queries[$i].size")
            for (j in e.indices) {
                assertFoldEquals("$name: proof.queries[$i][$j]", e[j], a[j])
            }
        }
        val eCompValues = expected.compValues
        val aCompValues = actual.compValues
        assertEquals(eCompValues == null, aCompValues == null, "$name: comp_values.null")
        if (eCompValues != null && aCompValues != null) {
            assertEquals(eCompValues.size, aCompValues.size, "$name: comp_values.size")
            for (i in eCompValues.indices) {
                assertCompValueEquals("$name: comp_values[$i]", eCompValues[i], aCompValues[i])
            }
        }
        val eAir = expected.air
        val aAir = actual.air
        assertEquals(eAir == null, aAir == null, "$name: air.null")
        if (eAir != null && aAir != null) {
            assertAirEquals(name, eAir, aAir)
        }
    }

    private fun assertCommitmentsEquals(
        name: String,
        expected: OfflineStarkCommitments,
        actual: OfflineStarkCommitments,
    ) {
        assertEquals(expected.version, actual.version, "$name: commits.version")
        assertEquals(expected.roots.size, actual.roots.size, "$name: commits.roots.size")
        for (i in expected.roots.indices) {
            assertContentEquals(expected.roots[i], actual.roots[i], "$name: commits.roots[$i]")
        }
        val eRoot = expected.compRoot
        val aRoot = actual.compRoot
        if (eRoot == null || aRoot == null) {
            assertEquals(eRoot == null, aRoot == null, "$name: commits.comp_root.null")
        } else {
            assertContentEquals(eRoot, aRoot, "$name: commits.comp_root")
        }
    }

    private fun assertFoldEquals(
        label: String,
        expected: OfflineFoldDecommit,
        actual: OfflineFoldDecommit,
    ) {
        assertEquals(expected.j, actual.j, "$label.j")
        assertBigIntegerEquals("$label.y0", expected.y0, actual.y0)
        assertBigIntegerEquals("$label.y1", expected.y1, actual.y1)
        assertMerklePathEquals("$label.path_y0", expected.pathY0, actual.pathY0)
        assertMerklePathEquals("$label.path_y1", expected.pathY1, actual.pathY1)
        assertBigIntegerEquals("$label.z", expected.z, actual.z)
        assertMerklePathEquals("$label.path_z", expected.pathZ, actual.pathZ)
    }

    private fun assertCompValueEquals(
        label: String,
        expected: OfflineStarkCompositionValue,
        actual: OfflineStarkCompositionValue,
    ) {
        assertBigIntegerEquals("$label.leaf", expected.leaf, actual.leaf)
        assertBigIntegerEquals("$label.constant", expected.constant, actual.constant)
        assertBigIntegerEquals("$label.z_coeff", expected.zCoeff, actual.zCoeff)
        assertEquals(expected.auxTerms.size, actual.auxTerms.size, "$label.aux_terms.size")
        for (i in expected.auxTerms.indices) {
            val e = expected.auxTerms[i]
            val a = actual.auxTerms[i]
            assertEquals(e.wireIndex, a.wireIndex, "$label.aux_terms[$i].wire_index")
            assertBigIntegerEquals("$label.aux_terms[$i].value", e.value, a.value)
            assertBigIntegerEquals("$label.aux_terms[$i].coeff", e.coeff, a.coeff)
        }
        assertMerklePathEquals("$label.path", expected.path, actual.path)
    }

    private fun assertAirEquals(
        name: String,
        expected: OfflineStarkAirProof,
        actual: OfflineStarkAirProof,
    ) {
        assertEquals(expected.version, actual.version, "$name: air.version")
        assertEquals(expected.circuitId, actual.circuitId, "$name: air.circuit_id")
        assertContentEquals(expected.publicDigest, actual.publicDigest, "$name: air.public_digest")
        assertContentEquals(expected.traceRoot, actual.traceRoot, "$name: air.trace_root")
        assertContentEquals(expected.compositionRoot, actual.compositionRoot, "$name: air.composition_root")
        assertEquals(expected.traceWidth, actual.traceWidth, "$name: air.trace_width")
        assertEquals(expected.openings.size, actual.openings.size, "$name: air.openings.size")
        for (i in expected.openings.indices) {
            val e = expected.openings[i]
            val a = actual.openings[i]
            assertEquals(e.index, a.index, "$name: air.openings[$i].index")
            assertEquals(e.row.size, a.row.size, "$name: air.openings[$i].row.size")
            for (j in e.row.indices) {
                assertBigIntegerEquals("$name: air.openings[$i].row[$j]", e.row[j], a.row[j])
            }
            assertEquals(e.nextRow.size, a.nextRow.size, "$name: air.openings[$i].next_row.size")
            for (j in e.nextRow.indices) {
                assertBigIntegerEquals("$name: air.openings[$i].next_row[$j]", e.nextRow[j], a.nextRow[j])
            }
            assertMerklePathEquals("$name: air.openings[$i].row_path", e.rowPath, a.rowPath)
            assertMerklePathEquals("$name: air.openings[$i].next_row_path", e.nextRowPath, a.nextRowPath)
            assertBigIntegerEquals(
                "$name: air.openings[$i].composition_value",
                e.compositionValue,
                a.compositionValue,
            )
            assertMerklePathEquals("$name: air.openings[$i].composition_path", e.compositionPath, a.compositionPath)
        }
    }

    private fun assertMerklePathEquals(
        label: String,
        expected: OfflineMerklePath,
        actual: OfflineMerklePath,
    ) {
        assertContentEquals(expected.dirs, actual.dirs, "$label.dirs")
        assertEquals(expected.siblings.size, actual.siblings.size, "$label.siblings.size")
        for (i in expected.siblings.indices) {
            assertContentEquals(expected.siblings[i], actual.siblings[i], "$label.siblings[$i]")
        }
    }

    private fun assertBigIntegerEquals(label: String, expected: BigInteger, actual: BigInteger) {
        if (expected != actual) {
            error("$label: expected $expected but got $actual")
        }
        assertNotNull(actual, label)
    }
}
