#![allow(dead_code)]
//! Runtime configuration and CLI parsing for the Izanami chaos tool.

use std::{ops::RangeInclusive, sync::OnceLock, time::Duration};

use clap::{Args, Parser, ValueEnum};
use color_eyre::{Result, eyre::eyre};
use humantime::parse_duration;
use iroha_config::{
    base::{
        read::ConfigReader,
        toml::{TomlSource, Writer as TomlWriter},
    },
    parameters::actual::{
        Commit, ConsensusMode, Da, Fusion, LaneRoutingPolicy, LaneRoutingRule, LaneValidatorMode,
        Nexus as ActualNexus, Sumeragi as ActualSumeragi,
    },
};
use iroha_data_model::nexus::{DataSpaceCatalog, DataSpaceId, LaneCatalog, LaneId};
use iroha_primitives::addr::SocketAddr as IrohaSocketAddr;
use toml::{Table, Value};
use tracing_subscriber::{layer::SubscriberExt, util::SubscriberInitExt};

/// Command-line arguments exposed by the `izanami` binary.
#[derive(Debug, Parser, Clone)]
#[command(author, version, about = "Izanami chaosnet orchestrator for Iroha", long_about = None)]
pub struct IzanamiArgs {
    /// Launch interactive TUI to configure a run.
    #[arg(long)]
    pub tui: bool,
    /// Allow Izanami to orchestrate networked peers (required outside tests).
    #[arg(long, default_value_t = false)]
    pub allow_net: bool,
    /// Total number of peers to start in the chaos network.
    #[arg(long, default_value_t = 4)]
    pub peers: usize,
    /// Number of peers that should behave in a faulty (Byzantine) manner.
    #[arg(long, default_value_t = 1)]
    pub faulty: usize,
    /// Wall-clock duration for which the scenario should run.
    #[arg(long, default_value = "120s", value_parser = parse_duration)]
    pub duration: Duration,
    /// Optional total consensus pipeline time (block production + commit), minimum 2ms.
    #[arg(long, value_parser = parse_duration)]
    pub pipeline_time: Option<Duration>,
    /// Target total block height required across all running peers before stopping.
    #[arg(long)]
    pub target_blocks: Option<u64>,
    /// Interval between block-height progress checks when a target is set.
    #[arg(long, default_value = "15s", value_parser = parse_duration)]
    pub progress_interval: Duration,
    /// Maximum time without block progress before failing when a target is set.
    #[arg(long, default_value = "120s", value_parser = parse_duration)]
    pub progress_timeout: Duration,
    /// Optional p95 block-interval threshold enforced when `target_blocks` is set.
    #[arg(long, value_parser = parse_duration)]
    pub latency_p95_threshold: Option<Duration>,
    /// Optional deterministic seed for reproducible chaos runs.
    #[arg(long)]
    pub seed: Option<u64>,
    /// Target average transactions per second generated by Izanami.
    #[arg(long, default_value_t = 15.0)]
    pub tps: f64,
    /// Upper bound on the number of concurrently in-flight transactions submitted by Izanami.
    #[arg(long, default_value_t = 32)]
    pub max_inflight: usize,
    /// Workload profile controlling which recipes are scheduled.
    #[arg(long, value_enum, default_value_t = WorkloadProfile::Stable)]
    pub workload_profile: WorkloadProfile,
    /// Allow contract deployment recipes in stable runs (use with care).
    #[arg(long, default_value_t = false)]
    pub allow_contract_deploy_in_stable: bool,
    /// Tracing filter passed to `tracing-subscriber` (overridden by `RUST_LOG` if set).
    #[arg(long, default_value = "info")]
    pub log_filter: String,
    /// Minimum interval between fault injections against a faulty peer.
    #[arg(long, default_value = "5s", value_parser = parse_duration)]
    pub fault_interval_min: Duration,
    /// Maximum interval between fault injections against a faulty peer.
    #[arg(long, default_value = "20s", value_parser = parse_duration)]
    pub fault_interval_max: Duration,
    /// Fault toggle switches parsed from CLI flags.
    #[command(flatten)]
    pub faults: FaultArgs,
    /// Enable Nexus/Sora multi-lane defaults from `defaults/nexus/config.toml`.
    #[arg(long)]
    pub nexus: bool,
}

/// Workload profiles for recipe selection.
#[derive(Debug, Clone, Copy, ValueEnum, PartialEq, Eq, Default)]
pub enum WorkloadProfile {
    /// Favor deterministic, execution-safe recipes for long runs.
    #[default]
    Stable,
    /// Include intentionally invalid recipes for chaos coverage.
    Chaos,
}

pub const DEFAULT_PROGRESS_INTERVAL: Duration = Duration::from_secs(15);
pub const DEFAULT_PROGRESS_TIMEOUT: Duration = Duration::from_secs(120);
/// Minimum pipeline time accepted by the test-network builder (must stay in sync).
pub const MIN_PIPELINE_TIME: Duration = Duration::from_millis(2);

/// CLI fault toggles controlling which fault injectors run.
#[derive(Debug, Clone, Args)]
#[allow(clippy::struct_excessive_bools)]
pub struct FaultArgs {
    /// Enable transient network latency faults.
    #[arg(long = "fault-enable-network-latency", default_value_t = true)]
    pub network_latency: bool,
    /// Enable network partition faults.
    #[arg(long = "fault-enable-network-partition", default_value_t = true)]
    pub network_partition: bool,
    /// Enable CPU stress faults.
    #[arg(long = "fault-enable-cpu-stress", default_value_t = true)]
    pub cpu_stress: bool,
    /// Enable disk saturation faults.
    #[arg(long = "fault-enable-disk-saturation", default_value_t = true)]
    pub disk_saturation: bool,
}

impl FaultArgs {
    pub fn to_toggles(&self) -> FaultToggles {
        FaultToggles::from_array([
            self.network_latency,
            self.network_partition,
            self.cpu_stress,
            self.disk_saturation,
        ])
    }
}

impl Default for FaultArgs {
    fn default() -> Self {
        Self {
            network_latency: true,
            network_partition: true,
            cpu_stress: true,
            disk_saturation: true,
        }
    }
}

impl From<FaultToggles> for FaultArgs {
    fn from(toggles: FaultToggles) -> Self {
        Self {
            network_latency: toggles.network_latency(),
            network_partition: toggles.network_partition(),
            cpu_stress: toggles.cpu_stress(),
            disk_saturation: toggles.disk_saturation(),
        }
    }
}

/// Bitflags describing which fault injectors are enabled.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct FaultToggles {
    bits: u8,
}

impl FaultToggles {
    const NETWORK_LATENCY: u8 = 1 << 0;
    const NETWORK_PARTITION: u8 = 1 << 1;
    const CPU_STRESS: u8 = 1 << 2;
    const DISK_SATURATION: u8 = 1 << 3;

    pub const fn from_array(flags: [bool; 4]) -> Self {
        let mut bits = 0u8;
        if flags[0] {
            bits |= Self::NETWORK_LATENCY;
        }
        if flags[1] {
            bits |= Self::NETWORK_PARTITION;
        }
        if flags[2] {
            bits |= Self::CPU_STRESS;
        }
        if flags[3] {
            bits |= Self::DISK_SATURATION;
        }
        Self { bits }
    }

    pub const fn from_bits(bits: u8) -> Self {
        Self { bits: bits & 0x0F }
    }

    pub const fn bits(self) -> u8 {
        self.bits
    }

    pub const fn network_latency(self) -> bool {
        self.bits & Self::NETWORK_LATENCY != 0
    }

    pub const fn network_partition(self) -> bool {
        self.bits & Self::NETWORK_PARTITION != 0
    }

    pub const fn cpu_stress(self) -> bool {
        self.bits & Self::CPU_STRESS != 0
    }

    pub const fn disk_saturation(self) -> bool {
        self.bits & Self::DISK_SATURATION != 0
    }
}

/// Derived runtime configuration constructed from [`IzanamiArgs`].
#[derive(Debug, Clone)]
pub struct ChaosConfig {
    /// Whether Izanami may open network sockets; must be true to run scenarios.
    pub allow_net: bool,
    pub peer_count: usize,
    pub faulty_peers: usize,
    pub duration: Duration,
    pub pipeline_time: Option<Duration>,
    pub target_blocks: Option<u64>,
    pub progress_interval: Duration,
    pub progress_timeout: Duration,
    pub latency_p95_threshold: Option<Duration>,
    pub seed: Option<u64>,
    pub tps: f64,
    pub max_inflight: usize,
    pub workload_profile: WorkloadProfile,
    pub allow_contract_deploy_in_stable: bool,
    pub fault_interval: RangeInclusive<Duration>,
    pub log_filter: String,
    pub faults: FaultToggles,
    pub nexus: Option<NexusProfile>,
}

impl TryFrom<IzanamiArgs> for ChaosConfig {
    type Error = color_eyre::Report;

    fn try_from(args: IzanamiArgs) -> Result<Self> {
        if !args.allow_net {
            return Err(eyre!(
                "network orchestration disabled: pass --allow-net or set allow_net=true to run Izanami"
            ));
        }
        if args.peers == 0 {
            return Err(eyre!("peer count must be greater than zero"));
        }
        if args.faulty > args.peers {
            return Err(eyre!(
                "faulty peer count ({}) cannot exceed total peer count ({})",
                args.faulty,
                args.peers
            ));
        }
        if args.duration.is_zero() {
            return Err(eyre!("duration must be greater than zero"));
        }
        if args
            .pipeline_time
            .is_some_and(|duration| duration < MIN_PIPELINE_TIME)
        {
            return Err(eyre!(
                "pipeline_time must be at least {} ms",
                MIN_PIPELINE_TIME.as_millis()
            ));
        }
        if args.target_blocks == Some(0) {
            return Err(eyre!("target_blocks must be greater than zero"));
        }
        if args.progress_interval.is_zero() {
            return Err(eyre!("progress_interval must be greater than zero"));
        }
        if args.progress_timeout.is_zero() {
            return Err(eyre!("progress_timeout must be greater than zero"));
        }
        if args.progress_interval > args.progress_timeout {
            return Err(eyre!(
                "progress_interval ({:?}) must not exceed progress_timeout ({:?})",
                args.progress_interval,
                args.progress_timeout
            ));
        }
        if args
            .latency_p95_threshold
            .is_some_and(|duration| duration.is_zero())
        {
            return Err(eyre!("latency_p95_threshold must be greater than zero"));
        }
        if args.latency_p95_threshold.is_some() && args.target_blocks.is_none() {
            return Err(eyre!(
                "latency_p95_threshold requires target_blocks to be set"
            ));
        }
        if args.tps <= 0.0 {
            return Err(eyre!("tps must be positive"));
        }
        if !args.tps.is_finite() {
            return Err(eyre!("tps must be finite"));
        }
        let interval_secs = 1.0 / args.tps;
        let interval = Duration::try_from_secs_f64(interval_secs)
            .map_err(|_| eyre!("tps too low for timer range"))?;
        if interval.is_zero() {
            return Err(eyre!("tps too high for timer resolution"));
        }
        if args.max_inflight == 0 {
            return Err(eyre!("max_inflight must be greater than zero"));
        }
        if args.fault_interval_min > args.fault_interval_max {
            return Err(eyre!(
                "fault interval min ({:?}) cannot be greater than max ({:?})",
                args.fault_interval_min,
                args.fault_interval_max,
            ));
        }

        let toggles = args.faults.to_toggles();
        let IzanamiArgs {
            tui: _,
            peers,
            faulty,
            duration,
            pipeline_time,
            target_blocks,
            progress_interval,
            progress_timeout,
            latency_p95_threshold,
            seed,
            tps,
            max_inflight,
            workload_profile,
            allow_contract_deploy_in_stable,
            log_filter,
            fault_interval_min,
            fault_interval_max,
            faults: _faults,
            nexus,
            allow_net,
        } = args;
        let nexus = if nexus {
            Some(NexusProfile::sora_defaults()?)
        } else {
            None
        };

        Ok(Self {
            allow_net,
            peer_count: peers,
            faulty_peers: faulty,
            duration,
            pipeline_time,
            target_blocks,
            progress_interval,
            progress_timeout,
            latency_p95_threshold,
            seed,
            tps,
            max_inflight,
            workload_profile,
            allow_contract_deploy_in_stable,
            fault_interval: fault_interval_min..=fault_interval_max,
            log_filter,
            faults: toggles,
            nexus,
        })
    }
}

/// Initialise tracing using the resolved filter string.
pub fn init_tracing_with_filter(default_filter: &str) {
    static SUBSCRIBER: OnceLock<()> = OnceLock::new();
    SUBSCRIBER.get_or_init(|| {
        let filter = std::env::var("RUST_LOG").unwrap_or_else(|_| default_filter.to_string());
        let _ = tracing_subscriber::registry()
            .with(tracing_subscriber::EnvFilter::new(filter))
            .with(tracing_subscriber::fmt::layer())
            .try_init();
    });
}

impl IzanamiArgs {
    pub fn from_config(cfg: &ChaosConfig) -> Self {
        let (min, max) = cfg.fault_interval.clone().into_inner();
        Self {
            tui: false,
            peers: cfg.peer_count,
            faulty: cfg.faulty_peers,
            duration: cfg.duration,
            pipeline_time: cfg.pipeline_time,
            target_blocks: cfg.target_blocks,
            progress_interval: cfg.progress_interval,
            progress_timeout: cfg.progress_timeout,
            latency_p95_threshold: cfg.latency_p95_threshold,
            seed: cfg.seed,
            tps: cfg.tps,
            max_inflight: cfg.max_inflight,
            workload_profile: cfg.workload_profile,
            allow_contract_deploy_in_stable: cfg.allow_contract_deploy_in_stable,
            log_filter: cfg.log_filter.clone(),
            fault_interval_min: min,
            fault_interval_max: max,
            faults: FaultArgs::from(cfg.faults),
            nexus: cfg.nexus.is_some(),
            allow_net: cfg.allow_net,
        }
    }

    pub fn defaults() -> Self {
        Self::parse_from(["izanami"])
    }
}

/// Nexus/Sora profile derived from `defaults/nexus/config.toml`.
#[derive(Debug, Clone)]
pub struct NexusProfile {
    pub lane_catalog: LaneCatalog,
    pub dataspace_catalog: DataSpaceCatalog,
    pub bootstrap_public_lanes: Vec<LaneId>,
    pub routing_policy: LaneRoutingPolicy,
    pub fusion: Fusion,
    pub commit: Commit,
    pub da: Da,
    pub da_enabled: bool,
    pub config_layer: Table,
}

fn canonical_addr_literal(addr: &str) -> Result<String> {
    let parsed: std::net::SocketAddr = addr
        .parse()
        .map_err(|err| eyre!("failed to parse embedded socket address `{addr}`: {err}"))?;
    Ok(IrohaSocketAddr::from(parsed).to_literal())
}

impl NexusProfile {
    /// Load the embedded Sora profile and expose both typed values and a TOML layer.
    pub fn sora_defaults() -> Result<Self> {
        const DEFAULT_CONFIG: &str = include_str!("../../../defaults/nexus/config.toml");
        let config_str = DEFAULT_CONFIG.replace("\\0", "");
        let mut raw_table: Table = toml::from_str(&config_str)
            .map_err(|err| eyre!("failed to parse embedded nexus config: {err}"))?;
        normalize_lane_metadata(&mut raw_table);
        let consensus_mode = Value::String("npos".to_string());
        if let Some(sumeragi) = raw_table.get_mut("sumeragi").and_then(Value::as_table_mut) {
            sumeragi.insert("consensus_mode".to_string(), consensus_mode);
        } else {
            let mut sumeragi = Table::new();
            sumeragi.insert("consensus_mode".to_string(), consensus_mode);
            raw_table.insert("sumeragi".to_string(), Value::Table(sumeragi));
        }
        let default_p2p_addr = canonical_addr_literal("127.0.0.1:1337")?;
        let default_torii_addr = canonical_addr_literal("127.0.0.1:8080")?;
        // Provide safe defaults for required network addresses and drop unsupported nested sections
        // so that deserialization succeeds without binding to real sockets.
        if let Some(network) = raw_table.get_mut("network").and_then(Value::as_table_mut) {
            network.insert(
                "address".to_string(),
                Value::String(default_p2p_addr.clone()),
            );
            network.insert(
                "public_address".to_string(),
                Value::String(default_p2p_addr.clone()),
            );
        } else {
            let mut network = Table::new();
            network.insert(
                "address".to_string(),
                Value::String(default_p2p_addr.clone()),
            );
            network.insert(
                "public_address".to_string(),
                Value::String(default_p2p_addr.clone()),
            );
            raw_table.insert("network".to_string(), Value::Table(network));
        }
        if let Some(torii) = raw_table.get_mut("torii").and_then(Value::as_table_mut) {
            torii.insert(
                "address".to_string(),
                Value::String(default_torii_addr.clone()),
            );
            torii.remove("sorafs");
        } else {
            let mut torii = Table::new();
            torii.insert(
                "address".to_string(),
                Value::String(default_torii_addr.clone()),
            );
            raw_table.insert("torii".to_string(), Value::Table(torii));
        }
        let actual = ConfigReader::new()
            .with_toml_source(TomlSource::inline(raw_table.clone()))
            .read_and_complete::<iroha_config::parameters::user::Root>()
            .map_err(|err| eyre!("failed to load embedded nexus config: {err:?}"))?
            .parse()
            .map_err(|err| eyre!("failed to parse embedded nexus config: {err:?}"))?;

        let nexus = actual.nexus.clone();
        let sumeragi = actual.sumeragi;
        let bootstrap_public_lanes = derive_bootstrap_public_lanes(&nexus);
        let config_layer = build_nexus_layer(&nexus, &sumeragi);

        Ok(Self {
            lane_catalog: nexus.lane_catalog,
            dataspace_catalog: nexus.dataspace_catalog,
            bootstrap_public_lanes,
            routing_policy: nexus.routing_policy,
            fusion: nexus.fusion,
            commit: nexus.commit,
            da: nexus.da,
            da_enabled: sumeragi.da.enabled,
            config_layer,
        })
    }
}

fn derive_bootstrap_public_lanes(nexus: &ActualNexus) -> Vec<LaneId> {
    let lanes: Vec<LaneId> = if nexus.lane_catalog.lanes().is_empty() {
        vec![LaneId::SINGLE]
    } else {
        nexus
            .lane_catalog
            .lanes()
            .iter()
            .map(|lane| lane.id)
            .collect()
    };

    lanes
        .into_iter()
        .filter(|lane| {
            matches!(
                nexus.staking.validator_mode(*lane, &nexus.lane_catalog),
                LaneValidatorMode::StakeElected
            )
        })
        .collect()
}

fn normalize_lane_metadata(raw: &mut Table) {
    if let Some(nexus) = raw.get_mut("nexus").and_then(Value::as_table_mut) {
        if let Some(Value::Array(lanes)) = nexus.get_mut("lane_catalog") {
            for lane in lanes {
                if let Some(table) = lane.as_table_mut() {
                    table
                        .entry("metadata".to_string())
                        .or_insert(Value::Table(Table::new()));
                }
            }
        }
    }
}

fn build_nexus_layer(nexus: &ActualNexus, sumeragi: &ActualSumeragi) -> Table {
    let mut layer = Table::new();
    TomlWriter::new(&mut layer).write(["nexus", "enabled"], true);
    TomlWriter::new(&mut layer).write(
        ["nexus", "lane_count"],
        i64::from(nexus.lane_catalog.lane_count().get()),
    );

    let dataspace_aliases = dataspace_alias_map(&nexus.dataspace_catalog);

    let lane_entries: Vec<Value> = nexus
        .lane_catalog
        .lanes()
        .iter()
        .map(|lane| {
            let mut entry = Table::new();
            entry.insert(
                "index".to_string(),
                Value::Integer(i64::from(lane.id.as_u32())),
            );
            entry.insert("alias".to_string(), Value::String(lane.alias.clone()));
            if let Some(description) = &lane.description {
                entry.insert(
                    "description".to_string(),
                    Value::String(description.clone()),
                );
            }
            entry.insert(
                "visibility".to_string(),
                Value::String(lane.visibility.as_str().to_string()),
            );
            entry.insert(
                "storage".to_string(),
                Value::String(lane.storage.as_str().to_string()),
            );
            entry.insert(
                "proof_scheme".to_string(),
                Value::String(lane.proof_scheme.as_str().to_string()),
            );
            if let Some(lane_type) = &lane.lane_type {
                entry.insert("lane_type".to_string(), Value::String(lane_type.clone()));
            }
            if let Some(governance) = &lane.governance {
                entry.insert("governance".to_string(), Value::String(governance.clone()));
            }
            if let Some(settlement) = &lane.settlement {
                entry.insert("settlement".to_string(), Value::String(settlement.clone()));
            }
            if let Some(dataspace) = dataspace_aliases.get(&lane.dataspace_id) {
                entry.insert("dataspace".to_string(), Value::String(dataspace.clone()));
            }
            let mut metadata = Table::new();
            for (key, value) in &lane.metadata {
                metadata.insert(key.clone(), Value::String(value.clone()));
            }
            entry.insert("metadata".to_string(), Value::Table(metadata));
            Value::Table(entry)
        })
        .collect();
    TomlWriter::new(&mut layer).write(["nexus", "lane_catalog"], Value::Array(lane_entries));

    let dataspace_entries: Vec<Value> = nexus
        .dataspace_catalog
        .entries()
        .iter()
        .map(|entry| {
            let mut value = Table::new();
            value.insert("alias".to_string(), Value::String(entry.alias.clone()));
            let id = i64::try_from(entry.id.as_u64()).unwrap_or_default();
            value.insert("id".to_string(), Value::Integer(id));
            if let Some(description) = &entry.description {
                value.insert(
                    "description".to_string(),
                    Value::String(description.clone()),
                );
            }
            Value::Table(value)
        })
        .collect();
    TomlWriter::new(&mut layer).write(
        ["nexus", "dataspace_catalog"],
        Value::Array(dataspace_entries),
    );

    TomlWriter::new(&mut layer).write(
        ["nexus", "routing_policy", "default_lane"],
        i64::from(nexus.routing_policy.default_lane.as_u32()),
    );
    if let Some(default_ds) = dataspace_aliases.get(&nexus.routing_policy.default_dataspace) {
        TomlWriter::new(&mut layer).write(
            ["nexus", "routing_policy", "default_dataspace"],
            default_ds.clone(),
        );
    }
    let rule_values: Vec<Value> = nexus
        .routing_policy
        .rules
        .iter()
        .map(|rule| lane_rule_to_value(rule, &dataspace_aliases))
        .collect();
    TomlWriter::new(&mut layer).write(
        ["nexus", "routing_policy", "rules"],
        Value::Array(rule_values),
    );

    TomlWriter::new(&mut layer).write(
        ["nexus", "fusion", "floor_teu"],
        i64::from(nexus.fusion.floor_teu),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "fusion", "exit_teu"],
        i64::from(nexus.fusion.exit_teu),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "fusion", "observation_slots"],
        i64::from(nexus.fusion.observation_slots.get()),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "fusion", "max_window_slots"],
        i64::from(nexus.fusion.max_window_slots.get()),
    );

    TomlWriter::new(&mut layer).write(
        ["nexus", "commit", "window_slots"],
        i64::from(nexus.commit.window_slots.get()),
    );

    TomlWriter::new(&mut layer).write(
        ["nexus", "da", "q_in_slot_total"],
        i64::from(nexus.da.q_in_slot_total.get()),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "da", "q_in_slot_per_ds_min"],
        i64::from(nexus.da.q_in_slot_per_ds_min.get()),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "da", "sample_size_base"],
        i64::from(nexus.da.sample_size_base.get()),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "da", "sample_size_max"],
        i64::from(nexus.da.sample_size_max.get()),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "da", "threshold_base"],
        i64::from(nexus.da.threshold_base.get()),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "da", "per_attester_shards"],
        i64::from(nexus.da.per_attester_shards.get()),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "da", "audit", "sample_size"],
        i64::from(nexus.da.audit.sample_size.get()),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "da", "audit", "window_count"],
        i64::from(nexus.da.audit.window_count.get()),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "da", "audit", "interval_ms"],
        i64::try_from(nexus.da.audit.interval.as_millis()).unwrap_or_default(),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "da", "recovery", "request_timeout_ms"],
        i64::try_from(nexus.da.recovery.request_timeout.as_millis()).unwrap_or_default(),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "da", "rotation", "max_hits_per_window"],
        i64::from(nexus.da.rotation.max_hits_per_window.get()),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "da", "rotation", "window_slots"],
        i64::from(nexus.da.rotation.window_slots.get()),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "da", "rotation", "seed_tag"],
        nexus.da.rotation.seed_tag.clone(),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "da", "rotation", "latency_decay"],
        nexus.da.rotation.latency_decay,
    );

    let consensus_mode = match sumeragi.consensus_mode {
        ConsensusMode::Permissioned => "permissioned",
        ConsensusMode::Npos => "npos",
    };
    TomlWriter::new(&mut layer)
        .write(["sumeragi", "consensus_mode"], consensus_mode)
        .write(["sumeragi", "da", "enabled"], sumeragi.da.enabled);

    layer
}

fn dataspace_alias_map(
    catalog: &DataSpaceCatalog,
) -> std::collections::BTreeMap<DataSpaceId, String> {
    catalog
        .entries()
        .iter()
        .map(|entry| (entry.id, entry.alias.clone()))
        .collect()
}

fn lane_rule_to_value(
    rule: &LaneRoutingRule,
    dataspace_aliases: &std::collections::BTreeMap<DataSpaceId, String>,
) -> Value {
    let mut table = Table::new();
    table.insert(
        "lane".to_string(),
        Value::Integer(i64::from(rule.lane.as_u32())),
    );
    if let Some(dataspace) = rule
        .dataspace
        .and_then(|id| dataspace_aliases.get(&id).cloned())
    {
        table.insert("dataspace".to_string(), Value::String(dataspace));
    }
    let mut matcher = Table::new();
    if let Some(account) = &rule.matcher.account {
        matcher.insert("account".to_string(), Value::String(account.to_string()));
    }
    if let Some(instruction) = &rule.matcher.instruction {
        matcher.insert(
            "instruction".to_string(),
            Value::String(instruction.clone()),
        );
    }
    if let Some(description) = &rule.matcher.description {
        matcher.insert(
            "description".to_string(),
            Value::String(description.clone()),
        );
    }
    table.insert("matcher".to_string(), Value::Table(matcher));
    Value::Table(table)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn chaos_config_rejects_invalid_faulty_counts() {
        let args = IzanamiArgs {
            tui: false,
            allow_net: true,
            peers: 2,
            faulty: 3,
            duration: Duration::from_secs(1),
            pipeline_time: None,
            target_blocks: None,
            progress_interval: DEFAULT_PROGRESS_INTERVAL,
            progress_timeout: DEFAULT_PROGRESS_TIMEOUT,
            latency_p95_threshold: None,
            seed: None,
            tps: 1.0,
            max_inflight: 1,
            workload_profile: WorkloadProfile::Stable,
            allow_contract_deploy_in_stable: false,
            log_filter: "info".to_string(),
            fault_interval_min: Duration::from_secs(1),
            fault_interval_max: Duration::from_secs(2),
            faults: FaultArgs {
                network_latency: true,
                network_partition: true,
                cpu_stress: true,
                disk_saturation: true,
            },
            nexus: false,
        };
        assert!(ChaosConfig::try_from(args).is_err());
    }

    #[test]
    fn init_tracing_is_idempotent() {
        let args = IzanamiArgs {
            tui: false,
            allow_net: true,
            peers: 1,
            faulty: 0,
            duration: Duration::from_secs(1),
            pipeline_time: None,
            target_blocks: None,
            progress_interval: DEFAULT_PROGRESS_INTERVAL,
            progress_timeout: DEFAULT_PROGRESS_TIMEOUT,
            latency_p95_threshold: None,
            seed: Some(42),
            tps: 1.0,
            max_inflight: 1,
            workload_profile: WorkloadProfile::Stable,
            allow_contract_deploy_in_stable: false,
            log_filter: "warn".to_string(),
            fault_interval_min: Duration::from_secs(1),
            fault_interval_max: Duration::from_secs(1),
            faults: FaultArgs::default(),
            nexus: false,
        };
        init_tracing_with_filter(&args.log_filter);
        init_tracing_with_filter(&args.log_filter);
    }

    #[test]
    fn chaos_config_requires_allow_net_opt_in() {
        let args = IzanamiArgs {
            tui: false,
            allow_net: false,
            peers: 1,
            faulty: 0,
            duration: Duration::from_secs(1),
            pipeline_time: None,
            target_blocks: None,
            progress_interval: DEFAULT_PROGRESS_INTERVAL,
            progress_timeout: DEFAULT_PROGRESS_TIMEOUT,
            latency_p95_threshold: None,
            seed: None,
            tps: 1.0,
            max_inflight: 1,
            workload_profile: WorkloadProfile::Stable,
            allow_contract_deploy_in_stable: false,
            log_filter: "info".to_string(),
            fault_interval_min: Duration::from_secs(1),
            fault_interval_max: Duration::from_secs(1),
            faults: FaultArgs::default(),
            nexus: false,
        };
        let Err(err) = ChaosConfig::try_from(args) else {
            panic!("allow_net=false should prevent ChaosConfig construction");
        };
        assert!(
            err.to_string().contains("allow_net"),
            "error should mention allow_net opt-in: {err}"
        );
    }

    #[test]
    fn chaos_config_rejects_zero_target_blocks() {
        let args = IzanamiArgs {
            tui: false,
            allow_net: true,
            peers: 1,
            faulty: 0,
            duration: Duration::from_secs(1),
            pipeline_time: None,
            target_blocks: Some(0),
            progress_interval: DEFAULT_PROGRESS_INTERVAL,
            progress_timeout: DEFAULT_PROGRESS_TIMEOUT,
            latency_p95_threshold: None,
            seed: None,
            tps: 1.0,
            max_inflight: 1,
            workload_profile: WorkloadProfile::Stable,
            allow_contract_deploy_in_stable: false,
            log_filter: "info".to_string(),
            fault_interval_min: Duration::from_secs(1),
            fault_interval_max: Duration::from_secs(1),
            faults: FaultArgs::default(),
            nexus: false,
        };
        assert!(ChaosConfig::try_from(args).is_err());
    }

    #[test]
    fn chaos_config_rejects_pipeline_time_under_minimum() {
        let args = IzanamiArgs {
            tui: false,
            allow_net: true,
            peers: 1,
            faulty: 0,
            duration: Duration::from_secs(1),
            pipeline_time: Some(
                MIN_PIPELINE_TIME
                    .checked_sub(Duration::from_millis(1))
                    .unwrap_or(Duration::ZERO),
            ),
            target_blocks: None,
            progress_interval: DEFAULT_PROGRESS_INTERVAL,
            progress_timeout: DEFAULT_PROGRESS_TIMEOUT,
            latency_p95_threshold: None,
            seed: None,
            tps: 1.0,
            max_inflight: 1,
            workload_profile: WorkloadProfile::Stable,
            allow_contract_deploy_in_stable: false,
            log_filter: "info".to_string(),
            fault_interval_min: Duration::from_secs(1),
            fault_interval_max: Duration::from_secs(1),
            faults: FaultArgs::default(),
            nexus: false,
        };
        let Err(err) = ChaosConfig::try_from(args) else {
            panic!("pipeline_time below minimum should fail");
        };
        assert!(
            err.to_string().contains("pipeline_time must be at least"),
            "error should mention pipeline_time minimum: {err}"
        );
    }

    #[test]
    fn nexus_profile_sets_npos_consensus_mode() {
        let profile = NexusProfile::sora_defaults().expect("nexus profile should load");
        let mode = profile
            .config_layer
            .get("sumeragi")
            .and_then(Value::as_table)
            .and_then(|sumeragi| sumeragi.get("consensus_mode"))
            .and_then(Value::as_str);
        assert_eq!(
            mode,
            Some("npos"),
            "nexus profile must force consensus_mode=npos"
        );
    }

    #[test]
    fn nexus_profile_derives_bootstrap_public_lanes() {
        let profile = NexusProfile::sora_defaults().expect("nexus profile should load");
        assert_eq!(
            profile.bootstrap_public_lanes,
            vec![LaneId::new(0), LaneId::new(1), LaneId::new(2)],
            "embedded nexus profile should expose every stake-elected bootstrap lane"
        );
    }

    #[test]
    fn chaos_config_rejects_progress_interval_over_timeout() {
        let args = IzanamiArgs {
            tui: false,
            allow_net: true,
            peers: 1,
            faulty: 0,
            duration: Duration::from_secs(1),
            pipeline_time: None,
            target_blocks: Some(5),
            progress_interval: Duration::from_secs(10),
            progress_timeout: Duration::from_secs(5),
            latency_p95_threshold: None,
            seed: None,
            tps: 1.0,
            max_inflight: 1,
            workload_profile: WorkloadProfile::Stable,
            allow_contract_deploy_in_stable: false,
            log_filter: "info".to_string(),
            fault_interval_min: Duration::from_secs(1),
            fault_interval_max: Duration::from_secs(1),
            faults: FaultArgs::default(),
            nexus: false,
        };
        let Err(err) = ChaosConfig::try_from(args) else {
            panic!("progress_interval > progress_timeout should fail");
        };
        assert!(
            err.to_string().contains("progress_interval"),
            "error should mention progress_interval: {err}"
        );
    }

    #[test]
    fn chaos_config_rejects_non_finite_tps() {
        let args = IzanamiArgs {
            tui: false,
            allow_net: true,
            peers: 1,
            faulty: 0,
            duration: Duration::from_secs(1),
            pipeline_time: None,
            target_blocks: None,
            progress_interval: DEFAULT_PROGRESS_INTERVAL,
            progress_timeout: DEFAULT_PROGRESS_TIMEOUT,
            latency_p95_threshold: None,
            seed: None,
            tps: f64::NAN,
            max_inflight: 1,
            workload_profile: WorkloadProfile::Stable,
            allow_contract_deploy_in_stable: false,
            log_filter: "info".to_string(),
            fault_interval_min: Duration::from_secs(1),
            fault_interval_max: Duration::from_secs(1),
            faults: FaultArgs::default(),
            nexus: false,
        };
        let Err(err) = ChaosConfig::try_from(args) else {
            panic!("non-finite tps should fail");
        };
        assert!(
            err.to_string().contains("tps must be finite"),
            "error should mention finite tps: {err}"
        );
    }

    #[test]
    fn chaos_config_rejects_tps_too_high_for_timer() {
        let args = IzanamiArgs {
            tui: false,
            allow_net: true,
            peers: 1,
            faulty: 0,
            duration: Duration::from_secs(1),
            pipeline_time: None,
            target_blocks: None,
            progress_interval: DEFAULT_PROGRESS_INTERVAL,
            progress_timeout: DEFAULT_PROGRESS_TIMEOUT,
            latency_p95_threshold: None,
            seed: None,
            tps: f64::MAX,
            max_inflight: 1,
            workload_profile: WorkloadProfile::Stable,
            allow_contract_deploy_in_stable: false,
            log_filter: "info".to_string(),
            fault_interval_min: Duration::from_secs(1),
            fault_interval_max: Duration::from_secs(1),
            faults: FaultArgs::default(),
            nexus: false,
        };
        let Err(err) = ChaosConfig::try_from(args) else {
            panic!("tps too high for timer resolution should fail");
        };
        assert!(
            err.to_string().contains("tps too high"),
            "error should mention timer resolution: {err}"
        );
    }

    #[test]
    fn chaos_config_rejects_tps_too_low_for_timer() {
        let args = IzanamiArgs {
            tui: false,
            allow_net: true,
            peers: 1,
            faulty: 0,
            duration: Duration::from_secs(1),
            pipeline_time: None,
            target_blocks: None,
            progress_interval: DEFAULT_PROGRESS_INTERVAL,
            progress_timeout: DEFAULT_PROGRESS_TIMEOUT,
            latency_p95_threshold: None,
            seed: None,
            tps: f64::MIN_POSITIVE,
            max_inflight: 1,
            workload_profile: WorkloadProfile::Stable,
            allow_contract_deploy_in_stable: false,
            log_filter: "info".to_string(),
            fault_interval_min: Duration::from_secs(1),
            fault_interval_max: Duration::from_secs(1),
            faults: FaultArgs::default(),
            nexus: false,
        };
        let Err(err) = ChaosConfig::try_from(args) else {
            panic!("tps too low for timer range should fail");
        };
        assert!(
            err.to_string().contains("tps too low"),
            "error should mention timer range: {err}"
        );
    }

    #[test]
    fn chaos_config_rejects_latency_threshold_without_target_blocks() {
        let args = IzanamiArgs {
            tui: false,
            allow_net: true,
            peers: 1,
            faulty: 0,
            duration: Duration::from_secs(1),
            pipeline_time: None,
            target_blocks: None,
            progress_interval: DEFAULT_PROGRESS_INTERVAL,
            progress_timeout: DEFAULT_PROGRESS_TIMEOUT,
            latency_p95_threshold: Some(Duration::from_millis(900)),
            seed: None,
            tps: 1.0,
            max_inflight: 1,
            workload_profile: WorkloadProfile::Stable,
            allow_contract_deploy_in_stable: false,
            log_filter: "info".to_string(),
            fault_interval_min: Duration::from_secs(1),
            fault_interval_max: Duration::from_secs(1),
            faults: FaultArgs::default(),
            nexus: false,
        };
        let Err(err) = ChaosConfig::try_from(args) else {
            panic!("latency threshold without target_blocks should fail");
        };
        assert!(
            err.to_string().contains("requires target_blocks"),
            "error should mention target_blocks requirement: {err}"
        );
    }

    #[test]
    fn chaos_config_rejects_zero_latency_threshold() {
        let args = IzanamiArgs {
            tui: false,
            allow_net: true,
            peers: 1,
            faulty: 0,
            duration: Duration::from_secs(1),
            pipeline_time: None,
            target_blocks: Some(5),
            progress_interval: DEFAULT_PROGRESS_INTERVAL,
            progress_timeout: DEFAULT_PROGRESS_TIMEOUT,
            latency_p95_threshold: Some(Duration::ZERO),
            seed: None,
            tps: 1.0,
            max_inflight: 1,
            workload_profile: WorkloadProfile::Stable,
            allow_contract_deploy_in_stable: false,
            log_filter: "info".to_string(),
            fault_interval_min: Duration::from_secs(1),
            fault_interval_max: Duration::from_secs(1),
            faults: FaultArgs::default(),
            nexus: false,
        };
        let Err(err) = ChaosConfig::try_from(args) else {
            panic!("zero latency threshold should fail");
        };
        assert!(
            err.to_string().contains("latency_p95_threshold"),
            "error should mention latency_p95_threshold: {err}"
        );
    }
}
