#![allow(dead_code)]
//! Runtime configuration and CLI parsing for the Izanami chaos tool.
use clap::{Args, Parser, ValueEnum};
use color_eyre::{Result, eyre::eyre};
use humantime::parse_duration;
use iroha_config::{
    base::{
        read::ConfigReader,
        toml::{TomlSource, Writer as TomlWriter},
    },
    parameters::actual::{
        Commit, Da, Fusion, LaneRoutingPolicy, LaneRoutingRule, LaneValidatorMode,
        Nexus as ActualNexus, Sumeragi as ActualSumeragi,
    },
};
use iroha_crypto::{Algorithm, ExposedPrivateKey, Hash, KeyPair};
use iroha_data_model::{
    asset::{AssetDefinitionAlias, AssetDefinitionId},
    block::consensus_v2::{
        MAX_VALIDATORS_PER_HEIGHT, MIN_VALIDATORS_PER_HEIGHT, is_valid_committee_size,
    },
    nexus::{DataSpaceCatalog, DataSpaceId, LaneCatalog, LaneId},
};
use iroha_primitives::addr::SocketAddr as IrohaSocketAddr;
use std::{
    collections::BTreeMap, ops::RangeInclusive, path::PathBuf, sync::OnceLock, time::Duration,
};
use toml::{Table, Value};
use tracing_subscriber::{layer::SubscriberExt, util::SubscriberInitExt};
/// Command-line arguments exposed by the `izanami` binary.
#[derive(Debug, Parser, Clone)]
#[command(author, version, about = "Izanami chaosnet orchestrator for Iroha", long_about = None)]
pub struct IzanamiArgs {
    /// Launch interactive TUI to configure a run.
    #[arg(long)]
    pub tui: bool,
    /// Allow Izanami to orchestrate networked peers (required outside tests).
    #[arg(long, default_value_t = false)]
    pub allow_net: bool,
    /// Exact bounded `3f + 1` validator committee to start in the chaos network.
    #[arg(long, default_value_t = 4)]
    pub peers: usize,
    /// Number of Byzantine peers, bounded by the committee's fault tolerance `f`.
    #[arg(long, default_value_t = 1)]
    pub faulty: usize,
    /// Wall-clock duration for which the scenario should run.
    #[arg(long, default_value = "120s", value_parser = parse_duration)]
    pub duration: Duration,
    /// Optional total consensus pipeline time (block production + commit), minimum 2ms.
    #[arg(long, value_parser = parse_duration)]
    pub pipeline_time: Option<Duration>,
    /// Target total block height required across all running peers before stopping.
    #[arg(long)]
    pub target_blocks: Option<u64>,
    /// Interval between block-height progress checks when a target is set.
    #[arg(long, default_value = "15s", value_parser = parse_duration)]
    pub progress_interval: Duration,
    /// Maximum time without block progress before failing when a target is set.
    #[arg(long, default_value = "120s", value_parser = parse_duration)]
    pub progress_timeout: Duration,
    /// Bounded grace period for draining spawned submission tasks after workload shutdown.
    #[arg(long, default_value = "15s", value_parser = parse_duration)]
    pub shutdown_drain_timeout: Duration,
    /// Optional p95 block-interval threshold enforced while monitoring block progress.
    #[arg(long, value_parser = parse_duration)]
    pub latency_p95_threshold: Option<Duration>,
    /// Optional run-relative offset before fault workers start injecting faults.
    #[arg(long, value_parser = parse_duration)]
    pub fault_window_start: Option<Duration>,
    /// Optional run-relative offset after which fault workers stop injecting faults.
    #[arg(long, value_parser = parse_duration)]
    pub fault_window_end: Option<Duration>,
    /// Optional deterministic seed for reproducible chaos runs.
    #[arg(long)]
    pub seed: Option<u64>,
    /// Target average transactions per second generated by Izanami.
    #[arg(long, default_value_t = 15.0)]
    pub tps: f64,
    /// Upper bound on the number of concurrently in-flight transactions submitted by Izanami.
    #[arg(long, default_value_t = 32)]
    pub max_inflight: usize,
    /// Number of independent transaction submitter loops sharing the global inflight budget.
    #[arg(long, default_value_t = 1)]
    pub submitters: usize,
    /// Number of transactions to sign, encode, and cache before the timed load window starts.
    #[arg(long, default_value_t = 0)]
    pub prebuild_tx_buffer: usize,
    /// Number of workers used to fill the prebuilt transaction buffer; 0 chooses a host-aware default.
    #[arg(long, default_value_t = 0)]
    pub prebuild_tx_workers: usize,
    /// Maximum transactions per Sumeragi block injected into the test network.
    #[arg(
        long,
        default_value_t = DEFAULT_SUMERAGI_BLOCK_MAX_TRANSACTIONS,
        value_parser = clap::value_parser!(u64).range(1..)
    )]
    pub sumeragi_block_max_transactions: u64,
    /// Proposal queue scan multiplier used to fill each candidate Sumeragi block.
    #[arg(
        long,
        default_value_t = DEFAULT_SUMERAGI_PROPOSAL_QUEUE_SCAN_MULTIPLIER,
        value_parser = clap::value_parser!(u64).range(1..)
    )]
    pub sumeragi_proposal_queue_scan_multiplier: u64,
    /// Workload profile controlling which recipes are scheduled.
    #[arg(long, value_enum, default_value_t = WorkloadProfile::Stable)]
    pub workload_profile: WorkloadProfile,
    /// Allow contract deployment recipes in stable runs (use with care).
    #[arg(long, default_value_t = false)]
    pub allow_contract_deploy_in_stable: bool,
    /// Tracing filter passed to `tracing-subscriber` (overridden by `RUST_LOG` if set).
    #[arg(long, default_value = "info")]
    pub log_filter: String,
    /// Minimum interval between fault injections against a faulty peer.
    #[arg(long, default_value = "5s", value_parser = parse_duration)]
    pub fault_interval_min: Duration,
    /// Maximum interval between fault injections against a faulty peer.
    #[arg(long, default_value = "20s", value_parser = parse_duration)]
    pub fault_interval_max: Duration,
    /// Fault toggle switches parsed from CLI flags.
    #[command(flatten)]
    pub faults: FaultArgs,
    /// Load the Sora multi-lane profile from `defaults/nexus/config.toml`.
    #[arg(long)]
    pub nexus: bool,
    /// Optional directory where Izanami copies test-network diagnostics before cleanup.
    #[arg(long)]
    pub diagnostic_dir: Option<PathBuf>,
}
/// Workload profiles for recipe selection.
#[derive(Debug, Clone, Copy, ValueEnum, PartialEq, Eq, Default)]
pub enum WorkloadProfile {
    /// Favor deterministic, execution-safe recipes for long runs.
    #[default]
    Stable,
    /// Include intentionally invalid recipes for chaos coverage.
    Chaos,
}
pub const DEFAULT_PROGRESS_INTERVAL: Duration = Duration::from_secs(15);
pub const DEFAULT_PROGRESS_TIMEOUT: Duration = Duration::from_secs(120);
pub const DEFAULT_SHUTDOWN_DRAIN_TIMEOUT: Duration = Duration::from_secs(15);
pub const DEFAULT_SUMERAGI_BLOCK_MAX_TRANSACTIONS: u64 = 1_024;
pub const DEFAULT_SUMERAGI_PROPOSAL_QUEUE_SCAN_MULTIPLIER: u64 = 1;
/// Minimum pipeline time accepted by the test-network builder (must stay in sync).
pub const MIN_PIPELINE_TIME: Duration = Duration::from_millis(2);
/// CLI fault toggles controlling which fault injectors run.
#[derive(Debug, Clone, Args)]
#[allow(clippy::struct_excessive_bools)]
pub struct FaultArgs {
    /// Enable crash-and-restart faults.
    #[arg(
        long = "fault-enable-crash-restart",
        default_value_t = true,
        action = clap::ArgAction::Set,
        num_args = 0..=1,
        require_equals = true,
        default_missing_value = "true",
    )]
    pub crash_restart: bool,
    /// Enable wipe-storage-and-restart faults.
    #[arg(
        long = "fault-enable-wipe-storage",
        default_value_t = true,
        action = clap::ArgAction::Set,
        num_args = 0..=1,
        require_equals = true,
        default_missing_value = "true",
    )]
    pub wipe_storage: bool,
    /// Enable invalid-transaction spam faults.
    #[arg(
        long = "fault-enable-spam-invalid-transactions",
        default_value_t = true,
        action = clap::ArgAction::Set,
        num_args = 0..=1,
        require_equals = true,
        default_missing_value = "true",
    )]
    pub spam_invalid_transactions: bool,
    /// Enable transient network latency faults.
    #[arg(
        long = "fault-enable-network-latency",
        default_value_t = true,
        action = clap::ArgAction::Set,
        num_args = 0..=1,
        require_equals = true,
        default_missing_value = "true",
    )]
    pub network_latency: bool,
    /// Enable network partition faults.
    #[arg(
        long = "fault-enable-network-partition",
        default_value_t = true,
        action = clap::ArgAction::Set,
        num_args = 0..=1,
        require_equals = true,
        default_missing_value = "true",
    )]
    pub network_partition: bool,
    /// Enable CPU stress faults.
    #[arg(
        long = "fault-enable-cpu-stress",
        default_value_t = true,
        action = clap::ArgAction::Set,
        num_args = 0..=1,
        require_equals = true,
        default_missing_value = "true",
    )]
    pub cpu_stress: bool,
    /// Enable disk saturation faults.
    #[arg(
        long = "fault-enable-disk-saturation",
        default_value_t = true,
        action = clap::ArgAction::Set,
        num_args = 0..=1,
        require_equals = true,
        default_missing_value = "true",
    )]
    pub disk_saturation: bool,
}
impl FaultArgs {
    pub fn to_toggles(&self) -> FaultToggles {
        FaultToggles::from_enabled_flags([
            self.crash_restart,
            self.wipe_storage,
            self.spam_invalid_transactions,
            self.network_latency,
            self.network_partition,
            self.cpu_stress,
            self.disk_saturation,
        ])
    }
}
impl Default for FaultArgs {
    fn default() -> Self {
        Self {
            crash_restart: true,
            wipe_storage: true,
            spam_invalid_transactions: true,
            network_latency: true,
            network_partition: true,
            cpu_stress: true,
            disk_saturation: true,
        }
    }
}
impl From<FaultToggles> for FaultArgs {
    fn from(toggles: FaultToggles) -> Self {
        Self {
            crash_restart: toggles.crash_restart(),
            wipe_storage: toggles.wipe_storage(),
            spam_invalid_transactions: toggles.spam_invalid_transactions(),
            network_latency: toggles.network_latency(),
            network_partition: toggles.network_partition(),
            cpu_stress: toggles.cpu_stress(),
            disk_saturation: toggles.disk_saturation(),
        }
    }
}
/// Bitflags describing which fault injectors are enabled.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct FaultToggles {
    bits: u8,
}
impl FaultToggles {
    const CRASH_RESTART: u8 = 1 << 0;
    const WIPE_STORAGE: u8 = 1 << 1;
    const SPAM_INVALID_TRANSACTIONS: u8 = 1 << 2;
    const NETWORK_LATENCY: u8 = 1 << 3;
    const NETWORK_PARTITION: u8 = 1 << 4;
    const CPU_STRESS: u8 = 1 << 5;
    const DISK_SATURATION: u8 = 1 << 6;
    const ALL_BITS: u8 = Self::CRASH_RESTART
        | Self::WIPE_STORAGE
        | Self::SPAM_INVALID_TRANSACTIONS
        | Self::NETWORK_LATENCY
        | Self::NETWORK_PARTITION
        | Self::CPU_STRESS
        | Self::DISK_SATURATION;
    /// Build the exact V1 fault set in declaration order.
    pub const fn from_enabled_flags(flags: [bool; 7]) -> Self {
        let mut bits = 0u8;
        if flags[0] {
            bits |= Self::CRASH_RESTART;
        }
        if flags[1] {
            bits |= Self::WIPE_STORAGE;
        }
        if flags[2] {
            bits |= Self::SPAM_INVALID_TRANSACTIONS;
        }
        if flags[3] {
            bits |= Self::NETWORK_LATENCY;
        }
        if flags[4] {
            bits |= Self::NETWORK_PARTITION;
        }
        if flags[5] {
            bits |= Self::CPU_STRESS;
        }
        if flags[6] {
            bits |= Self::DISK_SATURATION;
        }
        Self { bits }
    }
    /// Admit only the exact first-release fault bitset.
    pub const fn try_from_bits(bits: u8) -> Option<Self> {
        if bits & !Self::ALL_BITS == 0 {
            Some(Self { bits })
        } else {
            None
        }
    }
    pub const fn bits(self) -> u8 {
        self.bits
    }
    pub const fn any_enabled(self) -> bool {
        self.bits != 0
    }
    pub const fn crash_restart(self) -> bool {
        self.bits & Self::CRASH_RESTART != 0
    }
    pub const fn wipe_storage(self) -> bool {
        self.bits & Self::WIPE_STORAGE != 0
    }
    pub const fn spam_invalid_transactions(self) -> bool {
        self.bits & Self::SPAM_INVALID_TRANSACTIONS != 0
    }
    pub const fn network_latency(self) -> bool {
        self.bits & Self::NETWORK_LATENCY != 0
    }
    pub const fn network_partition(self) -> bool {
        self.bits & Self::NETWORK_PARTITION != 0
    }
    pub const fn cpu_stress(self) -> bool {
        self.bits & Self::CPU_STRESS != 0
    }
    pub const fn disk_saturation(self) -> bool {
        self.bits & Self::DISK_SATURATION != 0
    }
}
/// Derived runtime configuration constructed from [`IzanamiArgs`].
#[derive(Debug, Clone)]
pub struct ChaosConfig {
    /// Whether Izanami may open network sockets; must be true to run scenarios.
    pub allow_net: bool,
    pub peer_count: usize,
    pub faulty_peers: usize,
    pub duration: Duration,
    pub pipeline_time: Option<Duration>,
    pub target_blocks: Option<u64>,
    pub progress_interval: Duration,
    pub progress_timeout: Duration,
    pub shutdown_drain_timeout: Duration,
    pub latency_p95_threshold: Option<Duration>,
    pub fault_window_start: Option<Duration>,
    pub fault_window_end: Option<Duration>,
    pub seed: Option<u64>,
    pub tps: f64,
    pub max_inflight: usize,
    pub submitters: usize,
    pub prebuild_tx_buffer: usize,
    pub prebuild_tx_workers: usize,
    pub sumeragi_block_max_transactions: u64,
    pub sumeragi_proposal_queue_scan_multiplier: u64,
    pub workload_profile: WorkloadProfile,
    pub allow_contract_deploy_in_stable: bool,
    pub fault_interval: RangeInclusive<Duration>,
    pub log_filter: String,
    pub faults: FaultToggles,
    pub nexus: Option<NexusProfile>,
    pub diagnostic_dir: Option<PathBuf>,
}
impl TryFrom<IzanamiArgs> for ChaosConfig {
    type Error = color_eyre::Report;
    fn try_from(args: IzanamiArgs) -> Result<Self> {
        if !args.allow_net {
            return Err(eyre!(
                "network orchestration disabled: pass --allow-net or set allow_net=true to run Izanami"
            ));
        }
        if !is_valid_committee_size(args.peers) {
            return Err(eyre!(
                "peer count ({}) must be an exact revision-4 3f + 1 committee in {}..={}",
                args.peers,
                MIN_VALIDATORS_PER_HEIGHT,
                MAX_VALIDATORS_PER_HEIGHT
            ));
        }
        let max_faulty_peers = (args.peers - 1) / 3;
        if args.faulty > max_faulty_peers {
            return Err(eyre!(
                "faulty peer count ({}) exceeds revision-4 fault tolerance f={} for {} peers",
                args.faulty,
                max_faulty_peers,
                args.peers
            ));
        }
        if args.duration.is_zero() {
            return Err(eyre!("duration must be greater than zero"));
        }
        if args
            .pipeline_time
            .is_some_and(|duration| duration < MIN_PIPELINE_TIME)
        {
            return Err(eyre!(
                "pipeline_time must be at least {} ms",
                MIN_PIPELINE_TIME.as_millis()
            ));
        }
        if args.target_blocks == Some(0) {
            return Err(eyre!("target_blocks must be greater than zero"));
        }
        if args.progress_interval.is_zero() {
            return Err(eyre!("progress_interval must be greater than zero"));
        }
        if args.progress_timeout.is_zero() {
            return Err(eyre!("progress_timeout must be greater than zero"));
        }
        if args.shutdown_drain_timeout.is_zero() {
            return Err(eyre!("shutdown_drain_timeout must be greater than zero"));
        }
        if args.progress_interval > args.progress_timeout {
            return Err(eyre!(
                "progress_interval ({:?}) must not exceed progress_timeout ({:?})",
                args.progress_interval,
                args.progress_timeout
            ));
        }
        if args
            .latency_p95_threshold
            .is_some_and(|duration| duration.is_zero())
        {
            return Err(eyre!("latency_p95_threshold must be greater than zero"));
        }
        if args
            .fault_window_start
            .is_some_and(|offset| offset >= args.duration)
        {
            return Err(eyre!(
                "fault_window_start ({:?}) must be before duration ({:?})",
                args.fault_window_start.expect("checked above"),
                args.duration
            ));
        }
        if args
            .fault_window_end
            .is_some_and(|offset| offset > args.duration)
        {
            return Err(eyre!(
                "fault_window_end ({:?}) must not exceed duration ({:?})",
                args.fault_window_end.expect("checked above"),
                args.duration
            ));
        }
        if let (Some(start), Some(end)) = (args.fault_window_start, args.fault_window_end)
            && end <= start
        {
            return Err(eyre!(
                "fault_window_end ({end:?}) must be after fault_window_start ({start:?})"
            ));
        }
        if args.tps <= 0.0 {
            return Err(eyre!("tps must be positive"));
        }
        if !args.tps.is_finite() {
            return Err(eyre!("tps must be finite"));
        }
        let interval_secs = 1.0 / args.tps;
        let interval = Duration::try_from_secs_f64(interval_secs)
            .map_err(|_| eyre!("tps too low for timer range"))?;
        if interval.is_zero() {
            return Err(eyre!("tps too high for timer resolution"));
        }
        if args.max_inflight == 0 {
            return Err(eyre!("max_inflight must be greater than zero"));
        }
        if args.submitters == 0 {
            return Err(eyre!("submitters must be greater than zero"));
        }
        if i64::try_from(args.sumeragi_block_max_transactions).is_err() {
            return Err(eyre!(
                "sumeragi_block_max_transactions ({}) exceeds config-layer limits",
                args.sumeragi_block_max_transactions
            ));
        }
        if i64::try_from(args.sumeragi_proposal_queue_scan_multiplier).is_err() {
            return Err(eyre!(
                "sumeragi_proposal_queue_scan_multiplier ({}) exceeds config-layer limits",
                args.sumeragi_proposal_queue_scan_multiplier
            ));
        }
        if args.fault_interval_min > args.fault_interval_max {
            return Err(eyre!(
                "fault interval min ({:?}) cannot be greater than max ({:?})",
                args.fault_interval_min,
                args.fault_interval_max,
            ));
        }
        let toggles = args.faults.to_toggles();
        if args.faulty > 0 && !toggles.any_enabled() {
            return Err(eyre!(
                "at least one fault scenario must be enabled when faulty peers are configured"
            ));
        }
        let IzanamiArgs {
            tui: _,
            peers,
            faulty,
            duration,
            pipeline_time,
            target_blocks,
            progress_interval,
            progress_timeout,
            shutdown_drain_timeout,
            latency_p95_threshold,
            fault_window_start,
            fault_window_end,
            seed,
            tps,
            max_inflight,
            submitters,
            prebuild_tx_buffer,
            prebuild_tx_workers,
            sumeragi_block_max_transactions,
            sumeragi_proposal_queue_scan_multiplier,
            workload_profile,
            allow_contract_deploy_in_stable,
            log_filter,
            fault_interval_min,
            fault_interval_max,
            faults: _faults,
            nexus,
            diagnostic_dir,
            allow_net,
        } = args;
        let nexus = if nexus {
            Some(NexusProfile::sora_defaults()?)
        } else {
            None
        };
        Ok(Self {
            allow_net,
            peer_count: peers,
            faulty_peers: faulty,
            duration,
            pipeline_time,
            target_blocks,
            progress_interval,
            progress_timeout,
            shutdown_drain_timeout,
            latency_p95_threshold,
            fault_window_start,
            fault_window_end,
            seed,
            tps,
            max_inflight,
            submitters,
            prebuild_tx_buffer,
            prebuild_tx_workers,
            sumeragi_block_max_transactions,
            sumeragi_proposal_queue_scan_multiplier,
            workload_profile,
            allow_contract_deploy_in_stable,
            fault_interval: fault_interval_min..=fault_interval_max,
            log_filter,
            faults: toggles,
            nexus,
            diagnostic_dir,
        })
    }
}
/// Initialise tracing using the resolved filter string.
pub fn init_tracing_with_filter(default_filter: &str) {
    static SUBSCRIBER: OnceLock<()> = OnceLock::new();
    SUBSCRIBER.get_or_init(|| {
        let filter = std::env::var("RUST_LOG").unwrap_or_else(|_| default_filter.to_string());
        let _ = tracing_subscriber::registry()
            .with(tracing_subscriber::EnvFilter::new(filter))
            .with(tracing_subscriber::fmt::layer())
            .try_init();
    });
}
impl IzanamiArgs {
    pub fn from_config(cfg: &ChaosConfig) -> Self {
        let (min, max) = cfg.fault_interval.clone().into_inner();
        Self {
            tui: false,
            peers: cfg.peer_count,
            faulty: cfg.faulty_peers,
            duration: cfg.duration,
            pipeline_time: cfg.pipeline_time,
            target_blocks: cfg.target_blocks,
            progress_interval: cfg.progress_interval,
            progress_timeout: cfg.progress_timeout,
            shutdown_drain_timeout: cfg.shutdown_drain_timeout,
            latency_p95_threshold: cfg.latency_p95_threshold,
            fault_window_start: cfg.fault_window_start,
            fault_window_end: cfg.fault_window_end,
            seed: cfg.seed,
            tps: cfg.tps,
            max_inflight: cfg.max_inflight,
            submitters: cfg.submitters,
            prebuild_tx_buffer: cfg.prebuild_tx_buffer,
            prebuild_tx_workers: cfg.prebuild_tx_workers,
            sumeragi_block_max_transactions: cfg.sumeragi_block_max_transactions,
            sumeragi_proposal_queue_scan_multiplier: cfg.sumeragi_proposal_queue_scan_multiplier,
            workload_profile: cfg.workload_profile,
            allow_contract_deploy_in_stable: cfg.allow_contract_deploy_in_stable,
            log_filter: cfg.log_filter.clone(),
            fault_interval_min: min,
            fault_interval_max: max,
            faults: FaultArgs::from(cfg.faults),
            nexus: cfg.nexus.is_some(),
            allow_net: cfg.allow_net,
            diagnostic_dir: cfg.diagnostic_dir.clone(),
        }
    }
    pub fn defaults() -> Self {
        Self::parse_from(["izanami"])
    }
}
/// Nexus/Sora profile derived from `defaults/nexus/config.toml`.
#[derive(Debug, Clone)]
pub struct NexusProfile {
    pub lane_catalog: LaneCatalog,
    pub dataspace_catalog: DataSpaceCatalog,
    pub bootstrap_public_lanes: Vec<LaneId>,
    pub stake_asset_id: AssetDefinitionId,
    pub fee_asset_id: AssetDefinitionId,
    pub routing_policy: LaneRoutingPolicy,
    pub fusion: Fusion,
    pub commit: Commit,
    pub da: Da,
    pub config_layer: Table,
}
fn canonical_addr_literal(addr: &str) -> Result<String> {
    let parsed: std::net::SocketAddr = addr
        .parse()
        .map_err(|err| eyre!("failed to parse embedded socket address `{addr}`: {err}"))?;
    Ok(IrohaSocketAddr::from(parsed).to_literal())
}
fn resolve_embedded_asset_selector(
    field_path: &str,
    selector: &str,
    canonical_default: &str,
) -> Result<AssetDefinitionId> {
    if let Ok(asset_id) = selector.parse() {
        return Ok(asset_id);
    }
    selector.parse::<AssetDefinitionAlias>().map_err(|err| {
        eyre!(
            "failed to parse embedded {field_path} `{selector}` as a canonical asset definition id or alias: {err}"
        )
    })?;
    canonical_default.parse().map_err(|err| {
        eyre!(
            "failed to resolve embedded {field_path} alias `{selector}` to canonical asset definition id `{canonical_default}`: {err}"
        )
    })
}
impl NexusProfile {
    /// Load the embedded Sora profile and expose both typed values and a TOML layer.
    #[expect(
        clippy::too_many_lines,
        reason = "profile projection verifies every operator-owned file source before substituting non-runtime identities"
    )]
    pub fn sora_defaults() -> Result<Self> {
        const DEFAULT_CONFIG: &str = include_str!("../../../defaults/nexus/config.toml");
        let config_str = DEFAULT_CONFIG.replace("\\0", "");
        let mut raw_table: Table = toml::from_str(&config_str)
            .map_err(|err| eyre!("failed to parse embedded nexus config: {err}"))?;
        normalize_lane_metadata(&mut raw_table);
        // The embedded profile predates the first-release reducer and still carries a
        // node-local DA toggle. DA and mode now come exclusively from signed genesis,
        // so discard the whole legacy Sumeragi table and let the strict v2 defaults
        // populate the node-local timeout, limits, key policy, and NPoS policy.
        raw_table.remove("sumeragi");
        // The checked-in profile deliberately keeps every private identity file-backed. Verify
        // those operator-owned sources exactly, then substitute deterministic in-memory keys only
        // for this typed Nexus/Sumeragi projection; none are copied into `config_layer`.
        const VALIDATOR_PRIVATE_KEY_FILE: &str = "/run/secrets/iroha/nexus-validator-private-key";
        const VALIDATOR_PROJECTION_PRIVATE_KEY: &str =
            "8926201CA347641228C3B79AA43839DEDC85FA51C0E8B9B6A00F6B0D6B0423E902973F";
        const SORANET_TRANSPORT_PRIVATE_KEY_FILE: &str =
            "/run/secrets/iroha/nexus-soranet-transport-private-key";
        const STREAMING_PRIVATE_KEY_FILE: &str =
            "/run/secrets/iroha/nexus-streaming-identity-private-key";
        if raw_table.contains_key("private_key") {
            return Err(eyre!(
                "embedded Nexus signing profile must source its validator private key from the operator-owned file"
            ));
        }
        let validator_private_key_file = raw_table
            .remove("private_key_file")
            .ok_or_else(|| eyre!("embedded Nexus signing profile lacks private_key_file"))?;
        if validator_private_key_file.as_str() != Some(VALIDATOR_PRIVATE_KEY_FILE) {
            return Err(eyre!(
                "embedded Nexus signing profile must retain private_key_file = `{VALIDATOR_PRIVATE_KEY_FILE}`"
            ));
        }
        raw_table.insert(
            "private_key".to_owned(),
            Value::String(VALIDATOR_PROJECTION_PRIVATE_KEY.to_owned()),
        );
        if raw_table.contains_key("soranet_transport_private_key") {
            return Err(eyre!(
                "embedded Nexus signing profile must source its SoraNet transport private key from the operator-owned file"
            ));
        }
        let soranet_transport_private_key_file = raw_table
            .remove("soranet_transport_private_key_file")
            .ok_or_else(|| {
                eyre!("embedded Nexus signing profile lacks soranet_transport_private_key_file")
            })?;
        if soranet_transport_private_key_file.as_str() != Some(SORANET_TRANSPORT_PRIVATE_KEY_FILE) {
            return Err(eyre!(
                "embedded Nexus signing profile must retain soranet_transport_private_key_file = `{SORANET_TRANSPORT_PRIVATE_KEY_FILE}`"
            ));
        }
        let soranet_transport_key_pair = KeyPair::try_from_seed(
            b"Izanami Nexus-profile SoraNet transport projection only".to_vec(),
            Algorithm::Ed25519,
        )
        .map_err(|error| eyre!("failed to derive projection-only SoraNet identity: {error}"))?;
        raw_table.insert(
            "soranet_transport_public_key".to_owned(),
            Value::String(soranet_transport_key_pair.public_key().to_string()),
        );
        raw_table.insert(
            "soranet_transport_private_key".to_owned(),
            Value::String(
                ExposedPrivateKey(soranet_transport_key_pair.private_key().clone()).to_string(),
            ),
        );
        let streaming = raw_table
            .get_mut("streaming")
            .and_then(Value::as_table_mut)
            .ok_or_else(|| eyre!("embedded Nexus signing profile lacks the streaming table"))?;
        if streaming.contains_key("identity_private_key") {
            return Err(eyre!(
                "embedded Nexus signing profile must source its streaming private key from the operator-owned file"
            ));
        }
        let streaming_private_key_file =
            streaming
                .remove("identity_private_key_file")
                .ok_or_else(|| {
                    eyre!(
                        "embedded Nexus signing profile lacks streaming.identity_private_key_file"
                    )
                })?;
        if streaming_private_key_file.as_str() != Some(STREAMING_PRIVATE_KEY_FILE) {
            return Err(eyre!(
                "embedded Nexus signing profile must retain streaming.identity_private_key_file = `{STREAMING_PRIVATE_KEY_FILE}`"
            ));
        }
        let streaming_key_pair = KeyPair::try_from_seed(
            b"Izanami Nexus-profile streaming projection only".to_vec(),
            Algorithm::Ed25519,
        )
        .map_err(|error| eyre!("failed to derive projection-only streaming identity: {error}"))?;
        streaming.insert(
            "identity_public_key".to_owned(),
            Value::String(streaming_key_pair.public_key().to_string()),
        );
        streaming.insert(
            "identity_private_key".to_owned(),
            Value::String(ExposedPrivateKey(streaming_key_pair.private_key().clone()).to_string()),
        );
        let default_p2p_addr = canonical_addr_literal("127.0.0.1:1337")?;
        let default_torii_addr = canonical_addr_literal("127.0.0.1:8080")?;
        // Provide safe defaults for required network addresses and drop unsupported nested sections
        // so that deserialization succeeds without binding to real sockets.
        if let Some(network) = raw_table.get_mut("network").and_then(Value::as_table_mut) {
            network.insert(
                "address".to_string(),
                Value::String(default_p2p_addr.clone()),
            );
            network.insert(
                "public_address".to_string(),
                Value::String(default_p2p_addr.clone()),
            );
        } else {
            let mut network = Table::new();
            network.insert(
                "address".to_string(),
                Value::String(default_p2p_addr.clone()),
            );
            network.insert(
                "public_address".to_string(),
                Value::String(default_p2p_addr.clone()),
            );
            raw_table.insert("network".to_string(), Value::Table(network));
        }
        if let Some(torii) = raw_table.get_mut("torii").and_then(Value::as_table_mut) {
            torii.insert(
                "address".to_string(),
                Value::String(default_torii_addr.clone()),
            );
            torii.remove("sorafs");
        } else {
            let mut torii = Table::new();
            torii.insert(
                "address".to_string(),
                Value::String(default_torii_addr.clone()),
            );
            raw_table.insert("torii".to_string(), Value::Table(torii));
        }
        const EXPECTED_HASH_FILE: &str = "/run/iroha/genesis.expected_hash";
        let genesis = raw_table
            .get_mut("genesis")
            .and_then(Value::as_table_mut)
            .ok_or_else(|| eyre!("embedded Nexus signing profile lacks the genesis table"))?;
        if genesis.contains_key("expected_hash") {
            return Err(eyre!(
                "embedded Nexus signing profile must source its genesis hash from the operator-owned file"
            ));
        }
        let expected_hash_file = genesis.remove("expected_hash_file").ok_or_else(|| {
            eyre!("embedded Nexus signing profile lacks genesis.expected_hash_file")
        })?;
        if expected_hash_file.as_str() != Some(EXPECTED_HASH_FILE) {
            return Err(eyre!(
                "embedded Nexus signing profile must retain genesis.expected_hash_file = `{EXPECTED_HASH_FILE}`"
            ));
        }
        // Izanami parses the complete profile only to project Nexus and Sumeragi fields below;
        // genesis is never copied into `config_layer`. Keep the checked-in profile intentionally
        // not self-contained and use a deterministic in-memory value solely to satisfy
        // complete-config normalization.
        genesis.insert(
            "expected_hash".to_owned(),
            Value::String(norito::literal::format(
                "hash",
                &Hash::new(b"Izanami Nexus-profile policy projection only")
                    .to_string()
                    .to_ascii_uppercase(),
            )),
        );
        let reader = ConfigReader::new().with_toml_source(TomlSource::inline(raw_table.clone()));
        let actual = reader
            .read_and_complete::<iroha_config::parameters::user::Root>()
            .map_err(|err| eyre!("failed to load embedded nexus config: {err:?}"))?
            .parse()
            .map_err(|err| eyre!("failed to parse embedded nexus config: {err:?}"))?;
        let nexus = actual.nexus.clone();
        let sumeragi = actual.sumeragi;
        let bootstrap_public_lanes = derive_bootstrap_public_lanes(&nexus);
        let stake_asset_id = resolve_embedded_asset_selector(
            "nexus.staking.stake_asset_id",
            &nexus.staking.stake_asset_id,
            &iroha_config::parameters::defaults::nexus::staking::stake_asset_id(),
        )?;
        let fee_asset_id = resolve_embedded_asset_selector(
            "nexus.fees.fee_asset_id",
            &nexus.fees.fee_asset_id,
            &iroha_config::parameters::defaults::nexus::fees::fee_asset_id(),
        )?;
        let config_layer = build_nexus_layer(&nexus, &sumeragi, &stake_asset_id, &fee_asset_id);
        Ok(Self {
            lane_catalog: nexus.lane_catalog,
            dataspace_catalog: nexus.dataspace_catalog,
            bootstrap_public_lanes,
            stake_asset_id,
            fee_asset_id,
            routing_policy: nexus.routing_policy,
            fusion: nexus.fusion,
            commit: nexus.commit,
            da: nexus.da,
            config_layer,
        })
    }
}
fn derive_bootstrap_public_lanes(nexus: &ActualNexus) -> Vec<LaneId> {
    if nexus.lane_catalog.lanes().is_empty() {
        return matches!(
            nexus
                .staking
                .validator_mode(LaneId::SINGLE, &nexus.lane_catalog),
            LaneValidatorMode::StakeElected
        )
        .then_some(LaneId::SINGLE)
        .into_iter()
        .collect();
    }
    let mut owner_by_dataspace = BTreeMap::new();
    for lane in nexus.lane_catalog.lanes().iter().filter(|lane| {
        matches!(
            nexus.staking.validator_mode(lane.id, &nexus.lane_catalog),
            LaneValidatorMode::StakeElected
        )
    }) {
        owner_by_dataspace
            .entry(lane.dataspace_id)
            .and_modify(|owner: &mut LaneId| *owner = (*owner).min(lane.id))
            .or_insert(lane.id);
    }
    let mut owners = owner_by_dataspace.into_values().collect::<Vec<_>>();
    owners.sort_unstable();
    owners
}
fn normalize_lane_metadata(raw: &mut Table) {
    if let Some(nexus) = raw.get_mut("nexus").and_then(Value::as_table_mut) {
        if let Some(Value::Array(lanes)) = nexus.get_mut("lane_catalog") {
            for lane in lanes {
                if let Some(table) = lane.as_table_mut() {
                    table
                        .entry("metadata".to_string())
                        .or_insert(Value::Table(Table::new()));
                }
            }
        }
    }
}
fn embedded_dataspace_manifest_hash(id: DataSpaceId) -> String {
    use std::fmt::Write as _;
    let mut bytes = [0_u8; 32];
    bytes[..8].copy_from_slice(&id.as_u64().to_le_bytes());
    let mut encoded = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        write!(&mut encoded, "{byte:02x}").expect("writing to String should not fail");
    }
    encoded
}
fn build_nexus_layer(
    nexus: &ActualNexus,
    sumeragi: &ActualSumeragi,
    stake_asset_id: &AssetDefinitionId,
    fee_asset_id: &AssetDefinitionId,
) -> Table {
    let mut layer = Table::new();
    TomlWriter::new(&mut layer).write(
        ["nexus", "lane_count"],
        i64::from(nexus.lane_catalog.lane_count().get()),
    );
    let dataspace_aliases = dataspace_alias_map(&nexus.dataspace_catalog);
    let lane_entries: Vec<Value> = nexus
        .lane_catalog
        .lanes()
        .iter()
        .map(|lane| {
            let mut entry = Table::new();
            entry.insert(
                "index".to_string(),
                Value::Integer(i64::from(lane.id.as_u32())),
            );
            entry.insert("alias".to_string(), Value::String(lane.alias.clone()));
            if let Some(description) = &lane.description {
                entry.insert(
                    "description".to_string(),
                    Value::String(description.clone()),
                );
            }
            entry.insert(
                "visibility".to_string(),
                Value::String(lane.visibility.as_str().to_string()),
            );
            entry.insert(
                "storage".to_string(),
                Value::String(lane.storage.as_str().to_string()),
            );
            entry.insert(
                "proof_scheme".to_string(),
                Value::String(lane.proof_scheme.as_str().to_string()),
            );
            if let Some(lane_type) = &lane.lane_type {
                entry.insert("lane_type".to_string(), Value::String(lane_type.clone()));
            }
            if let Some(governance) = &lane.governance {
                entry.insert("governance".to_string(), Value::String(governance.clone()));
            }
            if let Some(settlement) = &lane.settlement {
                entry.insert("settlement".to_string(), Value::String(settlement.clone()));
            }
            if let Some(dataspace) = dataspace_aliases.get(&lane.dataspace_id) {
                entry.insert("dataspace".to_string(), Value::String(dataspace.clone()));
            }
            let mut metadata = Table::new();
            for (key, value) in &lane.metadata {
                metadata.insert(key.clone(), Value::String(value.clone()));
            }
            entry.insert("metadata".to_string(), Value::Table(metadata));
            Value::Table(entry)
        })
        .collect();
    TomlWriter::new(&mut layer).write(["nexus", "lane_catalog"], Value::Array(lane_entries));
    let dataspace_entries: Vec<Value> = nexus
        .dataspace_catalog
        .entries()
        .iter()
        .map(|entry| {
            let mut value = Table::new();
            value.insert("alias".to_string(), Value::String(entry.alias.clone()));
            let id = i64::try_from(entry.id.as_u64()).unwrap_or_default();
            value.insert("id".to_string(), Value::Integer(id));
            if entry.id != DataSpaceId::UNIVERSAL {
                value.insert(
                    "manifest_hash".to_string(),
                    Value::String(embedded_dataspace_manifest_hash(entry.id)),
                );
            }
            if let Some(description) = &entry.description {
                value.insert(
                    "description".to_string(),
                    Value::String(description.clone()),
                );
            }
            Value::Table(value)
        })
        .collect();
    TomlWriter::new(&mut layer).write(
        ["nexus", "dataspace_catalog"],
        Value::Array(dataspace_entries),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "routing_policy", "default_lane"],
        i64::from(nexus.routing_policy.default_lane.as_u32()),
    );
    if let Some(default_ds) = dataspace_aliases.get(&nexus.routing_policy.default_dataspace) {
        TomlWriter::new(&mut layer).write(
            ["nexus", "routing_policy", "default_dataspace"],
            default_ds.clone(),
        );
    }
    let rule_values: Vec<Value> = nexus
        .routing_policy
        .rules
        .iter()
        .map(|rule| lane_rule_to_value(rule, &dataspace_aliases))
        .collect();
    TomlWriter::new(&mut layer).write(
        ["nexus", "routing_policy", "rules"],
        Value::Array(rule_values),
    );
    TomlWriter::new(&mut layer).write(["nexus", "fees", "fee_asset_id"], fee_asset_id.to_string());
    TomlWriter::new(&mut layer).write(
        ["nexus", "staking", "stake_asset_id"],
        stake_asset_id.to_string(),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "fusion", "floor_teu"],
        i64::from(nexus.fusion.floor_teu),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "fusion", "exit_teu"],
        i64::from(nexus.fusion.exit_teu),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "fusion", "observation_slots"],
        i64::from(nexus.fusion.observation_slots.get()),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "fusion", "max_window_slots"],
        i64::from(nexus.fusion.max_window_slots.get()),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "commit", "window_slots"],
        i64::from(nexus.commit.window_slots.get()),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "da", "q_in_slot_total"],
        i64::from(nexus.da.q_in_slot_total.get()),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "da", "q_in_slot_per_ds_min"],
        i64::from(nexus.da.q_in_slot_per_ds_min.get()),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "da", "sample_size_base"],
        i64::from(nexus.da.sample_size_base.get()),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "da", "sample_size_max"],
        i64::from(nexus.da.sample_size_max.get()),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "da", "threshold_base"],
        i64::from(nexus.da.threshold_base.get()),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "da", "per_attester_shards"],
        i64::from(nexus.da.per_attester_shards.get()),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "da", "audit", "sample_size"],
        i64::from(nexus.da.audit.sample_size.get()),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "da", "audit", "window_count"],
        i64::from(nexus.da.audit.window_count.get()),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "da", "audit", "interval_ms"],
        i64::try_from(nexus.da.audit.interval.as_millis()).unwrap_or_default(),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "da", "recovery", "request_timeout_ms"],
        i64::try_from(nexus.da.recovery.request_timeout.as_millis()).unwrap_or_default(),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "da", "rotation", "max_hits_per_window"],
        i64::from(nexus.da.rotation.max_hits_per_window.get()),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "da", "rotation", "window_slots"],
        i64::from(nexus.da.rotation.window_slots.get()),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "da", "rotation", "seed_tag"],
        nexus.da.rotation.seed_tag.clone(),
    );
    TomlWriter::new(&mut layer).write(
        ["nexus", "da", "rotation", "latency_decay"],
        nexus.da.rotation.latency_decay,
    );
    write_sumeragi_v2_layer(&mut layer, sumeragi);
    layer
}
fn write_sumeragi_v2_layer(layer: &mut Table, sumeragi: &ActualSumeragi) {
    let usize_value = |value: usize| i64::try_from(value).expect("Sumeragi limit fits i64");
    let role = match sumeragi.role {
        iroha_config::parameters::actual::NodeRole::Validator => "validator",
        iroha_config::parameters::actual::NodeRole::Observer => "observer",
    };
    let allowed_algorithms = sumeragi
        .keys
        .allowed_algorithms
        .iter()
        .map(|algorithm| Value::String(algorithm.to_string()))
        .collect();
    TomlWriter::new(layer)
        .write(["sumeragi", "role"], role)
        .write(
            ["sumeragi", "block", "max_transactions"],
            usize_value(sumeragi.block.max_transactions.get()),
        )
        .write(
            ["sumeragi", "block", "max_payload_bytes"],
            usize_value(sumeragi.block.max_payload_bytes.get()),
        )
        .write(
            ["sumeragi", "block", "proposal_queue_scan_multiplier"],
            usize_value(sumeragi.block.proposal_queue_scan_multiplier.get()),
        )
        .write(
            ["sumeragi", "queues", "commands"],
            usize_value(sumeragi.queues.commands.get()),
        )
        .write(
            ["sumeragi", "queues", "bodies"],
            usize_value(sumeragi.queues.bodies.get()),
        )
        .write(
            ["sumeragi", "queues", "chunks"],
            usize_value(sumeragi.queues.chunks.get()),
        )
        .write(
            ["sumeragi", "queues", "ready_bodies"],
            usize_value(sumeragi.queues.ready_bodies.get()),
        )
        .write(
            ["sumeragi", "keys", "activation_lead_blocks"],
            i64::try_from(sumeragi.keys.activation_lead_blocks).expect("key limit fits i64"),
        )
        .write(
            ["sumeragi", "keys", "overlap_grace_blocks"],
            i64::try_from(sumeragi.keys.overlap_grace_blocks).expect("key limit fits i64"),
        )
        .write(
            ["sumeragi", "keys", "expiry_grace_blocks"],
            i64::try_from(sumeragi.keys.expiry_grace_blocks).expect("key limit fits i64"),
        )
        .write(
            ["sumeragi", "keys", "allowed_algorithms"],
            Value::Array(allowed_algorithms),
        );
}
fn dataspace_alias_map(
    catalog: &DataSpaceCatalog,
) -> std::collections::BTreeMap<DataSpaceId, String> {
    catalog
        .entries()
        .iter()
        .map(|entry| (entry.id, entry.alias.clone()))
        .collect()
}
fn lane_rule_to_value(
    rule: &LaneRoutingRule,
    dataspace_aliases: &std::collections::BTreeMap<DataSpaceId, String>,
) -> Value {
    let mut table = Table::new();
    table.insert(
        "lane".to_string(),
        Value::Integer(i64::from(rule.lane.as_u32())),
    );
    if let Some(dataspace) = rule
        .dataspace
        .and_then(|id| dataspace_aliases.get(&id).cloned())
    {
        table.insert("dataspace".to_string(), Value::String(dataspace));
    }
    let mut matcher = Table::new();
    if let Some(account) = &rule.matcher.account {
        matcher.insert("account".to_string(), Value::String(account.to_string()));
    }
    if let Some(instruction) = &rule.matcher.instruction {
        matcher.insert(
            "instruction".to_string(),
            Value::String(instruction.clone()),
        );
    }
    if let Some(description) = &rule.matcher.description {
        matcher.insert(
            "description".to_string(),
            Value::String(description.clone()),
        );
    }
    table.insert("matcher".to_string(), Value::Table(matcher));
    Value::Table(table)
}
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fault_toggles_use_the_exact_v1_flag_order() {
        let toggles =
            FaultToggles::from_enabled_flags([true, false, true, false, true, false, true]);

        assert!(toggles.crash_restart());
        assert!(!toggles.wipe_storage());
        assert!(toggles.spam_invalid_transactions());
        assert!(!toggles.network_latency());
        assert!(toggles.network_partition());
        assert!(!toggles.cpu_stress());
        assert!(toggles.disk_saturation());
        assert_eq!(FaultToggles::try_from_bits(toggles.bits()), Some(toggles));
        assert_eq!(FaultToggles::try_from_bits(toggles.bits() | (1 << 7)), None);
    }

    #[test]
    fn chaos_config_rejects_invalid_faulty_counts() {
        let args = IzanamiArgs {
            tui: false,
            allow_net: true,
            peers: 7,
            faulty: 3,
            duration: Duration::from_secs(1),
            pipeline_time: None,
            target_blocks: None,
            progress_interval: DEFAULT_PROGRESS_INTERVAL,
            progress_timeout: DEFAULT_PROGRESS_TIMEOUT,
            shutdown_drain_timeout: DEFAULT_SHUTDOWN_DRAIN_TIMEOUT,
            latency_p95_threshold: None,
            fault_window_start: None,
            fault_window_end: None,
            seed: None,
            tps: 1.0,
            max_inflight: 1,
            submitters: 1,
            prebuild_tx_buffer: 0,
            prebuild_tx_workers: 0,
            sumeragi_block_max_transactions: DEFAULT_SUMERAGI_BLOCK_MAX_TRANSACTIONS,
            sumeragi_proposal_queue_scan_multiplier:
                DEFAULT_SUMERAGI_PROPOSAL_QUEUE_SCAN_MULTIPLIER,
            workload_profile: WorkloadProfile::Stable,
            allow_contract_deploy_in_stable: false,
            log_filter: "info".to_string(),
            fault_interval_min: Duration::from_secs(1),
            fault_interval_max: Duration::from_secs(2),
            faults: FaultArgs {
                crash_restart: true,
                wipe_storage: true,
                spam_invalid_transactions: true,
                network_latency: true,
                network_partition: true,
                cpu_stress: true,
                disk_saturation: true,
            },
            nexus: false,
            diagnostic_dir: None,
        };
        let err = ChaosConfig::try_from(args).expect_err("faulty peers above f must fail");
        assert!(
            err.to_string().contains("fault tolerance f=2"),
            "error should report the revision-4 fault bound: {err}"
        );
    }
    #[test]
    fn chaos_config_accepts_every_revision4_committee_size() {
        for peers in (MIN_VALIDATORS_PER_HEIGHT..=MAX_VALIDATORS_PER_HEIGHT).step_by(3) {
            let mut args = IzanamiArgs::defaults();
            args.allow_net = true;
            args.peers = peers;
            args.faulty = (peers - 1) / 3;
            let config = ChaosConfig::try_from(args)
                .unwrap_or_else(|error| panic!("valid {peers}-peer committee failed: {error}"));
            assert_eq!(config.peer_count, peers);
            assert_eq!(config.faulty_peers, (peers - 1) / 3);
        }
    }
    #[test]
    fn chaos_config_rejects_non_revision4_committee_sizes() {
        for peers in [0, 1, 2, 3, 5, 6, 8, 30, 32, 34] {
            let mut args = IzanamiArgs::defaults();
            args.allow_net = true;
            args.peers = peers;
            args.faulty = 0;
            let error = ChaosConfig::try_from(args)
                .expect_err("non-revision-4 committee geometry must fail");
            assert!(
                error.to_string().contains("exact revision-4 3f + 1"),
                "error should report invalid committee geometry for {peers} peers: {error}"
            );
        }
    }
    #[test]
    fn init_tracing_is_idempotent() {
        let args = IzanamiArgs {
            tui: false,
            allow_net: true,
            peers: 4,
            faulty: 0,
            duration: Duration::from_secs(1),
            pipeline_time: None,
            target_blocks: None,
            progress_interval: DEFAULT_PROGRESS_INTERVAL,
            progress_timeout: DEFAULT_PROGRESS_TIMEOUT,
            shutdown_drain_timeout: DEFAULT_SHUTDOWN_DRAIN_TIMEOUT,
            latency_p95_threshold: None,
            fault_window_start: None,
            fault_window_end: None,
            seed: Some(42),
            tps: 1.0,
            max_inflight: 1,
            submitters: 1,
            prebuild_tx_buffer: 0,
            prebuild_tx_workers: 0,
            sumeragi_block_max_transactions: DEFAULT_SUMERAGI_BLOCK_MAX_TRANSACTIONS,
            sumeragi_proposal_queue_scan_multiplier:
                DEFAULT_SUMERAGI_PROPOSAL_QUEUE_SCAN_MULTIPLIER,
            workload_profile: WorkloadProfile::Stable,
            allow_contract_deploy_in_stable: false,
            log_filter: "warn".to_string(),
            fault_interval_min: Duration::from_secs(1),
            fault_interval_max: Duration::from_secs(1),
            faults: FaultArgs::default(),
            nexus: false,
            diagnostic_dir: None,
        };
        init_tracing_with_filter(&args.log_filter);
        init_tracing_with_filter(&args.log_filter);
    }
    #[test]
    fn chaos_config_requires_allow_net_opt_in() {
        let args = IzanamiArgs {
            tui: false,
            allow_net: false,
            peers: 4,
            faulty: 0,
            duration: Duration::from_secs(1),
            pipeline_time: None,
            target_blocks: None,
            progress_interval: DEFAULT_PROGRESS_INTERVAL,
            progress_timeout: DEFAULT_PROGRESS_TIMEOUT,
            shutdown_drain_timeout: DEFAULT_SHUTDOWN_DRAIN_TIMEOUT,
            latency_p95_threshold: None,
            fault_window_start: None,
            fault_window_end: None,
            seed: None,
            tps: 1.0,
            max_inflight: 1,
            submitters: 1,
            prebuild_tx_buffer: 0,
            prebuild_tx_workers: 0,
            sumeragi_block_max_transactions: DEFAULT_SUMERAGI_BLOCK_MAX_TRANSACTIONS,
            sumeragi_proposal_queue_scan_multiplier:
                DEFAULT_SUMERAGI_PROPOSAL_QUEUE_SCAN_MULTIPLIER,
            workload_profile: WorkloadProfile::Stable,
            allow_contract_deploy_in_stable: false,
            log_filter: "info".to_string(),
            fault_interval_min: Duration::from_secs(1),
            fault_interval_max: Duration::from_secs(1),
            faults: FaultArgs::default(),
            nexus: false,
            diagnostic_dir: None,
        };
        let Err(err) = ChaosConfig::try_from(args) else {
            panic!("allow_net=false should prevent ChaosConfig construction");
        };
        assert!(
            err.to_string().contains("allow_net"),
            "error should mention allow_net opt-in: {err}"
        );
    }
    #[test]
    fn chaos_config_rejects_zero_target_blocks() {
        let args = IzanamiArgs {
            tui: false,
            allow_net: true,
            peers: 4,
            faulty: 0,
            duration: Duration::from_secs(1),
            pipeline_time: None,
            target_blocks: Some(0),
            progress_interval: DEFAULT_PROGRESS_INTERVAL,
            progress_timeout: DEFAULT_PROGRESS_TIMEOUT,
            shutdown_drain_timeout: DEFAULT_SHUTDOWN_DRAIN_TIMEOUT,
            latency_p95_threshold: None,
            fault_window_start: None,
            fault_window_end: None,
            seed: None,
            tps: 1.0,
            max_inflight: 1,
            submitters: 1,
            prebuild_tx_buffer: 0,
            prebuild_tx_workers: 0,
            sumeragi_block_max_transactions: DEFAULT_SUMERAGI_BLOCK_MAX_TRANSACTIONS,
            sumeragi_proposal_queue_scan_multiplier:
                DEFAULT_SUMERAGI_PROPOSAL_QUEUE_SCAN_MULTIPLIER,
            workload_profile: WorkloadProfile::Stable,
            allow_contract_deploy_in_stable: false,
            log_filter: "info".to_string(),
            fault_interval_min: Duration::from_secs(1),
            fault_interval_max: Duration::from_secs(1),
            faults: FaultArgs::default(),
            nexus: false,
            diagnostic_dir: None,
        };
        assert!(ChaosConfig::try_from(args).is_err());
    }
    #[test]
    fn chaos_config_rejects_pipeline_time_under_minimum() {
        let args = IzanamiArgs {
            tui: false,
            allow_net: true,
            peers: 4,
            faulty: 0,
            duration: Duration::from_secs(1),
            pipeline_time: Some(
                MIN_PIPELINE_TIME
                    .checked_sub(Duration::from_millis(1))
                    .unwrap_or(Duration::ZERO),
            ),
            target_blocks: None,
            progress_interval: DEFAULT_PROGRESS_INTERVAL,
            progress_timeout: DEFAULT_PROGRESS_TIMEOUT,
            shutdown_drain_timeout: DEFAULT_SHUTDOWN_DRAIN_TIMEOUT,
            latency_p95_threshold: None,
            fault_window_start: None,
            fault_window_end: None,
            seed: None,
            tps: 1.0,
            max_inflight: 1,
            submitters: 1,
            prebuild_tx_buffer: 0,
            prebuild_tx_workers: 0,
            sumeragi_block_max_transactions: DEFAULT_SUMERAGI_BLOCK_MAX_TRANSACTIONS,
            sumeragi_proposal_queue_scan_multiplier:
                DEFAULT_SUMERAGI_PROPOSAL_QUEUE_SCAN_MULTIPLIER,
            workload_profile: WorkloadProfile::Stable,
            allow_contract_deploy_in_stable: false,
            log_filter: "info".to_string(),
            fault_interval_min: Duration::from_secs(1),
            fault_interval_max: Duration::from_secs(1),
            faults: FaultArgs::default(),
            nexus: false,
            diagnostic_dir: None,
        };
        let Err(err) = ChaosConfig::try_from(args) else {
            panic!("pipeline_time below minimum should fail");
        };
        assert!(
            err.to_string().contains("pipeline_time must be at least"),
            "error should mention pipeline_time minimum: {err}"
        );
    }
    #[test]
    fn nexus_profile_emits_only_node_local_sumeragi_v2_configuration() {
        let profile = NexusProfile::sora_defaults().expect("nexus profile should load");
        assert!(
            !profile.config_layer.contains_key("genesis"),
            "the operator-owned genesis identity must not leak into Izanami's projected layer"
        );
        let sumeragi = profile
            .config_layer
            .get("sumeragi")
            .and_then(Value::as_table)
            .expect("strict Sumeragi v2 configuration");
        assert!(!sumeragi.contains_key("round_timeout_ms"));
        assert_eq!(
            sumeragi.get("role").and_then(Value::as_str),
            Some("validator")
        );
        assert!(!sumeragi.contains_key("consensus_mode"));
        assert!(!sumeragi.contains_key("protocol_version"));
        assert!(!sumeragi.contains_key("da"));
        assert!(!sumeragi.contains_key("advanced"));
        assert!(!sumeragi.contains_key("recovery"));
        assert!(sumeragi.contains_key("block"));
        assert!(sumeragi.contains_key("queues"));
        assert!(sumeragi.contains_key("keys"));
        assert!(!sumeragi.contains_key("npos"));
        let nexus = profile
            .config_layer
            .get("nexus")
            .and_then(Value::as_table)
            .expect("canonical Nexus lane configuration");
        assert!(
            !nexus.contains_key("enabled"),
            "the retired nexus.enabled switch must not be emitted"
        );
        assert!(nexus.contains_key("lane_count"));
    }
    #[test]
    fn nexus_profile_deduplicates_bootstrap_staking_owners_for_shared_dataspace() {
        let profile = NexusProfile::sora_defaults().expect("nexus profile should load");
        assert!(
            profile
                .lane_catalog
                .lanes()
                .iter()
                .all(|lane| lane.dataspace_id == DataSpaceId::UNIVERSAL),
            "the fixture must exercise several lanes sharing one physical dataspace"
        );
        assert_eq!(
            profile.bootstrap_public_lanes,
            vec![LaneId::new(0)],
            "only the lowest stake-elected lane may own shared-dataspace staking state"
        );
    }
    #[test]
    fn nexus_profile_preserves_embedded_dataspace_manifest_hashes() {
        let profile = NexusProfile::sora_defaults().expect("nexus profile should load");
        let dataspaces = profile
            .config_layer
            .get("nexus")
            .and_then(Value::as_table)
            .and_then(|nexus| nexus.get("dataspace_catalog"))
            .and_then(Value::as_array)
            .expect("embedded dataspace catalog");
        let manifest_hash = |alias: &str| {
            dataspaces
                .iter()
                .filter_map(Value::as_table)
                .find(|entry| entry.get("alias").and_then(Value::as_str) == Some(alias))
                .and_then(|entry| entry.get("manifest_hash"))
                .and_then(Value::as_str)
        };
        assert_eq!(manifest_hash("universal"), None);
        assert_eq!(
            manifest_hash("governance"),
            Some("0100000000000000000000000000000000000000000000000000000000000000")
        );
        assert_eq!(
            manifest_hash("zk"),
            Some("0200000000000000000000000000000000000000000000000000000000000000")
        );
    }
    #[test]
    fn nexus_profile_preserves_effective_bootstrap_asset_ids() {
        let profile = NexusProfile::sora_defaults().expect("nexus profile should load");
        let expected_fee_asset = profile.fee_asset_id.to_string();
        let expected_stake_asset = profile.stake_asset_id.to_string();
        let fee_asset = profile
            .config_layer
            .get("nexus")
            .and_then(Value::as_table)
            .and_then(|nexus| nexus.get("fees"))
            .and_then(Value::as_table)
            .and_then(|fees| fees.get("fee_asset_id"))
            .and_then(Value::as_str);
        let stake_asset = profile
            .config_layer
            .get("nexus")
            .and_then(Value::as_table)
            .and_then(|nexus| nexus.get("staking"))
            .and_then(Value::as_table)
            .and_then(|staking| staking.get("stake_asset_id"))
            .and_then(Value::as_str);
        assert_eq!(fee_asset, Some(expected_fee_asset.as_str()));
        assert_eq!(stake_asset, Some(expected_stake_asset.as_str()));
    }
    #[test]
    fn chaos_config_rejects_progress_interval_over_timeout() {
        let args = IzanamiArgs {
            tui: false,
            allow_net: true,
            peers: 4,
            faulty: 0,
            duration: Duration::from_secs(1),
            pipeline_time: None,
            target_blocks: Some(5),
            progress_interval: Duration::from_secs(10),
            progress_timeout: Duration::from_secs(5),
            shutdown_drain_timeout: DEFAULT_SHUTDOWN_DRAIN_TIMEOUT,
            latency_p95_threshold: None,
            fault_window_start: None,
            fault_window_end: None,
            seed: None,
            tps: 1.0,
            max_inflight: 1,
            submitters: 1,
            prebuild_tx_buffer: 0,
            prebuild_tx_workers: 0,
            sumeragi_block_max_transactions: DEFAULT_SUMERAGI_BLOCK_MAX_TRANSACTIONS,
            sumeragi_proposal_queue_scan_multiplier:
                DEFAULT_SUMERAGI_PROPOSAL_QUEUE_SCAN_MULTIPLIER,
            workload_profile: WorkloadProfile::Stable,
            allow_contract_deploy_in_stable: false,
            log_filter: "info".to_string(),
            fault_interval_min: Duration::from_secs(1),
            fault_interval_max: Duration::from_secs(1),
            faults: FaultArgs::default(),
            nexus: false,
            diagnostic_dir: None,
        };
        let Err(err) = ChaosConfig::try_from(args) else {
            panic!("progress_interval > progress_timeout should fail");
        };
        assert!(
            err.to_string().contains("progress_interval"),
            "error should mention progress_interval: {err}"
        );
    }
    #[test]
    fn chaos_config_rejects_non_finite_tps() {
        let args = IzanamiArgs {
            tui: false,
            allow_net: true,
            peers: 4,
            faulty: 0,
            duration: Duration::from_secs(1),
            pipeline_time: None,
            target_blocks: None,
            progress_interval: DEFAULT_PROGRESS_INTERVAL,
            progress_timeout: DEFAULT_PROGRESS_TIMEOUT,
            shutdown_drain_timeout: DEFAULT_SHUTDOWN_DRAIN_TIMEOUT,
            latency_p95_threshold: None,
            fault_window_start: None,
            fault_window_end: None,
            seed: None,
            tps: f64::NAN,
            max_inflight: 1,
            submitters: 1,
            prebuild_tx_buffer: 0,
            prebuild_tx_workers: 0,
            sumeragi_block_max_transactions: DEFAULT_SUMERAGI_BLOCK_MAX_TRANSACTIONS,
            sumeragi_proposal_queue_scan_multiplier:
                DEFAULT_SUMERAGI_PROPOSAL_QUEUE_SCAN_MULTIPLIER,
            workload_profile: WorkloadProfile::Stable,
            allow_contract_deploy_in_stable: false,
            log_filter: "info".to_string(),
            fault_interval_min: Duration::from_secs(1),
            fault_interval_max: Duration::from_secs(1),
            faults: FaultArgs::default(),
            nexus: false,
            diagnostic_dir: None,
        };
        let Err(err) = ChaosConfig::try_from(args) else {
            panic!("non-finite tps should fail");
        };
        assert!(
            err.to_string().contains("tps must be finite"),
            "error should mention finite tps: {err}"
        );
    }
    #[test]
    fn chaos_config_rejects_tps_too_high_for_timer() {
        let args = IzanamiArgs {
            tui: false,
            allow_net: true,
            peers: 4,
            faulty: 0,
            duration: Duration::from_secs(1),
            pipeline_time: None,
            target_blocks: None,
            progress_interval: DEFAULT_PROGRESS_INTERVAL,
            progress_timeout: DEFAULT_PROGRESS_TIMEOUT,
            shutdown_drain_timeout: DEFAULT_SHUTDOWN_DRAIN_TIMEOUT,
            latency_p95_threshold: None,
            fault_window_start: None,
            fault_window_end: None,
            seed: None,
            tps: f64::MAX,
            max_inflight: 1,
            submitters: 1,
            prebuild_tx_buffer: 0,
            prebuild_tx_workers: 0,
            sumeragi_block_max_transactions: DEFAULT_SUMERAGI_BLOCK_MAX_TRANSACTIONS,
            sumeragi_proposal_queue_scan_multiplier:
                DEFAULT_SUMERAGI_PROPOSAL_QUEUE_SCAN_MULTIPLIER,
            workload_profile: WorkloadProfile::Stable,
            allow_contract_deploy_in_stable: false,
            log_filter: "info".to_string(),
            fault_interval_min: Duration::from_secs(1),
            fault_interval_max: Duration::from_secs(1),
            faults: FaultArgs::default(),
            nexus: false,
            diagnostic_dir: None,
        };
        let Err(err) = ChaosConfig::try_from(args) else {
            panic!("tps too high for timer resolution should fail");
        };
        assert!(
            err.to_string().contains("tps too high"),
            "error should mention timer resolution: {err}"
        );
    }
    #[test]
    fn chaos_config_rejects_tps_too_low_for_timer() {
        let args = IzanamiArgs {
            tui: false,
            allow_net: true,
            peers: 4,
            faulty: 0,
            duration: Duration::from_secs(1),
            pipeline_time: None,
            target_blocks: None,
            progress_interval: DEFAULT_PROGRESS_INTERVAL,
            progress_timeout: DEFAULT_PROGRESS_TIMEOUT,
            shutdown_drain_timeout: DEFAULT_SHUTDOWN_DRAIN_TIMEOUT,
            latency_p95_threshold: None,
            fault_window_start: None,
            fault_window_end: None,
            seed: None,
            tps: f64::MIN_POSITIVE,
            max_inflight: 1,
            submitters: 1,
            prebuild_tx_buffer: 0,
            prebuild_tx_workers: 0,
            sumeragi_block_max_transactions: DEFAULT_SUMERAGI_BLOCK_MAX_TRANSACTIONS,
            sumeragi_proposal_queue_scan_multiplier:
                DEFAULT_SUMERAGI_PROPOSAL_QUEUE_SCAN_MULTIPLIER,
            workload_profile: WorkloadProfile::Stable,
            allow_contract_deploy_in_stable: false,
            log_filter: "info".to_string(),
            fault_interval_min: Duration::from_secs(1),
            fault_interval_max: Duration::from_secs(1),
            faults: FaultArgs::default(),
            nexus: false,
            diagnostic_dir: None,
        };
        let Err(err) = ChaosConfig::try_from(args) else {
            panic!("tps too low for timer range should fail");
        };
        assert!(
            err.to_string().contains("tps too low"),
            "error should mention timer range: {err}"
        );
    }
    #[test]
    fn chaos_config_accepts_latency_threshold_without_target_blocks() {
        let args = IzanamiArgs {
            tui: false,
            allow_net: true,
            peers: 4,
            faulty: 0,
            duration: Duration::from_secs(1),
            pipeline_time: None,
            target_blocks: None,
            progress_interval: DEFAULT_PROGRESS_INTERVAL,
            progress_timeout: DEFAULT_PROGRESS_TIMEOUT,
            shutdown_drain_timeout: DEFAULT_SHUTDOWN_DRAIN_TIMEOUT,
            latency_p95_threshold: Some(Duration::from_millis(900)),
            fault_window_start: None,
            fault_window_end: None,
            seed: None,
            tps: 1.0,
            max_inflight: 1,
            submitters: 1,
            prebuild_tx_buffer: 0,
            prebuild_tx_workers: 0,
            sumeragi_block_max_transactions: DEFAULT_SUMERAGI_BLOCK_MAX_TRANSACTIONS,
            sumeragi_proposal_queue_scan_multiplier:
                DEFAULT_SUMERAGI_PROPOSAL_QUEUE_SCAN_MULTIPLIER,
            workload_profile: WorkloadProfile::Stable,
            allow_contract_deploy_in_stable: false,
            log_filter: "info".to_string(),
            fault_interval_min: Duration::from_secs(1),
            fault_interval_max: Duration::from_secs(1),
            faults: FaultArgs::default(),
            nexus: false,
            diagnostic_dir: None,
        };
        let config = ChaosConfig::try_from(args)
            .expect("duration-only cadence gates should not require target_blocks");
        assert_eq!(
            config.latency_p95_threshold,
            Some(Duration::from_millis(900))
        );
    }
    #[test]
    fn chaos_config_rejects_zero_latency_threshold() {
        let args = IzanamiArgs {
            tui: false,
            allow_net: true,
            peers: 4,
            faulty: 0,
            duration: Duration::from_secs(1),
            pipeline_time: None,
            target_blocks: Some(5),
            progress_interval: DEFAULT_PROGRESS_INTERVAL,
            progress_timeout: DEFAULT_PROGRESS_TIMEOUT,
            shutdown_drain_timeout: DEFAULT_SHUTDOWN_DRAIN_TIMEOUT,
            latency_p95_threshold: Some(Duration::ZERO),
            fault_window_start: None,
            fault_window_end: None,
            seed: None,
            tps: 1.0,
            max_inflight: 1,
            submitters: 1,
            prebuild_tx_buffer: 0,
            prebuild_tx_workers: 0,
            sumeragi_block_max_transactions: DEFAULT_SUMERAGI_BLOCK_MAX_TRANSACTIONS,
            sumeragi_proposal_queue_scan_multiplier:
                DEFAULT_SUMERAGI_PROPOSAL_QUEUE_SCAN_MULTIPLIER,
            workload_profile: WorkloadProfile::Stable,
            allow_contract_deploy_in_stable: false,
            log_filter: "info".to_string(),
            fault_interval_min: Duration::from_secs(1),
            fault_interval_max: Duration::from_secs(1),
            faults: FaultArgs::default(),
            nexus: false,
            diagnostic_dir: None,
        };
        let Err(err) = ChaosConfig::try_from(args) else {
            panic!("zero latency threshold should fail");
        };
        assert!(
            err.to_string().contains("latency_p95_threshold"),
            "error should mention latency_p95_threshold: {err}"
        );
    }
    #[test]
    fn chaos_config_accepts_sumeragi_block_tuning() {
        let mut args = IzanamiArgs::defaults();
        args.allow_net = true;
        args.faulty = 0;
        args.sumeragi_block_max_transactions = 1_536;
        args.sumeragi_proposal_queue_scan_multiplier = 2;
        let config = ChaosConfig::try_from(args).expect("sumeragi block tuning should be valid");
        assert_eq!(config.sumeragi_block_max_transactions, 1_536);
        assert_eq!(config.sumeragi_proposal_queue_scan_multiplier, 2);
    }
    #[test]
    fn chaos_config_accepts_bounded_fault_window() {
        let mut args = IzanamiArgs::defaults();
        args.allow_net = true;
        args.duration = Duration::from_secs(800);
        args.fault_window_start = Some(Duration::from_secs(133));
        args.fault_window_end = Some(Duration::from_secs(266));
        let config = ChaosConfig::try_from(args).expect("paper fault window should be valid");
        assert_eq!(config.fault_window_start, Some(Duration::from_secs(133)));
        assert_eq!(config.fault_window_end, Some(Duration::from_secs(266)));
    }
    #[test]
    fn chaos_config_rejects_fault_window_end_before_start() {
        let mut args = IzanamiArgs::defaults();
        args.allow_net = true;
        args.duration = Duration::from_secs(800);
        args.fault_window_start = Some(Duration::from_secs(266));
        args.fault_window_end = Some(Duration::from_secs(133));
        let err = ChaosConfig::try_from(args).expect_err("inverted fault window must fail");
        assert!(
            err.to_string().contains("fault_window_end"),
            "error should mention fault_window_end: {err}"
        );
    }
    #[test]
    fn chaos_config_rejects_fault_window_start_after_duration() {
        let mut args = IzanamiArgs::defaults();
        args.allow_net = true;
        args.duration = Duration::from_secs(30);
        args.fault_window_start = Some(Duration::from_secs(30));
        let err = ChaosConfig::try_from(args).expect_err("late fault window must fail");
        assert!(
            err.to_string().contains("fault_window_start"),
            "error should mention fault_window_start: {err}"
        );
    }
    #[test]
    fn chaos_config_rejects_zero_submitters() {
        let args = IzanamiArgs {
            tui: false,
            allow_net: true,
            peers: 4,
            faulty: 0,
            duration: Duration::from_secs(1),
            pipeline_time: None,
            target_blocks: None,
            progress_interval: DEFAULT_PROGRESS_INTERVAL,
            progress_timeout: DEFAULT_PROGRESS_TIMEOUT,
            shutdown_drain_timeout: DEFAULT_SHUTDOWN_DRAIN_TIMEOUT,
            latency_p95_threshold: None,
            fault_window_start: None,
            fault_window_end: None,
            seed: None,
            tps: 1.0,
            max_inflight: 1,
            submitters: 0,
            prebuild_tx_buffer: 0,
            prebuild_tx_workers: 0,
            sumeragi_block_max_transactions: DEFAULT_SUMERAGI_BLOCK_MAX_TRANSACTIONS,
            sumeragi_proposal_queue_scan_multiplier:
                DEFAULT_SUMERAGI_PROPOSAL_QUEUE_SCAN_MULTIPLIER,
            workload_profile: WorkloadProfile::Stable,
            allow_contract_deploy_in_stable: false,
            log_filter: "info".to_string(),
            fault_interval_min: Duration::from_secs(1),
            fault_interval_max: Duration::from_secs(1),
            faults: FaultArgs::default(),
            nexus: false,
            diagnostic_dir: None,
        };
        let Err(err) = ChaosConfig::try_from(args) else {
            panic!("zero submitters should fail");
        };
        assert!(
            err.to_string().contains("submitters"),
            "error should mention submitters: {err}"
        );
    }
    #[test]
    fn chaos_config_rejects_faulty_peers_with_no_enabled_faults() {
        let args = IzanamiArgs {
            tui: false,
            allow_net: true,
            peers: 4,
            faulty: 1,
            duration: Duration::from_secs(1),
            pipeline_time: None,
            target_blocks: None,
            progress_interval: DEFAULT_PROGRESS_INTERVAL,
            progress_timeout: DEFAULT_PROGRESS_TIMEOUT,
            shutdown_drain_timeout: DEFAULT_SHUTDOWN_DRAIN_TIMEOUT,
            latency_p95_threshold: None,
            fault_window_start: None,
            fault_window_end: None,
            seed: None,
            tps: 1.0,
            max_inflight: 1,
            submitters: 1,
            prebuild_tx_buffer: 0,
            prebuild_tx_workers: 0,
            sumeragi_block_max_transactions: DEFAULT_SUMERAGI_BLOCK_MAX_TRANSACTIONS,
            sumeragi_proposal_queue_scan_multiplier:
                DEFAULT_SUMERAGI_PROPOSAL_QUEUE_SCAN_MULTIPLIER,
            workload_profile: WorkloadProfile::Stable,
            allow_contract_deploy_in_stable: false,
            log_filter: "info".to_string(),
            fault_interval_min: Duration::from_secs(1),
            fault_interval_max: Duration::from_secs(1),
            faults: FaultArgs {
                crash_restart: false,
                wipe_storage: false,
                spam_invalid_transactions: false,
                network_latency: false,
                network_partition: false,
                cpu_stress: false,
                disk_saturation: false,
            },
            nexus: false,
            diagnostic_dir: None,
        };
        let Err(err) = ChaosConfig::try_from(args) else {
            panic!("faulty peers without enabled faults should fail");
        };
        assert!(
            err.to_string().contains("fault scenario"),
            "error should mention enabled fault scenarios: {err}"
        );
    }
}
