//! Immutable compiler-captured identities for this source owner’s existing codecs.

#[test]
fn captured_codec_schema_identities() {
    crate::captured_schema_tests::assert_bidirectional::<super::JurisdictionId>(
        "iroha_data_model::jurisdiction::JurisdictionId",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::JdgBlockRange>(
        "iroha_data_model::jurisdiction::JdgBlockRange",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::JdgAttestationScope>(
        "iroha_data_model::jurisdiction::JdgAttestationScope",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::JdgStateAccessSet>(
        "iroha_data_model::jurisdiction::JdgStateAccessSet",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::JdgVerdict>(
        "iroha_data_model::jurisdiction::JdgVerdict",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::JdgSignatureScheme>(
        "iroha_data_model::jurisdiction::JdgSignatureScheme",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::JdgThresholdSignature>(
        "iroha_data_model::jurisdiction::JdgThresholdSignature",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::JdgSdnCommitment>(
        "iroha_data_model::jurisdiction::JdgSdnCommitment",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::JdgSdnCommitmentSignable>(
        "iroha_data_model::jurisdiction::JdgSdnCommitmentSignable",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::JdgSdnRotationPolicy>(
        "iroha_data_model::jurisdiction::JdgSdnRotationPolicy",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::JdgSdnPolicy>(
        "iroha_data_model::jurisdiction::JdgSdnPolicy",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::JdgSdnKeyRecord>(
        "iroha_data_model::jurisdiction::JdgSdnKeyRecord",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::JdgCommitteeId>(
        "iroha_data_model::jurisdiction::JdgCommitteeId",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::JdgAttestation>(
        "iroha_data_model::jurisdiction::JdgAttestation",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::JdgAttestationSignable>(
        "iroha_data_model::jurisdiction::JdgAttestationSignable",
    );
}
