[package]
name = "iroha_swarm"

edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
iroha_model_base = { workspace = true }
iroha_crypto = { workspace = true, default-features = false, features = ["node-crypto"] }
iroha_data_model = { workspace = true, default-features = false, features = ["application-model"] }
iroha_primitives.workspace = true
path-absolutize.workspace = true
displaydoc.workspace = true
pathdiff = "0.2.3"
norito = { workspace = true, default-features = false, features = ["node-codec"] }

[dev-dependencies]
iroha_config.workspace = true
nonzero_ext.workspace = true
