//! Immutable compiler-captured identities for this source owner’s existing codecs.

#[test]
fn captured_codec_schema_identities() {
    crate::captured_schema_tests::assert_bidirectional::<super::TaikaiAnchorReceiptBodyV1>(
        "iroha_data_model::taikai::TaikaiAnchorReceiptBodyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::TaikaiAnchorReceiptV1>(
        "iroha_data_model::taikai::TaikaiAnchorReceiptV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::TaikaiTrackKind>(
        "iroha_data_model::taikai::TaikaiTrackKind",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::TaikaiResolution>(
        "iroha_data_model::taikai::TaikaiResolution",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::TaikaiAudioLayout>(
        "iroha_data_model::taikai::TaikaiAudioLayout",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::TaikaiCodec>(
        "iroha_data_model::taikai::TaikaiCodec",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::TaikaiTrackMetadata>(
        "iroha_data_model::taikai::TaikaiTrackMetadata",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::TaikaiCarPointer>(
        "iroha_data_model::taikai::TaikaiCarPointer",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::TaikaiIngestPointer>(
        "iroha_data_model::taikai::TaikaiIngestPointer",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::TaikaiInstrumentation>(
        "iroha_data_model::taikai::TaikaiInstrumentation",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::TaikaiSegmentEnvelopeV1>(
        "iroha_data_model::taikai::TaikaiSegmentEnvelopeV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::TaikaiTimeIndexKey>(
        "iroha_data_model::taikai::TaikaiTimeIndexKey",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::TaikaiCidIndexKey>(
        "iroha_data_model::taikai::TaikaiCidIndexKey",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::TaikaiEnvelopeIndexes>(
        "iroha_data_model::taikai::TaikaiEnvelopeIndexes",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::CekRotationReceiptV1>(
        "iroha_data_model::taikai::CekRotationReceiptV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ReplicationProofTokenV1>(
        "iroha_data_model::taikai::ReplicationProofTokenV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::TaikaiSegmentWindow>(
        "iroha_data_model::taikai::TaikaiSegmentWindow",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::TaikaiAvailabilityClass>(
        "iroha_data_model::taikai::TaikaiAvailabilityClass",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::TaikaiRenditionRouteV1>(
        "iroha_data_model::taikai::TaikaiRenditionRouteV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::TaikaiRoutingManifestV1>(
        "iroha_data_model::taikai::TaikaiRoutingManifestV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::TaikaiSegmentSigningBodyV1>(
        "iroha_data_model::taikai::TaikaiSegmentSigningBodyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::TaikaiSegmentSigningManifestV1>(
        "iroha_data_model::taikai::TaikaiSegmentSigningManifestV1",
    );
}
