//! Immutable compiler-captured identities for this source owner’s existing codecs.

#[test]
fn captured_codec_schema_identities() {
    crate::captured_schema_tests::assert_bidirectional::<super::ComputeCodec>(
        "iroha_data_model::compute::ComputeCodec",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ComputePriceWeights>(
        "iroha_data_model::compute::ComputePriceWeights",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ComputePriceAmplifiers>(
        "iroha_data_model::compute::ComputePriceAmplifiers",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ComputeDeterminism>(
        "iroha_data_model::compute::ComputeDeterminism",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ComputeExecutionClass>(
        "iroha_data_model::compute::ComputeExecutionClass",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ComputeModelRef>(
        "iroha_data_model::compute::ComputeModelRef",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ComputeInputLimits>(
        "iroha_data_model::compute::ComputeInputLimits",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ComputeFeeSplit>(
        "iroha_data_model::compute::ComputeFeeSplit",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ComputeSponsorPolicy>(
        "iroha_data_model::compute::ComputeSponsorPolicy",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ComputePriceRiskClass>(
        "iroha_data_model::compute::ComputePriceRiskClass",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ComputePriceDeltaBounds>(
        "iroha_data_model::compute::ComputePriceDeltaBounds",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ComputeResourceBudget>(
        "iroha_data_model::compute::ComputeResourceBudget",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ComputeSandboxMode>(
        "iroha_data_model::compute::ComputeSandboxMode",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ComputeRandomnessPolicy>(
        "iroha_data_model::compute::ComputeRandomnessPolicy",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ComputeStorageAccess>(
        "iroha_data_model::compute::ComputeStorageAccess",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ComputeSandboxRules>(
        "iroha_data_model::compute::ComputeSandboxRules",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ComputeAuthPolicy>(
        "iroha_data_model::compute::ComputeAuthPolicy",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ComputeRouteId>(
        "iroha_data_model::compute::ComputeRouteId",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ComputeRoute>(
        "iroha_data_model::compute::ComputeRoute",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ComputeManifest>(
        "iroha_data_model::compute::ComputeManifest",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ComputeRequest>(
        "iroha_data_model::compute::ComputeRequest",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ComputeAuthn>(
        "iroha_data_model::compute::ComputeAuthn",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ComputeAuthz>(
        "iroha_data_model::compute::ComputeAuthz",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ComputeCall>(
        "iroha_data_model::compute::ComputeCall",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ComputeCallSummary>(
        "iroha_data_model::compute::ComputeCallSummary",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ComputeMetering>(
        "iroha_data_model::compute::ComputeMetering",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ComputeOutcomeKind>(
        "iroha_data_model::compute::ComputeOutcomeKind",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ComputeOutcome>(
        "iroha_data_model::compute::ComputeOutcome",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ComputeReceipt>(
        "iroha_data_model::compute::ComputeReceipt",
    );
}
