"""Canonical checker components and reviewed Rust source inventories.

The checker loads these declarations through its regular-file component loader.
The multilane gate parses the Rust inventories as data and authenticates their
canonical digest; this file must contain only literal inventory declarations.
"""

_CHECKER_COMPONENT_FILES = (
    "sumeragi_v2_proof_ledger_source_inventory.py",
    "sumeragi_v2_proof_ledger_async_contracts.py",
    "sumeragi_v2_proof_ledger_contract_types.py",
    "sumeragi_v2_proof_ledger_cross_tool_contracts.py",
    "sumeragi_v2_proof_ledger_proof_inventory.py",
    "sumeragi_v2_proof_ledger_serve_contracts.py",
    "sumeragi_v2_proof_ledger_historical_contracts.py",
    "sumeragi_v2_proof_ledger_quantitative_contracts.py",
    "sumeragi_v2_proof_ledger_exact_property_contracts.py",
    "sumeragi_v2_proof_ledger_supporting_theorem_contracts.py",
    "sumeragi_v2_proof_ledger_proof_token_contracts.py",
    "sumeragi_v2_proof_ledger_reviewed_rust_source_loader_contracts.py",
    "sumeragi_v2_proof_ledger_source_seal_contracts.py",
    "sumeragi_v2_proof_ledger_network_source_seal_contracts.py",
    "sumeragi_v2_proof_ledger_ingress_source_seal_contracts.py",
    "sumeragi_v2_proof_ledger_production_trace_contracts.py",
    "sumeragi_v2_proof_ledger_production_trace_evidence_contracts.py",
    "sumeragi_v2_proof_ledger_candidate_continuation_contracts.py",
    "sumeragi_v2_proof_ledger_serviced_candidate_contracts.py",
    "sumeragi_v2_proof_ledger_reply_writer_deadline_formal_contracts.py",
    "sumeragi_v2_proof_ledger_reply_writer_deadline_production_contracts.py",
    "sumeragi_v2_proof_ledger_merge_runtime_config_contracts.py",
    "sumeragi_v2_proof_ledger_shared_tlc_result_contracts.py",
    "sumeragi_v2_proof_ledger_locked_body_reproposal_contracts.py",
    "sumeragi_v2_proof_ledger_runtime_ingress_contracts.py",
    "sumeragi_v2_proof_ledger_direct_serve_contracts.py",
    "sumeragi_v2_proof_ledger_successor_production_recovery_contracts.py",
    "sumeragi_v2_proof_ledger_successor_production_contracts.py",
    "sumeragi_v2_proof_ledger_successor_recovery_contracts.py",
    "sumeragi_v2_proof_ledger_successor_recovery_lifecycle_contracts.py",
    "sumeragi_v2_proof_ledger_successor_recovery_source_contracts.py",
    "sumeragi_v2_proof_ledger_successor_recovery_support_contracts.py",
    "sumeragi_v2_proof_ledger_successor_recovery_tail_contracts.py",
    "sumeragi_v2_proof_ledger_chain_inventory_contracts.py",
    "sumeragi_v2_proof_ledger_release_inventory_contracts.py",
    "sumeragi_v2_proof_ledger_proof_architecture_contracts.py",
    "sumeragi_v2_proof_ledger_effect_capacity_tail_contracts.py",
    "sumeragi_v2_proof_ledger_effect_capacity_contracts.py",
    "sumeragi_v2_proof_ledger_leader_wire_contracts.py",
    "sumeragi_v2_proof_ledger_timeout_vote_episode_contracts.py",
    "sumeragi_v2_proof_ledger_terminal_discharge_contracts.py",
    "sumeragi_v2_proof_ledger_kura_native_amx_contracts.py",
)

_KURA_PRODUCTION_COMPONENT_FILES = (
    "kura/startup_finality_support.rs",
    "kura/bound_progress_and_retained_support.rs",
    "kura/autonomous_reservation_bounds.rs",
    "kura/certified_bundle_capacity_reservation_types.rs",
    "kura/index_resource_accounting.rs",
    "kura/evidence_resource_accounting.rs",
    "kura/storage_resource_accounting.rs",
    "kura/physical_resource_accounting.rs",
    "kura/physical_resource_guard.rs",
    "kura/canonical_physical_resource_accounting.rs",
    "kura/physical_resource_initialization.rs",
    "kura/resident_inventory_remaining_owners.rs",
    "kura/prune_commit_merge_support.rs",
    "kura/resident_inventory_owners.rs",
    "kura/merge_ledger_latest_execution_index.rs",
    "kura/replica_advert_and_body_status.rs",
    "kura/retired_pipeline_roster_rejection.rs",
    "kura/retained_finality_replica_authority.rs",
    "kura/queue_plan_admission_batch.rs",
    "kura/wsv_checkpoint_read_helpers.rs",
    "kura/durable_block_and_atomic_sidecar_io.rs",
    "kura/prune_intent_publication.rs",
    "kura/prune_recovery_capacity.rs",
    "kura/block_store_definition_and_test_controls.rs",
    "kura/startup_finality_session_reads.rs",
    "kura/pipeline_and_lane_artifacts.rs",
    "kura/canonical_autonomous_replica.rs",
    "kura/autonomous_terminal_capacity.rs",
    "kura/autonomous_publication_temp_recovery.rs",
    "kura/historical_autonomous_recovery_temp_reconciliation.rs",
    "kura/hot_path_capacity_preflight.rs",
    "kura/autonomous_execution_view_capacity.rs",
    "kura/certified_bundle_capacity.rs",
    "kura/lane_artifact_budget.rs",
    "kura/autonomous_lifecycle_terminal_outcomes.rs",
    "kura/autonomous_release_authority.rs",
    "kura/autonomous_retired_attempt.rs",
    "kura/autonomous_application_evidence.rs",
    "kura/sidecar_physical_resource_accounting.rs",
    "kura/indexed_sidecar_io.rs",
    "kura/consensus_storage_reads.rs",
    "kura/indexed_sidecar_rewrite.rs",
    "kura/lane_history_compaction.rs",
    "kura/prune_block_store_tail.rs",
    "kura/snapshot_finalization_resource_test_observation.rs",
    "kura/test_fault_injection_state.rs",
    "kura/test_fault_injection_controls.rs",
    "kura/file_error_support.rs",
)

_REVIEWED_RUST_INCLUDE_MANIFESTS = {
    'crates/iroha_core/src/block.rs': (
        'block/autonomous_merge_carrier_content_tests.rs',
        'block/exact_quorum_cardinality_tests.rs',
        'block/autonomous_anchor_network_tests.rs',
        'block/sccp_soracloud_validation_tests.rs',
        'block/canonical_genesis_validation_tests.rs',
        'block/genesis_validation_regression_tests.rs',
        'block/axt_shared_budget_across_envelopes_test.rs',
        'block/scheduler_variant_tests.rs',
        'block/validation_native_amx_test_support.rs',
        'block/native_amx_receipt_regression_tests.rs',
        'block/native_amx_exact_quorum_cardinality_tests.rs',
        'block/native_amx_and_dag_tests.rs',
        'block/sequential_rejected_pipeline_trigger_tests.rs',
        'block/tx_order_validation_revalidation_test.rs',
        'block/rejected_live_batch_fee_tests.rs',
        'block/fee_admission_tests.rs',
        'block/bootstrap_and_genesis_tests.rs',
    ),
    'crates/iroha_config/src/parameters/actual.rs': (
        'actual/torii_sccp_replay_archive.rs',
        'actual/torii_tx_history.rs',
        'actual/torii_http_transport.rs',
        'actual/torii_mcp_profile.rs',
        'actual/kagemusha.rs',
        'actual/tests.rs',
    ),
    'crates/iroha_config/src/parameters/actual/tests.rs': (
        'sora_profile_discovery_disabled_test.rs',
        'sora_profile_runtime_tests.rs',
    ),
    'crates/iroha_config/src/parameters/user.rs': (
        'user/kura.rs',
        'user_soranet_handshake_tests.rs',
        'user/torii_peer_geo.rs',
        'user/torii_soranet_privacy_ingest.rs',
        'user/torii_sccp_replay_archive.rs',
        'user/torii_tx_history.rs',
        'user/sorafs_moderation_query_bound_tests.rs',
        'user/governance_dag_head_mode_tests.rs',
        'user/zk_prover_report_retention_tests.rs',
        'user/zk_attachment_retention_tests.rs',
        'user/query_fanout_memory_tests.rs',
        'user/app_routed_read_body_timeout_tests.rs',
        'user/torii_api_connect_exactness_tests.rs',
        'user/operator_signature_body_timeout_tests.rs',
        'user/verified_source_ingress_tests.rs',
        'user/iso_bridge_store_memory_tests.rs',
        'user/kura_and_snapshot_tests.rs',
        'user/runtime_tail_tests.rs',
    ),
    'crates/iroha_data_model/src/block/consensus_v2.rs': (
        'consensus_v2/messages.rs',
        'consensus_v2_tests.rs',
    ),
    'crates/iroha_data_model/src/block/consensus_v2_tests.rs': (
        'consensus_v2_context_tests.rs',
        'consensus_v2_json_tests.rs',
    ),
    'crates/iroha_core/src/kura.rs': (
        *_KURA_PRODUCTION_COMPONENT_FILES,
        'kura/tests/resident_resource_inventory.rs',
        'kura/tests/resident_remaining_resource_inventory.rs',
        'kura/tests/00_bounded_sidecar_read_tests.rs',
        'kura/tests/01_support_snapshot_bootstrap_and_rewrite.rs',
        'kura/tests/01_prune_capacity_support.rs',
        'kura/tests/01a_retained_eviction_and_rewrite_tail.rs',
        'kura/tests/01b_retained_physical_resource_tests.rs',
        'kura/tests/01c_retained_resource_race_tests.rs',
        'kura/tests/02_replacement_and_preflight.rs',
        'kura/tests/02a_fresh_single_lane_preflight.rs',
        'kura/tests/03_preflight_and_merge_entry.rs',
        'kura/tests/03a_preflight_and_merge_entry_tail.rs',
        'kura/tests/04_merge_log_and_associations.rs',
        'kura/tests/04b_merge_artifact_budget.rs',
        'kura/tests/04c_canonical_association_capacity.rs',
        'kura/tests/04d_prune_intent_capacity.rs',
        'kura/tests/05_merge_resolution_and_eviction.rs',
        'kura/tests/05a_replica_advert_and_body_eviction.rs',
        'kura/tests/05b_canonical_physical_resource_tests.rs',
        'kura/tests/05c_canonical_stage_identity_tests.rs',
        'kura/tests/06_eviction_and_autonomous_lanes.rs',
        'kura/tests/07a_autonomous_reservation_reconciliation_support.rs',
        'kura/tests/07_autonomous_lanes_and_sidecars.rs',
        'kura/tests/07b_autonomous_reservation_reconciliation_tests.rs',
        'kura/tests/07c_lane_execution_sidecar_tests.rs',
        'kura/tests/07d_strict_lane_ownership_barrier_tests.rs',
        'kura/tests/07e_autonomous_lifecycle_and_canonical_artifact_tests.rs',
        'kura/tests/07e_autonomous_publication_temp_recovery_tests.rs',
        'kura/tests/07e_terminal_capacity_hardening_tests.rs',
        'kura/tests/07f_canonical_carrier_terminal_recovery_tests.rs',
        'kura/tests/07g_claim_capacity_preflight_tests.rs',
        'kura/tests/07h_autonomous_execution_view_capacity_tests.rs',
        'kura/tests/07i_historical_autonomous_batch_capacity_tests.rs',
        'kura/tests/07j_certified_bundle_capacity_tests.rs',
        'kura/tests/07k_historical_atomic_temp_recovery_tests.rs',
        'kura/tests/07l_pending_canonical_capacity_tests.rs',
        'kura/tests/07m_canonical_autonomous_replica_tests.rs',
        'kura/tests/08_lane_receipts_and_artifacts.rs',
        'kura/tests/08a_certified_lane_block_read_tests.rs',
        'kura/tests/08b_lane_history_compaction_capacity_tests.rs',
        'kura/tests/09_lane_artifacts_and_fastpq.rs',
        'kura/tests/10_native_amx_and_roster.rs',
        'kura/tests/10b_native_amx_prepublication_transition.rs',
        'kura/tests/11_roster_and_progress_sidecars.rs',
        'kura/tests/12_sidecar_index_and_pruning.rs',
        'kura/tests/13_manifests_and_fsync.rs',
        'kura/tests/14b_sidecar_physical_resource_tests.rs',
        'kura/tests/14c_authenticated_snapshot_resource_tests.rs',
        'kura/tests/14_resource_evidence.rs',
        'kura/tests/14a_physical_resource_guard_tests.rs',
        'kura/tests/14b_metadata_physical_resource_tests.rs',
        'kura/tests/15_remaining_physical_writer_tests.rs',
        'kura/tests/15a_merge_recovery_resource_failure_tests.rs',
        'kura/tests/16_resource_file_admission_tests.rs',
    ),
    'crates/iroha_core/src/kura/autonomous_application_evidence.rs': (
        'passive_diagnostic_reads.rs',
    ),
    'crates/iroha_core/src/kura/tests/10_native_amx_and_roster.rs': (
        '10c_native_amx_latest_index_support_and_bounds.rs',
    ),
    'crates/iroha_core/src/kura/pipeline_and_lane_artifacts.rs': (
        'autonomous_merge_bundle_support.rs',
        'autonomous_reservation_types.rs',
        'autonomous_reservation_inventory.rs',
        'autonomous_reservation_classifier.rs',
        'historical_autonomous_recovery.rs',
        'native_amx_participant_application_artifacts.rs',
    ),
    'crates/iroha_core/src/kura/lane_geometry.rs': (
        'lane_geometry/bootstrap_path_safety.rs',
        'lane_geometry/bootstrap_relabel.rs',
        'lane_geometry/catalog_validation.rs',
        'lane_geometry/retirement_bounds.rs',
        'lane_geometry_tests/00_support.rs',
        'lane_geometry/native_amx_retained_window_tests.rs',
        'lane_geometry_tests/00_retirement.rs',
        'lane_geometry_tests/01_retirement_and_recovery.rs',
        'lane_geometry_tests/02_geometry_moves_and_journal.rs',
        'lane_geometry_tests/03_gc_and_startup.rs',
        'lane_geometry_tests/04_physical_resource_accounting.rs',
    ),
    'crates/iroha_core/src/merge_sidecar.rs': (
        'merge_sidecar_signing_guard_tests.rs',
    ),
    'crates/iroha_core/src/queue.rs': (
        'queue/canonical_terminal_cleanup.rs',
        'queue/nexus_reconfigure_manifest_reload_tests.rs',
        'queue/privacy_governance_compliance_tests.rs',
        'queue/plan_journal_startup_atomicity_tests.rs',
        'queue/global_guard_claim_conflict_tests.rs',
        'queue/transaction_guard_return_tests.rs',
        'queue/queue_metadata_and_admission_tests.rs',
        'queue/instruction_and_state_routing_tests.rs',
        'queue/kagemusha_top_up_admission_tests.rs',
        'queue/routing_batch_admission_tests.rs',
        'queue/config_factory_test_support.rs',
        'queue/teu_limit_and_backlog_tests.rs',
        'queue/routing_projection_resilience_tests.rs',
        'queue/capacity_and_concurrency_tests.rs',
        'queue/pressure_resync_tests.rs',
        'queue/expiry_tracking_tests.rs',
        'queue/inflight_tracking_tests.rs',
        'queue/lane_reservation_tests.rs',
        'queue/lane_reservation_terminal_fault_tests.rs',
        'queue/reservation_recovery_tests.rs',
    ),
    'crates/iroha_core/src/queue/instruction_and_state_routing_tests.rs': (
        'gossip_routing_metadata_tests.rs',
        'gossip_route_validation_tests.rs',
        'drain_revalidation_tests.rs',
    ),
    'crates/iroha_core/src/queue/lane_reservation_tests.rs': (
        'lane_reservation_core_tests.rs',
    ),
    'crates/iroha_core/src/queue/reservation_recovery_tests.rs': (
        'retired_release_snapshot_recovery_tests.rs',
        'native_amx_reservation_tests.rs',
    ),
    'crates/iroha_core/src/queue/journal.rs': (
        'journal_reservation_commit_preflight.rs',
        'journal_direct_file_io.rs',
        'plan_journal_bounds_tests.rs',
        'plan_journal_replay_tests.rs',
    ),
    'crates/iroha_core/src/smartcontracts/ivm/host.rs': (
        'host/axt_persistent_budget_tests.rs',
        'host/axt_unanchored_admission_tests.rs',
        'host/core_codec_and_contract_tests.rs',
        'host/core_query_execution_tests.rs',
        'host/core_query_pagination_tests.rs',
        'host/nested_contract_state_and_rollback_tests.rs',
        'host/zk_verification_tests.rs',
        'host/prepared_public_arguments_tests.rs',
        'host/pointer_abi_validation_tests.rs',
        'host/pointer_abi_and_sm_tests.rs',
    ),
    'crates/iroha_core/src/state.rs': (
        'state/vpn_lease_validation.rs',
        'state/axt_handle_budget.rs',
        'state/zk_asset_state.rs',
        'state/restored_staking_owner_tests.rs',
        'state/confidential_policy_transition_index_tests.rs',
        'state/passive_lane_diagnostic_methods.rs',
        'state/runtime_configuration.rs',
        'state/lane_lifecycle_support.rs',
        'state/diagnostic_state_generation.rs',
        'state/autonomous_predecessor_application.rs',
        'state/state_commit_lock_order_tests.rs',
        'state/transfer_transcript_tests.rs',
        'state/block_proof_tests.rs',
        'state/range_bounds.rs',
        'state/deserialize_core.rs',
        'state/deserialize_world.rs',
        'state/default_oracle.rs',
    ),
    'crates/iroha_core/src/snapshot.rs': (
        'snapshot/support_policy_tests.rs',
        'snapshot/write_roundtrip_tests.rs',
        'snapshot/reconciliation_generation_tests.rs',
    ),
    'crates/iroha_core/src/sumeragi/evidence.rs': (
        'evidence/missing_signer_pop_test.rs',
    ),
    'crates/iroha_core/src/sumeragi/serviced_candidate_store.rs': (
        'serviced_candidate_store_cases.rs',
    ),
    'crates/iroha_core/src/sumeragi/serviced_candidate_store_cases.rs': (
        'serviced_candidate_store/body_terminal_recovery_tests.rs',
        'serviced_candidate_store_tail_tests.rs',
    ),
    'crates/iroha_p2p/src/network.rs': (
        'network/admission.rs',
        'network/best_effort_admission.rs',
        'network/reliable_actor.rs',
        'network/handle_update_tests.rs',
        'network/queue_depth_tests.rs',
    ),
    'crates/iroha_p2p/src/peer.rs': (
        'peer_handshake_config_tests.rs',
        'peer_state_tests.rs',
        'peer_consensus_mode_test.rs',
        'peer_tests.rs',
    ),
    'crates/irohad/src/main.rs': (
        'main/shared_sorafs_provider_cache_tests.rs',
        'main/runtime_deps.rs',
        'sumeragi_lane_relay_item.rs',
        'main/online_peers_provider.rs',
        'main/resolved_genesis_trust_anchor_wrong_hash_test.rs',
        'main_tests/governance_dag_publisher_binding_signer.rs',
        'main/runtime_dependency_contract_tests.rs',
        'main/governance_dag_launcher_tests.rs',
        'main/runtime_budget_and_config_tests.rs',
        'main/startup_tail_tests.rs',
    ),
    'crates/iroha_core/src/sumeragi/mod.rs': (
        'fair_v2_ingress_leader_wire_identity.rs',
        'fair_v2_ingress_selector.rs',
        'tests/queue_plan_admission_handoff.rs',
        'tests/mod_authoritative_runtime_gate_01_support.rs',
        'tests/mod_authoritative_runtime_gate_02_carrierless_replay.rs',
        'tests/mod_authoritative_runtime_gate_03_admission_and_fairness.rs',
        'tests/mod_authoritative_runtime_gate_04_routes_and_dequeue.rs',
        'tests/mod_authoritative_runtime_gate_05_ownership_maintenance.rs',
        'tests/mod_authoritative_runtime_gate_06_source_isolation.rs',
        'tests/mod_authoritative_runtime_gate_07_wire_bounds.rs',
        'tests/mod_authoritative_runtime_gate_08_capacity_and_control.rs',
        'tests/mod_authoritative_runtime_gate_09_checked_dequeue.rs',
        'tests/mod_authoritative_runtime_gate_09_snapshot_and_source_lanes.rs',
    ),
    'crates/iroha_core/src/sumeragi/status.rs': (
        'status/test_guards.rs',
    ),
    'crates/iroha_core/src/sumeragi/v2.rs': (
        'v2_adapter_persistence_and_wal_types.rs',
        'v2_recovered_decision_validate_adapter_startup.rs',
        'v2_authenticated_recovered_adapter_startup_impl.rs',
        'v2_verified_height_context_recovered_output_auth.rs',
        'v2_adapter_equivocation_evidence.rs',
        'v2_ready_durable_validate_adapter_preview.rs',
        'v2_recovered_lifecycle_sign_completion.rs',
        'v2_wire_registry_and_authentication.rs',
        'tests/v2_adapter_leader_wire_consumer.rs',
        'tests/v2_adapter_main_00.rs',
        'tests/v2_adapter_main_01.rs',
        'tests/v2_adapter_main_02.rs',
        'tests/v2_adapter_main_03.rs',
        'tests/v2_adapter_main_04.rs',
    ),
    'crates/iroha_core/src/sumeragi/v2_recovery.rs': (
        'v2_recovery_tests.rs',
    ),
    'crates/iroha_core/src/sumeragi/v2_lifecycle_coordinator.rs': (
        'v2_lifecycle_coordinator_state_helpers.rs',
        'tests/v2_lifecycle_coordinator_explorer_cases.rs',
    ),
    'crates/iroha_core/src/sumeragi/v2_lifecycle_launch.rs': (
        'v2_lifecycle_launch_tests.rs',
    ),
    'crates/iroha_core/src/sumeragi/v2_lifecycle_launch_tests.rs': (
        'v2_lifecycle_launch_ready_proposal_sign_test_fixtures.rs',
        'v2_lifecycle_launch_pending_kura_source_tests.rs',
        'v2_lifecycle_launch_recovered_sign_settlement_source_tests.rs',
        'v2_lifecycle_launch_recovered_fetch_source_tests.rs',
        'v2_lifecycle_launch_certified_response_retry_source_tests.rs',
        'v2_lifecycle_launch_recovered_fetch_settlement_source_tests.rs',
    ),
    'crates/iroha_core/src/sumeragi/v2_lifecycle_ledger.rs': (
        'v2_lifecycle_ledger_operations.rs',
        'v2_lifecycle_ledger_store.rs',
        'v2_lifecycle_ledger_tests.rs',
    ),
    'crates/iroha_core/src/sumeragi/v2_lifecycle_ledger_tests.rs': (
        'v2_lifecycle_ledger_tests_durable_recovery_01.rs',
        'v2_lifecycle_ledger_tests_durable_recovery_02.rs',
        'v2_lifecycle_ledger_tests_frame_and_store.rs',
    ),
    'crates/iroha_core/src/sumeragi/v2_lifecycle_projection.rs': (
        'tests/v2_lifecycle_projection_cases.rs',
    ),
    'crates/iroha_core/src/sumeragi/v2_lifecycle_scheduler_inputs.rs': (
        'tests/v2_lifecycle_scheduler_completion_cases.rs',
        'tests/v2_lifecycle_scheduler_certified_serve_cases.rs',
    ),
    'crates/iroha_core/src/sumeragi/v2_lifecycle_replay_authority.rs': (
        'v2_lifecycle_replay_authority_recovered_decision_validate.rs',
        'v2_lifecycle_replay_authority_live_wal.rs',
        'v2_lifecycle_replay_authority_certified_serve.rs',
        'v2_lifecycle_replay_authority_certified_body.rs',
        'v2_lifecycle_replay_authority_payload_projection.rs',
        'v2_lifecycle_replay_authority_output_recovery.rs',
        'tests/v2_lifecycle_replay_authority_fixtures.rs',
        'tests/v2_lifecycle_replay_authority_cases.rs',
    ),
    'crates/iroha_core/src/sumeragi/v2_lifecycle_work_registry_validate_recovery.rs': (
        'v2_lifecycle_work_registry_validate_recovery_registry_impl.rs',
        'v2_lifecycle_work_registry_validate_recovery_parent.rs',
    ),
    'crates/iroha_core/src/sumeragi/v2_lifecycle_work_registry_validate_recovery_registry_impl.rs': (
        'v2_lifecycle_work_registry_validate_recovery_census_impl.rs',
        'v2_lifecycle_work_registry_validate_recovery_registry_tail_impl.rs',
        'v2_lifecycle_work_registry_validate_completion_impl.rs',
        'v2_lifecycle_work_registry_access_impl.rs',
        'v2_lifecycle_work_registry_validate_recovery_execution_impl.rs',
    ),
    'crates/iroha_core/src/sumeragi/v2_lifecycle_work_registry.rs': (
        'v2_lifecycle_work_registry_body_validate_carriers.rs',
        'v2_lifecycle_work_registry_pre_admission.rs',
        'v2_lifecycle_work_registry_live_wal_sign.rs',
        'v2_lifecycle_work_registry_output.rs',
        'v2_lifecycle_work_registry_live_validate_children.rs',
        'v2_lifecycle_work_registry_recovered_wal.rs',
        'v2_lifecycle_work_registry_validate_recovery.rs',
        'v2_lifecycle_work_registry_validate_execution.rs',
        'v2_lifecycle_work_registry_validate_sidecar.rs',
        'v2_lifecycle_work_registry_body_retirement.rs',
        'tests/v2_lifecycle_work_registry_00.rs',
        'tests/v2_lifecycle_work_registry_01.rs',
        'tests/v2_lifecycle_work_registry_02.rs',
        'tests/v2_lifecycle_work_registry_validate_dispatch_cases.rs',
        'tests/v2_lifecycle_work_registry_validate_dispatch_execution_cases.rs',
        'tests/v2_lifecycle_work_registry_validate_sidecar_cases.rs',
        'tests/v2_lifecycle_work_registry_durable_store_and_validate_cases.rs',
        'tests/v2_lifecycle_work_registry_exact_registry_cases.rs',
        'tests/v2_lifecycle_work_registry_recovery_surface_cases.rs',
        'tests/v2_lifecycle_work_registry_replay_evidence_cases.rs',
    ),
    'crates/iroha_core/src/sumeragi/tests/v2_lifecycle_work_registry_validate_dispatch_execution_cases.rs': (
        'v2_lifecycle_work_registry_validate_apply_cases.rs',
        'v2_lifecycle_work_registry_validate_completion_cases.rs',
    ),
    'crates/iroha_core/src/sumeragi/v2_lifecycle_work_registry_recovered_wal.rs': (
        'v2_lifecycle_work_registry_recovered_wal_persisted_ledger_impl.rs',
    ),
    'crates/iroha_core/src/sumeragi/v2_runtime.rs': (
        'v2_runtime_lifecycle_ordinal_source.rs',
        'v2_runtime_durable_recovery_pending.rs',
        'v2_runtime_effect_ownership_core_impl.rs',
        'v2_runtime_effect_ownership_rebind_impl.rs',
        'v2_runtime_ready_validate_publication.rs',
        'v2_runtime/network_ingress_classification.rs',
        'tests/v2_runtime_pending_binding_cases.rs',
        'tests/v2_runtime_main_00.rs',
        'tests/v2_runtime_main_01.rs',
        'tests/v2_runtime_main_02.rs',
        'tests/v2_runtime_main_03.rs',
        'tests/v2_runtime_main_04.rs',
        'tests/v2_runtime_main_05.rs',
        'tests/v2_runtime_main_06.rs',
        'tests/v2_runtime_unsealed_01b_lifecycle_bounds.rs',
        'tests/v2_runtime_unsealed_02_owner_retirement_and_fairness.rs',
    ),
    'crates/iroha_core/src/sumeragi/v2_worker.rs': (
        'v2_worker_completion.rs',
        'v2_worker_io_execution.rs',
        'v2_worker_exact_output.rs',
        'v2_worker_services.rs',
        'v2_worker_services_impl.rs',
        'tests/v2_worker_main_00.rs',
        'tests/v2_worker_main_01.rs',
        'tests/v2_worker_lifecycle_capacity_cases.rs',
        'tests/v2_worker_equivocation_fixture.rs',
        'v2_worker/applied_height_handoff_tests.rs',
        'v2_worker/queue_plan_admission_handoff_tests.rs',
        'v2_worker/upstream_reply_route_test.rs',
        'tests/v2_worker_main_02.rs',
        'tests/v2_worker_main_04.rs',
        'tests/v2_worker_main_05.rs',
    ),
    'crates/iroha_core/src/sumeragi/v2_worker_io_execution.rs': (
        'v2_worker/exact_output_rollover_claim.rs',
        'v2_worker/queue_plan_admission_handoff.rs',
        'v2_worker/exact_output_pending_state.rs',
    ),
    'crates/iroha_core/src/sumeragi/v2_worker_exact_output.rs': (
        'v2_worker/autonomous_lane_output_reconstruction.rs',
        'v2_worker/kura_replica_advert_refresh.rs',
    ),
    'crates/iroha_core/src/sumeragi/v2_worker_services_impl.rs': (
        'v2_worker/pending_kura_apply_io_snapshot.rs',
        'v2_worker/current_lane_output_rollover_claim.rs',
        'v2_worker/production_services_drop_impl.rs',
        'v2_worker/effect_services_impl.rs',
    ),
    'crates/iroha_core/src/sumeragi/v2_runner.rs': (
        'v2_runner/lifecycle_terminal_recovery.rs',
        'v2_runner/decided_lane_recovery.rs',
        'v2_runner/outer_ingress_cursor.rs',
        'v2_runner/finalized_output_rollover.rs',
        'v2_runner/canonical_recovery_ingress.rs',
        'v2_runner/reply_route_retention.rs',
        'v2_runner/merge_sidecar_recovery.rs',
    ),
    'crates/iroha_core/src/sumeragi/v2_runner_tests.rs': (
        'tests/v2_runner_unsealed_00.rs',
        'tests/v2_runner_unsealed_01.rs',
        'tests/v2_runner_unsealed_02.rs',
        'tests/v2_runner_upstream_recovery.rs',
        'tests/v2_runner_lifecycle_startup_order.rs',
    ),
    'crates/iroha_core/src/sumeragi/v2_apply.rs': (
        'v2_apply/autonomous_recovery_types.rs',
        'v2_apply/historical_autonomous_recovery.rs',
        'v2_apply/reconciliation_authority.rs',
        'v2_apply/committed_carrier_cleanup.rs',
        'v2_apply/error_recovery.rs',
    ),
    'crates/iroha_core/src/sumeragi/v2_core/reducer.rs': (
        'reducer/prepare_certificate_handling.rs',
        'tests/reducer_timeout_and_projection.rs',
        'tests/v2_core_reducer_primitive_projection.rs',
        'reducer/counterfeit_boundary_capability_test.rs',
    ),
    'crates/iroha_core/src/sumeragi/v2_core/refinement.rs': (
        'refinement/leader_wire_admission_trace_projection.rs',
        'refinement/first_release_witness.rs',
        'refinement/volatile_summary_well_formed.rs',
        'refinement/post_carrier_transition.rs',
        'refinement_constructor_test_helpers.rs',
        'refinement/transition_gate_tail.rs',
    ),
    'crates/iroha_core/src/sumeragi/v2_core/refinement_cases.rs': (
        'refinement_cases/effect_candidate.rs',
        'refinement_cases/terminal_body_pipeline.rs',
    ),
    'crates/iroha_core/src/sumeragi/v2_core/tests.rs': (
        'tests/committee_fallback_and_retransmit.rs',
        'tests/v2_core_view_zero_parent_binding.rs',
        'tests/empty_replay_resume_test.rs',
        'tests/delayed_prepare_qc_cache_bounds.rs',
        'tests/v2_core_terminal_transactionality.rs',
    ),
    'crates/iroha_core/src/sumeragi/v2_effects.rs': (
        'v2_effects_recovered_fetch_and_pipeline_types.rs',
        'v2_effects_recovered_lifecycle_output_service.rs',
        'v2_effects_lifecycle_admission_settlement.rs',
        'v2_effects_body_retirement.rs',
        'v2_effects_runner_decision_cleanup_plan.rs',
        'v2_effects_test_consumer_wrappers.rs',
        'tests/v2_effects_main_00.rs',
        'tests/v2_effects_main_01.rs',
        'tests/v2_effects_main_02.rs',
        'tests/v2_effects_main_03.rs',
        'tests/v2_effects_main_04.rs',
        'tests/v2_effects_main_05.rs',
        'tests/v2_effects_03_locked_body_and_sidecar.rs',
        'tests/v2_effects_certified_body_fence_supersession.rs',
    ),
    'crates/iroha_core/src/sumeragi/v2_lane_work.rs': (
        'v2_lane_work/canonical_executed_block_application_repair.rs',
        'v2_lane_work/queue_plan_admission_handoff.rs',
        'v2_lane_work/signing_authority_tests.rs',
        'v2_lane_work/native_amx_signing_guard_capacity_boundary_test.rs',
        'v2_lane_work/typed_finality_handoff_tests.rs',
        'v2_lane_work/terminal_retirement_journal_failure_test.rs',
        'tests/v2_lane_work_native_signing_guard.rs',
        'v2_lane_work/native_amx_route_and_receipt_tests.rs',
        'tests/v2_lane_work_observer_role.rs',
        'tests/v2_lane_work_native_body_recovery.rs',
        'tests/v2_lane_work_lifecycle_and_recovery_cases.rs',
        'v2_lane_work/strict_historical_read_tests.rs',
        'v2_lane_work/strict_volatile_owner_tests.rs',
        'v2_lane_work/strict_receipt_gate_tests.rs',
        'v2_lane_work/canonical_executed_block_recovery_drift_test.rs',
        'v2_lane_work/historical_recovery_and_carrier_tests.rs',
        'v2_lane_work_autonomous_ready_durability_tests.rs',
        'v2_lane_work/autonomous_retirement_and_merge_tests.rs',
        'v2_lane_work/queue_plan_admission_handoff_tests.rs',
    ),
    'crates/iroha_core/src/sumeragi/tests/v2_lane_work_lifecycle_and_recovery_cases.rs': (
        'v2_lane_work_effect_queue.rs',
    ),
    'integration_tests/tests/sumeragi_v2_runner.rs': (
        'sumeragi_v2_runner/prepare_qc_split_tests.rs',
        'sumeragi_v2_runner/status_validation_helpers.rs',
        'sumeragi_v2_runner/status_set_validation.rs',
    ),
    'integration_tests/tests/sumeragi_v2_runner/prepare_qc_split_tests.rs': (
        'restart_timing_test.rs',
    ),
    'crates/iroha_sumeragi_core/src/verus_proofs.rs': (
        'verus_proofs/production_transition_contracts.rs',
        'verus_proofs/in_flight_first_release_proofs.rs',
        'verus_proofs/production_kernel_tail.rs',
    ),
    'crates/iroha_core/src/sumeragi/tests/v2_adapter_main_00.rs': (
        'v2_adapter_activation_context.rs',
    ),
    'crates/iroha_core/src/sumeragi/tests/v2_adapter_main_03.rs': (
        'v2_adapter_04_wal_recovery.rs',
        'v2_adapter_04b_lifecycle_startup.rs',
        'v2_adapter_05_direct_lifecycle.rs',
    ),
    'crates/iroha_core/src/sumeragi/tests/v2_adapter_05_direct_lifecycle.rs': (
        'v2_adapter_05_direct_lifecycle_recovered_wal_seal_case.rs',
    ),
    'crates/iroha_core/src/sumeragi/tests/v2_adapter_04_wal_recovery.rs': (
        'v2_adapter_04_wal_recovery_decision_classifier_cases.rs',
    ),
    'crates/iroha_core/src/sumeragi/tests/v2_adapter_04b_lifecycle_startup.rs': (
        'v2_adapter_04b_lifecycle_startup_tail.rs',
    ),
    'crates/iroha_core/src/sumeragi/tests/v2_adapter_main_04.rs': (
        'v2_adapter_01_replay_and_registry.rs',
        'v2_adapter_02_view_and_lock_progress.rs',
        'v2_adapter_03_tc_and_terminal_ingress.rs',
    ),
    'crates/iroha_core/src/sumeragi/tests/v2_worker_main_01.rs': (
        'v2_worker_reply_route_cases.rs',
        'v2_worker_backpressure_cases.rs',
        'v2_worker_recovered_lifecycle_output_cases.rs',
        'v2_worker_nonzero_view_restart.rs',
    ),
    'crates/iroha_core/src/sumeragi/tests/v2_worker_backpressure_cases.rs': (
        'v2_worker_backpressure_retirement_cases.rs',
    ),
    'crates/iroha_core/src/sumeragi/tests/v2_effects_main_05.rs': (
        'v2_effects_kura_tip_replay.rs',
        'v2_effects_01_view_churn_and_runtime_steps.rs',
        'v2_effects_highest_prepare_retention.rs',
        'v2_effects_02_admission_handoffs.rs',
    ),
}
