#!/bin/bash
set -euo pipefail

mode="${1:-fast}"
root_dir="$(cd "$(dirname "$0")/../.." && pwd)"
spec_dir="$root_dir/docs/formal/sumeragi"
apalache_version="${APALACHE_VERSION:-0.52.2}"
default_local_apalache_bin="$root_dir/target/apalache/toolchains/v${apalache_version}/bin/apalache-mc"
if [[ -n "${APALACHE_BIN:-}" ]]; then
  apalache_bin="$APALACHE_BIN"
elif [[ -x "$default_local_apalache_bin" ]]; then
  apalache_bin="$default_local_apalache_bin"
else
  apalache_bin="apalache-mc"
fi
apalache_docker_image="${APALACHE_DOCKER_IMAGE:-ghcr.io/apalache-mc/apalache:${apalache_version}}"
allow_docker_fallback="${APALACHE_ALLOW_DOCKER:-1}"
expect_failure=0

case "$mode" in
  fast)
    spec_file="$spec_dir/Sumeragi.tla"
    cfg_file="$spec_dir/Sumeragi_fast.cfg"
    apalache_length=10
    ;;
  deep)
    spec_file="$spec_dir/Sumeragi.tla"
    cfg_file="$spec_dir/Sumeragi_deep.cfg"
    apalache_length=10
    ;;
  fork-fast)
    spec_file="$spec_dir/SumeragiForkSafety.tla"
    cfg_file="$spec_dir/SumeragiForkSafety_fast.cfg"
    apalache_length=9
    ;;
  fork-npos)
    spec_file="$spec_dir/SumeragiForkSafety.tla"
    cfg_file="$spec_dir/SumeragiForkSafety_npos.cfg"
    apalache_length=9
    ;;
  quorum-fast)
    spec_file="$spec_dir/SumeragiQuorumPolicy.tla"
    cfg_file="$spec_dir/SumeragiQuorumPolicy_fast.cfg"
    apalache_length=2
    ;;
  rbc-fast)
    spec_file="$spec_dir/SumeragiRbcDeliverQuorum.tla"
    cfg_file="$spec_dir/SumeragiRbcDeliverQuorum_fast.cfg"
    apalache_length=2
    ;;
  qc-signers-fast)
    spec_file="$spec_dir/SumeragiQcSignerBitmap.tla"
    cfg_file="$spec_dir/SumeragiQcSignerBitmap_fast.cfg"
    apalache_length=2
    ;;
  commit-roots-fast)
    spec_file="$spec_dir/SumeragiCommitRootConsistency.tla"
    cfg_file="$spec_dir/SumeragiCommitRootConsistency_fast.cfg"
    apalache_length=2
    ;;
  commit-pipeline-recovery-fast)
    spec_file="$spec_dir/SumeragiCommitPipelineRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiCommitPipelineRecoveryGate_fast.cfg"
    apalache_length=2
    ;;
  commit-evidence-replay-fast)
    spec_file="$spec_dir/SumeragiCommitEvidenceReplayGate.tla"
    cfg_file="$spec_dir/SumeragiCommitEvidenceReplayGate_fast.cfg"
    apalache_length=2
    ;;
  block-sync-recovery-fast)
    spec_file="$spec_dir/SumeragiBlockSyncRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiBlockSyncRecoveryGate_fast.cfg"
    apalache_length=2
    ;;
  native-amx-attestation-fast)
    spec_file="$spec_dir/SumeragiNativeAmxAttestationGate.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxAttestationGate_fast.cfg"
    apalache_length=2
    ;;
  native-amx-journal-fast)
    spec_file="$spec_dir/SumeragiNativeAmxJournalReplay.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxJournalReplay_fast.cfg"
    apalache_length=1
    ;;
  precommit-fast)
    spec_file="$spec_dir/SumeragiPrecommitVoteGate.tla"
    cfg_file="$spec_dir/SumeragiPrecommitVoteGate_fast.cfg"
    apalache_length=2
    ;;
  proposal-fast)
    spec_file="$spec_dir/SumeragiProposalAssemblyGate.tla"
    cfg_file="$spec_dir/SumeragiProposalAssemblyGate_fast.cfg"
    apalache_length=2
    ;;
  engine-tick-fast)
    spec_file="$spec_dir/SumeragiEngineTickGate.tla"
    cfg_file="$spec_dir/SumeragiEngineTickGate_fast.cfg"
    apalache_length=2
    ;;
  engine-new-view-fast)
    spec_file="$spec_dir/SumeragiEngineNewViewQcGate.tla"
    cfg_file="$spec_dir/SumeragiEngineNewViewQcGate_fast.cfg"
    apalache_length=2
    ;;
  engine-proposal-fast)
    spec_file="$spec_dir/SumeragiEngineProposalGate.tla"
    cfg_file="$spec_dir/SumeragiEngineProposalGate_fast.cfg"
    apalache_length=2
    ;;
  engine-prepare-fast)
    spec_file="$spec_dir/SumeragiEnginePrepareQcGate.tla"
    cfg_file="$spec_dir/SumeragiEnginePrepareQcGate_fast.cfg"
    apalache_length=2
    ;;
  engine-commit-fast)
    spec_file="$spec_dir/SumeragiEngineCommitQcGate.tla"
    cfg_file="$spec_dir/SumeragiEngineCommitQcGate_fast.cfg"
    apalache_length=2
    ;;
  engine-committed-block-fast)
    spec_file="$spec_dir/SumeragiEngineCommittedBlockGate.tla"
    cfg_file="$spec_dir/SumeragiEngineCommittedBlockGate_fast.cfg"
    apalache_length=2
    ;;
  engine-payload-fast)
    spec_file="$spec_dir/SumeragiEnginePayloadAvailabilityGate.tla"
    cfg_file="$spec_dir/SumeragiEnginePayloadAvailabilityGate_fast.cfg"
    apalache_length=2
    ;;
  engine-validation-result-fast)
    spec_file="$spec_dir/SumeragiEngineValidationResultGate.tla"
    cfg_file="$spec_dir/SumeragiEngineValidationResultGate_fast.cfg"
    apalache_length=2
    ;;
  reconfig-fast)
    spec_file="$spec_dir/SumeragiValidatorSetTransition.tla"
    cfg_file="$spec_dir/SumeragiValidatorSetTransition_fast.cfg"
    apalache_length=7
    ;;
  recovery-fast)
    spec_file="$spec_dir/SumeragiCertifiedRecovery.tla"
    cfg_file="$spec_dir/SumeragiCertifiedRecovery_fast.cfg"
    apalache_length=7
    ;;
  view-change-fast)
    spec_file="$spec_dir/SumeragiViewChangeSafety.tla"
    cfg_file="$spec_dir/SumeragiViewChangeSafety_fast.cfg"
    apalache_length=6
    ;;
  validation-fast)
    spec_file="$spec_dir/SumeragiValidationGate.tla"
    cfg_file="$spec_dir/SumeragiValidationGate_fast.cfg"
    apalache_length=6
    ;;
  admission-fast)
    spec_file="$spec_dir/SumeragiCertificateAdmission.tla"
    cfg_file="$spec_dir/SumeragiCertificateAdmission_fast.cfg"
    apalache_length=6
    ;;
  highest-fast)
    spec_file="$spec_dir/SumeragiHighestQcSelection.tla"
    cfg_file="$spec_dir/SumeragiHighestQcSelection_fast.cfg"
    apalache_length=6
    ;;
  frontier-fast)
    spec_file="$spec_dir/SumeragiFrontierRecovery.tla"
    cfg_file="$spec_dir/SumeragiFrontierRecovery_fast.cfg"
    apalache_length=7
    ;;
  frontier-deep)
    spec_file="$spec_dir/SumeragiFrontierRecovery.tla"
    cfg_file="$spec_dir/SumeragiFrontierRecovery_deep.cfg"
    apalache_length=8
    ;;
  frontier-wide)
    spec_file="$spec_dir/SumeragiFrontierRecovery.tla"
    cfg_file="$spec_dir/SumeragiFrontierRecovery_wide.cfg"
    apalache_length=7
    ;;
  frontier-nightly)
    spec_file="$spec_dir/SumeragiFrontierRecovery.tla"
    cfg_file="$spec_dir/SumeragiFrontierRecovery_wide.cfg"
    apalache_length=10
    ;;
  frontier-bug-stale-owner)
    spec_file="$spec_dir/SumeragiFrontierRecovery.tla"
    cfg_file="$spec_dir/SumeragiFrontierRecovery_bug_stale_owner.cfg"
    apalache_length=4
    expect_failure=1
    ;;
  frontier-bug-vote-queue)
    spec_file="$spec_dir/SumeragiFrontierRecovery.tla"
    cfg_file="$spec_dir/SumeragiFrontierRecovery_bug_vote_queue.cfg"
    apalache_length=4
    expect_failure=1
    ;;
  frontier-bug-payload-recovery)
    spec_file="$spec_dir/SumeragiFrontierRecovery.tla"
    cfg_file="$spec_dir/SumeragiFrontierRecovery_bug_payload_recovery.cfg"
    apalache_length=4
    expect_failure=1
    ;;
  frontier-bug-retransmit-followthrough)
    spec_file="$spec_dir/SumeragiFrontierRecovery.tla"
    cfg_file="$spec_dir/SumeragiFrontierRecovery_bug_retransmit_followthrough.cfg"
    apalache_length=6
    expect_failure=1
    ;;
  frontier-bug-future-promotion)
    spec_file="$spec_dir/SumeragiFrontierRecovery.tla"
    cfg_file="$spec_dir/SumeragiFrontierRecovery_bug_future_promotion.cfg"
    apalache_length=5
    expect_failure=1
    ;;
  frontier-bug-future-reanchor-clear)
    spec_file="$spec_dir/SumeragiFrontierRecovery.tla"
    cfg_file="$spec_dir/SumeragiFrontierRecovery_bug_future_reanchor_clear.cfg"
    apalache_length=5
    expect_failure=1
    ;;
  frontier-bug-future-evidence-drop)
    spec_file="$spec_dir/SumeragiFrontierRecovery.tla"
    cfg_file="$spec_dir/SumeragiFrontierRecovery_bug_future_evidence_drop.cfg"
    apalache_length=3
    expect_failure=1
    ;;
  frontier-bug-promotion-reset)
    spec_file="$spec_dir/SumeragiFrontierRecovery.tla"
    cfg_file="$spec_dir/SumeragiFrontierRecovery_bug_promotion_reset.cfg"
    apalache_length=7
    expect_failure=1
    ;;
  frontier-bug-future-stale-owner)
    spec_file="$spec_dir/SumeragiFrontierRecovery.tla"
    cfg_file="$spec_dir/SumeragiFrontierRecovery_bug_future_stale_owner.cfg"
    apalache_length=5
    expect_failure=1
    ;;
  frontier-bug-progress-touch)
    spec_file="$spec_dir/SumeragiFrontierRecovery.tla"
    cfg_file="$spec_dir/SumeragiFrontierRecovery_bug_progress_touch.cfg"
    apalache_length=3
    expect_failure=1
    ;;
  frontier-bug-height-only-recovery)
    spec_file="$spec_dir/SumeragiFrontierRecovery.tla"
    cfg_file="$spec_dir/SumeragiFrontierRecovery_bug_height_only_recovery.cfg"
    apalache_length=3
    expect_failure=1
    ;;
  fork-bug-double-sign)
    spec_file="$spec_dir/SumeragiForkSafety.tla"
    cfg_file="$spec_dir/SumeragiForkSafety_bug_double_sign.cfg"
    apalache_length=9
    expect_failure=1
    ;;
  quorum-bug-count-under-threshold)
    spec_file="$spec_dir/SumeragiQuorumPolicy.tla"
    cfg_file="$spec_dir/SumeragiQuorumPolicy_bug_count_under_threshold.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  quorum-bug-count-over-validators)
    spec_file="$spec_dir/SumeragiQuorumPolicy.tla"
    cfg_file="$spec_dir/SumeragiQuorumPolicy_bug_count_over_validators.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  quorum-bug-stake-exact-two-thirds)
    spec_file="$spec_dir/SumeragiQuorumPolicy.tla"
    cfg_file="$spec_dir/SumeragiQuorumPolicy_bug_stake_exact_two_thirds.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  quorum-bug-stake-over-total)
    spec_file="$spec_dir/SumeragiQuorumPolicy.tla"
    cfg_file="$spec_dir/SumeragiQuorumPolicy_bug_stake_over_total.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  quorum-bug-stake-invalid-input)
    spec_file="$spec_dir/SumeragiQuorumPolicy.tla"
    cfg_file="$spec_dir/SumeragiQuorumPolicy_bug_stake_invalid_input.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  quorum-bug-stake-overflow)
    spec_file="$spec_dir/SumeragiQuorumPolicy.tla"
    cfg_file="$spec_dir/SumeragiQuorumPolicy_bug_stake_overflow.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  reconfig-bug-premature-activation)
    spec_file="$spec_dir/SumeragiValidatorSetTransition.tla"
    cfg_file="$spec_dir/SumeragiValidatorSetTransition_bug_premature_activation.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  reconfig-bug-premature-new-cert)
    spec_file="$spec_dir/SumeragiValidatorSetTransition.tla"
    cfg_file="$spec_dir/SumeragiValidatorSetTransition_bug_premature_new_cert.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  reconfig-bug-mixed-cert)
    spec_file="$spec_dir/SumeragiValidatorSetTransition.tla"
    cfg_file="$spec_dir/SumeragiValidatorSetTransition_bug_mixed_cert.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  recovery-bug-commit-without-payload)
    spec_file="$spec_dir/SumeragiCertifiedRecovery.tla"
    cfg_file="$spec_dir/SumeragiCertifiedRecovery_bug_commit_without_payload.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  recovery-bug-mismatched-payload)
    spec_file="$spec_dir/SumeragiCertifiedRecovery.tla"
    cfg_file="$spec_dir/SumeragiCertifiedRecovery_bug_mismatched_payload.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  recovery-bug-conflicting-finality)
    spec_file="$spec_dir/SumeragiCertifiedRecovery.tla"
    cfg_file="$spec_dir/SumeragiCertifiedRecovery_bug_conflicting_finality.cfg"
    apalache_length=6
    expect_failure=1
    ;;
  view-change-bug-stale-new-view)
    spec_file="$spec_dir/SumeragiViewChangeSafety.tla"
    cfg_file="$spec_dir/SumeragiViewChangeSafety_bug_stale_new_view.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  view-change-bug-unsafe-proposal)
    spec_file="$spec_dir/SumeragiViewChangeSafety.tla"
    cfg_file="$spec_dir/SumeragiViewChangeSafety_bug_unsafe_proposal.cfg"
    apalache_length=4
    expect_failure=1
    ;;
  view-change-bug-lock-overwrite)
    spec_file="$spec_dir/SumeragiViewChangeSafety.tla"
    cfg_file="$spec_dir/SumeragiViewChangeSafety_bug_lock_overwrite.cfg"
    apalache_length=3
    expect_failure=1
    ;;
  view-change-bug-highest-regression)
    spec_file="$spec_dir/SumeragiViewChangeSafety.tla"
    cfg_file="$spec_dir/SumeragiViewChangeSafety_bug_highest_regression.cfg"
    apalache_length=3
    expect_failure=1
    ;;
  validation-bug-unknown-result)
    spec_file="$spec_dir/SumeragiValidationGate.tla"
    cfg_file="$spec_dir/SumeragiValidationGate_bug_unknown_result.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  validation-bug-completed-replay)
    spec_file="$spec_dir/SumeragiValidationGate.tla"
    cfg_file="$spec_dir/SumeragiValidationGate_bug_completed_replay.cfg"
    apalache_length=4
    expect_failure=1
    ;;
  validation-bug-timeout-inflight)
    spec_file="$spec_dir/SumeragiValidationGate.tla"
    cfg_file="$spec_dir/SumeragiValidationGate_bug_timeout_inflight.cfg"
    apalache_length=3
    expect_failure=1
    ;;
  validation-bug-invalid-replay)
    spec_file="$spec_dir/SumeragiValidationGate.tla"
    cfg_file="$spec_dir/SumeragiValidationGate_bug_invalid_replay.cfg"
    apalache_length=3
    expect_failure=1
    ;;
  admission-bug-wrong-context)
    spec_file="$spec_dir/SumeragiCertificateAdmission.tla"
    cfg_file="$spec_dir/SumeragiCertificateAdmission_bug_wrong_context.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  admission-bug-stale-prepare-commit)
    spec_file="$spec_dir/SumeragiCertificateAdmission.tla"
    cfg_file="$spec_dir/SumeragiCertificateAdmission_bug_stale_prepare_commit.cfg"
    apalache_length=3
    expect_failure=1
    ;;
  admission-bug-future-height)
    spec_file="$spec_dir/SumeragiCertificateAdmission.tla"
    cfg_file="$spec_dir/SumeragiCertificateAdmission_bug_future_height.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  admission-bug-committed-height)
    spec_file="$spec_dir/SumeragiCertificateAdmission.tla"
    cfg_file="$spec_dir/SumeragiCertificateAdmission_bug_committed_height.cfg"
    apalache_length=4
    expect_failure=1
    ;;
  highest-bug-height-priority)
    spec_file="$spec_dir/SumeragiHighestQcSelection.tla"
    cfg_file="$spec_dir/SumeragiHighestQcSelection_bug_height_priority.cfg"
    apalache_length=3
    expect_failure=1
    ;;
  highest-bug-phase-rank)
    spec_file="$spec_dir/SumeragiHighestQcSelection.tla"
    cfg_file="$spec_dir/SumeragiHighestQcSelection_bug_phase_rank.cfg"
    apalache_length=3
    expect_failure=1
    ;;
  highest-bug-subject-tie)
    spec_file="$spec_dir/SumeragiHighestQcSelection.tla"
    cfg_file="$spec_dir/SumeragiHighestQcSelection_bug_subject_tie.cfg"
    apalache_length=3
    expect_failure=1
    ;;
  highest-bug-non-new-view)
    spec_file="$spec_dir/SumeragiHighestQcSelection.tla"
    cfg_file="$spec_dir/SumeragiHighestQcSelection_bug_non_new_view.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  rbc-bug-duplicate-ready)
    spec_file="$spec_dir/SumeragiRbcDeliverQuorum.tla"
    cfg_file="$spec_dir/SumeragiRbcDeliverQuorum_bug_duplicate_ready_count.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  rbc-bug-under-quorum-deliver)
    spec_file="$spec_dir/SumeragiRbcDeliverQuorum.tla"
    cfg_file="$spec_dir/SumeragiRbcDeliverQuorum_bug_under_quorum_deliver.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  rbc-bug-wrong-commit-formula)
    spec_file="$spec_dir/SumeragiRbcDeliverQuorum.tla"
    cfg_file="$spec_dir/SumeragiRbcDeliverQuorum_bug_wrong_commit_formula.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  rbc-bug-force-one-ignored)
    spec_file="$spec_dir/SumeragiRbcDeliverQuorum.tla"
    cfg_file="$spec_dir/SumeragiRbcDeliverQuorum_bug_force_one_ignored.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  qc-signers-bug-count-observers)
    spec_file="$spec_dir/SumeragiQcSignerBitmap.tla"
    cfg_file="$spec_dir/SumeragiQcSignerBitmap_bug_count_observers.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  qc-signers-bug-ignore-bitmap-length)
    spec_file="$spec_dir/SumeragiQcSignerBitmap.tla"
    cfg_file="$spec_dir/SumeragiQcSignerBitmap_bug_ignore_bitmap_length.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  qc-signers-bug-ignore-out-of-bounds)
    spec_file="$spec_dir/SumeragiQcSignerBitmap.tla"
    cfg_file="$spec_dir/SumeragiQcSignerBitmap_bug_ignore_out_of_bounds.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  qc-signers-bug-under-quorum-accept)
    spec_file="$spec_dir/SumeragiQcSignerBitmap.tla"
    cfg_file="$spec_dir/SumeragiQcSignerBitmap_bug_under_quorum_accept.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-roots-bug-mix-root-signers)
    spec_file="$spec_dir/SumeragiCommitRootConsistency.tla"
    cfg_file="$spec_dir/SumeragiCommitRootConsistency_bug_mix_root_signers.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-roots-bug-count-wrong-context)
    spec_file="$spec_dir/SumeragiCommitRootConsistency.tla"
    cfg_file="$spec_dir/SumeragiCommitRootConsistency_bug_count_wrong_context.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-roots-bug-tie-high-root)
    spec_file="$spec_dir/SumeragiCommitRootConsistency.tla"
    cfg_file="$spec_dir/SumeragiCommitRootConsistency_bug_tie_high_root.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-roots-bug-stake-ignores-weight)
    spec_file="$spec_dir/SumeragiCommitRootConsistency.tla"
    cfg_file="$spec_dir/SumeragiCommitRootConsistency_bug_stake_ignores_weight.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-roots-bug-under-quorum-accept)
    spec_file="$spec_dir/SumeragiCommitRootConsistency.tla"
    cfg_file="$spec_dir/SumeragiCommitRootConsistency_bug_under_quorum_accept.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-roots-bug-validate-mismatched-roots)
    spec_file="$spec_dir/SumeragiCommitRootConsistency.tla"
    cfg_file="$spec_dir/SumeragiCommitRootConsistency_bug_validate_mismatched_roots.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  precommit-bug-invalid-validation)
    spec_file="$spec_dir/SumeragiPrecommitVoteGate.tla"
    cfg_file="$spec_dir/SumeragiPrecommitVoteGate_bug_invalid_validation.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  precommit-bug-observer)
    spec_file="$spec_dir/SumeragiPrecommitVoteGate.tla"
    cfg_file="$spec_dir/SumeragiPrecommitVoteGate_bug_observer.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  precommit-bug-duplicate)
    spec_file="$spec_dir/SumeragiPrecommitVoteGate.tla"
    cfg_file="$spec_dir/SumeragiPrecommitVoteGate_bug_duplicate.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  precommit-bug-unsuperseded-conflict)
    spec_file="$spec_dir/SumeragiPrecommitVoteGate.tla"
    cfg_file="$spec_dir/SumeragiPrecommitVoteGate_bug_unsuperseded_conflict.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  precommit-bug-older-quorum-completion)
    spec_file="$spec_dir/SumeragiPrecommitVoteGate.tla"
    cfg_file="$spec_dir/SumeragiPrecommitVoteGate_bug_older_quorum_completion.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  precommit-bug-locked-conflict)
    spec_file="$spec_dir/SumeragiPrecommitVoteGate.tla"
    cfg_file="$spec_dir/SumeragiPrecommitVoteGate_bug_locked_conflict.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  precommit-bug-missing-locked-payload)
    spec_file="$spec_dir/SumeragiPrecommitVoteGate.tla"
    cfg_file="$spec_dir/SumeragiPrecommitVoteGate_bug_missing_locked_payload.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  precommit-bug-non-extending-lock)
    spec_file="$spec_dir/SumeragiPrecommitVoteGate.tla"
    cfg_file="$spec_dir/SumeragiPrecommitVoteGate_bug_non_extending_lock.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  precommit-bug-reject-safe)
    spec_file="$spec_dir/SumeragiPrecommitVoteGate.tla"
    cfg_file="$spec_dir/SumeragiPrecommitVoteGate_bug_reject_safe.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  proposal-bug-observer)
    spec_file="$spec_dir/SumeragiProposalAssemblyGate.tla"
    cfg_file="$spec_dir/SumeragiProposalAssemblyGate_bug_observer.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  proposal-bug-active-vote-conflict)
    spec_file="$spec_dir/SumeragiProposalAssemblyGate.tla"
    cfg_file="$spec_dir/SumeragiProposalAssemblyGate_bug_active_vote_conflict.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  proposal-bug-pending-vote-verification)
    spec_file="$spec_dir/SumeragiProposalAssemblyGate.tla"
    cfg_file="$spec_dir/SumeragiProposalAssemblyGate_bug_pending_vote_verification.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  proposal-bug-missing-highest-qc)
    spec_file="$spec_dir/SumeragiProposalAssemblyGate.tla"
    cfg_file="$spec_dir/SumeragiProposalAssemblyGate_bug_missing_highest_qc.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  proposal-bug-non-extending-highest)
    spec_file="$spec_dir/SumeragiProposalAssemblyGate.tla"
    cfg_file="$spec_dir/SumeragiProposalAssemblyGate_bug_non_extending_highest.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  proposal-bug-split-vote-lock)
    spec_file="$spec_dir/SumeragiProposalAssemblyGate.tla"
    cfg_file="$spec_dir/SumeragiProposalAssemblyGate_bug_split_vote_lock.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  proposal-bug-committed-edge-conflict)
    spec_file="$spec_dir/SumeragiProposalAssemblyGate.tla"
    cfg_file="$spec_dir/SumeragiProposalAssemblyGate_bug_committed_edge_conflict.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  proposal-bug-reject-safe)
    spec_file="$spec_dir/SumeragiProposalAssemblyGate.tla"
    cfg_file="$spec_dir/SumeragiProposalAssemblyGate_bug_reject_safe.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  proposal-bug-reject-stale-retired)
    spec_file="$spec_dir/SumeragiProposalAssemblyGate.tla"
    cfg_file="$spec_dir/SumeragiProposalAssemblyGate_bug_reject_stale_retired.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  proposal-bug-reject-locked-fallback)
    spec_file="$spec_dir/SumeragiProposalAssemblyGate.tla"
    cfg_file="$spec_dir/SumeragiProposalAssemblyGate_bug_reject_locked_fallback.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-tick-bug-skip-round-advance)
    spec_file="$spec_dir/SumeragiEngineTickGate.tla"
    cfg_file="$spec_dir/SumeragiEngineTickGate_bug_skip_round_advance.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-tick-bug-skip-new-view-vote)
    spec_file="$spec_dir/SumeragiEngineTickGate.tla"
    cfg_file="$spec_dir/SumeragiEngineTickGate_bug_skip_new_view_vote.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-tick-bug-skip-advance-output)
    spec_file="$spec_dir/SumeragiEngineTickGate.tla"
    cfg_file="$spec_dir/SumeragiEngineTickGate_bug_skip_advance_output.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-tick-bug-wrong-phase)
    spec_file="$spec_dir/SumeragiEngineTickGate.tla"
    cfg_file="$spec_dir/SumeragiEngineTickGate_bug_wrong_phase.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-tick-bug-keep-validation)
    spec_file="$spec_dir/SumeragiEngineTickGate.tla"
    cfg_file="$spec_dir/SumeragiEngineTickGate_bug_keep_validation.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-tick-bug-drop-pending-finality)
    spec_file="$spec_dir/SumeragiEngineTickGate.tla"
    cfg_file="$spec_dir/SumeragiEngineTickGate_bug_drop_pending_finality.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-tick-bug-use-zero-despite-highest)
    spec_file="$spec_dir/SumeragiEngineTickGate.tla"
    cfg_file="$spec_dir/SumeragiEngineTickGate_bug_use_zero_despite_highest.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-tick-bug-use-highest-without-highest)
    spec_file="$spec_dir/SumeragiEngineTickGate.tla"
    cfg_file="$spec_dir/SumeragiEngineTickGate_bug_use_highest_without_highest.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-tick-bug-omit-highest-binding)
    spec_file="$spec_dir/SumeragiEngineTickGate.tla"
    cfg_file="$spec_dir/SumeragiEngineTickGate_bug_omit_highest_binding.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-tick-bug-bind-highest-without-highest)
    spec_file="$spec_dir/SumeragiEngineTickGate.tla"
    cfg_file="$spec_dir/SumeragiEngineTickGate_bug_bind_highest_without_highest.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-new-view-bug-accept-wrong-context)
    spec_file="$spec_dir/SumeragiEngineNewViewQcGate.tla"
    cfg_file="$spec_dir/SumeragiEngineNewViewQcGate_bug_accept_wrong_context.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-new-view-bug-accept-wrong-quorum)
    spec_file="$spec_dir/SumeragiEngineNewViewQcGate.tla"
    cfg_file="$spec_dir/SumeragiEngineNewViewQcGate_bug_accept_wrong_quorum.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-new-view-bug-accept-stale-view)
    spec_file="$spec_dir/SumeragiEngineNewViewQcGate.tla"
    cfg_file="$spec_dir/SumeragiEngineNewViewQcGate_bug_accept_stale_view.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-new-view-bug-accept-incompatible-highest)
    spec_file="$spec_dir/SumeragiEngineNewViewQcGate.tla"
    cfg_file="$spec_dir/SumeragiEngineNewViewQcGate_bug_accept_incompatible_highest.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-new-view-bug-reject-safe-no-highest)
    spec_file="$spec_dir/SumeragiEngineNewViewQcGate.tla"
    cfg_file="$spec_dir/SumeragiEngineNewViewQcGate_bug_reject_safe_no_highest.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-new-view-bug-reject-safe-improving-highest)
    spec_file="$spec_dir/SumeragiEngineNewViewQcGate.tla"
    cfg_file="$spec_dir/SumeragiEngineNewViewQcGate_bug_reject_safe_improving_highest.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-new-view-bug-reject-safe-lower-highest)
    spec_file="$spec_dir/SumeragiEngineNewViewQcGate.tla"
    cfg_file="$spec_dir/SumeragiEngineNewViewQcGate_bug_reject_safe_lower_highest.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-new-view-bug-skip-advance-output)
    spec_file="$spec_dir/SumeragiEngineNewViewQcGate.tla"
    cfg_file="$spec_dir/SumeragiEngineNewViewQcGate_bug_skip_advance_output.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-new-view-bug-wrong-phase)
    spec_file="$spec_dir/SumeragiEngineNewViewQcGate.tla"
    cfg_file="$spec_dir/SumeragiEngineNewViewQcGate_bug_wrong_phase.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-new-view-bug-keep-validation)
    spec_file="$spec_dir/SumeragiEngineNewViewQcGate.tla"
    cfg_file="$spec_dir/SumeragiEngineNewViewQcGate_bug_keep_validation.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-new-view-bug-drop-pending-finality)
    spec_file="$spec_dir/SumeragiEngineNewViewQcGate.tla"
    cfg_file="$spec_dir/SumeragiEngineNewViewQcGate_bug_drop_pending_finality.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-new-view-bug-overwrite-lower-highest)
    spec_file="$spec_dir/SumeragiEngineNewViewQcGate.tla"
    cfg_file="$spec_dir/SumeragiEngineNewViewQcGate_bug_overwrite_lower_highest.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-new-view-bug-skip-highest-record)
    spec_file="$spec_dir/SumeragiEngineNewViewQcGate.tla"
    cfg_file="$spec_dir/SumeragiEngineNewViewQcGate_bug_skip_highest_record.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-proposal-bug-wrong-phase)
    spec_file="$spec_dir/SumeragiEngineProposalGate.tla"
    cfg_file="$spec_dir/SumeragiEngineProposalGate_bug_wrong_phase.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-proposal-bug-wrong-round)
    spec_file="$spec_dir/SumeragiEngineProposalGate.tla"
    cfg_file="$spec_dir/SumeragiEngineProposalGate_bug_wrong_round.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-proposal-bug-incompatible-highest)
    spec_file="$spec_dir/SumeragiEngineProposalGate.tla"
    cfg_file="$spec_dir/SumeragiEngineProposalGate_bug_incompatible_highest.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-proposal-bug-locked-conflict-no-qc)
    spec_file="$spec_dir/SumeragiEngineProposalGate.tla"
    cfg_file="$spec_dir/SumeragiEngineProposalGate_bug_locked_conflict_no_qc.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-proposal-bug-locked-conflict-equal-qc)
    spec_file="$spec_dir/SumeragiEngineProposalGate.tla"
    cfg_file="$spec_dir/SumeragiEngineProposalGate_bug_locked_conflict_equal_qc.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-proposal-bug-locked-conflict-lower-qc)
    spec_file="$spec_dir/SumeragiEngineProposalGate.tla"
    cfg_file="$spec_dir/SumeragiEngineProposalGate_bug_locked_conflict_lower_qc.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-proposal-bug-reject-unlocked)
    spec_file="$spec_dir/SumeragiEngineProposalGate.tla"
    cfg_file="$spec_dir/SumeragiEngineProposalGate_bug_reject_unlocked.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-proposal-bug-reject-locked-subject)
    spec_file="$spec_dir/SumeragiEngineProposalGate.tla"
    cfg_file="$spec_dir/SumeragiEngineProposalGate_bug_reject_locked_subject.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-proposal-bug-reject-higher-qc)
    spec_file="$spec_dir/SumeragiEngineProposalGate.tla"
    cfg_file="$spec_dir/SumeragiEngineProposalGate_bug_reject_higher_qc.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-proposal-bug-skip-validation)
    spec_file="$spec_dir/SumeragiEngineProposalGate.tla"
    cfg_file="$spec_dir/SumeragiEngineProposalGate_bug_skip_validation_request.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-proposal-bug-skip-prepare-vote)
    spec_file="$spec_dir/SumeragiEngineProposalGate.tla"
    cfg_file="$spec_dir/SumeragiEngineProposalGate_bug_skip_prepare_vote.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-proposal-bug-skip-prepare-phase)
    spec_file="$spec_dir/SumeragiEngineProposalGate.tla"
    cfg_file="$spec_dir/SumeragiEngineProposalGate_bug_skip_prepare_phase.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-prepare-bug-wrong-context)
    spec_file="$spec_dir/SumeragiEnginePrepareQcGate.tla"
    cfg_file="$spec_dir/SumeragiEnginePrepareQcGate_bug_wrong_context.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-prepare-bug-wrong-quorum-policy)
    spec_file="$spec_dir/SumeragiEnginePrepareQcGate.tla"
    cfg_file="$spec_dir/SumeragiEnginePrepareQcGate_bug_wrong_quorum_policy.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-prepare-bug-stale-view)
    spec_file="$spec_dir/SumeragiEnginePrepareQcGate.tla"
    cfg_file="$spec_dir/SumeragiEnginePrepareQcGate_bug_stale_view.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-prepare-bug-committed-height)
    spec_file="$spec_dir/SumeragiEnginePrepareQcGate.tla"
    cfg_file="$spec_dir/SumeragiEnginePrepareQcGate_bug_committed_height.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-prepare-bug-replay-prepare)
    spec_file="$spec_dir/SumeragiEnginePrepareQcGate.tla"
    cfg_file="$spec_dir/SumeragiEnginePrepareQcGate_bug_replay_prepare.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-prepare-bug-conflicting-prepare)
    spec_file="$spec_dir/SumeragiEnginePrepareQcGate.tla"
    cfg_file="$spec_dir/SumeragiEnginePrepareQcGate_bug_conflicting_prepare.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-prepare-bug-pending-finality)
    spec_file="$spec_dir/SumeragiEnginePrepareQcGate.tla"
    cfg_file="$spec_dir/SumeragiEnginePrepareQcGate_bug_pending_finality.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-prepare-bug-reject-safe)
    spec_file="$spec_dir/SumeragiEnginePrepareQcGate.tla"
    cfg_file="$spec_dir/SumeragiEnginePrepareQcGate_bug_reject_safe.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-prepare-bug-missing-lock-record)
    spec_file="$spec_dir/SumeragiEnginePrepareQcGate.tla"
    cfg_file="$spec_dir/SumeragiEnginePrepareQcGate_bug_missing_lock_record.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-commit-bug-wrong-context)
    spec_file="$spec_dir/SumeragiEngineCommitQcGate.tla"
    cfg_file="$spec_dir/SumeragiEngineCommitQcGate_bug_wrong_context.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-commit-bug-wrong-quorum-policy)
    spec_file="$spec_dir/SumeragiEngineCommitQcGate.tla"
    cfg_file="$spec_dir/SumeragiEngineCommitQcGate_bug_wrong_quorum_policy.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-commit-bug-stale-view)
    spec_file="$spec_dir/SumeragiEngineCommitQcGate.tla"
    cfg_file="$spec_dir/SumeragiEngineCommitQcGate_bug_stale_view.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-commit-bug-committed-height)
    spec_file="$spec_dir/SumeragiEngineCommitQcGate.tla"
    cfg_file="$spec_dir/SumeragiEngineCommitQcGate_bug_committed_height.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-commit-bug-pending-replay)
    spec_file="$spec_dir/SumeragiEngineCommitQcGate.tla"
    cfg_file="$spec_dir/SumeragiEngineCommitQcGate_bug_pending_replay.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-commit-bug-pending-conflict)
    spec_file="$spec_dir/SumeragiEngineCommitQcGate.tla"
    cfg_file="$spec_dir/SumeragiEngineCommitQcGate_bug_pending_conflict.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-commit-bug-commit-without-payload)
    spec_file="$spec_dir/SumeragiEngineCommitQcGate.tla"
    cfg_file="$spec_dir/SumeragiEngineCommitQcGate_bug_commit_without_payload.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-commit-bug-fetch-despite-payload)
    spec_file="$spec_dir/SumeragiEngineCommitQcGate.tla"
    cfg_file="$spec_dir/SumeragiEngineCommitQcGate_bug_fetch_despite_payload.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-commit-bug-reject-available)
    spec_file="$spec_dir/SumeragiEngineCommitQcGate.tla"
    cfg_file="$spec_dir/SumeragiEngineCommitQcGate_bug_reject_available.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-commit-bug-reject-missing-payload)
    spec_file="$spec_dir/SumeragiEngineCommitQcGate.tla"
    cfg_file="$spec_dir/SumeragiEngineCommitQcGate_bug_reject_missing_payload.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-commit-bug-missing-highest-record)
    spec_file="$spec_dir/SumeragiEngineCommitQcGate.tla"
    cfg_file="$spec_dir/SumeragiEngineCommitQcGate_bug_missing_highest_record.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-committed-block-bug-skip-fresh-record)
    spec_file="$spec_dir/SumeragiEngineCommittedBlockGate.tla"
    cfg_file="$spec_dir/SumeragiEngineCommittedBlockGate_bug_skip_fresh_record.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-committed-block-bug-reject-boundary-activation)
    spec_file="$spec_dir/SumeragiEngineCommittedBlockGate.tla"
    cfg_file="$spec_dir/SumeragiEngineCommittedBlockGate_bug_reject_boundary_activation.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-committed-block-bug-activate-without-boundary)
    spec_file="$spec_dir/SumeragiEngineCommittedBlockGate.tla"
    cfg_file="$spec_dir/SumeragiEngineCommittedBlockGate_bug_activate_without_boundary.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-committed-block-bug-activate-non-boundary)
    spec_file="$spec_dir/SumeragiEngineCommittedBlockGate.tla"
    cfg_file="$spec_dir/SumeragiEngineCommittedBlockGate_bug_activate_non_boundary.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-committed-block-bug-record-duplicate)
    spec_file="$spec_dir/SumeragiEngineCommittedBlockGate.tla"
    cfg_file="$spec_dir/SumeragiEngineCommittedBlockGate_bug_record_duplicate.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-committed-block-bug-activate-duplicate)
    spec_file="$spec_dir/SumeragiEngineCommittedBlockGate.tla"
    cfg_file="$spec_dir/SumeragiEngineCommittedBlockGate_bug_activate_duplicate.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-committed-block-bug-record-conflict)
    spec_file="$spec_dir/SumeragiEngineCommittedBlockGate.tla"
    cfg_file="$spec_dir/SumeragiEngineCommittedBlockGate_bug_record_conflict.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-committed-block-bug-activate-conflict)
    spec_file="$spec_dir/SumeragiEngineCommittedBlockGate.tla"
    cfg_file="$spec_dir/SumeragiEngineCommittedBlockGate_bug_activate_conflict.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-committed-block-bug-overwrite-conflict)
    spec_file="$spec_dir/SumeragiEngineCommittedBlockGate.tla"
    cfg_file="$spec_dir/SumeragiEngineCommittedBlockGate_bug_overwrite_conflict.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-payload-bug-skip-available-record)
    spec_file="$spec_dir/SumeragiEnginePayloadAvailabilityGate.tla"
    cfg_file="$spec_dir/SumeragiEnginePayloadAvailabilityGate_bug_skip_available_record.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-payload-bug-commit-without-pending)
    spec_file="$spec_dir/SumeragiEnginePayloadAvailabilityGate.tla"
    cfg_file="$spec_dir/SumeragiEnginePayloadAvailabilityGate_bug_commit_without_pending.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-payload-bug-commit-mismatched-payload)
    spec_file="$spec_dir/SumeragiEnginePayloadAvailabilityGate.tla"
    cfg_file="$spec_dir/SumeragiEnginePayloadAvailabilityGate_bug_commit_mismatched_payload.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-payload-bug-drop-pending-on-mismatch)
    spec_file="$spec_dir/SumeragiEnginePayloadAvailabilityGate.tla"
    cfg_file="$spec_dir/SumeragiEnginePayloadAvailabilityGate_bug_drop_pending_on_mismatch.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-payload-bug-reject-matching-payload)
    spec_file="$spec_dir/SumeragiEnginePayloadAvailabilityGate.tla"
    cfg_file="$spec_dir/SumeragiEnginePayloadAvailabilityGate_bug_reject_matching_payload.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-payload-bug-keep-pending-after-commit)
    spec_file="$spec_dir/SumeragiEnginePayloadAvailabilityGate.tla"
    cfg_file="$spec_dir/SumeragiEnginePayloadAvailabilityGate_bug_keep_pending_after_commit.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-payload-bug-wrong-phase-after-commit)
    spec_file="$spec_dir/SumeragiEnginePayloadAvailabilityGate.tla"
    cfg_file="$spec_dir/SumeragiEnginePayloadAvailabilityGate_bug_wrong_phase_after_commit.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-validation-result-bug-accept-wrong-round)
    spec_file="$spec_dir/SumeragiEngineValidationResultGate.tla"
    cfg_file="$spec_dir/SumeragiEngineValidationResultGate_bug_accept_wrong_round.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-validation-result-bug-accept-wrong-block-hash)
    spec_file="$spec_dir/SumeragiEngineValidationResultGate.tla"
    cfg_file="$spec_dir/SumeragiEngineValidationResultGate_bug_accept_wrong_block_hash.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-validation-result-bug-accept-no-inflight)
    spec_file="$spec_dir/SumeragiEngineValidationResultGate.tla"
    cfg_file="$spec_dir/SumeragiEngineValidationResultGate_bug_accept_no_inflight.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-validation-result-bug-accept-superseded)
    spec_file="$spec_dir/SumeragiEngineValidationResultGate.tla"
    cfg_file="$spec_dir/SumeragiEngineValidationResultGate_bug_accept_superseded.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-validation-result-bug-reject-current-valid)
    spec_file="$spec_dir/SumeragiEngineValidationResultGate.tla"
    cfg_file="$spec_dir/SumeragiEngineValidationResultGate_bug_reject_current_valid.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-validation-result-bug-reject-current-invalid)
    spec_file="$spec_dir/SumeragiEngineValidationResultGate.tla"
    cfg_file="$spec_dir/SumeragiEngineValidationResultGate_bug_reject_current_invalid.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-validation-result-bug-keep-validation)
    spec_file="$spec_dir/SumeragiEngineValidationResultGate.tla"
    cfg_file="$spec_dir/SumeragiEngineValidationResultGate_bug_keep_validation.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-validation-result-bug-valid-emits-output)
    spec_file="$spec_dir/SumeragiEngineValidationResultGate.tla"
    cfg_file="$spec_dir/SumeragiEngineValidationResultGate_bug_valid_emits_output.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-validation-result-bug-skip-round-advance)
    spec_file="$spec_dir/SumeragiEngineValidationResultGate.tla"
    cfg_file="$spec_dir/SumeragiEngineValidationResultGate_bug_skip_round_advance.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-validation-result-bug-skip-new-view-vote)
    spec_file="$spec_dir/SumeragiEngineValidationResultGate.tla"
    cfg_file="$spec_dir/SumeragiEngineValidationResultGate_bug_skip_new_view_vote.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-validation-result-bug-skip-advance-output)
    spec_file="$spec_dir/SumeragiEngineValidationResultGate.tla"
    cfg_file="$spec_dir/SumeragiEngineValidationResultGate_bug_skip_advance_output.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-validation-result-bug-wrong-phase)
    spec_file="$spec_dir/SumeragiEngineValidationResultGate.tla"
    cfg_file="$spec_dir/SumeragiEngineValidationResultGate_bug_wrong_phase.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-validation-result-bug-use-invalid-subject-despite-highest)
    spec_file="$spec_dir/SumeragiEngineValidationResultGate.tla"
    cfg_file="$spec_dir/SumeragiEngineValidationResultGate_bug_use_invalid_subject_despite_highest.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-validation-result-bug-use-highest-without-highest)
    spec_file="$spec_dir/SumeragiEngineValidationResultGate.tla"
    cfg_file="$spec_dir/SumeragiEngineValidationResultGate_bug_use_highest_without_highest.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-validation-result-bug-omit-highest-binding)
    spec_file="$spec_dir/SumeragiEngineValidationResultGate.tla"
    cfg_file="$spec_dir/SumeragiEngineValidationResultGate_bug_omit_highest_binding.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-validation-result-bug-bind-highest-without-highest)
    spec_file="$spec_dir/SumeragiEngineValidationResultGate.tla"
    cfg_file="$spec_dir/SumeragiEngineValidationResultGate_bug_bind_highest_without_highest.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-validation-result-bug-drop-pending-finality)
    spec_file="$spec_dir/SumeragiEngineValidationResultGate.tla"
    cfg_file="$spec_dir/SumeragiEngineValidationResultGate_bug_drop_pending_finality.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  engine-validation-result-bug-overwrite-committed)
    spec_file="$spec_dir/SumeragiEngineValidationResultGate.tla"
    cfg_file="$spec_dir/SumeragiEngineValidationResultGate_bug_overwrite_committed.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-pipeline-recovery-bug-skip-local-qc-formation)
    spec_file="$spec_dir/SumeragiCommitPipelineRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiCommitPipelineRecoveryGate_bug_skip_local_qc_formation.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-pipeline-recovery-bug-recover-despite-local-quorum)
    spec_file="$spec_dir/SumeragiCommitPipelineRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiCommitPipelineRecoveryGate_bug_recover_despite_local_quorum.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-pipeline-recovery-bug-request-recovery-before-timeout)
    spec_file="$spec_dir/SumeragiCommitPipelineRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiCommitPipelineRecoveryGate_bug_request_recovery_before_timeout.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-pipeline-recovery-bug-request-recovery-without-local-vote)
    spec_file="$spec_dir/SumeragiCommitPipelineRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiCommitPipelineRecoveryGate_bug_request_recovery_without_local_vote.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-pipeline-recovery-bug-request-recovery-with-commit-qc)
    spec_file="$spec_dir/SumeragiCommitPipelineRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiCommitPipelineRecoveryGate_bug_request_recovery_with_commit_qc.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-pipeline-recovery-bug-request-recovery-with-missing-data)
    spec_file="$spec_dir/SumeragiCommitPipelineRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiCommitPipelineRecoveryGate_bug_request_recovery_with_missing_data.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-pipeline-recovery-bug-request-recovery-invalid-pending)
    spec_file="$spec_dir/SumeragiCommitPipelineRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiCommitPipelineRecoveryGate_bug_request_recovery_invalid_pending.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-pipeline-recovery-bug-request-recovery-off-tip)
    spec_file="$spec_dir/SumeragiCommitPipelineRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiCommitPipelineRecoveryGate_bug_request_recovery_off_tip.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-pipeline-recovery-bug-skip-missing-qc-request)
    spec_file="$spec_dir/SumeragiCommitPipelineRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiCommitPipelineRecoveryGate_bug_skip_missing_qc_request.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-pipeline-recovery-bug-drop-commit-qc-marker)
    spec_file="$spec_dir/SumeragiCommitPipelineRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiCommitPipelineRecoveryGate_bug_drop_commit_qc_marker.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-pipeline-recovery-bug-skip-quorum-retransmit)
    spec_file="$spec_dir/SumeragiCommitPipelineRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiCommitPipelineRecoveryGate_bug_skip_quorum_retransmit.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-pipeline-recovery-bug-use-collector-targets)
    spec_file="$spec_dir/SumeragiCommitPipelineRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiCommitPipelineRecoveryGate_bug_use_collector_targets.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-pipeline-recovery-bug-rebroadcast-without-votes)
    spec_file="$spec_dir/SumeragiCommitPipelineRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiCommitPipelineRecoveryGate_bug_rebroadcast_without_votes.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-pipeline-recovery-bug-rebroadcast-after-qc)
    spec_file="$spec_dir/SumeragiCommitPipelineRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiCommitPipelineRecoveryGate_bug_rebroadcast_after_qc.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-evidence-replay-bug-replay-inactive)
    spec_file="$spec_dir/SumeragiCommitEvidenceReplayGate.tla"
    cfg_file="$spec_dir/SumeragiCommitEvidenceReplayGate_bug_replay_inactive.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-evidence-replay-bug-ignore-cooldown)
    spec_file="$spec_dir/SumeragiCommitEvidenceReplayGate.tla"
    cfg_file="$spec_dir/SumeragiCommitEvidenceReplayGate_bug_ignore_cooldown.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-evidence-replay-bug-replay-without-targets)
    spec_file="$spec_dir/SumeragiCommitEvidenceReplayGate.tla"
    cfg_file="$spec_dir/SumeragiCommitEvidenceReplayGate_bug_replay_without_targets.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-evidence-replay-bug-skip-first-evidence)
    spec_file="$spec_dir/SumeragiCommitEvidenceReplayGate.tla"
    cfg_file="$spec_dir/SumeragiCommitEvidenceReplayGate_bug_skip_first_evidence.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-evidence-replay-bug-skip-progress)
    spec_file="$spec_dir/SumeragiCommitEvidenceReplayGate.tla"
    cfg_file="$spec_dir/SumeragiCommitEvidenceReplayGate_bug_skip_progress.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-evidence-replay-bug-skip-stalled-retry)
    spec_file="$spec_dir/SumeragiCommitEvidenceReplayGate.tla"
    cfg_file="$spec_dir/SumeragiCommitEvidenceReplayGate_bug_skip_stalled_retry.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-evidence-replay-bug-replay-no-evidence)
    spec_file="$spec_dir/SumeragiCommitEvidenceReplayGate.tla"
    cfg_file="$spec_dir/SumeragiCommitEvidenceReplayGate_bug_replay_no_evidence.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-evidence-replay-bug-votes-use-payload-fallback)
    spec_file="$spec_dir/SumeragiCommitEvidenceReplayGate.tla"
    cfg_file="$spec_dir/SumeragiCommitEvidenceReplayGate_bug_votes_use_payload_fallback.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-evidence-replay-bug-commit-qc-uses-votes)
    spec_file="$spec_dir/SumeragiCommitEvidenceReplayGate.tla"
    cfg_file="$spec_dir/SumeragiCommitEvidenceReplayGate_bug_commit_qc_uses_votes.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-evidence-replay-bug-drop-commit-qc-replay)
    spec_file="$spec_dir/SumeragiCommitEvidenceReplayGate.tla"
    cfg_file="$spec_dir/SumeragiCommitEvidenceReplayGate_bug_drop_commit_qc_replay.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-evidence-replay-bug-use-local-targets)
    spec_file="$spec_dir/SumeragiCommitEvidenceReplayGate.tla"
    cfg_file="$spec_dir/SumeragiCommitEvidenceReplayGate_bug_use_local_targets.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  commit-evidence-replay-bug-use-duplicate-targets)
    spec_file="$spec_dir/SumeragiCommitEvidenceReplayGate.tla"
    cfg_file="$spec_dir/SumeragiCommitEvidenceReplayGate_bug_use_duplicate_targets.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  block-sync-recovery-bug-accept-stale-without-request)
    spec_file="$spec_dir/SumeragiBlockSyncRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiBlockSyncRecoveryGate_bug_accept_stale_without_request.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  block-sync-recovery-bug-drop-requested-stale)
    spec_file="$spec_dir/SumeragiBlockSyncRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiBlockSyncRecoveryGate_bug_drop_requested_stale.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  block-sync-recovery-bug-accept-future-unrequested)
    spec_file="$spec_dir/SumeragiBlockSyncRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiBlockSyncRecoveryGate_bug_accept_future_unrequested.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  block-sync-recovery-bug-revive-aborted-without-commit-qc)
    spec_file="$spec_dir/SumeragiBlockSyncRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiBlockSyncRecoveryGate_bug_revive_aborted_without_commit_qc.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  block-sync-recovery-bug-keep-aborted-with-commit-qc)
    spec_file="$spec_dir/SumeragiBlockSyncRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiBlockSyncRecoveryGate_bug_keep_aborted_with_commit_qc.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  block-sync-recovery-bug-skip-vote-backed-owner)
    spec_file="$spec_dir/SumeragiBlockSyncRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiBlockSyncRecoveryGate_bug_skip_vote_backed_owner.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  block-sync-recovery-bug-steal-owner-with-payload-only)
    spec_file="$spec_dir/SumeragiBlockSyncRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiBlockSyncRecoveryGate_bug_steal_owner_with_payload_only.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  block-sync-recovery-bug-skip-certified-owner)
    spec_file="$spec_dir/SumeragiBlockSyncRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiBlockSyncRecoveryGate_bug_skip_certified_owner.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  block-sync-recovery-bug-activate-uncertified-conflict)
    spec_file="$spec_dir/SumeragiBlockSyncRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiBlockSyncRecoveryGate_bug_activate_uncertified_conflict.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  block-sync-recovery-bug-drop-commit-qc-marker)
    spec_file="$spec_dir/SumeragiBlockSyncRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiBlockSyncRecoveryGate_bug_drop_commit_qc_marker.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  block-sync-recovery-bug-skip-missing-commit-qc-request)
    spec_file="$spec_dir/SumeragiBlockSyncRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiBlockSyncRecoveryGate_bug_skip_missing_commit_qc_request.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  block-sync-recovery-bug-keep-missing-request)
    spec_file="$spec_dir/SumeragiBlockSyncRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiBlockSyncRecoveryGate_bug_keep_missing_request.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  block-sync-recovery-bug-clear-inflight-for-payload-only)
    spec_file="$spec_dir/SumeragiBlockSyncRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiBlockSyncRecoveryGate_bug_clear_inflight_for_payload_only.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  block-sync-recovery-bug-keep-inflight-for-certified)
    spec_file="$spec_dir/SumeragiBlockSyncRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiBlockSyncRecoveryGate_bug_keep_inflight_for_certified.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  block-sync-recovery-bug-promote-unvalidated-qc)
    spec_file="$spec_dir/SumeragiBlockSyncRecoveryGate.tla"
    cfg_file="$spec_dir/SumeragiBlockSyncRecoveryGate_bug_promote_unvalidated_qc.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  native-amx-attestation-bug-seal-non-native-plan)
    spec_file="$spec_dir/SumeragiNativeAmxAttestationGate.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxAttestationGate_bug_seal_non_native_plan.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  native-amx-attestation-bug-seal-empty-roster)
    spec_file="$spec_dir/SumeragiNativeAmxAttestationGate.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxAttestationGate_bug_seal_empty_roster.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  native-amx-attestation-bug-skip-prepare-request)
    spec_file="$spec_dir/SumeragiNativeAmxAttestationGate.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxAttestationGate_bug_skip_prepare_request.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  native-amx-attestation-bug-skip-commit-request)
    spec_file="$spec_dir/SumeragiNativeAmxAttestationGate.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxAttestationGate_bug_skip_commit_request.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  native-amx-attestation-bug-request-commit-before-prepare)
    spec_file="$spec_dir/SumeragiNativeAmxAttestationGate.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxAttestationGate_bug_request_commit_before_prepare.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  native-amx-attestation-bug-retry-prepare-after-quorum)
    spec_file="$spec_dir/SumeragiNativeAmxAttestationGate.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxAttestationGate_bug_retry_prepare_after_quorum.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  native-amx-attestation-bug-seal-with-prepare-only)
    spec_file="$spec_dir/SumeragiNativeAmxAttestationGate.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxAttestationGate_bug_seal_with_prepare_only.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  native-amx-attestation-bug-seal-with-commit-only)
    spec_file="$spec_dir/SumeragiNativeAmxAttestationGate.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxAttestationGate_bug_seal_with_commit_only.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  native-amx-attestation-bug-seal-partial-multi-leg)
    spec_file="$spec_dir/SumeragiNativeAmxAttestationGate.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxAttestationGate_bug_seal_partial_multi_leg.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  native-amx-attestation-bug-accept-duplicate-prepare)
    spec_file="$spec_dir/SumeragiNativeAmxAttestationGate.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxAttestationGate_bug_accept_duplicate_prepare.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  native-amx-attestation-bug-accept-duplicate-commit)
    spec_file="$spec_dir/SumeragiNativeAmxAttestationGate.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxAttestationGate_bug_accept_duplicate_commit.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  native-amx-attestation-bug-accept-wrong-prepare-body)
    spec_file="$spec_dir/SumeragiNativeAmxAttestationGate.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxAttestationGate_bug_accept_wrong_prepare_body.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  native-amx-attestation-bug-accept-wrong-commit-body)
    spec_file="$spec_dir/SumeragiNativeAmxAttestationGate.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxAttestationGate_bug_accept_wrong_commit_body.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  native-amx-attestation-bug-accept-outsider-signer)
    spec_file="$spec_dir/SumeragiNativeAmxAttestationGate.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxAttestationGate_bug_accept_outsider_signer.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  native-amx-attestation-bug-use-arrival-order-bitmap)
    spec_file="$spec_dir/SumeragiNativeAmxAttestationGate.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxAttestationGate_bug_use_arrival_order_bitmap.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  native-amx-attestation-bug-collapse-retry-bodies)
    spec_file="$spec_dir/SumeragiNativeAmxAttestationGate.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxAttestationGate_bug_collapse_retry_bodies.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  native-amx-attestation-bug-collapse-participant-legs)
    spec_file="$spec_dir/SumeragiNativeAmxAttestationGate.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxAttestationGate_bug_collapse_participant_legs.cfg"
    apalache_length=2
    expect_failure=1
    ;;
  native-amx-journal-bug-drop-native-plan)
    spec_file="$spec_dir/SumeragiNativeAmxJournalReplay.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxJournalReplay_bug_drop_native_plan.cfg"
    apalache_length=1
    expect_failure=1
    ;;
  native-amx-journal-bug-collapse-native-to-single)
    spec_file="$spec_dir/SumeragiNativeAmxJournalReplay.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxJournalReplay_bug_collapse_native_to_single.cfg"
    apalache_length=1
    expect_failure=1
    ;;
  native-amx-journal-bug-single-plan-as-native)
    spec_file="$spec_dir/SumeragiNativeAmxJournalReplay.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxJournalReplay_bug_single_plan_as_native.cfg"
    apalache_length=1
    expect_failure=1
    ;;
  native-amx-journal-bug-drop-participants)
    spec_file="$spec_dir/SumeragiNativeAmxJournalReplay.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxJournalReplay_bug_drop_participants.cfg"
    apalache_length=1
    expect_failure=1
    ;;
  native-amx-journal-bug-reorder-participants)
    spec_file="$spec_dir/SumeragiNativeAmxJournalReplay.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxJournalReplay_bug_reorder_participants.cfg"
    apalache_length=1
    expect_failure=1
    ;;
  native-amx-journal-bug-keep-duplicate-participant)
    spec_file="$spec_dir/SumeragiNativeAmxJournalReplay.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxJournalReplay_bug_keep_duplicate_participant.cfg"
    apalache_length=1
    expect_failure=1
    ;;
  native-amx-journal-bug-recompute-digest-wrong)
    spec_file="$spec_dir/SumeragiNativeAmxJournalReplay.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxJournalReplay_bug_recompute_digest_wrong.cfg"
    apalache_length=1
    expect_failure=1
    ;;
  native-amx-journal-bug-drop-gossip-payload)
    spec_file="$spec_dir/SumeragiNativeAmxJournalReplay.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxJournalReplay_bug_drop_gossip_payload.cfg"
    apalache_length=1
    expect_failure=1
    ;;
  native-amx-journal-bug-drop-entrypoint)
    spec_file="$spec_dir/SumeragiNativeAmxJournalReplay.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxJournalReplay_bug_drop_entrypoint.cfg"
    apalache_length=1
    expect_failure=1
    ;;
  native-amx-journal-bug-remove-by-hash-only)
    spec_file="$spec_dir/SumeragiNativeAmxJournalReplay.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxJournalReplay_bug_remove_by_hash_only.cfg"
    apalache_length=1
    expect_failure=1
    ;;
  native-amx-journal-bug-ignore-exact-remove)
    spec_file="$spec_dir/SumeragiNativeAmxJournalReplay.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxJournalReplay_bug_ignore_exact_remove.cfg"
    apalache_length=1
    expect_failure=1
    ;;
  native-amx-journal-bug-replay-unsupported-version)
    spec_file="$spec_dir/SumeragiNativeAmxJournalReplay.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxJournalReplay_bug_replay_unsupported_version.cfg"
    apalache_length=1
    expect_failure=1
    ;;
  native-amx-journal-bug-first-put-wins)
    spec_file="$spec_dir/SumeragiNativeAmxJournalReplay.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxJournalReplay_bug_first_put_wins.cfg"
    apalache_length=1
    expect_failure=1
    ;;
  native-amx-journal-bug-compaction-drops-live)
    spec_file="$spec_dir/SumeragiNativeAmxJournalReplay.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxJournalReplay_bug_compaction_drops_live.cfg"
    apalache_length=1
    expect_failure=1
    ;;
  native-amx-journal-bug-compaction-keeps-removed)
    spec_file="$spec_dir/SumeragiNativeAmxJournalReplay.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxJournalReplay_bug_compaction_keeps_removed.cfg"
    apalache_length=1
    expect_failure=1
    ;;
  native-amx-journal-bug-keep-torn-tail)
    spec_file="$spec_dir/SumeragiNativeAmxJournalReplay.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxJournalReplay_bug_keep_torn_tail.cfg"
    apalache_length=1
    expect_failure=1
    ;;
  native-amx-journal-bug-drop-prior-on-tail-repair)
    spec_file="$spec_dir/SumeragiNativeAmxJournalReplay.tla"
    cfg_file="$spec_dir/SumeragiNativeAmxJournalReplay_bug_drop_prior_on_tail_repair.cfg"
    apalache_length=1
    expect_failure=1
    ;;
  *)
    echo "unknown Sumeragi formal mode: $mode" >&2
    echo "see docs/formal/sumeragi/README.md for supported modes" >&2
    exit 2
    ;;
esac

apalache_length="${APALACHE_LENGTH:-$apalache_length}"

if [[ ! -f "$cfg_file" ]]; then
  echo "error: missing config '$cfg_file'" >&2
  exit 2
fi

run_dir="$root_dir/target/apalache/sumeragi-$mode"
out_dir="$root_dir/target/apalache/out"
mkdir -p "$run_dir" "$out_dir"

run_with_expected_status() {
  if [[ "$expect_failure" == "1" ]]; then
    if "$@"; then
      echo "error: expected Apalache to reject '$mode', but it passed" >&2
      return 1
    fi
    echo "[formal] expected Apalache rejection observed for '$mode'"
    return 0
  fi

  "$@"
}

if [[ "$apalache_bin" == */* ]]; then
  if [[ -x "$apalache_bin" ]]; then
    run_with_expected_status "$apalache_bin" --out-dir="$out_dir" check --length="$apalache_length" --config="$cfg_file" --run-dir="$run_dir" "$spec_file"
    exit 0
  fi
elif command -v "$apalache_bin" >/dev/null 2>&1; then
  run_with_expected_status "$apalache_bin" --out-dir="$out_dir" check --length="$apalache_length" --config="$cfg_file" --run-dir="$run_dir" "$spec_file"
  exit 0
fi

docker_daemon_available=0
if command -v docker >/dev/null 2>&1; then
  if docker info >/dev/null 2>&1; then
    docker_daemon_available=1
  elif [[ "$allow_docker_fallback" != "0" ]]; then
    echo "warning: docker is installed but the daemon is unavailable; skipping docker fallback" >&2
  fi
fi

if [[ "$allow_docker_fallback" != "0" ]] && [[ "$docker_daemon_available" == "1" ]]; then
  cfg_rel="docs/formal/sumeragi/$(basename "$cfg_file")"
  spec_rel="docs/formal/sumeragi/$(basename "$spec_file")"
  run_rel="target/apalache/sumeragi-$mode"
  out_rel="target/apalache/out"

  run_with_expected_status docker run --rm \
    --user "$(id -u):$(id -g)" \
    --volume "$root_dir:/work" \
    --workdir /work \
    "$apalache_docker_image" \
    apalache-mc --out-dir="$out_rel" check --length="$apalache_length" --config="$cfg_rel" --run-dir="$run_rel" "$spec_rel"
  exit 0
fi

echo "error: '$apalache_bin' not found; install Apalache or set APALACHE_BIN" >&2
if [[ "$allow_docker_fallback" != "0" ]]; then
  if command -v docker >/dev/null 2>&1 && [[ "$docker_daemon_available" != "1" ]]; then
    echo "hint: start Docker daemon and rerun, or set APALACHE_ALLOW_DOCKER=0" >&2
  else
    echo "hint: install Docker and use APALACHE_DOCKER_IMAGE=${apalache_docker_image} fallback" >&2
  fi
fi
exit 127
