"""Canonical Kura replica-retention source-binding contract data.

This data-only module keeps the multilane structural checker below its source
budget without performing validation, filesystem access, or digest work at
import time. The owning checker imports only the reviewed constants below.
"""

from __future__ import annotations

KURA_RETENTION_CONTRACT_KEY = "kura_replica_retention_contract"
KURA_RETENTION_MODULE = "SumeragiV2KuraReplicaRetention"
KURA_RETENTION_POSITIVE_CONFIG = "kura_replica_retention_fixed.cfg"
KURA_RETENTION_REFINEMENT_OBLIGATION = (
    "KuraReplicaRetentionProductionRefinementObligation"
)
KURA_RETENTION_INVARIANTS = (
    "KRAdmittedAdvertsSigned",
    "KRAdmittedAdvertsDirectAuthenticated",
    "KRAdmittedAdvertsBindExactFinality",
    "KRAdmittedAdvertsBindExactWire",
    "KRDeterministicFPlusOneKeepers",
    "KRLocalSelectedKeeperPinsBody",
    "KREvictionRequiresAllSelectedRemoteFresh",
    "KRExpiredAdvertsCannotAuthorize",
    "KRRestartClearsAdvertRegistry",
    "KRRegistryCapacityBounded",
    "KRRefreshWindowBounded",
    "KRRefreshCursorExact",
    "KRFinalPreStageRecheck",
)
KURA_RETENTION_MUTATIONS = (
    ("kura_replica_forged_signature_bug.cfg", "KRAdmittedAdvertsSigned"),
    (
        "kura_replica_relayed_advert_bug.cfg",
        "KRAdmittedAdvertsDirectAuthenticated",
    ),
    (
        "kura_replica_wrong_finality_identity_bug.cfg",
        "KRAdmittedAdvertsBindExactFinality",
    ),
    (
        "kura_replica_wrong_wire_identity_bug.cfg",
        "KRAdmittedAdvertsBindExactWire",
    ),
    (
        "kura_replica_keeper_cardinality_bug.cfg",
        "KRDeterministicFPlusOneKeepers",
    ),
    (
        "kura_replica_nonsigner_keeper_bug.cfg",
        "KRDeterministicFPlusOneKeepers",
    ),
    (
        "kura_replica_local_keeper_evict_bug.cfg",
        "KRLocalSelectedKeeperPinsBody",
    ),
    (
        "kura_replica_partial_remote_freshness_bug.cfg",
        "KREvictionRequiresAllSelectedRemoteFresh",
    ),
    (
        "kura_replica_ttl_expiry_bug.cfg",
        "KRExpiredAdvertsCannotAuthorize",
    ),
    (
        "kura_replica_restart_registry_reuse_bug.cfg",
        "KRRestartClearsAdvertRegistry",
    ),
    (
        "kura_replica_registry_capacity_overflow_bug.cfg",
        "KRRegistryCapacityBounded",
    ),
    (
        "kura_replica_refresh_window_oversize_bug.cfg",
        "KRRefreshWindowBounded",
    ),
    (
        "kura_replica_refresh_cursor_skip_bug.cfg",
        "KRRefreshCursorExact",
    ),
    (
        "kura_replica_skip_final_prestage_recheck_bug.cfg",
        "KRFinalPreStageRecheck",
    ),
)
KURA_RETENTION_REQUIRED_BINDINGS = (
    (
        "crates/iroha_core/src/sumeragi/message.rs",
        "struct",
        "KuraReplicaAdvertV1",
        (
            "version: u16",
            "chain_id: ChainId",
            "height: u64",
            "block_hash: HashOf<BlockHeader>",
            "executed_block_wire_len: u64",
            "executed_block_wire_hash: Hash",
            "finality_artifact_hash: HashOf<V2FinalityArtifact>",
            "keeper_index: u32",
            "keeper: PeerId",
            "signature: Vec<u8>",
        ),
    ),
    (
        "crates/iroha_core/src/sumeragi/message.rs",
        "method",
        "KuraReplicaAdvertV1::signature_preimage",
        (
            "KURA_REPLICA_ADVERT_SIGNATURE_DOMAIN_V1",
            "version: self.version",
            "chain_id: self.chain_id.clone()",
            "height: self.height",
            "block_hash: self.block_hash",
            "executed_block_wire_len: self.executed_block_wire_len",
            "executed_block_wire_hash: self.executed_block_wire_hash",
            "finality_artifact_hash: self.finality_artifact_hash",
            "keeper_index: self.keeper_index",
            "keeper: self.keeper.clone()",
        ),
    ),
    (
        "crates/iroha_core/src/sumeragi/message.rs",
        "method",
        "KuraReplicaAdvertV1::verify_keeper_signature",
        (
            "self.version != KURA_REPLICA_ADVERT_VERSION_V1",
            "self.executed_block_wire_len > MAX_EXECUTED_BLOCK_WIRE_BYTES",
            "self.signature.len() != KURA_REPLICA_ADVERT_SIGNATURE_BYTES",
            "self.encode().len() > MAX_KURA_REPLICA_ADVERT_WIRE_BYTES",
            "Signature::try_from_bytes(&self.signature)",
            ".verify(self.keeper.public_key(), &self.signature_preimage())",
        ),
    ),
    (
        "crates/iroha_core/src/sumeragi/v2_runner.rs",
        "fn",
        "admit_kura_replica_advert_ingress",
        (
            "let authenticated_via = inbound.via().cloned()",
            "matches_semantic_origin(inbound.sender())",
            "sender.as_ref() != Some(&advertised_keeper)",
            "authenticated_via.as_ref() != Some(&advertised_keeper)",
            "advert.keeper != advertised_keeper",
            "kura.admit_kura_replica_advert(&advert)",
        ),
    ),
    (
        "crates/iroha_config/src/parameters/actual.rs",
        "method",
        "KuraReplicaAdvertPolicy::validate",
        (
            "self.eviction_required_replicas.get() > KURA_REPLICA_ADVERT_KEEPERS_PER_KEY_LIMIT",
            "kura_replica_advert_registry_key_capacity(blocks_in_memory, self.evictable_window)",
            "KuraReplicaAdvertPolicyError::RegistryKeyCapacityOverflow",
            "kura_replica_advert_registry_entry_capacity(blocks_in_memory, self.evictable_window)",
            "KuraReplicaAdvertPolicyError::RegistryEntryCapacityOverflow",
            "self.ttl < KURA_REPLICA_ADVERT_TTL_MIN",
            "self.ttl > KURA_REPLICA_ADVERT_TTL_MAX",
            "self.refresh_interval < KURA_REPLICA_ADVERT_REFRESH_INTERVAL_MIN",
            "KuraReplicaAdvertPolicyError::RefreshIntervalBelowMinimum",
            "self.refresh_interval > self.ttl.checked_div(2).unwrap_or_default()",
            "Ok(key_capacity)",
        ),
    ),
    (
        "crates/iroha_config/src/parameters/actual.rs",
        "fn",
        "kura_replica_advert_registry_key_capacity",
        (
            "blocks_in_memory\n        .get()\n        .checked_add(evictable_window.get())",
            ".and_then(NonZeroUsize::new)",
        ),
    ),
    (
        "crates/iroha_config/src/parameters/actual.rs",
        "fn",
        "kura_replica_advert_registry_entry_capacity",
        (
            "kura_replica_advert_registry_key_capacity(blocks_in_memory, evictable_window)?",
            ".checked_mul(KURA_REPLICA_ADVERT_KEEPERS_PER_KEY_LIMIT)",
            ".and_then(NonZeroUsize::new)",
        ),
    ),
    (
        "crates/iroha_core/src/kura/replica_advert_and_body_status.rs",
        "struct",
        "KuraReplicaAdvertSourceV1",
        (
            "chain_id: ChainId",
            "height: u64",
            "block_hash: HashOf<BlockHeader>",
            "executed_block_wire_len: u64",
            "executed_block_wire_hash: Hash",
            "finality_artifact_hash: HashOf<V2FinalityArtifact>",
            "keeper_index: u32",
            "keeper: PeerId",
        ),
    ),
    (
        "crates/iroha_core/src/kura/replica_advert_and_body_status.rs",
        "method",
        "Kura::bind_local_peer_id",
        (
            "self.local_peer_id.get()",
            "self.local_peer_id.set(peer)",
            "Error::KuraReplicaLocalPeerConflict",
        ),
    ),
    (
        "crates/iroha_core/src/kura.rs",
        "method",
        "Kura::start",
        (
            "kura.local_peer_id.get().is_none()",
            "Error::KuraReplicaLocalPeerUnbound",
            "kura.ensure_snapshot_bootstrap_authenticated()?",
            "kura.ensure_canonical_storage_not_poisoned()?",
        ),
    ),
    (
        "crates/iroha_core/src/kura/tests/04_merge_log_and_associations.rs",
        "fn",
        "kura_start_rejects_unbound_local_peer_identity",
        (
            "let kura = Kura::blank_kura_for_testing()",
            "Kura::start(kura, ShutdownSignal::new())",
            "Err(Error::KuraReplicaLocalPeerUnbound)",
        ),
    ),
    (
        "crates/irohad/src/main.rs",
        "method",
        "Iroha::start_with_runtime_deps",
        (
            "kura.bind_local_peer_id(PeerId::new(config.common.key_pair.public_key().clone()))",
            "failed to bind the configured node identity to Kura before runtime start",
            "Kura::start(kura.clone(), supervisor.shutdown_signal())",
        ),
    ),
    (
        "crates/irohad/src/main.rs",
        "fn",
        "standard_launcher_binds_kura_local_peer_before_start",
        (
            "let construct = compact_source",
            "let bind = compact_source",
            "let start = compact_source",
            "construct < bind && bind < start",
        ),
    ),
    (
        "crates/iroha_core/src/kura.rs",
        "method",
        "Kura::new_inner",
        (
            "let replica_registry_key_capacity = config",
            ".replica_advert\n            .validate(config.blocks_in_memory)",
            "Error::InvalidKuraReplicaAdvertConfiguration(error.to_string())",
            "eviction_required_replicas: config.replica_advert.eviction_required_replicas",
            "local_peer_id: OnceLock::new()",
            "replica_registry: Mutex::new(BTreeMap::new())",
            "replica_registry_key_capacity,",
            "replica_advert_evictable_window: config.replica_advert.evictable_window",
            "replica_advert_ttl: config.replica_advert.ttl",
            "replica_advert_refresh_interval: config.replica_advert.refresh_interval",
        ),
    ),
    (
        "crates/iroha_core/src/kura/replica_advert_and_body_status.rs",
        "method",
        "Kura::exact_kura_replica_advert_tip",
        (
            "let _prune_guard = self.prune_lock.lock()",
            "let _canonical_chain_guard = self.canonical_chain_lock.lock()",
            "let height = store.read_exact_durable_index_count()?",
            "Self::read_durable_hash_at_height(&mut store, height)?",
            "Ok(Some((height, hash)))",
        ),
    ),
    (
        "crates/iroha_core/src/kura/replica_advert_and_body_status.rs",
        "method",
        "Kura::probe_kura_replica_advert_source",
        (
            "let keeper = PeerId::new(local_key.public_key().clone())",
            "self.local_peer_id.get() != Some(&keeper)",
            "let _prune_guard = self.prune_lock.lock()",
            "let _canonical_chain_guard = self.canonical_chain_lock.lock()",
            "self.probe_kura_replica_advert_source_under_guards(height, &keeper)",
        ),
    ),
    (
        "crates/iroha_core/src/kura/replica_advert_and_body_status.rs",
        "method",
        "Kura::build_signed_kura_replica_advert_from_source",
        (
            "source.keeper != keeper || self.local_peer_id.get() != Some(&keeper)",
            "let _prune_guard = self.prune_lock.lock()",
            "let _canonical_chain_guard = self.canonical_chain_lock.lock()",
            ".probe_kura_replica_advert_source_under_guards(source.height, &keeper)?",
            "if &current != source",
            "self.verify_complete_kura_replica_body_under_guards(source)?",
            "Signature::try_new(local_key.private_key(), &advert.signature_preimage())",
            ".verify_keeper_signature()",
        ),
    ),
    (
        "crates/iroha_core/src/kura/replica_advert_and_body_status.rs",
        "method",
        "Kura::revalidate_kura_replica_advert_source",
        (
            ".verify_keeper_signature()",
            "self.local_peer_id.get() != Some(&advert.keeper)",
            "let _prune_guard = self.prune_lock.lock()",
            "let _canonical_chain_guard = self.canonical_chain_lock.lock()",
            "let source = KuraReplicaAdvertSourceV1::from_advert(advert)",
            ".probe_kura_replica_advert_source_under_guards(advert.height, &advert.keeper)?",
            "if current != source",
            "self.verify_complete_kura_replica_body_under_guards(&source)?",
        ),
    ),
    (
        "crates/iroha_core/src/sumeragi/v2_worker/kura_replica_advert_refresh.rs",
        "struct",
        "KuraReplicaAdvertRefreshWindow",
        (
            "durable_tip: u64",
            "evictable_start: u64",
            "evictable_len: u64",
            "tail_start: u64",
            "tail_len: u64",
        ),
    ),
    (
        "crates/iroha_core/src/sumeragi/v2_worker/kura_replica_advert_refresh.rs",
        "method",
        "KuraReplicaAdvertRefreshCursor::next_height",
        (
            "self.window.height_at(self.next_offset)?",
            "self.next_offset = self.next_offset.saturating_add(1)",
        ),
    ),
    (
        "crates/iroha_core/src/sumeragi/v2_worker/kura_replica_advert_refresh.rs",
        "method",
        "KuraReplicaAdvertRefreshWindow::new",
        (
            "let tail_len = durable_tip.min(protected_tail)",
            "let before_tail = durable_tip.saturating_sub(tail_len)",
            "let evictable_len = before_tail.min(evictable_window)",
            ".saturating_sub(evictable_len)",
            ".saturating_sub(tail_len)",
        ),
    ),
    (
        "crates/iroha_core/src/sumeragi/v2_worker/kura_replica_advert_refresh.rs",
        "method",
        "KuraReplicaAdvertRefreshWindow::contains",
        (
            "height == 0 || height > self.durable_tip || self.len() == 0",
            "let first = if self.evictable_len == 0",
            "height >= first",
        ),
    ),
    (
        "crates/iroha_core/src/sumeragi/v2_worker/kura_replica_advert_refresh.rs",
        "struct",
        "KuraReplicaAdvertRefreshTip",
        (
            "height: u64",
            "block_hash: HashOf<BlockHeader>",
        ),
    ),
    (
        "crates/iroha_core/src/sumeragi/v2_worker/kura_replica_advert_refresh.rs",
        "struct",
        "KuraReplicaAdvertRefreshState",
        (
            "observed_durable_tip: Option<KuraReplicaAdvertRefreshTip>",
            "cursor: Option<KuraReplicaAdvertRefreshCursor>",
            "retained_source: Option<KuraReplicaAdvertSourceV1>",
            "urgent_heights: BTreeSet<u64>",
            "next_cycle_at: Instant",
            "follow_up_cycle_requested: bool",
        ),
    ),
    (
        "crates/iroha_core/src/sumeragi/v2_worker/kura_replica_advert_refresh.rs",
        "method",
        "KuraReplicaAdvertRefreshState::note_durable_tip",
        (
            "previous.height == current.height && previous.block_hash == current.block_hash",
            "current.height <= previous.height",
            "self.retained_source = None",
            "self.follow_up_cycle_requested = true",
        ),
    ),
    (
        "crates/iroha_core/src/sumeragi/v2_worker/kura_replica_advert_refresh.rs",
        "method",
        "KuraReplicaAdvertRefreshOwner::from_kura",
        (
            "kura.blocks_in_memory().get()",
            "kura.replica_advert_evictable_window().get()",
            ".exact_kura_replica_advert_tip()",
            ".map(|(height, block_hash)| KuraReplicaAdvertRefreshTip::new(height, block_hash))",
            "kura.replica_advert_refresh_interval()",
        ),
    ),
    (
        "crates/iroha_core/src/sumeragi/v2_worker/kura_replica_advert_refresh.rs",
        "method",
        "KuraReplicaAdvertRefreshOwner::new",
        (
            "refresh_interval < KURA_REPLICA_ADVERT_REFRESH_INTERVAL_MIN",
            "now.checked_add(refresh_interval)",
            "protected_tail",
            "evictable_window",
            "refresh_interval",
            "state: Mutex::new(KuraReplicaAdvertRefreshState::new(initial_durable_tip, now))",
        ),
    ),
    (
        "crates/iroha_core/src/sumeragi/v2_worker/kura_replica_advert_refresh.rs",
        "method",
        "KuraReplicaAdvertRefreshOwner::note_durable_tip",
        (
            "tip: Option<(u64, HashOf<BlockHeader>)>",
            "tip.is_some_and(|(height, _)| height == 0)",
            "tip.map(|(height, block_hash)| KuraReplicaAdvertRefreshTip::new(height, block_hash))",
            "let active_window = KuraReplicaAdvertRefreshWindow::new(",
            ".retain(|height| active_window.contains(*height))",
        ),
    ),
    (
        "crates/iroha_core/src/sumeragi/v2_worker/kura_replica_advert_refresh.rs",
        "method",
        "KuraReplicaAdvertRefreshOwner::schedule_retired_exact_output_heights",
        (
            "let active_window = KuraReplicaAdvertRefreshWindow::new(",
            "active_window.contains(height) && state.urgent_heights.insert(height)",
            "scheduled.checked_add(1)",
            "state.next_cycle_at = now",
            "u64::try_from(state.urgent_heights.len())",
            ".is_ok_and(|count| count <= active_window.len())",
        ),
    ),
    (
        "crates/iroha_core/src/sumeragi/v2_worker/kura_replica_advert_refresh.rs",
        "method",
        "KuraReplicaAdvertRefreshOwner::drive_turn",
        (
            "if let Some(source) = state.retained_source.as_ref()",
            "KuraReplicaAdvertRefreshWindow::new(",
            "anchor.map_or(0, |tip| tip.height)",
            "while outcome.probes < KURA_REPLICA_ADVERT_REFRESH_PROBES_PER_TURN",
            "state.urgent_heights.pop_first()",
            ".and_then(KuraReplicaAdvertRefreshCursor::next_height)",
            "if transfer(&source)? == ExactFanoutOwnership::SourceRetained",
            "cursor.anchor != state.observed_durable_tip",
            "let next_cycle_at = now.checked_add(self.refresh_interval)",
            "state.cursor = Some(KuraReplicaAdvertRefreshCursor::new(",
            "state.next_cycle_at = next_cycle_at",
            "state.cursor.is_some() || !state.urgent_heights.is_empty()",
        ),
    ),
    (
        "crates/iroha_core/src/sumeragi/v2_worker.rs",
        "method",
        "ProductionV2Services::service_kura_replica_advert_refresh_turn",
        (
            "self.exact_output_handoff_owner.is_sealed()",
            ".exact_kura_replica_advert_tip()",
            ".note_durable_tip(durable_tip, now)?",
            ".begin_fail_stop_operation()",
            ".probe_kura_replica_advert_source(source_height, &self.key_pair)",
            "|source| self.post_kura_replica_advert_while_guarded(source, operation.permit())",
            "operation.complete()",
        ),
    ),
    (
        "crates/iroha_core/src/sumeragi/v2_worker.rs",
        "method",
        "PendingExactOutput::pending_kura_replica_advert_heights",
        (
            "let mut heights = BTreeSet::new()",
            "ExactOutputRolloverClaim::DurableKuraReplicaAdvert",
            ".validate_fanout(&fanout.messages, &fanout.semantic_peers())?",
            "if *source_height == 0",
            "heights.insert(*source_height)",
        ),
    ),
    (
        "crates/iroha_core/src/sumeragi/v2_worker.rs",
        "method",
        "ProductionV2Services::handoff_applied_height_output_to_durable_reconstruction",
        (
            "let retired_kura_replica_advert_heights =",
            "pending.pending_kura_replica_advert_heights()?",
            "pending.handoff_applied_height_to_durable_reconstruction(",
            ".schedule_retired_exact_output_heights(",
            "retired_kura_replica_advert_heights",
            "operation.complete()",
        ),
    ),
    (
        "crates/iroha_core/src/sumeragi/v2_worker.rs",
        "method",
        "ProductionV2Services::post_kura_replica_advert_while_guarded",
        (
            "let source_height = source.height()",
            "source_height == 0 || source_height > self.context.height",
            ".build_signed_kura_replica_advert_from_source(source, &self.key_pair)",
            "ExactOutputRolloverClaim::DurableKuraReplicaAdvert",
            "advert_hash: HashOf::new(&advert)",
            "BlockMessage::KuraReplicaAdvert(advert)",
            "self.remote_voters()",
            "self.enqueue_exact_fanout_while_guarded(",
        ),
    ),
    (
        "crates/iroha_core/src/sumeragi/v2_runner.rs",
        "fn",
        "run_inner",
        (
            "let kura_replica_advert_refresh = Arc::new(",
            "KuraReplicaAdvertRefreshOwner::from_kura(kura.as_ref(), Instant::now())",
            "Arc::clone(&kura_replica_advert_refresh)",
            ".service_kura_replica_advert_refresh_turn(Instant::now())",
        ),
    ),
    (
        "crates/iroha_core/src/kura/retained_finality_replica_authority.rs",
        "method",
        "Kura::deterministic_kura_replica_keepers",
        (
            "artifact.height_context.quorum.min_signers",
            "validator_count.checked_sub(quorum_count)",
            ".saturating_add(1)",
            ".max(self.eviction_required_replicas.get())",
            "artifact.commit_qc.signers",
            "KURA_REPLICA_KEEPER_SELECTION_DOMAIN_V1",
            ".then_with(|| left.1.cmp(&right.1))",
            ".take(required)",
        ),
    ),
    (
        "crates/iroha_core/src/kura/retained_finality_replica_authority.rs",
        "method",
        "Kura::verified_kura_replica_authority_for_eviction",
        (
            "validate_v2_finality_wire_bindings",
            "verify_v2_finality_artifact_at",
            "finality_artifact_hash: HashOf::new(&record.artifact)",
            "selected_keepers = self.deterministic_kura_replica_keepers",
        ),
    ),
    (
        "crates/iroha_core/src/kura/replica_advert_and_body_status.rs",
        "method",
        "Kura::verified_kura_replica_advert_authority_under_guards",
        (
            "canonical_hash != advert.block_hash",
            "index.length != advert.executed_block_wire_len",
            "advert.finality_artifact_hash != authority.key.finality_artifact_hash",
            "advert.executed_block_wire_hash != authority.key.executed_block_wire_hash",
            "*index == advert.keeper_index && peer == &advert.keeper",
        ),
    ),
    (
        "crates/iroha_core/src/kura/replica_advert_and_body_status.rs",
        "method",
        "Kura::admit_kura_replica_advert",
        (
            ".verify_keeper_signature()",
            "verified_kura_replica_advert_authority_under_guards",
            "self.replica_registry_height_horizon(canonical_tip)",
            "now.saturating_duration_since(observation.observed_at) <= self.replica_advert_ttl",
            "self.replica_registry_capacity()",
            "prospective_keys > registry_cap",
            "KURA_REPLICA_ADVERT_KEEPERS_PER_KEY_LIMIT",
            "self.prune_replica_adverts_for_horizon(",
            "key.height != authority.key.height || key == &authority.key",
            "registry.entry(authority.key).or_default().insert",
        ),
    ),
    (
        "crates/iroha_core/src/kura/replica_advert_and_body_status.rs",
        "method",
        "Kura::prune_replica_adverts_for_horizon",
        (
            "now.saturating_duration_since(advert.observed_at) <= self.replica_advert_ttl",
            "!peers.is_empty()",
            "key.height >= minimum_height && key.height <= maximum_height",
        ),
    ),
    (
        "crates/iroha_core/src/kura/replica_advert_and_body_status.rs",
        "method",
        "Kura::replica_registry_capacity",
        (
            "self.replica_registry_key_capacity.get()",
        ),
    ),
    (
        "crates/iroha_core/src/kura/replica_advert_and_body_status.rs",
        "method",
        "Kura::matching_selected_keeper_count",
        (
            "self.replica_registry_height_horizon(canonical_tip)",
            "self.prune_replica_adverts_for_horizon(",
            ".selected_keepers",
            "advert.keeper_index == *index",
        ),
    ),
    (
        "crates/iroha_core/src/kura/replica_advert_and_body_status.rs",
        "method",
        "Kura::has_all_selected_remote_keepers",
        (
            "self.local_peer_id.get()",
            "authority.selected_keepers.is_empty()",
            ".any(|(_, keeper)| keeper == local_peer)",
            "self.matching_selected_keeper_count(authority, canonical_tip)",
            "== authority.selected_keepers.len()",
        ),
    ),
    (
        "crates/iroha_core/src/kura.rs",
        "method",
        "Kura::evict_block_bodies_unlocked",
        (
            "verified_kura_replica_authority_for_eviction",
            "has_all_selected_remote_keepers",
            "maybe_pause_eviction_before_stage_publication_for_tests",
            "current_authority.key == *expected_authority",
            "cleanup_unpublished_eviction_compaction_files",
            "write_eviction_compaction_stage",
        ),
    ),
)
KURA_RETENTION_PRESTAGE_ORDERED_TOKENS = (
    "self.maybe_pause_eviction_before_stage_publication_for_tests();",
    "let fresh_authority = if eviction_authorities.len() == evicted.len() {",
    "current_authority.key == *expected_authority",
    "&& self.has_all_selected_remote_keepers(",
    "if !fresh_authority {",
    "let stage = EvictionCompactionStageV1 {",
    "block_store.write_eviction_compaction_stage(&stage)",
)
KURA_RETENTION_HANDOFF_ORDERED_TOKENS = (
    "let retired_kura_replica_advert_heights =",
    "pending.pending_kura_replica_advert_heights()?;",
    "let retired = pending.handoff_applied_height_to_durable_reconstruction(",
    "let scheduled_kura_replica_adverts = self",
    ".schedule_retired_exact_output_heights(",
    "operation.complete();",
)
KURA_RETENTION_REFRESH_START_ORDERED_TOKENS = (
    "let next_cycle_at = now.checked_add(self.refresh_interval).ok_or_else(|| {",
    "state.cursor = Some(KuraReplicaAdvertRefreshCursor::new(",
    "state.next_cycle_at = next_cycle_at;",
)
