#!/bin/bash
set -euo pipefail

mode="${1:-frontier-small}"
root_dir="$(cd "$(dirname "$0")/../.." && pwd)"
spec_dir="$root_dir/docs/formal/sumeragi"
apalache_version="${APALACHE_VERSION:-0.52.2}"
default_tlc_jar="$root_dir/target/apalache/toolchains/v${apalache_version}/lib/apalache.jar"
expect_failure=0

case "$mode" in
  frontier-small)
    module="SumeragiFrontierRecovery"
    cfg_file="$spec_dir/SumeragiFrontierRecovery_tlc_small.cfg"
    ;;
  validation-redrive-label-fast)
    module="SumeragiValidationRedriveLabelGate"
    cfg_file="$spec_dir/SumeragiValidationRedriveLabelGate_fast.cfg"
    ;;
  validation-redrive-label-bug-*)
    bug_name="${mode#validation-redrive-label-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiValidationRedriveLabelGate"
    cfg_file="$spec_dir/SumeragiValidationRedriveLabelGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  validation-ownership-cleanup-fast)
    module="SumeragiValidationOwnershipCleanupGate"
    cfg_file="$spec_dir/SumeragiValidationOwnershipCleanupGate_fast.cfg"
    ;;
  validation-ownership-cleanup-bug-*)
    bug_name="${mode#validation-ownership-cleanup-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiValidationOwnershipCleanupGate"
    cfg_file="$spec_dir/SumeragiValidationOwnershipCleanupGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  worker-loop-stage-fast)
    module="SumeragiWorkerLoopStageGate"
    cfg_file="$spec_dir/SumeragiWorkerLoopStageGate_fast.cfg"
    ;;
  worker-loop-stage-bug-*)
    bug_name="${mode#worker-loop-stage-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiWorkerLoopStageGate"
    cfg_file="$spec_dir/SumeragiWorkerLoopStageGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  worker-tick-gap-fast)
    module="SumeragiWorkerTickGapGate"
    cfg_file="$spec_dir/SumeragiWorkerTickGapGate_fast.cfg"
    ;;
  worker-tick-gap-bug-*)
    bug_name="${mode#worker-tick-gap-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiWorkerTickGapGate"
    cfg_file="$spec_dir/SumeragiWorkerTickGapGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  vnext-performance-config-fast)
    module="SumeragiVNextPerformanceConfigGate"
    cfg_file="$spec_dir/SumeragiVNextPerformanceConfigGate_fast.cfg"
    ;;
  vnext-performance-config-bug-*)
    bug_name="${mode#vnext-performance-config-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiVNextPerformanceConfigGate"
    cfg_file="$spec_dir/SumeragiVNextPerformanceConfigGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  validation-worker-config-fast)
    module="SumeragiValidationWorkerConfigGate"
    cfg_file="$spec_dir/SumeragiValidationWorkerConfigGate_fast.cfg"
    ;;
  validation-worker-config-bug-*)
    bug_name="${mode#validation-worker-config-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiValidationWorkerConfigGate"
    cfg_file="$spec_dir/SumeragiValidationWorkerConfigGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  commit-worker-config-fast)
    module="SumeragiCommitWorkerConfigGate"
    cfg_file="$spec_dir/SumeragiCommitWorkerConfigGate_fast.cfg"
    ;;
  commit-worker-config-bug-*)
    bug_name="${mode#commit-worker-config-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiCommitWorkerConfigGate"
    cfg_file="$spec_dir/SumeragiCommitWorkerConfigGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  commit-stage-timing-threshold-fast)
    module="SumeragiCommitStageTimingThresholdGate"
    cfg_file="$spec_dir/SumeragiCommitStageTimingThresholdGate_fast.cfg"
    ;;
  commit-stage-timing-threshold-bug-*)
    bug_name="${mode#commit-stage-timing-threshold-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiCommitStageTimingThresholdGate"
    cfg_file="$spec_dir/SumeragiCommitStageTimingThresholdGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  commit-inflight-timeout-fast)
    module="SumeragiCommitInflightTimeoutGate"
    cfg_file="$spec_dir/SumeragiCommitInflightTimeoutGate_fast.cfg"
    ;;
  commit-inflight-timeout-bug-*)
    bug_name="${mode#commit-inflight-timeout-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiCommitInflightTimeoutGate"
    cfg_file="$spec_dir/SumeragiCommitInflightTimeoutGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  post-commit-pacemaker-kick-fast)
    module="SumeragiPostCommitPacemakerKickGate"
    cfg_file="$spec_dir/SumeragiPostCommitPacemakerKickGate_fast.cfg"
    ;;
  post-commit-pacemaker-kick-bug-*)
    bug_name="${mode#post-commit-pacemaker-kick-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiPostCommitPacemakerKickGate"
    cfg_file="$spec_dir/SumeragiPostCommitPacemakerKickGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  idle-view-proposal-budget-fast)
    module="SumeragiIdleViewProposalBudgetGate"
    cfg_file="$spec_dir/SumeragiIdleViewProposalBudgetGate_fast.cfg"
    ;;
  idle-view-proposal-budget-bug-*)
    bug_name="${mode#idle-view-proposal-budget-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiIdleViewProposalBudgetGate"
    cfg_file="$spec_dir/SumeragiIdleViewProposalBudgetGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  cached-slot-timeout-fast)
    module="SumeragiCachedSlotTimeoutGate"
    cfg_file="$spec_dir/SumeragiCachedSlotTimeoutGate_fast.cfg"
    ;;
  cached-slot-timeout-bug-*)
    bug_name="${mode#cached-slot-timeout-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiCachedSlotTimeoutGate"
    cfg_file="$spec_dir/SumeragiCachedSlotTimeoutGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  pending-fast-path-timeout-fast)
    module="SumeragiPendingFastPathTimeoutGate"
    cfg_file="$spec_dir/SumeragiPendingFastPathTimeoutGate_fast.cfg"
    ;;
  pending-fast-path-timeout-bug-*)
    bug_name="${mode#pending-fast-path-timeout-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiPendingFastPathTimeoutGate"
    cfg_file="$spec_dir/SumeragiPendingFastPathTimeoutGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  stalled-pending-timeout-fast)
    module="SumeragiStalledPendingTimeoutDecisionGate"
    cfg_file="$spec_dir/SumeragiStalledPendingTimeoutDecisionGate_fast.cfg"
    ;;
  stalled-pending-timeout-bug-*)
    bug_name="${mode#stalled-pending-timeout-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiStalledPendingTimeoutDecisionGate"
    cfg_file="$spec_dir/SumeragiStalledPendingTimeoutDecisionGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  stalled-pending-frontier-timeout-fast)
    module="SumeragiStalledPendingFrontierTimeoutGate"
    cfg_file="$spec_dir/SumeragiStalledPendingFrontierTimeoutGate_fast.cfg"
    ;;
  stalled-pending-frontier-timeout-bug-*)
    bug_name="${mode#stalled-pending-frontier-timeout-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiStalledPendingFrontierTimeoutGate"
    cfg_file="$spec_dir/SumeragiStalledPendingFrontierTimeoutGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  frontier-proposal-grace-fast)
    module="SumeragiFrontierProposalGraceGate"
    cfg_file="$spec_dir/SumeragiFrontierProposalGraceGate_fast.cfg"
    ;;
  frontier-proposal-grace-bug-*)
    bug_name="${mode#frontier-proposal-grace-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiFrontierProposalGraceGate"
    cfg_file="$spec_dir/SumeragiFrontierProposalGraceGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  frontier-slot-helpers-fast)
    module="SumeragiFrontierSlotHelpersGate"
    cfg_file="$spec_dir/SumeragiFrontierSlotHelpersGate_fast.cfg"
    ;;
  frontier-slot-helpers-bug-*)
    bug_name="${mode#frontier-slot-helpers-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiFrontierSlotHelpersGate"
    cfg_file="$spec_dir/SumeragiFrontierSlotHelpersGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  frontier-slot-tracker-fast)
    module="SumeragiFrontierSlotTrackerGate"
    cfg_file="$spec_dir/SumeragiFrontierSlotTrackerGate_fast.cfg"
    ;;
  frontier-slot-tracker-bug-*)
    bug_name="${mode#frontier-slot-tracker-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiFrontierSlotTrackerGate"
    cfg_file="$spec_dir/SumeragiFrontierSlotTrackerGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  slot-tracker-state-fast)
    module="SumeragiSlotTrackerStateGate"
    cfg_file="$spec_dir/SumeragiSlotTrackerStateGate_fast.cfg"
    ;;
  slot-tracker-state-bug-*)
    bug_name="${mode#slot-tracker-state-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiSlotTrackerStateGate"
    cfg_file="$spec_dir/SumeragiSlotTrackerStateGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  timeout-derivation-fast)
    module="SumeragiTimeoutDerivationGate"
    cfg_file="$spec_dir/SumeragiTimeoutDerivationGate_fast.cfg"
    ;;
  timeout-derivation-bug-*)
    bug_name="${mode#timeout-derivation-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiTimeoutDerivationGate"
    cfg_file="$spec_dir/SumeragiTimeoutDerivationGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  round-view-helpers-fast)
    module="SumeragiRoundViewHelpersGate"
    cfg_file="$spec_dir/SumeragiRoundViewHelpersGate_fast.cfg"
    ;;
  round-view-helpers-bug-*)
    bug_name="${mode#round-view-helpers-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiRoundViewHelpersGate"
    cfg_file="$spec_dir/SumeragiRoundViewHelpersGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  phase-tracker-fast)
    module="SumeragiPhaseTrackerGate"
    cfg_file="$spec_dir/SumeragiPhaseTrackerGate_fast.cfg"
    ;;
  phase-tracker-bug-*)
    bug_name="${mode#phase-tracker-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiPhaseTrackerGate"
    cfg_file="$spec_dir/SumeragiPhaseTrackerGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  failure-recovery-helpers-fast)
    module="SumeragiFailureRecoveryHelpersGate"
    cfg_file="$spec_dir/SumeragiFailureRecoveryHelpersGate_fast.cfg"
    ;;
  failure-recovery-helpers-bug-*)
    bug_name="${mode#failure-recovery-helpers-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiFailureRecoveryHelpersGate"
    cfg_file="$spec_dir/SumeragiFailureRecoveryHelpersGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  missing-qc-timing-fast)
    module="SumeragiMissingQcTimingGate"
    cfg_file="$spec_dir/SumeragiMissingQcTimingGate_fast.cfg"
    ;;
  missing-qc-timing-bug-*)
    bug_name="${mode#missing-qc-timing-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiMissingQcTimingGate"
    cfg_file="$spec_dir/SumeragiMissingQcTimingGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  idle-backlog-signals-fast)
    module="SumeragiIdleBacklogSignalsGate"
    cfg_file="$spec_dir/SumeragiIdleBacklogSignalsGate_fast.cfg"
    ;;
  idle-backlog-signals-bug-*)
    bug_name="${mode#idle-backlog-signals-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiIdleBacklogSignalsGate"
    cfg_file="$spec_dir/SumeragiIdleBacklogSignalsGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  proposal-liveness-fast)
    module="SumeragiProposalLivenessGate"
    cfg_file="$spec_dir/SumeragiProposalLivenessGate_fast.cfg"
    ;;
  proposal-liveness-bug-*)
    bug_name="${mode#proposal-liveness-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiProposalLivenessGate"
    cfg_file="$spec_dir/SumeragiProposalLivenessGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  actionable-vote-backed-proposal-fast)
    module="SumeragiActionableVoteBackedProposalGate"
    cfg_file="$spec_dir/SumeragiActionableVoteBackedProposalGate_fast.cfg"
    ;;
  actionable-vote-backed-proposal-bug-*)
    bug_name="${mode#actionable-vote-backed-proposal-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiActionableVoteBackedProposalGate"
    cfg_file="$spec_dir/SumeragiActionableVoteBackedProposalGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  slot-proposal-evidence-fast)
    module="SumeragiSlotProposalEvidenceGate"
    cfg_file="$spec_dir/SumeragiSlotProposalEvidenceGate_fast.cfg"
    ;;
  slot-proposal-evidence-bug-*)
    bug_name="${mode#slot-proposal-evidence-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiSlotProposalEvidenceGate"
    cfg_file="$spec_dir/SumeragiSlotProposalEvidenceGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  round-liveness-fast)
    module="SumeragiRoundLivenessGate"
    cfg_file="$spec_dir/SumeragiRoundLivenessGate_fast.cfg"
    ;;
  round-liveness-bug-*)
    bug_name="${mode#round-liveness-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiRoundLivenessGate"
    cfg_file="$spec_dir/SumeragiRoundLivenessGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  roster-recovery-fsm-fast)
    module="SumeragiRosterRecoveryFsmGate"
    cfg_file="$spec_dir/SumeragiRosterRecoveryFsmGate_fast.cfg"
    ;;
  roster-recovery-fsm-bug-*)
    bug_name="${mode#roster-recovery-fsm-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiRosterRecoveryFsmGate"
    cfg_file="$spec_dir/SumeragiRosterRecoveryFsmGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  consensus-recovery-prune-fast)
    module="SumeragiConsensusRecoveryPruneGate"
    cfg_file="$spec_dir/SumeragiConsensusRecoveryPruneGate_fast.cfg"
    ;;
  consensus-recovery-prune-bug-*)
    bug_name="${mode#consensus-recovery-prune-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiConsensusRecoveryPruneGate"
    cfg_file="$spec_dir/SumeragiConsensusRecoveryPruneGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  frontier-live-owner-work-fast)
    module="SumeragiFrontierLiveOwnerWorkGate"
    cfg_file="$spec_dir/SumeragiFrontierLiveOwnerWorkGate_fast.cfg"
    ;;
  frontier-live-owner-work-bug-*)
    bug_name="${mode#frontier-live-owner-work-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiFrontierLiveOwnerWorkGate"
    cfg_file="$spec_dir/SumeragiFrontierLiveOwnerWorkGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  keep-frontier-pending-active-fast)
    module="SumeragiKeepFrontierPendingActiveGate"
    cfg_file="$spec_dir/SumeragiKeepFrontierPendingActiveGate_fast.cfg"
    ;;
  keep-frontier-pending-active-bug-*)
    bug_name="${mode#keep-frontier-pending-active-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiKeepFrontierPendingActiveGate"
    cfg_file="$spec_dir/SumeragiKeepFrontierPendingActiveGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  stale-view-pending-prune-fast)
    module="SumeragiStaleViewPendingPruneGate"
    cfg_file="$spec_dir/SumeragiStaleViewPendingPruneGate_fast.cfg"
    ;;
  stale-view-pending-prune-bug-*)
    bug_name="${mode#stale-view-pending-prune-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiStaleViewPendingPruneGate"
    cfg_file="$spec_dir/SumeragiStaleViewPendingPruneGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  superseded-frontier-payload-retention-fast)
    module="SumeragiSupersededFrontierPayloadRetentionGate"
    cfg_file="$spec_dir/SumeragiSupersededFrontierPayloadRetentionGate_fast.cfg"
    ;;
  superseded-frontier-payload-retention-bug-*)
    bug_name="${mode#superseded-frontier-payload-retention-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiSupersededFrontierPayloadRetentionGate"
    cfg_file="$spec_dir/SumeragiSupersededFrontierPayloadRetentionGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  stale-missing-block-request-prune-fast)
    module="SumeragiStaleMissingBlockRequestPruneGate"
    cfg_file="$spec_dir/SumeragiStaleMissingBlockRequestPruneGate_fast.cfg"
    ;;
  stale-missing-block-request-prune-bug-*)
    bug_name="${mode#stale-missing-block-request-prune-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiStaleMissingBlockRequestPruneGate"
    cfg_file="$spec_dir/SumeragiStaleMissingBlockRequestPruneGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  stale-missing-commit-qc-prune-fast)
    module="SumeragiStaleMissingCommitQcPruneGate"
    cfg_file="$spec_dir/SumeragiStaleMissingCommitQcPruneGate_fast.cfg"
    ;;
  stale-missing-commit-qc-prune-bug-*)
    bug_name="${mode#stale-missing-commit-qc-prune-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiStaleMissingCommitQcPruneGate"
    cfg_file="$spec_dir/SumeragiStaleMissingCommitQcPruneGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  stale-rbc-session-prune-fast)
    module="SumeragiStaleRbcSessionPruneGate"
    cfg_file="$spec_dir/SumeragiStaleRbcSessionPruneGate_fast.cfg"
    ;;
  stale-rbc-session-prune-bug-*)
    bug_name="${mode#stale-rbc-session-prune-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiStaleRbcSessionPruneGate"
    cfg_file="$spec_dir/SumeragiStaleRbcSessionPruneGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  highest-qc-defer-marker-prune-fast)
    module="SumeragiHighestQcDeferMarkerPruneGate"
    cfg_file="$spec_dir/SumeragiHighestQcDeferMarkerPruneGate_fast.cfg"
    ;;
  highest-qc-defer-marker-prune-bug-*)
    bug_name="${mode#highest-qc-defer-marker-prune-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiHighestQcDeferMarkerPruneGate"
    cfg_file="$spec_dir/SumeragiHighestQcDeferMarkerPruneGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  fast-finality-inline-validation-fast)
    module="SumeragiFastFinalityInlineValidationGate"
    cfg_file="$spec_dir/SumeragiFastFinalityInlineValidationGate_fast.cfg"
    ;;
  fast-finality-inline-validation-bug-*)
    bug_name="${mode#fast-finality-inline-validation-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiFastFinalityInlineValidationGate"
    cfg_file="$spec_dir/SumeragiFastFinalityInlineValidationGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  observer-signature-recovery-fast)
    module="SumeragiObserverSignatureRecoveryGate"
    cfg_file="$spec_dir/SumeragiObserverSignatureRecoveryGate_fast.cfg"
    ;;
  observer-signature-recovery-bug-*)
    bug_name="${mode#observer-signature-recovery-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiObserverSignatureRecoveryGate"
    cfg_file="$spec_dir/SumeragiObserverSignatureRecoveryGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  validation-failure-finalize-fast)
    module="SumeragiValidationFailureFinalizeGate"
    cfg_file="$spec_dir/SumeragiValidationFailureFinalizeGate_fast.cfg"
    ;;
  validation-failure-finalize-bug-*)
    bug_name="${mode#validation-failure-finalize-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiValidationFailureFinalizeGate"
    cfg_file="$spec_dir/SumeragiValidationFailureFinalizeGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  validation-reject-reason-label-fast)
    module="SumeragiValidationRejectReasonLabelGate"
    cfg_file="$spec_dir/SumeragiValidationRejectReasonLabelGate_fast.cfg"
    ;;
  validation-reject-reason-label-bug-*)
    bug_name="${mode#validation-reject-reason-label-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiValidationRejectReasonLabelGate"
    cfg_file="$spec_dir/SumeragiValidationRejectReasonLabelGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  validation-reject-status-fast)
    module="SumeragiValidationRejectStatusGate"
    cfg_file="$spec_dir/SumeragiValidationRejectStatusGate_fast.cfg"
    ;;
  validation-reject-status-bug-*)
    bug_name="${mode#validation-reject-status-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiValidationRejectStatusGate"
    cfg_file="$spec_dir/SumeragiValidationRejectStatusGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  peer-key-policy-status-fast)
    module="SumeragiPeerKeyPolicyStatusGate"
    cfg_file="$spec_dir/SumeragiPeerKeyPolicyStatusGate_fast.cfg"
    ;;
  peer-key-policy-status-bug-*)
    bug_name="${mode#peer-key-policy-status-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiPeerKeyPolicyStatusGate"
    cfg_file="$spec_dir/SumeragiPeerKeyPolicyStatusGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  view-change-cause-status-fast)
    module="SumeragiViewChangeCauseStatusGate"
    cfg_file="$spec_dir/SumeragiViewChangeCauseStatusGate_fast.cfg"
    ;;
  view-change-cause-status-bug-*)
    bug_name="${mode#view-change-cause-status-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiViewChangeCauseStatusGate"
    cfg_file="$spec_dir/SumeragiViewChangeCauseStatusGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  view-change-proof-status-fast)
    module="SumeragiViewChangeProofStatusGate"
    cfg_file="$spec_dir/SumeragiViewChangeProofStatusGate_fast.cfg"
    ;;
  view-change-proof-status-bug-*)
    bug_name="${mode#view-change-proof-status-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiViewChangeProofStatusGate"
    cfg_file="$spec_dir/SumeragiViewChangeProofStatusGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  qc-status-fast)
    module="SumeragiQcStatusGate"
    cfg_file="$spec_dir/SumeragiQcStatusGate_fast.cfg"
    ;;
  qc-status-bug-*)
    bug_name="${mode#qc-status-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiQcStatusGate"
    cfg_file="$spec_dir/SumeragiQcStatusGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  commit-quorum-status-fast)
    module="SumeragiCommitQuorumStatusGate"
    cfg_file="$spec_dir/SumeragiCommitQuorumStatusGate_fast.cfg"
    ;;
  commit-quorum-status-bug-*)
    bug_name="${mode#commit-quorum-status-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiCommitQuorumStatusGate"
    cfg_file="$spec_dir/SumeragiCommitQuorumStatusGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  commit-inflight-status-fast)
    module="SumeragiCommitInflightStatusGate"
    cfg_file="$spec_dir/SumeragiCommitInflightStatusGate_fast.cfg"
    ;;
  commit-inflight-status-bug-*)
    bug_name="${mode#commit-inflight-status-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiCommitInflightStatusGate"
    cfg_file="$spec_dir/SumeragiCommitInflightStatusGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  history-status-fast)
    module="SumeragiHistoryStatusGate"
    cfg_file="$spec_dir/SumeragiHistoryStatusGate_fast.cfg"
    ;;
  history-status-bug-*)
    bug_name="${mode#history-status-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiHistoryStatusGate"
    cfg_file="$spec_dir/SumeragiHistoryStatusGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  rbc-abort-status-fast)
    module="SumeragiRbcAbortStatusGate"
    cfg_file="$spec_dir/SumeragiRbcAbortStatusGate_fast.cfg"
    ;;
  rbc-abort-status-bug-*)
    bug_name="${mode#rbc-abort-status-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiRbcAbortStatusGate"
    cfg_file="$spec_dir/SumeragiRbcAbortStatusGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  rbc-mismatch-status-fast)
    module="SumeragiRbcMismatchStatusGate"
    cfg_file="$spec_dir/SumeragiRbcMismatchStatusGate_fast.cfg"
    ;;
  rbc-mismatch-status-bug-*)
    bug_name="${mode#rbc-mismatch-status-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiRbcMismatchStatusGate"
    cfg_file="$spec_dir/SumeragiRbcMismatchStatusGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  rbc-progress-stage-fast)
    module="SumeragiRbcProgressStageGate"
    cfg_file="$spec_dir/SumeragiRbcProgressStageGate_fast.cfg"
    ;;
  rbc-progress-stage-bug-*)
    bug_name="${mode#rbc-progress-stage-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiRbcProgressStageGate"
    cfg_file="$spec_dir/SumeragiRbcProgressStageGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  rbc-hot-repair-fast)
    module="SumeragiRbcHotRepairGate"
    cfg_file="$spec_dir/SumeragiRbcHotRepairGate_fast.cfg"
    ;;
  rbc-hot-repair-bug-*)
    bug_name="${mode#rbc-hot-repair-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiRbcHotRepairGate"
    cfg_file="$spec_dir/SumeragiRbcHotRepairGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  rbc-repair-request-fast)
    module="SumeragiRbcRepairRequestGate"
    cfg_file="$spec_dir/SumeragiRbcRepairRequestGate_fast.cfg"
    ;;
  rbc-repair-request-bug-*)
    bug_name="${mode#rbc-repair-request-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiRbcRepairRequestGate"
    cfg_file="$spec_dir/SumeragiRbcRepairRequestGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  rbc-targeted-repair-fast)
    module="SumeragiRbcTargetedRepairGate"
    cfg_file="$spec_dir/SumeragiRbcTargetedRepairGate_fast.cfg"
    ;;
  rbc-targeted-repair-bug-*)
    bug_name="${mode#rbc-targeted-repair-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiRbcTargetedRepairGate"
    cfg_file="$spec_dir/SumeragiRbcTargetedRepairGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  rbc-outbound-flush-fast)
    module="SumeragiRbcOutboundFlushGate"
    cfg_file="$spec_dir/SumeragiRbcOutboundFlushGate_fast.cfg"
    ;;
  rbc-outbound-flush-bug-*)
    bug_name="${mode#rbc-outbound-flush-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiRbcOutboundFlushGate"
    cfg_file="$spec_dir/SumeragiRbcOutboundFlushGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  rbc-chunk-post-debug-fast)
    module="SumeragiRbcChunkPostDebugGate"
    cfg_file="$spec_dir/SumeragiRbcChunkPostDebugGate_fast.cfg"
    ;;
  rbc-chunk-post-debug-bug-*)
    bug_name="${mode#rbc-chunk-post-debug-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiRbcChunkPostDebugGate"
    cfg_file="$spec_dir/SumeragiRbcChunkPostDebugGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  rbc-deferral-throttle-fast)
    module="SumeragiRbcDeferralThrottleGate"
    cfg_file="$spec_dir/SumeragiRbcDeferralThrottleGate_fast.cfg"
    ;;
  rbc-deferral-throttle-bug-*)
    bug_name="${mode#rbc-deferral-throttle-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiRbcDeferralThrottleGate"
    cfg_file="$spec_dir/SumeragiRbcDeferralThrottleGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  rbc-missing-init-rebroadcast-fast)
    module="SumeragiRbcMissingInitRebroadcastGate"
    cfg_file="$spec_dir/SumeragiRbcMissingInitRebroadcastGate_fast.cfg"
    ;;
  rbc-missing-init-rebroadcast-bug-*)
    bug_name="${mode#rbc-missing-init-rebroadcast-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiRbcMissingInitRebroadcastGate"
    cfg_file="$spec_dir/SumeragiRbcMissingInitRebroadcastGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  rbc-sampling-fast)
    module="SumeragiRbcSamplingGate"
    cfg_file="$spec_dir/SumeragiRbcSamplingGate_fast.cfg"
    ;;
  rbc-sampling-bug-*)
    bug_name="${mode#rbc-sampling-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiRbcSamplingGate"
    cfg_file="$spec_dir/SumeragiRbcSamplingGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  rbc-store-fast)
    module="SumeragiRbcStoreGuardGate"
    cfg_file="$spec_dir/SumeragiRbcStoreGuardGate_fast.cfg"
    ;;
  rbc-store-bug-*)
    bug_name="${mode#rbc-store-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiRbcStoreGuardGate"
    cfg_file="$spec_dir/SumeragiRbcStoreGuardGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  rbc-store-status-fast)
    module="SumeragiRbcStoreStatusGate"
    cfg_file="$spec_dir/SumeragiRbcStoreStatusGate_fast.cfg"
    ;;
  rbc-store-status-bug-*)
    bug_name="${mode#rbc-store-status-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiRbcStoreStatusGate"
    cfg_file="$spec_dir/SumeragiRbcStoreStatusGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  rbc-store-pressure-log-fast)
    module="SumeragiRbcStorePressureLogGate"
    cfg_file="$spec_dir/SumeragiRbcStorePressureLogGate_fast.cfg"
    ;;
  rbc-store-pressure-log-bug-*)
    bug_name="${mode#rbc-store-pressure-log-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiRbcStorePressureLogGate"
    cfg_file="$spec_dir/SumeragiRbcStorePressureLogGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  round-gap-status-fast)
    module="SumeragiRoundGapStatusGate"
    cfg_file="$spec_dir/SumeragiRoundGapStatusGate_fast.cfg"
    ;;
  round-gap-status-bug-*)
    bug_name="${mode#round-gap-status-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiRoundGapStatusGate"
    cfg_file="$spec_dir/SumeragiRoundGapStatusGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  rbc-recovery-helper-fast)
    module="SumeragiRbcRecoveryHelperGate"
    cfg_file="$spec_dir/SumeragiRbcRecoveryHelperGate_fast.cfg"
    ;;
  rbc-recovery-helper-bug-*)
    bug_name="${mode#rbc-recovery-helper-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiRbcRecoveryHelperGate"
    cfg_file="$spec_dir/SumeragiRbcRecoveryHelperGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  rbc-missing-block-recovery-fast)
    module="SumeragiRbcMissingBlockRecoveryGate"
    cfg_file="$spec_dir/SumeragiRbcMissingBlockRecoveryGate_fast.cfg"
    ;;
  rbc-missing-block-recovery-bug-*)
    bug_name="${mode#rbc-missing-block-recovery-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiRbcMissingBlockRecoveryGate"
    cfg_file="$spec_dir/SumeragiRbcMissingBlockRecoveryGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  rbc-unverified-roster-fast)
    module="SumeragiRbcUnverifiedRosterGate"
    cfg_file="$spec_dir/SumeragiRbcUnverifiedRosterGate_fast.cfg"
    ;;
  rbc-unverified-roster-bug-*)
    bug_name="${mode#rbc-unverified-roster-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiRbcUnverifiedRosterGate"
    cfg_file="$spec_dir/SumeragiRbcUnverifiedRosterGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  rbc-preimage-fast)
    module="SumeragiRbcSigningPreimageGate"
    cfg_file="$spec_dir/SumeragiRbcSigningPreimageGate_fast.cfg"
    ;;
  rbc-preimage-bug-*)
    bug_name="${mode#rbc-preimage-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiRbcSigningPreimageGate"
    cfg_file="$spec_dir/SumeragiRbcSigningPreimageGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  classic-preimage-fast)
    module="SumeragiClassicSigningPreimageGate"
    cfg_file="$spec_dir/SumeragiClassicSigningPreimageGate_fast.cfg"
    ;;
  classic-preimage-bug-*)
    bug_name="${mode#classic-preimage-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiClassicSigningPreimageGate"
    cfg_file="$spec_dir/SumeragiClassicSigningPreimageGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  classic-signature-fast)
    module="SumeragiClassicSignatureGate"
    cfg_file="$spec_dir/SumeragiClassicSignatureGate_fast.cfg"
    ;;
  classic-signature-bug-*)
    bug_name="${mode#classic-signature-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiClassicSignatureGate"
    cfg_file="$spec_dir/SumeragiClassicSignatureGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  invalid-signature-labels-fast)
    module="SumeragiInvalidSignatureLabelsGate"
    cfg_file="$spec_dir/SumeragiInvalidSignatureLabelsGate_fast.cfg"
    ;;
  invalid-signature-labels-bug-*)
    bug_name="${mode#invalid-signature-labels-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiInvalidSignatureLabelsGate"
    cfg_file="$spec_dir/SumeragiInvalidSignatureLabelsGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  invalid-signature-throttle-fast)
    module="SumeragiInvalidSignatureThrottleGate"
    cfg_file="$spec_dir/SumeragiInvalidSignatureThrottleGate_fast.cfg"
    ;;
  invalid-signature-throttle-bug-*)
    bug_name="${mode#invalid-signature-throttle-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiInvalidSignatureThrottleGate"
    cfg_file="$spec_dir/SumeragiInvalidSignatureThrottleGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  penalty-offender-selection-fast)
    module="SumeragiPenaltyOffenderSelectionGate"
    cfg_file="$spec_dir/SumeragiPenaltyOffenderSelectionGate_fast.cfg"
    ;;
  penalty-offender-selection-bug-*)
    bug_name="${mode#penalty-offender-selection-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiPenaltyOffenderSelectionGate"
    cfg_file="$spec_dir/SumeragiPenaltyOffenderSelectionGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  consensus-penalty-action-fast)
    module="SumeragiConsensusPenaltyActionGate"
    cfg_file="$spec_dir/SumeragiConsensusPenaltyActionGate_fast.cfg"
    ;;
  consensus-penalty-action-bug-*)
    bug_name="${mode#consensus-penalty-action-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiConsensusPenaltyActionGate"
    cfg_file="$spec_dir/SumeragiConsensusPenaltyActionGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  penalty-status-fast)
    module="SumeragiPenaltyStatusGate"
    cfg_file="$spec_dir/SumeragiPenaltyStatusGate_fast.cfg"
    ;;
  penalty-status-bug-*)
    bug_name="${mode#penalty-status-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiPenaltyStatusGate"
    cfg_file="$spec_dir/SumeragiPenaltyStatusGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  local-peer-removed-status-fast)
    module="SumeragiLocalPeerRemovedStatusGate"
    cfg_file="$spec_dir/SumeragiLocalPeerRemovedStatusGate_fast.cfg"
    ;;
  local-peer-removed-status-bug-*)
    bug_name="${mode#local-peer-removed-status-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiLocalPeerRemovedStatusGate"
    cfg_file="$spec_dir/SumeragiLocalPeerRemovedStatusGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  exec-witness-roots-fast)
    module="SumeragiExecWitnessRootProjectionGate"
    cfg_file="$spec_dir/SumeragiExecWitnessRootProjectionGate_fast.cfg"
    ;;
  exec-witness-roots-bug-*)
    bug_name="${mode#exec-witness-roots-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiExecWitnessRootProjectionGate"
    cfg_file="$spec_dir/SumeragiExecWitnessRootProjectionGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  block-message-rbc-compact-fast)
    module="SumeragiBlockMessageRbcCompactGate"
    cfg_file="$spec_dir/SumeragiBlockMessageRbcCompactGate_fast.cfg"
    ;;
  block-message-rbc-compact-bug-*)
    bug_name="${mode#block-message-rbc-compact-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiBlockMessageRbcCompactGate"
    cfg_file="$spec_dir/SumeragiBlockMessageRbcCompactGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  block-message-priority-fast)
    module="SumeragiBlockMessagePriorityGate"
    cfg_file="$spec_dir/SumeragiBlockMessagePriorityGate_fast.cfg"
    ;;
  block-message-priority-bug-*)
    bug_name="${mode#block-message-priority-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiBlockMessagePriorityGate"
    cfg_file="$spec_dir/SumeragiBlockMessagePriorityGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  block-message-height-view-fast)
    module="SumeragiBlockMessageHeightViewGate"
    cfg_file="$spec_dir/SumeragiBlockMessageHeightViewGate_fast.cfg"
    ;;
  block-message-height-view-bug-*)
    bug_name="${mode#block-message-height-view-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiBlockMessageHeightViewGate"
    cfg_file="$spec_dir/SumeragiBlockMessageHeightViewGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  block-message-kind-fast)
    module="SumeragiBlockMessageKindGate"
    cfg_file="$spec_dir/SumeragiBlockMessageKindGate_fast.cfg"
    ;;
  block-message-kind-bug-*)
    bug_name="${mode#block-message-kind-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiBlockMessageKindGate"
    cfg_file="$spec_dir/SumeragiBlockMessageKindGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  message-projection-fast)
    module="SumeragiMessageProjectionGate"
    cfg_file="$spec_dir/SumeragiMessageProjectionGate_fast.cfg"
    ;;
  message-projection-bug-*)
    bug_name="${mode#message-projection-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiMessageProjectionGate"
    cfg_file="$spec_dir/SumeragiMessageProjectionGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  pipeline-event-emission-fast)
    module="SumeragiPipelineEventEmissionGate"
    cfg_file="$spec_dir/SumeragiPipelineEventEmissionGate_fast.cfg"
    ;;
  pipeline-event-emission-bug-*)
    bug_name="${mode#pipeline-event-emission-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiPipelineEventEmissionGate"
    cfg_file="$spec_dir/SumeragiPipelineEventEmissionGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  block-message-wire-fast)
    module="SumeragiBlockMessageWireGate"
    cfg_file="$spec_dir/SumeragiBlockMessageWireGate_fast.cfg"
    ;;
  block-message-wire-bug-*)
    bug_name="${mode#block-message-wire-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiBlockMessageWireGate"
    cfg_file="$spec_dir/SumeragiBlockMessageWireGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  block-created-frontier-wire-fast)
    module="SumeragiBlockCreatedFrontierWireGate"
    cfg_file="$spec_dir/SumeragiBlockCreatedFrontierWireGate_fast.cfg"
    ;;
  block-created-frontier-wire-bug-*)
    bug_name="${mode#block-created-frontier-wire-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiBlockCreatedFrontierWireGate"
    cfg_file="$spec_dir/SumeragiBlockCreatedFrontierWireGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  cached-proposal-rebroadcast-fast)
    module="SumeragiCachedProposalRebroadcastGate"
    cfg_file="$spec_dir/SumeragiCachedProposalRebroadcastGate_fast.cfg"
    ;;
  cached-proposal-rebroadcast-bug-*)
    bug_name="${mode#cached-proposal-rebroadcast-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiCachedProposalRebroadcastGate"
    cfg_file="$spec_dir/SumeragiCachedProposalRebroadcastGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  frontier-same-slot-activity-fast)
    module="SumeragiFrontierSameSlotActivityGate"
    cfg_file="$spec_dir/SumeragiFrontierSameSlotActivityGate_fast.cfg"
    ;;
  frontier-same-slot-activity-bug-*)
    bug_name="${mode#frontier-same-slot-activity-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiFrontierSameSlotActivityGate"
    cfg_file="$spec_dir/SumeragiFrontierSameSlotActivityGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  frontier-reassembly-activity-fast)
    module="SumeragiFrontierReassemblyActivityGate"
    cfg_file="$spec_dir/SumeragiFrontierReassemblyActivityGate_fast.cfg"
    ;;
  frontier-reassembly-activity-bug-*)
    bug_name="${mode#frontier-reassembly-activity-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiFrontierReassemblyActivityGate"
    cfg_file="$spec_dir/SumeragiFrontierReassemblyActivityGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  frontier-quorum-owner-actionable-fast)
    module="SumeragiFrontierQuorumOwnerActionableGate"
    cfg_file="$spec_dir/SumeragiFrontierQuorumOwnerActionableGate_fast.cfg"
    ;;
  frontier-quorum-owner-actionable-bug-*)
    bug_name="${mode#frontier-quorum-owner-actionable-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiFrontierQuorumOwnerActionableGate"
    cfg_file="$spec_dir/SumeragiFrontierQuorumOwnerActionableGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  frontier-sidecar-retarget-fast)
    module="SumeragiFrontierSidecarRetargetGate"
    cfg_file="$spec_dir/SumeragiFrontierSidecarRetargetGate_fast.cfg"
    ;;
  frontier-sidecar-retarget-bug-*)
    bug_name="${mode#frontier-sidecar-retarget-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiFrontierSidecarRetargetGate"
    cfg_file="$spec_dir/SumeragiFrontierSidecarRetargetGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  frontier-sidecar-expected-hash-fast)
    module="SumeragiFrontierSidecarExpectedHashGate"
    cfg_file="$spec_dir/SumeragiFrontierSidecarExpectedHashGate_fast.cfg"
    ;;
  frontier-sidecar-expected-hash-bug-*)
    bug_name="${mode#frontier-sidecar-expected-hash-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiFrontierSidecarExpectedHashGate"
    cfg_file="$spec_dir/SumeragiFrontierSidecarExpectedHashGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  contiguous-frontier-payload-hint-fast)
    module="SumeragiContiguousFrontierPayloadHintGate"
    cfg_file="$spec_dir/SumeragiContiguousFrontierPayloadHintGate_fast.cfg"
    ;;
  contiguous-frontier-payload-hint-bug-*)
    bug_name="${mode#contiguous-frontier-payload-hint-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiContiguousFrontierPayloadHintGate"
    cfg_file="$spec_dir/SumeragiContiguousFrontierPayloadHintGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  frontier-parent-qc-hint-retarget-fast)
    module="SumeragiFrontierParentQcHintRetargetGate"
    cfg_file="$spec_dir/SumeragiFrontierParentQcHintRetargetGate_fast.cfg"
    ;;
  frontier-parent-qc-hint-retarget-bug-*)
    bug_name="${mode#frontier-parent-qc-hint-retarget-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiFrontierParentQcHintRetargetGate"
    cfg_file="$spec_dir/SumeragiFrontierParentQcHintRetargetGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  live-frontier-idle-missing-qc-fast)
    module="SumeragiLiveFrontierIdleMissingQcGate"
    cfg_file="$spec_dir/SumeragiLiveFrontierIdleMissingQcGate_fast.cfg"
    ;;
  live-frontier-idle-missing-qc-bug-*)
    bug_name="${mode#live-frontier-idle-missing-qc-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiLiveFrontierIdleMissingQcGate"
    cfg_file="$spec_dir/SumeragiLiveFrontierIdleMissingQcGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  missing-qc-reacquire-admission-fast)
    module="SumeragiMissingQcReacquireAdmissionGate"
    cfg_file="$spec_dir/SumeragiMissingQcReacquireAdmissionGate_fast.cfg"
    ;;
  missing-qc-reacquire-admission-bug-*)
    bug_name="${mode#missing-qc-reacquire-admission-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiMissingQcReacquireAdmissionGate"
    cfg_file="$spec_dir/SumeragiMissingQcReacquireAdmissionGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  missing-qc-reacquire-action-fast)
    module="SumeragiMissingQcReacquireActionGate"
    cfg_file="$spec_dir/SumeragiMissingQcReacquireActionGate_fast.cfg"
    ;;
  missing-qc-reacquire-action-bug-*)
    bug_name="${mode#missing-qc-reacquire-action-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiMissingQcReacquireActionGate"
    cfg_file="$spec_dir/SumeragiMissingQcReacquireActionGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  missing-commit-qc-actionable-fast)
    module="SumeragiMissingCommitQcActionableGate"
    cfg_file="$spec_dir/SumeragiMissingCommitQcActionableGate_fast.cfg"
    ;;
  missing-commit-qc-actionable-bug-*)
    bug_name="${mode#missing-commit-qc-actionable-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiMissingCommitQcActionableGate"
    cfg_file="$spec_dir/SumeragiMissingCommitQcActionableGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  missing-qc-height-stall-fast)
    module="SumeragiMissingQcHeightStallGate"
    cfg_file="$spec_dir/SumeragiMissingQcHeightStallGate_fast.cfg"
    ;;
  missing-qc-height-stall-bug-*)
    bug_name="${mode#missing-qc-height-stall-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiMissingQcHeightStallGate"
    cfg_file="$spec_dir/SumeragiMissingQcHeightStallGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  missing-qc-stall-range-pull-fast)
    module="SumeragiMissingQcStallRangePullGate"
    cfg_file="$spec_dir/SumeragiMissingQcStallRangePullGate_fast.cfg"
    ;;
  missing-qc-stall-range-pull-bug-*)
    bug_name="${mode#missing-qc-stall-range-pull-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiMissingQcStallRangePullGate"
    cfg_file="$spec_dir/SumeragiMissingQcStallRangePullGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  canonical-frontier-reanchor-fast)
    module="SumeragiCanonicalFrontierReanchorGate"
    cfg_file="$spec_dir/SumeragiCanonicalFrontierReanchorGate_fast.cfg"
    ;;
  canonical-frontier-reanchor-bug-*)
    bug_name="${mode#canonical-frontier-reanchor-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiCanonicalFrontierReanchorGate"
    cfg_file="$spec_dir/SumeragiCanonicalFrontierReanchorGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  frontier-repair-view-change-fast)
    module="SumeragiFrontierRepairViewChangeGate"
    cfg_file="$spec_dir/SumeragiFrontierRepairViewChangeGate_fast.cfg"
    ;;
  frontier-repair-view-change-bug-*)
    bug_name="${mode#frontier-repair-view-change-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiFrontierRepairViewChangeGate"
    cfg_file="$spec_dir/SumeragiFrontierRepairViewChangeGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  frontier-recovery-advance-fast)
    module="SumeragiFrontierRecoveryAdvanceGate"
    cfg_file="$spec_dir/SumeragiFrontierRecoveryAdvanceGate_fast.cfg"
    ;;
  frontier-recovery-advance-bug-*)
    bug_name="${mode#frontier-recovery-advance-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiFrontierRecoveryAdvanceGate"
    cfg_file="$spec_dir/SumeragiFrontierRecoveryAdvanceGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  same-height-no-proposal-storm-fast)
    module="SumeragiSameHeightNoProposalStormGate"
    cfg_file="$spec_dir/SumeragiSameHeightNoProposalStormGate_fast.cfg"
    ;;
  same-height-no-proposal-storm-bug-*)
    bug_name="${mode#same-height-no-proposal-storm-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiSameHeightNoProposalStormGate"
    cfg_file="$spec_dir/SumeragiSameHeightNoProposalStormGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  vrf-admission-fast)
    module="SumeragiVrfMessageAdmissionGate"
    cfg_file="$spec_dir/SumeragiVrfMessageAdmissionGate_fast.cfg"
    ;;
  vrf-admission-bug-*)
    bug_name="${mode#vrf-admission-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiVrfMessageAdmissionGate"
    cfg_file="$spec_dir/SumeragiVrfMessageAdmissionGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  vrf-epoch-window-fast)
    module="SumeragiVrfEpochWindowGate"
    cfg_file="$spec_dir/SumeragiVrfEpochWindowGate_fast.cfg"
    ;;
  vrf-epoch-window-bug-*)
    bug_name="${mode#vrf-epoch-window-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiVrfEpochWindowGate"
    cfg_file="$spec_dir/SumeragiVrfEpochWindowGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  vrf-epoch-boundary-fast)
    module="SumeragiVrfEpochBoundaryGate"
    cfg_file="$spec_dir/SumeragiVrfEpochBoundaryGate_fast.cfg"
    ;;
  vrf-epoch-boundary-bug-*)
    bug_name="${mode#vrf-epoch-boundary-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiVrfEpochBoundaryGate"
    cfg_file="$spec_dir/SumeragiVrfEpochBoundaryGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  vrf-epoch-restore-fast)
    module="SumeragiVrfEpochRestoreGate"
    cfg_file="$spec_dir/SumeragiVrfEpochRestoreGate_fast.cfg"
    ;;
  vrf-epoch-restore-bug-*)
    bug_name="${mode#vrf-epoch-restore-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiVrfEpochRestoreGate"
    cfg_file="$spec_dir/SumeragiVrfEpochRestoreGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  vrf-material-derivation-fast)
    module="SumeragiVrfMaterialDerivationGate"
    cfg_file="$spec_dir/SumeragiVrfMaterialDerivationGate_fast.cfg"
    ;;
  vrf-material-derivation-bug-*)
    bug_name="${mode#vrf-material-derivation-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiVrfMaterialDerivationGate"
    cfg_file="$spec_dir/SumeragiVrfMaterialDerivationGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  vrf-local-state-fast)
    module="SumeragiVrfLocalStateGate"
    cfg_file="$spec_dir/SumeragiVrfLocalStateGate_fast.cfg"
    ;;
  vrf-local-state-bug-*)
    bug_name="${mode#vrf-local-state-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiVrfLocalStateGate"
    cfg_file="$spec_dir/SumeragiVrfLocalStateGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  vrf-penalties-report-fast)
    module="SumeragiVrfPenaltiesReportGate"
    cfg_file="$spec_dir/SumeragiVrfPenaltiesReportGate_fast.cfg"
    ;;
  vrf-penalties-report-bug-*)
    bug_name="${mode#vrf-penalties-report-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiVrfPenaltiesReportGate"
    cfg_file="$spec_dir/SumeragiVrfPenaltiesReportGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  vote-admission-fast)
    module="SumeragiVoteAdmissionGate"
    cfg_file="$spec_dir/SumeragiVoteAdmissionGate_fast.cfg"
    ;;
  vote-admission-bug-*)
    bug_name="${mode#vote-admission-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiVoteAdmissionGate"
    cfg_file="$spec_dir/SumeragiVoteAdmissionGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  vote-duplicate-key-fast)
    module="SumeragiVoteDuplicateKeyGate"
    cfg_file="$spec_dir/SumeragiVoteDuplicateKeyGate_fast.cfg"
    ;;
  vote-duplicate-key-bug-*)
    bug_name="${mode#vote-duplicate-key-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiVoteDuplicateKeyGate"
    cfg_file="$spec_dir/SumeragiVoteDuplicateKeyGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  evidence-horizon-fast)
    module="SumeragiEvidenceHorizonGate"
    cfg_file="$spec_dir/SumeragiEvidenceHorizonGate_fast.cfg"
    ;;
  evidence-horizon-bug-*)
    bug_name="${mode#evidence-horizon-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiEvidenceHorizonGate"
    cfg_file="$spec_dir/SumeragiEvidenceHorizonGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  evidence-canonicalization-fast)
    module="SumeragiEvidenceCanonicalizationGate"
    cfg_file="$spec_dir/SumeragiEvidenceCanonicalizationGate_fast.cfg"
    ;;
  evidence-canonicalization-bug-*)
    bug_name="${mode#evidence-canonicalization-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiEvidenceCanonicalizationGate"
    cfg_file="$spec_dir/SumeragiEvidenceCanonicalizationGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  evidence-validation-fast)
    module="SumeragiEvidenceValidationGate"
    cfg_file="$spec_dir/SumeragiEvidenceValidationGate_fast.cfg"
    ;;
  evidence-validation-bug-*)
    bug_name="${mode#evidence-validation-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiEvidenceValidationGate"
    cfg_file="$spec_dir/SumeragiEvidenceValidationGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  vote-verify-worker-config-fast)
    module="SumeragiVoteVerifyWorkerConfigGate"
    cfg_file="$spec_dir/SumeragiVoteVerifyWorkerConfigGate_fast.cfg"
    ;;
  vote-verify-worker-config-bug-*)
    bug_name="${mode#vote-verify-worker-config-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiVoteVerifyWorkerConfigGate"
    cfg_file="$spec_dir/SumeragiVoteVerifyWorkerConfigGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  qc-verify-worker-config-fast)
    module="SumeragiQcVerifyWorkerConfigGate"
    cfg_file="$spec_dir/SumeragiQcVerifyWorkerConfigGate_fast.cfg"
    ;;
  qc-verify-worker-config-bug-*)
    bug_name="${mode#qc-verify-worker-config-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiQcVerifyWorkerConfigGate"
    cfg_file="$spec_dir/SumeragiQcVerifyWorkerConfigGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  qc-signer-count-fast)
    module="SumeragiQcSignerCountGate"
    cfg_file="$spec_dir/SumeragiQcSignerCountGate_fast.cfg"
    ;;
  qc-signer-count-bug-*)
    bug_name="${mode#qc-signer-count-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiQcSignerCountGate"
    cfg_file="$spec_dir/SumeragiQcSignerCountGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  voting-signer-count-fast)
    module="SumeragiVotingSignerCountGate"
    cfg_file="$spec_dir/SumeragiVotingSignerCountGate_fast.cfg"
    ;;
  voting-signer-count-bug-*)
    bug_name="${mode#voting-signer-count-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiVotingSignerCountGate"
    cfg_file="$spec_dir/SumeragiVotingSignerCountGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  precommit-vote-count-fast)
    module="SumeragiPrecommitVoteCountGate"
    cfg_file="$spec_dir/SumeragiPrecommitVoteCountGate_fast.cfg"
    ;;
  precommit-vote-count-bug-*)
    bug_name="${mode#precommit-vote-count-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiPrecommitVoteCountGate"
    cfg_file="$spec_dir/SumeragiPrecommitVoteCountGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  commit-quorum-signers-fast)
    module="SumeragiCommitQuorumSignersGate"
    cfg_file="$spec_dir/SumeragiCommitQuorumSignersGate_fast.cfg"
    ;;
  commit-quorum-signers-bug-*)
    bug_name="${mode#commit-quorum-signers-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiCommitQuorumSignersGate"
    cfg_file="$spec_dir/SumeragiCommitQuorumSignersGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  signer-index-normalization-fast)
    module="SumeragiSignerIndexNormalizationGate"
    cfg_file="$spec_dir/SumeragiSignerIndexNormalizationGate_fast.cfg"
    ;;
  signer-index-normalization-bug-*)
    bug_name="${mode#signer-index-normalization-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiSignerIndexNormalizationGate"
    cfg_file="$spec_dir/SumeragiSignerIndexNormalizationGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  commit-qc-lookup-fast)
    module="SumeragiCommitQcLookupGate"
    cfg_file="$spec_dir/SumeragiCommitQcLookupGate_fast.cfg"
    ;;
  commit-qc-lookup-bug-*)
    bug_name="${mode#commit-qc-lookup-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiCommitQcLookupGate"
    cfg_file="$spec_dir/SumeragiCommitQcLookupGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  precommit-signer-record-fast)
    module="SumeragiPrecommitSignerRecordGate"
    cfg_file="$spec_dir/SumeragiPrecommitSignerRecordGate_fast.cfg"
    ;;
  precommit-signer-record-bug-*)
    bug_name="${mode#precommit-signer-record-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiPrecommitSignerRecordGate"
    cfg_file="$spec_dir/SumeragiPrecommitSignerRecordGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  collector-plan-fast)
    module="SumeragiCollectorPlanGate"
    cfg_file="$spec_dir/SumeragiCollectorPlanGate_fast.cfg"
    ;;
  collector-plan-bug-*)
    bug_name="${mode#collector-plan-bug-}"
    cfg_bug_name="${bug_name//-/_}"
    module="SumeragiCollectorPlanGate"
    cfg_file="$spec_dir/SumeragiCollectorPlanGate_bug_${cfg_bug_name}.cfg"
    expect_failure=1
    ;;
  *)
    echo "usage: $0 {frontier-small|validation-redrive-label-fast|validation-redrive-label-bug-*|validation-ownership-cleanup-fast|validation-ownership-cleanup-bug-*|worker-loop-stage-fast|worker-loop-stage-bug-*|worker-tick-gap-fast|worker-tick-gap-bug-*|vnext-performance-config-fast|vnext-performance-config-bug-*|validation-worker-config-fast|validation-worker-config-bug-*|commit-worker-config-fast|commit-worker-config-bug-*|commit-stage-timing-threshold-fast|commit-stage-timing-threshold-bug-*|commit-inflight-timeout-fast|commit-inflight-timeout-bug-*|post-commit-pacemaker-kick-fast|post-commit-pacemaker-kick-bug-*|idle-view-proposal-budget-fast|idle-view-proposal-budget-bug-*|cached-slot-timeout-fast|cached-slot-timeout-bug-*|pending-fast-path-timeout-fast|pending-fast-path-timeout-bug-*|stalled-pending-timeout-fast|stalled-pending-timeout-bug-*|stalled-pending-frontier-timeout-fast|stalled-pending-frontier-timeout-bug-*|frontier-proposal-grace-fast|frontier-proposal-grace-bug-*|frontier-slot-helpers-fast|frontier-slot-helpers-bug-*|frontier-slot-tracker-fast|frontier-slot-tracker-bug-*|slot-tracker-state-fast|slot-tracker-state-bug-*|timeout-derivation-fast|timeout-derivation-bug-*|round-view-helpers-fast|round-view-helpers-bug-*|phase-tracker-fast|phase-tracker-bug-*|failure-recovery-helpers-fast|failure-recovery-helpers-bug-*|missing-qc-timing-fast|missing-qc-timing-bug-*|idle-backlog-signals-fast|idle-backlog-signals-bug-*|proposal-liveness-fast|proposal-liveness-bug-*|actionable-vote-backed-proposal-fast|actionable-vote-backed-proposal-bug-*|slot-proposal-evidence-fast|slot-proposal-evidence-bug-*|round-liveness-fast|round-liveness-bug-*|roster-recovery-fsm-fast|roster-recovery-fsm-bug-*|consensus-recovery-prune-fast|consensus-recovery-prune-bug-*|frontier-live-owner-work-fast|frontier-live-owner-work-bug-*|keep-frontier-pending-active-fast|keep-frontier-pending-active-bug-*|stale-view-pending-prune-fast|stale-view-pending-prune-bug-*|superseded-frontier-payload-retention-fast|superseded-frontier-payload-retention-bug-*|stale-missing-block-request-prune-fast|stale-missing-block-request-prune-bug-*|stale-missing-commit-qc-prune-fast|stale-missing-commit-qc-prune-bug-*|stale-rbc-session-prune-fast|stale-rbc-session-prune-bug-*|highest-qc-defer-marker-prune-fast|highest-qc-defer-marker-prune-bug-*|fast-finality-inline-validation-fast|fast-finality-inline-validation-bug-*|observer-signature-recovery-fast|observer-signature-recovery-bug-*|validation-failure-finalize-fast|validation-failure-finalize-bug-*|validation-reject-reason-label-fast|validation-reject-reason-label-bug-*|validation-reject-status-fast|validation-reject-status-bug-*|peer-key-policy-status-fast|peer-key-policy-status-bug-*|view-change-cause-status-fast|view-change-cause-status-bug-*|view-change-proof-status-fast|view-change-proof-status-bug-*|qc-status-fast|qc-status-bug-*|commit-quorum-status-fast|commit-quorum-status-bug-*|commit-inflight-status-fast|commit-inflight-status-bug-*|history-status-fast|history-status-bug-*|rbc-abort-status-fast|rbc-abort-status-bug-*|rbc-mismatch-status-fast|rbc-mismatch-status-bug-*|rbc-progress-stage-fast|rbc-progress-stage-bug-*|rbc-hot-repair-fast|rbc-hot-repair-bug-*|rbc-repair-request-fast|rbc-repair-request-bug-*|rbc-targeted-repair-fast|rbc-targeted-repair-bug-*|rbc-outbound-flush-fast|rbc-outbound-flush-bug-*|rbc-chunk-post-debug-fast|rbc-chunk-post-debug-bug-*|rbc-deferral-throttle-fast|rbc-deferral-throttle-bug-*|rbc-missing-init-rebroadcast-fast|rbc-missing-init-rebroadcast-bug-*|rbc-sampling-fast|rbc-sampling-bug-*|rbc-store-fast|rbc-store-bug-*|rbc-store-status-fast|rbc-store-status-bug-*|rbc-store-pressure-log-fast|rbc-store-pressure-log-bug-*|round-gap-status-fast|round-gap-status-bug-*|rbc-recovery-helper-fast|rbc-recovery-helper-bug-*|rbc-missing-block-recovery-fast|rbc-missing-block-recovery-bug-*|rbc-unverified-roster-fast|rbc-unverified-roster-bug-*|rbc-preimage-fast|rbc-preimage-bug-*|classic-preimage-fast|classic-preimage-bug-*|classic-signature-fast|classic-signature-bug-*|invalid-signature-labels-fast|invalid-signature-labels-bug-*|invalid-signature-throttle-fast|invalid-signature-throttle-bug-*|penalty-offender-selection-fast|penalty-offender-selection-bug-*|consensus-penalty-action-fast|consensus-penalty-action-bug-*|penalty-status-fast|penalty-status-bug-*|local-peer-removed-status-fast|local-peer-removed-status-bug-*|exec-witness-roots-fast|exec-witness-roots-bug-*|block-message-rbc-compact-fast|block-message-rbc-compact-bug-*|block-message-priority-fast|block-message-priority-bug-*|block-message-height-view-fast|block-message-height-view-bug-*|block-message-kind-fast|block-message-kind-bug-*|message-projection-fast|message-projection-bug-*|pipeline-event-emission-fast|pipeline-event-emission-bug-*|block-message-wire-fast|block-message-wire-bug-*|block-created-frontier-wire-fast|block-created-frontier-wire-bug-*|cached-proposal-rebroadcast-fast|cached-proposal-rebroadcast-bug-*|frontier-same-slot-activity-fast|frontier-same-slot-activity-bug-*|frontier-reassembly-activity-fast|frontier-reassembly-activity-bug-*|frontier-quorum-owner-actionable-fast|frontier-quorum-owner-actionable-bug-*|frontier-sidecar-retarget-fast|frontier-sidecar-retarget-bug-*|frontier-sidecar-expected-hash-fast|frontier-sidecar-expected-hash-bug-*|contiguous-frontier-payload-hint-fast|contiguous-frontier-payload-hint-bug-*|frontier-parent-qc-hint-retarget-fast|frontier-parent-qc-hint-retarget-bug-*|vote-verify-worker-config-fast|vote-verify-worker-config-bug-*|qc-verify-worker-config-fast|qc-verify-worker-config-bug-*|qc-signer-count-fast|qc-signer-count-bug-*|voting-signer-count-fast|voting-signer-count-bug-*|precommit-vote-count-fast|precommit-vote-count-bug-*|commit-quorum-signers-fast|commit-quorum-signers-bug-*|signer-index-normalization-fast|signer-index-normalization-bug-*|commit-qc-lookup-fast|commit-qc-lookup-bug-*|precommit-signer-record-fast|precommit-signer-record-bug-*|collector-plan-fast|collector-plan-bug-*}" >&2
    echo "additional modes: live-frontier-idle-missing-qc-fast|live-frontier-idle-missing-qc-bug-*|missing-qc-reacquire-admission-fast|missing-qc-reacquire-admission-bug-*|missing-qc-reacquire-action-fast|missing-qc-reacquire-action-bug-*|missing-commit-qc-actionable-fast|missing-commit-qc-actionable-bug-*|missing-qc-height-stall-fast|missing-qc-height-stall-bug-*|missing-qc-stall-range-pull-fast|missing-qc-stall-range-pull-bug-*|canonical-frontier-reanchor-fast|canonical-frontier-reanchor-bug-*|frontier-repair-view-change-fast|frontier-repair-view-change-bug-*|frontier-recovery-advance-fast|frontier-recovery-advance-bug-*|same-height-no-proposal-storm-fast|same-height-no-proposal-storm-bug-*|vrf-admission-fast|vrf-admission-bug-*|vrf-epoch-window-fast|vrf-epoch-window-bug-*|vrf-epoch-boundary-fast|vrf-epoch-boundary-bug-*|vrf-epoch-restore-fast|vrf-epoch-restore-bug-*|vrf-material-derivation-fast|vrf-material-derivation-bug-*|vrf-local-state-fast|vrf-local-state-bug-*|vrf-penalties-report-fast|vrf-penalties-report-bug-*|vote-admission-fast|vote-admission-bug-*|vote-duplicate-key-fast|vote-duplicate-key-bug-*|evidence-horizon-fast|evidence-horizon-bug-*|evidence-canonicalization-fast|evidence-canonicalization-bug-*|evidence-validation-fast|evidence-validation-bug-*" >&2
    exit 2
    ;;
esac

tlc_jar="${TLC_JAR:-${TLA2TOOLS_JAR:-$default_tlc_jar}}"
if [[ "$tlc_jar" != /* ]]; then
  tlc_jar="$root_dir/$tlc_jar"
fi
workers="${TLC_WORKERS:-1}"
run_dir="$root_dir/target/tlc/sumeragi-$mode"
mkdir -p "$run_dir"

if [[ ! -f "$cfg_file" ]]; then
  echo "error: missing config '$cfg_file'" >&2
  exit 2
fi

if [[ ! -f "$tlc_jar" ]]; then
  echo "error: TLC jar '$tlc_jar' not found" >&2
  echo "hint: run scripts/formal/install_apalache.sh ${apalache_version}, or set TLC_JAR/TLA2TOOLS_JAR" >&2
  exit 127
fi

if ! command -v java >/dev/null 2>&1; then
  echo "error: java not found" >&2
  exit 127
fi

log_file="$run_dir/tlc.log"
set +e
(
  cd "$spec_dir"
  java ${TLC_JAVA_OPTS:-} -cp "$tlc_jar" tlc2.TLC \
    -cleanup \
    -workers "$workers" \
    -metadir "$run_dir" \
    -config "$cfg_file" \
    "$module"
) 2>&1 | tee "$log_file"
tlc_status=${PIPESTATUS[0]}
set -e

if [[ "$expect_failure" -eq 1 ]]; then
  if [[ "$tlc_status" -eq 0 ]]; then
    echo "error: Sumeragi TLC '$mode' unexpectedly passed" >&2
    exit 1
  fi
  if grep -Eq "Invariant .* is violated|Error: Invariant|Error: The invariant of .* is equal to FALSE|Temporal properties were violated" "$log_file"; then
    echo "[formal] Sumeragi TLC '$mode' produced the expected failure"
    exit 0
  fi
  echo "error: Sumeragi TLC '$mode' failed without the expected invariant violation" >&2
  exit "$tlc_status"
fi

if [[ "$tlc_status" -ne 0 ]]; then
  exit "$tlc_status"
fi

echo "[formal] Sumeragi TLC '$mode' check passed"
