#!/usr/bin/env python3
"""Static QueuePlan startup-replay bindings for the multilane model gate."""

QUEUE_PLAN_STARTUP_REPLAY_MODULE = "SumeragiV2QueuePlanAdmissionRegistry"
QUEUE_PLAN_STARTUP_REPLAY_BINDINGS = (
    (
        "crates/iroha_core/src/queue/journal.rs",
        "method",
        "QueuePlanJournalReplay::into_verified_records",
        (
            "self.verify_snapshot_content()?",
            "std::mem::take(&mut self.live_positions)",
            "live.ownership_position",
            "self.verify_snapshot_storage()?",
            "record.claim_digest()",
            "record.entrypoint_hash != entrypoint_hash",
            "record.plan_digest() != live.plan_digest",
            "claim_digest != live.claim_digest",
            "verified.push(record)",
            "Ok(verified)",
        ),
    ),
    (
        "crates/iroha_core/src/queue/journal.rs",
        "method",
        "QueuePlanJournal::remove_all_live_exact_atomic_strict_durable",
        (
            "remove_many_exact_atomic_strict_durable_inner(removals, true)?",
            "Ok(())",
        ),
    ),
    (
        "crates/iroha_core/src/queue/journal.rs",
        "method",
        "QueuePlanJournal::remove_many_exact_atomic_strict_durable_inner",
        (
            "self.ensure_healthy()?",
            "removals.len() > self.limits.max_live_records",
            "QueuePlanJournalFrameV4::RemoveBatch(requested.clone())",
            "prepare_replay_with_removed_entrypoints(Some(&entrypoints))",
            "if require_all_live",
            "live_removals.len() != requested.len()",
            "QueuePlanJournalExactRemoveResult::Removed",
            "atomic live-removal batch contains an already-absent target",
            "QueuePlanJournalFrameV4::RemoveBatch(live_removals.clone())",
            "self.compact(true)?",
            "if compacted != (outcomes.clone(), live_removals.clone())",
            "self.append_encoded(&encoded, AppendPhase::OrdinaryRemove)",
            "self.sync_all_raw(SyncPhase::General)?",
            "Ok(outcomes)",
        ),
    ),
    (
        "crates/iroha_core/src/queue.rs",
        "method",
        "Queue::ensure_plan_journal_replay_startup_shape_locked",
        (
            "self.txs.is_empty()",
            "self.materialized_active_len() == 0",
            "self.materialized_retained_bytes() == 0",
            "self.tx_hashes.is_empty()",
            "self.queued_count.load(Ordering::Acquire) == 0",
            "self.routing_decisions.is_empty()",
            "self.routing_plans.is_empty()",
            "self.durable_plan_claims.is_empty()",
            "self.tx_encoded_len.is_empty()",
            "self.tx_gas_cost.is_empty()",
            "self.tx_enqueued_at_ms.is_empty()",
            "self.queued_tx_enqueued_at_ms.is_empty()",
            "self.queued_age_ring.lock().is_empty()",
            "self.removed_hashes.is_empty()",
            "self.txs_per_user.is_empty()",
            "fee_admission_reservations",
            "self.expiry_ring.lock().is_empty()",
            "self.expiry_ring_members.is_empty()",
            "self.tx_gossip.is_empty()",
            "self.tx_teu.is_empty()",
            "lane_teu_pending",
            "dataspace_teu_pending",
            "only exact durable reservation FIFO identities may pre-exist",
        ),
    ),
    (
        "crates/iroha_core/src/queue.rs",
        "method",
        "Queue::plan_journal_replay_reservation_shape_locked",
        (
            "store.durable_owned_hashes().collect::<HashSet<_>>()",
            ".filter(|hash| !self.txs.contains_key(hash))",
            "expected_missing_payload_hashes != store.missing_payload_hashes",
            "missing_reservation_payload_count",
            "store.missing_payload_hashes.len()",
            "store.live_by_hash.values().chain(",
            "completed_releases",
            "record.validate()",
            ".insert(hash, record.fifo_order)",
            "multiple durable FIFO owners",
            "durable_owned_hashes",
            "durable_fifo_orders",
            "missing_payload_hashes: store.missing_payload_hashes.clone()",
        ),
    ),
    (
        "crates/iroha_core/src/queue.rs",
        "method",
        "Queue::prepare_plan_journal_replay_locked",
        (
            "self.ensure_plan_journal_replay_startup_shape_locked()?",
            "self.plan_journal_replay_reservation_shape_locked()?",
            "journal_hashes.len() != records.len()",
            ".missing_payload_hashes",
            ".difference(&journal_hashes)",
            "commit_barrier_hashes.contains(hash)",
            "state_view.transactions.get(hash).is_none()",
            "let replay_observed_at = self.time_source.get_unix_time();",
            "AcceptedTransaction::accept_entrypoint_at_time",
            "accepted.hash_as_entrypoint() != entrypoint_hash",
            "queue_plan_replay_reservation_owner",
            "reservation_shape.durable_owned_hashes.contains(&hash)",
            "reservation_owner.is_present()",
            "reservation_owner.fifo_order()",
            "state_view.transactions.get(&hash).is_some()",
            "recorded_global_admission_identity",
            "queue_plan_admission_registry_match",
            "QueuePlanAdmissionRegistryMatch::Conflict",
            "global_registry_match.is_none()",
            "self.is_expired_at_with_enqueue_timestamp(",
            "replay_observed_at",
            "!has_durable_reservation_owner",
            "resolve_routing_plan_for_queue_admission(",
            "durable_plan_claim_context_revalidates_in_view",
            "QueueAdmissionPreparationMode::AtomicJournalReplay",
            "transaction_selection_durability_faulted()",
            "self.active_len()",
            "self.retained_bytes()",
            "projected_active > self.capacity.get()",
            "projected_retained > self.max_retained_bytes.get()",
            "projected > self.capacity_per_user.get()",
            ".reserve(admission.hash, reservation)",
            "orphaned FIFO identity",
            "reservation FIFO anchors disagree with authenticated journal order",
            "anchors.len() != reservation_shape.durable_fifo_orders.len()",
            "final_fifo.len() > self.tx_hashes.capacity()",
            "terminal_removals",
            "Ok(PreparedQueuePlanReplay {",
        ),
    ),
    (
        "crates/iroha_core/src/queue.rs",
        "method",
        "Queue::apply_plan_journal_replay_locked",
        (
            "terminal_removals: _",
            "*self.fee_admission_reservations.lock() = fee_reservations;",
            "*self.next_fifo_ordinal.lock() = next_fifo_ordinal;",
            "self.fifo_order_by_hash.insert(hash, fifo_order);",
            "self.txs.insert(hash, Arc::clone(&tx_arc));",
            "self.track_active_transaction();",
            "self.routing_decisions.insert(hash, routing_decision);",
            "self.routing_plans.insert(hash, routing_plan.clone());",
            "self.durable_plan_claims.insert(hash, claim.clone());",
            "self.track_expiry_hash(hash);",
            "notifications.push(QueueAdmissionNotification {",
            "self.apply_per_user_tx_count_increments(per_user_increments);",
            "self.reconcile_missing_reservation_payloads_locked(&mut store);",
            "self.replace_fifo_locked(&final_fifo);",
            "(summary, notifications)",
        ),
    ),
    (
        "crates/iroha_core/src/queue.rs",
        "method",
        "Queue::replay_plan_journal",
        (
            "self.plan_journal_install_lock.lock()",
            "self.lane_reservation_transition_lock.lock()",
            "state.lock_lane_lifecycle_work_admission()",
            "state.state_view_generation()",
            "let state_view = state.view();",
            "self.ensure_plan_journal_replay_startup_shape_locked()?",
            "self.sync_nexus_routing_with_view(&state_view);",
            "let mut journal_guard = self.plan_journal.lock();",
            "let queue_guard = self.push_remove_lock.lock();",
            "let records = journal.prepare_replay()?.into_verified_records()?;",
            "let expected_record_claims = records",
            "self.prepare_plan_journal_replay_locked(",
            "let observed_record_claims = journal",
            "if observed_record_claims != expected_record_claims",
            "let terminal_removals = prepared.terminal_removals.clone();",
            "remove_all_live_exact_atomic_strict_durable(&terminal_removals)",
            "self.mark_plan_journal_durability_fault",
            "self.apply_plan_journal_replay_locked(prepared)",
            "self.publish_admission_notifications(&notifications);",
            "self.publish_backpressure_state(self.active_len(), backpressure_telemetry);",
            "status::set_tx_queue_pressure(self.pressure_snapshot());",
            "Ok(summary)",
        ),
    ),
    (
        "crates/iroha_core/src/queue.rs",
        "method",
        "Queue::complete_lane_reservation_startup_reconciliation",
        (
            "self.lane_reservation_transition_lock.lock()",
            "self.push_remove_lock.lock()",
            "self.transaction_selection_durability_faulted()",
            "!store.commit_barriers.is_empty()",
            "!store.release_barriers.is_empty()",
            "!store.completed_releases.is_empty()",
            "!store.missing_payload_hashes.is_empty()",
            "lane_reservation_reconciliation_pending",
            ".store(false, Ordering::Release)",
        ),
    ),
    (
        "crates/iroha_core/src/queue.rs",
        "method",
        "Queue::lane_reservation_reconciliation_snapshot",
        (
            "self.lane_reservation_transition_lock.lock()",
            "self.push_remove_lock.lock()",
            "let store = self.lane_reservations.lock()",
            "store.live_by_hash.values()",
            "store.commit_barriers.clone()",
            "store.release_barriers.clone()",
            "store.completed_releases.clone()",
            "key.validate()",
            "for barrier in &prepared_release_barriers",
            "barrier\n                .validate()",
            "for completion in &completed_releases",
            "completion\n                .validate()",
            "commit_barriers.sort_by_key",
            "prepared_release_barriers.sort_by_key",
            "completed_releases.sort_by_key",
            "LaneQueueReservationReconciliationSnapshotV1 {",
        ),
    ),
    (
        "crates/iroha_core/src/sumeragi/v2_apply.rs",
        "fn",
        "plan_lane_reservation_ownership",
        (
            "let current_snapshot = queue.lane_reservation_reconciliation_snapshot()?;",
            "handoff.into_queue_handoff()",
            "revalidate_lane_reservation_startup_reconciliation_receipt(",
            "deferred_terminal_recovery",
            "if snapshot.is_empty()",
            "let release_barriers = snapshot.release_barriers()",
            "let commit_barriers = snapshot.commit_barriers.as_slice()",
            "has_committed_transaction",
            "unique_recovered",
            "get_merge_entry_by_carrier_height",
            "authenticated_autonomous_carrier_application_projections",
            "certified_merge_queue_reservations",
            "exact_committed_carrier_height_for_group",
            "authenticated_committed_carriers",
            ".queue_cleanup_authorization()",
            "commit_authorization",
            "ReservationReconciliationAction::Commit {",
            "lane_incarnation_at_height",
            "classify_autonomous_lane_reservation_groups",
            "canonical_autonomous_carrier_disposition",
            "RecoverCanonicalBodies",
            "InstallHistoricalAutonomousRecoveries",
            "if queue.lane_reservation_reconciliation_snapshot()? != snapshot",
            "let replay_receipt = match recovered_receipt",
        ),
    ),
    (
        "crates/iroha_core/src/sumeragi/v2_apply.rs",
        "fn",
        "apply_lane_reservation_reconciliation_plan",
        (
            "replay_receipt",
            "deferred_terminal_recovery",
            "historical_autonomous_install_is_durable",
            "revalidate_lane_reservation_startup_reconciliation_receipt(&replay_receipt, &snapshot)",
            "ReservationReconciliationAction::Commit {",
            "finalize_startup_committed_canonical_carriers(",
            "retire_autonomous_lane_slot_and_release_reservations",
            "release_strictly_absent_lane_reservations_in_order",
            "let final_snapshot = queue.lane_reservation_reconciliation_snapshot()?;",
            "!final_snapshot.commit_barriers.is_empty()",
            "!final_snapshot.prepared_release_barriers.is_empty()",
            "!final_snapshot.completed_releases.is_empty()",
            "complete_deferred_autonomous_lifecycle_terminal_outcomes_after_queue_actions(",
            "queue.complete_lane_reservation_startup_reconciliation(replay_receipt)?;",
        ),
    ),
    (
        "crates/irohad/src/main.rs",
        "method",
        "Iroha::start_with_runtime_deps",
        (
            "install_lane_reservation_journal(",
            "install_plan_journal(",
            "replay_plan_journal(&state)",
            "IrohaNetwork::start_with_crypto_and_initial_trusted_sources(",
        ),
    ),
)
QUEUE_PLAN_STARTUP_REPLAY_ORDERED_SOURCE_CHECKS = (
    (
        "crates/iroha_core/src/queue/journal.rs",
        "method",
        "QueuePlanJournalReplay::into_verified_records",
        (
            "self.verify_snapshot_content()?;",
            "std::mem::take(&mut self.live_positions)",
            "ordered.sort_unstable_by_key",
            "for (entrypoint_hash, live) in ordered {",
            "self.verify_snapshot_storage()?;",
            "let claim_digest = record.claim_digest()",
            "if record.entrypoint_hash != entrypoint_hash",
            "verified.push(record);",
            "self.verify_snapshot_content()?;",
            "Ok(verified)",
        ),
    ),
    (
        "crates/iroha_core/src/queue/journal.rs",
        "method",
        "QueuePlanJournal::remove_many_exact_atomic_strict_durable_inner",
        (
            "let (outcomes, live_removals) =",
            "if require_all_live",
            "atomic live-removal batch contains an already-absent target",
            "if live_removals.is_empty()",
            "let encoded = encode_frame(",
            "self.ensure_append_capacity(encoded.len())",
            "self.compact(true)?;",
            "let compacted =",
            "if compacted != (outcomes.clone(), live_removals.clone())",
            "self.append_encoded(&encoded, AppendPhase::OrdinaryRemove)",
            "self.sync_all_raw(SyncPhase::General)?;",
            "Ok(outcomes)",
        ),
    ),
    (
        "crates/iroha_core/src/queue.rs",
        "method",
        "Queue::prepare_plan_journal_replay_locked",
        (
            "self.ensure_plan_journal_replay_startup_shape_locked()?;",
            "self.plan_journal_replay_reservation_shape_locked()?;",
            "let journal_hashes = records",
            ".missing_payload_hashes",
            ".difference(&journal_hashes)",
            "let replay_observed_at = self.time_source.get_unix_time();",
            "for record in records {",
            "AcceptedTransaction::accept_entrypoint_at_time(",
            "queue_plan_replay_reservation_owner(",
            "let state_committed = state_view.transactions.get(&hash).is_some();",
            "let global_registry_match =",
            "self.is_expired_at_with_enqueue_timestamp(",
            "resolve_routing_plan_for_queue_admission(",
            "prepare_checked_for_enqueue(",
            "if self.transaction_selection_durability_faulted()",
            "let mut projected_active = self.active_len();",
            "let mut fifo_orders =",
            "let anchors = pending_admissions",
            "Ok(PreparedQueuePlanReplay {",
        ),
    ),
    (
        "crates/iroha_core/src/queue.rs",
        "method",
        "Queue::apply_plan_journal_replay_locked",
        (
            "*self.fee_admission_reservations.lock() = fee_reservations;",
            "*self.next_fifo_ordinal.lock() = next_fifo_ordinal;",
            "for replayed in admissions {",
            "self.fifo_order_by_hash.insert(hash, fifo_order);",
            "self.txs.insert(hash, Arc::clone(&tx_arc));",
            "self.durable_plan_claims.insert(hash, claim.clone());",
            "notifications.push(QueueAdmissionNotification {",
            "self.apply_per_user_tx_count_increments(per_user_increments);",
            "self.reconcile_missing_reservation_payloads_locked(&mut store);",
            "self.replace_fifo_locked(&final_fifo);",
            "(summary, notifications)",
        ),
    ),
    (
        "crates/iroha_core/src/queue.rs",
        "method",
        "Queue::replay_plan_journal",
        (
            "self.plan_journal_install_lock.lock()",
            "self.lane_reservation_transition_lock.lock()",
            "state.lock_lane_lifecycle_work_admission()",
            "let state_view = state.view();",
            "self.ensure_plan_journal_replay_startup_shape_locked()?;",
            "self.sync_nexus_routing_with_view(&state_view);",
            "let mut journal_guard = self.plan_journal.lock();",
            "let queue_guard = self.push_remove_lock.lock();",
            "let records = journal.prepare_replay()?.into_verified_records()?;",
            "let expected_record_claims = records",
            "let prepared = self.prepare_plan_journal_replay_locked(",
            "let observed_record_claims = journal",
            ".prepare_replay()?",
            ".into_verified_records()?",
            "if observed_record_claims != expected_record_claims",
            "let terminal_removals = prepared.terminal_removals.clone();",
            "remove_all_live_exact_atomic_strict_durable(&terminal_removals)",
            "self.apply_plan_journal_replay_locked(prepared)",
            "self.publish_admission_notifications(&notifications);",
            "Ok(summary)",
        ),
    ),
    (
        "crates/iroha_core/src/queue.rs",
        "method",
        "Queue::lane_reservation_reconciliation_snapshot",
        (
            "let _reservation_transition_guard = self.lane_reservation_transition_lock.lock();",
            "let _queue_guard = self.push_remove_lock.lock();",
            "if self.lane_reservation_journal.lock().is_none()",
            "let store = self.lane_reservations.lock();",
            "for record in store.live_by_hash.values() {",
            "let mut commit_barriers = store.commit_barriers.clone();",
            "commit_barriers.sort_by_key",
            "let mut prepared_release_barriers = store.release_barriers.clone();",
            "prepared_release_barriers.sort_by_key",
            "let mut completed_releases = store.completed_releases.clone();",
            "completed_releases.sort_by_key",
            "drop(store);",
            "ordered_records",
            "Ok(LaneQueueReservationReconciliationSnapshotV1 {",
        ),
    ),
    (
        "crates/iroha_core/src/sumeragi/v2_apply.rs",
        "fn",
        "plan_lane_reservation_ownership",
        (
            "let current_snapshot = queue.lane_reservation_reconciliation_snapshot()?;",
            "let (snapshot, recovered_receipt, deferred_terminal_recovery) = match lifecycle_handoff",
            "handoff.into_queue_handoff()",
            "if snapshot != current_snapshot",
            "revalidate_lane_reservation_startup_reconciliation_receipt(",
            "if snapshot.is_empty() {",
            "let release_barriers = snapshot.release_barriers();",
            "let commit_barriers = snapshot.commit_barriers.as_slice();",
            "for barrier in &release_barriers {",
            "for key in commit_barriers {",
            "let mut authenticated_committed_carriers =",
            "BTreeMap::<",
            "for input in inputs.iter_mut().filter(|input| input.committed) {",
            ".get_merge_entry_by_carrier_height(carrier_height)?",
            "authenticated_autonomous_carrier_application_projections(",
            "let reservation_group =",
            "lane_queue_reservation_group_binding_from_ordered_keys(",
            "input.commit_authorization = Some(",
            ".queue_cleanup_authorization()",
            "for input in &mut inputs {",
            "let authorization = input.commit_authorization.take().ok_or_else(||",
            "actions.push(ReservationReconciliationAction::Commit {",
            "if queue.lane_reservation_reconciliation_snapshot()? != snapshot",
            "let replay_receipt = match recovered_receipt",
            "LaneReservationReconciliationPlan {",
        ),
    ),
    (
        "crates/iroha_core/src/sumeragi/v2_apply.rs",
        "fn",
        "apply_lane_reservation_reconciliation_plan",
        (
            "historical_autonomous_install_is_durable",
            "revalidate_lane_reservation_startup_reconciliation_receipt(&replay_receipt, &snapshot)",
            "let mut authorized_commit_groups = Vec::new();",
            "for action in actions {",
            "ReservationReconciliationAction::Commit {",
            "authorized_commit_groups.push((keys, authorization))",
            "finalize_startup_committed_canonical_carriers(",
            "for action in remaining_actions {",
            "retire_autonomous_lane_slot_and_release_reservations(",
            "queue.release_strictly_absent_lane_reservations_in_order(",
            "let final_snapshot = queue.lane_reservation_reconciliation_snapshot()?;",
            "!final_snapshot.commit_barriers.is_empty()",
            "!final_snapshot.prepared_release_barriers.is_empty()",
            "!final_snapshot.completed_releases.is_empty()",
            "complete_deferred_autonomous_lifecycle_terminal_outcomes_after_queue_actions(",
            "queue.complete_lane_reservation_startup_reconciliation(replay_receipt)?;",
        ),
    ),
    (
        "crates/irohad/src/main.rs",
        "method",
        "Iroha::start_with_runtime_deps",
        (
            "install_lane_reservation_journal(",
            "install_plan_journal(",
            "replay_plan_journal(&state)",
            "IrohaNetwork::start_with_crypto_and_initial_trusted_sources(",
        ),
    ),
)
QUEUE_PLAN_STARTUP_REPLAY_FORBIDDEN_SOURCE_CHECKS = (
    (
        "crates/iroha_core/src/queue.rs",
        "method",
        "Queue::apply_plan_journal_replay_locked",
        (
            "?",
            "Result<",
            "return Err(",
            "expect(",
            "unwrap(",
            "panic!(",
            "unreachable!(",
        ),
    ),
    (
        "crates/iroha_core/src/sumeragi/v2_apply.rs",
        "fn",
        "plan_lane_reservation_ownership",
        (
            "live_lane_reservations()",
            "lane_reservation_commit_barriers()",
            "lane_reservation_release_barriers()",
            "AutonomousLaneQueueCarrierCleanupAuthorization::from_projection_for_test",
        ),
    ),
    (
        "crates/iroha_core/src/sumeragi/v2_apply.rs",
        "fn",
        "apply_lane_reservation_reconciliation_plan",
        (
            "lane_reservation_commit_barriers()",
            "lane_reservation_release_barriers()",
            "queue.commit_lane_reservation_group(",
            "commit_lane_reservation_group_with_authorization(",
        ),
    ),
)
QUEUE_PLAN_STARTUP_REPLAY_POST_APPLY_MARKER = (
    "let (summary, notifications) = self.apply_plan_journal_replay_locked(prepared);"
)
QUEUE_PLAN_STARTUP_REPLAY_POST_APPLY_FORBIDDEN_TOKENS = (
    "?",
    "return Err(",
    ".map_err(",
    "expect(",
    "unwrap(",
    "panic!(",
    "unreachable!(",
)
QUEUE_PLAN_STARTUP_REPLAY_TEST_BINDINGS = (
    (
        "crates/iroha_core/src/queue/journal.rs",
        "exact_atomic_live_tombstone_batch_rejects_retry_before_append",
        (
            "remove_all_live_exact_atomic_strict_durable(",
            "expect_err(",
            "io::ErrorKind::InvalidData",
            "the startup publication form must reject a mixed absent and live batch",
            "the all-live precondition must reject a mixed batch before append",
            "rejecting a mixed batch must retain its still-live member",
            "the all-live precondition must reject before another frame is appended",
        ),
    ),
    (
        "crates/iroha_core/src/queue/plan_journal_replay_tests.rs",
        "materialized_replay_rejects_later_record_corruption_before_any_callback",
        (
            ".get_mut(&second_key)",
            ".for_each_record(",
            "expect_err(",
            "callbacks, 0",
            "a valid earlier record must remain private when a later record is corrupt",
        ),
    ),
    (
        "crates/iroha_core/src/queue.rs",
        "queue_plan_journal_replay_retains_current_admission_rejection_and_fails_startup",
        (
            "expect_err(\"a current admission failure must abort startup\")",
            "failed current admission",
            "assert_eq!(replay_queue.active_len(), 0);",
            "live_record_count()",
            "without publishing or tombstoning a prefix",
        ),
    ),
    (
        "crates/iroha_core/src/queue.rs",
        "queue_plan_journal_replay_rejects_aggregate_per_user_overflow_without_prefix",
        (
            "capacity_per_user = nonzero!(1_usize)",
            "aggregate per-user overflow must reject the complete replay",
            "std::io::ErrorKind::PermissionDenied",
            "assert_eq!(replay_queue.active_len(), 0);",
            "live_record_count()",
        ),
    ),
    (
        "crates/iroha_core/src/queue.rs",
        "queue_plan_journal_replay_rejects_orphaned_startup_fifo_identity",
        (
            "fifo_order_by_hash.insert(orphan, fifo_order)",
            "an unowned startup FIFO identity must fail closed",
            "orphaned FIFO identity",
            "Some(fifo_order)",
        ),
    ),
    (
        "crates/iroha_core/src/queue/lane_reservation_tests.rs",
        "reservation_restart_fits_ordinary_fifo_around_middle_anchor",
        (
            "install_lane_reservation_journal(&reservation_path",
            "replay_plan_journal(&state)",
            "Some(u64::try_from(index)",
            "release_lane_reservations_in_order(&[reserved_key])",
            "restart replay must preserve A/B/C",
        ),
    ),
    (
        "crates/iroha_core/src/queue/reservation_recovery_tests.rs",
        "state_committed_live_reservation_replays_quarantined_until_explicit_proof_commit",
        (
            "authenticate and quarantine the sole payload source",
            "tombstoned_committed: 0",
            "assert!(queue.txs.contains_key(&hash));",
            "assert_eq!(queue.queued_len(), 0);",
            "missing_reservation_payload_count",
            "live_record_count()",
            "commit_lane_reservation_for_test(&key)",
            "lane_reservation_commit_barriers().is_empty()",
        ),
    ),
    (
        "crates/iroha_core/src/queue/reservation_recovery_tests.rs",
        "expired_live_reservation_replays_payload_without_fifo_or_tombstone",
        (
            "transaction_time_to_live: Duration::from_millis(1)",
            "time_handle.advance(Duration::from_millis(2));",
            "materialize expired payload under its durable reservation owner",
            "tombstoned_expired: 0",
            "assert_eq!(queue.queued_len(), 0);",
            "must not tombstone the sole payload source",
        ),
    ),
    (
        "crates/iroha_core/src/queue/lane_reservation_tests.rs",
        "restart_reconciliation_snapshot_is_fifo_group_complete_and_read_only",
        (
            "lane_reservation_reconciliation_snapshot()",
            "snapshot.commit_barriers.is_empty()",
            "snapshot.prepared_release_barriers.is_empty()",
            "snapshot.completed_releases.is_empty()",
            "snapshot.release_barriers().is_empty()",
            "assert_eq!(capture_store(), store_before);",
        ),
    ),
    (
        "crates/iroha_core/src/queue/lane_reservation_tests.rs",
        "ordered_release_restart_retains_barrier_until_explicit_evidence_gated_finalize",
        (
            "for crash_after_completion in [false, true]",
            "lane_reservation_reconciliation_snapshot()",
            "reconciliation_snapshot.prepared_release_barriers",
            "reconciliation_snapshot.completed_releases[0]",
            ".ordered_records",
            "reconciliation_snapshot.release_barriers()",
        ),
    ),
    (
        "crates/iroha_core/src/queue/lane_reservation_tests.rs",
        "reservation_group_forget_prefix_replays_and_resumes_exactly_once",
        (
            "assert_eq!(replay.commit_barriers, 1);",
            "lane_reservation_reconciliation_snapshot()",
            "reconciliation_snapshot.commit_barriers, vec![keys[2]]",
            "reconciliation_snapshot",
            ".prepared_release_barriers",
            "reconciliation_snapshot.completed_releases.is_empty()",
        ),
    ),
)
