//! Immutable compiler-captured identities for this source owner’s existing codecs.

#[test]
fn captured_codec_schema_identities() {
    crate::captured_schema_tests::assert_bidirectional::<super::BlobDigest>(
        "iroha_data_model::da::types::BlobDigest",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::StorageTicketId>(
        "iroha_data_model::da::types::StorageTicketId",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::BlobClass>(
        "iroha_data_model::da::types::BlobClass",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::BlobCodec>(
        "iroha_data_model::da::types::BlobCodec",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::Compression>(
        "iroha_data_model::da::types::Compression",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::GovernanceTag>(
        "iroha_data_model::da::types::GovernanceTag",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FecScheme>(
        "iroha_data_model::da::types::FecScheme",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ErasureProfile>(
        "iroha_data_model::da::types::ErasureProfile",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::RetentionPolicy>(
        "iroha_data_model::da::types::RetentionPolicy",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ExtraMetadata>(
        "iroha_data_model::da::types::ExtraMetadata",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MetadataEncryption>(
        "iroha_data_model::da::types::MetadataEncryption",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MetadataCipherEnvelope>(
        "iroha_data_model::da::types::MetadataCipherEnvelope",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MetadataEntry>(
        "iroha_data_model::da::types::MetadataEntry",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MetadataVisibility>(
        "iroha_data_model::da::types::MetadataVisibility",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::DaRentPolicyV1>(
        "iroha_data_model::da::types::DaRentPolicyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::DaRentQuote>(
        "iroha_data_model::da::types::DaRentQuote",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::DaRentLedgerProjection>(
        "iroha_data_model::da::types::DaRentLedgerProjection",
    );
}
