//! Immutable compiler-captured identities for this source owner’s existing codecs.

#[test]
fn captured_codec_schema_identities() {
    crate::captured_schema_tests::assert_bidirectional::<super::GatewayHostSet>(
        "iroha_data_model::soradns::GatewayHostSet",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ResolverTransportBundle>(
        "iroha_data_model::soradns::ResolverTransportBundle",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::HttpTransportV1>(
        "iroha_data_model::soradns::HttpTransportV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::TlsTransportV1>(
        "iroha_data_model::soradns::TlsTransportV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::QuicTransportV1>(
        "iroha_data_model::soradns::QuicTransportV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OdohRelayV1>(
        "iroha_data_model::soradns::OdohRelayV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoranetBridgeConfigV1>(
        "iroha_data_model::soradns::SoranetBridgeConfigV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PaddingPolicyV1>(
        "iroha_data_model::soradns::PaddingPolicyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ResolverTlsBundle>(
        "iroha_data_model::soradns::ResolverTlsBundle",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::TlsProvisioningProfile>(
        "iroha_data_model::soradns::TlsProvisioningProfile",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::RotationPolicyV1>(
        "iroha_data_model::soradns::RotationPolicyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ResolverAttestationDocumentV1>(
        "iroha_data_model::soradns::ResolverAttestationDocumentV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ResolverDirectoryRecordV1>(
        "iroha_data_model::soradns::ResolverDirectoryRecordV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PendingDirectoryDraftV1>(
        "iroha_data_model::soradns::PendingDirectoryDraftV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ResolverRevocationRecordV1>(
        "iroha_data_model::soradns::ResolverRevocationRecordV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::DirectoryRotationPolicyV1>(
        "iroha_data_model::soradns::DirectoryRotationPolicyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ResolverDirectoryEventV1>(
        "iroha_data_model::soradns::ResolverDirectoryEventV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::RadRevokeReason>(
        "iroha_data_model::soradns::RadRevokeReason",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::DirectoryDraftSubmittedEventV1>(
        "iroha_data_model::soradns::DirectoryDraftSubmittedEventV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::DirectoryPublishedEventV1>(
        "iroha_data_model::soradns::DirectoryPublishedEventV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::DirectoryRevokedEventV1>(
        "iroha_data_model::soradns::DirectoryRevokedEventV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::DirectoryUnrevokedEventV1>(
        "iroha_data_model::soradns::DirectoryUnrevokedEventV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::DirectoryReleaseSignerEventV1>(
        "iroha_data_model::soradns::DirectoryReleaseSignerEventV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::DirectoryPolicyUpdatedEventV1>(
        "iroha_data_model::soradns::DirectoryPolicyUpdatedEventV1",
    );
}
