//! Immutable compiler-captured identities for this source owner’s existing codecs.

const CASES: &[crate::captured_schema_tests::Case] = &[
    crate::captured_schema_tests::Case::bidirectional::<super::VpnAddressSlotV1>(
        "iroha_data_model::soranet::vpn::VpnAddressSlotV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::VpnCellClassV1>(
        "iroha_data_model::soranet::vpn::VpnCellClassV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::VpnCellFlagsV1>(
        "iroha_data_model::soranet::vpn::VpnCellFlagsV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::VpnFlowLabelV1>(
        "iroha_data_model::soranet::vpn::VpnFlowLabelV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::VpnCellHeaderV1>(
        "iroha_data_model::soranet::vpn::VpnCellHeaderV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::VpnCellV1>(
        "iroha_data_model::soranet::vpn::VpnCellV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::VpnCoverScheduleV1>(
        "iroha_data_model::soranet::vpn::VpnCoverScheduleV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::VpnCoverPlanEntryV1>(
        "iroha_data_model::soranet::vpn::VpnCoverPlanEntryV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::VpnExitClassV1>(
        "iroha_data_model::soranet::vpn::VpnExitClassV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::VpnControlPlaneV1>(
        "iroha_data_model::soranet::vpn::VpnControlPlaneV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::VpnRouteV1>(
        "iroha_data_model::soranet::vpn::VpnRouteV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::VpnUsageVoucherBodyV1>(
        "iroha_data_model::soranet::vpn::VpnUsageVoucherBodyV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::VpnUsageVoucherV1>(
        "iroha_data_model::soranet::vpn::VpnUsageVoucherV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::VpnUsageVoucherEnvelopeV1>(
        "iroha_data_model::soranet::vpn::VpnUsageVoucherEnvelopeV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::VpnTariffV1>(
        "iroha_data_model::soranet::vpn::VpnTariffV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::VpnQuotePolicyV1>(
        "iroha_data_model::soranet::vpn::VpnQuotePolicyV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::VpnQuoteBodyV1>(
        "iroha_data_model::soranet::vpn::VpnQuoteBodyV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::VpnSignedQuoteV1>(
        "iroha_data_model::soranet::vpn::VpnSignedQuoteV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::VpnLeaseStatusV1>(
        "iroha_data_model::soranet::vpn::VpnLeaseStatusV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::VpnLeaseRecordV1>(
        "iroha_data_model::soranet::vpn::VpnLeaseRecordV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::VpnSessionReceiptV1>(
        "iroha_data_model::soranet::vpn::VpnSessionReceiptV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::VpnSignedSessionReceiptV1>(
        "iroha_data_model::soranet::vpn::VpnSignedSessionReceiptV1",
    ),
];

#[test]
fn captured_codec_schema_identities() {
    for case in CASES {
        case.check();
    }
}
