
#+LANGUAGE: zh-hant
#+DIRECTION: ltr
#+SOURCE: docs/source/lts_selection.org
#+STATUS: complete
#+GENERATOR: scripts/sync_docs_i18n.py
#+SOURCE_HASH: 1535fc970027c05003b4e03135f47b565d1434f8dc3c42946525a1b16252d40d
#+SOURCE_LAST_MODIFIED: 2026-01-05T09:28:12.022775+00:00
#+TRANSLATION_LAST_REVIEWED: 2026-02-07

#+TITLE: On selecting versions as LTS candidates
#+AUTHOR: Aleksandr Petrosyan
#+DATE: 12-08-2023
#+TRANSLATOR: machine-google-reviewed

#+TITLE: On selecting versions as LTS candidates
#+AUTHOR: Aleksandr Petrosyan
#+DATE: 12-08-2023
* 關於

為了保護工程資源，我們有責任
限制發布後支持範圍的利益。如果一個人有
Iroha 的多個版本並行運行，它們可能需要
盡可能多地重複支持工作
版本。

我們沒有試圖糟糕地支持多個版本，而是嘗試
用 20% 的努力滿足 80% 的用例並達到
平等且僅支持每個已發布版本之間的妥協
支持最新穩定版本。

具體來說，我們支持最新的 =stable= 版本。經常這樣
發布版本要么沒有經過充分測試、沒有充分記錄，要么
得到 SDK 的良好支持，此外還經常發生變化
因此，每月發布一次，並選擇每年一次發布
成為長期支持和發展的目標。

* LTS選擇標準

以下是建議注意事項的非詳盡列表
用於選擇特定版本作為 LTS 候選版本

1. 該版本應該/不太可能/包含主要/已知/問題
   會妨礙它發揮作用。

   更具體地說，該版本應該很好地覆蓋
   基本用例，例如，(Pre-)RC-6[fn:1] 是最後一個版本
   包含舊的共識引擎。鑑於基於演員
   共識的最大穩定吞吐量為 10 TPS，(Pre-)RC-6 是
   儘管被用作 LTS，但並未標記為 LTS。

   RC-9 包含運行 Iroha 節點的所有必要功能
   根據新的共識，對結構進行了一些改變
   配置以及對 =p2p= 子系統的一些修復。它可能有
   填補了基於 Iroha 的任何項目的所有可能的空白，並且
   因此，儘管不太好，它還是被標記為 LTS 版本
   已測試。

   RC8、RC12、RC13 和 RC17 版本因此被取消資格
   標準。

2. 如果存在導致 API 損壞的大型功能，
   具有最穩定版本的“舊方法”的版本
   事物”應該優先作為 LTS 候選者。

   例如，RC12 和 RC13 是 Iroha 的最後一個版本
   仍然使用硬編碼的權限驗證器。他們被貼上標籤
   作為 LTS 候選人，由於主要的已知問題而被排除在外，
   特別是穩定性、覆蓋範圍差，並且因為釋放
   RC9 之後的 LTS 會分割開發資源
   解決嚴格的不可修改權限驗證器的問題。

   另一方面，RC14 和 RC15 正處於緩慢的發展過程中。
   特徵的遷移。因此，後面的版本將是
   考慮直接升級之前的，有更多
   優化和更好的功能覆蓋。

3. 該版本必須針對用例提供完整的功能。這與第 1 點不同，因為雖然 RC10 和 RC13 是免費的
   對於重大問題，他們沒有提供足夠全面的覆蓋
   主要項目利益相關者所需的功能。

4. 該版本必須得到所有SDK的支持。

   雖然 Iroha Python 中的支持主要局限於 LTS
   考生，造成第22條軍規的局面，實屬例外。的
   另外兩個主要的 SDK，即 Kotlin 和 TypeScript 必須支持
   LTS 候選人。如果SDK無法支持
   候選人，該候選人被取消資格。

5. 發布必須經過充分測試。

   這一點補充了第一點，因為缺乏已知的特徵
   事實上，加上糟糕的測試覆蓋率並不意味著可以免受
   主要問題。

   這通常適用於 RC6 之後到 RC17 之前的所有版本，因為
   開發團隊被告知重組的方法
   集成測試，但該過程僅以 RC17 結束，
   引入 =pytest= 框架。

   雖然通過集成測試是必要的，但這還不夠，
   需要進行以下最低限度的測試才能使發布符合要求
   LTS 候選人

   1. 單元和集成測試。必須小心運行所有
      集成測試，包括長的和片狀的測試。如果測試
      異常片狀，表明存在問題，並且
      發布應被取消資格（參見 [[../../flakyness.org]]）。

   2. =pytest= 測試，技術上符合集成要求
      測試。

   3.壽命測試。候選人必須接受至少兩項測試
      幾週才有資格。如果候選人被接受為 LTS，則
      壽命測試應進行至少四個星期。

   4.負載測試。 LTS 候選人必須滿足所有標準
      由 QA 團隊制定為運營和開發
      負載下的要求（也稱為額外功能，和
      被誤認為是非功能性的）。未能在 a 中生成區塊
      及時時尚是自動取消資格。其他
      取消資格標準由 QA 自行決定
      團隊。

   5. 必須作為 =development= 容器部署在至少一個
      項目至少兩週，沒有出現大問題。 RC9做到了
      未通過此測試，將被取消資格
      本文件中列出的更新標準。

6. 發布必須有詳細記錄。

   它不應包含多個缺乏的新功能
   文檔。文檔覆蓋範圍方面的任何不足
   必須最多在發布窗口的時間範圍內修復
   為候選人。否則將自動取消資格。

除了中概述的常規發布程序之外
[[release_procedure.org]]，LTS 必須遵守以下附加條款
步驟。除了執行常規發布之外，還需要一個單獨的 PR
標題 =[release]: <semver> LTS= 其中 =<semver>= 是語義
必須創建來自開發分支的代碼版本。的
必須避免常規檢查表，而必須使用 Pull Request
由審查和批准該文件的同一人員進行審查
=stable= 發布。最多需要兩次審查，以確保所有
更改將按正確的順序進行，並且不會
未記錄的問題被忽略了。

一旦 LTS 版本發布，CI 將生成一個 docker 容器
隨著 Alpine Linux 平台和 Ubuntu Linux 上的 LTS 版本的發布，
使用 =glibc= 的平臺本機版本。 CI 還必須提供
所有受支持的包，並將它們發佈到各自的
存儲庫。例如，這意味著 AUR 包已更新
合併拉取請求並生成正確的包後。的
GitHub 發布頁面必須填充名為
LTS 並包含單文件 =AppImage=。這些版本必須
作為單獨的軟件包出現，這些軟件包被標記為不可與
穩定版本。

* 向後移植政策

通常，不鼓勵向後移植到 LTS。以下
向後移植的原因被認為是可以接受的：
1. 與 Iroha API 無關的添加，例如將軍
   輔助工具和/或文檔。
2.修復重大安全漏洞。
3.修復一個重大bug。
4. 修復妨礙使用的重大設計疏忽，前提是：
   當前 LTS 的主要利益相關者/用戶已口頭表示
   證明向後移植是更好的解決方案。

向後移植必須通過與發布版本相同的渠道宣布
本身。所需的更改必須在兩個版本中都標記為向後移植
修復它們的上游版本以及其中的版本
它們已被向後移植。

公告必須說明
1. 為什麼選擇向後移植（參見上述原因）
2. 向後移植的影響是什麼
3. 功能、集成和應用的現狀如何？
   負載/壽命測試。

* 適用性

LTS/穩定版本政策應在第一次發布後立即修改
Iroha 的功能完整版本已發布 (v2.0.0)。不再給予
積極開發，核心開發團隊可以（並且應該）能夠
更加關注對不同版本的支持。

* 腳註[fn:1] 命名約定早在任何計劃之前就已經穩定下來
發布了 Iroha 的版本。  因此調用任何版本的
Iroha 候選版本有一些影響。  稱他們為預
發布候選者是一種類似的用詞不當，但不那麼令人震驚，
因為這不是對現有術語的誤用，而是
發明一個術語，/可能/與
釋放候選人。  實際上這些應該被稱為
*開發快照*。  但為了不破壞連續性
對於現有的 SDK，我們選擇了一種折衷方案。