name: OpenSSF Scorecard

on:
  push:
    branches: [main]
  schedule:
    - cron: "37 3 * * 1"

jobs:
  scorecard:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      id-token: write
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
      - name: Upload Scorecard SARIF
        uses: github/codeql-action/upload-sarif@4187e74d05793876e9989daffde9c3e66b4acd07
        with:
          sarif_file: results.sarif
