"""Tests for scripts/check_sorafs_hedging_fixture_manifest.py."""

from __future__ import annotations

import importlib.util
import json
import os
import sys
from argparse import Namespace
from pathlib import Path


MODULE_PATH = Path(__file__).resolve().parents[1] / "check_sorafs_hedging_fixture_manifest.py"
SPEC = importlib.util.spec_from_file_location("check_sorafs_hedging_fixture_manifest", MODULE_PATH)
MODULE = importlib.util.module_from_spec(SPEC)
assert SPEC and SPEC.loader  # pragma: no cover - defensive
sys.modules[SPEC.name] = MODULE
SPEC.loader.exec_module(MODULE)

REPO_ROOT = Path(__file__).resolve().parents[2]
SOURCE_MANIFEST = REPO_ROOT / "fixtures" / "sorafs_manifest" / "hedging" / "fixture_manifest.json"


def write_manifest(path: Path, payload: dict) -> Path:
    """Write a fixture manifest for checker tests."""

    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return path


def base_manifest() -> dict:
    """Return the checked-in fixture manifest payload."""

    return json.loads(SOURCE_MANIFEST.read_text(encoding="utf-8"))


def write_generated_pairs(root: Path, payload: dict) -> None:
    """Write minimal generated byte/JSON pairs under a temporary repo root."""

    for fixture in payload["fixtures"]:
        norito_path = root / fixture["norito_path"]
        json_path = root / fixture["json_path"]
        norito_path.parent.mkdir(parents=True, exist_ok=True)
        json_path.parent.mkdir(parents=True, exist_ok=True)
        norito_bytes = fixture["name"].encode("utf-8")
        norito_path.write_bytes(norito_bytes)
        sidecar = generated_sidecar(fixture)
        sidecar["norito_bytes_hex"] = norito_bytes.hex()
        json_path.write_text(json.dumps(sidecar), encoding="utf-8")


def generated_sidecar(fixture: dict) -> dict:
    """Return a minimal valid generated sidecar for a manifest fixture."""

    if fixture["kind"] == "price-feed":
        return generated_price_feed_sidecar(fixture["name"])
    if fixture["kind"] == "reference-price-decision":
        return generated_reference_price_sidecar(fixture["expected_status"] == "rejected")
    if fixture["kind"] == "billing-line-item":
        return generated_billing_line_sidecar(fixture["name"])
    if fixture["kind"] == "billing-statement":
        return {
            "account_id": "provider-a",
            "account_id_hex": "70726f76696465722d61",
            "due_at_unix": 1_700_691_200,
            "lines": [generated_billing_line_sidecar("billing_line_storage_v1")],
            "net_due_usd": "0.001",
            "net_due_xor": "1",
            "period_end_unix": 1_700_604_800,
            "period_start_unix": 1_700_000_000,
            "previous_statement_id_hex": "12" * 32,
            "reference_price": generated_reference_price_sidecar(
                fixture["expected_status"] == "rejected"
            ),
            "statement_id_hex": "34" * 32,
            "total_credit_usd": "0",
            "total_credit_xor": "0",
            "total_debit_usd": "0.001",
            "total_debit_xor": "1",
            "version": 1,
        }
    raise AssertionError(f"unexpected fixture kind: {fixture['kind']}")


def generated_price_feed_sidecar(name: str) -> dict:
    """Return a generated price-feed JSON object without Norito bytes."""

    return {
        "evidence_digest_hex": "ab" * 32,
        "feed_id": name,
        "observed_at_unix": 1_700_604_700,
        "source": "test-source",
        "status": "degraded" if "secondary" in name else "ok",
        "version": 1,
        "weight_bps": 5_000,
        "xor_usd_price": "2",
    }


def generated_reference_price_sidecar(rejected: bool) -> dict:
    """Return a generated reference-price JSON object without Norito bytes."""

    return {
        "decision_id_hex": "cd" * 32,
        "degradation_reasons": ["fixture"],
        "degraded": rejected,
        "effective_at_unix": 1_700_604_800,
        "feeds": [
            generated_price_feed_sidecar("price_feed_primary_v1"),
            generated_price_feed_sidecar("price_feed_secondary_v1"),
        ],
        "max_divergence_bps": 500,
        "max_feed_age_secs": 300,
        "version": 1,
        "xor_usd_price": "2",
    }


def generated_billing_line_sidecar(name: str) -> dict:
    """Return a generated billing-line JSON object without Norito bytes."""

    return {
        "direction": "credit" if "credit" in name else "debit",
        "kind": "incentive_credit" if "credit" in name else "storage",
        "line_id_hex": "ef" * 32,
        "note": None,
        "quantity_units": "1",
        "source_id": name,
        "usd_amount": "2",
        "version": 1,
        "xor_amount": "1",
    }


def test_exact_quantity_string_policy_matches_v1_bounds() -> None:
    assert MODULE.is_quantity_string("0", max_scale=MODULE.MAX_QUANTITY_SCALE)
    assert MODULE.is_quantity_string("0.000000001", max_scale=MODULE.MAX_XOR_QUANTITY_SCALE)
    assert MODULE.is_quantity_string(
        str(MODULE.MAX_QUANTITY_MANTISSA),
        max_scale=MODULE.MAX_QUANTITY_SCALE,
    )
    assert MODULE.is_quantity_string(
        "0." + "0" * 27 + "1",
        max_scale=MODULE.MAX_QUANTITY_SCALE,
    )

    for value in (
        "",
        "00",
        "01",
        "1.0",
        "1.",
        "+1",
        "-1",
        "1e3",
        str(MODULE.MAX_QUANTITY_MANTISSA + 1),
    ):
        assert not MODULE.is_quantity_string(value, max_scale=MODULE.MAX_QUANTITY_SCALE)
    assert not MODULE.is_quantity_string(
        "0.0000000001",
        max_scale=MODULE.MAX_XOR_QUANTITY_SCALE,
    )


def write_fake_validator(path: Path, reject_negative: bool) -> Path:
    """Write a fake sorafs-validate executable for checker tests."""

    path.write_text(
        "\n".join(
            [
                "#!/usr/bin/env python3",
                "import sys",
                "joined = ' '.join(sys.argv[1:])",
                f"if {reject_negative!r} and '/negative/' in joined:",
                "    raise SystemExit(2)",
                "raise SystemExit(0)",
                "",
            ]
        ),
        encoding="utf-8",
    )
    path.chmod(0o755)
    return path


def write_sentinel_validator(path: Path, sentinel: Path) -> Path:
    """Write a fake validator that records execution before succeeding."""

    path.write_text(
        "\n".join(
            [
                "#!/usr/bin/env python3",
                "from pathlib import Path",
                f"Path({str(sentinel)!r}).write_text('executed', encoding='utf-8')",
                "raise SystemExit(0)",
                "",
            ]
        ),
        encoding="utf-8",
    )
    path.chmod(0o755)
    return path


def test_manifest_only_accepts_checked_in_inventory(tmp_path: Path) -> None:
    manifest = write_manifest(tmp_path / "fixture_manifest.json", base_manifest())
    summary = tmp_path / "summary.json"

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--manifest-only",
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 0
    payload = json.loads(summary.read_text(encoding="utf-8"))
    assert payload["status"] == "ok"
    assert payload["manifest_only"] is True
    assert payload["entry_count"] == 10
    assert {entry["generated"] for entry in payload["entries"]} == {"not_checked"}


def test_checked_in_manifest_matches_required_fixture_inventory() -> None:
    payload = base_manifest()

    assert {fixture["name"] for fixture in payload["fixtures"]} == MODULE.REQUIRED_FIXTURES
    assert {
        fixture["expected_status"] for fixture in payload["fixtures"]
    } == MODULE.EXPECTED_STATUSES
    for fixture in payload["fixtures"]:
        assert fixture["expected_status"] in MODULE.EXPECTED_STATUSES


def test_summary_out_same_as_manifest_fails_before_write(
    tmp_path: Path,
    capsys,
) -> None:
    manifest = write_manifest(tmp_path / "fixture_manifest.json", base_manifest())
    original = manifest.read_text(encoding="utf-8")
    summary = manifest

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--manifest-only",
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 2
    assert manifest.read_text(encoding="utf-8") == original
    captured = capsys.readouterr()
    assert "must not be the same path as --manifest" in captured.err
    assert captured.out == ""


def test_preflight_sanitizes_non_path_summary_out_label() -> None:
    errors = MODULE.validate_fixture_manifest_preflight(
        Namespace(manifest=Path("fixture_manifest.json"), summary_out=object())
    )

    assert errors == ["--summary-out `<non-path>` must be a path"]


def test_preflight_sanitizes_non_path_manifest_label() -> None:
    errors = MODULE.validate_fixture_manifest_preflight(
        Namespace(manifest=object(), summary_out=None)
    )

    assert errors == ["--manifest `<non-path>` must be a path"]


def test_manifest_unsafe_path_fails_before_read_without_leaking(
    tmp_path: Path,
    capsys,
    monkeypatch,
) -> None:
    manifest = tmp_path / "private%26%2395%3Bkey.json"
    summary = tmp_path / "summary.json"

    def load_manifest(*_args, **_kwargs):
        raise AssertionError("unsafe manifest path must not be loaded")

    monkeypatch.setattr(MODULE, "load_manifest", load_manifest)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--manifest-only",
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 2
    assert not summary.exists()
    captured = capsys.readouterr()
    assert "SoraFS checker-rendered paths must not contain secret-looking" in captured.err
    assert "private%26%2395%3Bkey" not in captured.err
    assert "private&#95;key" not in captured.err
    assert "private_key" not in captured.err
    assert captured.out == ""


def test_summary_out_directory_fails_before_write(
    tmp_path: Path,
    capsys,
) -> None:
    manifest = write_manifest(tmp_path / "fixture_manifest.json", base_manifest())
    summary = tmp_path / "summary-dir"
    summary.mkdir()

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--manifest-only",
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 2
    captured = capsys.readouterr()
    assert "must not be a directory" in captured.err
    assert captured.out == ""


def test_summary_out_symlink_fails_before_manifest_read(
    tmp_path: Path,
    capsys,
    monkeypatch,
) -> None:
    manifest = write_manifest(tmp_path / "fixture_manifest.json", base_manifest())
    target = tmp_path / "actual-summary.json"
    target.write_text("old", encoding="utf-8")
    summary = tmp_path / "summary.json"
    summary.symlink_to(target)
    original_open = os.open

    def open_path(path: Path, flags: int, *args, **kwargs):
        if path == manifest:
            raise AssertionError("manifest should not be read after summary preflight fails")
        return original_open(path, flags, *args, **kwargs)

    monkeypatch.setattr(os, "open", open_path)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--manifest-only",
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 2
    assert target.read_text(encoding="utf-8") == "old"
    captured = capsys.readouterr()
    assert "must not be a symlink" in captured.err
    assert captured.out == ""


def test_summary_out_parent_chain_symlink_fails_before_write(
    tmp_path: Path,
    capsys,
) -> None:
    manifest = write_manifest(tmp_path / "fixture_manifest.json", base_manifest())
    target_parent = tmp_path / "actual-parent"
    target_parent.mkdir()
    parent = tmp_path / "summary-parent"
    parent.symlink_to(target_parent, target_is_directory=True)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--manifest-only",
            "--summary-out",
            str(parent / "nested" / "summary.json"),
        ]
    )

    assert rc == 2
    assert not (target_parent / "nested").exists()
    captured = capsys.readouterr()
    assert "must not be a symlink" in captured.err
    assert captured.out == ""


def test_inspect_regular_file_sanitizes_noncanonical_path_and_error(
    monkeypatch,
) -> None:
    errors: list[str] = []

    def is_file(path: Path) -> bool:
        if str(path) == "bad\nmanifest":
            raise OSError("denied\nsecret")
        return False

    monkeypatch.setattr(Path, "is_file", is_file)

    assert MODULE.inspect_regular_file(Path("bad\nmanifest"), "manifest", errors) is None
    assert errors == [
        "failed to inspect manifest `<non-canonical-path>`: <non-canonical-error>"
    ]


def test_inspect_directory_sanitizes_non_path_label() -> None:
    errors: list[str] = []

    assert MODULE.inspect_directory(object(), "generated fixture root", errors) is None
    assert errors == ["generated fixture root `<non-path>` must be a path"]


def test_manifest_read_error_writes_blocked_summary_without_traceback(
    tmp_path: Path,
    monkeypatch,
) -> None:
    manifest = write_manifest(tmp_path / "fixture_manifest.json", base_manifest())
    summary = tmp_path / "summary.json"
    original_open = os.open

    def open_path(path: Path, flags: int, *args, **kwargs):
        if path == manifest:
            raise OSError("manifest read denied")
        return original_open(path, flags, *args, **kwargs)

    monkeypatch.setattr(os, "open", open_path)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--manifest-only",
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert result["manifest_sha256"] is None
    assert any(
        "failed to read manifest" in error and "manifest read denied" in error
        for error in result["errors"]
    )


def test_manifest_rejects_non_standard_json_constants(
    tmp_path: Path,
) -> None:
    manifest = tmp_path / "fixture_manifest.json"
    manifest.write_text('{"schema_version": NaN}', encoding="utf-8")
    summary = tmp_path / "summary.json"

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--manifest-only",
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert result["manifest_sha256"] is None
    assert any("non-standard JSON constant `NaN`" in error for error in result["errors"])


def test_load_manifest_sanitizes_noncanonical_path_decode_error(
    tmp_path: Path,
) -> None:
    manifest = tmp_path / "bad\nmanifest.json"
    manifest.write_text("[]", encoding="utf-8")
    errors: list[str] = []

    payload, digest = MODULE.load_manifest(manifest, errors)

    assert payload == {}
    assert digest is None
    assert errors == [
        "manifest is not valid bounded JSON object: <non-canonical-error>"
    ]


def test_default_mode_fails_closed_when_generated_bytes_are_missing(
    tmp_path: Path,
    monkeypatch,
) -> None:
    manifest = write_manifest(tmp_path / "fixture_manifest.json", base_manifest())
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", tmp_path / "repo")

    rc = MODULE.main(["--manifest", str(manifest), "--summary-out", str(summary)])

    assert rc == 1
    payload = json.loads(summary.read_text(encoding="utf-8"))
    assert payload["status"] == "blocked"
    assert payload["manifest_only"] is False
    assert any("missing generated Norito fixture" in error for error in payload["errors"])


def test_full_mode_rejects_unreadable_generated_fixture_without_traceback(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    target = repo_root / payload["fixtures"][0]["norito_path"]
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    original_open = os.open
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    def open_path(path: Path, flags: int, *args, **kwargs):
        if path == target:
            raise OSError("generated fixture read denied")
        return original_open(path, flags, *args, **kwargs)

    monkeypatch.setattr(os, "open", open_path)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any(
        "failed to read generated Norito fixture" in error
        and "generated fixture read denied" in error
        for error in result["errors"]
    )


def test_read_file_bytes_sanitizes_noncanonical_path_and_error(
    monkeypatch,
) -> None:
    errors: list[str] = []

    def read_evidence_bytes(path: Path, max_bytes: int) -> bytes:
        assert max_bytes == 16
        if str(path) == "bad\nfixture.to":
            raise OSError("read denied\nsecret")
        return b"fixture"

    monkeypatch.setattr(MODULE, "read_evidence_bytes", read_evidence_bytes)

    assert (
        MODULE.read_file_bytes(
            Path("bad\nfixture.to"),
            "generated Norito fixture",
            errors,
            max_bytes=16,
        )
        is None
    )
    assert errors == [
        "failed to read generated Norito fixture `<non-canonical-path>`: "
        "<non-canonical-error>"
    ]


def test_read_file_bytes_uses_typed_oversize_error(monkeypatch) -> None:
    errors: list[str] = []

    def read_evidence_bytes(_path: Path, max_bytes: int) -> bytes:
        raise MODULE.EvidenceFileTooLargeError(max_bytes)

    monkeypatch.setattr(MODULE, "read_evidence_bytes", read_evidence_bytes)

    assert (
        MODULE.read_file_bytes(
            Path("fixture.to"),
            "generated Norito fixture",
            errors,
            max_bytes=16,
        )
        is None
    )
    assert errors == ["generated Norito fixture exceeds 16 bytes: fixture.to"]


def test_generated_json_sidecar_missing_path_sanitizes_label() -> None:
    errors: list[str] = []

    assert MODULE.load_generated_json_sidecar(Path("bad\nsidecar.json"), errors) is None
    assert errors == ["missing generated JSON fixture: <non-canonical-path>"]


def test_generated_json_sidecar_sanitizes_noncanonical_path_decode_error(
    tmp_path: Path,
) -> None:
    sidecar = tmp_path / "bad\nsidecar.json"
    sidecar.write_text("[]", encoding="utf-8")
    errors: list[str] = []

    assert MODULE.load_generated_json_sidecar(sidecar, errors) is None
    assert errors == [
        "<non-canonical-path> is not a valid bounded JSON object: "
        "<non-canonical-error>"
    ]


def test_manifest_only_rejects_drifted_validation_command(tmp_path: Path) -> None:
    payload = base_manifest()
    payload["fixtures"][0]["validation_command"] = (
        "sorafs-validate hedging --kind billing-statement --input wrong.to"
    )
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--manifest-only",
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any("validation_command must be" in error for error in result["errors"])


def test_validation_command_tokenize_error_is_sanitized(monkeypatch) -> None:
    errors: list[str] = []
    entry = {
        "name": "bad_command",
        "kind": "billing-statement",
        "expected_status": "accepted",
        "validation_command": (
            "sorafs-validate hedging --kind billing-statement --input 'unterminated"
        ),
    }

    def split_raises(_command: str):
        raise ValueError("unterminated\nquote")

    monkeypatch.setattr(MODULE.shlex, "split", split_raises)

    MODULE.validate_expected_status(
        entry,
        Path("fixtures/sorafs_manifest/hedging/statement.to"),
        "sorafs-validate",
        1,
        {},
        errors,
    )

    assert errors == [
        "bad_command validation_command is not shell-tokenizable: "
        "<non-canonical-error>"
    ]


def test_validation_command_token_mismatch_is_sanitized() -> None:
    errors: list[str] = []
    entry = {
        "name": "bad_command",
        "kind": "billing-statement",
        "expected_status": "accepted",
        "validation_command": (
            "sorafs-validate hedging --kind billing-statement --input "
            "fixtures/sorafs_manifest/hedging/statement.to "
            "--private-key runtime-secret"
        ),
    }

    MODULE.validate_expected_status(
        entry,
        Path("fixtures/sorafs_manifest/hedging/statement.to"),
        "sorafs-validate",
        1,
        {},
        errors,
    )

    rendered = json.dumps(errors)
    assert errors == [
        f"bad_command {MODULE.VALIDATION_COMMAND_TOKENS_DIAGNOSTIC}"
    ]
    assert "--private-key" not in rendered
    assert "private_key" not in rendered
    assert "runtime-secret" not in rendered


def test_manifest_only_rejects_negative_case_drift(tmp_path: Path) -> None:
    payload = base_manifest()
    fixture = next(
        item
        for item in payload["fixtures"]
        if item["name"] == "stale_reference_price_decision_v1"
    )
    fixture["negative_case"] = "totals_mismatch"
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--manifest-only",
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any(
        "negative_case must be `stale_feed`" in error
        for error in result["errors"]
    )


def test_manifest_only_rejects_rejected_fixtures_outside_negative_dir(
    tmp_path: Path,
) -> None:
    payload = base_manifest()
    fixture = next(
        item
        for item in payload["fixtures"]
        if item["name"] == "stale_reference_price_decision_v1"
    )
    fixture["norito_path"] = (
        "fixtures/sorafs_manifest/hedging/stale_reference_price_decision_v1.to"
    )
    fixture["json_path"] = (
        "fixtures/sorafs_manifest/hedging/stale_reference_price_decision_v1.json"
    )
    fixture["validation_command"] = (
        "sorafs-validate hedging --kind reference-price-decision --input "
        "fixtures/sorafs_manifest/hedging/stale_reference_price_decision_v1.to"
    )
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--manifest-only",
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any(
        "rejected fixture paths must both stay under negative/" in error
        for error in result["errors"]
    )


def test_full_mode_rejects_missing_fixture_paths_without_traceback(
    tmp_path: Path,
) -> None:
    payload = base_manifest()
    del payload["fixtures"][0]["norito_path"]
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"

    rc = MODULE.main(["--manifest", str(manifest), "--summary-out", str(summary)])

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert result["entries"][0]["generated"] == "not_checked"
    assert any("fixtures[0].norito_path" in error for error in result["errors"])


def test_full_mode_rejects_absolute_fixture_paths_before_read(
    tmp_path: Path,
) -> None:
    payload = base_manifest()
    payload["fixtures"][0]["norito_path"] = "/tmp/sorafs-outside.to"
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"

    rc = MODULE.main(["--manifest", str(manifest), "--summary-out", str(summary)])

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert result["entries"][0]["generated"] == "not_checked"
    assert any("repository-relative path" in error for error in result["errors"])
    assert not any("/tmp/sorafs-outside.to" in error for error in result["errors"])


def test_manifest_only_rejects_secret_looking_fixture_name_without_echo(
    tmp_path: Path,
) -> None:
    payload = base_manifest()
    payload["fixtures"][0]["name"] = "private_key_v1"
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--manifest-only",
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    rendered = summary.read_text(encoding="utf-8")
    result = json.loads(rendered)
    assert result["status"] == "blocked"
    assert any("fixtures[0].name has invalid shape" in error for error in result["errors"])
    assert "private_key_v1" not in rendered
    assert "private_key" not in rendered
    assert "private-key" not in rendered


def test_manifest_only_rejects_encoded_secret_fixture_path_without_echo(
    tmp_path: Path,
) -> None:
    payload = base_manifest()
    payload["fixtures"][0]["norito_path"] = (
        "fixtures/sorafs_manifest/hedging/private%26%2395%3Bkey.to"
    )
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--manifest-only",
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    rendered = summary.read_text(encoding="utf-8")
    result = json.loads(rendered)
    assert result["status"] == "blocked"
    assert any(MODULE.FIXTURE_PATH_DIAGNOSTIC in error for error in result["errors"])
    assert "private%26%2395%3Bkey" not in rendered
    assert "private&#95;key" not in rendered
    assert "private_key" not in rendered


def test_full_mode_enforces_expected_validator_statuses(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 0
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "ok"
    assert {entry["validator"] for entry in result["entries"]} == {"checked"}
    assert {entry["validator_actual_status"] for entry in result["entries"]} == {
        "accepted",
        "rejected",
    }


def test_full_mode_rejects_validator_status_mismatch(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=False)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any(
        "expected validator status rejected, got accepted" in error
        for error in result["errors"]
    )


def test_full_mode_resolves_repo_relative_validator_binary(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    validator = repo_root / "target" / "debug" / "sorafs-validate"
    validator.parent.mkdir(parents=True, exist_ok=True)
    write_fake_validator(validator, reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            "target/debug/sorafs-validate",
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 0
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "ok"
    assert {entry["validator"] for entry in result["entries"]} == {"checked"}


def test_full_mode_sanitizes_missing_secret_validator_binary(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            "private%26%2395%3Bkey",
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    rendered = summary.read_text(encoding="utf-8")
    result = json.loads(rendered)
    assert result["status"] == "blocked"
    assert any(
        "validator binary not found" in error
        and "<secret-looking-path>" in error
        for error in result["errors"]
    )
    assert "private%26%2395%3Bkey" not in rendered
    assert "private&#95;key" not in rendered
    assert "private_key" not in rendered


def test_validator_execution_error_is_sanitized(monkeypatch, tmp_path: Path) -> None:
    errors: list[str] = []
    result: dict = {}
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    entry = {
        "name": "bad_exec",
        "kind": "billing-statement",
        "expected_status": "accepted",
        "validation_command": (
            "sorafs-validate hedging --kind billing-statement --input "
            "fixtures/sorafs_manifest/hedging/statement.to"
        ),
    }

    def run_raises(*_args, **_kwargs):
        raise OSError("launch denied\nsecret")

    monkeypatch.setattr(MODULE.subprocess, "run", run_raises)

    MODULE.validate_expected_status(
        entry,
        Path("fixtures/sorafs_manifest/hedging/statement.to"),
        str(validator),
        1,
        result,
        errors,
    )

    assert result == {}
    assert errors == ["bad_exec validator execution failed: <non-canonical-error>"]


def test_full_mode_rejects_command_injection_before_validator_exec(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    sentinel = tmp_path / "validator-executed.txt"
    validator = write_sentinel_validator(tmp_path / "sorafs-validate", sentinel)
    payload["fixtures"][0]["validation_command"] += " ; touch /tmp/sorafs-owned"
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    assert not sentinel.exists()
    rendered = summary.read_text(encoding="utf-8")
    result = json.loads(rendered)
    assert result["status"] == "blocked"
    assert any("validation_command must be" in error for error in result["errors"])
    assert "/tmp/sorafs-owned" not in rendered


def test_full_mode_rejects_secret_validation_command_drift_without_echo(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    sentinel = tmp_path / "validator-executed.txt"
    validator = write_sentinel_validator(tmp_path / "sorafs-validate", sentinel)
    payload["fixtures"][0]["validation_command"] += " --private-key runtime-secret"
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    assert not sentinel.exists()
    rendered = summary.read_text(encoding="utf-8")
    result = json.loads(rendered)
    assert result["status"] == "blocked"
    assert any("validation_command must be" in error for error in result["errors"])
    assert "--private-key" not in rendered
    assert "private_key" not in rendered
    assert "runtime-secret" not in rendered


def test_full_mode_rejects_unmanifested_generated_fixtures(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    extra = repo_root / "fixtures" / "sorafs_manifest" / "hedging" / "orphan.to"
    extra.write_bytes(b"orphan")
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any(
        "unmanifested generated hedging fixtures" in error
        for error in result["errors"]
    )
    assert any("orphan.to" in error for error in result["errors"])


def test_full_mode_rejects_secret_unmanifested_generated_fixture_without_echo(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    extra = (
        repo_root
        / "fixtures"
        / "sorafs_manifest"
        / "hedging"
        / "private%26%2395%3Bkey.to"
    )
    extra.write_bytes(b"orphan")
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    rendered = summary.read_text(encoding="utf-8")
    result = json.loads(rendered)
    assert result["status"] == "blocked"
    assert any(
        "unmanifested generated hedging fixtures" in error
        and MODULE.UNSAFE_GENERATED_FIXTURE_PATH_LABEL in error
        for error in result["errors"]
    )
    assert "private%26%2395%3Bkey" not in rendered
    assert "private&#95;key" not in rendered
    assert "private_key" not in rendered


def test_unmanifested_generated_fixture_label_rejects_control_path_without_echo() -> None:
    unsafe_path = "fixtures/sorafs_manifest/hedging/orphan\u202e.to"

    assert MODULE.safe_generated_fixture_path_labels([unsafe_path]) == [
        MODULE.UNSAFE_GENERATED_FIXTURE_PATH_LABEL
    ]


def test_full_mode_rejects_fixture_inventory_scan_errors_without_traceback(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    fixture_root = repo_root / MODULE.HEDGING_FIXTURE_ROOT
    original_rglob = Path.rglob
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    def rglob(path: Path, pattern: str):
        if path == fixture_root:
            raise OSError("fixture inventory scan denied")
        return original_rglob(path, pattern)

    monkeypatch.setattr(Path, "rglob", rglob)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any(
        "failed to scan generated fixture root" in error
        and "fixture inventory scan denied" in error
        for error in result["errors"]
    )


def test_full_mode_rejects_symlinked_generated_fixture_root(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    target_repo = tmp_path / "target-repo"
    write_generated_pairs(target_repo, payload)
    fixture_root = repo_root / MODULE.HEDGING_FIXTURE_ROOT
    fixture_root.parent.mkdir(parents=True, exist_ok=True)
    fixture_root.symlink_to(
        target_repo / MODULE.HEDGING_FIXTURE_ROOT,
        target_is_directory=True,
    )
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any(
        "generated fixture root" in error and "must not be a symlink" in error
        for error in result["errors"]
    )


def test_full_mode_rejects_generated_fixture_root_parent_symlink(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    target_repo = tmp_path / "target-repo"
    write_generated_pairs(target_repo, payload)
    repo_root = tmp_path / "repo-link"
    repo_root.symlink_to(target_repo, target_is_directory=True)
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any(
        "generated fixture root parent" in error and "must not be a symlink" in error
        for error in result["errors"]
    )


def test_full_mode_rejects_symlinked_generated_fixture_inventory_entry(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    target = tmp_path / "external.to"
    target.write_bytes(b"external")
    symlink = repo_root / MODULE.HEDGING_FIXTURE_ROOT / "symlinked.to"
    symlink.symlink_to(target)
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any(
        "generated fixture candidate" in error
        and "symlinked.to" in error
        and "must not be a symlink" in error
        for error in result["errors"]
    )


def test_full_mode_rejects_secret_symlinked_generated_fixture_without_echo(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    target = tmp_path / "external.to"
    target.write_bytes(b"external")
    symlink = (
        repo_root
        / MODULE.HEDGING_FIXTURE_ROOT
        / "private%26%2395%3Bkey.to"
    )
    symlink.symlink_to(target)
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    rendered = summary.read_text(encoding="utf-8")
    result = json.loads(rendered)
    assert result["status"] == "blocked"
    assert any(
        "generated fixture candidate" in error
        and "<secret-looking-path>" in error
        and "must not be a symlink" in error
        for error in result["errors"]
    )
    assert "private%26%2395%3Bkey" not in rendered
    assert "private&#95;key" not in rendered
    assert "private_key" not in rendered


def test_full_mode_rejects_malformed_json_sidecar(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    sidecar_path = repo_root / payload["fixtures"][0]["json_path"]
    sidecar = json.loads(sidecar_path.read_text(encoding="utf-8"))
    del sidecar["version"]
    sidecar_path.write_text(json.dumps(sidecar), encoding="utf-8")
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any(
        "missing required JSON sidecar fields" in error
        for error in result["errors"]
    )


def test_full_mode_rejects_sensitive_extra_json_sidecar_key_without_echo(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    sidecar_path = repo_root / payload["fixtures"][0]["json_path"]
    sidecar = json.loads(sidecar_path.read_text(encoding="utf-8"))
    sidecar["private&#95;key"] = "runtime-secret"
    sidecar_path.write_text(json.dumps(sidecar), encoding="utf-8")
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    rendered = summary.read_text(encoding="utf-8")
    result = json.loads(rendered)
    assert result["status"] == "blocked"
    assert any(
        "unexpected JSON sidecar fields" in error
        and MODULE.SENSITIVE_JSON_FIELD_LABEL in error
        for error in result["errors"]
    )
    assert "private&#95;key" not in rendered
    assert "private_key" not in rendered
    assert "runtime-secret" not in rendered


def test_safe_json_field_label_rejects_unicode_controls_without_echo() -> None:
    assert MODULE.safe_json_field_label("feed_id") == "feed_id"

    for field in (
        "",
        " feed_id",
        "feed_id ",
        "bad\nkey",
        "bad\u200dkey",
        "bad\u202ekey",
        "bad\ue000key",
    ):
        assert MODULE.safe_json_field_label(field) == MODULE.NON_CANONICAL_JSON_FIELD_LABEL


def test_full_mode_rejects_noncanonical_extra_json_sidecar_key_without_echo(
    tmp_path: Path,
    monkeypatch,
) -> None:
    for index, key in enumerate(("bad\nkey", "bad\u200dkey", "bad\u202ekey")):
        payload = base_manifest()
        repo_root = tmp_path / f"repo-{index}"
        write_generated_pairs(repo_root, payload)
        sidecar_path = repo_root / payload["fixtures"][0]["json_path"]
        sidecar = json.loads(sidecar_path.read_text(encoding="utf-8"))
        sidecar[key] = "runtime-secret"
        sidecar_path.write_text(json.dumps(sidecar), encoding="utf-8")
        validator = write_fake_validator(
            tmp_path / f"sorafs-validate-{index}",
            reject_negative=True,
        )
        manifest = write_manifest(tmp_path / f"fixture_manifest-{index}.json", payload)
        summary = tmp_path / f"summary-{index}.json"
        monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

        rc = MODULE.main(
            [
                "--manifest",
                str(manifest),
                "--validator-bin",
                str(validator),
                "--summary-out",
                str(summary),
            ]
        )

        assert rc == 1
        rendered = summary.read_text(encoding="utf-8")
        result = json.loads(rendered)
        assert result["status"] == "blocked"
        assert any(
            "unexpected JSON sidecar fields" in error
            and MODULE.NON_CANONICAL_JSON_FIELD_LABEL in error
            for error in result["errors"]
        )
        assert key not in rendered
        assert key.encode("unicode_escape").decode("ascii") not in rendered
        assert "runtime-secret" not in rendered


def test_full_mode_rejects_non_object_json_sidecar_with_shared_loader(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    sidecar_path = repo_root / payload["fixtures"][0]["json_path"]
    sidecar_path.write_text("[]", encoding="utf-8")
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any(
        "evidence root must be a JSON object" in error
        for error in result["errors"]
    )


def test_full_mode_rejects_oversized_norito_with_shared_byte_reader(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)
    monkeypatch.setattr(MODULE, "MAX_NORITO_BYTES", 4)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any(
        "generated Norito fixture exceeds 4 bytes" in error
        for error in result["errors"]
    )


def test_full_mode_rejects_odd_length_norito_hex_without_traceback(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    sidecar_path = repo_root / payload["fixtures"][0]["json_path"]
    sidecar = json.loads(sidecar_path.read_text(encoding="utf-8"))
    sidecar["norito_bytes_hex"] = "abc"
    sidecar_path.write_text(json.dumps(sidecar), encoding="utf-8")
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any(
        "lowercase even-length hex norito_bytes_hex" in error
        for error in result["errors"]
    )


def test_full_mode_rejects_malformed_nested_json_sidecar(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    statement_fixture = next(
        fixture for fixture in payload["fixtures"] if fixture["name"] == "billing_statement_v1"
    )
    sidecar_path = repo_root / statement_fixture["json_path"]
    sidecar = json.loads(sidecar_path.read_text(encoding="utf-8"))
    del sidecar["lines"][0]["direction"]
    sidecar_path.write_text(json.dumps(sidecar), encoding="utf-8")
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any("lines[0]" in error for error in result["errors"])
    assert any(
        "missing required JSON sidecar fields" in error
        for error in result["errors"]
    )


def test_full_mode_rejects_sensitive_nested_json_sidecar_key_without_echo(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    statement_fixture = next(
        fixture for fixture in payload["fixtures"] if fixture["name"] == "billing_statement_v1"
    )
    sidecar_path = repo_root / statement_fixture["json_path"]
    sidecar = json.loads(sidecar_path.read_text(encoding="utf-8"))
    sidecar["reference_price"]["private%5Fkey"] = "runtime-secret"
    sidecar_path.write_text(json.dumps(sidecar), encoding="utf-8")
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    rendered = summary.read_text(encoding="utf-8")
    result = json.loads(rendered)
    assert result["status"] == "blocked"
    assert any(
        "unexpected JSON sidecar fields" in error
        and MODULE.SENSITIVE_JSON_FIELD_LABEL in error
        for error in result["errors"]
    )
    assert "private%5Fkey" not in rendered
    assert "private_key" not in rendered
    assert "runtime-secret" not in rendered


def test_full_mode_rejects_json_sidecar_version_drift(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    sidecar_path = repo_root / payload["fixtures"][0]["json_path"]
    sidecar = json.loads(sidecar_path.read_text(encoding="utf-8"))
    sidecar["version"] = 2
    sidecar_path.write_text(json.dumps(sidecar), encoding="utf-8")
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any("version must be 1" in error for error in result["errors"])


def test_full_mode_rejects_sensitive_duplicate_nested_id_without_echo(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    statement_fixture = next(
        fixture for fixture in payload["fixtures"] if fixture["name"] == "billing_statement_v1"
    )
    sidecar_path = repo_root / statement_fixture["json_path"]
    sidecar = json.loads(sidecar_path.read_text(encoding="utf-8"))
    sidecar["lines"][0]["line_id_hex"] = "private_key"
    duplicate = dict(sidecar["lines"][0])
    sidecar["lines"].append(duplicate)
    sidecar_path.write_text(json.dumps(sidecar), encoding="utf-8")
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    rendered = summary.read_text(encoding="utf-8")
    result = json.loads(rendered)
    assert result["status"] == "blocked"
    assert any("duplicate line_id_hex values" in error for error in result["errors"])
    assert "private_key" not in rendered
    assert "private-key" not in rendered


def test_full_mode_rejects_statement_sidecar_value_invariants(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    statement_fixture = next(
        fixture for fixture in payload["fixtures"] if fixture["name"] == "billing_statement_v1"
    )
    sidecar_path = repo_root / statement_fixture["json_path"]
    sidecar = json.loads(sidecar_path.read_text(encoding="utf-8"))
    sidecar["account_id_hex"] = "626164"
    sidecar["due_at_unix"] = sidecar["period_end_unix"] - 1
    sidecar["lines"].append(dict(sidecar["lines"][0]))
    sidecar_path.write_text(json.dumps(sidecar), encoding="utf-8")
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any(
        "account_id_hex must decode to account_id" in error
        for error in result["errors"]
    )
    assert any("due_at_unix must be at or after" in error for error in result["errors"])
    assert any("duplicate line_id_hex" in error for error in result["errors"])


def test_full_mode_rejects_sidecar_numeric_policy_bounds(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    feed_path = repo_root / payload["fixtures"][0]["json_path"]
    feed_sidecar = json.loads(feed_path.read_text(encoding="utf-8"))
    feed_sidecar["weight_bps"] = 10_001
    feed_path.write_text(json.dumps(feed_sidecar), encoding="utf-8")
    line_fixture = next(
        fixture for fixture in payload["fixtures"] if fixture["name"] == "billing_line_storage_v1"
    )
    line_path = repo_root / line_fixture["json_path"]
    line_sidecar = json.loads(line_path.read_text(encoding="utf-8"))
    line_sidecar["xor_amount"] = "0"
    line_sidecar["usd_amount"] = f"{(1 << 511)}"
    line_sidecar["quantity_units"] = "01"
    line_path.write_text(json.dumps(line_sidecar), encoding="utf-8")
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any(
        "weight_bps must be an integer in 1..=10000" in error
        for error in result["errors"]
    )
    assert any(
        "xor_amount must be a positive canonical exact decimal string with scale at most 9"
        in error
        for error in result["errors"]
    )
    assert any(
        "usd_amount must be a positive canonical exact decimal string with scale at most 28"
        in error
        for error in result["errors"]
    )
    assert any(
        "quantity_units must be an unsigned u128 decimal string" in error
        for error in result["errors"]
    )
