"""Tests for scripts/check_sorafs_hedging_fixture_manifest.py."""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path


MODULE_PATH = Path(__file__).resolve().parents[1] / "check_sorafs_hedging_fixture_manifest.py"
SPEC = importlib.util.spec_from_file_location("check_sorafs_hedging_fixture_manifest", MODULE_PATH)
MODULE = importlib.util.module_from_spec(SPEC)
assert SPEC and SPEC.loader  # pragma: no cover - defensive
sys.modules[SPEC.name] = MODULE
SPEC.loader.exec_module(MODULE)

REPO_ROOT = Path(__file__).resolve().parents[2]
SOURCE_MANIFEST = REPO_ROOT / "fixtures" / "sorafs_manifest" / "hedging" / "fixture_manifest.json"


def write_manifest(path: Path, payload: dict) -> Path:
    """Write a fixture manifest for checker tests."""

    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return path


def base_manifest() -> dict:
    """Return the checked-in fixture manifest payload."""

    return json.loads(SOURCE_MANIFEST.read_text(encoding="utf-8"))


def write_generated_pairs(root: Path, payload: dict) -> None:
    """Write minimal generated byte/JSON pairs under a temporary repo root."""

    for fixture in payload["fixtures"]:
        norito_path = root / fixture["norito_path"]
        json_path = root / fixture["json_path"]
        norito_path.parent.mkdir(parents=True, exist_ok=True)
        json_path.parent.mkdir(parents=True, exist_ok=True)
        norito_bytes = fixture["name"].encode("utf-8")
        norito_path.write_bytes(norito_bytes)
        sidecar = generated_sidecar(fixture)
        sidecar["norito_bytes_hex"] = norito_bytes.hex()
        json_path.write_text(json.dumps(sidecar), encoding="utf-8")


def generated_sidecar(fixture: dict) -> dict:
    """Return a minimal valid generated sidecar for a manifest fixture."""

    if fixture["kind"] == "price-feed":
        return generated_price_feed_sidecar(fixture["name"])
    if fixture["kind"] == "reference-price-decision":
        return generated_reference_price_sidecar(fixture["expected_status"] == "rejected")
    if fixture["kind"] == "billing-line-item":
        return generated_billing_line_sidecar(fixture["name"])
    if fixture["kind"] == "billing-statement":
        return {
            "account_id": "provider-a",
            "account_id_hex": "70726f76696465722d61",
            "due_at_unix": 1_700_691_200,
            "lines": [generated_billing_line_sidecar("billing_line_storage_v1")],
            "net_due_usd_micros": "1000",
            "net_due_xor_micro": "1000000",
            "period_end_unix": 1_700_604_800,
            "period_start_unix": 1_700_000_000,
            "previous_statement_id_hex": "12" * 32,
            "reference_price": generated_reference_price_sidecar(
                fixture["expected_status"] == "rejected"
            ),
            "statement_id_hex": "34" * 32,
            "total_credit_usd_micros": "0",
            "total_credit_xor_micro": "0",
            "total_debit_usd_micros": "1000",
            "total_debit_xor_micro": "1000000",
            "version": 1,
        }
    raise AssertionError(f"unexpected fixture kind: {fixture['kind']}")


def generated_price_feed_sidecar(name: str) -> dict:
    """Return a generated price-feed JSON object without Norito bytes."""

    return {
        "evidence_digest_hex": "ab" * 32,
        "feed_id": name,
        "observed_at_unix": 1_700_604_700,
        "source": "test-source",
        "status": "degraded" if "secondary" in name else "ok",
        "version": 1,
        "weight_bps": 5_000,
        "xor_usd_micros": 2_000_000,
    }


def generated_reference_price_sidecar(rejected: bool) -> dict:
    """Return a generated reference-price JSON object without Norito bytes."""

    return {
        "decision_id_hex": "cd" * 32,
        "degradation_reasons": ["fixture"],
        "degraded": rejected,
        "effective_at_unix": 1_700_604_800,
        "feeds": [
            generated_price_feed_sidecar("price_feed_primary_v1"),
            generated_price_feed_sidecar("price_feed_secondary_v1"),
        ],
        "max_divergence_bps": 500,
        "max_feed_age_secs": 300,
        "version": 1,
        "xor_usd_micros": 2_000_000,
    }


def generated_billing_line_sidecar(name: str) -> dict:
    """Return a generated billing-line JSON object without Norito bytes."""

    return {
        "direction": "credit" if "credit" in name else "debit",
        "kind": "incentive_credit" if "credit" in name else "storage",
        "line_id_hex": "ef" * 32,
        "note": None,
        "quantity_units": "1",
        "source_id": name,
        "usd_micros": "1000",
        "version": 1,
        "xor_amount_micro": "1000000",
    }


def write_fake_validator(path: Path, reject_negative: bool) -> Path:
    """Write a fake sorafs-validate executable for checker tests."""

    path.write_text(
        "\n".join(
            [
                "#!/usr/bin/env python3",
                "import sys",
                "joined = ' '.join(sys.argv[1:])",
                f"if {reject_negative!r} and '/negative/' in joined:",
                "    raise SystemExit(2)",
                "raise SystemExit(0)",
                "",
            ]
        ),
        encoding="utf-8",
    )
    path.chmod(0o755)
    return path


def write_sentinel_validator(path: Path, sentinel: Path) -> Path:
    """Write a fake validator that records execution before succeeding."""

    path.write_text(
        "\n".join(
            [
                "#!/usr/bin/env python3",
                "from pathlib import Path",
                f"Path({str(sentinel)!r}).write_text('executed', encoding='utf-8')",
                "raise SystemExit(0)",
                "",
            ]
        ),
        encoding="utf-8",
    )
    path.chmod(0o755)
    return path


def test_manifest_only_accepts_checked_in_inventory(tmp_path: Path) -> None:
    manifest = write_manifest(tmp_path / "fixture_manifest.json", base_manifest())
    summary = tmp_path / "summary.json"

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--manifest-only",
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 0
    payload = json.loads(summary.read_text(encoding="utf-8"))
    assert payload["status"] == "ok"
    assert payload["manifest_only"] is True
    assert payload["entry_count"] == 10
    assert {entry["generated"] for entry in payload["entries"]} == {"not_checked"}


def test_summary_out_same_as_manifest_fails_before_write(
    tmp_path: Path,
    capsys,
) -> None:
    manifest = write_manifest(tmp_path / "fixture_manifest.json", base_manifest())
    original = manifest.read_text(encoding="utf-8")
    summary = tmp_path / "nested" / ".." / "fixture_manifest.json"

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--manifest-only",
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 2
    assert manifest.read_text(encoding="utf-8") == original
    captured = capsys.readouterr()
    assert "must not be the same path as --manifest" in captured.err
    assert captured.out == ""


def test_summary_out_directory_fails_before_write(
    tmp_path: Path,
    capsys,
) -> None:
    manifest = write_manifest(tmp_path / "fixture_manifest.json", base_manifest())
    summary = tmp_path / "summary-dir"
    summary.mkdir()

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--manifest-only",
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 2
    captured = capsys.readouterr()
    assert "must not be a directory" in captured.err
    assert captured.out == ""


def test_summary_out_symlink_fails_before_manifest_read(
    tmp_path: Path,
    capsys,
    monkeypatch,
) -> None:
    manifest = write_manifest(tmp_path / "fixture_manifest.json", base_manifest())
    target = tmp_path / "actual-summary.json"
    target.write_text("old", encoding="utf-8")
    summary = tmp_path / "summary.json"
    summary.symlink_to(target)
    original_open = Path.open

    def open_path(path: Path, *args, **kwargs):
        if path == manifest:
            raise AssertionError("manifest should not be read after summary preflight fails")
        return original_open(path, *args, **kwargs)

    monkeypatch.setattr(Path, "open", open_path)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--manifest-only",
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 2
    assert target.read_text(encoding="utf-8") == "old"
    captured = capsys.readouterr()
    assert "must not be a symlink" in captured.err
    assert captured.out == ""


def test_summary_out_parent_chain_symlink_fails_before_write(
    tmp_path: Path,
    capsys,
) -> None:
    manifest = write_manifest(tmp_path / "fixture_manifest.json", base_manifest())
    target_parent = tmp_path / "actual-parent"
    target_parent.mkdir()
    parent = tmp_path / "summary-parent"
    parent.symlink_to(target_parent, target_is_directory=True)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--manifest-only",
            "--summary-out",
            str(parent / "nested" / "summary.json"),
        ]
    )

    assert rc == 2
    assert not (target_parent / "nested").exists()
    captured = capsys.readouterr()
    assert "must not be a symlink" in captured.err
    assert captured.out == ""


def test_manifest_read_error_writes_blocked_summary_without_traceback(
    tmp_path: Path,
    monkeypatch,
) -> None:
    manifest = write_manifest(tmp_path / "fixture_manifest.json", base_manifest())
    summary = tmp_path / "summary.json"
    original_open = Path.open

    def open_path(path: Path, *args, **kwargs):
        if path == manifest:
            raise OSError("manifest read denied")
        return original_open(path, *args, **kwargs)

    monkeypatch.setattr(Path, "open", open_path)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--manifest-only",
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert result["manifest_sha256"] is None
    assert any(
        "failed to read manifest" in error and "manifest read denied" in error
        for error in result["errors"]
    )


def test_manifest_rejects_non_standard_json_constants(
    tmp_path: Path,
) -> None:
    manifest = tmp_path / "fixture_manifest.json"
    manifest.write_text('{"schema_version": NaN}', encoding="utf-8")
    summary = tmp_path / "summary.json"

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--manifest-only",
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert result["manifest_sha256"] is None
    assert any("non-standard JSON constant `NaN`" in error for error in result["errors"])


def test_default_mode_fails_closed_when_generated_bytes_are_missing(
    tmp_path: Path,
    monkeypatch,
) -> None:
    manifest = write_manifest(tmp_path / "fixture_manifest.json", base_manifest())
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", tmp_path / "repo")

    rc = MODULE.main(["--manifest", str(manifest), "--summary-out", str(summary)])

    assert rc == 1
    payload = json.loads(summary.read_text(encoding="utf-8"))
    assert payload["status"] == "blocked"
    assert payload["manifest_only"] is False
    assert any("missing generated Norito fixture" in error for error in payload["errors"])


def test_full_mode_rejects_unreadable_generated_fixture_without_traceback(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    target = repo_root / payload["fixtures"][0]["norito_path"]
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    original_read_bytes = Path.read_bytes
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    def read_bytes(path: Path) -> bytes:
        if path == target:
            raise OSError("generated fixture read denied")
        return original_read_bytes(path)

    monkeypatch.setattr(Path, "read_bytes", read_bytes)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any(
        "failed to read generated Norito fixture" in error
        and "generated fixture read denied" in error
        for error in result["errors"]
    )


def test_manifest_only_rejects_drifted_validation_command(tmp_path: Path) -> None:
    payload = base_manifest()
    payload["fixtures"][0]["validation_command"] = "sorafs-validate hedging --statement wrong.to"
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--manifest-only",
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any("validation_command must be" in error for error in result["errors"])


def test_manifest_only_rejects_negative_case_drift(tmp_path: Path) -> None:
    payload = base_manifest()
    fixture = next(
        item
        for item in payload["fixtures"]
        if item["name"] == "stale_reference_price_decision_v1"
    )
    fixture["negative_case"] = "totals_mismatch"
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--manifest-only",
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any(
        "negative_case must be `stale_feed`" in error
        for error in result["errors"]
    )


def test_manifest_only_rejects_rejected_fixtures_outside_negative_dir(
    tmp_path: Path,
) -> None:
    payload = base_manifest()
    fixture = next(
        item
        for item in payload["fixtures"]
        if item["name"] == "stale_reference_price_decision_v1"
    )
    fixture["norito_path"] = (
        "fixtures/sorafs_manifest/hedging/stale_reference_price_decision_v1.to"
    )
    fixture["json_path"] = (
        "fixtures/sorafs_manifest/hedging/stale_reference_price_decision_v1.json"
    )
    fixture["validation_command"] = (
        "sorafs-validate hedging --decision "
        "fixtures/sorafs_manifest/hedging/stale_reference_price_decision_v1.to"
    )
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--manifest-only",
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any(
        "rejected fixture paths must both stay under negative/" in error
        for error in result["errors"]
    )


def test_full_mode_rejects_missing_fixture_paths_without_traceback(
    tmp_path: Path,
) -> None:
    payload = base_manifest()
    del payload["fixtures"][0]["norito_path"]
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"

    rc = MODULE.main(["--manifest", str(manifest), "--summary-out", str(summary)])

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert result["entries"][0]["generated"] == "not_checked"
    assert any("fixtures[0].norito_path" in error for error in result["errors"])


def test_full_mode_rejects_absolute_fixture_paths_before_read(
    tmp_path: Path,
) -> None:
    payload = base_manifest()
    payload["fixtures"][0]["norito_path"] = "/tmp/sorafs-outside.to"
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"

    rc = MODULE.main(["--manifest", str(manifest), "--summary-out", str(summary)])

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert result["entries"][0]["generated"] == "not_checked"
    assert any("repository-relative path" in error for error in result["errors"])
    assert not any("/tmp/sorafs-outside.to" in error for error in result["errors"])


def test_full_mode_enforces_expected_validator_statuses(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 0
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "ok"
    assert {entry["validator"] for entry in result["entries"]} == {"checked"}
    assert {entry["validator_actual_status"] for entry in result["entries"]} == {
        "accepted",
        "rejected",
    }


def test_full_mode_rejects_validator_status_mismatch(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=False)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any(
        "expected validator status rejected, got accepted" in error
        for error in result["errors"]
    )


def test_full_mode_resolves_repo_relative_validator_binary(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    validator = repo_root / "target" / "debug" / "sorafs-validate"
    validator.parent.mkdir(parents=True, exist_ok=True)
    write_fake_validator(validator, reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            "target/debug/sorafs-validate",
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 0
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "ok"
    assert {entry["validator"] for entry in result["entries"]} == {"checked"}


def test_full_mode_rejects_command_injection_before_validator_exec(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    sentinel = tmp_path / "validator-executed.txt"
    validator = write_sentinel_validator(tmp_path / "sorafs-validate", sentinel)
    payload["fixtures"][0]["validation_command"] += " ; touch /tmp/sorafs-owned"
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    assert not sentinel.exists()
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any("validation_command must be" in error for error in result["errors"])


def test_full_mode_rejects_unmanifested_generated_fixtures(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    extra = repo_root / "fixtures" / "sorafs_manifest" / "hedging" / "orphan.to"
    extra.write_bytes(b"orphan")
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any(
        "unmanifested generated hedging fixtures" in error
        for error in result["errors"]
    )
    assert any("orphan.to" in error for error in result["errors"])


def test_full_mode_rejects_fixture_inventory_scan_errors_without_traceback(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    fixture_root = repo_root / MODULE.HEDGING_FIXTURE_ROOT
    original_rglob = Path.rglob
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    def rglob(path: Path, pattern: str):
        if path == fixture_root:
            raise OSError("fixture inventory scan denied")
        return original_rglob(path, pattern)

    monkeypatch.setattr(Path, "rglob", rglob)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any(
        "failed to scan generated fixture root" in error
        and "fixture inventory scan denied" in error
        for error in result["errors"]
    )


def test_full_mode_rejects_malformed_json_sidecar(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    sidecar_path = repo_root / payload["fixtures"][0]["json_path"]
    sidecar = json.loads(sidecar_path.read_text(encoding="utf-8"))
    del sidecar["version"]
    sidecar_path.write_text(json.dumps(sidecar), encoding="utf-8")
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any(
        "missing required JSON sidecar fields" in error
        for error in result["errors"]
    )


def test_full_mode_rejects_non_object_json_sidecar_with_shared_loader(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    sidecar_path = repo_root / payload["fixtures"][0]["json_path"]
    sidecar_path.write_text("[]", encoding="utf-8")
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any(
        "evidence root must be a JSON object" in error
        for error in result["errors"]
    )


def test_full_mode_rejects_odd_length_norito_hex_without_traceback(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    sidecar_path = repo_root / payload["fixtures"][0]["json_path"]
    sidecar = json.loads(sidecar_path.read_text(encoding="utf-8"))
    sidecar["norito_bytes_hex"] = "abc"
    sidecar_path.write_text(json.dumps(sidecar), encoding="utf-8")
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any(
        "lowercase even-length hex norito_bytes_hex" in error
        for error in result["errors"]
    )


def test_full_mode_rejects_malformed_nested_json_sidecar(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    statement_fixture = next(
        fixture for fixture in payload["fixtures"] if fixture["name"] == "billing_statement_v1"
    )
    sidecar_path = repo_root / statement_fixture["json_path"]
    sidecar = json.loads(sidecar_path.read_text(encoding="utf-8"))
    del sidecar["lines"][0]["direction"]
    sidecar_path.write_text(json.dumps(sidecar), encoding="utf-8")
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any("lines[0]" in error for error in result["errors"])
    assert any(
        "missing required JSON sidecar fields" in error
        for error in result["errors"]
    )


def test_full_mode_rejects_json_sidecar_version_drift(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    sidecar_path = repo_root / payload["fixtures"][0]["json_path"]
    sidecar = json.loads(sidecar_path.read_text(encoding="utf-8"))
    sidecar["version"] = 2
    sidecar_path.write_text(json.dumps(sidecar), encoding="utf-8")
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any("version must be 1" in error for error in result["errors"])


def test_full_mode_rejects_statement_sidecar_value_invariants(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    statement_fixture = next(
        fixture for fixture in payload["fixtures"] if fixture["name"] == "billing_statement_v1"
    )
    sidecar_path = repo_root / statement_fixture["json_path"]
    sidecar = json.loads(sidecar_path.read_text(encoding="utf-8"))
    sidecar["account_id_hex"] = "626164"
    sidecar["due_at_unix"] = sidecar["period_end_unix"] - 1
    sidecar["lines"].append(dict(sidecar["lines"][0]))
    sidecar_path.write_text(json.dumps(sidecar), encoding="utf-8")
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any(
        "account_id_hex must decode to account_id" in error
        for error in result["errors"]
    )
    assert any("due_at_unix must be at or after" in error for error in result["errors"])
    assert any("duplicate line_id_hex" in error for error in result["errors"])


def test_full_mode_rejects_sidecar_numeric_policy_bounds(
    tmp_path: Path,
    monkeypatch,
) -> None:
    payload = base_manifest()
    repo_root = tmp_path / "repo"
    write_generated_pairs(repo_root, payload)
    feed_path = repo_root / payload["fixtures"][0]["json_path"]
    feed_sidecar = json.loads(feed_path.read_text(encoding="utf-8"))
    feed_sidecar["weight_bps"] = 10_001
    feed_path.write_text(json.dumps(feed_sidecar), encoding="utf-8")
    line_fixture = next(
        fixture for fixture in payload["fixtures"] if fixture["name"] == "billing_line_storage_v1"
    )
    line_path = repo_root / line_fixture["json_path"]
    line_sidecar = json.loads(line_path.read_text(encoding="utf-8"))
    line_sidecar["xor_amount_micro"] = "0"
    line_sidecar["usd_micros"] = "340282366920938463463374607431768211456"
    line_sidecar["quantity_units"] = "01"
    line_path.write_text(json.dumps(line_sidecar), encoding="utf-8")
    validator = write_fake_validator(tmp_path / "sorafs-validate", reject_negative=True)
    manifest = write_manifest(tmp_path / "fixture_manifest.json", payload)
    summary = tmp_path / "summary.json"
    monkeypatch.setattr(MODULE, "REPO_ROOT", repo_root)

    rc = MODULE.main(
        [
            "--manifest",
            str(manifest),
            "--validator-bin",
            str(validator),
            "--summary-out",
            str(summary),
        ]
    )

    assert rc == 1
    result = json.loads(summary.read_text(encoding="utf-8"))
    assert result["status"] == "blocked"
    assert any(
        "weight_bps must be an integer in 1..=10000" in error
        for error in result["errors"]
    )
    assert any(
        "xor_amount_micro must be a positive unsigned u128 decimal string" in error
        for error in result["errors"]
    )
    assert any(
        "usd_micros must be a positive unsigned u128 decimal string" in error
        for error in result["errors"]
    )
    assert any(
        "quantity_units must be an unsigned u128 decimal string" in error
        for error in result["errors"]
    )
