"""Tests for scripts/check_generated_artifacts.py."""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest


ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "scripts" / "check_generated_artifacts.py"


def _write_manifest(repo: Path, *, extra: str = "") -> None:
    (repo / "generated-files.toml").write_text(
        """
schema_version = 1

[policy]
forbidden_tracked_globs = [
  "dist/**",
  "**/__pycache__/**",
]
allowed_tracked_paths = ["dist/.gitkeep"]
generated_source_extensions = [".rs", ".py"]

[[generated]]
name = "demo"
kind = "file"
outputs = ["src/generated.rs"]
generator = "python3 scripts/generate.py"
generator_sources = ["scripts/generate.py"]
inputs = ["spec/*.toml"]
check = "python3 scripts/generate.py --check"
""".lstrip()
        + extra,
        encoding="utf-8",
    )


def _init_repo(tmp_path: Path) -> Path:
    repo = tmp_path / "repo"
    (repo / "src").mkdir(parents=True)
    (repo / "scripts").mkdir()
    (repo / "spec").mkdir()
    shutil.copy2(SCRIPT, repo / "scripts" / "check_generated_artifacts.py")
    (repo / "scripts" / "generate.py").write_text(
        '"""Deterministic test generator."""\n',
        encoding="utf-8",
    )
    (repo / "spec" / "demo.toml").write_text("version = 1\n", encoding="utf-8")
    (repo / "src" / "generated.rs").write_text(
        "// @generated\npub const VALUE: u8 = 1;\n",
        encoding="utf-8",
    )
    _write_manifest(repo)
    subprocess.run(["git", "init", "-q"], cwd=repo, check=True)
    subprocess.run(["git", "add", "."], cwd=repo, check=True)
    return repo


def _run(repo: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [
            "python3",
            str(repo / "scripts" / "check_generated_artifacts.py"),
            "--root",
            str(repo),
        ],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )


def test_valid_manifest_and_repository_pass(tmp_path: Path) -> None:
    repo = _init_repo(tmp_path)

    result = _run(repo)

    assert result.returncode == 0
    assert "1 outputs" in result.stdout


def test_single_star_input_does_not_cross_directory_boundary(tmp_path: Path) -> None:
    repo = _init_repo(tmp_path)
    subprocess.run(["git", "rm", "-f", "spec/demo.toml"], cwd=repo, check=True)
    nested = repo / "spec" / "nested" / "demo.toml"
    nested.parent.mkdir(parents=True)
    nested.write_text("version = 1\n", encoding="utf-8")
    subprocess.run(["git", "add", str(nested)], cwd=repo, check=True)

    result = _run(repo)

    assert result.returncode == 1
    assert "inputs pattern matches no tracked regular files" in result.stderr


@pytest.mark.parametrize("nested", [False, True])
def test_globstar_input_matches_zero_or_more_directories(
    tmp_path: Path, nested: bool
) -> None:
    repo = _init_repo(tmp_path)
    manifest = repo / "generated-files.toml"
    manifest.write_text(
        manifest.read_text(encoding="utf-8").replace(
            'inputs = ["spec/*.toml"]',
            'inputs = ["spec/**/*.toml"]',
        ),
        encoding="utf-8",
    )
    if nested:
        subprocess.run(["git", "rm", "-f", "spec/demo.toml"], cwd=repo, check=True)
        fixture = repo / "spec" / "nested" / "demo.toml"
        fixture.parent.mkdir(parents=True)
        fixture.write_text("version = 1\n", encoding="utf-8")
        subprocess.run(["git", "add", str(fixture)], cwd=repo, check=True)
    subprocess.run(["git", "add", str(manifest)], cwd=repo, check=True)

    result = _run(repo)

    assert result.returncode == 0


def test_forbidden_tracked_build_artifact_fails(tmp_path: Path) -> None:
    repo = _init_repo(tmp_path)
    path = repo / "dist" / "bundle.js"
    path.parent.mkdir()
    path.write_text("generated package output\n", encoding="utf-8")
    subprocess.run(["git", "add", str(path)], cwd=repo, check=True)

    result = _run(repo)

    assert result.returncode == 1
    assert "forbidden generated/build artifacts" in result.stderr
    assert "dist/bundle.js" in result.stderr


def test_allowed_directory_marker_passes(tmp_path: Path) -> None:
    repo = _init_repo(tmp_path)
    path = repo / "dist" / ".gitkeep"
    path.parent.mkdir()
    path.write_text("", encoding="utf-8")
    subprocess.run(["git", "add", "-f", str(path)], cwd=repo, check=True)

    result = _run(repo)

    assert result.returncode == 0


def test_unregistered_generated_header_fails(tmp_path: Path) -> None:
    repo = _init_repo(tmp_path)
    path = repo / "src" / "orphan.rs"
    path.write_text("// Code generated by demo; DO NOT EDIT.\n", encoding="utf-8")
    subprocess.run(["git", "add", str(path)], cwd=repo, check=True)

    result = _run(repo)

    assert result.returncode == 1
    assert "generated source has no generated-files.toml owner" in result.stderr
    assert "src/orphan.rs" in result.stderr


def test_duplicate_output_ownership_fails(tmp_path: Path) -> None:
    repo = _init_repo(tmp_path)
    with (repo / "generated-files.toml").open("a", encoding="utf-8") as manifest:
        manifest.write(
            """

[[generated]]
name = "duplicate"
kind = "regions"
outputs = ["src/generated.rs"]
generator = "python3 scripts/generate.py"
generator_sources = ["scripts/generate.py"]
inputs = ["spec/demo.toml"]
check = "python3 scripts/generate.py --check"
"""
        )
    subprocess.run(["git", "add", "generated-files.toml"], cwd=repo, check=True)

    result = _run(repo)

    assert result.returncode == 1
    assert "owned by both demo and duplicate" in result.stderr


def test_missing_generator_source_fails(tmp_path: Path) -> None:
    repo = _init_repo(tmp_path)
    manifest = repo / "generated-files.toml"
    manifest.write_text(
        manifest.read_text(encoding="utf-8").replace(
            'generator_sources = ["scripts/generate.py"]',
            'generator_sources = ["scripts/missing.py"]',
        ),
        encoding="utf-8",
    )
    subprocess.run(["git", "add", "generated-files.toml"], cwd=repo, check=True)

    result = _run(repo)

    assert result.returncode == 1
    assert "generator_sources is not a tracked regular file" in result.stderr


def test_tracked_elf_core_dump_fails(tmp_path: Path) -> None:
    repo = _init_repo(tmp_path)
    path = repo / "crates" / "demo" / "core"
    path.parent.mkdir(parents=True)
    path.write_bytes(b"\x7fELF" + b"\0" * 32)
    subprocess.run(["git", "add", str(path)], cwd=repo, check=True)

    result = _run(repo)

    assert result.returncode == 1
    assert "executable core dumps are tracked" in result.stderr
    assert "crates/demo/core" in result.stderr


@pytest.mark.parametrize("invalid", ["../outside.rs", "/absolute.rs", "src//bad.rs"])
def test_non_normalized_output_path_fails(tmp_path: Path, invalid: str) -> None:
    repo = _init_repo(tmp_path)
    manifest = repo / "generated-files.toml"
    manifest.write_text(
        manifest.read_text(encoding="utf-8").replace("src/generated.rs", invalid),
        encoding="utf-8",
    )
    subprocess.run(["git", "add", "generated-files.toml"], cwd=repo, check=True)

    result = _run(repo)

    assert result.returncode == 1
    assert "normalized repository-relative path" in result.stderr
