# Source-seal regression fixture shared by the mobile SDK artifact test.

test_build_source_seal() {
  local root="$TMP_DIR/source-seal"
  local cargo_target="$TMP_DIR/source-seal-cargo-target"
  local bridge_build="$TMP_DIR/source-seal-bridge-build"
  local bridge_output="$TMP_DIR/source-seal-bridge-output"
  local exact_rustc exact_rustdoc
  mkdir -p "$root/scripts" "$root/IrohaSwift" \
    "$root/crates/connect_norito_bridge/src" \
    "$root/crates/unrelated/src" "$cargo_target" "$bridge_build" "$bridge_output"
  cp "$SCRIPT_DIR/build_norito_xcframework.sh" \
    "$root/scripts/build_norito_xcframework.sh"
  cp "$SCRIPT_DIR/exec_with_file_lock.py" \
    "$root/scripts/exec_with_file_lock.py"
  cp "$SCRIPT_DIR/norito_bridge_source_seal.py" \
    "$root/scripts/norito_bridge_source_seal.py"
  cp "$SCRIPT_DIR/run_mobile_hermetic_command.py" \
    "$root/scripts/run_mobile_hermetic_command.py"
  cp "$SCRIPT_DIR/validate_norito_bridge_xcframework.py" \
    "$root/scripts/validate_norito_bridge_xcframework.py"
  cp "$SCRIPT_DIR/../IrohaSwift/Package.resolved" \
    "$root/IrohaSwift/Package.resolved"
  printf '[toolchain]\nchannel = "1.93.1"\n' >"$root/rust-toolchain.toml"
  printf '[workspace]\nmembers = ["crates/connect_norito_bridge", "crates/unrelated"]\nresolver = "2"\n' \
    >"$root/Cargo.toml"
  printf '[package]\nname = "connect_norito_bridge"\nversion = "0.1.0"\nedition = "2024"\n\n[features]\nprivacy-production-enabled = []\n' \
    >"$root/crates/connect_norito_bridge/Cargo.toml"
  printf 'pub fn bridge_fixture() {}\n' \
    >"$root/crates/connect_norito_bridge/src/lib.rs"
  printf '[package]\nname = "unrelated"\nversion = "0.1.0"\nedition = "2024"\n' \
    >"$root/crates/unrelated/Cargo.toml"
  printf 'pub fn unrelated_fixture() {}\n' >"$root/crates/unrelated/src/lib.rs"
  printf '# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = "connect_norito_bridge"\nversion = "0.1.0"\n\n[[package]]\nname = "unrelated"\nversion = "0.1.0"\n' \
    >"$root/Cargo.lock"
  mkdir -p "$root/private-lock"
  cp "$root/Cargo.lock" "$root/private-lock/Cargo.lock"
  git -C "$root" init -q
  git -C "$root" add .
  git -C "$root" -c user.name=test -c user.email=test@example.invalid \
    commit -qm source-seal-fixture

  exact_rustc="$(rustup which --toolchain 1.93.1 rustc)"
  exact_rustdoc="$(rustup which --toolchain 1.93.1 rustdoc)"
  export CARGO_BUILD_JOBS=1
  export CARGO_INCREMENTAL=0
  export CARGO_NET_OFFLINE=true
  export CARGO_TARGET_DIR="$cargo_target"
  export NORITO_BRIDGE_BUILD_DIR="$bridge_build"
  export NORITO_BRIDGE_OUT_DIR="$bridge_output"
  export RUSTC="$exact_rustc"
  export RUSTC_BOOTSTRAP=1
  export RUSTDOC="$exact_rustdoc"

  NORITO_BRIDGE_SOURCE_SEAL_TEST_ONLY=1 \
    bash "$root/scripts/build_norito_xcframework.sh"

  local invalid_lock_output
  if invalid_lock_output="$(NORITO_BRIDGE_SOURCE_SEAL_TEST_ONLY=1 \
      bash "$root/scripts/build_norito_xcframework.sh" \
        --lockfile-path "$root/private-lock/Cargo.lock" 2>&1)"; then
    fail "expected Apple builder to reject the retired alternate-lock interface"
  fi
  case "$invalid_lock_output" in
    *"Unknown argument: --lockfile-path"*) ;;
    *)
      printf '%s\n' "$invalid_lock_output" >&2
      fail "retired alternate-lock failure was not explicit"
      ;;
  esac

  local hostile_bin="$root/hostile-bin"
  local hostile_marker="$root/hostile-tool-invoked"
  mkdir -p "$hostile_bin"
  local tool_name
  for tool_name in python3 git rustup cargo rustc nm; do
    printf '#!/bin/sh\nprintf "%%s\\n" "$0" >>"%s"\nexit 97\n' "$hostile_marker" \
      >"$hostile_bin/$tool_name"
    chmod 0700 "$hostile_bin/$tool_name"
  done
  PATH="$hostile_bin" \
    HOME="$root/forged-home" \
    RUSTFLAGS="-C link-arg=forged" \
    CARGO_ENCODED_RUSTFLAGS="forged" \
    RUSTC_WRAPPER="$hostile_bin/rustc-wrapper" \
    RUSTC_WORKSPACE_WRAPPER="$hostile_bin/workspace-wrapper" \
    GIT_DIR="$root/forged-git-dir" \
    GIT_WORK_TREE="$root/forged-work-tree" \
    GIT_INDEX_FILE="$root/forged-index" \
    GIT_CONFIG_GLOBAL="$root/forged-git-config" \
    NORITO_BRIDGE_SOURCE_SEAL_TEST_ONLY=1 \
    /bin/bash "$root/scripts/build_norito_xcframework.sh"
  [[ ! -e "$hostile_marker" ]] \
    || fail "Apple builder trusted a hostile ambient PATH tool"

  # A workspace package outside the bridge dependency closure must not make
  # otherwise identical native slices appear mixed-source.
  NORITO_BRIDGE_SOURCE_SEAL_TEST_ONLY=1 \
    NORITO_BRIDGE_SOURCE_SEAL_TEST_MUTATE=crates/unrelated/src/lib.rs \
    bash "$root/scripts/build_norito_xcframework.sh"

  local output
  if output="$(NORITO_BRIDGE_SOURCE_SEAL_TEST_ONLY=1 \
      NORITO_BRIDGE_SOURCE_SEAL_TEST_MUTATE=Cargo.toml \
      bash "$root/scripts/build_norito_xcframework.sh" 2>&1)"; then
    printf '%s\n' "$output" >&2
    fail "expected source seal to reject an in-build source mutation"
  fi
  case "$output" in
    *"refusing mixed-source Apple slices"*) ;;
    *)
      printf '%s\n' "$output" >&2
      fail "source seal mutation failure was not explicit"
      ;;
  esac
}
