//! Immutable compiler-captured identities for this source owner’s existing codecs.

const CASES: &[crate::captured_schema_tests::Case] = &[
    crate::captured_schema_tests::Case::bidirectional::<super::SccpBn254G1PointV1>(
        "iroha_data_model::bridge::sccp_registry::SccpBn254G1PointV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SccpBn254G2PointV1>(
        "iroha_data_model::bridge::sccp_registry::SccpBn254G2PointV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SccpGroth16Bn254IcV1>(
        "iroha_data_model::bridge::sccp_registry::SccpGroth16Bn254IcV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SccpGroth16Bn254VerifyingKeyV1>(
        "iroha_data_model::bridge::sccp_registry::SccpGroth16Bn254VerifyingKeyV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SccpGroth16Bls12381IcV1>(
        "iroha_data_model::bridge::sccp_registry::SccpGroth16Bls12381IcV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SccpGroth16Bls12381VerifyingKeyV1>(
        "iroha_data_model::bridge::sccp_registry::SccpGroth16Bls12381VerifyingKeyV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SccpGroth16Bn254SemanticCircuitV1>(
        "iroha_data_model::bridge::sccp_registry::SccpGroth16Bn254SemanticCircuitV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SccpGroth16Bls12381SemanticCircuitV1>(
        "iroha_data_model::bridge::sccp_registry::SccpGroth16Bls12381SemanticCircuitV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SccpSemanticProofProfileV1>(
        "iroha_data_model::bridge::sccp_registry::SccpSemanticProofProfileV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SccpSoraFinalityAnchorV1>(
        "iroha_data_model::bridge::sccp_registry::SccpSoraFinalityAnchorV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SccpOutboundProofPolicyV1>(
        "iroha_data_model::bridge::sccp_registry::SccpOutboundProofPolicyV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SccpPortableVerifyingKeyRefV1>(
        "iroha_data_model::bridge::sccp_registry::SccpPortableVerifyingKeyRefV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SccpSoraOutboundExecutionPolicyV1>(
        "iroha_data_model::bridge::sccp_registry::SccpSoraOutboundExecutionPolicyV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SccpRouteActivationV1>(
        "iroha_data_model::bridge::sccp_registry::SccpRouteActivationV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SccpInboundFinalityCutoffV1>(
        "iroha_data_model::bridge::sccp_registry::SccpInboundFinalityCutoffV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SccpRouteKeyV1>(
        "iroha_data_model::bridge::sccp_registry::SccpRouteKeyV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SccpEvmDestinationDeploymentV1>(
        "iroha_data_model::bridge::sccp_registry::SccpEvmDestinationDeploymentV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SccpTronDestinationDeploymentV1>(
        "iroha_data_model::bridge::sccp_registry::SccpTronDestinationDeploymentV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SccpTonMintBreakerGuardianKeysV1>(
        "iroha_data_model::bridge::sccp_registry::SccpTonMintBreakerGuardianKeysV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SccpTonDestinationDeploymentV1>(
        "iroha_data_model::bridge::sccp_registry::SccpTonDestinationDeploymentV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SccpDestinationDeploymentV1>(
        "iroha_data_model::bridge::sccp_registry::SccpDestinationDeploymentV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SccpSoraSettlementV1>(
        "iroha_data_model::bridge::sccp_registry::SccpSoraSettlementV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SccpGovernedRouteV1>(
        "iroha_data_model::bridge::sccp_registry::SccpGovernedRouteV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SccpGovernedLaneV1>(
        "iroha_data_model::bridge::sccp_registry::SccpGovernedLaneV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SccpRegistryV1>(
        "iroha_data_model::bridge::sccp_registry::SccpRegistryV1",
    ),
];

#[test]
fn captured_codec_schema_identities() {
    for case in CASES {
        case.check();
    }
}
