//! Immutable compiler-captured identities for this source owner’s existing codecs.

#[test]
fn captured_codec_schema_identities() {
    crate::captured_schema_tests::assert_bidirectional::<super::ProofOutcomeSignerPolicyV1>(
        "iroha_data_model::sorafs::proof_ledger::ProofOutcomeSignerPolicyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ProofOutcomeSignerPolicyRecordV1>(
        "iroha_data_model::sorafs::proof_ledger::ProofOutcomeSignerPolicyRecordV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ProofOutcomeKindV1>(
        "iroha_data_model::sorafs::proof_ledger::ProofOutcomeKindV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PdpOutcomeStatusV1>(
        "iroha_data_model::sorafs::proof_ledger::PdpOutcomeStatusV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PotrOutcomeStatusV1>(
        "iroha_data_model::sorafs::proof_ledger::PotrOutcomeStatusV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ProofOutcomeEd25519AttestationV1>(
        "iroha_data_model::sorafs::proof_ledger::ProofOutcomeEd25519AttestationV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PdpOutcomeProjectionV1>(
        "iroha_data_model::sorafs::proof_ledger::PdpOutcomeProjectionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PotrOutcomeProjectionV1>(
        "iroha_data_model::sorafs::proof_ledger::PotrOutcomeProjectionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ProofOutcomeProjectionV1>(
        "iroha_data_model::sorafs::proof_ledger::ProofOutcomeProjectionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ProofOutcomeRecordV1>(
        "iroha_data_model::sorafs::proof_ledger::ProofOutcomeRecordV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ProofOutcomeFinalizedCursorV1>(
        "iroha_data_model::sorafs::proof_ledger::ProofOutcomeFinalizedCursorV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ProofOutcomeFinalizedRecordV1>(
        "iroha_data_model::sorafs::proof_ledger::ProofOutcomeFinalizedRecordV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ProofOutcomeFinalizedEventCursorV1>(
        "iroha_data_model::sorafs::proof_ledger::ProofOutcomeFinalizedEventCursorV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ProofOutcomeFinalizedEventV1>(
        "iroha_data_model::sorafs::proof_ledger::ProofOutcomeFinalizedEventV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ProofOutcomeFinalizedEventPageV1>(
        "iroha_data_model::sorafs::proof_ledger::ProofOutcomeFinalizedEventPageV1",
    );
}
