//! Immutable compiler-captured identities for this source owner’s existing codecs.

const CASES: &[crate::captured_schema_tests::Case] = &[
    crate::captured_schema_tests::Case::bidirectional::<super::MergeSignerProof>(
        "iroha_data_model::merge::MergeSignerProof",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::LaneDrainNativeFrontierEvidenceV1>(
        "iroha_data_model::merge::LaneDrainNativeFrontierEvidenceV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::LaneDrainFrontierV1>(
        "iroha_data_model::merge::LaneDrainFrontierV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::LaneDrainIntentV1>(
        "iroha_data_model::merge::LaneDrainIntentV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::LaneDrainCertificateBodyV1>(
        "iroha_data_model::merge::LaneDrainCertificateBodyV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::LaneDrainCertificateV1>(
        "iroha_data_model::merge::LaneDrainCertificateV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::LaneDrainCommitmentV1>(
        "iroha_data_model::merge::LaneDrainCommitmentV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::LaneDrainStateV1>(
        "iroha_data_model::merge::LaneDrainStateV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MergeLaneBinding>(
        "iroha_data_model::merge::MergeLaneBinding",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MergeLaneCommitteeRosterV1>(
        "iroha_data_model::merge::MergeLaneCommitteeRosterV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MergeLaneAuthorityCatalogV1>(
        "iroha_data_model::merge::MergeLaneAuthorityCatalogV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MergeQuorumCertificate>(
        "iroha_data_model::merge::MergeQuorumCertificate",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MergeCommitteeSignature>(
        "iroha_data_model::merge::MergeCommitteeSignature",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MergeLaneSnapshot>(
        "iroha_data_model::merge::MergeLaneSnapshot",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MergeLaneSignerProof>(
        "iroha_data_model::merge::MergeLaneSignerProof",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MergeLaneFastpqTranscripts>(
        "iroha_data_model::merge::MergeLaneFastpqTranscripts",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MergeLaneExecution>(
        "iroha_data_model::merge::MergeLaneExecution",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MergeExecutionBatch>(
        "iroha_data_model::merge::MergeExecutionBatch",
    ),
    crate::captured_schema_tests::Case::serialize::<super::MergeLedgerEntry>(
        "iroha_data_model::merge::MergeLedgerEntry",
    ),
    crate::captured_schema_tests::Case::deserialize::<super::MergeLedgerEntryWire>(
        "iroha_data_model::merge::MergeLedgerEntryWire",
    ),
];

#[test]
fn captured_codec_schema_identities() {
    for case in CASES {
        case.check();
    }
}
