//! Immutable compiler-captured identities for this source owner’s existing codecs.

#[test]
fn captured_codec_schema_identities() {
    crate::captured_schema_tests::assert_bidirectional::<super::SoranetGarAbuseCountV1>(
        "iroha_data_model::soranet::privacy_metrics::SoranetGarAbuseCountV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoranetGarAbuseShareV1>(
        "iroha_data_model::soranet::privacy_metrics::SoranetGarAbuseShareV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoranetPrivacyModeV1>(
        "iroha_data_model::soranet::privacy_metrics::SoranetPrivacyModeV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoranetPrivacyPrioShareV1>(
        "iroha_data_model::soranet::privacy_metrics::SoranetPrivacyPrioShareV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoranetLatencyPercentileV1>(
        "iroha_data_model::soranet::privacy_metrics::SoranetLatencyPercentileV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoranetPrivacyBucketMetricsV1>(
        "iroha_data_model::soranet::privacy_metrics::SoranetPrivacyBucketMetricsV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoranetPrivacySuppressionReasonV1>(
        "iroha_data_model::soranet::privacy_metrics::SoranetPrivacySuppressionReasonV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoranetPrivacyEventV1>(
        "iroha_data_model::soranet::privacy_metrics::SoranetPrivacyEventV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoranetPrivacyEventKindV1>(
        "iroha_data_model::soranet::privacy_metrics::SoranetPrivacyEventKindV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::SoranetPrivacyEventHandshakeSuccessV1,
    >("iroha_data_model::soranet::privacy_metrics::SoranetPrivacyEventHandshakeSuccessV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::SoranetPrivacyEventHandshakeFailureV1,
    >("iroha_data_model::soranet::privacy_metrics::SoranetPrivacyEventHandshakeFailureV1");
    crate::captured_schema_tests::assert_bidirectional::<super::SoranetPrivacyEventThrottleV1>(
        "iroha_data_model::soranet::privacy_metrics::SoranetPrivacyEventThrottleV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoranetPrivacyEventActiveSampleV1>(
        "iroha_data_model::soranet::privacy_metrics::SoranetPrivacyEventActiveSampleV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoranetPrivacyEventVerifiedBytesV1>(
        "iroha_data_model::soranet::privacy_metrics::SoranetPrivacyEventVerifiedBytesV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::SoranetPrivacyEventGarAbuseCategoryV1,
    >("iroha_data_model::soranet::privacy_metrics::SoranetPrivacyEventGarAbuseCategoryV1");
    crate::captured_schema_tests::assert_bidirectional::<super::SoranetPrivacyHandshakeFailureV1>(
        "iroha_data_model::soranet::privacy_metrics::SoranetPrivacyHandshakeFailureV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoranetPowFailureReasonV1>(
        "iroha_data_model::soranet::privacy_metrics::SoranetPowFailureReasonV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoranetPowFailureCountV1>(
        "iroha_data_model::soranet::privacy_metrics::SoranetPowFailureCountV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoranetPrivacyThrottleScopeV1>(
        "iroha_data_model::soranet::privacy_metrics::SoranetPrivacyThrottleScopeV1",
    );
}
