//! Immutable compiler-captured identities for this source owner’s existing codecs.

const CASES: &[crate::captured_schema_tests::Case] = &[
    crate::captured_schema_tests::Case::bidirectional::<super::ManifestDigest>(
        "iroha_data_model::sorafs::pin_registry::ManifestDigest",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ChunkerProfileHandle>(
        "iroha_data_model::sorafs::pin_registry::ChunkerProfileHandle",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::PinPolicy>(
        "iroha_data_model::sorafs::pin_registry::PinPolicy",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::StorageClass>(
        "iroha_data_model::sorafs::pin_registry::StorageClass",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ManifestAliasBinding>(
        "iroha_data_model::sorafs::pin_registry::ManifestAliasBinding",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::PinStatus>(
        "iroha_data_model::sorafs::pin_registry::PinStatus",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::PinStatusKindV1>(
        "iroha_data_model::sorafs::pin_registry::PinStatusKindV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::PinResourceUsage>(
        "iroha_data_model::sorafs::pin_registry::PinResourceUsage",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::PinLineageSummaryV1>(
        "iroha_data_model::sorafs::pin_registry::PinLineageSummaryV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::PinFeePayment>(
        "iroha_data_model::sorafs::pin_registry::PinFeePayment",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::PinManifestRecord>(
        "iroha_data_model::sorafs::pin_registry::PinManifestRecord",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::PinManifestFinalizedCursorV1>(
        "iroha_data_model::sorafs::pin_registry::PinManifestFinalizedCursorV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::PinManifestFinalizedRecordV1>(
        "iroha_data_model::sorafs::pin_registry::PinManifestFinalizedRecordV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::PinManifestSummaryV1>(
        "iroha_data_model::sorafs::pin_registry::PinManifestSummaryV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::PinManifestPageV1>(
        "iroha_data_model::sorafs::pin_registry::PinManifestPageV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ManifestAliasId>(
        "iroha_data_model::sorafs::pin_registry::ManifestAliasId",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ManifestAliasRecord>(
        "iroha_data_model::sorafs::pin_registry::ManifestAliasRecord",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ReplicationOrderId>(
        "iroha_data_model::sorafs::pin_registry::ReplicationOrderId",
    ),
    crate::captured_schema_tests::Case::bidirectional::<
        super::ProviderIngestCompletionSignerPolicyV1,
    >("iroha_data_model::sorafs::pin_registry::ProviderIngestCompletionSignerPolicyV1"),
    crate::captured_schema_tests::Case::bidirectional::<super::ProviderIngestCompletionAuthorityV1>(
        "iroha_data_model::sorafs::pin_registry::ProviderIngestCompletionAuthorityV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ProviderIngestFinalizedAnchorV1>(
        "iroha_data_model::sorafs::pin_registry::ProviderIngestFinalizedAnchorV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ReplicationOrderStatus>(
        "iroha_data_model::sorafs::pin_registry::ReplicationOrderStatus",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ReplicationOrderCompletionRecord>(
        "iroha_data_model::sorafs::pin_registry::ReplicationOrderCompletionRecord",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ReplicationOrderRecord>(
        "iroha_data_model::sorafs::pin_registry::ReplicationOrderRecord",
    ),
];

#[test]
fn captured_codec_schema_identities() {
    for case in CASES {
        case.check();
    }
}
