//! Real-world asset lot structures and helper types.

use std::{format, str::FromStr, string::String, vec::Vec};

use derive_more::{Constructor, Display};
use getset::{Getters, MutGetters};
use iroha_crypto::Hash;
use iroha_primitives::numeric::{Numeric, NumericSpec};
use iroha_schema::IntoSchema;
use norito::codec::{Decode, Encode};

use crate::{
    HasMetadata, Identifiable, IntoKeyValue, Registered,
    common::{Owned, Ref, split_nonempty},
    error::ParseError,
    metadata::Metadata,
    prelude::{AccountId, DomainId, Name, RoleId},
};

/// Identifier of a single canonical RWA lot.
#[derive(
    Debug,
    Clone,
    Display,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Hash,
    Constructor,
    Getters,
    Decode,
    Encode,
    IntoSchema,
)]
#[display("{hash}${domain}")]
#[getset(get = "pub")]
#[cfg_attr(
    feature = "json",
    derive(crate::DeriveJsonSerialize, crate::DeriveJsonDeserialize)
)]
#[cfg_attr(any(feature = "ffi_export", feature = "ffi_import"), ffi_type)]
pub struct RwaId {
    /// Domain that scopes the lot identifier.
    pub domain: DomainId,
    /// Canonical generated hash for the lot.
    pub hash: Hash,
}

/// Quantitative provenance edge from a parent lot.
#[derive(
    Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Constructor, Getters, Decode, Encode, IntoSchema,
)]
#[getset(get = "pub")]
#[cfg_attr(
    feature = "json",
    derive(crate::DeriveJsonSerialize, crate::DeriveJsonDeserialize)
)]
#[cfg_attr(any(feature = "ffi_export", feature = "ffi_import"), ffi_type)]
pub struct RwaParentRef {
    /// Parent lot contributing to the child lot.
    pub rwa: RwaId,
    /// Quantity contributed by the parent lot.
    pub quantity: Numeric,
}

/// Per-lot controller configuration for optional compliance actions.
#[allow(clippy::struct_excessive_bools)] // Independent compliance toggles are kept explicit in the public data model.
#[derive(
    Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default, Getters, Decode, Encode, IntoSchema,
)]
#[getset(get = "pub")]
#[cfg_attr(
    feature = "json",
    derive(crate::DeriveJsonSerialize, crate::DeriveJsonDeserialize)
)]
#[cfg_attr(any(feature = "ffi_export", feature = "ffi_import"), ffi_type)]
pub struct RwaControlPolicy {
    /// Explicit controller accounts allowed to operate enabled controls on this lot.
    pub controller_accounts: Vec<AccountId>,
    /// Explicit controller roles allowed to operate enabled controls on this lot.
    pub controller_roles: Vec<RoleId>,
    /// Whether freezing is enabled for this lot.
    pub freeze_enabled: bool,
    /// Whether holds/reservations are enabled for this lot.
    pub hold_enabled: bool,
    /// Whether controller-driven forced transfer is enabled for this lot.
    pub force_transfer_enabled: bool,
    /// Whether redemption is enabled for this lot.
    pub redeem_enabled: bool,
}

/// Canonical real-world asset lot.
#[derive(
    Debug,
    Clone,
    Display,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Getters,
    MutGetters,
    Decode,
    Encode,
    IntoSchema,
)]
#[display("{id}")]
#[cfg_attr(
    feature = "json",
    derive(
        crate::DeriveFastJson,
        crate::DeriveJsonSerialize,
        crate::DeriveJsonDeserialize
    )
)]
#[cfg_attr(feature = "json", norito(no_fast_from_json))]
#[cfg_attr(any(feature = "ffi_export", feature = "ffi_import"), ffi_type)]
pub struct Rwa {
    /// Canonical identifier of the lot.
    pub id: RwaId,
    /// Current lot quantity. Partial transfers and redemptions reduce this value in place.
    #[getset(get = "pub", get_mut = "pub")]
    pub quantity: Numeric,
    /// Numeric policy constraining the quantity precision.
    #[getset(get_copy = "pub")]
    pub spec: NumericSpec,
    /// Primary off-chain reference describing the lot or certificate.
    #[getset(get = "pub")]
    pub primary_reference: String,
    /// Optional free-form status label.
    #[getset(get = "pub")]
    pub status: Option<Name>,
    /// Metadata carried by the lot.
    #[getset(get = "pub", get_mut = "pub")]
    pub metadata: Metadata,
    /// Quantitative parent edges describing provenance.
    #[getset(get = "pub", get_mut = "pub")]
    pub parents: Vec<RwaParentRef>,
    /// Optional compliance controls for the lot.
    #[getset(get = "pub", get_mut = "pub")]
    pub controls: RwaControlPolicy,
    /// Account that currently owns the lot.
    #[getset(get = "pub", get_mut = "pub")]
    pub owned_by: AccountId,
    /// Whether the lot is currently frozen.
    #[getset(get_copy = "pub", get_mut = "pub")]
    pub is_frozen: bool,
    /// Reserved quantity that cannot be transferred, merged, or redeemed.
    #[getset(get = "pub", get_mut = "pub")]
    pub held_quantity: Numeric,
}

/// Registration payload for a new lot. The canonical identifier is generated by the protocol.
#[allow(clippy::too_many_arguments)] // Constructor fields intentionally mirror the registration payload one-to-one.
#[derive(
    Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Getters, Decode, Encode, IntoSchema, Constructor,
)]
#[getset(get = "pub")]
#[cfg_attr(
    feature = "json",
    derive(crate::DeriveJsonSerialize, crate::DeriveJsonDeserialize)
)]
#[cfg_attr(any(feature = "ffi_export", feature = "ffi_import"), ffi_type)]
pub struct NewRwa {
    /// Domain that will scope the generated lot identifier.
    pub domain: DomainId,
    /// Initial lot quantity.
    pub quantity: Numeric,
    /// Numeric policy constraining the quantity precision.
    pub spec: NumericSpec,
    /// Primary off-chain reference describing the lot or certificate.
    pub primary_reference: String,
    /// Optional free-form status label.
    pub status: Option<Name>,
    /// Metadata carried by the lot.
    pub metadata: Metadata,
    /// Quantitative parent edges describing provenance.
    pub parents: Vec<RwaParentRef>,
    /// Optional compliance controls for the lot.
    pub controls: RwaControlPolicy,
}

/// Read-only reference to [`Rwa`].
pub type RwaEntry<'world> = Ref<'world, RwaId, RwaValue>;

/// [`Rwa`] without `id` field for world-state storage.
#[derive(Clone, norito::NoritoSerialize, norito::NoritoDeserialize)]
#[cfg_attr(
    feature = "json",
    derive(
        crate::DeriveFastJson,
        crate::DeriveJsonSerialize,
        crate::DeriveJsonDeserialize
    )
)]
#[cfg_attr(feature = "json", norito(no_fast_from_json))]
pub struct RwaData {
    /// Current lot quantity.
    pub quantity: Numeric,
    /// Numeric policy constraining the quantity precision.
    pub spec: NumericSpec,
    /// Primary off-chain reference describing the lot or certificate.
    pub primary_reference: String,
    /// Optional free-form status label.
    pub status: Option<Name>,
    /// Metadata carried by the lot.
    pub metadata: Metadata,
    /// Quantitative parent edges describing provenance.
    pub parents: Vec<RwaParentRef>,
    /// Optional compliance controls for the lot.
    pub controls: RwaControlPolicy,
    /// Account that currently owns the lot.
    pub owned_by: AccountId,
    /// Whether the lot is currently frozen.
    pub is_frozen: bool,
    /// Reserved quantity that cannot be transferred, merged, or redeemed.
    pub held_quantity: Numeric,
}

/// Wrapper over [`RwaData`] used in storages.
pub type RwaValue = Owned<RwaData>;

impl RwaId {
    /// Create a generated RWA identifier inside the given domain.
    pub fn generated(domain: DomainId, hash: Hash) -> Self {
        Self { domain, hash }
    }
}

impl FromStr for RwaId {
    type Err = ParseError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let (hash_candidate, domain_id_candidate) = split_nonempty(
            s,
            '$',
            "RWA ID should have format `hash$domain`",
            "Empty `hash` part in `hash$domain`",
            "Empty `domain` part in `hash$domain`",
        )?;
        let hash = hash_candidate.parse().map_err(|_| ParseError {
            reason: "Failed to parse `hash` part in `hash$domain`",
        })?;
        let domain_id =
            DomainId::parse_fully_qualified(domain_id_candidate).map_err(|_| ParseError {
                reason: "Failed to parse `domain` part in `hash$domain`",
            })?;
        Ok(Self::new(domain_id, hash))
    }
}

impl Rwa {
    /// Construct a fully identified lot.
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        id: RwaId,
        quantity: Numeric,
        spec: NumericSpec,
        primary_reference: String,
        status: Option<Name>,
        metadata: Metadata,
        parents: Vec<RwaParentRef>,
        controls: RwaControlPolicy,
        owned_by: AccountId,
    ) -> Self {
        Self {
            id,
            quantity,
            spec,
            primary_reference,
            status,
            metadata,
            parents,
            controls,
            owned_by,
            is_frozen: false,
            held_quantity: Numeric::zero(),
        }
    }

    /// Return the available quantity after subtracting held reservations.
    pub fn available_quantity(&self) -> Option<Numeric> {
        self.quantity
            .clone()
            .checked_sub(self.held_quantity.clone())
    }
}

impl NewRwa {
    /// Build a canonical lot from a generated identifier and owner.
    pub fn build(self, id: RwaId, owner: AccountId) -> Rwa {
        Rwa::new(
            id,
            self.quantity,
            self.spec,
            self.primary_reference,
            self.status,
            self.metadata,
            self.parents,
            self.controls,
            owner,
        )
    }
}

impl Identifiable for Rwa {
    type Id = RwaId;

    fn id(&self) -> &Self::Id {
        &self.id
    }
}

impl Registered for Rwa {
    type With = Self;
}

impl HasMetadata for Rwa {
    fn metadata(&self) -> &Metadata {
        &self.metadata
    }
}

impl HasMetadata for NewRwa {
    fn metadata(&self) -> &Metadata {
        &self.metadata
    }
}

impl IntoKeyValue for Rwa {
    type Key = RwaId;
    type Value = RwaValue;

    fn into_key_value(self) -> (Self::Key, Self::Value) {
        (
            self.id,
            Owned::new(RwaData {
                quantity: self.quantity,
                spec: self.spec,
                primary_reference: self.primary_reference,
                status: self.status,
                metadata: self.metadata,
                parents: self.parents,
                controls: self.controls,
                owned_by: self.owned_by,
                is_frozen: self.is_frozen,
                held_quantity: self.held_quantity,
            }),
        )
    }
}

#[cfg(feature = "json")]
impl mv::json::JsonKeyCodec for RwaId {
    fn encode_json_key(&self, out: &mut String) {
        norito::json::write_json_string(&self.to_string(), out);
    }

    fn decode_json_key(encoded: &str) -> Result<Self, norito::json::Error> {
        encoded
            .parse::<Self>()
            .map_err(|err| norito::json::Error::Message(err.to_string()))
    }
}

#[cfg(all(test, feature = "json"))]
mod json_tests {
    use super::*;

    #[test]
    fn new_rwa_json_roundtrip() {
        let builder = NewRwa::new(
            DomainId::try_new("vault", "universal").expect("domain"),
            "12.50".parse().expect("quantity"),
            NumericSpec::fractional(2),
            "https://example.test/certificates/lot-7".to_owned(),
            Some("vaulted".parse().expect("status")),
            Metadata::default(),
            Vec::new(),
            RwaControlPolicy::default(),
        );

        let json = norito::json::to_json(&builder).expect("serialize");
        let decoded: NewRwa = norito::json::from_json(&json).expect("deserialize");

        assert_eq!(decoded, builder);
    }
}

/// Prelude re-exports for the RWA module.
pub mod prelude {
    pub use super::{NewRwa, Rwa, RwaControlPolicy, RwaId, RwaParentRef};
}
