---------------------------- MODULE counterexample ----------------------------

EXTENDS Sumeragi

(* Constant initialization state *)
ConstInit ==
  CommitQuorum = 3
    /\ F = 1
    /\ MaxChunks = 2
    /\ MaxView = 4
    /\ N = 4
    /\ StakePerByzVote = 1
    /\ StakePerHonestVote = 3
    /\ StakeQuorum = 8
    /\ ViewQuorum = 3

(* Initial state [_transition(0)] *)
(* State0 ==
  CommitQuorum = 3
    /\ F = 1
    /\ MaxChunks = 2
    /\ MaxView = 4
    /\ N = 4
    /\ StakePerByzVote = 1
    /\ StakePerHonestVote = 3
    /\ StakeQuorum = 8
    /\ ViewQuorum = 3
    /\ __EventuallyCommit_init = FALSE
    /\ __InLoop = FALSE
    /\ __saved_☐(gst ⇒ ♢committed) = FALSE
    /\ __saved_gst ⇒ ♢committed = TRUE
    /\ __saved_♢committed = FALSE
    /\ __saved_chunkCount = 0
    /\ __saved_commitVotesByz = 0
    /\ __saved_commitVotesHonest = 0
    /\ __saved_committed = FALSE
    /\ __saved_digestValid = FALSE
    /\ __saved_gst = FALSE
    /\ __saved_headerSeen = FALSE
    /\ __saved_newViewVotes = 0
    /\ __saved_phase = "Propose"
    /\ __saved_prepareVotes = 0
    /\ __saved_rbcState = "Idle"
    /\ __saved_readyVotes = 0
    /\ __saved_stakeSigned = 0
    /\ __saved_view = 0
    /\ ☐(gst ⇒ ♢committed) = FALSE
    /\ __temporal_t_1_unroll = TRUE
    /\ __temporal_t_1_unroll_prev = TRUE
    /\ gst ⇒ ♢committed = TRUE
    /\ ♢committed = FALSE
    /\ __temporal_t_3_unroll = FALSE
    /\ __temporal_t_3_unroll_prev = FALSE
    /\ chunkCount = 0
    /\ commitVotesByz = 0
    /\ commitVotesHonest = 0
    /\ committed = FALSE
    /\ digestValid = FALSE
    /\ gst = FALSE
    /\ headerSeen = FALSE
    /\ newViewVotes = 0
    /\ phase = "Propose"
    /\ prepareVotes = 0
    /\ rbcState = "Idle"
    /\ readyVotes = 0
    /\ stakeSigned = 0
    /\ view = 0 *)
State0 ==
  CommitQuorum = 3
    /\ F = 1
    /\ MaxChunks = 2
    /\ MaxView = 4
    /\ N = 4
    /\ StakePerByzVote = 1
    /\ StakePerHonestVote = 3
    /\ StakeQuorum = 8
    /\ ViewQuorum = 3
    /\ __EventuallyCommit_init = FALSE
    /\ __InLoop = FALSE
    /\ __saved___temporal_t_1 = FALSE
    /\ __saved___temporal_t_2 = TRUE
    /\ __saved___temporal_t_3 = FALSE
    /\ __saved_chunkCount = 0
    /\ __saved_commitVotesByz = 0
    /\ __saved_commitVotesHonest = 0
    /\ __saved_committed = FALSE
    /\ __saved_digestValid = FALSE
    /\ __saved_gst = FALSE
    /\ __saved_headerSeen = FALSE
    /\ __saved_newViewVotes = 0
    /\ __saved_phase = "Propose"
    /\ __saved_prepareVotes = 0
    /\ __saved_rbcState = "Idle"
    /\ __saved_readyVotes = 0
    /\ __saved_stakeSigned = 0
    /\ __saved_view = 0
    /\ __temporal_t_1 = FALSE
    /\ __temporal_t_1_unroll = TRUE
    /\ __temporal_t_1_unroll_prev = TRUE
    /\ __temporal_t_2 = TRUE
    /\ __temporal_t_3 = FALSE
    /\ __temporal_t_3_unroll = FALSE
    /\ __temporal_t_3_unroll_prev = FALSE
    /\ chunkCount = 0
    /\ commitVotesByz = 0
    /\ commitVotesHonest = 0
    /\ committed = FALSE
    /\ digestValid = FALSE
    /\ gst = FALSE
    /\ headerSeen = FALSE
    /\ newViewVotes = 0
    /\ phase = "Propose"
    /\ prepareVotes = 0
    /\ rbcState = "Idle"
    /\ readyVotes = 0
    /\ stakeSigned = 0
    /\ view = 0

(* State1 [_transition(22)] *)
(* State1 ==
  CommitQuorum = 3
    /\ F = 1
    /\ MaxChunks = 2
    /\ MaxView = 4
    /\ N = 4
    /\ StakePerByzVote = 1
    /\ StakePerHonestVote = 3
    /\ StakeQuorum = 8
    /\ ViewQuorum = 3
    /\ __EventuallyCommit_init = FALSE
    /\ __InLoop = FALSE
    /\ __saved_☐(gst ⇒ ♢committed) = FALSE
    /\ __saved_gst ⇒ ♢committed = TRUE
    /\ __saved_♢committed = FALSE
    /\ __saved_chunkCount = 0
    /\ __saved_commitVotesByz = 0
    /\ __saved_commitVotesHonest = 0
    /\ __saved_committed = FALSE
    /\ __saved_digestValid = FALSE
    /\ __saved_gst = FALSE
    /\ __saved_headerSeen = FALSE
    /\ __saved_newViewVotes = 0
    /\ __saved_phase = "Propose"
    /\ __saved_prepareVotes = 0
    /\ __saved_rbcState = "Idle"
    /\ __saved_readyVotes = 0
    /\ __saved_stakeSigned = 0
    /\ __saved_view = 0
    /\ ☐(gst ⇒ ♢committed) = FALSE
    /\ __temporal_t_1_unroll = TRUE
    /\ __temporal_t_1_unroll_prev = TRUE
    /\ gst ⇒ ♢committed = TRUE
    /\ ♢committed = FALSE
    /\ __temporal_t_3_unroll = FALSE
    /\ __temporal_t_3_unroll_prev = FALSE
    /\ chunkCount = 0
    /\ commitVotesByz = 0
    /\ commitVotesHonest = 0
    /\ committed = FALSE
    /\ digestValid = FALSE
    /\ gst = TRUE
    /\ headerSeen = FALSE
    /\ newViewVotes = 0
    /\ phase = "Propose"
    /\ prepareVotes = 0
    /\ rbcState = "Idle"
    /\ readyVotes = 0
    /\ stakeSigned = 0
    /\ view = 0 *)
State1 ==
  CommitQuorum = 3
    /\ F = 1
    /\ MaxChunks = 2
    /\ MaxView = 4
    /\ N = 4
    /\ StakePerByzVote = 1
    /\ StakePerHonestVote = 3
    /\ StakeQuorum = 8
    /\ ViewQuorum = 3
    /\ __EventuallyCommit_init = FALSE
    /\ __InLoop = FALSE
    /\ __saved___temporal_t_1 = FALSE
    /\ __saved___temporal_t_2 = TRUE
    /\ __saved___temporal_t_3 = FALSE
    /\ __saved_chunkCount = 0
    /\ __saved_commitVotesByz = 0
    /\ __saved_commitVotesHonest = 0
    /\ __saved_committed = FALSE
    /\ __saved_digestValid = FALSE
    /\ __saved_gst = FALSE
    /\ __saved_headerSeen = FALSE
    /\ __saved_newViewVotes = 0
    /\ __saved_phase = "Propose"
    /\ __saved_prepareVotes = 0
    /\ __saved_rbcState = "Idle"
    /\ __saved_readyVotes = 0
    /\ __saved_stakeSigned = 0
    /\ __saved_view = 0
    /\ __temporal_t_1 = FALSE
    /\ __temporal_t_1_unroll = TRUE
    /\ __temporal_t_1_unroll_prev = TRUE
    /\ __temporal_t_2 = TRUE
    /\ __temporal_t_3 = FALSE
    /\ __temporal_t_3_unroll = FALSE
    /\ __temporal_t_3_unroll_prev = FALSE
    /\ chunkCount = 0
    /\ commitVotesByz = 0
    /\ commitVotesHonest = 0
    /\ committed = FALSE
    /\ digestValid = FALSE
    /\ gst = TRUE
    /\ headerSeen = FALSE
    /\ newViewVotes = 0
    /\ phase = "Propose"
    /\ prepareVotes = 0
    /\ rbcState = "Idle"
    /\ readyVotes = 0
    /\ stakeSigned = 0
    /\ view = 0

(* State2 [_transition(8)] *)
(* State2 ==
  CommitQuorum = 3
    /\ F = 1
    /\ MaxChunks = 2
    /\ MaxView = 4
    /\ N = 4
    /\ StakePerByzVote = 1
    /\ StakePerHonestVote = 3
    /\ StakeQuorum = 8
    /\ ViewQuorum = 3
    /\ __EventuallyCommit_init = FALSE
    /\ __InLoop = FALSE
    /\ __saved_☐(gst ⇒ ♢committed) = FALSE
    /\ __saved_gst ⇒ ♢committed = TRUE
    /\ __saved_♢committed = FALSE
    /\ __saved_chunkCount = 0
    /\ __saved_commitVotesByz = 0
    /\ __saved_commitVotesHonest = 0
    /\ __saved_committed = FALSE
    /\ __saved_digestValid = FALSE
    /\ __saved_gst = FALSE
    /\ __saved_headerSeen = FALSE
    /\ __saved_newViewVotes = 0
    /\ __saved_phase = "Propose"
    /\ __saved_prepareVotes = 0
    /\ __saved_rbcState = "Idle"
    /\ __saved_readyVotes = 0
    /\ __saved_stakeSigned = 0
    /\ __saved_view = 0
    /\ ☐(gst ⇒ ♢committed) = FALSE
    /\ __temporal_t_1_unroll = FALSE
    /\ __temporal_t_1_unroll_prev = TRUE
    /\ gst ⇒ ♢committed = FALSE
    /\ ♢committed = FALSE
    /\ __temporal_t_3_unroll = FALSE
    /\ __temporal_t_3_unroll_prev = FALSE
    /\ chunkCount = 0
    /\ commitVotesByz = 0
    /\ commitVotesHonest = 0
    /\ committed = FALSE
    /\ digestValid = FALSE
    /\ gst = TRUE
    /\ headerSeen = FALSE
    /\ newViewVotes = 0
    /\ phase = "NewView"
    /\ prepareVotes = 0
    /\ rbcState = "Idle"
    /\ readyVotes = 0
    /\ stakeSigned = 0
    /\ view = 1 *)
State2 ==
  CommitQuorum = 3
    /\ F = 1
    /\ MaxChunks = 2
    /\ MaxView = 4
    /\ N = 4
    /\ StakePerByzVote = 1
    /\ StakePerHonestVote = 3
    /\ StakeQuorum = 8
    /\ ViewQuorum = 3
    /\ __EventuallyCommit_init = FALSE
    /\ __InLoop = FALSE
    /\ __saved___temporal_t_1 = FALSE
    /\ __saved___temporal_t_2 = TRUE
    /\ __saved___temporal_t_3 = FALSE
    /\ __saved_chunkCount = 0
    /\ __saved_commitVotesByz = 0
    /\ __saved_commitVotesHonest = 0
    /\ __saved_committed = FALSE
    /\ __saved_digestValid = FALSE
    /\ __saved_gst = FALSE
    /\ __saved_headerSeen = FALSE
    /\ __saved_newViewVotes = 0
    /\ __saved_phase = "Propose"
    /\ __saved_prepareVotes = 0
    /\ __saved_rbcState = "Idle"
    /\ __saved_readyVotes = 0
    /\ __saved_stakeSigned = 0
    /\ __saved_view = 0
    /\ __temporal_t_1 = FALSE
    /\ __temporal_t_1_unroll = FALSE
    /\ __temporal_t_1_unroll_prev = TRUE
    /\ __temporal_t_2 = FALSE
    /\ __temporal_t_3 = FALSE
    /\ __temporal_t_3_unroll = FALSE
    /\ __temporal_t_3_unroll_prev = FALSE
    /\ chunkCount = 0
    /\ commitVotesByz = 0
    /\ commitVotesHonest = 0
    /\ committed = FALSE
    /\ digestValid = FALSE
    /\ gst = TRUE
    /\ headerSeen = FALSE
    /\ newViewVotes = 0
    /\ phase = "NewView"
    /\ prepareVotes = 0
    /\ rbcState = "Idle"
    /\ readyVotes = 0
    /\ stakeSigned = 0
    /\ view = 1

(* State3 [_transition(21)] *)
(* State3 ==
  CommitQuorum = 3
    /\ F = 1
    /\ MaxChunks = 2
    /\ MaxView = 4
    /\ N = 4
    /\ StakePerByzVote = 1
    /\ StakePerHonestVote = 3
    /\ StakeQuorum = 8
    /\ ViewQuorum = 3
    /\ __EventuallyCommit_init = FALSE
    /\ __InLoop = TRUE
    /\ __saved_☐(gst ⇒ ♢committed) = FALSE
    /\ __saved_gst ⇒ ♢committed = FALSE
    /\ __saved_♢committed = FALSE
    /\ __saved_chunkCount = 0
    /\ __saved_commitVotesByz = 0
    /\ __saved_commitVotesHonest = 0
    /\ __saved_committed = FALSE
    /\ __saved_digestValid = FALSE
    /\ __saved_gst = TRUE
    /\ __saved_headerSeen = FALSE
    /\ __saved_newViewVotes = 0
    /\ __saved_phase = "NewView"
    /\ __saved_prepareVotes = 0
    /\ __saved_rbcState = "Idle"
    /\ __saved_readyVotes = 0
    /\ __saved_stakeSigned = 0
    /\ __saved_view = 1
    /\ ☐(gst ⇒ ♢committed) = FALSE
    /\ __temporal_t_1_unroll = FALSE
    /\ __temporal_t_1_unroll_prev = FALSE
    /\ gst ⇒ ♢committed = FALSE
    /\ ♢committed = FALSE
    /\ __temporal_t_3_unroll = FALSE
    /\ __temporal_t_3_unroll_prev = FALSE
    /\ chunkCount = 0
    /\ commitVotesByz = 0
    /\ commitVotesHonest = 0
    /\ committed = FALSE
    /\ digestValid = FALSE
    /\ gst = TRUE
    /\ headerSeen = FALSE
    /\ newViewVotes = 0
    /\ phase = "NewView"
    /\ prepareVotes = 0
    /\ rbcState = "Idle"
    /\ readyVotes = 0
    /\ stakeSigned = 0
    /\ view = 1 *)
State3 ==
  CommitQuorum = 3
    /\ F = 1
    /\ MaxChunks = 2
    /\ MaxView = 4
    /\ N = 4
    /\ StakePerByzVote = 1
    /\ StakePerHonestVote = 3
    /\ StakeQuorum = 8
    /\ ViewQuorum = 3
    /\ __EventuallyCommit_init = FALSE
    /\ __InLoop = TRUE
    /\ __saved___temporal_t_1 = FALSE
    /\ __saved___temporal_t_2 = FALSE
    /\ __saved___temporal_t_3 = FALSE
    /\ __saved_chunkCount = 0
    /\ __saved_commitVotesByz = 0
    /\ __saved_commitVotesHonest = 0
    /\ __saved_committed = FALSE
    /\ __saved_digestValid = FALSE
    /\ __saved_gst = TRUE
    /\ __saved_headerSeen = FALSE
    /\ __saved_newViewVotes = 0
    /\ __saved_phase = "NewView"
    /\ __saved_prepareVotes = 0
    /\ __saved_rbcState = "Idle"
    /\ __saved_readyVotes = 0
    /\ __saved_stakeSigned = 0
    /\ __saved_view = 1
    /\ __temporal_t_1 = FALSE
    /\ __temporal_t_1_unroll = FALSE
    /\ __temporal_t_1_unroll_prev = FALSE
    /\ __temporal_t_2 = FALSE
    /\ __temporal_t_3 = FALSE
    /\ __temporal_t_3_unroll = FALSE
    /\ __temporal_t_3_unroll_prev = FALSE
    /\ chunkCount = 0
    /\ commitVotesByz = 0
    /\ commitVotesHonest = 0
    /\ committed = FALSE
    /\ digestValid = FALSE
    /\ gst = TRUE
    /\ headerSeen = FALSE
    /\ newViewVotes = 0
    /\ phase = "NewView"
    /\ prepareVotes = 0
    /\ rbcState = "Idle"
    /\ readyVotes = 0
    /\ stakeSigned = 0
    /\ view = 1

(* The following formula holds true in the last state and violates the invariant *)
(* InvariantViolation ==
  (__InLoop
      /\ commitVotesHonest = __saved_commitVotesHonest
      /\ readyVotes = __saved_readyVotes
      /\ chunkCount = __saved_chunkCount
      /\ view = __saved_view
      /\ stakeSigned = __saved_stakeSigned
      /\ gst = __saved_gst
      /\ commitVotesByz = __saved_commitVotesByz
      /\ committed = __saved_committed
      /\ prepareVotes = __saved_prepareVotes
      /\ phase = __saved_phase
      /\ digestValid = __saved_digestValid
      /\ rbcState = __saved_rbcState
      /\ headerSeen = __saved_headerSeen
      /\ newViewVotes = __saved_newViewVotes
      /\ ☐(gst ⇒ ♢committed) = __saved_☐(gst ⇒ ♢committed)
      /\ gst ⇒ ♢committed = __saved_gst ⇒ ♢committed
      /\ ♢committed = __saved_♢committed
      /\ (~♢committed \/ __temporal_t_3_unroll)
      /\ __temporal_t_3_unroll_prev = __temporal_t_3_unroll
      /\ (~__temporal_t_1_unroll \/ ☐(gst ⇒ ♢committed))
      /\ __temporal_t_1_unroll_prev = __temporal_t_1_unroll)
    /\ ~__EventuallyCommit_init *)
InvariantViolation ==
  (__InLoop
      /\ commitVotesHonest = __saved_commitVotesHonest
      /\ readyVotes = __saved_readyVotes
      /\ chunkCount = __saved_chunkCount
      /\ view = __saved_view
      /\ stakeSigned = __saved_stakeSigned
      /\ gst = __saved_gst
      /\ commitVotesByz = __saved_commitVotesByz
      /\ committed = __saved_committed
      /\ prepareVotes = __saved_prepareVotes
      /\ phase = __saved_phase
      /\ digestValid = __saved_digestValid
      /\ rbcState = __saved_rbcState
      /\ headerSeen = __saved_headerSeen
      /\ newViewVotes = __saved_newViewVotes
      /\ __temporal_t_1 = __saved___temporal_t_1
      /\ __temporal_t_2 = __saved___temporal_t_2
      /\ __temporal_t_3 = __saved___temporal_t_3
      /\ (~__temporal_t_3 \/ __temporal_t_3_unroll)
      /\ __temporal_t_3_unroll_prev = __temporal_t_3_unroll
      /\ (~__temporal_t_1_unroll \/ __temporal_t_1)
      /\ __temporal_t_1_unroll_prev = __temporal_t_1_unroll)
    /\ ~__EventuallyCommit_init

================================================================================
(* Created by Apalache on Mon Feb 23 17:19:07 GST 2026 *)
(* https://github.com/apalache-mc/apalache *)
