[package]
name = "sorafs_chunker"
autobins = false
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "Deterministic content-defined chunking primitives for SoraFS."

[features]
dev-tools = []

[[bin]]
name = "export_vectors"
path = "src/bin/export_vectors.rs"
required-features = ["dev-tools"]

[[bin]]
name = "sorafs_chunk_digest"
path = "src/bin/sorafs_chunk_digest.rs"
required-features = ["dev-tools"]

[[bin]]
name = "sorafs_chunk_dump"
path = "src/bin/sorafs_chunk_dump.rs"
required-features = ["dev-tools"]

[dependencies]
sha3 = "0.10.8"
blake3 = "1.8.2"
norito = { workspace = true, default-features = false, features = ["base-codec"] }
iroha_crypto = { workspace = true, default-features = false, features = ["application"] }
hex = "0.4.3"
