#!/usr/bin/env python3
"""Generate deterministic SignedRansTablesV1 artefacts with the xtask helper.

The script wraps `cargo run -p xtask -- codec rans-tables` to ensure the tables
are produced inside `codec/rans/tables/` with the CC0/Apache notice applied.
"""

from __future__ import annotations

import argparse
import pathlib
import shutil
import subprocess
import sys
import tempfile
from typing import Iterable

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = pathlib.Path("codec/rans/tables/rans_seed0.toml")
HEADER = """\
SPDX-License-Identifier: CC0-1.0
rANS Deterministic Tables and Initialization Vectors
These tables are generated by tools/rans/gen_tables.py and are dedicated to the public
domain (CC0-1.0). The surrounding source code remains Apache-2.0 licensed.
Attribution: rANS is a variant of Asymmetric Numeral Systems (J. Duda, arXiv:1311.2540).
"""


def main() -> None:
    args = parse_args()
    if args.bundle_width < 2 or args.bundle_width > 4:
        raise SystemExit("[gen_tables] --bundle-width must be within 2..=4")
    out_path = (REPO_ROOT / args.output).resolve()
    out_path.parent.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory() as tmpdir:
        tmp_base = pathlib.Path(tmpdir) / "signed_rans_tables"
        run_xtask(
            seed=args.seed,
            bundle_width=args.bundle_width,
            output_base=tmp_base,
            cwd=REPO_ROOT,
        )
        tmp_toml = tmp_base.with_suffix(".toml")
        if not tmp_toml.exists():
            raise SystemExit(f"[gen_tables] expected output file {tmp_toml} was not created")
        write_with_header(tmp_toml, out_path)

    if args.verify:
        run_xtask(
            seed=args.seed,
            bundle_width=args.bundle_width,
            output_base=out_path,
            cwd=REPO_ROOT,
            verify=True,
        )
    print(f"[gen_tables] wrote {out_path.relative_to(REPO_ROOT)}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--seed",
        default="0",
        help="u64 seed for the deterministic generator (decimal or 0x-prefixed hex).",
    )
    parser.add_argument(
        "--bundle-width",
        type=int,
        default=4,
        help="maximum bundle width (2..4) to target when generating the tables.",
    )
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=DEFAULT_OUTPUT,
        help=f"destination path relative to repo root (default: {DEFAULT_OUTPUT})",
    )
    parser.add_argument(
        "--verify",
        action="store_true",
        help="re-run xtask verification against the generated artefact",
    )
    return parser.parse_args()


def run_xtask(
    *,
    seed: str,
    bundle_width: int,
    output_base: pathlib.Path,
    cwd: pathlib.Path,
    verify: bool = False,
) -> None:
    seed_value = parse_seed(seed)
    cmd: list[str] = [
        "cargo",
        "run",
        "-p",
        "xtask",
        "--bin",
        "xtask",
        "--",
        "codec",
        "rans-tables",
        "--bundle-width",
        str(bundle_width),
        "--seed",
        str(seed_value),
    ]
    if verify:
        cmd.extend(["--verify", str(output_base)])
    else:
        cmd.extend(["--format", "toml", "--output", str(output_base)])
    subprocess.run(cmd, cwd=cwd, check=True)


def parse_seed(value: str) -> int:
    try:
        return int(value, 0)
    except ValueError as exc:  # pragma: no cover - argument parsing guard
        raise SystemExit(f"[gen_tables] invalid seed '{value}': {exc}") from exc


def write_with_header(src: pathlib.Path, dest: pathlib.Path) -> None:
    text = src.read_text(encoding="utf-8")
    header_lines = _comment_block(HEADER.strip().splitlines())
    dest.write_text("\n".join(header_lines) + "\n\n" + text, encoding="utf-8")


def _comment_block(lines: Iterable[str]) -> list[str]:
    return [f"# {line}" if line else "#" for line in lines]


if __name__ == "__main__":
    if shutil.which("cargo") is None:  # pragma: no cover - environment guard
        raise SystemExit("[gen_tables] cargo binary not found in PATH")
    main()
