using System.Text.Json.Nodes;
using System.Text.Json.Serialization;

namespace Hyperledger.Iroha.Torii;

[JsonSerializable(typeof(JsonNode))]
[JsonSerializable(typeof(JsonObject))]
[JsonSerializable(typeof(ToriiAccountAliasLookupRequest))]
[JsonSerializable(typeof(ToriiAccountAliasLookupItem))]
[JsonSerializable(typeof(ToriiAccountAliasLookupResponse))]
[JsonSerializable(typeof(ToriiAccountAliasIndexResolution))]
[JsonSerializable(typeof(ToriiAccountFaucetPuzzle))]
[JsonSerializable(typeof(ToriiAccountFaucetRequest))]
[JsonSerializable(typeof(ToriiAccountFaucetResponse))]
[JsonSerializable(typeof(ToriiAliasResolutionRequest))]
[JsonSerializable(typeof(ToriiAliasResolveIndexRequest))]
[JsonSerializable(typeof(ToriiExplorerAccountQrSnapshot))]
[JsonSerializable(typeof(ToriiAccountOnboardingResponse))]
[JsonSerializable(typeof(ToriiAccountOnboardingRequest))]
[JsonSerializable(typeof(ToriiAccountsPage))]
[JsonSerializable(typeof(ToriiAccountAliasResolution))]
[JsonSerializable(typeof(ToriiAccountPermission))]
[JsonSerializable(typeof(ToriiAccountPermissionsPage))]
[JsonSerializable(typeof(ToriiAccountSummary))]
[JsonSerializable(typeof(ToriiAssetAliasBinding))]
[JsonSerializable(typeof(ToriiAssetAliasResolution))]
[JsonSerializable(typeof(ToriiAssetBalancesPage))]
[JsonSerializable(typeof(ToriiAssetBalance))]
[JsonSerializable(typeof(ToriiTransactionsPage))]
[JsonSerializable(typeof(ToriiTransactionSummary))]
[JsonSerializable(typeof(ToriiUaidBindingsDataspace))]
[JsonSerializable(typeof(ToriiUaidBindingsResponse))]
[JsonSerializable(typeof(ToriiUaidManifestLifecycle))]
[JsonSerializable(typeof(ToriiUaidManifestRecord))]
[JsonSerializable(typeof(ToriiUaidManifestRevocation))]
[JsonSerializable(typeof(ToriiUaidManifestsResponse))]
[JsonSerializable(typeof(ToriiUaidPortfolioAsset))]
[JsonSerializable(typeof(ToriiUaidPortfolioAccount))]
[JsonSerializable(typeof(ToriiUaidPortfolioDataspace))]
[JsonSerializable(typeof(ToriiUaidPortfolioResponse))]
[JsonSerializable(typeof(ToriiUaidPortfolioTotals))]
[JsonSerializable(typeof(ToriiContractAliasBinding))]
[JsonSerializable(typeof(ToriiContractAliasResolutionRequest))]
[JsonSerializable(typeof(ToriiContractAliasResolution))]
[JsonSerializable(typeof(ToriiIdentifierPoliciesResponse))]
[JsonSerializable(typeof(ToriiIdentifierPolicySummary))]
[JsonSerializable(typeof(ToriiIdentifierResolveRequest))]
[JsonSerializable(typeof(ToriiIdentifierResolveResponse))]
[JsonSerializable(typeof(ToriiMultisigAccountOnboardingRequest))]
[JsonSerializable(typeof(ToriiMultisigAccountOnboardingResponse))]
[JsonSerializable(typeof(ToriiNodeCapabilities))]
[JsonSerializable(typeof(ToriiNodeCryptoCapabilities))]
[JsonSerializable(typeof(ToriiNodeSmCapabilities))]
[JsonSerializable(typeof(ToriiNodeSmAcceleration))]
[JsonSerializable(typeof(ToriiNodeCurveCapabilities))]
[JsonSerializable(typeof(ToriiRuntimeMetrics))]
[JsonSerializable(typeof(ToriiRuntimeUpgradeCounters))]
[JsonSerializable(typeof(ToriiRuntimeAbiActive))]
[JsonSerializable(typeof(ToriiRuntimeAbiHash))]
internal sealed partial class ToriiJsonSerializerContext : JsonSerializerContext
{
}
