//! POSIX shell quoting for operator handoff commands generated by Kagami.

use color_eyre::eyre::{Result, WrapErr as _, eyre};
use std::path::{Path, PathBuf};

/// Quote one control-free value as a POSIX shell word.
pub fn single_quote(value: &str) -> Result<String> {
    if value.contains(['\0', '\n', '\r']) {
        return Err(eyre!("shell value contains a control character"));
    }
    Ok(format!("'{}'", value.replace('\'', "'\"'\"'")))
}

/// Quote a UTF-8 path as one POSIX shell word.
pub fn quote_path(path: &Path) -> Result<String> {
    let value = path
        .to_str()
        .ok_or_else(|| eyre!("shell command path is not valid UTF-8: {}", path.display()))?;
    single_quote(value)
}

/// Resolve a lexical path against the current directory and quote it as one shell word.
pub fn absolute_quote_path(path: &Path) -> Result<String> {
    let absolute = if path.is_absolute() {
        PathBuf::from(path)
    } else {
        std::env::current_dir()
            .wrap_err("resolve current directory for shell handoff command")?
            .join(path)
    };
    quote_path(&absolute)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn single_quote_handles_spaces_and_apostrophes() {
        assert_eq!(
            single_quote("/tmp/local net's").expect("quote shell path"),
            "'/tmp/local net'\"'\"'s'"
        );
    }

    #[test]
    fn quote_path_rejects_control_characters() {
        assert!(quote_path(Path::new("/tmp/localnet\nnext")).is_err());
    }
}
