#![allow(unsafe_code)]

//! Structures and macros related to FFI and generation of FFI bindings. Any type that implements
//! [`FfiType`] can be used in the FFI bindings generated with [`ffi_export`]/[`ffi_import`]. It
//! is advisable to implement [`Ir`] and benefit from automatic implementation of [`FfiType`]
use derive_more::Display;
use ir::{Ir, Transmute};
pub use iroha_ffi_proc_macro::*;
use repr_c::{
    COutPtr, COutPtrRead, COutPtrWrite, CType, CTypeConvert, CWrapperType, Cloned, NonLocal,
};
use std::{boxed::Box, format, string::String, vec::Vec};
pub mod handle;
pub mod ir;
pub mod option;
pub mod primitives;
pub mod repr_c;
pub mod slice;
mod std_impls;
/// Panic logging utilities invoked by generated FFI stubs.
pub mod panic_notifier {
    use std::{
        any::Any,
        fmt,
        io::{self, Write as _},
    };
    fn write_stderr(args: fmt::Arguments<'_>) {
        let mut stderr = io::stderr().lock();
        let _ = stderr.write_fmt(args);
        let _ = stderr.write_all(b"\n");
    }
    /// Logs the panic payload captured while crossing the FFI boundary.
    ///
    /// The notifier prefers human-readable messages (`&str`/`String`) and falls back to
    /// a generic marker for non-string payloads.
    pub fn log_panic(payload: &(dyn Any + Send + 'static)) {
        if let Some(message) = payload.downcast_ref::<&str>() {
            write_stderr(format_args!("ffi panic: {message}"));
        } else if let Some(message) = payload.downcast_ref::<String>() {
            write_stderr(format_args!("ffi panic: {message}"));
        } else {
            write_stderr(format_args!("ffi panic: non-string payload"));
        }
    }
    /// Logs and destroys a caught panic payload without permitting a malicious
    /// payload destructor to unwind across the FFI boundary.
    pub fn handle_panic(payload: Box<dyn Any + Send + 'static>) {
        log_panic(payload.as_ref());
        if let Err(drop_panic) =
            std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| drop(payload)))
        {
            write_stderr(format_args!(
                "ffi panic: panic payload destructor also panicked"
            ));
            std::mem::forget(drop_panic);
        }
    }
    /// Logs an unexpected handle identifier observed on the FFI boundary.
    pub fn log_unknown_handle(handle_id: crate::handle::Id) {
        write_stderr(format_args!("ffi error: unknown handle id {handle_id}"));
    }
}
pub use option::OptionWithoutNicheRepr;
/// A specialized `Result` type for FFI operations
pub type Result<T> = core::result::Result<T, FfiReturn>;
#[doc = include_str!("lib_docs/handle.md")]
pub unsafe trait Handle {
    /// Unique identifier of the handle. Most commonly, it is
    /// used to facilitate generic monomorphization over FFI
    const ID: handle::Id;
}
#[doc = include_str!("lib_docs/repr_c.md")]
// NOTE: Type is `Copy` to indicate that there can be no ownership transfer
pub unsafe trait ReprC: Copy {}
/// A type that can be converted into some C type
pub trait FfiType {
    /// C type current type can be converted into
    type ReprC: ReprC;
}
/// Facilitates conversion of rust types to/from `ReprC` types.
pub trait FfiConvert<'itm, C: ReprC>: Sized {
    /// Type into which state can be stored during conversion from [`Self`]. Useful for
    /// returning owning heap allocated types or non-owning types that are not transmutable.
    /// Serves similar purpose as does context in a closure
    type RustStore: Default;
    /// Type into which state can be stored during conversion into [`Self`]. Useful for
    /// returning non-owning types that are not transmutable. Serves similar purpose as
    /// does context in a closure
    type FfiStore: Default;
    /// Perform the conversion from [`Self`] into `C`
    fn into_ffi(self, store: &'itm mut Self::RustStore) -> C;
    #[doc = include_str!("lib_docs/try_from_ffi.md")]
    unsafe fn try_from_ffi(source: C, store: &'itm mut Self::FfiStore) -> Result<Self>;
}
#[doc = include_str!("lib_docs/ffi_wrapper_type.md")]
pub trait FfiWrapperType {
    /// Type used instead of the input type in the wrapper function generated by `ffi_import`
    type InputType;
    /// Type used instead of the output type in the wrapper function generated by `ffi_import`
    type ReturnType;
}
/// Facilitates the use of [`Self`] as out-pointer.
pub trait FfiOutPtr: FfiType {
    /// Type of the out-pointer
    type OutPtr: ReprC;
}
/// Facilitates writing [`Self`] into `Self::OutPtr`.
pub trait FfiOutPtrWrite: FfiOutPtr {
    #[doc = include_str!("lib_docs/write_out.md")]
    unsafe fn write_out(self, out_ptr: *mut Self::OutPtr);
}
/// Facilitates reading from `Self::OutPtr` out-pointer.
pub trait FfiOutPtrRead: FfiOutPtr + Sized {
    #[doc = include_str!("lib_docs/try_read_out.md")]
    unsafe fn try_read_out(out_ptr: Self::OutPtr) -> Result<Self>;
}
#[doc = include_str!("lib_docs/local_ref.md")]
#[derive(Debug, PartialEq, Eq, PartialOrd, Ord)]
#[repr(transparent)]
pub struct LocalRef<'data, R>(R, core::marker::PhantomData<&'data ()>);
#[doc = include_str!("lib_docs/local_slice.md")]
#[derive(Debug, Default, PartialEq, Eq, PartialOrd, Ord)]
#[repr(transparent)]
pub struct LocalSlice<'data, R>(Box<[R]>, core::marker::PhantomData<&'data ()>);
/// Result of execution of an FFI function
#[derive(Debug, Display, Clone, Copy, PartialEq, Eq)]
#[repr(i8)]
pub enum FfiReturn {
    /// The input argument provided to FFI function can't be converted into inner rust representation.
    ConversionFailed = -6,
    /// The input argument provided to FFI function contains a trap representation.
    TrapRepresentation = -5,
    /// FFI function execution panicked.
    UnrecoverableError = -4,
    /// Provided handle id doesn't match any known handles.
    UnknownHandle = -3,
    /// FFI function failed during the execution of the wrapped method on the provided handle.
    ExecutionFail = -2,
    /// The input argument provided to FFI function is a null pointer.
    ArgIsNull = -1,
    /// FFI function executed successfully.
    Ok = 0,
}
/// Trait for converting Rust-side errors into [`FfiReturn`] codes when exporting
/// functions over FFI.
pub trait IntoFfiReturn {
    /// Convert the error into an [`FfiReturn`].
    fn into_ffi_return(self) -> FfiReturn;
}
impl IntoFfiReturn for FfiReturn {
    #[inline]
    fn into_ffi_return(self) -> FfiReturn {
        self
    }
}
impl IntoFfiReturn for () {
    #[inline]
    fn into_ffi_return(self) -> FfiReturn {
        FfiReturn::ExecutionFail
    }
}
impl IntoFfiReturn for core::convert::Infallible {
    #[inline]
    fn into_ffi_return(self) -> FfiReturn {
        match self {}
    }
}
impl IntoFfiReturn for &'static str {
    #[inline]
    fn into_ffi_return(self) -> FfiReturn {
        let _ = self;
        FfiReturn::ExecutionFail
    }
}
impl IntoFfiReturn for String {
    #[inline]
    fn into_ffi_return(self) -> FfiReturn {
        let _ = self;
        FfiReturn::ExecutionFail
    }
}
/// Trait for converting [`FfiReturn`] codes back into Rust error values when importing
/// functions over FFI.
pub trait FromFfiReturn: Sized {
    /// Construct an error value from an [`FfiReturn`] produced by the foreign function.
    fn from_ffi_return(code: FfiReturn) -> Self;
}
impl FromFfiReturn for FfiReturn {
    #[inline]
    fn from_ffi_return(code: FfiReturn) -> Self {
        code
    }
}
impl FromFfiReturn for () {
    #[inline]
    fn from_ffi_return(_: FfiReturn) -> Self {}
}
impl FromFfiReturn for &'static str {
    #[inline]
    fn from_ffi_return(_: FfiReturn) -> Self {
        ""
    }
}
impl FromFfiReturn for String {
    #[inline]
    fn from_ffi_return(code: FfiReturn) -> Self {
        format!("{code:?}")
    }
}
impl FromFfiReturn for u8 {
    #[inline]
    fn from_ffi_return(_: FfiReturn) -> Self {
        0
    }
}
impl FromFfiReturn for core::convert::Infallible {
    #[inline]
    fn from_ffi_return(_: FfiReturn) -> Self {
        unreachable!("FFI returned an error for an infallible result")
    }
}
#[doc = include_str!("lib_docs/ffi_type_macro.md")]
#[macro_export]
macro_rules! ffi_type {
    (impl $(<$($impl_generics: tt $(: $bounds: path)?),*>)? Robust for $ty: ty $(where $($where_ty:ty: $where_bound:path),* )? {} ) => {
        impl$(<$($impl_generics $(: $bounds)?),*>)? $crate::ir::Ir for $ty where Self: $crate::ReprC, $($($where_ty: $where_bound),*)? {
            type Type = $crate::ir::Robust;
        }

        // SAFETY: Robust type with a defined C representation by definition
        unsafe impl$(<$($impl_generics $(: $bounds)?),*>)? $crate::ir::InfallibleTransmute for $ty where Self: $crate::ReprC, $($($where_ty: $where_bound),*)? {}

        impl$(<$($impl_generics $(: $bounds)?),*>)? $crate::option::OptionIr for $ty where $($($where_ty: $where_bound),*)? {
            type Type = Option<$crate::option::WithoutNiche>;
        }

        impl<$($($impl_generics $(: $bounds)?),*)?> $crate::WrapperTypeOf<Self> for $ty where $($($where_ty: $where_bound),*)? {
            type Type = Self;
        }
    };
    (unsafe impl $(<$($impl_generics: tt $(: $bounds: path)?),*>)? Transparent for $ty: ty $(where $($where_ty:ty: $where_bound:path),* )? {
        type Target = $target:ty;

        validation_fn=unsafe {$validity_fn: expr},
        niche_value=$niche_value: expr
        $(,)?
    }) => {
        impl<$($($impl_generics $(: $bounds)?),*)?> $crate::ir::Ir for $ty where $($($where_ty: $where_bound),*)? {
            type Type = $crate::ir::Transparent;
        }

        // SAFETY: `$ty` is transmutable into `$target` and `is_valid` doesn't return false positives
        unsafe impl<$($($impl_generics $(: $bounds)?),*)?> $crate::ir::Transmute for $ty where $($($where_ty: $where_bound),*)? {
            type Target = $target;

            #[inline]
            #[allow(clippy::redundant_closure_call)]
            unsafe fn is_valid(target: &Self::Target) -> bool {
                $validity_fn(target)
            }
        }

        impl<$($($impl_generics $(: $bounds)?),*)?> $crate::option::Niche<'_> for $ty where $($($where_ty: $where_bound),*)? {
            const NICHE_VALUE: <$target as $crate::FfiType>::ReprC = $niche_value;
        }
    };
    (unsafe impl $(<$($impl_generics: tt $(: $bounds: path)?),*>)? Transparent for $ty: ty $(where $($where_ty:ty: $where_bound:path),* )? {
        type Target = $target:ty;
    } ) => {
        impl<$($($impl_generics $(: $bounds)?),*)?> $crate::ir::Ir for $ty where $($($where_ty: $where_bound),*)? {
            type Type = $crate::ir::Transparent;
        }

        // SAFETY: `$ty` is transmutable into `$target` and `is_valid` doesn't return false positives
        unsafe impl<$($($impl_generics $(: $bounds)?),*)?> $crate::ir::Transmute for $ty where $($($where_ty: $where_bound),*)? {
            type Target = $target;

            #[inline]
            unsafe fn is_valid(_: &Self::Target) -> bool {
                true
            }
        }

        // SAFETY: `$t` is robust with respect to `$target`
        unsafe impl<$($($impl_generics $(: $bounds)?),*)?> $crate::ir::InfallibleTransmute for $ty where $($($where_ty: $where_bound),*)? {}

        impl<'dummy, $($($impl_generics $(: $bounds)?),*)?> $crate::option::Niche<'dummy> for $ty where $target: $crate::option::Niche<'dummy>, $($($where_ty: $where_bound),*)? {
            const NICHE_VALUE: <$target as $crate::FfiType>::ReprC = <$target as $crate::option::Niche<'dummy>>::NICHE_VALUE;
        }

        impl<$($($impl_generics $(: $bounds)?),*)?> $crate::WrapperTypeOf<$ty> for $target where $($($where_ty: $where_bound),*)? {
            type Type = $ty;
        }
    };
}
/// Wrapper around struct/enum opaque pointer. When wrapped with the [`ffi`] macro in the
/// crate linking dynamically to some `cdylib` crate, it replaces struct/enum body definition
#[repr(C)]
// NOTE: Irrelevant for a type that is always behind a pointer
#[allow(missing_copy_implementations)]
pub struct Extern {
    __data: [u8; 0],

    // Required for !Send & !Sync & !Unpin.
    //
    // - `*mut u8` is !Send & !Sync. It must be in `PhantomData` to not
    //   affect alignment.
    //
    // - `PhantomPinned` is !Unpin. It must be in `PhantomData` because
    //   its memory representation is not considered FFI-safe.
    __marker: core::marker::PhantomData<(*mut u8, core::marker::PhantomPinned)>,
}
#[doc = include_str!("lib_docs/wrapper_type_of.md")]
pub trait WrapperTypeOf<T> {
    #[doc = include_str!("lib_docs/wrapper_return_type.md")]
    type Type;
}
impl<R> WrapperTypeOf<Self> for *const R {
    type Type = Self;
}
impl<R> WrapperTypeOf<Self> for *mut R {
    type Type = Self;
}
impl<'itm, T> WrapperTypeOf<&'itm T> for *const T {
    type Type = &'itm T;
}
impl<'itm, T> WrapperTypeOf<&'itm mut T> for *mut T {
    type Type = &'itm mut T;
}
impl<'itm, R: ?Sized, T: ?Sized> WrapperTypeOf<&'itm R> for &'itm T {
    type Type = &'itm R;
}
impl<'itm, R: ?Sized, T: ?Sized> WrapperTypeOf<&'itm mut R> for &'itm mut T {
    type Type = &'itm mut R;
}
impl<R, T> WrapperTypeOf<Box<R>> for Box<T> {
    type Type = Box<R>;
}
impl<R, T> WrapperTypeOf<Vec<R>> for Vec<T> {
    type Type = Vec<R>;
}
impl<R, T, const N: usize> WrapperTypeOf<[R; N]> for [T; N] {
    type Type = [R; N];
}
impl<R, T> WrapperTypeOf<Option<R>> for Option<T> {
    type Type = Option<R>;
}
impl<'itm, R, T> WrapperTypeOf<&'itm R> for LocalRef<'itm, T> {
    type Type = LocalRef<'itm, R>;
}
impl<'slice, R, T> WrapperTypeOf<&'slice [R]> for LocalSlice<'slice, T> {
    type Type = LocalSlice<'slice, R>;
}
// SAFETY: `LocalRef` is transparent and `R` is transmutable into `R::Target`
unsafe impl<'itm, R: Transmute> Transmute for LocalRef<'itm, R> {
    type Target = LocalRef<'itm, R::Target>;
    #[inline]
    unsafe fn is_valid(target: &Self::Target) -> bool {
        unsafe { R::is_valid(&target.0) }
    }
}
// SAFETY: `LocalSlice` is transparent and `R` is transmutable into `R::Target`
unsafe impl<'itm, R: Transmute> Transmute for LocalSlice<'itm, R> {
    type Target = LocalSlice<'itm, R::Target>;
    #[inline]
    unsafe fn is_valid(target: &Self::Target) -> bool {
        target.iter().all(|item| unsafe { R::is_valid(item) })
    }
}
impl<R> core::ops::Deref for LocalRef<'_, R> {
    type Target = R;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl<R> core::ops::Deref for LocalSlice<'_, R> {
    type Target = [R];
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
// SAFETY: `*const R` is robust with a defined C ABI regardless of whether `R` is
// When `R` is not `ReprC` the pointer is opaque; dereferencing is immediate UB
unsafe impl<R> ReprC for *const R {}
// SAFETY: `*mut R` is robust with a defined C ABI regardless of whether `R` is
// When `R` is not `ReprC` the pointer is opaque; dereferencing is immediate UB
unsafe impl<R> ReprC for *mut R {}
// SAFETY: `*mut R` is robust with a defined C ABI
unsafe impl<C: ReprC, const N: usize> ReprC for [C; N] {}
impl<R: Ir + CType<R::Type>> FfiType for R {
    type ReprC = <R as CType<R::Type>>::ReprC;
}
impl<'itm, R: Ir + CTypeConvert<'itm, R::Type, C>, C: ReprC> FfiConvert<'itm, C> for R {
    type RustStore = R::RustStore;
    type FfiStore = R::FfiStore;
    #[inline]
    fn into_ffi(self, store: &'itm mut Self::RustStore) -> C {
        self.into_repr_c(store)
    }
    #[inline]
    unsafe fn try_from_ffi(source: C, store: &'itm mut Self::FfiStore) -> Result<Self> {
        unsafe { R::try_from_repr_c(source, store) }
    }
}
impl FfiWrapperType for () {
    type InputType = ();
    type ReturnType = ();
}
impl<R: Ir + CWrapperType<R::Type>> FfiWrapperType for R {
    type InputType = R::InputType;
    type ReturnType = R::ReturnType;
}
impl<R: Ir + COutPtr<R::Type>> FfiOutPtr for R {
    type OutPtr = R::OutPtr;
}
impl<R: Ir + COutPtrWrite<R::Type>> FfiOutPtrWrite for R {
    unsafe fn write_out(self, out_ptr: *mut Self::OutPtr) {
        unsafe { R::write_out(self, out_ptr) };
    }
}
impl<R: Ir + COutPtrRead<R::Type>> FfiOutPtrRead for R {
    unsafe fn try_read_out(out_ptr: Self::OutPtr) -> Result<Self> {
        unsafe { R::try_read_out(out_ptr) }
    }
}
mod tuple_helpers {
    use crate::{FfiConvert, FfiOutPtrRead, FfiOutPtrWrite, ReprC, Result};
    use core::mem::MaybeUninit;
    #[inline]
    pub fn make_out_value<T>(value: T) -> T::OutPtr
    where
        T: FfiOutPtrWrite,
    {
        let mut slot = MaybeUninit::<T::OutPtr>::uninit();
        // SAFETY: `slot` is freshly allocated and will be fully initialized by `write_out`.
        unsafe {
            T::write_out(value, slot.as_mut_ptr());
            slot.assume_init()
        }
    }
    #[inline]
    pub fn read_out_value<T>(ptr: T::OutPtr) -> Result<T>
    where
        T: FfiOutPtrRead,
    {
        // SAFETY: caller guarantees `ptr` originated from a matching write operation.
        unsafe { T::try_read_out(ptr) }
    }
    #[inline]
    pub fn write_final_ptr<T>(ptr: *mut T, value: T) {
        // SAFETY: tuple writers obtain valid exclusive pointers from the caller.
        unsafe {
            ptr.write(value);
        }
    }
    /// Convert a single tuple element from its FFI representation.
    #[inline]
    pub fn convert_from_repr<'itm, T, C>(value: C, store: &'itm mut T::FfiStore) -> Result<T>
    where
        T: FfiConvert<'itm, C>,
        C: ReprC,
    {
        // SAFETY: callers guarantee the representation matches the element type.
        unsafe { T::try_from_ffi(value, store) }
    }
}
macro_rules! impl_tuple {
    ( ($( $ty:ident ),+) -> $ffi_ty:ident with ($($repr_c:ident),+) ) => {
        /// FFI-compatible tuple with n elements
        #[repr(C)]
        #[derive(Debug, Clone, Copy, Default, PartialEq, Eq, PartialOrd, Ord)]
        pub struct $ffi_ty<$($ty: ReprC),+>($(pub $ty),+);

        #[allow(non_snake_case)]
        impl<$($ty: $crate::ReprC),+> From<($( $ty, )+)> for $ffi_ty<$($ty),+> {
            fn from(source: ($( $ty, )+)) -> Self {
                let ($($ty,)+) = source;
                Self($( $ty ),+)
            }
        }

        // SAFETY: Implementing type is robust with a defined C ABI
        unsafe impl<$($ty: ReprC),+> ReprC for $ffi_ty<$($ty),+> {}

        impl<$($ty),+> $crate::ir::Ir for ($($ty,)+) {
            type Type = Self;
        }

        impl<$($ty: FfiType),+> $crate::repr_c::CType<Self> for ($($ty,)+) {
            type ReprC = $ffi_ty<$($ty::ReprC),+>;
        }
        impl<'itm, $($ty: FfiConvert<'itm, $repr_c>, $repr_c: $crate::ReprC),+> $crate::repr_c::CTypeConvert<'itm, Self, $ffi_ty<$($repr_c),+>> for ($($ty,)+) {
            type RustStore = ($( $ty::RustStore, )+);
            type FfiStore = ($( $ty::FfiStore, )+);

            #[allow(non_snake_case)]
            fn into_repr_c(self, store: &'itm mut Self::RustStore) -> $ffi_ty<$($repr_c),+> {
                impl_tuple! {@decl_priv_store $($ty),+ for RustStore with $($repr_c),+}

                let ($($ty,)+) = self;
                let store: private_store::Store<$($ty),+, $($repr_c),+> = store.into();
                $ffi_ty($( <$ty as FfiConvert<$repr_c>>::into_ffi($ty, store.$ty),)+)
            }
            #[allow(non_snake_case, clippy::missing_errors_doc, clippy::missing_safety_doc)]
            unsafe fn try_from_repr_c(source: $ffi_ty<$($repr_c),+>, store: &'itm mut Self::FfiStore) -> Result<Self> {
                impl_tuple! {@decl_priv_store $($ty),+ for FfiStore with $($repr_c),+}

                let $ffi_ty($($ty,)+) = source;
                let store: private_store::Store<$($ty),+, $($repr_c),+> = store.into();
                Ok(($( crate::tuple_helpers::convert_from_repr::<$ty, $repr_c>($ty, store.$ty)?, )+))
            }
        }

        impl<$($ty),+> CWrapperType<Self> for ($($ty,)+) {
            type InputType = Self;
            type ReturnType = Self;
        }
        impl<$($ty: FfiOutPtr),+> COutPtr<Self> for ($($ty,)+) {
            type OutPtr = $ffi_ty<$($ty::OutPtr),+>;
        }
        #[allow(non_snake_case)]
        impl<$($ty: FfiOutPtrWrite),+> COutPtrWrite<Self> for ($($ty,)+) {
            unsafe fn write_out(self, out_ptr: *mut Self::OutPtr) {
                let ($($ty,)+) = self;
                let value = $ffi_ty($( crate::tuple_helpers::make_out_value($ty), )+);
                crate::tuple_helpers::write_final_ptr(out_ptr, value);
            }
        }
        #[allow(non_snake_case)]
        impl<$($ty: FfiOutPtrRead),+> COutPtrRead<Self> for ($($ty,)+) {
            unsafe fn try_read_out(source: Self::OutPtr) -> Result<Self> {
                let $ffi_ty($($ty,)+) = source;
                Ok(($( crate::tuple_helpers::read_out_value($ty)?, )+))
            }
        }

        impl<$($ty),+> WrapperTypeOf<Self> for ($($ty,)+) {
            type Type = Self;
        }

        impl<$($ty),+> Cloned for ($($ty,)+) where Self: CType<Self> {}

        // SAFETY: Tuple doesn't use store if it's inner types don't use it
        unsafe impl<$($ty: Ir + NonLocal<$ty::Type>),+> NonLocal<Self> for ($($ty,)+) {}
    };

    // NOTE: This is a trick to index tuples
    ( @decl_priv_store $( $ty:ident ),+ for $store:ident with $($repr_c:ident),+ ) => {
        mod private_store {
            pub struct Store<'itm, $($ty: $crate::FfiConvert<'itm, $repr_c>),+, $($repr_c: $crate::ReprC),+> {
                $(pub $ty: &'itm mut $ty::$store),+
            }

            impl<'itm, $($ty: $crate::FfiConvert<'itm, $repr_c>),+, $($repr_c: $crate::ReprC),+> From<&'itm mut ($($ty::$store,)+)> for Store<'itm, $($ty,)+ $($repr_c),+> {
                fn from(($($ty,)+): &'itm mut ($($ty::$store,)+)) -> Self {
                    Self {$($ty,)+}
                }
            }
        }
    };
}
impl_tuple! {(A) -> FfiTuple1 with (C1)}
impl_tuple! {(A, B) -> FfiTuple2 with (C1, C2)}
impl_tuple! {(A, B, C) -> FfiTuple3 with (C1, C2, C3)}
impl_tuple! {(A, B, C, D) -> FfiTuple4 with (C1, C2, C3, C4)}
impl_tuple! {(A, B, C, D, E) -> FfiTuple5 with (C1, C2, C3, C4, C5)}
impl_tuple! {(A, B, C, D, E, F) -> FfiTuple6 with (C1, C2, C3, C4, C5, C6)}
impl_tuple! {(A, B, C, D, E, F, G) -> FfiTuple7 with (C1, C2, C3, C4, C5, C6, C7)}
impl_tuple! {(A, B, C, D, E, F, G, H) -> FfiTuple8 with (C1, C2, C3, C4, C5, C6, C7, C8)}
impl_tuple! {(A, B, C, D, E, F, G, H, I) -> FfiTuple9 with (C1, C2, C3, C4, C5, C6, C7, C8, C9)}
impl_tuple! {(A, B, C, D, E, F, G, H, I, J) -> FfiTuple10 with (C1, C2, C3, C4, C5, C6, C7, C8, C9, C10)}
impl_tuple! {(A, B, C, D, E, F, G, H, I, J, K) -> FfiTuple11 with (C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11)}
impl_tuple! {(A, B, C, D, E, F, G, H, I, J, K, L) -> FfiTuple12 with (C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11, C12)}
