//! Helpers for parsing SoraNet handshake messages.
//!
//! This module focuses on decoding the client-provided Noise XX `ClientHello`
//! frame so the relay can validate capability requirements before invoking the
//! full handshake engine (`iroha_crypto::soranet::handshake`).

use thiserror::Error;

/// Message type identifier for `ClientHello`.
pub const CLIENT_HELLO_TYPE: u8 = 0x01;
/// Padded frame length used by the Noise XX handshake.
pub const NOISE_PADDING_BLOCK: usize = 1024;
/// Maximum `ClientHello` frame length accepted by the relay (four padding blocks).
pub const MAX_CLIENT_HELLO_LEN: usize = NOISE_PADDING_BLOCK * 4;

const X25519_PUBLIC_LEN: usize = 32;

/// Parsed representation of the `ClientHello` handshake frame.
#[derive(Debug, Clone)]
pub struct ClientHello {
    nonce: Vec<u8>,
    kem_id: u8,
    sig_id: u8,
    ephemeral_public: [u8; X25519_PUBLIC_LEN],
    kem_public: Vec<u8>,
    raw_capabilities: Vec<u8>,
    resume_hash: Option<Vec<u8>>,
}

impl ClientHello {
    /// Parse a padded Noise XX `ClientHello` message produced by a SoraNet client.
    ///
    /// # Errors
    /// Returns an error if the frame uses an unexpected type identifier, is truncated,
    /// or if the embedded capability vector cannot be decoded.
    pub fn parse(frame: &[u8]) -> Result<Self, ClientHelloError> {
        if frame.is_empty() {
            return Err(ClientHelloError::EmptyFrame);
        }

        if frame[0] != CLIENT_HELLO_TYPE {
            return Err(ClientHelloError::UnexpectedType {
                expected: CLIENT_HELLO_TYPE,
                actual: frame[0],
            });
        }

        let mut cursor = 1usize;
        let nonce = take_len_prefixed(frame, &mut cursor, "client_nonce")?;
        let kem_id = take_byte(frame, &mut cursor, "kem_id")?;
        let sig_id = take_byte(frame, &mut cursor, "sig_id")?;
        let ephemeral_bytes =
            take_exact(frame, &mut cursor, X25519_PUBLIC_LEN, "client_ephemeral")?;
        let mut ephemeral_public = [0u8; X25519_PUBLIC_LEN];
        ephemeral_public.copy_from_slice(&ephemeral_bytes);

        let kem_public = take_len_prefixed(frame, &mut cursor, "client_kem_public")?;
        if kem_public.is_empty() {
            return Err(ClientHelloError::EmptyField("client_kem_public"));
        }
        let raw_capabilities = take_len_prefixed(frame, &mut cursor, "client_capabilities")?;
        if raw_capabilities.is_empty() {
            return Err(ClientHelloError::EmptyField("client_capabilities"));
        }

        let resume_flag = take_byte(frame, &mut cursor, "resume_flag")?;
        let resume_hash = match resume_flag {
            0 => None,
            1 => Some(take_len_prefixed(frame, &mut cursor, "resume_hash")?),
            other => return Err(ClientHelloError::InvalidResumeFlag(other)),
        };

        if frame[cursor..].iter().any(|&b| b != 0) {
            return Err(ClientHelloError::UnexpectedTrailingData);
        }

        Ok(Self {
            nonce,
            kem_id,
            sig_id,
            ephemeral_public,
            kem_public,
            raw_capabilities,
            resume_hash,
        })
    }

    /// Returns the random nonce generated by the client.
    pub fn nonce(&self) -> &[u8] {
        &self.nonce
    }

    /// Returns the negotiated ML-KEM identifier.
    pub fn kem_id(&self) -> u8 {
        self.kem_id
    }

    /// Returns the negotiated signature suite identifier.
    pub fn sig_id(&self) -> u8 {
        self.sig_id
    }

    /// Returns the client's Noise ephemeral public key.
    pub fn ephemeral_public(&self) -> &[u8; X25519_PUBLIC_LEN] {
        &self.ephemeral_public
    }

    /// Returns the client's ML-KEM public key commitment.
    pub fn kem_public(&self) -> &[u8] {
        &self.kem_public
    }

    /// Returns the raw capability TLV payload provided by the client.
    pub fn raw_capabilities(&self) -> &[u8] {
        &self.raw_capabilities
    }

    /// Returns the optional resume hash advertised by the client.
    pub fn resume_hash(&self) -> Option<&[u8]> {
        self.resume_hash.as_deref()
    }
}

/// Errors surfaced while decoding a `ClientHello` frame.
#[derive(Debug, Error)]
pub enum ClientHelloError {
    /// The payload did not include the expected type identifier.
    #[error("unexpected client hello type: expected {expected:#04x}, got {actual:#04x}")]
    UnexpectedType { expected: u8, actual: u8 },
    /// Encountered an unexpected end-of-frame while parsing a field.
    #[error("handshake frame truncated while reading {0}")]
    Truncated(&'static str),
    /// A variable-length field exceeded the advertised frame length.
    #[error("handshake field {0} exceeds available data")]
    LengthExceedsFrame(&'static str),
    /// The resume flag did not use a recognised value.
    #[error("invalid resume flag value {0:#04x}")]
    InvalidResumeFlag(u8),
    /// Non-zero padding bytes remained after parsing.
    #[error("unexpected non-zero padding at end of frame")]
    UnexpectedTrailingData,
    /// A required field was present but empty.
    #[error("field {0} must not be empty")]
    EmptyField(&'static str),
    /// No data was received.
    #[error("client hello frame is empty")]
    EmptyFrame,
}

fn take_byte(
    frame: &[u8],
    cursor: &mut usize,
    field: &'static str,
) -> Result<u8, ClientHelloError> {
    if *cursor >= frame.len() {
        return Err(ClientHelloError::Truncated(field));
    }
    let value = frame[*cursor];
    *cursor += 1;
    Ok(value)
}

fn take_exact(
    frame: &[u8],
    cursor: &mut usize,
    len: usize,
    field: &'static str,
) -> Result<Vec<u8>, ClientHelloError> {
    if frame.len() < *cursor + len {
        return Err(ClientHelloError::Truncated(field));
    }
    let slice = &frame[*cursor..*cursor + len];
    *cursor += len;
    Ok(slice.to_vec())
}

fn take_len_prefixed(
    frame: &[u8],
    cursor: &mut usize,
    field: &'static str,
) -> Result<Vec<u8>, ClientHelloError> {
    if frame.len() < *cursor + 2 {
        return Err(ClientHelloError::Truncated(field));
    }
    let len = u16::from_be_bytes([frame[*cursor], frame[*cursor + 1]]) as usize;
    *cursor += 2;
    if frame.len() < *cursor + len {
        return Err(ClientHelloError::LengthExceedsFrame(field));
    }
    let slice = &frame[*cursor..*cursor + len];
    *cursor += len;
    Ok(slice.to_vec())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn build_basic_client_hello() -> Vec<u8> {
        let mut frame = Vec::new();
        frame.push(CLIENT_HELLO_TYPE);

        frame.extend_from_slice(&(32u16.to_be_bytes()));
        frame.extend_from_slice(&[0xAA; 32]);

        frame.push(1);
        frame.push(1);

        frame.extend_from_slice(&[0x11; X25519_PUBLIC_LEN]);

        frame.extend_from_slice(&(4u16.to_be_bytes()));
        frame.extend_from_slice(&[0x01, 0x02, 0x03, 0x04]);

        frame.extend_from_slice(&0x0101u16.to_be_bytes());
        frame.extend_from_slice(&2u16.to_be_bytes());
        frame.extend_from_slice(&[0x80, 0x01]);

        frame.push(0);

        let rem = frame.len() % NOISE_PADDING_BLOCK;
        if rem != 0 {
            frame.resize(frame.len() + NOISE_PADDING_BLOCK - rem, 0);
        }

        frame
    }

    #[test]
    fn client_hello_manual_round_trip() {
        let frame = build_basic_client_hello();
        let hello = ClientHello::parse(&frame).expect("parse client hello");

        assert_eq!(hello.kem_id(), 1);
        assert_eq!(hello.sig_id(), 1);
        assert_eq!(hello.nonce(), &[0xAA; 32]);
        assert_eq!(hello.ephemeral_public(), &[0x11; X25519_PUBLIC_LEN]);
        assert_eq!(hello.kem_public(), &[0x01, 0x02, 0x03, 0x04]);
        assert!(hello.resume_hash().is_none());
    }

    #[test]
    fn invalid_type_rejected() {
        let mut frame = build_basic_client_hello();
        frame[0] = 0xFF;
        let err = ClientHello::parse(&frame).expect_err("should fail");
        assert!(matches!(
            err,
            ClientHelloError::UnexpectedType {
                expected: _,
                actual: _
            }
        ));
    }

    #[test]
    fn trailing_bytes_detected() {
        let mut frame = vec![0u8; NOISE_PADDING_BLOCK];
        frame[0] = CLIENT_HELLO_TYPE;
        frame[1] = 0;
        frame[2] = 32;
        for i in 0..32 {
            frame[3 + i] = i as u8;
        }
        let err = ClientHello::parse(&frame).expect_err("missing fields");
        assert!(matches!(
            err,
            ClientHelloError::EmptyField(_) | ClientHelloError::Truncated(_)
        ));
    }
}
