//! Per-hop fixed-interval cell scheduler for SoraNet constant-rate transport (SNNet-17A).
//!
//! This module implements the pacing layer that sits above QUIC congestion control,
//! ensuring traffic leaves the relay at a deterministic rate regardless of application
//! throughput. It enforces Weighted Fair Queuing (WFQ) across traffic classes and
//! generates dummy cells when queues are empty.
use crate::constant_rate::CONSTANT_RATE_CELL_BYTES;
use std::{
    collections::VecDeque,
    time::{Duration, Instant},
};
/// Fixed cell size used for constant-rate transport.
pub const CELL_SIZE_BYTES: usize = CONSTANT_RATE_CELL_BYTES as usize;
const CELL_HEADER_BYTES: usize = 3; // [Type (1B) | Length (2B)]
const MAX_PAYLOAD_BYTES: usize = CELL_SIZE_BYTES - CELL_HEADER_BYTES;
const CELL_TYPE_DUMMY: u8 = 0x00;
const CELL_TYPE_DATA: u8 = 0x01;
/// Traffic class for a cell, used for WFQ scheduling.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CellClass {
    /// Control plane traffic (highest priority, e.g. handshake, telemetry).
    Control,
    /// Interactive traffic (medium priority, e.g. Kaigi voice/video).
    Interactive,
    /// Bulk data transfer (lowest priority, e.g. SoraFS chunks).
    Bulk,
}
impl CellClass {
    /// Returns the scheduling weight for this class. Higher values mean more bandwidth share.
    fn weight(&self) -> u32 {
        match self {
            Self::Control => 8,
            Self::Interactive => 4,
            Self::Bulk => 1,
        }
    }
}
/// A fixed-size cell suitable for constant-rate transport.
#[derive(Debug, Clone)]
pub struct Cell {
    /// The traffic class of this cell.
    pub class: CellClass,
    /// The payload data. Must be <= `CONSTANT_RATE_CELL_BYTES`.
    /// If shorter, it will be padded to the fixed size.
    pub data: Vec<u8>,
    /// Whether this is a dummy cell generated by the scheduler.
    pub is_dummy: bool,
}
impl Cell {
    /// Create a new data cell. Panics if `data` exceeds the cell size limit.
    pub fn new(class: CellClass, data: Vec<u8>) -> Self {
        assert!(
            data.len() <= MAX_PAYLOAD_BYTES,
            "cell data exceeds payload limit ({}B > {}B)",
            data.len(),
            MAX_PAYLOAD_BYTES
        );
        Self {
            class,
            data,
            is_dummy: false,
        }
    }
    /// Create a dummy cell that carries no payload.
    pub fn dummy() -> Self {
        Self {
            class: CellClass::Bulk, // Dummy cells count toward bulk stats
            data: Vec::new(),
            is_dummy: true,
        }
    }
    /// Serialize the cell into a fixed-size byte buffer with a deterministic envelope.
    ///
    /// Layout: `[Type (1B) | Length (2B) | Payload | Padding]`
    /// where `Length` is big-endian, `Payload + Padding = MAX_PAYLOAD_BYTES`,
    /// and every padding byte is the canonical zero value.
    pub fn to_bytes(&self) -> Vec<u8> {
        let mut buf = vec![0u8; CELL_SIZE_BYTES];
        let (payload_len, cell_type) = if self.is_dummy {
            (0usize, CELL_TYPE_DUMMY)
        } else {
            (self.data.len(), CELL_TYPE_DATA)
        };
        buf[0] = cell_type;
        buf[1..CELL_HEADER_BYTES].copy_from_slice(&(payload_len as u16).to_be_bytes());
        if payload_len > 0 {
            buf[CELL_HEADER_BYTES..CELL_HEADER_BYTES + payload_len]
                .copy_from_slice(&self.data[..payload_len]);
        }
        buf
    }
    /// Parse a cell from a raw byte buffer, rejecting non-canonical non-zero padding.
    pub fn from_bytes(raw: &[u8], class: CellClass) -> Option<Self> {
        if raw.len() != CELL_SIZE_BYTES {
            return None;
        }
        let ty = raw[0];
        let payload_len = u16::from_be_bytes([raw[1], raw[2]]) as usize;
        if payload_len > MAX_PAYLOAD_BYTES {
            return None;
        }
        let payload_end = CELL_HEADER_BYTES + payload_len;
        if raw[payload_end..].iter().any(|byte| *byte != 0) {
            return None;
        }
        let is_dummy = ty == CELL_TYPE_DUMMY;
        if is_dummy {
            if payload_len != 0 {
                return None;
            }
            return Some(Self {
                class: CellClass::Bulk,
                data: Vec::new(),
                is_dummy: true,
            });
        }
        if ty != CELL_TYPE_DATA {
            return None;
        }
        let mut data = Vec::with_capacity(payload_len);
        data.extend_from_slice(&raw[CELL_HEADER_BYTES..payload_end]);
        Some(Self {
            class,
            data,
            is_dummy: false,
        })
    }
}
/// Fragment a message into multiple cells of the given class.
/// If the message is empty, returns an empty vector.
pub fn fragment_message(class: CellClass, message: &[u8]) -> Vec<Cell> {
    if message.is_empty() {
        return Vec::new();
    }
    message
        .chunks(MAX_PAYLOAD_BYTES)
        .map(|chunk| Cell::new(class, chunk.to_vec()))
        .collect()
}
/// Deterministic overflow policy for the scheduler.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OverflowPolicy {
    /// Drop the oldest item in the queue (tail drop / ring buffer).
    DropOldest,
    /// Reject new items (head drop).
    RejectNew,
}
/// Configuration for the cell scheduler.
#[derive(Debug, Clone)]
pub struct SchedulerConfig {
    /// Target tick duration (interval between cell emissions).
    pub tick_duration: Duration,
    /// Maximum queue depth per class.
    pub queue_capacity: usize,
    /// Overflow policy to apply when queues are full.
    pub overflow_policy: OverflowPolicy,
}
impl Default for SchedulerConfig {
    fn default() -> Self {
        Self {
            tick_duration: Duration::from_millis(20), // 50 Hz
            queue_capacity: 1024,
            overflow_policy: OverflowPolicy::DropOldest,
        }
    }
}
/// Snapshot of queue depths for each class.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct QueueDepths {
    pub control: usize,
    pub interactive: usize,
    pub bulk: usize,
}
impl QueueDepths {
    /// Returns the total number of queued cells across all classes.
    pub fn total(&self) -> usize {
        self.control + self.interactive + self.bulk
    }
}
/// The per-hop fixed-interval sender.
#[derive(Debug)]
pub struct CellScheduler {
    config: SchedulerConfig,
    queues: [VecDeque<Cell>; 3], // Indexed by class ordinal
    last_tick: Instant,
    deficit: [i32; 3], // Smooth weighted round-robin current weights
}
impl CellScheduler {
    /// Create a new scheduler with the given configuration.
    pub fn new(config: SchedulerConfig) -> Self {
        Self {
            config,
            queues: [VecDeque::new(), VecDeque::new(), VecDeque::new()],
            last_tick: Instant::now(),
            deficit: [0; 3],
        }
    }
    /// Enqueue a cell for transmission.
    /// Returns `true` if successful, `false` if rejected (under `RejectNew` policy).
    pub fn enqueue(&mut self, cell: Cell) -> bool {
        let class_idx = self.class_index(cell.class);
        let queue = &mut self.queues[class_idx];
        if queue.len() >= self.config.queue_capacity {
            match self.config.overflow_policy {
                OverflowPolicy::DropOldest => {
                    queue.pop_front(); // Drop oldest to make room
                }
                OverflowPolicy::RejectNew => return false,
            }
        }
        queue.push_back(cell);
        true
    }
    /// Poll the scheduler for the next cell to send.
    ///
    /// This function should be called periodically (e.g. in an event loop).
    /// It returns `Some(Cell)` if a tick has elapsed, or `None` if it's too early.
    /// If no data is available when a tick occurs, a dummy cell is returned.
    pub fn poll(&mut self, now: Instant) -> Option<Cell> {
        if now.duration_since(self.last_tick) < self.config.tick_duration {
            return None;
        }
        self.last_tick = now;
        Some(self.select_next_cell())
    }
    /// Force a tick immediately (useful for tests or flushing).
    pub fn force_tick(&mut self) -> Cell {
        self.last_tick = Instant::now();
        self.select_next_cell()
    }
    /// Drop the oldest enqueued cell from the lowest-priority class.
    ///
    /// Returns the class that was dropped when a cell was removed.
    pub fn drop_lowest_priority(&mut self) -> Option<CellClass> {
        let priorities = [CellClass::Bulk, CellClass::Interactive, CellClass::Control];
        for class in priorities {
            let idx = self.class_index(class);
            if self.queues[idx].is_empty() {
                self.deficit[idx] = 0;
                continue;
            }
            let dropped = self.queues[idx].pop_front().map(|_| class);
            if self.queues[idx].is_empty() {
                self.deficit[idx] = 0;
            }
            if dropped.is_some() {
                return dropped;
            }
        }
        None
    }
    /// Returns the queue depths per class.
    pub fn queue_depths(&self) -> QueueDepths {
        QueueDepths {
            control: self.queues[self.class_index(CellClass::Control)].len(),
            interactive: self.queues[self.class_index(CellClass::Interactive)].len(),
            bulk: self.queues[self.class_index(CellClass::Bulk)].len(),
        }
    }
    fn select_next_cell(&mut self) -> Cell {
        let classes = [CellClass::Control, CellClass::Interactive, CellClass::Bulk];
        let mut active_weight = 0_i32;
        let mut selected = None;

        // All cells have the same wire size, so smooth weighted round-robin is
        // equivalent to weighted fair queuing here. Accruing each active
        // class's weight and charging the winner the total active weight keeps
        // the scheduler work-conserving without letting the fixed scan order
        // starve lower-weight classes.
        for (idx, class) in classes.iter().enumerate() {
            if self.queues[idx].is_empty() {
                self.deficit[idx] = 0;
                continue;
            }

            let weight = class.weight() as i32;
            active_weight += weight;
            self.deficit[idx] += weight;
            if selected.is_none_or(|winner| self.deficit[idx] > self.deficit[winner]) {
                selected = Some(idx);
            }
        }

        let Some(selected) = selected else {
            return Cell::dummy();
        };
        self.deficit[selected] -= active_weight;
        let Some(cell) = self.queues[selected].pop_front() else {
            self.deficit[selected] = 0;
            return Cell::dummy();
        };
        if self.queues[selected].is_empty() {
            self.deficit[selected] = 0;
        }
        cell
    }
    fn class_index(&self, class: CellClass) -> usize {
        match class {
            CellClass::Control => 0,
            CellClass::Interactive => 1,
            CellClass::Bulk => 2,
        }
    }
}
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn scheduler_emits_dummies_when_empty() {
        let mut scheduler = CellScheduler::new(SchedulerConfig::default());
        let cell = scheduler.force_tick();
        assert!(cell.is_dummy);
        assert!(cell.data.is_empty());
        assert_eq!(cell.to_bytes().len(), CELL_SIZE_BYTES);
    }
    #[test]
    fn dummy_round_trip_is_lossless() {
        let dummy = Cell::dummy();
        let bytes = dummy.to_bytes();
        let parsed = Cell::from_bytes(&bytes, CellClass::Bulk).expect("parse dummy");
        assert!(parsed.is_dummy);
        assert!(parsed.data.is_empty());
    }
    #[test]
    fn cell_serialization_round_trip() {
        let original = Cell::new(CellClass::Interactive, vec![0xAA, 0xBB, 0xCC]);
        let bytes = original.to_bytes();
        assert_eq!(bytes.len(), CELL_SIZE_BYTES);
        let parsed = Cell::from_bytes(&bytes, CellClass::Interactive).expect("parse");
        assert!(!parsed.is_dummy);
        assert_eq!(parsed.data, vec![0xAA, 0xBB, 0xCC]);
    }
    #[test]
    fn fragmentation_splits_large_payloads() {
        let large_data = vec![0xDD; MAX_PAYLOAD_BYTES + 10];
        let cells = fragment_message(CellClass::Bulk, &large_data);
        assert_eq!(cells.len(), 2);
        assert_eq!(cells[0].data.len(), MAX_PAYLOAD_BYTES);
        assert_eq!(cells[1].data.len(), 10);
        // Check content
        assert!(cells[0].data.iter().all(|&b| b == 0xDD));
        assert!(cells[1].data.iter().all(|&b| b == 0xDD));
    }
    #[test]
    fn scheduler_respects_weights() {
        let mut scheduler = CellScheduler::new(SchedulerConfig::default());
        for _ in 0..9 {
            scheduler.enqueue(Cell::new(CellClass::Bulk, vec![0xBB]));
            scheduler.enqueue(Cell::new(CellClass::Control, vec![0xCC]));
        }
        let mut c_count = 0;
        let mut b_count = 0;
        for _ in 0..9 {
            let c = scheduler.force_tick();
            assert!(!c.is_dummy, "queued data must take precedence over cover");
            match c.class {
                CellClass::Control => c_count += 1,
                CellClass::Bulk => b_count += 1,
                CellClass::Interactive => unreachable!("interactive queue is empty"),
            }
        }
        assert_eq!((c_count, b_count), (8, 1));
    }
    #[test]
    fn sustained_higher_priority_backlog_does_not_starve_other_classes() {
        let mut scheduler = CellScheduler::new(SchedulerConfig::default());
        for _ in 0..13 {
            scheduler.enqueue(Cell::new(CellClass::Control, vec![0xCC]));
            scheduler.enqueue(Cell::new(CellClass::Interactive, vec![0x11]));
            scheduler.enqueue(Cell::new(CellClass::Bulk, vec![0xBB]));
        }

        let mut counts = [0_u8; 3];
        for _ in 0..13 {
            let cell = scheduler.force_tick();
            assert!(
                !cell.is_dummy,
                "queued data must take precedence over cover"
            );
            counts[scheduler.class_index(cell.class)] += 1;
        }

        assert_eq!(counts, [8, 4, 1], "scheduler must honor the 8:4:1 weights");
    }
    #[test]
    fn scheduler_dequeue_path_clears_drained_positive_deficit_queue() {
        let mut scheduler = CellScheduler::new(SchedulerConfig::default());
        let bulk_idx = scheduler.class_index(CellClass::Bulk);
        scheduler.enqueue(Cell::new(CellClass::Bulk, vec![0xAA]));
        scheduler.deficit[bulk_idx] = 3;
        let cell = scheduler.force_tick();
        assert!(!cell.is_dummy);
        assert_eq!(cell.class, CellClass::Bulk);
        assert_eq!(cell.data, vec![0xAA]);
        let dummy = scheduler.force_tick();
        assert!(dummy.is_dummy);
        assert_eq!(scheduler.deficit[bulk_idx], 0);
    }
    #[test]
    fn overflow_policy_reject_new() {
        let config = SchedulerConfig {
            queue_capacity: 2,
            overflow_policy: OverflowPolicy::RejectNew,
            ..Default::default()
        };
        let mut scheduler = CellScheduler::new(config);
        assert!(scheduler.enqueue(Cell::new(CellClass::Bulk, vec![1])));
        assert!(scheduler.enqueue(Cell::new(CellClass::Bulk, vec![2])));
        assert!(!scheduler.enqueue(Cell::new(CellClass::Bulk, vec![3]))); // Rejected
        let c1 = scheduler.force_tick();
        assert_eq!(c1.data[0], 1);
        let c2 = scheduler.force_tick();
        assert_eq!(c2.data[0], 2);
    }
    #[test]
    fn overflow_policy_drop_oldest() {
        let config = SchedulerConfig {
            queue_capacity: 2,
            overflow_policy: OverflowPolicy::DropOldest,
            ..Default::default()
        };
        let mut scheduler = CellScheduler::new(config);
        assert!(scheduler.enqueue(Cell::new(CellClass::Bulk, vec![1])));
        assert!(scheduler.enqueue(Cell::new(CellClass::Bulk, vec![2])));
        assert!(scheduler.enqueue(Cell::new(CellClass::Bulk, vec![3]))); // Should drop 1
        let c1 = scheduler.force_tick();
        assert_eq!(c1.data[0], 2); // 1 was dropped
        let c2 = scheduler.force_tick();
        assert_eq!(c2.data[0], 3);
    }
    #[test]
    fn rejecting_invalid_payload_lengths() {
        let mut raw = vec![0u8; CELL_SIZE_BYTES];
        raw[0] = CELL_TYPE_DATA;
        let invalid_len = (MAX_PAYLOAD_BYTES + 1) as u16;
        raw[1..CELL_HEADER_BYTES].copy_from_slice(&invalid_len.to_be_bytes());
        assert!(Cell::from_bytes(&raw, CellClass::Bulk).is_none());
        // Dummy frames must never claim payload bytes.
        let mut dummy = vec![0u8; CELL_SIZE_BYTES];
        dummy[0] = CELL_TYPE_DUMMY;
        dummy[1..CELL_HEADER_BYTES].copy_from_slice(&1u16.to_be_bytes());
        assert!(Cell::from_bytes(&dummy, CellClass::Bulk).is_none());
    }
    #[test]
    fn rejecting_nonzero_padding_bytes() {
        let mut data = Cell::new(CellClass::Bulk, vec![0xAB]).to_bytes();
        data[CELL_HEADER_BYTES + 1] = 0x01;
        assert!(Cell::from_bytes(&data, CellClass::Bulk).is_none());

        let mut dummy = Cell::dummy().to_bytes();
        dummy[CELL_HEADER_BYTES] = 0x01;
        assert!(Cell::from_bytes(&dummy, CellClass::Bulk).is_none());
    }
    #[test]
    fn queue_depths_reflect_per_class_enqueues() {
        let mut scheduler = CellScheduler::new(SchedulerConfig {
            queue_capacity: 4,
            ..Default::default()
        });
        assert_eq!(
            scheduler.queue_depths(),
            QueueDepths {
                control: 0,
                interactive: 0,
                bulk: 0
            }
        );
        scheduler.enqueue(Cell::new(CellClass::Control, vec![1]));
        scheduler.enqueue(Cell::new(CellClass::Interactive, vec![2]));
        scheduler.enqueue(Cell::new(CellClass::Bulk, vec![3]));
        let depths = scheduler.queue_depths();
        assert_eq!(depths.control, 1);
        assert_eq!(depths.interactive, 1);
        assert_eq!(depths.bulk, 1);
        assert_eq!(depths.total(), 3);
    }
    #[test]
    fn drop_lowest_priority_prefers_bulk() {
        let mut scheduler = CellScheduler::new(SchedulerConfig {
            queue_capacity: 4,
            ..Default::default()
        });
        scheduler.enqueue(Cell::new(CellClass::Control, vec![0x01]));
        scheduler.enqueue(Cell::new(CellClass::Interactive, vec![0x02]));
        scheduler.enqueue(Cell::new(CellClass::Bulk, vec![0x03]));
        let dropped = scheduler.drop_lowest_priority();
        assert_eq!(dropped, Some(CellClass::Bulk));
        let depths = scheduler.queue_depths();
        assert_eq!(depths.bulk, 0);
        assert_eq!(depths.interactive, 1);
        assert_eq!(depths.control, 1);
    }
    #[test]
    fn drop_lowest_priority_cleans_deficit() {
        let mut scheduler = CellScheduler::new(SchedulerConfig {
            queue_capacity: 2,
            ..Default::default()
        });
        scheduler.enqueue(Cell::new(CellClass::Bulk, vec![0xAA]));
        scheduler.deficit[scheduler.class_index(CellClass::Bulk)] = 3;
        let dropped = scheduler.drop_lowest_priority();
        assert_eq!(dropped, Some(CellClass::Bulk));
        assert_eq!(scheduler.queue_depths().bulk, 0);
        // Dropping should also reset deficit to avoid stale positive credits on empty queues.
        assert_eq!(scheduler.deficit[scheduler.class_index(CellClass::Bulk)], 0);
        // With no queued cells there is nothing to drop.
        assert!(scheduler.drop_lowest_priority().is_none());
    }
}
