//! Explicit wire identifiers for the built-in instruction registry.
use super::*;
use crate::isi::offline_cash_v1;
#[cfg(test)]
type TypeName = fn() -> &'static str;
/// One built-in instruction's Rust type and path-independent wire identity.
#[derive(Clone, Copy)]
pub(super) struct BuiltInWireId {
    #[cfg(test)]
    pub(super) type_label: &'static str,
    #[cfg(test)]
    pub(super) type_name: TypeName,
    #[cfg(test)]
    pub(super) wire_id: &'static str,
    #[cfg(test)]
    pub(super) governance_only: bool,
    register: Registrar,
}
macro_rules! built_in_wire_id_with_scope {
    ($ty:ty => $wire_id:literal, governance_only = $governance_only:literal, register = $register:expr) => {
        BuiltInWireId {
            #[cfg(test)]
            type_label: stringify!($ty),
            #[cfg(test)]
            type_name: std::any::type_name::<$ty>,
            #[cfg(test)]
            wire_id: $wire_id,
            #[cfg(test)]
            governance_only: $governance_only,
            register: $register,
        }
    };
}
macro_rules! built_in_wire_id {
    ($ty:ty => $wire_id:literal) => {
        built_in_wire_id_with_scope!(
            $ty => $wire_id,
            governance_only = false,
            register = |registry| registry.register_with_id_slice::<$ty>($wire_id)
        )
    };
    ($ty:ty => $wire_id:literal, register) => {
        built_in_wire_id_with_scope!(
            $ty => $wire_id,
            governance_only = false,
            register = |registry| registry.register_with_id::<$ty>($wire_id)
        )
    };
}
#[cfg(feature = "governance")]
macro_rules! governance_wire_id {
    ($ty:ty => $wire_id:literal) => {
        built_in_wire_id_with_scope!(
            $ty => $wire_id,
            governance_only = true,
            register = |registry| registry.register_with_id_slice::<$ty>($wire_id)
        )
    };
}
/// Complete canonical wire-ID inventory for built-in instructions.
pub(super) const ALL: &[BuiltInWireId] = &[
    built_in_wire_id!(RegisterBox => "iroha.register"),
    built_in_wire_id!(UnregisterBox => "iroha.unregister"),
    built_in_wire_id!(MintBox => "iroha.mint"),
    built_in_wire_id!(BurnBox => "iroha.burn"),
    built_in_wire_id!(TransferAssetBatch => "iroha.transfer_batch"),
    built_in_wire_id!(TransferBox => "iroha.transfer"),
    built_in_wire_id!(asset_transfer_control::SetAssetTransferAvailability => "iroha.asset.transfer.availability.set"),
    built_in_wire_id!(asset_transfer_control::SetAssetTransferBlacklist => "iroha.asset.transfer.blacklist.set"),
    built_in_wire_id!(asset_transfer_control::SetAssetTransferControl => "iroha.asset.transfer.control.set"),
    built_in_wire_id!(asset_transfer_control::SetAssetHoldingLimit => "iroha.asset.holding_limit.set"),
    built_in_wire_id!(rwa::RwaInstructionBox => "iroha.rwa"),
    built_in_wire_id!(defi::DeFiInstructionBox => "iroha.defi", register),
    built_in_wire_id!(repo::RepoInstructionBox => "iroha.repo"),
    built_in_wire_id!(settlement::SettlementInstructionBox => "iroha.settlement"),
    built_in_wire_id!(SetParameter => "iroha.set_parameter"),
    built_in_wire_id!(SetKeyValueBox => "iroha.set_key_value"),
    built_in_wire_id!(AddSignatory => "iroha.instruction.v1::transparent::AddSignatory"),
    built_in_wire_id!(RemoveSignatory => "iroha.instruction.v1::transparent::RemoveSignatory"),
    built_in_wire_id!(SetAccountQuorum => "iroha.instruction.v1::transparent::SetAccountQuorum"),
    built_in_wire_id!(SetAssetKeyValue => "iroha.instruction.v1::transparent::SetAssetKeyValue"),
    built_in_wire_id!(RemoveKeyValueBox => "iroha.remove_key_value"),
    built_in_wire_id!(RemoveAssetKeyValue => "iroha.instruction.v1::transparent::RemoveAssetKeyValue"),
    built_in_wire_id!(GrantBox => "iroha.grant"),
    built_in_wire_id!(RevokeBox => "iroha.revoke"),
    built_in_wire_id!(offline_cash_v1::TopUpOfflineCashV1 => "iroha.offline_cash.v1.top_up", register),
    built_in_wire_id!(offline_cash_v1::RedeemOfflineCashV1 => "iroha.offline_cash.v1.redeem", register),
    built_in_wire_id!(crate::isi::staking::RegisterPublicLaneValidator => "iroha.instruction.v1::staking::RegisterPublicLaneValidator"),
    built_in_wire_id!(crate::isi::staking::RebindPublicLaneValidatorPeer => "iroha.staking.rebind_public_lane_validator_peer"),
    built_in_wire_id!(crate::isi::staking::ActivatePublicLaneValidator => "iroha.staking.activate_public_lane_validator"),
    built_in_wire_id!(crate::isi::staking::ExitPublicLaneValidator => "iroha.staking.exit_public_lane_validator"),
    built_in_wire_id!(crate::isi::staking::BondPublicLaneStake => "iroha.instruction.v1::staking::BondPublicLaneStake", register),
    built_in_wire_id!(crate::isi::staking::SchedulePublicLaneUnbond => "iroha.instruction.v1::staking::SchedulePublicLaneUnbond", register),
    built_in_wire_id!(crate::isi::staking::FinalizePublicLaneUnbond => "iroha.instruction.v1::staking::FinalizePublicLaneUnbond", register),
    built_in_wire_id!(crate::isi::staking::SlashPublicLaneValidator => "iroha.instruction.v1::staking::SlashPublicLaneValidator", register),
    built_in_wire_id!(crate::isi::staking::CancelConsensusEvidencePenalty => "iroha.instruction.v1::staking::CancelConsensusEvidencePenalty"),
    built_in_wire_id!(crate::isi::staking::RecordPublicLaneRewards => "iroha.instruction.v1::staking::RecordPublicLaneRewards", register),
    built_in_wire_id!(crate::isi::staking::ClaimPublicLaneRewards => "iroha.instruction.v1::staking::ClaimPublicLaneRewards", register),
    built_in_wire_id!(nexus::SetLaneRelayEmergencyValidators => "nexus::SetLaneRelayEmergencyValidators"),
    built_in_wire_id!(nexus::RegisterVerifiedLaneRelay => "nexus::RegisterVerifiedLaneRelay"),
    built_in_wire_id!(nexus::RegisterVerifiedFeeSponsorVaultAllocation => "nexus::RegisterVerifiedFeeSponsorVaultAllocation"),
    built_in_wire_id!(nexus::CreateFeeSponsorProgram => "nexus::CreateFeeSponsorProgram"),
    built_in_wire_id!(nexus::StageFeeSponsorProgramRevision => "nexus::StageFeeSponsorProgramRevision"),
    built_in_wire_id!(nexus::ActivateFeeSponsorProgramRevision => "nexus::ActivateFeeSponsorProgramRevision"),
    built_in_wire_id!(nexus::PauseFeeSponsorProgram => "nexus::PauseFeeSponsorProgram"),
    built_in_wire_id!(nexus::BeginCloseFeeSponsorProgram => "nexus::BeginCloseFeeSponsorProgram"),
    built_in_wire_id!(nexus::CloseFeeSponsorProgram => "nexus::CloseFeeSponsorProgram"),
    built_in_wire_id!(nexus::EnrollFeeSponsorBeneficiary => "nexus::EnrollFeeSponsorBeneficiary"),
    built_in_wire_id!(nexus::UnenrollFeeSponsorBeneficiary => "nexus::UnenrollFeeSponsorBeneficiary"),
    built_in_wire_id!(nexus::FundFeeSponsorProgram => "nexus::FundFeeSponsorProgram"),
    built_in_wire_id!(nexus::WithdrawFeeSponsorProgram => "nexus::WithdrawFeeSponsorProgram"),
    built_in_wire_id!(bridge::ApplySccpRouteGovernance => "iroha.instruction.v1::bridge::ApplySccpRouteGovernance"),
    built_in_wire_id!(bridge::SubmitSccpTonBreakerObservationV1 => "iroha.instruction.v1::bridge::SubmitSccpTonBreakerObservationV1"),
    built_in_wire_id!(oracle::RegisterOracleFeed => "iroha.instruction.v1::oracle::RegisterOracleFeed"),
    built_in_wire_id!(oracle::SubmitOracleObservation => "iroha.instruction.v1::oracle::SubmitOracleObservation"),
    built_in_wire_id!(oracle::AggregateOracleFeed => "iroha.instruction.v1::oracle::AggregateOracleFeed"),
    built_in_wire_id!(oracle::OpenOracleDispute => "iroha.instruction.v1::oracle::OpenOracleDispute"),
    built_in_wire_id!(oracle::ResolveOracleDispute => "iroha.instruction.v1::oracle::ResolveOracleDispute"),
    built_in_wire_id!(oracle::ProposeOracleChange => "iroha.instruction.v1::oracle::ProposeOracleChange"),
    built_in_wire_id!(oracle::VoteOracleChangeStage => "iroha.instruction.v1::oracle::VoteOracleChangeStage"),
    built_in_wire_id!(oracle::RollbackOracleChange => "iroha.instruction.v1::oracle::RollbackOracleChange"),
    built_in_wire_id!(oracle::SubmitDefiOracleAttestation => "iroha.instruction.v1::oracle::SubmitDefiOracleAttestation"),
    built_in_wire_id!(oracle::RecordTwitterBinding => "iroha.instruction.v1::oracle::RecordTwitterBinding"),
    built_in_wire_id!(oracle::RevokeTwitterBinding => "iroha.instruction.v1::oracle::RevokeTwitterBinding"),
    built_in_wire_id!(social::ClaimTwitterFollowReward => "iroha.instruction.v1::social::ClaimTwitterFollowReward"),
    built_in_wire_id!(social::SendToTwitter => "iroha.instruction.v1::social::SendToTwitter"),
    built_in_wire_id!(social::CancelTwitterEscrow => "iroha.instruction.v1::social::CancelTwitterEscrow"),
    built_in_wire_id!(escrow::OpenAssetEscrow => "iroha.instruction.v1::escrow::OpenAssetEscrow"),
    built_in_wire_id!(escrow::AcceptAssetEscrow => "iroha.instruction.v1::escrow::AcceptAssetEscrow"),
    built_in_wire_id!(escrow::MarkEscrowPaymentSent => "iroha.instruction.v1::escrow::MarkEscrowPaymentSent"),
    built_in_wire_id!(escrow::ReleaseAssetEscrow => "iroha.instruction.v1::escrow::ReleaseAssetEscrow"),
    built_in_wire_id!(escrow::CancelAssetEscrow => "iroha.instruction.v1::escrow::CancelAssetEscrow"),
    built_in_wire_id!(escrow::OpenEscrowDispute => "iroha.instruction.v1::escrow::OpenEscrowDispute"),
    built_in_wire_id!(escrow::ResolveEscrowDispute => "iroha.instruction.v1::escrow::ResolveEscrowDispute"),
    built_in_wire_id!(escrow::OpenAssetLock => "iroha.instruction.v1::escrow::OpenAssetLock"),
    built_in_wire_id!(escrow::OpenConditionalEscrow => "iroha.instruction.v1::escrow::OpenConditionalEscrow"),
    built_in_wire_id!(escrow::AttestEscrowCondition => "iroha.instruction.v1::escrow::AttestEscrowCondition"),
    built_in_wire_id!(escrow::ExpireConditionalEscrow => "iroha.instruction.v1::escrow::ExpireConditionalEscrow"),
    built_in_wire_id!(escrow::DrawdownAssetLock => "iroha.instruction.v1::escrow::DrawdownAssetLock"),
    built_in_wire_id!(escrow::CancelAssetLock => "iroha.instruction.v1::escrow::CancelAssetLock"),
    built_in_wire_id!(escrow::ExpireAssetLock => "iroha.instruction.v1::escrow::ExpireAssetLock"),
    built_in_wire_id!(vpn::OpenVpnLeaseEscrow => "iroha.instruction.v1::vpn::OpenVpnLeaseEscrow"),
    built_in_wire_id!(vpn::SettleVpnLease => "iroha.instruction.v1::vpn::SettleVpnLease"),
    built_in_wire_id!(vpn::RefundExpiredVpnLease => "iroha.instruction.v1::vpn::RefundExpiredVpnLease"),
    built_in_wire_id!(soracloud::DeploySoracloudService => "soracloud::DeploySoracloudService"),
    built_in_wire_id!(soracloud::UpgradeSoracloudService => "soracloud::UpgradeSoracloudService"),
    built_in_wire_id!(soracloud::DeploySoracloudAppInfra => "iroha.instruction.v1::soracloud::DeploySoracloudAppInfra"),
    built_in_wire_id!(soracloud::UpgradeSoracloudAppInfra => "iroha.instruction.v1::soracloud::UpgradeSoracloudAppInfra"),
    built_in_wire_id!(soracloud::RollbackSoracloudService => "soracloud::RollbackSoracloudService"),
    built_in_wire_id!(soracloud::SetSoracloudServiceConfig => "iroha.instruction.v1::soracloud::SetSoracloudServiceConfig"),
    built_in_wire_id!(soracloud::DeleteSoracloudServiceConfig => "iroha.instruction.v1::soracloud::DeleteSoracloudServiceConfig"),
    built_in_wire_id!(soracloud::SetSoracloudServiceSecret => "iroha.instruction.v1::soracloud::SetSoracloudServiceSecret"),
    built_in_wire_id!(soracloud::DeleteSoracloudServiceSecret => "iroha.instruction.v1::soracloud::DeleteSoracloudServiceSecret"),
    built_in_wire_id!(soracloud::MutateSoracloudState => "soracloud::MutateSoracloudState"),
    built_in_wire_id!(soracloud::RegisterSoracloudFhePolicy => "soracloud::RegisterSoracloudFhePolicy"),
    built_in_wire_id!(soracloud::RotateSoracloudFhePolicy => "soracloud::RotateSoracloudFhePolicy"),
    built_in_wire_id!(soracloud::RevokeSoracloudFhePolicy => "soracloud::RevokeSoracloudFhePolicy"),
    built_in_wire_id!(soracloud::RunSoracloudFheJob => "soracloud::RunSoracloudFheJob"),
    built_in_wire_id!(soracloud::RecordSoracloudDecryptionRequest => "soracloud::RecordSoracloudDecryptionRequest"),
    built_in_wire_id!(soracloud::JoinSoracloudHfSharedLease => "soracloud::JoinSoracloudHfSharedLease"),
    built_in_wire_id!(soracloud::LeaveSoracloudHfSharedLease => "soracloud::LeaveSoracloudHfSharedLease"),
    built_in_wire_id!(soracloud::RenewSoracloudHfSharedLease => "soracloud::RenewSoracloudHfSharedLease"),
    built_in_wire_id!(soracloud::AdvertiseSoracloudInrouHost => "soracloud::AdvertiseSoracloudInrouHost"),
    built_in_wire_id!(soracloud::WithdrawSoracloudInrouHost => "soracloud::WithdrawSoracloudInrouHost"),
    built_in_wire_id!(soracloud::ReconcileSoracloudInrouPlacements => "soracloud::ReconcileSoracloudInrouPlacements"),
    built_in_wire_id!(soracloud::DeploySoracloudAgentApartment => "soracloud::DeploySoracloudAgentApartment"),
    built_in_wire_id!(soracloud::RenewSoracloudAgentLease => "soracloud::RenewSoracloudAgentLease"),
    built_in_wire_id!(soracloud::RestartSoracloudAgentApartment => "soracloud::RestartSoracloudAgentApartment"),
    built_in_wire_id!(soracloud::RevokeSoracloudAgentPolicy => "soracloud::RevokeSoracloudAgentPolicy"),
    built_in_wire_id!(soracloud::RequestSoracloudAgentWalletSpend => "soracloud::RequestSoracloudAgentWalletSpend"),
    built_in_wire_id!(soracloud::ApproveSoracloudAgentWalletSpend => "soracloud::ApproveSoracloudAgentWalletSpend"),
    built_in_wire_id!(soracloud::EnqueueSoracloudAgentMessage => "soracloud::EnqueueSoracloudAgentMessage"),
    built_in_wire_id!(soracloud::AcknowledgeSoracloudAgentMessage => "soracloud::AcknowledgeSoracloudAgentMessage"),
    built_in_wire_id!(soracloud::AllowSoracloudAgentAutonomyArtifact => "soracloud::AllowSoracloudAgentAutonomyArtifact"),
    built_in_wire_id!(soracloud::RunSoracloudAgentAutonomy => "soracloud::RunSoracloudAgentAutonomy"),
    built_in_wire_id!(soracloud::RecordSoracloudAgentAutonomyExecution => "soracloud::RecordSoracloudAgentAutonomyExecution"),
    built_in_wire_id!(soracloud::StartSoracloudTrainingJob => "soracloud::StartSoracloudTrainingJob"),
    built_in_wire_id!(soracloud::CheckpointSoracloudTrainingJob => "soracloud::CheckpointSoracloudTrainingJob"),
    built_in_wire_id!(soracloud::RetrySoracloudTrainingJob => "soracloud::RetrySoracloudTrainingJob"),
    built_in_wire_id!(soracloud::RegisterSoracloudModelArtifact => "soracloud::RegisterSoracloudModelArtifact"),
    built_in_wire_id!(soracloud::RegisterSoracloudModelWeight => "soracloud::RegisterSoracloudModelWeight"),
    built_in_wire_id!(soracloud::PromoteSoracloudModelWeight => "soracloud::PromoteSoracloudModelWeight"),
    built_in_wire_id!(soracloud::RollbackSoracloudModelWeight => "soracloud::RollbackSoracloudModelWeight"),
    built_in_wire_id!(soracloud::RegisterSoracloudUploadedModelBundle => "soracloud::RegisterSoracloudUploadedModelBundle"),
    built_in_wire_id!(soracloud::FinalizeSoracloudUploadedModelBundle => "soracloud::FinalizeSoracloudUploadedModelBundle"),
    built_in_wire_id!(soracloud::AdvanceSoracloudRollout => "soracloud::AdvanceSoracloudRollout"),
    built_in_wire_id!(soracloud::SetSoracloudRuntimeState => "soracloud::SetSoracloudRuntimeState"),
    built_in_wire_id!(soracloud::SetSoracloudInrouReplicaRuntimeState => "soracloud::SetSoracloudInrouReplicaRuntimeState"),
    built_in_wire_id!(soracloud::ClearSoracloudInrouReplicaRuntimeState => "soracloud::ClearSoracloudInrouReplicaRuntimeState"),
    built_in_wire_id!(soracloud::ReportSoracloudServiceLeaseUsage => "soracloud::ReportSoracloudServiceLeaseUsage"),
    built_in_wire_id!(soracloud::RecordSoracloudMailboxMessage => "soracloud::RecordSoracloudMailboxMessage"),
    built_in_wire_id!(soracloud::RecordSoracloudRuntimeReceipt => "soracloud::RecordSoracloudRuntimeReceipt"),
    built_in_wire_id!(soracloud::ApplySoracloudOrderedMailboxResult => "soracloud::ApplySoracloudOrderedMailboxResult"),
    built_in_wire_id!(ExecuteTrigger => "iroha.execute_trigger"),
    built_in_wire_id!(Upgrade => "iroha.upgrade"),
    built_in_wire_id!(Log => "iroha.log"),
    built_in_wire_id!(CustomInstruction => "iroha.custom"),
    built_in_wire_id!(InvalidInstruction => "iroha.invalid_instruction"),
    built_in_wire_id!(verifying_keys::RegisterVerifyingKey => "iroha.instruction.v1::verifying_keys::RegisterVerifyingKey"),
    built_in_wire_id!(verifying_keys::UpdateVerifyingKey => "iroha.instruction.v1::verifying_keys::UpdateVerifyingKey"),
    built_in_wire_id!(consensus_keys::RegisterConsensusKey => "consensus::RegisterConsensusKey"),
    built_in_wire_id!(consensus_keys::RotateConsensusKey => "consensus::RotateConsensusKey"),
    built_in_wire_id!(consensus_keys::DisableConsensusKey => "consensus::DisableConsensusKey"),
    built_in_wire_id!(consensus_keys::ApplyThresholdKeyLifecycleCertificateV1 => "iroha.consensus.threshold-key-lifecycle.apply.v1"),
    built_in_wire_id!(endorsement::RegisterDomainCommittee => "nexus::RegisterDomainCommittee"),
    built_in_wire_id!(endorsement::SetDomainEndorsementPolicy => "nexus::SetDomainEndorsementPolicy"),
    built_in_wire_id!(endorsement::SubmitDomainEndorsement => "nexus::SubmitDomainEndorsement"),
    built_in_wire_id!(alias_setup::EnsureAlias => "iroha.alias.ensure"),
    built_in_wire_id!(alias_setup::RenewAliasLease => "iroha.alias.lease.renew"),
    built_in_wire_id!(alias_setup::ConfigureAliasAutoRenew => "iroha.alias.auto_renew.configure"),
    built_in_wire_id!(alias_setup::RebindAccountAlias => "iroha.account.alias.rebind"),
    built_in_wire_id!(alias_setup::CompareAndSetPrimaryAccountAlias => "iroha.account.alias.primary.compare_and_set"),
    built_in_wire_id!(account_recovery::ReplaceAccountController => "iroha.account.controller.replace"),
    built_in_wire_id!(account_recovery::SetAccountRecoveryPolicy => "iroha.account.recovery.policy.set"),
    built_in_wire_id!(account_recovery::ClearAccountRecoveryPolicy => "iroha.account.recovery.policy.clear"),
    built_in_wire_id!(account_recovery::ProposeAccountRecovery => "iroha.account.recovery.propose"),
    built_in_wire_id!(account_recovery::ApproveAccountRecovery => "iroha.account.recovery.approve"),
    built_in_wire_id!(account_recovery::CancelAccountRecovery => "iroha.account.recovery.cancel"),
    built_in_wire_id!(account_recovery::FinalizeAccountRecovery => "iroha.account.recovery.finalize"),
    built_in_wire_id!(contract_alias::SetContractAlias => "iroha.contract.alias.set"),
    built_in_wire_id!(musubi::RegisterMusubiNamespaceBindingV1 => "iroha.musubi.v1.namespace_binding.register"),
    built_in_wire_id!(musubi::RegisterMusubiArchiveV1 => "iroha.musubi.v1.archive.register"),
    built_in_wire_id!(musubi::RegisterMusubiProviderBundleAttestationV1 => "iroha.musubi.v1.provider_bundle_attestation.register"),
    built_in_wire_id!(musubi::AddMusubiArchiveLocationV1 => "iroha.musubi.v1.archive_location.add"),
    built_in_wire_id!(musubi::RetireMusubiArchiveLocationV1 => "iroha.musubi.v1.archive_location.retire"),
    built_in_wire_id!(musubi::PublishMusubiReleaseV1 => "iroha.musubi.v1.release.publish"),
    built_in_wire_id!(musubi::SetMusubiReleaseYankV1 => "iroha.musubi.v1.release_yank.set"),
    built_in_wire_id!(musubi::SetMusubiPackageMetadataV1 => "iroha.musubi.v1.package_metadata.set"),
    built_in_wire_id!(musubi::InviteMusubiPackageMaintainerV1 => "iroha.musubi.v1.package_member.invite"),
    built_in_wire_id!(musubi::AcceptMusubiPackageMaintainerV1 => "iroha.musubi.v1.package_member.accept"),
    built_in_wire_id!(musubi::RevokeMusubiPackageMaintainerInvitationV1 => "iroha.musubi.v1.package_member.invitation.revoke"),
    built_in_wire_id!(musubi::SetMusubiPackageMaintainerRoleV1 => "iroha.musubi.v1.package_member.set_role"),
    built_in_wire_id!(musubi::RemoveMusubiPackageMaintainerV1 => "iroha.musubi.v1.package_member.remove"),
    built_in_wire_id!(musubi::RegisterMusubiAliasV1 => "iroha.musubi.v1.alias.register"),
    built_in_wire_id!(musubi::RecoverMusubiPackageV1 => "iroha.musubi.v1.parliament.package_recover"),
    built_in_wire_id!(musubi::RetargetMusubiAliasV1 => "iroha.musubi.v1.parliament.alias_retarget"),
    built_in_wire_id!(musubi::SetMusubiArtifactTakedownV1 => "iroha.musubi.v1.parliament.artifact_takedown"),
    built_in_wire_id!(musubi::SetMusubiRegistryPolicyV1 => "iroha.musubi.v1.parliament.registry_policy.set"),
    built_in_wire_id!(musubi::AssertMusubiReleaseDigestV1 => "iroha.musubi.v1.release_digest.assert"),
    built_in_wire_id!(ram_lfe::RegisterRamLfeProgramPolicy => "identity::RegisterRamLfeProgramPolicy"),
    built_in_wire_id!(ram_lfe::ActivateRamLfeProgramPolicy => "identity::ActivateRamLfeProgramPolicy"),
    built_in_wire_id!(ram_lfe::DeactivateRamLfeProgramPolicy => "identity::DeactivateRamLfeProgramPolicy"),
    built_in_wire_id!(identifier::RegisterIdentifierPolicy => "identity::RegisterIdentifierPolicy"),
    built_in_wire_id!(identifier::ActivateIdentifierPolicy => "identity::ActivateIdentifierPolicy"),
    built_in_wire_id!(identifier::ClaimIdentifier => "identity::ClaimIdentifier"),
    built_in_wire_id!(identifier::RevokeIdentifier => "identity::RevokeIdentifier"),
    built_in_wire_id!(asset_alias::SetAssetDefinitionAlias => "iroha.asset_definition.alias.set"),
    built_in_wire_id!(sorafs::RegisterPinManifest => "iroha.instruction.v1::sorafs::RegisterPinManifest"),
    built_in_wire_id!(sorafs::ApprovePinManifest => "iroha.instruction.v1::sorafs::ApprovePinManifest"),
    built_in_wire_id!(sorafs::RetirePinManifest => "iroha.instruction.v1::sorafs::RetirePinManifest"),
    built_in_wire_id!(sorafs::BindManifestAlias => "iroha.instruction.v1::sorafs::BindManifestAlias"),
    built_in_wire_id!(sorafs::RegisterCapacityDeclaration => "iroha.instruction.v1::sorafs::RegisterCapacityDeclaration"),
    built_in_wire_id!(sorafs::RecordCapacityTelemetry => "iroha.instruction.v1::sorafs::RecordCapacityTelemetry"),
    built_in_wire_id!(sorafs::RegisterCapacityDispute => "iroha.instruction.v1::sorafs::RegisterCapacityDispute"),
    built_in_wire_id!(sorafs::ResolveSorafsCapacityDispute => "iroha.instruction.v1::sorafs::ResolveSorafsCapacityDispute"),
    built_in_wire_id!(sorafs::IssueReplicationOrder => "iroha.instruction.v1::sorafs::IssueReplicationOrder"),
    built_in_wire_id!(sorafs::CompleteReplicationOrder => "iroha.instruction.v1::sorafs::CompleteReplicationOrder"),
    built_in_wire_id!(sorafs::ReviseReplicationOrderAssignments => "iroha.instruction.v1::sorafs::ReviseReplicationOrderAssignments"),
    built_in_wire_id!(sorafs::ExpireReplicationOrder => "iroha.instruction.v1::sorafs::ExpireReplicationOrder"),
    built_in_wire_id!(sorafs::RegisterProviderOwner => "iroha.instruction.v1::sorafs::RegisterProviderOwner"),
    built_in_wire_id!(sorafs::UnregisterProviderOwner => "iroha.instruction.v1::sorafs::UnregisterProviderOwner"),
    built_in_wire_id!(sorafs::SetProviderIngestCompletionAuthority => "iroha.instruction.v1::sorafs::SetProviderIngestCompletionAuthority"),
    built_in_wire_id!(sorafs::RevokeProviderIngestCompletionAuthority => "iroha.instruction.v1::sorafs::RevokeProviderIngestCompletionAuthority"),
    built_in_wire_id!(sorafs::SetPricingSchedule => "iroha.instruction.v1::sorafs::SetPricingSchedule"),
    built_in_wire_id!(sorafs::UpsertProviderCredit => "iroha.instruction.v1::sorafs::UpsertProviderCredit"),
    built_in_wire_id!(sorafs::SetSorafsPopIssuerPolicy => "iroha.instruction.v1::sorafs::SetSorafsPopIssuerPolicy"),
    built_in_wire_id!(sorafs::CommitSorafsPopCredentialBatch => "iroha.instruction.v1::sorafs::CommitSorafsPopCredentialBatch"),
    built_in_wire_id!(sorafs::PublishSorafsPopRevocationList => "iroha.instruction.v1::sorafs::PublishSorafsPopRevocationList"),
    built_in_wire_id!(sorafs::RegisterSorafsCitizenBond => "iroha.instruction.v1::sorafs::RegisterSorafsCitizenBond"),
    built_in_wire_id!(sorafs::RotateSorafsCitizenBondAuthorization => "iroha.instruction.v1::sorafs::RotateSorafsCitizenBondAuthorization"),
    built_in_wire_id!(sorafs::RequestSorafsCitizenBondExit => "iroha.instruction.v1::sorafs::RequestSorafsCitizenBondExit"),
    built_in_wire_id!(sorafs::SetSorafsOrderbookPolicy => "iroha.instruction.v1::sorafs::SetSorafsOrderbookPolicy"),
    built_in_wire_id!(sorafs::SubmitSorafsOrderbookOrder => "iroha.instruction.v1::sorafs::SubmitSorafsOrderbookOrder"),
    built_in_wire_id!(sorafs::CancelSorafsOrderbookOrder => "iroha.instruction.v1::sorafs::CancelSorafsOrderbookOrder"),
    built_in_wire_id!(sorafs::MatchSorafsOrderbook => "iroha.instruction.v1::sorafs::MatchSorafsOrderbook"),
    built_in_wire_id!(sorafs::MaintainSorafsOrderbook => "iroha.instruction.v1::sorafs::MaintainSorafsOrderbook"),
    built_in_wire_id!(sorafs::RecordSorafsOrderbookSettlementReceipt => "iroha.instruction.v1::sorafs::RecordSorafsOrderbookSettlementReceipt"),
    built_in_wire_id!(sorafs::SetSorafsReservePolicy => "iroha.instruction.v1::sorafs::SetSorafsReservePolicy"),
    built_in_wire_id!(sorafs::RegisterSorafsReserveAccount => "iroha.instruction.v1::sorafs::RegisterSorafsReserveAccount"),
    built_in_wire_id!(sorafs::RequestSorafsReserveMovement => "iroha.instruction.v1::sorafs::RequestSorafsReserveMovement"),
    built_in_wire_id!(sorafs::DecideSorafsReserveMovement => "iroha.instruction.v1::sorafs::DecideSorafsReserveMovement"),
    built_in_wire_id!(sorafs::ChargeSorafsReserveRent => "iroha.instruction.v1::sorafs::ChargeSorafsReserveRent"),
    built_in_wire_id!(sorafs::AdvanceSorafsReserveLifecycle => "iroha.instruction.v1::sorafs::AdvanceSorafsReserveLifecycle"),
    built_in_wire_id!(sorafs::DrawSorafsReserveCredit => "iroha.instruction.v1::sorafs::DrawSorafsReserveCredit"),
    built_in_wire_id!(sorafs::RepaySorafsReserveCredit => "iroha.instruction.v1::sorafs::RepaySorafsReserveCredit"),
    built_in_wire_id!(sorafs::SubmitSorafsReserveAppeal => "iroha.instruction.v1::sorafs::SubmitSorafsReserveAppeal"),
    built_in_wire_id!(sorafs::DecideSorafsReserveAppeal => "iroha.instruction.v1::sorafs::DecideSorafsReserveAppeal"),
    built_in_wire_id!(sorafs::SubmitSorafsRepairTask => "iroha.instruction.v1::sorafs::SubmitSorafsRepairTask"),
    built_in_wire_id!(sorafs::ApplySorafsRepairTaskAction => "iroha.instruction.v1::sorafs::ApplySorafsRepairTaskAction"),
    built_in_wire_id!(sorafs::SubmitSorafsRepairAppeal => "iroha.instruction.v1::sorafs::SubmitSorafsRepairAppeal"),
    built_in_wire_id!(sorafs::SetSorafsProofOutcomeSignerPolicy => "iroha.instruction.v1::sorafs::SetSorafsProofOutcomeSignerPolicy"),
    built_in_wire_id!(sorafs::SubmitSorafsProofOutcome => "iroha.instruction.v1::sorafs::SubmitSorafsProofOutcome"),
    built_in_wire_id!(sorafs::SetSorafsReputationJournalAuthorityPolicy => "iroha.instruction.v1::sorafs::SetSorafsReputationJournalAuthorityPolicy"),
    built_in_wire_id!(sorafs::AppendSorafsPorReputationJournalEntry => "iroha.instruction.v1::sorafs::AppendSorafsPorReputationJournalEntry"),
    built_in_wire_id!(sorafs::AppendSorafsStreamTokenReputationJournalEntry => "iroha.instruction.v1::sorafs::AppendSorafsStreamTokenReputationJournalEntry"),
    built_in_wire_id!(sorafs::SetSorafsModerationPolicy => "iroha.instruction.v1::sorafs::SetSorafsModerationPolicy"),
    built_in_wire_id!(sorafs::SubmitSorafsModerationAppeal => "iroha.instruction.v1::sorafs::SubmitSorafsModerationAppeal"),
    built_in_wire_id!(sorafs::RegisterSorafsModerationJurorEligibility => "iroha.instruction.v1::sorafs::RegisterSorafsModerationJurorEligibility"),
    built_in_wire_id!(sorafs::FinalizeSorafsModerationSortition => "iroha.instruction.v1::sorafs::FinalizeSorafsModerationSortition"),
    built_in_wire_id!(sorafs::AcceptSorafsModerationJurorAssignment => "iroha.instruction.v1::sorafs::AcceptSorafsModerationJurorAssignment"),
    built_in_wire_id!(sorafs::ActivateSorafsModerationCase => "iroha.instruction.v1::sorafs::ActivateSorafsModerationCase"),
    built_in_wire_id!(sorafs::SubmitSorafsModerationCommit => "iroha.instruction.v1::sorafs::SubmitSorafsModerationCommit"),
    built_in_wire_id!(sorafs::RaiseSorafsModerationChallenge => "iroha.instruction.v1::sorafs::RaiseSorafsModerationChallenge"),
    built_in_wire_id!(sorafs::ResolveSorafsModerationChallenge => "iroha.instruction.v1::sorafs::ResolveSorafsModerationChallenge"),
    built_in_wire_id!(sorafs::ExpireSorafsModerationChallenge => "iroha.instruction.v1::sorafs::ExpireSorafsModerationChallenge"),
    built_in_wire_id!(sorafs::SubmitSorafsModerationReveal => "iroha.instruction.v1::sorafs::SubmitSorafsModerationReveal"),
    built_in_wire_id!(sorafs::FinalizeSorafsModerationCase => "iroha.instruction.v1::sorafs::FinalizeSorafsModerationCase"),
    built_in_wire_id!(content::PublishContentBundle => "iroha.instruction.v1::content::PublishContentBundle", register),
    built_in_wire_id!(content::RetireContentBundle => "iroha.instruction.v1::content::RetireContentBundle", register),
    built_in_wire_id!(soradns::SubmitDirectoryDraft => "iroha.instruction.v1::soradns::SubmitDirectoryDraft", register),
    built_in_wire_id!(soradns::PublishDirectory => "iroha.instruction.v1::soradns::PublishDirectory", register),
    built_in_wire_id!(soradns::RevokeResolver => "iroha.instruction.v1::soradns::RevokeResolver", register),
    built_in_wire_id!(soradns::UnrevokeResolver => "iroha.instruction.v1::soradns::UnrevokeResolver", register),
    built_in_wire_id!(soradns::AddReleaseSigner => "iroha.instruction.v1::soradns::AddReleaseSigner", register),
    built_in_wire_id!(soradns::RemoveReleaseSigner => "iroha.instruction.v1::soradns::RemoveReleaseSigner", register),
    built_in_wire_id!(soradns::SetDirectoryRotationPolicy => "iroha.instruction.v1::soradns::SetDirectoryRotationPolicy", register),
    built_in_wire_id!(space_directory::PublishSpaceDirectoryManifest => "iroha.instruction.v1::space_directory::PublishSpaceDirectoryManifest"),
    built_in_wire_id!(space_directory::RevokeSpaceDirectoryManifest => "iroha.instruction.v1::space_directory::RevokeSpaceDirectoryManifest"),
    built_in_wire_id!(space_directory::ExpireSpaceDirectoryManifest => "iroha.instruction.v1::space_directory::ExpireSpaceDirectoryManifest"),
    built_in_wire_id!(smart_contract_code::RegisterSmartContractCode => "iroha.instruction.v1::smart_contract_code::RegisterSmartContractCode"),
    built_in_wire_id!(smart_contract_code::DeactivateContractInstance => "iroha.instruction.v1::smart_contract_code::DeactivateContractInstance"),
    built_in_wire_id!(smart_contract_code::ActivateContractInstance => "iroha.instruction.v1::smart_contract_code::ActivateContractInstance"),
    built_in_wire_id!(smart_contract_code::SetContractParliamentDelegation => "iroha.instruction.v1::smart_contract_code::SetContractParliamentDelegation"),
    built_in_wire_id!(smart_contract_code::OfferContractOwnership => "iroha.instruction.v1::smart_contract_code::OfferContractOwnership"),
    built_in_wire_id!(smart_contract_code::AcceptContractOwnership => "iroha.instruction.v1::smart_contract_code::AcceptContractOwnership"),
    built_in_wire_id!(smart_contract_code::CancelContractOwnershipOffer => "iroha.instruction.v1::smart_contract_code::CancelContractOwnershipOffer"),
    built_in_wire_id!(smart_contract_code::CommitContractDeployment => "iroha.instruction.v1::smart_contract_code::CommitContractDeployment"),
    built_in_wire_id!(smart_contract_code::RegisterSmartContractBytes => "iroha.instruction.v1::smart_contract_code::RegisterSmartContractBytes"),
    built_in_wire_id!(smart_contract_code::UploadSmartContractCodeChunk => "iroha.instruction.v1::smart_contract_code::UploadSmartContractCodeChunk"),
    built_in_wire_id!(smart_contract_code::FinalizeSmartContractCodeUpload => "iroha.instruction.v1::smart_contract_code::FinalizeSmartContractCodeUpload"),
    built_in_wire_id!(smart_contract_code::CancelSmartContractCodeUpload => "iroha.instruction.v1::smart_contract_code::CancelSmartContractCodeUpload"),
    built_in_wire_id!(smart_contract_code::RemoveSmartContractBytes => "iroha.instruction.v1::smart_contract_code::RemoveSmartContractBytes"),
    built_in_wire_id!(zk::VerifyProof => "iroha.instruction.v1::zk::VerifyProof"),
    built_in_wire_id!(zk::PruneProofs => "iroha.instruction.v1::zk::PruneProofs"),
    built_in_wire_id!(privacy::RegisterPrivacyProtocolActivationV1 => "iroha.privacy.register_protocol_activation.v1"),
    built_in_wire_id!(privacy::RegisterPrivacyExact12QualificationV1 => "iroha.privacy.register_exact12_qualification.v1"),
    built_in_wire_id!(privacy::SchedulePrivacyConsensusPolicyTighteningV1 => "iroha.privacy.schedule_consensus_policy_tightening.v1"),
    built_in_wire_id!(privacy::SchedulePrivacyProtocolLimitsTighteningV1 => "iroha.privacy.schedule_protocol_limits_tightening.v1"),
    built_in_wire_id!(privacy::TransitionPrivacyProtocolLifecycleV1 => "iroha.privacy.transition_protocol_lifecycle.v1"),
    built_in_wire_id!(privacy::PublishPrivacyRootV1 => "iroha.privacy.publish_root.v1"),
    built_in_wire_id!(privacy::BootstrapPrivacyOrchardPoolV1 => "iroha.privacy.bootstrap_orchard_pool.v1"),
    built_in_wire_id!(privacy::BootstrapPrivacyProofManagedPoolV1 => "iroha.privacy.bootstrap_proof_managed_pool.v1"),
    built_in_wire_id!(privacy::BootstrapPrivacyPgcAccountsV1 => "iroha.privacy.bootstrap_pgc_accounts.v1"),
    built_in_wire_id!(privacy::BootstrapPrivacyZkAmsRegistryV1 => "iroha.privacy.bootstrap_zk_ams_registry.v1"),
    built_in_wire_id!(privacy::RegisterPrivacyZkAcePolicyV1 => "iroha.privacy.register_zk_ace_policy.v1"),
    built_in_wire_id!(privacy::RotatePrivacyZkAcePolicyV1 => "iroha.privacy.rotate_zk_ace_policy.v1"),
    built_in_wire_id!(privacy::RevokePrivacyZkAcePolicyV1 => "iroha.privacy.revoke_zk_ace_policy.v1"),
    built_in_wire_id!(privacy::RegisterPrivacyBootleLanternIssuerPolicyV1 => "iroha.privacy.register_bootle_lantern_issuer_policy.v1"),
    built_in_wire_id!(privacy::RotatePrivacyBootleLanternIssuerPolicyV1 => "iroha.privacy.rotate_bootle_lantern_issuer_policy.v1"),
    built_in_wire_id!(privacy::RevokePrivacyBootleLanternIssuerPolicyV1 => "iroha.privacy.revoke_bootle_lantern_issuer_policy.v1"),
    built_in_wire_id!(privacy::RegisterPrivacyVegaIssuerV1 => "iroha.privacy.register_vega_issuer.v1"),
    built_in_wire_id!(privacy::RotatePrivacyVegaIssuerV1 => "iroha.privacy.rotate_vega_issuer.v1"),
    built_in_wire_id!(privacy::RevokePrivacyVegaIssuerV1 => "iroha.privacy.revoke_vega_issuer.v1"),
    built_in_wire_id!(privacy::RegisterPrivacyZkX509TrustAnchorV1 => "iroha.privacy.register_zk_x509_trust_anchor.v1"),
    built_in_wire_id!(privacy::RotatePrivacyZkX509TrustAnchorV1 => "iroha.privacy.rotate_zk_x509_trust_anchor.v1"),
    built_in_wire_id!(privacy::RevokePrivacyZkX509TrustAnchorV1 => "iroha.privacy.revoke_zk_x509_trust_anchor.v1"),
    built_in_wire_id!(privacy::RegisterPrivacyZkX509CertificatePolicyV1 => "iroha.privacy.register_zk_x509_certificate_policy.v1"),
    built_in_wire_id!(privacy::RotatePrivacyZkX509CertificatePolicyV1 => "iroha.privacy.rotate_zk_x509_certificate_policy.v1"),
    built_in_wire_id!(privacy::RevokePrivacyZkX509CertificatePolicyV1 => "iroha.privacy.revoke_zk_x509_certificate_policy.v1"),
    built_in_wire_id!(privacy::RegisterPrivacyZkX509CrlV1 => "iroha.privacy.register_zk_x509_crl.v1"),
    built_in_wire_id!(privacy::RotatePrivacyZkX509CrlV1 => "iroha.privacy.rotate_zk_x509_crl.v1"),
    built_in_wire_id!(privacy::RevokePrivacyZkX509CrlV1 => "iroha.privacy.revoke_zk_x509_crl.v1"),
    built_in_wire_id!(privacy::SubmitPrivacyProofV1 => "iroha.privacy.submit_proof.v1"),
    built_in_wire_id!(crate::isi::private_settlement::ActivatePrivateSettlementPoolV1 => "iroha.private_settlement.activate_pool.v1", register),
    built_in_wire_id!(crate::isi::private_settlement::RotatePrivateSettlementPoolPolicyV1 => "iroha.private_settlement.rotate_pool_policy.v1", register),
    built_in_wire_id!(crate::isi::private_settlement::RegisterAtomicPrivateSettlementPrepareV1 => "iroha.private_settlement.register_atomic_prepare.v1", register),
    built_in_wire_id!(crate::isi::private_settlement::AbortAtomicPrivateSettlementV1 => "iroha.private_settlement.abort_atomic_bundle.v1", register),
    built_in_wire_id!(crate::isi::private_settlement::FinalizeAtomicPrivateSettlementV1 => "iroha.private_settlement.finalize_atomic_bundle.v1", register),
    built_in_wire_id!(kaigi::CreateKaigi => "iroha.instruction.v1::kaigi::CreateKaigi"),
    built_in_wire_id!(kaigi::JoinKaigi => "iroha.instruction.v1::kaigi::JoinKaigi"),
    built_in_wire_id!(kaigi::LeaveKaigi => "iroha.instruction.v1::kaigi::LeaveKaigi"),
    built_in_wire_id!(kaigi::EndKaigi => "iroha.instruction.v1::kaigi::EndKaigi"),
    built_in_wire_id!(kaigi::RecordKaigiUsage => "iroha.instruction.v1::kaigi::RecordKaigiUsage"),
    built_in_wire_id!(kaigi::SetKaigiRelayManifest => "iroha.instruction.v1::kaigi::SetKaigiRelayManifest"),
    built_in_wire_id!(kaigi::RegisterKaigiRelay => "iroha.instruction.v1::kaigi::RegisterKaigiRelay"),
    built_in_wire_id!(kaigi::UnregisterKaigiRelay => "iroha.instruction.v1::kaigi::UnregisterKaigiRelay"),
    built_in_wire_id!(kaigi::ReportKaigiRelayHealth => "iroha.instruction.v1::kaigi::ReportKaigiRelayHealth"),
    built_in_wire_id!(zk::RegisterZkAsset => "iroha.instruction.v1::zk::RegisterZkAsset"),
    built_in_wire_id!(zk::ScheduleConfidentialPolicyTransition => "zk::ScheduleConfidentialPolicyTransition"),
    built_in_wire_id!(zk::CancelConfidentialPolicyTransition => "zk::CancelConfidentialPolicyTransition"),
    built_in_wire_id!(zk::CreateElection => "iroha.instruction.v1::zk::CreateElection"),
    built_in_wire_id!(zk::SubmitBallot => "iroha.instruction.v1::zk::SubmitBallot"),
    built_in_wire_id!(zk::FinalizeElection => "iroha.instruction.v1::zk::FinalizeElection"),
    built_in_wire_id!(bridge::SubmitBridgeProof => "iroha.instruction.v1::bridge::SubmitBridgeProof"),
    built_in_wire_id!(bridge::RecordBridgeReceipt => "iroha.instruction.v1::bridge::RecordBridgeReceipt"),
    built_in_wire_id!(bridge::RecordSccpMessage => "iroha.instruction.v1::bridge::RecordSccpMessage"),
    built_in_wire_id!(confidential::PublishPedersenParams => "iroha.instruction.v1::confidential::PublishPedersenParams", register),
    built_in_wire_id!(confidential::SetPedersenParamsLifecycle => "iroha.instruction.v1::confidential::SetPedersenParamsLifecycle", register),
    built_in_wire_id!(confidential::PublishPoseidonParams => "iroha.instruction.v1::confidential::PublishPoseidonParams", register),
    built_in_wire_id!(confidential::SetPoseidonParamsLifecycle => "iroha.instruction.v1::confidential::SetPoseidonParamsLifecycle", register),
    built_in_wire_id!(ministry::SubmitAgendaProposal => "iroha.instruction.v1::ministry::SubmitAgendaProposal"),
    #[cfg(feature = "governance")]
    governance_wire_id!(governance::ProposeDeployContract => "iroha.instruction.v1::governance::ProposeDeployContract"),
    #[cfg(feature = "governance")]
    governance_wire_id!(governance::ProposeContractLifecycleGovernance => "iroha.instruction.v1::governance::ProposeContractLifecycleGovernance"),
    #[cfg(feature = "governance")]
    governance_wire_id!(governance::ProposeContractEmergencyHold => "iroha.instruction.v1::governance::ProposeContractEmergencyHold"),
    #[cfg(feature = "governance")]
    governance_wire_id!(governance::ProposeGlobalDataTriggerPermissionGovernance => "iroha.instruction.v1::governance::ProposeGlobalDataTriggerPermissionGovernance"),
    #[cfg(feature = "governance")]
    governance_wire_id!(governance::ProposeRuntimeUpgradeProposal => "iroha.instruction.v1::governance::ProposeRuntimeUpgradeProposal"),
    #[cfg(feature = "governance")]
    governance_wire_id!(governance::ProposeSccpRouteGovernance => "iroha.instruction.v1::governance::ProposeSccpRouteGovernance"),
    #[cfg(feature = "governance")]
    governance_wire_id!(governance::ProposeSorafsProviderGovernance => "iroha.instruction.v1::governance::ProposeSorafsProviderGovernance"),
    #[cfg(feature = "governance")]
    governance_wire_id!(governance::ProposeValidationFeePolicy => "iroha.instruction.v1::governance::ProposeValidationFeePolicy"),
    #[cfg(feature = "governance")]
    governance_wire_id!(governance::ProposeValidationFeePayoutLifecycle => "iroha.instruction.v1::governance::ProposeValidationFeePayoutLifecycle"),
    #[cfg(feature = "governance")]
    governance_wire_id!(governance::CreateParliamentGovernanceAttemptV1 => "iroha.governance.parliament.attempt.create.v1"),
    #[cfg(feature = "governance")]
    governance_wire_id!(governance::SubmitParliamentLifecycleTransitionV1 => "iroha.governance.parliament.transition.submit.v1"),
    #[cfg(feature = "governance")]
    governance_wire_id!(governance::CastZkBallot => "iroha.instruction.v1::governance::CastZkBallot"),
    #[cfg(feature = "governance")]
    governance_wire_id!(governance::CastPlainBallot => "iroha.instruction.v1::governance::CastPlainBallot"),
    #[cfg(feature = "governance")]
    governance_wire_id!(governance::SlashGovernanceLock => "iroha.instruction.v1::governance::SlashGovernanceLock"),
    #[cfg(feature = "governance")]
    governance_wire_id!(governance::RestituteGovernanceLock => "iroha.instruction.v1::governance::RestituteGovernanceLock"),
    #[cfg(feature = "governance")]
    governance_wire_id!(governance::RegisterCitizen => "iroha.instruction.v1::governance::RegisterCitizen"),
    #[cfg(feature = "governance")]
    governance_wire_id!(governance::UnregisterCitizen => "iroha.instruction.v1::governance::UnregisterCitizen"),
    built_in_wire_id!(runtime_upgrade::ProposeRuntimeUpgrade => "iroha.runtime_upgrade.propose"),
    built_in_wire_id!(runtime_upgrade::ActivateRuntimeUpgrade => "iroha.runtime_upgrade.activate"),
    built_in_wire_id!(runtime_upgrade::CancelRuntimeUpgrade => "iroha.runtime_upgrade.cancel"),
];
/// Register every built-in instruction using its canonical typed codec constructor.
pub(super) fn register_all() -> InstructionRegistry {
    ALL.iter()
        .fold(InstructionRegistry::new(), |registry, entry| {
            (entry.register)(registry)
        })
}
