[sumeragi]
consensus_mode = "permissioned"
pacemaker_max_backoff_ms = 2000
pacemaker_rtt_floor_multiplier = 1

[sumeragi.npos.timeouts]
commit_ms = 800
da_ms = 400
precommit_ms = 600
prevote_ms = 400
propose_ms = 200
