#!/usr/bin/env python3
"""Validate the generated-file registry and reject tracked build artifacts.

Prerequisites: Python 3.11+ (or the ``tomli`` package) and a Git checkout.
The check is read-only. It reads ``generated-files.toml`` from the repository
root, validates every registered output and canonical input, and inspects the
Git index for forbidden build/cache artifacts.

No environment variables are required.
"""

from __future__ import annotations

import argparse
import fnmatch
import os
import re
import subprocess
import sys
from functools import lru_cache
from pathlib import Path
from typing import Any

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - exercised on Python 3.10
    import tomli as tomllib


MANIFEST_SCHEMA_VERSION = 1
GENERATED_KINDS = frozenset({"file", "regions"})
GENERATED_HEADER = re.compile(
    r"^(?://!?|#)\s*(?:@generated\b|auto-generated\b|code generated\b|generated by\b)",
    re.IGNORECASE,
)
CORE_DUMP_NAMES = re.compile(r"^core(?:\.\d+)?$")
EXECUTABLE_MAGICS = (
    b"\x7fELF",
    b"\xfe\xed\xfa\xce",
    b"\xfe\xed\xfa\xcf",
    b"\xce\xfa\xed\xfe",
    b"\xcf\xfa\xed\xfe",
)


class ValidationError(ValueError):
    """A generated-file manifest or tracked-artifact validation failure."""


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse command-line arguments."""

    parser = argparse.ArgumentParser(
        description=(
            "validate generated-files.toml and reject tracked build/cache artifacts"
        )
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="repository root (default: inferred from this script)",
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=Path("generated-files.toml"),
        help="manifest path, relative to --root unless absolute (default: %(default)s)",
    )
    return parser.parse_args(argv)


def _strict_keys(
    value: dict[str, Any],
    *,
    allowed: set[str],
    required: set[str],
    label: str,
) -> None:
    missing = sorted(required - set(value))
    unknown = sorted(set(value) - allowed)
    if missing:
        raise ValidationError(f"{label} is missing keys: {', '.join(missing)}")
    if unknown:
        raise ValidationError(f"{label} has unknown keys: {', '.join(unknown)}")


def _string(value: object, label: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValidationError(f"{label} must be a non-empty string")
    return value


def _string_list(value: object, label: str, *, nonempty: bool = False) -> list[str]:
    if not isinstance(value, list) or (nonempty and not value):
        qualifier = "non-empty " if nonempty else ""
        raise ValidationError(f"{label} must be a {qualifier}array of strings")
    result: list[str] = []
    for index, item in enumerate(value):
        result.append(_string(item, f"{label}[{index}]"))
    if len(result) != len(set(result)):
        raise ValidationError(f"{label} contains duplicate entries")
    return result


def _normalized_path(value: str, label: str, *, allow_glob: bool = False) -> str:
    path = value.replace("\\", "/")
    if (
        not path
        or path.startswith("/")
        or re.match(r"^[A-Za-z]:/", path)
        or "//" in path
        or any(part in {"", ".", ".."} for part in path.split("/"))
    ):
        raise ValidationError(f"{label} must be a normalized repository-relative path")
    if not allow_glob and any(character in path for character in "*?["):
        raise ValidationError(f"{label} must not contain glob metacharacters")
    return path


def _git_tracked_paths(root: Path) -> set[str]:
    try:
        result = subprocess.run(
            ["git", "ls-files", "-z"],
            cwd=root,
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
    except (OSError, subprocess.CalledProcessError) as error:
        detail = getattr(error, "stderr", b"")
        rendered = detail.decode("utf-8", errors="replace").strip()
        suffix = f": {rendered}" if rendered else ""
        raise ValidationError(f"failed to list tracked files{suffix}") from error
    paths = result.stdout.decode("utf-8", errors="strict").split("\0")
    return {
        path
        for path in paths
        if path and os.path.lexists(root / path)
    }


def _glob_matches(path: str, pattern: str) -> bool:
    """Match a normalized repository path with segment-aware glob semantics.

    A single ``*`` or ``?`` never crosses a directory separator. A complete
    ``**`` path segment matches zero or more path segments, including at the
    repository root. Keeping those two cases distinct prevents a shallow
    owner input such as ``src/*.rs`` from silently owning nested sources.
    """

    path_parts = tuple(path.split("/"))
    pattern_parts = tuple(pattern.split("/"))

    @lru_cache(maxsize=None)
    def matches(pattern_index: int, path_index: int) -> bool:
        if pattern_index == len(pattern_parts):
            return path_index == len(path_parts)

        pattern_part = pattern_parts[pattern_index]
        if pattern_part == "**":
            return matches(pattern_index + 1, path_index) or (
                path_index < len(path_parts)
                and matches(pattern_index, path_index + 1)
            )

        return (
            path_index < len(path_parts)
            and fnmatch.fnmatchcase(path_parts[path_index], pattern_part)
            and matches(pattern_index + 1, path_index + 1)
        )

    return matches(0, 0)


def _matching_paths(paths: set[str], pattern: str) -> set[str]:
    return {path for path in paths if _glob_matches(path, pattern)}


def _require_regular_file(root: Path, relative: str, label: str) -> None:
    path = root / relative
    if not path.exists():
        raise ValidationError(f"{label} does not exist: {relative}")
    if path.is_symlink() or not path.is_file():
        raise ValidationError(f"{label} must be a regular file: {relative}")


def _validate_policy(raw: object) -> tuple[list[str], set[str], set[str]]:
    if not isinstance(raw, dict):
        raise ValidationError("policy must be a table")
    _strict_keys(
        raw,
        allowed={
            "forbidden_tracked_globs",
            "allowed_tracked_paths",
            "generated_source_extensions",
        },
        required={
            "forbidden_tracked_globs",
            "allowed_tracked_paths",
            "generated_source_extensions",
        },
        label="policy",
    )
    forbidden = [
        _normalized_path(value, f"policy.forbidden_tracked_globs[{index}]", allow_glob=True)
        for index, value in enumerate(
            _string_list(
                raw["forbidden_tracked_globs"],
                "policy.forbidden_tracked_globs",
                nonempty=True,
            )
        )
    ]
    allowed = {
        _normalized_path(value, f"policy.allowed_tracked_paths[{index}]")
        for index, value in enumerate(
            _string_list(raw["allowed_tracked_paths"], "policy.allowed_tracked_paths")
        )
    }
    extensions = set(
        _string_list(
            raw["generated_source_extensions"],
            "policy.generated_source_extensions",
            nonempty=True,
        )
    )
    for extension in extensions:
        if not extension.startswith(".") or "/" in extension:
            raise ValidationError(
                "policy.generated_source_extensions entries must be file extensions"
            )
    return forbidden, allowed, extensions


def _validate_generated_entries(
    raw_entries: object,
    *,
    root: Path,
    tracked: set[str],
) -> set[str]:
    if not isinstance(raw_entries, list) or not raw_entries:
        raise ValidationError("generated must be a non-empty array of tables")

    names: set[str] = set()
    outputs_seen: dict[str, str] = {}
    all_outputs: set[str] = set()
    allowed_keys = {
        "name",
        "kind",
        "outputs",
        "generator",
        "generator_sources",
        "inputs",
        "check",
        "external",
        "provenance",
    }
    required_keys = {
        "name",
        "kind",
        "outputs",
        "generator",
        "generator_sources",
        "inputs",
        "check",
    }

    for index, entry in enumerate(raw_entries):
        label = f"generated[{index}]"
        if not isinstance(entry, dict):
            raise ValidationError(f"{label} must be a table")
        _strict_keys(
            entry,
            allowed=allowed_keys,
            required=required_keys,
            label=label,
        )
        name = _string(entry["name"], f"{label}.name")
        if name in names:
            raise ValidationError(f"duplicate generated entry name: {name}")
        names.add(name)

        kind = _string(entry["kind"], f"{label}.kind")
        if kind not in GENERATED_KINDS:
            raise ValidationError(
                f"{label}.kind must be one of: {', '.join(sorted(GENERATED_KINDS))}"
            )
        _string(entry["generator"], f"{label}.generator")
        _string(entry["check"], f"{label}.check")
        external = entry.get("external", False)
        if not isinstance(external, bool):
            raise ValidationError(f"{label}.external must be a boolean")
        provenance = entry.get("provenance")
        if external:
            _string(provenance, f"{label}.provenance")
        elif provenance is not None:
            raise ValidationError(
                f"{label}.provenance is only valid for an external generator"
            )

        generator_sources = [
            _normalized_path(value, f"{label}.generator_sources[{source_index}]")
            for source_index, value in enumerate(
                _string_list(
                    entry["generator_sources"],
                    f"{label}.generator_sources",
                    nonempty=not external,
                )
            )
        ]
        for source in generator_sources:
            if source not in tracked:
                raise ValidationError(
                    f"{label}.generator_sources is not a tracked regular file: {source}"
                )
            _require_regular_file(root, source, f"{label}.generator_sources")

        inputs = [
            _normalized_path(value, f"{label}.inputs[{input_index}]", allow_glob=True)
            for input_index, value in enumerate(
                _string_list(
                    entry["inputs"],
                    f"{label}.inputs",
                    nonempty=not external,
                )
            )
        ]
        for pattern in inputs:
            matches = _matching_paths(tracked, pattern)
            if not matches:
                raise ValidationError(
                    f"{label}.inputs pattern matches no tracked regular files: {pattern}"
                )
            for matched in sorted(matches):
                _require_regular_file(root, matched, f"{label}.inputs")

        outputs = [
            _normalized_path(value, f"{label}.outputs[{output_index}]")
            for output_index, value in enumerate(
                _string_list(entry["outputs"], f"{label}.outputs", nonempty=True)
            )
        ]
        for output in outputs:
            previous = outputs_seen.get(output)
            if previous is not None:
                raise ValidationError(
                    f"generated output {output} is owned by both {previous} and {name}"
                )
            if output in generator_sources:
                raise ValidationError(
                    f"generated output cannot also be a generator source: {output}"
                )
            outputs_seen[output] = name
            if output not in tracked:
                raise ValidationError(
                    f"{label}.outputs is not a tracked regular file: {output}"
                )
            _require_regular_file(root, output, f"{label}.outputs")
            all_outputs.add(output)

    return all_outputs


def _generated_header_paths(
    root: Path,
    tracked: set[str],
    extensions: set[str],
) -> set[str]:
    generated: set[str] = set()
    for relative in tracked:
        if Path(relative).suffix not in extensions:
            continue
        path = root / relative
        if path.is_symlink() or not path.is_file():
            continue
        try:
            with path.open("rb") as source:
                first_line = source.readline(512).decode("utf-8", errors="replace")
        except OSError as error:
            raise ValidationError(f"failed to inspect {relative}: {error}") from error
        if GENERATED_HEADER.match(first_line):
            generated.add(relative)
    return generated


def _forbidden_tracked_paths(
    tracked: set[str],
    forbidden: list[str],
    allowed: set[str],
) -> list[str]:
    violations = {
        path
        for path in tracked
        if path not in allowed and any(_glob_matches(path, pattern) for pattern in forbidden)
    }
    return sorted(violations)


def _tracked_core_dumps(root: Path, tracked: set[str]) -> list[str]:
    violations: list[str] = []
    for relative in sorted(tracked):
        if CORE_DUMP_NAMES.fullmatch(Path(relative).name) is None:
            continue
        path = root / relative
        if path.is_symlink() or not path.is_file():
            continue
        try:
            with path.open("rb") as source:
                magic = source.read(4)
        except OSError as error:
            raise ValidationError(f"failed to inspect {relative}: {error}") from error
        if magic in EXECUTABLE_MAGICS:
            violations.append(relative)
    return violations


def validate_repository(root: Path, manifest_path: Path) -> tuple[int, int]:
    """Validate one repository and return generated/tracked file counts."""

    root = root.resolve()
    if manifest_path.is_absolute():
        resolved_manifest = manifest_path
    else:
        resolved_manifest = root / manifest_path
    try:
        raw = tomllib.loads(resolved_manifest.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, tomllib.TOMLDecodeError) as error:
        raise ValidationError(f"failed to read {resolved_manifest}: {error}") from error
    if not isinstance(raw, dict):
        raise ValidationError("manifest root must be a table")
    _strict_keys(
        raw,
        allowed={"schema_version", "policy", "generated"},
        required={"schema_version", "policy", "generated"},
        label="manifest",
    )
    if raw["schema_version"] != MANIFEST_SCHEMA_VERSION:
        raise ValidationError(
            f"schema_version must be {MANIFEST_SCHEMA_VERSION}, got {raw['schema_version']!r}"
        )

    tracked = _git_tracked_paths(root)
    forbidden, allowed, extensions = _validate_policy(raw["policy"])
    generated_outputs = _validate_generated_entries(
        raw["generated"],
        root=root,
        tracked=tracked,
    )

    forbidden_paths = _forbidden_tracked_paths(tracked, forbidden, allowed)
    if forbidden_paths:
        rendered = "\n  ".join(forbidden_paths)
        raise ValidationError(f"forbidden generated/build artifacts are tracked:\n  {rendered}")

    core_dumps = _tracked_core_dumps(root, tracked)
    if core_dumps:
        rendered = "\n  ".join(core_dumps)
        raise ValidationError(f"executable core dumps are tracked:\n  {rendered}")

    marked_generated = _generated_header_paths(root, tracked, extensions)
    unregistered = sorted(marked_generated - generated_outputs)
    if unregistered:
        rendered = "\n  ".join(unregistered)
        raise ValidationError(
            f"generated source has no generated-files.toml owner:\n  {rendered}"
        )
    return len(generated_outputs), len(tracked)


def main(argv: list[str] | None = None) -> int:
    """Run the generated-artifact validation command."""

    args = parse_args(argv)
    try:
        generated_count, tracked_count = validate_repository(args.root, args.manifest)
    except ValidationError as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1
    print(
        f"Generated artifact registry is valid "
        f"({generated_count} outputs; {tracked_count} tracked files inspected)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
