"""Constrain explicitly requested, non-release Apple output to one ignored lane."""
from __future__ import annotations

import argparse
import os
from pathlib import Path
import stat
import subprocess

LANE = Path("target/norito-bridge-local")
SCOPE = "local-integration"


def directory(root: Path, path: Path, role: str) -> Path:
    """Require an owned canonical directory in the fixed local integration lane."""
    if root.resolve(strict=True) != root or path != Path(os.path.abspath(path)):
        raise ValueError("local integration paths must be canonical and absolute")
    lane = root / LANE
    expected = {"cargo": lane / "cargo", "build": lane / "build"}
    artifact = lane / "artifacts"
    staged = path.parent == artifact and path.name.startswith(".NoritoBridge.publish.")
    if role in expected:
        admitted = path == expected[role]
    elif role == "artifact":
        admitted = path == artifact or staged
    elif role == "projection":
        admitted = path == lane / "projections" or staged
    else:
        raise ValueError("unknown local integration directory role")
    if not admitted:
        raise ValueError("local integration directory is outside its fixed lane role")
    directories = {lane, path}
    if staged:
        directories.add(artifact)
    for item in directories:
        metadata = item.lstat()
        if (item.resolve(strict=True) != item or not stat.S_ISDIR(metadata.st_mode)
                or stat.S_ISLNK(metadata.st_mode) or metadata.st_uid != os.geteuid()
                or stat.S_IMODE(metadata.st_mode) != 0o700
                or not os.access(item, os.R_OK | os.W_OK | os.X_OK)):
            raise ValueError("local integration directories must be owned canonical mode-0700 directories")
    # Ignoring generated bytes is intentional; a forced tracked file must never be
    # silently excluded from source ownership by treating it as an output.
    environment = {key: value for key, value in os.environ.items() if not key.startswith("GIT_")}
    environment.update(GIT_CONFIG_GLOBAL=os.devnull, GIT_CONFIG_NOSYSTEM="1", GIT_OPTIONAL_LOCKS="0")
    tracked = subprocess.run(
        ["/usr/bin/git", "-C", str(root), "ls-files", "-z", "--", str(LANE)],
        env=environment, check=True, capture_output=True,
    )
    ignored = subprocess.run(
        ["/usr/bin/git", "-C", str(root), "check-ignore", "--no-index", "-q", "--", str(LANE)],
        env=environment, check=False, capture_output=True,
    )
    if tracked.stdout or ignored.returncode != 0:
        raise ValueError("local integration lane must be ignored and contain no tracked files")
    return path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument("--path", type=Path, required=True)
    parser.add_argument("--role", choices=("cargo", "build", "artifact", "projection"), required=True)
    arguments = parser.parse_args()
    try:
        print(directory(arguments.root, arguments.path, arguments.role))
    except (OSError, ValueError, subprocess.CalledProcessError) as error:
        parser.exit(1, f"local integration: {error}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
