//! Immutable compiler-captured identities for this source owner’s existing codecs.

const CASES: &[crate::captured_schema_tests::Case] = &[
    crate::captured_schema_tests::Case::bidirectional::<super::RiskClass>(
        "iroha_data_model::oracle::RiskClass",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OracleChangeClass>(
        "iroha_data_model::oracle::OracleChangeClass",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OracleChangeStage>(
        "iroha_data_model::oracle::OracleChangeStage",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OracleChangeStageFailure>(
        "iroha_data_model::oracle::OracleChangeStageFailure",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OracleChangeFailure>(
        "iroha_data_model::oracle::OracleChangeFailure",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OracleChangeStatus>(
        "iroha_data_model::oracle::OracleChangeStatus",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OracleChangeEvidence>(
        "iroha_data_model::oracle::OracleChangeEvidence",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OracleChangeStageRecord>(
        "iroha_data_model::oracle::OracleChangeStageRecord",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OracleChangeProposal>(
        "iroha_data_model::oracle::OracleChangeProposal",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AggregationRule>(
        "iroha_data_model::oracle::AggregationRule",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OutlierPolicy>(
        "iroha_data_model::oracle::OutlierPolicy",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::AbsoluteOutlier>(
        "iroha_data_model::oracle::AbsoluteOutlier",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::FeedConfig>(
        "iroha_data_model::oracle::FeedConfig",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ConnectorRequestMethod>(
        "iroha_data_model::oracle::ConnectorRequestMethod",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::RedactedHeaderValue>(
        "iroha_data_model::oracle::RedactedHeaderValue",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ConnectorRequest>(
        "iroha_data_model::oracle::ConnectorRequest",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ConnectorResponse>(
        "iroha_data_model::oracle::ConnectorResponse",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::TwitterBindingStatus>(
        "iroha_data_model::oracle::TwitterBindingStatus",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::TwitterBindingAttestation>(
        "iroha_data_model::oracle::TwitterBindingAttestation",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::TwitterBindingRecord>(
        "iroha_data_model::oracle::TwitterBindingRecord",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ObservationOutcome>(
        "iroha_data_model::oracle::ObservationOutcome",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ObservationValue>(
        "iroha_data_model::oracle::ObservationValue",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ObservationErrorCode>(
        "iroha_data_model::oracle::ObservationErrorCode",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ObservationErrorClass>(
        "iroha_data_model::oracle::ObservationErrorClass",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ObservationBody>(
        "iroha_data_model::oracle::ObservationBody",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::Observation>(
        "iroha_data_model::oracle::Observation",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ReportEntry>(
        "iroha_data_model::oracle::ReportEntry",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ReportBody>(
        "iroha_data_model::oracle::ReportBody",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::Report>(
        "iroha_data_model::oracle::Report",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::FeedSuccess>(
        "iroha_data_model::oracle::FeedSuccess",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::FeedError>(
        "iroha_data_model::oracle::FeedError",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::FeedEventOutcome>(
        "iroha_data_model::oracle::FeedEventOutcome",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::FeedEvent>(
        "iroha_data_model::oracle::FeedEvent",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OraclePenaltyKind>(
        "iroha_data_model::oracle::OraclePenaltyKind",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OraclePenalty>(
        "iroha_data_model::oracle::OraclePenalty",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OracleReward>(
        "iroha_data_model::oracle::OracleReward",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OracleProviderStats>(
        "iroha_data_model::oracle::OracleProviderStats",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OracleProviderStatsRecord>(
        "iroha_data_model::oracle::OracleProviderStatsRecord",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OracleDisputeOutcome>(
        "iroha_data_model::oracle::OracleDisputeOutcome",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OracleDispute>(
        "iroha_data_model::oracle::OracleDispute",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OracleDisputeStatus>(
        "iroha_data_model::oracle::OracleDisputeStatus",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::GossipKey>(
        "iroha_data_model::oracle::GossipKey",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::ReplayKey>(
        "iroha_data_model::oracle::ReplayKey",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::CommitteeDraw>(
        "iroha_data_model::oracle::CommitteeDraw",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OracleAbiManifest>(
        "iroha_data_model::oracle::OracleAbiManifest",
    ),
];

#[test]
fn captured_codec_schema_identities() {
    for case in CASES {
        case.check();
    }
}
