//! Immutable compiler-captured identities for this source owner’s existing codecs.

#[test]
fn captured_codec_schema_identities() {
    crate::captured_schema_tests::assert_bidirectional::<super::RiskClass>(
        "iroha_data_model::oracle::RiskClass",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OracleChangeClass>(
        "iroha_data_model::oracle::OracleChangeClass",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OracleChangeStage>(
        "iroha_data_model::oracle::OracleChangeStage",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OracleChangeStageFailure>(
        "iroha_data_model::oracle::OracleChangeStageFailure",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OracleChangeFailure>(
        "iroha_data_model::oracle::OracleChangeFailure",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OracleChangeStatus>(
        "iroha_data_model::oracle::OracleChangeStatus",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OracleChangeEvidence>(
        "iroha_data_model::oracle::OracleChangeEvidence",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OracleChangeStageRecord>(
        "iroha_data_model::oracle::OracleChangeStageRecord",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OracleChangeProposal>(
        "iroha_data_model::oracle::OracleChangeProposal",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AggregationRule>(
        "iroha_data_model::oracle::AggregationRule",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OutlierPolicy>(
        "iroha_data_model::oracle::OutlierPolicy",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AbsoluteOutlier>(
        "iroha_data_model::oracle::AbsoluteOutlier",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FeedConfig>(
        "iroha_data_model::oracle::FeedConfig",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ConnectorRequestMethod>(
        "iroha_data_model::oracle::ConnectorRequestMethod",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::RedactedHeaderValue>(
        "iroha_data_model::oracle::RedactedHeaderValue",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ConnectorRequest>(
        "iroha_data_model::oracle::ConnectorRequest",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ConnectorResponse>(
        "iroha_data_model::oracle::ConnectorResponse",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::TwitterBindingStatus>(
        "iroha_data_model::oracle::TwitterBindingStatus",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::TwitterBindingAttestation>(
        "iroha_data_model::oracle::TwitterBindingAttestation",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::TwitterBindingRecord>(
        "iroha_data_model::oracle::TwitterBindingRecord",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ObservationOutcome>(
        "iroha_data_model::oracle::ObservationOutcome",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ObservationValue>(
        "iroha_data_model::oracle::ObservationValue",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ObservationErrorCode>(
        "iroha_data_model::oracle::ObservationErrorCode",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ObservationErrorClass>(
        "iroha_data_model::oracle::ObservationErrorClass",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ObservationBody>(
        "iroha_data_model::oracle::ObservationBody",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::Observation>(
        "iroha_data_model::oracle::Observation",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ReportEntry>(
        "iroha_data_model::oracle::ReportEntry",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ReportBody>(
        "iroha_data_model::oracle::ReportBody",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::Report>(
        "iroha_data_model::oracle::Report",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FeedSuccess>(
        "iroha_data_model::oracle::FeedSuccess",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FeedError>(
        "iroha_data_model::oracle::FeedError",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FeedEventOutcome>(
        "iroha_data_model::oracle::FeedEventOutcome",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FeedEvent>(
        "iroha_data_model::oracle::FeedEvent",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OraclePenaltyKind>(
        "iroha_data_model::oracle::OraclePenaltyKind",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OraclePenalty>(
        "iroha_data_model::oracle::OraclePenalty",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OracleReward>(
        "iroha_data_model::oracle::OracleReward",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OracleProviderStats>(
        "iroha_data_model::oracle::OracleProviderStats",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OracleProviderStatsRecord>(
        "iroha_data_model::oracle::OracleProviderStatsRecord",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OracleDisputeOutcome>(
        "iroha_data_model::oracle::OracleDisputeOutcome",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OracleDispute>(
        "iroha_data_model::oracle::OracleDispute",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OracleDisputeStatus>(
        "iroha_data_model::oracle::OracleDisputeStatus",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::GossipKey>(
        "iroha_data_model::oracle::GossipKey",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ReplayKey>(
        "iroha_data_model::oracle::ReplayKey",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::CommitteeDraw>(
        "iroha_data_model::oracle::CommitteeDraw",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OracleAbiManifest>(
        "iroha_data_model::oracle::OracleAbiManifest",
    );
}
