#!/bin/bash
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$repo_root"

python3 scripts/formal/check_sumeragi_formal_coverage.py

bash scripts/formal/sumeragi_apalache.sh fast
bash scripts/formal/sumeragi_apalache.sh deep
bash scripts/formal/sumeragi_apalache.sh fork-fast
bash scripts/formal/sumeragi_apalache.sh fork-npos
bash scripts/formal/sumeragi_apalache.sh quorum-fast
bash scripts/formal/sumeragi_apalache.sh rbc-fast
bash scripts/formal/sumeragi_apalache.sh rbc-causality-fast
bash scripts/formal/sumeragi_apalache.sh rbc-deliver-acceptance-fast
bash scripts/formal/sumeragi_apalache.sh rbc-ready-emission-fast
bash scripts/formal/sumeragi_apalache.sh rbc-deliver-emission-fast
bash scripts/formal/sumeragi_apalache.sh rbc-delivered-rebroadcast-fast
bash scripts/formal/sumeragi_apalache.sh rbc-rebroadcast-cursor-fast
bash scripts/formal/sumeragi_apalache.sh rbc-rebroadcast-action-fast
bash scripts/formal/sumeragi_apalache.sh rbc-next-due-fast
bash scripts/formal/sumeragi_apalache.sh rbc-commit-processing-fast
bash scripts/formal/sumeragi_apalache.sh rbc-chunk-target-fast
bash scripts/formal/sumeragi_apalache.sh rbc-chunk-payload-cap-fast
bash scripts/formal/sumeragi_apalache.sh rbc-rebroadcast-selection-fast
bash scripts/formal/sumeragi_apalache.sh rbc-chunk-allocation-fast
bash scripts/formal/sumeragi_apalache.sh rbc-payload-chunking-fast
bash scripts/formal/sumeragi_apalache.sh rbc-payload-layout-fast
bash scripts/formal/sumeragi_apalache.sh rbc-session-chunk-ingest-fast
bash scripts/formal/sumeragi_apalache.sh rbc-session-ready-deliver-fast
bash scripts/formal/sumeragi_apalache.sh rbc-delivered-payload-bytes-fast
bash scripts/formal/sumeragi_apalache.sh rbc-rs16-initial-fanout-fast
bash scripts/formal/sumeragi_apalache.sh rbc-chunk-broadcast-order-fast
bash scripts/formal/sumeragi_apalache.sh pending-rbc-stash-fast
bash scripts/formal/sumeragi_apalache.sh pending-rbc-status-fast
bash scripts/formal/sumeragi_apalache.sh ingress-dedup-cache-fast
bash scripts/formal/sumeragi_apalache.sh ingress-status-counters-fast
bash scripts/formal/sumeragi_apalache.sh consensus-message-labels-fast
bash scripts/formal/sumeragi_apalache.sh phase-latency-status-fast
bash scripts/formal/sumeragi_apalache.sh telemetry-status-fast
bash scripts/formal/sumeragi_apalache.sh lane-detail-status-fast
bash scripts/formal/sumeragi_apalache.sh settlement-status-fast
bash scripts/formal/sumeragi_apalache.sh nexus-economics-status-fast
bash scripts/formal/sumeragi_apalache.sh npos-repair-coverage-status-fast
bash scripts/formal/sumeragi_apalache.sh mode-status-fast
bash scripts/formal/sumeragi_apalache.sh consensus-caps-status-fast
bash scripts/formal/sumeragi_apalache.sh effective-timing-status-fast
bash scripts/formal/sumeragi_apalache.sh tx-queue-backpressure-status-fast
bash scripts/formal/sumeragi_apalache.sh history-status-fast
bash scripts/formal/sumeragi_apalache.sh commit-quorum-status-fast
bash scripts/formal/sumeragi_apalache.sh commit-inflight-status-fast
bash scripts/formal/sumeragi_apalache.sh rbc-status-lookup-fast
bash scripts/formal/sumeragi_apalache.sh rbc-status-retention-fast
bash scripts/formal/sumeragi_apalache.sh rbc-status-persistence-fast
bash scripts/formal/sumeragi_apalache.sh rbc-status-handle-fast
bash scripts/formal/sumeragi_apalache.sh rbc-backlog-status-fast
bash scripts/formal/sumeragi_apalache.sh rbc-abort-status-fast
bash scripts/formal/sumeragi_apalache.sh rbc-mismatch-status-fast
bash scripts/formal/sumeragi_apalache.sh rbc-progress-stage-fast
bash scripts/formal/sumeragi_apalache.sh rbc-hot-repair-fast
bash scripts/formal/sumeragi_apalache.sh rbc-repair-request-fast
bash scripts/formal/sumeragi_apalache.sh rbc-targeted-repair-fast
bash scripts/formal/sumeragi_apalache.sh rbc-outbound-flush-fast
bash scripts/formal/sumeragi_apalache.sh rbc-chunk-post-debug-fast
bash scripts/formal/sumeragi_apalache.sh rbc-deferral-throttle-fast
bash scripts/formal/sumeragi_apalache.sh rbc-missing-init-rebroadcast-fast
bash scripts/formal/sumeragi_apalache.sh rbc-sampling-fast
bash scripts/formal/sumeragi_apalache.sh rbc-store-fast
bash scripts/formal/sumeragi_apalache.sh rbc-store-status-fast
bash scripts/formal/sumeragi_apalache.sh rbc-store-pressure-log-fast
bash scripts/formal/sumeragi_apalache.sh round-gap-status-fast
bash scripts/formal/sumeragi_apalache.sh rbc-recovery-helper-fast
bash scripts/formal/sumeragi_apalache.sh rbc-payload-hydration-fast
bash scripts/formal/sumeragi_apalache.sh rbc-missing-block-recovery-fast
bash scripts/formal/sumeragi_apalache.sh rbc-unverified-roster-fast
bash scripts/formal/sumeragi_apalache.sh rbc-preimage-fast
bash scripts/formal/sumeragi_apalache.sh classic-preimage-fast
bash scripts/formal/sumeragi_apalache.sh vrf-material-derivation-fast
bash scripts/formal/sumeragi_apalache.sh vrf-penalties-report-fast
bash scripts/formal/sumeragi_apalache.sh classic-signature-fast
bash scripts/formal/sumeragi_apalache.sh invalid-signature-labels-fast
bash scripts/formal/sumeragi_apalache.sh invalid-signature-throttle-fast
bash scripts/formal/sumeragi_apalache.sh vote-validation-drop-status-fast
bash scripts/formal/sumeragi_apalache.sh penalty-offender-selection-fast
bash scripts/formal/sumeragi_apalache.sh consensus-penalty-action-fast
bash scripts/formal/sumeragi_apalache.sh penalty-status-fast
bash scripts/formal/sumeragi_apalache.sh local-peer-removed-status-fast
bash scripts/formal/sumeragi_apalache.sh exec-witness-roots-fast
bash scripts/formal/sumeragi_apalache.sh exec-witness-recorder-fast
bash scripts/formal/sumeragi_apalache.sh exec-witness-access-key-fast
bash scripts/formal/sumeragi_apalache.sh smt-path-hash-fast
bash scripts/formal/sumeragi_apalache.sh block-message-rbc-compact-fast
bash scripts/formal/sumeragi_apalache.sh block-message-priority-fast
bash scripts/formal/sumeragi_apalache.sh block-message-height-view-fast
bash scripts/formal/sumeragi_apalache.sh block-message-kind-fast
bash scripts/formal/sumeragi_apalache.sh kura-replica-advert-fast
bash scripts/formal/sumeragi_apalache.sh message-projection-fast
bash scripts/formal/sumeragi_apalache.sh pipeline-event-emission-fast
bash scripts/formal/sumeragi_apalache.sh block-message-wire-fast
bash scripts/formal/sumeragi_apalache.sh block-created-frontier-wire-fast
bash scripts/formal/sumeragi_apalache.sh block-payload-canonicalization-fast
bash scripts/formal/sumeragi_apalache.sh cached-proposal-rebroadcast-fast
bash scripts/formal/sumeragi_apalache.sh frontier-block-sync-hint-fast
bash scripts/formal/sumeragi_apalache.sh frontier-same-slot-activity-fast
bash scripts/formal/sumeragi_apalache.sh frontier-reassembly-activity-fast
bash scripts/formal/sumeragi_apalache.sh frontier-quorum-owner-actionable-fast
bash scripts/formal/sumeragi_apalache.sh frontier-sidecar-retarget-fast
bash scripts/formal/sumeragi_apalache.sh frontier-sidecar-expected-hash-fast
bash scripts/formal/sumeragi_apalache.sh contiguous-frontier-payload-hint-fast
bash scripts/formal/sumeragi_apalache.sh frontier-parent-qc-hint-retarget-fast
bash scripts/formal/sumeragi_apalache.sh live-frontier-idle-missing-qc-fast
bash scripts/formal/sumeragi_apalache.sh missing-qc-reacquire-admission-fast
bash scripts/formal/sumeragi_apalache.sh missing-qc-reacquire-action-fast
bash scripts/formal/sumeragi_apalache.sh missing-commit-qc-actionable-fast
bash scripts/formal/sumeragi_apalache.sh missing-qc-height-stall-fast
bash scripts/formal/sumeragi_apalache.sh missing-qc-stall-range-pull-fast
bash scripts/formal/sumeragi_apalache.sh missing-payload-fetch-window-fast
bash scripts/formal/sumeragi_apalache.sh canonical-frontier-reanchor-fast
bash scripts/formal/sumeragi_apalache.sh frontier-repair-view-change-fast
bash scripts/formal/sumeragi_apalache.sh frontier-recovery-advance-fast
bash scripts/formal/sumeragi_apalache.sh same-height-no-proposal-storm-fast
bash scripts/formal/sumeragi_apalache.sh vrf-admission-fast
bash scripts/formal/sumeragi_apalache.sh vrf-epoch-window-fast
bash scripts/formal/sumeragi_apalache.sh vrf-epoch-boundary-fast
bash scripts/formal/sumeragi_apalache.sh vrf-epoch-restore-fast
bash scripts/formal/sumeragi_apalache.sh vrf-local-state-fast
bash scripts/formal/sumeragi_apalache.sh vote-admission-fast
bash scripts/formal/sumeragi_apalache.sh vote-duplicate-key-fast
bash scripts/formal/sumeragi_apalache.sh evidence-horizon-fast
bash scripts/formal/sumeragi_apalache.sh evidence-canonicalization-fast
bash scripts/formal/sumeragi_apalache.sh evidence-validation-fast
bash scripts/formal/sumeragi_apalache.sh double-vote-recording-fast
bash scripts/formal/sumeragi_apalache.sh invalid-qc-shape-fast
bash scripts/formal/sumeragi_apalache.sh qc-validation-evidence-fast
bash scripts/formal/sumeragi_apalache.sh qc-validation-reason-fast
bash scripts/formal/sumeragi_apalache.sh embedded-qc-roster-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-qc-fallback-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-qc-status-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-locked-qc-fast
bash scripts/formal/sumeragi_apalache.sh known-block-qc-enqueue-fast
bash scripts/formal/sumeragi_apalache.sh known-block-qc-work-fast
bash scripts/formal/sumeragi_apalache.sh known-block-qc-drain-fast
bash scripts/formal/sumeragi_apalache.sh signed-quorum-fetch-fallback-fast
bash scripts/formal/sumeragi_apalache.sh commit-qc-only-fetch-response-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-update-targets-fast
bash scripts/formal/sumeragi_apalache.sh apply-cached-qcs-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-roster-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-roster-status-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-vote-deferral-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-known-hintless-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-implicit-recovery-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-vote-placeholder-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-snapshot-hint-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-snapshot-roster-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-no-roster-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-known-roster-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-known-selected-roster-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-selected-signatures-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-selected-qc-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-selected-quorum-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-recovery-mode-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-selected-apply-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-selected-qc-prefilter-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-selected-qc-process-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-selected-qc-cache-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-stale-view-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-commit-conflict-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-warning-throttle-fast
bash scripts/formal/sumeragi_apalache.sh qc-insufficient-warning-fast
bash scripts/formal/sumeragi_apalache.sh fetch-response-deferral-fast
bash scripts/formal/sumeragi_apalache.sh fetch-block-body-handle-fast
bash scripts/formal/sumeragi_apalache.sh background-frame-cap-fast
bash scripts/formal/sumeragi_apalache.sh background-dispatch-fast
bash scripts/formal/sumeragi_apalache.sh background-bypass-fast
bash scripts/formal/sumeragi_apalache.sh background-fallback-fast
bash scripts/formal/sumeragi_apalache.sh fetch-pending-response-send-fast
bash scripts/formal/sumeragi_apalache.sh fetch-pending-responses-batch-fast
bash scripts/formal/sumeragi_apalache.sh pending-response-flush-fast
bash scripts/formal/sumeragi_apalache.sh deferred-block-sync-helper-fast
bash scripts/formal/sumeragi_apalache.sh deferred-block-sync-cache-fast
bash scripts/formal/sumeragi_apalache.sh deferred-block-sync-replay-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-future-window-fast
bash scripts/formal/sumeragi_apalache.sh block-body-repair-fast
bash scripts/formal/sumeragi_apalache.sh block-body-request-stash-fast
bash scripts/formal/sumeragi_apalache.sh same-height-block-body-repair-fast
bash scripts/formal/sumeragi_apalache.sh block-body-repair-epoch-fast
bash scripts/formal/sumeragi_apalache.sh direct-commit-qc-for-block-fast
bash scripts/formal/sumeragi_apalache.sh materialize-qc-fast
bash scripts/formal/sumeragi_apalache.sh block-body-direct-commit-qc-fast
bash scripts/formal/sumeragi_apalache.sh block-body-detached-commit-qc-fast
bash scripts/formal/sumeragi_apalache.sh block-body-response-dispatch-fast
bash scripts/formal/sumeragi_apalache.sh invalid-proposal-evidence-fast
bash scripts/formal/sumeragi_apalache.sh proposal-mismatch-fast
bash scripts/formal/sumeragi_apalache.sh proposal-cache-fast
bash scripts/formal/sumeragi_apalache.sh proposal-hint-fast
bash scripts/formal/sumeragi_apalache.sh stale-proposal-hint-repair-fast
bash scripts/formal/sumeragi_apalache.sh stale-rbc-hint-repair-fast
bash scripts/formal/sumeragi_apalache.sh proposal-admission-fast
bash scripts/formal/sumeragi_apalache.sh peer-admin-detection-fast
bash scripts/formal/sumeragi_apalache.sh block-created-admission-fast
bash scripts/formal/sumeragi_apalache.sh empty-block-qc-drop-fast
bash scripts/formal/sumeragi_apalache.sh missing-request-clear-fast
bash scripts/formal/sumeragi_apalache.sh missing-block-clear-fast
bash scripts/formal/sumeragi_apalache.sh proposal-budget-fast
bash scripts/formal/sumeragi_apalache.sh proposal-backpressure-fast
bash scripts/formal/sumeragi_apalache.sh proposal-defer-warning-fast
bash scripts/formal/sumeragi_apalache.sh non-rbc-payload-budget-fast
bash scripts/formal/sumeragi_apalache.sh proposal-batch-fast
bash scripts/formal/sumeragi_apalache.sh lane-interleave-fast
bash scripts/formal/sumeragi_apalache.sh commitment-snapshot-builder-fast
bash scripts/formal/sumeragi_apalache.sh collector-plan-fast
bash scripts/formal/sumeragi_apalache.sh collector-selection-fast
bash scripts/formal/sumeragi_apalache.sh topology-mutation-fast
bash scripts/formal/sumeragi_apalache.sh prf-leader-shuffle-fast
bash scripts/formal/sumeragi_apalache.sh topology-fanout-fast
bash scripts/formal/sumeragi_apalache.sh topology-role-filter-fast
bash scripts/formal/sumeragi_apalache.sh active-topology-selection-fast
bash scripts/formal/sumeragi_apalache.sh p2p-topology-trusted-fast
bash scripts/formal/sumeragi_apalache.sh p2p-topology-refresh-fast
bash scripts/formal/sumeragi_apalache.sh quorum-retransmit-fast
bash scripts/formal/sumeragi_apalache.sh retransmit-backpressure-fast
bash scripts/formal/sumeragi_apalache.sh paced-retransmit-targets-fast
bash scripts/formal/sumeragi_apalache.sh quorum-reschedule-backoff-fast
bash scripts/formal/sumeragi_apalache.sh rbc-availability-reschedule-fast
bash scripts/formal/sumeragi_apalache.sh vote-backed-reassembly-stall-fast
bash scripts/formal/sumeragi_apalache.sh completed-quorum-view-advance-fast
bash scripts/formal/sumeragi_apalache.sh quorum-rebroadcast-dispatch-fast
bash scripts/formal/sumeragi_apalache.sh isolated-vote-backed-handoff-fast
bash scripts/formal/sumeragi_apalache.sh preemptive-vote-backed-retransmit-fast
bash scripts/formal/sumeragi_apalache.sh near-quorum-preemptive-escalation-fast
bash scripts/formal/sumeragi_apalache.sh manifest-gate-reschedule-fast
bash scripts/formal/sumeragi_apalache.sh qc-signers-fast
bash scripts/formal/sumeragi_apalache.sh qc-signer-count-fast
bash scripts/formal/sumeragi_apalache.sh build-signers-bitmap-fast
bash scripts/formal/sumeragi_apalache.sh signer-index-normalization-fast
bash scripts/formal/sumeragi_apalache.sh commit-roots-fast
bash scripts/formal/sumeragi_apalache.sh commit-pipeline-recovery-fast
bash scripts/formal/sumeragi_apalache.sh known-block-commit-qc-recovery-fast
bash scripts/formal/sumeragi_apalache.sh stale-view-commit-qc-fetch-fast
bash scripts/formal/sumeragi_apalache.sh commit-anchor-qc-fast
bash scripts/formal/sumeragi_apalache.sh committed-height-qc-fast
bash scripts/formal/sumeragi_apalache.sh pending-progress-fast
bash scripts/formal/sumeragi_apalache.sh pending-block-lifecycle-fast
bash scripts/formal/sumeragi_apalache.sh pending-block-marker-fast
bash scripts/formal/sumeragi_apalache.sh kura-retry-fast
bash scripts/formal/sumeragi_apalache.sh commit-pipeline-scheduling-fast
bash scripts/formal/sumeragi_apalache.sh precommit-vote-count-fast
bash scripts/formal/sumeragi_apalache.sh voting-signer-count-fast
bash scripts/formal/sumeragi_apalache.sh distinct-vote-epochs-fast
bash scripts/formal/sumeragi_apalache.sh new-view-highest-qc-votes-fast
bash scripts/formal/sumeragi_apalache.sh frontier-new-view-catch-up-fast
bash scripts/formal/sumeragi_apalache.sh late-new-view-emission-fast
bash scripts/formal/sumeragi_apalache.sh near-quorum-new-view-rebroadcast-fast
bash scripts/formal/sumeragi_apalache.sh requester-roster-proof-fast
bash scripts/formal/sumeragi_apalache.sh online-validator-relay-counters-fast
bash scripts/formal/sumeragi_apalache.sh commit-result-drain-fast
bash scripts/formal/sumeragi_apalache.sh commit-drain-summary-fast
bash scripts/formal/sumeragi_apalache.sh commit-pipeline-sample-fast
bash scripts/formal/sumeragi_apalache.sh commit-pipeline-status-fast
bash scripts/formal/sumeragi_apalache.sh autoscale-transition-fast
bash scripts/formal/sumeragi_apalache.sh commit-quorum-signers-fast
bash scripts/formal/sumeragi_apalache.sh signature-index-recovery-fast
bash scripts/formal/sumeragi_apalache.sh commit-qc-lookup-fast
bash scripts/formal/sumeragi_apalache.sh precommit-signer-record-fast
bash scripts/formal/sumeragi_apalache.sh roster-validation-memo-fast
bash scripts/formal/sumeragi_apalache.sh roster-validation-cached-fast
bash scripts/formal/sumeragi_apalache.sh roster-validation-core-fast
bash scripts/formal/sumeragi_apalache.sh roster-artifact-selection-fast
bash scripts/formal/sumeragi_apalache.sh block-roster-caches-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-roster-evidence-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-history-roster-fast
bash scripts/formal/sumeragi_apalache.sh persisted-roster-selection-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-update-roster-fast
bash scripts/formal/sumeragi_apalache.sh roster-index-projection-fast
bash scripts/formal/sumeragi_apalache.sh membership-view-hash-fast
bash scripts/formal/sumeragi_apalache.sh membership-mismatch-status-fast
bash scripts/formal/sumeragi_apalache.sh membership-advert-fast
bash scripts/formal/sumeragi_apalache.sh membership-mismatch-ingress-fast
bash scripts/formal/sumeragi_apalache.sh consensus-params-ingress-fast
bash scripts/formal/sumeragi_apalache.sh prevalidated-commit-artifact-fast
bash scripts/formal/sumeragi_apalache.sh commit-job-dispatch-fast
bash scripts/formal/sumeragi_apalache.sh commit-worker-config-fast
bash scripts/formal/sumeragi_apalache.sh commit-stage-timing-threshold-fast
bash scripts/formal/sumeragi_apalache.sh commit-inflight-timeout-fast
bash scripts/formal/sumeragi_apalache.sh post-commit-pacemaker-kick-fast
bash scripts/formal/sumeragi_apalache.sh idle-view-proposal-budget-fast
bash scripts/formal/sumeragi_apalache.sh pacemaker-core-fast
bash scripts/formal/sumeragi_apalache.sh pacemaker-evaluation-fast
bash scripts/formal/sumeragi_apalache.sh pacing-governor-fast
bash scripts/formal/sumeragi_apalache.sh cached-slot-timeout-fast
bash scripts/formal/sumeragi_apalache.sh pending-fast-path-timeout-fast
bash scripts/formal/sumeragi_apalache.sh stalled-pending-timeout-fast
bash scripts/formal/sumeragi_apalache.sh stalled-pending-frontier-timeout-fast
bash scripts/formal/sumeragi_apalache.sh missing-qc-timing-fast
bash scripts/formal/sumeragi_apalache.sh idle-backlog-signals-fast
bash scripts/formal/sumeragi_apalache.sh proposal-liveness-fast
bash scripts/formal/sumeragi_apalache.sh frontier-slot-tracker-fast
bash scripts/formal/sumeragi_apalache.sh frontier-slot-helpers-fast
bash scripts/formal/sumeragi_apalache.sh frontier-proposal-grace-fast
bash scripts/formal/sumeragi_apalache.sh slot-tracker-state-fast
bash scripts/formal/sumeragi_apalache.sh timeout-derivation-fast
bash scripts/formal/sumeragi_apalache.sh round-view-helpers-fast
bash scripts/formal/sumeragi_apalache.sh phase-tracker-fast
bash scripts/formal/sumeragi_apalache.sh round-trace-status-fast
bash scripts/formal/sumeragi_apalache.sh failure-recovery-helpers-fast
bash scripts/formal/sumeragi_apalache.sh requeue-transactions-fast
bash scripts/formal/sumeragi_apalache.sh tick-deadline-helpers-fast
bash scripts/formal/sumeragi_apalache.sh worker-tick-gap-fast
bash scripts/formal/sumeragi_apalache.sh proposal-parent-resolution-fast
bash scripts/formal/sumeragi_apalache.sh highest-qc-dependency-deferral-fast
bash scripts/formal/sumeragi_apalache.sh precommit-qc-view-change-fast
bash scripts/formal/sumeragi_apalache.sh commit-evidence-replay-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-recovery-fast
bash scripts/formal/sumeragi_apalache.sh certified-fetch-fast
bash scripts/formal/sumeragi_apalache.sh missing-block-ingress-fetch-fast
bash scripts/formal/sumeragi_apalache.sh payload-progress-availability-fast
bash scripts/formal/sumeragi_apalache.sh highest-qc-fetch-body-known-fast
bash scripts/formal/sumeragi_apalache.sh local-payload-availability-fast
bash scripts/formal/sumeragi_apalache.sh block-known-locally-fast
bash scripts/formal/sumeragi_apalache.sh block-known-for-lock-fast
bash scripts/formal/sumeragi_apalache.sh missing-locked-qc-recovery-fast
bash scripts/formal/sumeragi_apalache.sh local-signed-block-lookup-fast
bash scripts/formal/sumeragi_apalache.sh authoritative-payload-progress-fast
bash scripts/formal/sumeragi_apalache.sh authoritative-block-payload-fast
bash scripts/formal/sumeragi_apalache.sh pending-block-active-for-tip-fast
bash scripts/formal/sumeragi_apalache.sh pending-fast-unblock-fast
bash scripts/formal/sumeragi_apalache.sh blocking-pending-blocks-fast
bash scripts/formal/sumeragi_apalache.sh quorum-recovery-vote-drain-fast
bash scripts/formal/sumeragi_apalache.sh frontier-body-gap-payload-drain-fast
bash scripts/formal/sumeragi_apalache.sh rbc-authoritative-payload-progress-fast
bash scripts/formal/sumeragi_apalache.sh slot-authoritative-payload-fast
bash scripts/formal/sumeragi_apalache.sh missing-block-fetch-fast
bash scripts/formal/sumeragi_apalache.sh recovery-status-counters-fast
bash scripts/formal/sumeragi_apalache.sh recovery-fsm-reason-fast
bash scripts/formal/sumeragi_apalache.sh qc-rebuild-status-fast
bash scripts/formal/sumeragi_apalache.sh qc-rebuild-quorum-fast
bash scripts/formal/sumeragi_apalache.sh collector-targeting-status-fast
bash scripts/formal/sumeragi_apalache.sh deferred-recovery-status-fast
bash scripts/formal/sumeragi_apalache.sh missing-qc-liveness-status-fast
bash scripts/formal/sumeragi_apalache.sh sidecar-no-proposal-status-fast
bash scripts/formal/sumeragi_apalache.sh deterministic-committee-status-fast
bash scripts/formal/sumeragi_apalache.sh timing-status-counters-fast
bash scripts/formal/sumeragi_apalache.sh roster-recovery-status-fast
bash scripts/formal/sumeragi_apalache.sh range-pull-recovery-fast
bash scripts/formal/sumeragi_apalache.sh range-pull-status-fast
bash scripts/formal/sumeragi_apalache.sh round-recovery-bundle-window-fast
bash scripts/formal/sumeragi_apalache.sh committed-edge-conflict-fast
bash scripts/formal/sumeragi_apalache.sh lock-rejected-sink-fast
bash scripts/formal/sumeragi_apalache.sh active-lock-reject-recovery-fast
bash scripts/formal/sumeragi_apalache.sh missing-block-hard-cap-fast
bash scripts/formal/sumeragi_apalache.sh missing-block-hard-cap-cleanup-fast
bash scripts/formal/sumeragi_apalache.sh missing-block-view-change-fast
bash scripts/formal/sumeragi_apalache.sh native-amx-attestation-fast
bash scripts/formal/sumeragi_apalache.sh native-amx-journal-fast
bash scripts/formal/sumeragi_apalache.sh native-amx-routing-plan-fast
bash scripts/formal/sumeragi_apalache.sh native-amx-receipt-fast
bash scripts/formal/sumeragi_apalache.sh native-amx-ingress-fast
bash scripts/formal/sumeragi_apalache.sh vnext-chain-order-fast
bash scripts/formal/sumeragi_apalache.sh vnext-stake-weight-fast
bash scripts/formal/sumeragi_apalache.sh vnext-rechain-fast
bash scripts/formal/sumeragi_apalache.sh vnext-rechain-error-label-fast
bash scripts/formal/sumeragi_apalache.sh vnext-signature-fast
bash scripts/formal/sumeragi_apalache.sh vnext-signing-preimage-fast
bash scripts/formal/sumeragi_apalache.sh vnext-control-ingress-fast
bash scripts/formal/sumeragi_apalache.sh vnext-slot-lifecycle-fast
bash scripts/formal/sumeragi_apalache.sh vnext-validation-fast
bash scripts/formal/sumeragi_apalache.sh vnext-deadline-protection-fast
bash scripts/formal/sumeragi_apalache.sh vnext-performance-config-fast
bash scripts/formal/sumeragi_apalache.sh validation-worker-config-fast
bash scripts/formal/sumeragi_apalache.sh validation-stall-redrive-fast
bash scripts/formal/sumeragi_apalache.sh validation-redrive-label-fast
bash scripts/formal/sumeragi_apalache.sh validation-ownership-cleanup-fast
bash scripts/formal/sumeragi_apalache.sh verify-cache-key-fast
bash scripts/formal/sumeragi_apalache.sh vote-verify-async-fast
bash scripts/formal/sumeragi_apalache.sh vote-verify-worker-config-fast
bash scripts/formal/sumeragi_apalache.sh qc-verify-async-fast
bash scripts/formal/sumeragi_apalache.sh qc-verify-worker-config-fast
bash scripts/formal/sumeragi_apalache.sh worker-drain-fast
bash scripts/formal/sumeragi_apalache.sh actor-gate-fast
bash scripts/formal/sumeragi_apalache.sh worker-budget-fast
bash scripts/formal/sumeragi_apalache.sh worker-ingress-fast
bash scripts/formal/sumeragi_apalache.sh worker-loop-stage-fast
bash scripts/formal/sumeragi_apalache.sh worker-queue-status-fast
bash scripts/formal/sumeragi_apalache.sh npos-vrf-fast
bash scripts/formal/sumeragi_apalache.sh kura-commit-fast
bash scripts/formal/sumeragi_apalache.sh kura-store-status-fast
bash scripts/formal/sumeragi_apalache.sh restart-replay-fast
bash scripts/formal/sumeragi_apalache.sh post-commit-cleanup-fast
bash scripts/formal/sumeragi_apalache.sh frontier-gap-realign-fast
bash scripts/formal/sumeragi_apalache.sh same-height-vote-conflict-fast
bash scripts/formal/sumeragi_apalache.sh same-height-vote-lock-fast
bash scripts/formal/sumeragi_apalache.sh proposal-stale-vote-fast
bash scripts/formal/sumeragi_apalache.sh same-height-vote-recovery-gap-fast
bash scripts/formal/sumeragi_apalache.sh tip-extension-helpers-fast
bash scripts/formal/sumeragi_apalache.sh da-gate-fast
bash scripts/formal/sumeragi_apalache.sh da-gate-status-fast
bash scripts/formal/sumeragi_apalache.sh manifest-guard-fast
bash scripts/formal/sumeragi_apalache.sh consensus-handshake-caps-fast
bash scripts/formal/sumeragi_apalache.sh handshake-fast
bash scripts/formal/sumeragi_apalache.sh mode-flip-fast
bash scripts/formal/sumeragi_apalache.sh effective-mode-fast
bash scripts/formal/sumeragi_apalache.sh effective-timing-fast
bash scripts/formal/sumeragi_apalache.sh new-view-stats-fast
bash scripts/formal/sumeragi_apalache.sh new-view-tracker-fast
bash scripts/formal/sumeragi_apalache.sh timing-monitor-fast
bash scripts/formal/sumeragi_apalache.sh hotspot-log-summary-fast
bash scripts/formal/sumeragi_apalache.sh adaptive-observability-fast
bash scripts/formal/sumeragi_apalache.sh pacing-backpressure-fast
bash scripts/formal/sumeragi_apalache.sh counter-backpressure-cooldown-fast
bash scripts/formal/sumeragi_apalache.sh pacemaker-backpressure-tracker-fast
bash scripts/formal/sumeragi_apalache.sh locked-qc-helper-fast
bash scripts/formal/sumeragi_apalache.sh precommit-qc-extends-locked-fast
bash scripts/formal/sumeragi_apalache.sh drop-precommit-vote-for-lock-fast
bash scripts/formal/sumeragi_apalache.sh stake-snapshot-fast
bash scripts/formal/sumeragi_apalache.sh validator-election-fast
bash scripts/formal/sumeragi_apalache.sh live-vote-roster-fast
bash scripts/formal/sumeragi_apalache.sh canonical-round-roster-fast
bash scripts/formal/sumeragi_apalache.sh vote-roster-selection-fast
bash scripts/formal/sumeragi_apalache.sh vote-roster-cache-fast
bash scripts/formal/sumeragi_apalache.sh commit-topology-state-fast
bash scripts/formal/sumeragi_apalache.sh precommit-signer-history-fast
bash scripts/formal/sumeragi_apalache.sh precommit-fast
bash scripts/formal/sumeragi_apalache.sh proposal-fast
bash scripts/formal/sumeragi_apalache.sh engine-initial-state-fast
bash scripts/formal/sumeragi_apalache.sh engine-read-accessors-fast
bash scripts/formal/sumeragi_apalache.sh engine-tick-fast
bash scripts/formal/sumeragi_apalache.sh engine-tick-state-preservation-fast
bash scripts/formal/sumeragi_apalache.sh engine-new-view-subject-fast
bash scripts/formal/sumeragi_apalache.sh engine-handle-dispatch-fast
bash scripts/formal/sumeragi_apalache.sh engine-handle-forwarding-fast
bash scripts/formal/sumeragi_apalache.sh engine-handle-output-relay-fast
bash scripts/formal/sumeragi_apalache.sh engine-certificate-dispatch-fast
bash scripts/formal/sumeragi_apalache.sh engine-certificate-prefilter-state-fast
bash scripts/formal/sumeragi_apalache.sh engine-certificate-prefilter-state-preservation-fast
bash scripts/formal/sumeragi_apalache.sh engine-view-advance-saturation-fast
bash scripts/formal/sumeragi_apalache.sh engine-new-view-fast
bash scripts/formal/sumeragi_apalache.sh engine-new-view-highest-qc-fast
bash scripts/formal/sumeragi_apalache.sh engine-new-view-state-preservation-fast
bash scripts/formal/sumeragi_apalache.sh engine-new-view-advance-fast
bash scripts/formal/sumeragi_apalache.sh engine-proposal-fast
bash scripts/formal/sumeragi_apalache.sh engine-proposal-output-fast
bash scripts/formal/sumeragi_apalache.sh engine-proposal-state-fast
bash scripts/formal/sumeragi_apalache.sh engine-proposal-state-preservation-fast
bash scripts/formal/sumeragi_apalache.sh engine-proposal-validation-owner-fast
bash scripts/formal/sumeragi_apalache.sh engine-proposal-lock-fast
bash scripts/formal/sumeragi_apalache.sh qc-round-compatibility-fast
bash scripts/formal/sumeragi_apalache.sh engine-qc-ref-projection-fast
bash scripts/formal/sumeragi_apalache.sh engine-qc-ref-comparator-fast
bash scripts/formal/sumeragi_apalache.sh engine-highest-qc-record-fast
bash scripts/formal/sumeragi_apalache.sh engine-commit-subject-fast
bash scripts/formal/sumeragi_apalache.sh engine-payload-lookup-fast
bash scripts/formal/sumeragi_apalache.sh engine-prepare-fast
bash scripts/formal/sumeragi_apalache.sh engine-prepare-lock-highest-fast
bash scripts/formal/sumeragi_apalache.sh engine-prepare-phase-fast
bash scripts/formal/sumeragi_apalache.sh engine-prepare-state-preservation-fast
bash scripts/formal/sumeragi_apalache.sh engine-prepare-vote-cache-fast
bash scripts/formal/sumeragi_apalache.sh engine-commit-fast
bash scripts/formal/sumeragi_apalache.sh engine-commit-highest-qc-fast
bash scripts/formal/sumeragi_apalache.sh engine-commit-phase-fast
bash scripts/formal/sumeragi_apalache.sh engine-commit-state-preservation-fast
bash scripts/formal/sumeragi_apalache.sh engine-commit-available-commit-fast
bash scripts/formal/sumeragi_apalache.sh engine-commit-pending-fetch-fast
bash scripts/formal/sumeragi_apalache.sh engine-commit-validation-cleanup-fast
bash scripts/formal/sumeragi_apalache.sh engine-committed-block-fast
bash scripts/formal/sumeragi_apalache.sh engine-committed-block-record-fast
bash scripts/formal/sumeragi_apalache.sh engine-reconfiguration-staging-fast
bash scripts/formal/sumeragi_apalache.sh engine-reconfiguration-dedup-fast
bash scripts/formal/sumeragi_apalache.sh engine-committed-block-cleanup-fast
bash scripts/formal/sumeragi_apalache.sh engine-committed-block-state-preservation-fast
bash scripts/formal/sumeragi_apalache.sh engine-payload-record-fast
bash scripts/formal/sumeragi_apalache.sh engine-payload-fast
bash scripts/formal/sumeragi_apalache.sh engine-payload-state-preservation-fast
bash scripts/formal/sumeragi_apalache.sh engine-validation-result-fast
bash scripts/formal/sumeragi_apalache.sh engine-validation-state-preservation-fast
bash scripts/formal/sumeragi_apalache.sh engine-validation-ownership-fast
bash scripts/formal/sumeragi_apalache.sh engine-validation-invalid-advance-fast
bash scripts/formal/sumeragi_apalache.sh reconfig-fast
bash scripts/formal/sumeragi_apalache.sh recovery-fast
bash scripts/formal/sumeragi_apalache.sh view-change-fast
bash scripts/formal/sumeragi_apalache.sh validation-fast
bash scripts/formal/sumeragi_apalache.sh validation-priority-fast
bash scripts/formal/sumeragi_apalache.sh vote-backed-evidence-fast
bash scripts/formal/sumeragi_apalache.sh vote-payload-actionable-fast
bash scripts/formal/sumeragi_apalache.sh actionable-vote-backed-proposal-fast
bash scripts/formal/sumeragi_apalache.sh slot-proposal-evidence-fast
bash scripts/formal/sumeragi_apalache.sh round-liveness-fast
bash scripts/formal/sumeragi_apalache.sh roster-recovery-fsm-fast
bash scripts/formal/sumeragi_apalache.sh consensus-recovery-prune-fast
bash scripts/formal/sumeragi_apalache.sh frontier-live-owner-work-fast
bash scripts/formal/sumeragi_apalache.sh keep-frontier-pending-active-fast
bash scripts/formal/sumeragi_apalache.sh stale-view-pending-prune-fast
bash scripts/formal/sumeragi_apalache.sh superseded-frontier-payload-retention-fast
bash scripts/formal/sumeragi_apalache.sh stale-missing-block-request-prune-fast
bash scripts/formal/sumeragi_apalache.sh stale-missing-commit-qc-prune-fast
bash scripts/formal/sumeragi_apalache.sh stale-rbc-session-prune-fast
bash scripts/formal/sumeragi_apalache.sh highest-qc-defer-marker-prune-fast
bash scripts/formal/sumeragi_apalache.sh fast-finality-inline-validation-fast
bash scripts/formal/sumeragi_apalache.sh observer-signature-recovery-fast
bash scripts/formal/sumeragi_apalache.sh validation-failure-finalize-fast
bash scripts/formal/sumeragi_apalache.sh validation-reject-reason-label-fast
bash scripts/formal/sumeragi_apalache.sh validation-reject-status-fast
bash scripts/formal/sumeragi_apalache.sh peer-key-policy-status-fast
bash scripts/formal/sumeragi_apalache.sh view-change-cause-status-fast
bash scripts/formal/sumeragi_apalache.sh view-change-proof-status-fast
bash scripts/formal/sumeragi_apalache.sh qc-status-fast
bash scripts/formal/sumeragi_apalache.sh validation-evidence-qc-fast
bash scripts/formal/sumeragi_apalache.sh admission-fast
bash scripts/formal/sumeragi_apalache.sh highest-fast
bash scripts/formal/sumeragi_apalache.sh highest-optional-fast
bash scripts/formal/sumeragi_apalache.sh frontier-fast
bash scripts/formal/sumeragi_apalache.sh frontier-deep
bash scripts/formal/sumeragi_apalache.sh frontier-wide
bash scripts/formal/sumeragi_tlc.sh frontier-fast
bash scripts/formal/sumeragi_tlc.sh frontier-small
bash ci/check_sumeragi_formal_expected_failures.sh

echo "[formal] sumeragi formal checks passed"
