#!/bin/bash
set -euo pipefail

root_dir="$(cd "$(dirname "$0")/.." && pwd)"
cd "$root_dir"

bash scripts/formal/sumeragi_apalache.sh frontier-bug-stale-owner
bash scripts/formal/sumeragi_apalache.sh frontier-bug-vote-queue
bash scripts/formal/sumeragi_apalache.sh frontier-bug-payload-recovery
bash scripts/formal/sumeragi_apalache.sh frontier-bug-retransmit-followthrough
bash scripts/formal/sumeragi_apalache.sh frontier-bug-future-promotion
bash scripts/formal/sumeragi_apalache.sh frontier-bug-future-reanchor-clear
bash scripts/formal/sumeragi_apalache.sh frontier-bug-future-evidence-drop
bash scripts/formal/sumeragi_apalache.sh frontier-bug-promotion-reset
bash scripts/formal/sumeragi_apalache.sh frontier-bug-future-stale-owner
bash scripts/formal/sumeragi_apalache.sh frontier-bug-progress-touch
bash scripts/formal/sumeragi_apalache.sh frontier-bug-height-only-recovery
bash scripts/formal/sumeragi_apalache.sh fork-bug-double-sign
bash scripts/formal/sumeragi_apalache.sh quorum-bug-count-under-threshold
bash scripts/formal/sumeragi_apalache.sh quorum-bug-count-over-validators
bash scripts/formal/sumeragi_apalache.sh quorum-bug-stake-exact-two-thirds
bash scripts/formal/sumeragi_apalache.sh quorum-bug-stake-over-total
bash scripts/formal/sumeragi_apalache.sh quorum-bug-stake-invalid-input
bash scripts/formal/sumeragi_apalache.sh quorum-bug-stake-overflow
bash scripts/formal/sumeragi_apalache.sh rbc-bug-duplicate-ready
bash scripts/formal/sumeragi_apalache.sh rbc-bug-under-quorum-deliver
bash scripts/formal/sumeragi_apalache.sh rbc-bug-wrong-commit-formula
bash scripts/formal/sumeragi_apalache.sh rbc-bug-force-one-ignored
bash scripts/formal/sumeragi_apalache.sh qc-signers-bug-count-observers
bash scripts/formal/sumeragi_apalache.sh qc-signers-bug-ignore-bitmap-length
bash scripts/formal/sumeragi_apalache.sh qc-signers-bug-ignore-out-of-bounds
bash scripts/formal/sumeragi_apalache.sh qc-signers-bug-under-quorum-accept
bash scripts/formal/sumeragi_apalache.sh commit-roots-bug-mix-root-signers
bash scripts/formal/sumeragi_apalache.sh commit-roots-bug-count-wrong-context
bash scripts/formal/sumeragi_apalache.sh commit-roots-bug-tie-high-root
bash scripts/formal/sumeragi_apalache.sh commit-roots-bug-stake-ignores-weight
bash scripts/formal/sumeragi_apalache.sh commit-roots-bug-under-quorum-accept
bash scripts/formal/sumeragi_apalache.sh commit-roots-bug-validate-mismatched-roots
bash scripts/formal/sumeragi_apalache.sh commit-pipeline-recovery-bug-skip-local-qc-formation
bash scripts/formal/sumeragi_apalache.sh commit-pipeline-recovery-bug-recover-despite-local-quorum
bash scripts/formal/sumeragi_apalache.sh commit-pipeline-recovery-bug-request-recovery-before-timeout
bash scripts/formal/sumeragi_apalache.sh commit-pipeline-recovery-bug-request-recovery-without-local-vote
bash scripts/formal/sumeragi_apalache.sh commit-pipeline-recovery-bug-request-recovery-with-commit-qc
bash scripts/formal/sumeragi_apalache.sh commit-pipeline-recovery-bug-request-recovery-with-missing-data
bash scripts/formal/sumeragi_apalache.sh commit-pipeline-recovery-bug-request-recovery-invalid-pending
bash scripts/formal/sumeragi_apalache.sh commit-pipeline-recovery-bug-request-recovery-off-tip
bash scripts/formal/sumeragi_apalache.sh commit-pipeline-recovery-bug-skip-missing-qc-request
bash scripts/formal/sumeragi_apalache.sh commit-pipeline-recovery-bug-drop-commit-qc-marker
bash scripts/formal/sumeragi_apalache.sh commit-pipeline-recovery-bug-skip-quorum-retransmit
bash scripts/formal/sumeragi_apalache.sh commit-pipeline-recovery-bug-use-collector-targets
bash scripts/formal/sumeragi_apalache.sh commit-pipeline-recovery-bug-rebroadcast-without-votes
bash scripts/formal/sumeragi_apalache.sh commit-pipeline-recovery-bug-rebroadcast-after-qc
bash scripts/formal/sumeragi_apalache.sh commit-evidence-replay-bug-replay-inactive
bash scripts/formal/sumeragi_apalache.sh commit-evidence-replay-bug-ignore-cooldown
bash scripts/formal/sumeragi_apalache.sh commit-evidence-replay-bug-replay-without-targets
bash scripts/formal/sumeragi_apalache.sh commit-evidence-replay-bug-skip-first-evidence
bash scripts/formal/sumeragi_apalache.sh commit-evidence-replay-bug-skip-progress
bash scripts/formal/sumeragi_apalache.sh commit-evidence-replay-bug-skip-stalled-retry
bash scripts/formal/sumeragi_apalache.sh commit-evidence-replay-bug-replay-no-evidence
bash scripts/formal/sumeragi_apalache.sh commit-evidence-replay-bug-votes-use-payload-fallback
bash scripts/formal/sumeragi_apalache.sh commit-evidence-replay-bug-commit-qc-uses-votes
bash scripts/formal/sumeragi_apalache.sh commit-evidence-replay-bug-drop-commit-qc-replay
bash scripts/formal/sumeragi_apalache.sh commit-evidence-replay-bug-use-local-targets
bash scripts/formal/sumeragi_apalache.sh commit-evidence-replay-bug-use-duplicate-targets
bash scripts/formal/sumeragi_apalache.sh block-sync-recovery-bug-accept-stale-without-request
bash scripts/formal/sumeragi_apalache.sh block-sync-recovery-bug-drop-requested-stale
bash scripts/formal/sumeragi_apalache.sh block-sync-recovery-bug-accept-future-unrequested
bash scripts/formal/sumeragi_apalache.sh block-sync-recovery-bug-revive-aborted-without-commit-qc
bash scripts/formal/sumeragi_apalache.sh block-sync-recovery-bug-keep-aborted-with-commit-qc
bash scripts/formal/sumeragi_apalache.sh block-sync-recovery-bug-skip-vote-backed-owner
bash scripts/formal/sumeragi_apalache.sh block-sync-recovery-bug-steal-owner-with-payload-only
bash scripts/formal/sumeragi_apalache.sh block-sync-recovery-bug-skip-certified-owner
bash scripts/formal/sumeragi_apalache.sh block-sync-recovery-bug-activate-uncertified-conflict
bash scripts/formal/sumeragi_apalache.sh block-sync-recovery-bug-drop-commit-qc-marker
bash scripts/formal/sumeragi_apalache.sh block-sync-recovery-bug-skip-missing-commit-qc-request
bash scripts/formal/sumeragi_apalache.sh block-sync-recovery-bug-keep-missing-request
bash scripts/formal/sumeragi_apalache.sh block-sync-recovery-bug-clear-inflight-for-payload-only
bash scripts/formal/sumeragi_apalache.sh block-sync-recovery-bug-keep-inflight-for-certified
bash scripts/formal/sumeragi_apalache.sh block-sync-recovery-bug-promote-unvalidated-qc
bash scripts/formal/sumeragi_apalache.sh native-amx-attestation-bug-seal-non-native-plan
bash scripts/formal/sumeragi_apalache.sh native-amx-attestation-bug-seal-empty-roster
bash scripts/formal/sumeragi_apalache.sh native-amx-attestation-bug-skip-prepare-request
bash scripts/formal/sumeragi_apalache.sh native-amx-attestation-bug-skip-commit-request
bash scripts/formal/sumeragi_apalache.sh native-amx-attestation-bug-request-commit-before-prepare
bash scripts/formal/sumeragi_apalache.sh native-amx-attestation-bug-retry-prepare-after-quorum
bash scripts/formal/sumeragi_apalache.sh native-amx-attestation-bug-seal-with-prepare-only
bash scripts/formal/sumeragi_apalache.sh native-amx-attestation-bug-seal-with-commit-only
bash scripts/formal/sumeragi_apalache.sh native-amx-attestation-bug-seal-partial-multi-leg
bash scripts/formal/sumeragi_apalache.sh native-amx-attestation-bug-accept-duplicate-prepare
bash scripts/formal/sumeragi_apalache.sh native-amx-attestation-bug-accept-duplicate-commit
bash scripts/formal/sumeragi_apalache.sh native-amx-attestation-bug-accept-wrong-prepare-body
bash scripts/formal/sumeragi_apalache.sh native-amx-attestation-bug-accept-wrong-commit-body
bash scripts/formal/sumeragi_apalache.sh native-amx-attestation-bug-accept-outsider-signer
bash scripts/formal/sumeragi_apalache.sh native-amx-attestation-bug-use-arrival-order-bitmap
bash scripts/formal/sumeragi_apalache.sh native-amx-attestation-bug-collapse-retry-bodies
bash scripts/formal/sumeragi_apalache.sh native-amx-attestation-bug-collapse-participant-legs
bash scripts/formal/sumeragi_apalache.sh native-amx-journal-bug-drop-native-plan
bash scripts/formal/sumeragi_apalache.sh native-amx-journal-bug-collapse-native-to-single
bash scripts/formal/sumeragi_apalache.sh native-amx-journal-bug-single-plan-as-native
bash scripts/formal/sumeragi_apalache.sh native-amx-journal-bug-drop-participants
bash scripts/formal/sumeragi_apalache.sh native-amx-journal-bug-reorder-participants
bash scripts/formal/sumeragi_apalache.sh native-amx-journal-bug-keep-duplicate-participant
bash scripts/formal/sumeragi_apalache.sh native-amx-journal-bug-recompute-digest-wrong
bash scripts/formal/sumeragi_apalache.sh native-amx-journal-bug-drop-gossip-payload
bash scripts/formal/sumeragi_apalache.sh native-amx-journal-bug-drop-entrypoint
bash scripts/formal/sumeragi_apalache.sh native-amx-journal-bug-remove-by-hash-only
bash scripts/formal/sumeragi_apalache.sh native-amx-journal-bug-ignore-exact-remove
bash scripts/formal/sumeragi_apalache.sh native-amx-journal-bug-replay-unsupported-version
bash scripts/formal/sumeragi_apalache.sh native-amx-journal-bug-first-put-wins
bash scripts/formal/sumeragi_apalache.sh native-amx-journal-bug-compaction-drops-live
bash scripts/formal/sumeragi_apalache.sh native-amx-journal-bug-compaction-keeps-removed
bash scripts/formal/sumeragi_apalache.sh native-amx-journal-bug-keep-torn-tail
bash scripts/formal/sumeragi_apalache.sh native-amx-journal-bug-drop-prior-on-tail-repair
bash scripts/formal/sumeragi_apalache.sh precommit-bug-invalid-validation
bash scripts/formal/sumeragi_apalache.sh precommit-bug-observer
bash scripts/formal/sumeragi_apalache.sh precommit-bug-duplicate
bash scripts/formal/sumeragi_apalache.sh precommit-bug-unsuperseded-conflict
bash scripts/formal/sumeragi_apalache.sh precommit-bug-older-quorum-completion
bash scripts/formal/sumeragi_apalache.sh precommit-bug-locked-conflict
bash scripts/formal/sumeragi_apalache.sh precommit-bug-missing-locked-payload
bash scripts/formal/sumeragi_apalache.sh precommit-bug-non-extending-lock
bash scripts/formal/sumeragi_apalache.sh precommit-bug-reject-safe
bash scripts/formal/sumeragi_apalache.sh proposal-bug-observer
bash scripts/formal/sumeragi_apalache.sh proposal-bug-active-vote-conflict
bash scripts/formal/sumeragi_apalache.sh proposal-bug-pending-vote-verification
bash scripts/formal/sumeragi_apalache.sh proposal-bug-missing-highest-qc
bash scripts/formal/sumeragi_apalache.sh proposal-bug-non-extending-highest
bash scripts/formal/sumeragi_apalache.sh proposal-bug-split-vote-lock
bash scripts/formal/sumeragi_apalache.sh proposal-bug-committed-edge-conflict
bash scripts/formal/sumeragi_apalache.sh proposal-bug-reject-safe
bash scripts/formal/sumeragi_apalache.sh proposal-bug-reject-stale-retired
bash scripts/formal/sumeragi_apalache.sh proposal-bug-reject-locked-fallback
bash scripts/formal/sumeragi_apalache.sh engine-tick-bug-skip-round-advance
bash scripts/formal/sumeragi_apalache.sh engine-tick-bug-skip-new-view-vote
bash scripts/formal/sumeragi_apalache.sh engine-tick-bug-skip-advance-output
bash scripts/formal/sumeragi_apalache.sh engine-tick-bug-wrong-phase
bash scripts/formal/sumeragi_apalache.sh engine-tick-bug-keep-validation
bash scripts/formal/sumeragi_apalache.sh engine-tick-bug-drop-pending-finality
bash scripts/formal/sumeragi_apalache.sh engine-tick-bug-use-zero-despite-highest
bash scripts/formal/sumeragi_apalache.sh engine-tick-bug-use-highest-without-highest
bash scripts/formal/sumeragi_apalache.sh engine-tick-bug-omit-highest-binding
bash scripts/formal/sumeragi_apalache.sh engine-tick-bug-bind-highest-without-highest
bash scripts/formal/sumeragi_apalache.sh engine-new-view-bug-accept-wrong-context
bash scripts/formal/sumeragi_apalache.sh engine-new-view-bug-accept-wrong-quorum
bash scripts/formal/sumeragi_apalache.sh engine-new-view-bug-accept-stale-view
bash scripts/formal/sumeragi_apalache.sh engine-new-view-bug-accept-incompatible-highest
bash scripts/formal/sumeragi_apalache.sh engine-new-view-bug-reject-safe-no-highest
bash scripts/formal/sumeragi_apalache.sh engine-new-view-bug-reject-safe-improving-highest
bash scripts/formal/sumeragi_apalache.sh engine-new-view-bug-reject-safe-lower-highest
bash scripts/formal/sumeragi_apalache.sh engine-new-view-bug-skip-advance-output
bash scripts/formal/sumeragi_apalache.sh engine-new-view-bug-wrong-phase
bash scripts/formal/sumeragi_apalache.sh engine-new-view-bug-keep-validation
bash scripts/formal/sumeragi_apalache.sh engine-new-view-bug-drop-pending-finality
bash scripts/formal/sumeragi_apalache.sh engine-new-view-bug-overwrite-lower-highest
bash scripts/formal/sumeragi_apalache.sh engine-new-view-bug-skip-highest-record
bash scripts/formal/sumeragi_apalache.sh engine-proposal-bug-wrong-phase
bash scripts/formal/sumeragi_apalache.sh engine-proposal-bug-wrong-round
bash scripts/formal/sumeragi_apalache.sh engine-proposal-bug-incompatible-highest
bash scripts/formal/sumeragi_apalache.sh engine-proposal-bug-locked-conflict-no-qc
bash scripts/formal/sumeragi_apalache.sh engine-proposal-bug-locked-conflict-equal-qc
bash scripts/formal/sumeragi_apalache.sh engine-proposal-bug-locked-conflict-lower-qc
bash scripts/formal/sumeragi_apalache.sh engine-proposal-bug-reject-unlocked
bash scripts/formal/sumeragi_apalache.sh engine-proposal-bug-reject-locked-subject
bash scripts/formal/sumeragi_apalache.sh engine-proposal-bug-reject-higher-qc
bash scripts/formal/sumeragi_apalache.sh engine-proposal-bug-skip-validation
bash scripts/formal/sumeragi_apalache.sh engine-proposal-bug-skip-prepare-vote
bash scripts/formal/sumeragi_apalache.sh engine-proposal-bug-skip-prepare-phase
bash scripts/formal/sumeragi_apalache.sh engine-prepare-bug-wrong-context
bash scripts/formal/sumeragi_apalache.sh engine-prepare-bug-wrong-quorum-policy
bash scripts/formal/sumeragi_apalache.sh engine-prepare-bug-stale-view
bash scripts/formal/sumeragi_apalache.sh engine-prepare-bug-committed-height
bash scripts/formal/sumeragi_apalache.sh engine-prepare-bug-replay-prepare
bash scripts/formal/sumeragi_apalache.sh engine-prepare-bug-conflicting-prepare
bash scripts/formal/sumeragi_apalache.sh engine-prepare-bug-pending-finality
bash scripts/formal/sumeragi_apalache.sh engine-prepare-bug-reject-safe
bash scripts/formal/sumeragi_apalache.sh engine-prepare-bug-missing-lock-record
bash scripts/formal/sumeragi_apalache.sh engine-commit-bug-wrong-context
bash scripts/formal/sumeragi_apalache.sh engine-commit-bug-wrong-quorum-policy
bash scripts/formal/sumeragi_apalache.sh engine-commit-bug-stale-view
bash scripts/formal/sumeragi_apalache.sh engine-commit-bug-committed-height
bash scripts/formal/sumeragi_apalache.sh engine-commit-bug-pending-replay
bash scripts/formal/sumeragi_apalache.sh engine-commit-bug-pending-conflict
bash scripts/formal/sumeragi_apalache.sh engine-commit-bug-commit-without-payload
bash scripts/formal/sumeragi_apalache.sh engine-commit-bug-fetch-despite-payload
bash scripts/formal/sumeragi_apalache.sh engine-commit-bug-reject-available
bash scripts/formal/sumeragi_apalache.sh engine-commit-bug-reject-missing-payload
bash scripts/formal/sumeragi_apalache.sh engine-commit-bug-missing-highest-record
bash scripts/formal/sumeragi_apalache.sh engine-committed-block-bug-skip-fresh-record
bash scripts/formal/sumeragi_apalache.sh engine-committed-block-bug-reject-boundary-activation
bash scripts/formal/sumeragi_apalache.sh engine-committed-block-bug-activate-without-boundary
bash scripts/formal/sumeragi_apalache.sh engine-committed-block-bug-activate-non-boundary
bash scripts/formal/sumeragi_apalache.sh engine-committed-block-bug-record-duplicate
bash scripts/formal/sumeragi_apalache.sh engine-committed-block-bug-activate-duplicate
bash scripts/formal/sumeragi_apalache.sh engine-committed-block-bug-record-conflict
bash scripts/formal/sumeragi_apalache.sh engine-committed-block-bug-activate-conflict
bash scripts/formal/sumeragi_apalache.sh engine-committed-block-bug-overwrite-conflict
bash scripts/formal/sumeragi_apalache.sh engine-payload-bug-skip-available-record
bash scripts/formal/sumeragi_apalache.sh engine-payload-bug-commit-without-pending
bash scripts/formal/sumeragi_apalache.sh engine-payload-bug-commit-mismatched-payload
bash scripts/formal/sumeragi_apalache.sh engine-payload-bug-drop-pending-on-mismatch
bash scripts/formal/sumeragi_apalache.sh engine-payload-bug-reject-matching-payload
bash scripts/formal/sumeragi_apalache.sh engine-payload-bug-keep-pending-after-commit
bash scripts/formal/sumeragi_apalache.sh engine-payload-bug-wrong-phase-after-commit
bash scripts/formal/sumeragi_apalache.sh engine-validation-result-bug-accept-wrong-round
bash scripts/formal/sumeragi_apalache.sh engine-validation-result-bug-accept-wrong-block-hash
bash scripts/formal/sumeragi_apalache.sh engine-validation-result-bug-accept-no-inflight
bash scripts/formal/sumeragi_apalache.sh engine-validation-result-bug-accept-superseded
bash scripts/formal/sumeragi_apalache.sh engine-validation-result-bug-reject-current-valid
bash scripts/formal/sumeragi_apalache.sh engine-validation-result-bug-reject-current-invalid
bash scripts/formal/sumeragi_apalache.sh engine-validation-result-bug-keep-validation
bash scripts/formal/sumeragi_apalache.sh engine-validation-result-bug-valid-emits-output
bash scripts/formal/sumeragi_apalache.sh engine-validation-result-bug-skip-round-advance
bash scripts/formal/sumeragi_apalache.sh engine-validation-result-bug-skip-new-view-vote
bash scripts/formal/sumeragi_apalache.sh engine-validation-result-bug-skip-advance-output
bash scripts/formal/sumeragi_apalache.sh engine-validation-result-bug-wrong-phase
bash scripts/formal/sumeragi_apalache.sh engine-validation-result-bug-use-invalid-subject-despite-highest
bash scripts/formal/sumeragi_apalache.sh engine-validation-result-bug-use-highest-without-highest
bash scripts/formal/sumeragi_apalache.sh engine-validation-result-bug-omit-highest-binding
bash scripts/formal/sumeragi_apalache.sh engine-validation-result-bug-bind-highest-without-highest
bash scripts/formal/sumeragi_apalache.sh engine-validation-result-bug-drop-pending-finality
bash scripts/formal/sumeragi_apalache.sh engine-validation-result-bug-overwrite-committed
bash scripts/formal/sumeragi_apalache.sh reconfig-bug-premature-activation
bash scripts/formal/sumeragi_apalache.sh reconfig-bug-premature-new-cert
bash scripts/formal/sumeragi_apalache.sh reconfig-bug-mixed-cert
bash scripts/formal/sumeragi_apalache.sh recovery-bug-commit-without-payload
bash scripts/formal/sumeragi_apalache.sh recovery-bug-mismatched-payload
bash scripts/formal/sumeragi_apalache.sh recovery-bug-conflicting-finality
bash scripts/formal/sumeragi_apalache.sh view-change-bug-stale-new-view
bash scripts/formal/sumeragi_apalache.sh view-change-bug-unsafe-proposal
bash scripts/formal/sumeragi_apalache.sh view-change-bug-lock-overwrite
bash scripts/formal/sumeragi_apalache.sh view-change-bug-highest-regression
bash scripts/formal/sumeragi_apalache.sh validation-bug-unknown-result
bash scripts/formal/sumeragi_apalache.sh validation-bug-completed-replay
bash scripts/formal/sumeragi_apalache.sh validation-bug-timeout-inflight
bash scripts/formal/sumeragi_apalache.sh validation-bug-invalid-replay
bash scripts/formal/sumeragi_apalache.sh admission-bug-wrong-context
bash scripts/formal/sumeragi_apalache.sh admission-bug-stale-prepare-commit
bash scripts/formal/sumeragi_apalache.sh admission-bug-future-height
bash scripts/formal/sumeragi_apalache.sh admission-bug-committed-height
bash scripts/formal/sumeragi_apalache.sh highest-bug-height-priority
bash scripts/formal/sumeragi_apalache.sh highest-bug-phase-rank
bash scripts/formal/sumeragi_apalache.sh highest-bug-subject-tie
bash scripts/formal/sumeragi_apalache.sh highest-bug-non-new-view

echo "[formal] Sumeragi expected-failure checks behaved as expected"
