#!/bin/bash
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$repo_root"

bash scripts/formal/sumeragi_apalache.sh fast
bash scripts/formal/sumeragi_apalache.sh deep
bash scripts/formal/sumeragi_apalache.sh fork-fast
bash scripts/formal/sumeragi_apalache.sh fork-npos
bash scripts/formal/sumeragi_apalache.sh quorum-fast
bash scripts/formal/sumeragi_apalache.sh rbc-fast
bash scripts/formal/sumeragi_apalache.sh rbc-causality-fast
bash scripts/formal/sumeragi_apalache.sh pending-rbc-stash-fast
bash scripts/formal/sumeragi_apalache.sh rbc-preimage-fast
bash scripts/formal/sumeragi_apalache.sh classic-preimage-fast
bash scripts/formal/sumeragi_apalache.sh classic-signature-fast
bash scripts/formal/sumeragi_apalache.sh vrf-admission-fast
bash scripts/formal/sumeragi_apalache.sh vote-admission-fast
bash scripts/formal/sumeragi_apalache.sh proposal-hint-fast
bash scripts/formal/sumeragi_apalache.sh proposal-admission-fast
bash scripts/formal/sumeragi_apalache.sh block-created-admission-fast
bash scripts/formal/sumeragi_apalache.sh qc-signers-fast
bash scripts/formal/sumeragi_apalache.sh commit-roots-fast
bash scripts/formal/sumeragi_apalache.sh commit-pipeline-recovery-fast
bash scripts/formal/sumeragi_apalache.sh commit-pipeline-scheduling-fast
bash scripts/formal/sumeragi_apalache.sh commit-result-drain-fast
bash scripts/formal/sumeragi_apalache.sh commit-job-dispatch-fast
bash scripts/formal/sumeragi_apalache.sh commit-inflight-timeout-fast
bash scripts/formal/sumeragi_apalache.sh post-commit-pacemaker-kick-fast
bash scripts/formal/sumeragi_apalache.sh idle-view-proposal-budget-fast
bash scripts/formal/sumeragi_apalache.sh pacemaker-evaluation-fast
bash scripts/formal/sumeragi_apalache.sh cached-slot-timeout-fast
bash scripts/formal/sumeragi_apalache.sh proposal-parent-resolution-fast
bash scripts/formal/sumeragi_apalache.sh precommit-qc-view-change-fast
bash scripts/formal/sumeragi_apalache.sh commit-evidence-replay-fast
bash scripts/formal/sumeragi_apalache.sh block-sync-recovery-fast
bash scripts/formal/sumeragi_apalache.sh certified-fetch-fast
bash scripts/formal/sumeragi_apalache.sh missing-block-fetch-fast
bash scripts/formal/sumeragi_apalache.sh missing-block-hard-cap-fast
bash scripts/formal/sumeragi_apalache.sh missing-block-hard-cap-cleanup-fast
bash scripts/formal/sumeragi_apalache.sh missing-block-view-change-fast
bash scripts/formal/sumeragi_apalache.sh native-amx-attestation-fast
bash scripts/formal/sumeragi_apalache.sh native-amx-journal-fast
bash scripts/formal/sumeragi_apalache.sh native-amx-routing-plan-fast
bash scripts/formal/sumeragi_apalache.sh native-amx-receipt-fast
bash scripts/formal/sumeragi_apalache.sh native-amx-ingress-fast
bash scripts/formal/sumeragi_apalache.sh vnext-chain-order-fast
bash scripts/formal/sumeragi_apalache.sh vnext-rechain-fast
bash scripts/formal/sumeragi_apalache.sh vnext-signature-fast
bash scripts/formal/sumeragi_apalache.sh vnext-signing-preimage-fast
bash scripts/formal/sumeragi_apalache.sh vnext-control-ingress-fast
bash scripts/formal/sumeragi_apalache.sh vnext-slot-lifecycle-fast
bash scripts/formal/sumeragi_apalache.sh vnext-validation-fast
bash scripts/formal/sumeragi_apalache.sh vote-verify-async-fast
bash scripts/formal/sumeragi_apalache.sh qc-verify-async-fast
bash scripts/formal/sumeragi_apalache.sh worker-drain-fast
bash scripts/formal/sumeragi_apalache.sh actor-gate-fast
bash scripts/formal/sumeragi_apalache.sh worker-budget-fast
bash scripts/formal/sumeragi_apalache.sh worker-ingress-fast
bash scripts/formal/sumeragi_apalache.sh npos-vrf-fast
bash scripts/formal/sumeragi_apalache.sh kura-commit-fast
bash scripts/formal/sumeragi_apalache.sh restart-replay-fast
bash scripts/formal/sumeragi_apalache.sh post-commit-cleanup-fast
bash scripts/formal/sumeragi_apalache.sh frontier-gap-realign-fast
bash scripts/formal/sumeragi_apalache.sh precommit-fast
bash scripts/formal/sumeragi_apalache.sh proposal-fast
bash scripts/formal/sumeragi_apalache.sh engine-tick-fast
bash scripts/formal/sumeragi_apalache.sh engine-new-view-subject-fast
bash scripts/formal/sumeragi_apalache.sh engine-handle-dispatch-fast
bash scripts/formal/sumeragi_apalache.sh engine-certificate-dispatch-fast
bash scripts/formal/sumeragi_apalache.sh engine-certificate-prefilter-state-fast
bash scripts/formal/sumeragi_apalache.sh engine-view-advance-saturation-fast
bash scripts/formal/sumeragi_apalache.sh engine-new-view-fast
bash scripts/formal/sumeragi_apalache.sh engine-new-view-highest-qc-fast
bash scripts/formal/sumeragi_apalache.sh engine-new-view-advance-fast
bash scripts/formal/sumeragi_apalache.sh engine-proposal-fast
bash scripts/formal/sumeragi_apalache.sh engine-proposal-output-fast
bash scripts/formal/sumeragi_apalache.sh engine-proposal-state-fast
bash scripts/formal/sumeragi_apalache.sh engine-proposal-validation-owner-fast
bash scripts/formal/sumeragi_apalache.sh engine-proposal-lock-fast
bash scripts/formal/sumeragi_apalache.sh qc-round-compatibility-fast
bash scripts/formal/sumeragi_apalache.sh engine-qc-ref-projection-fast
bash scripts/formal/sumeragi_apalache.sh engine-highest-qc-record-fast
bash scripts/formal/sumeragi_apalache.sh engine-commit-subject-fast
bash scripts/formal/sumeragi_apalache.sh engine-payload-lookup-fast
bash scripts/formal/sumeragi_apalache.sh engine-prepare-fast
bash scripts/formal/sumeragi_apalache.sh engine-prepare-lock-highest-fast
bash scripts/formal/sumeragi_apalache.sh engine-prepare-phase-fast
bash scripts/formal/sumeragi_apalache.sh engine-prepare-vote-cache-fast
bash scripts/formal/sumeragi_apalache.sh engine-commit-fast
bash scripts/formal/sumeragi_apalache.sh engine-commit-highest-qc-fast
bash scripts/formal/sumeragi_apalache.sh engine-commit-available-commit-fast
bash scripts/formal/sumeragi_apalache.sh engine-commit-pending-fetch-fast
bash scripts/formal/sumeragi_apalache.sh engine-commit-validation-cleanup-fast
bash scripts/formal/sumeragi_apalache.sh engine-committed-block-fast
bash scripts/formal/sumeragi_apalache.sh engine-committed-block-record-fast
bash scripts/formal/sumeragi_apalache.sh engine-reconfiguration-staging-fast
bash scripts/formal/sumeragi_apalache.sh engine-committed-block-cleanup-fast
bash scripts/formal/sumeragi_apalache.sh engine-payload-record-fast
bash scripts/formal/sumeragi_apalache.sh engine-payload-fast
bash scripts/formal/sumeragi_apalache.sh engine-validation-result-fast
bash scripts/formal/sumeragi_apalache.sh engine-validation-ownership-fast
bash scripts/formal/sumeragi_apalache.sh engine-validation-invalid-advance-fast
bash scripts/formal/sumeragi_apalache.sh reconfig-fast
bash scripts/formal/sumeragi_apalache.sh recovery-fast
bash scripts/formal/sumeragi_apalache.sh view-change-fast
bash scripts/formal/sumeragi_apalache.sh validation-fast
bash scripts/formal/sumeragi_apalache.sh admission-fast
bash scripts/formal/sumeragi_apalache.sh highest-fast
bash scripts/formal/sumeragi_apalache.sh frontier-fast
bash scripts/formal/sumeragi_apalache.sh frontier-deep
bash scripts/formal/sumeragi_apalache.sh frontier-wide
bash scripts/formal/sumeragi_tlc.sh frontier-small
bash ci/check_sumeragi_formal_expected_failures.sh

echo "[formal] sumeragi formal checks passed"
