// Ordinary native symbol references keep the SDK's dynamic exports linked.
// SwiftPM products must remain usable without unsafe linker flags.
#include "NoritoBridgeRetention.h"
#include "connect_norito_bridge.h"

// These current C exports are owned by crates/soranet_pq/include/soranet_pq.h.
// The bridge's packaged header exposes its own declarations separately.
int soranet_mldsa_parameters(uint32_t suite_id,
    uint32_t *public_key_len_out, uint32_t *secret_key_len_out,
    uint32_t *signature_len_out);
int soranet_mldsa_generate_keypair(uint32_t suite_id,
    uint8_t *public_key_out, size_t public_key_len,
    uint8_t *secret_key_out, size_t secret_key_len);
int soranet_mldsa_sign(uint32_t suite_id,
    const uint8_t *secret_key, size_t secret_key_len,
    const uint8_t *message, size_t message_len,
    uint8_t *signature_out, size_t signature_len);
int soranet_mldsa_verify(uint32_t suite_id,
    const uint8_t *public_key, size_t public_key_len,
    const uint8_t *message, size_t message_len,
    const uint8_t *signature, size_t signature_len);

typedef void (*NoritoBridgeExportReference)(void);

// Volatile reads prevent optimization from discarding this address inventory.
// The called retention function roots the table; its relocations extract every
// referenced archive member and retain the exports under linker dead stripping.
static NoritoBridgeExportReference volatile required_exports[] = {
    (NoritoBridgeExportReference)connect_norito_acceleration_config_get_v1,
    (NoritoBridgeExportReference)connect_norito_acceleration_config_set_v1,
    (NoritoBridgeExportReference)connect_norito_acceleration_state_get_v1,
    (NoritoBridgeExportReference)connect_norito_account_address_parse,
    (NoritoBridgeExportReference)connect_norito_account_address_render,
    (NoritoBridgeExportReference)connect_norito_account_read_permission_multisig_finalize,
    (NoritoBridgeExportReference)connect_norito_account_read_permission_multisig_payload_hash,
    (NoritoBridgeExportReference)connect_norito_alias_instruction_round_trip_v1,
    (NoritoBridgeExportReference)connect_norito_blake3_hash,
    (NoritoBridgeExportReference)connect_norito_bridge_abi_version,
    (NoritoBridgeExportReference)connect_norito_canonical_json_blake3_v1,
    (NoritoBridgeExportReference)connect_norito_chain_discriminant_scope_enter,
    (NoritoBridgeExportReference)connect_norito_chain_discriminant_scope_exit,
    (NoritoBridgeExportReference)connect_norito_committed_transaction_candidate_block_hash_v1,
    (NoritoBridgeExportReference)connect_norito_committed_transaction_query_finalize_v1,
    (NoritoBridgeExportReference)connect_norito_committed_transaction_query_payload_hash_v1,
    (NoritoBridgeExportReference)connect_norito_confidential_asset_tag_derive_v3,
    (NoritoBridgeExportReference)connect_norito_confidential_default_diversifier_v3,
    (NoritoBridgeExportReference)connect_norito_confidential_diversifier_derive_v3,
    (NoritoBridgeExportReference)connect_norito_confidential_merkle_path_advance_v3,
    (NoritoBridgeExportReference)connect_norito_confidential_merkle_path_derive_v3,
    (NoritoBridgeExportReference)connect_norito_confidential_merkle_path_verify_v3,
    (NoritoBridgeExportReference)connect_norito_confidential_network_tag_derive_v3,
    (NoritoBridgeExportReference)connect_norito_confidential_note_commitment_derive_v3,
    (NoritoBridgeExportReference)connect_norito_confidential_note_derivation_revision_v3,
    (NoritoBridgeExportReference)connect_norito_confidential_nullifier_derive_v3,
    (NoritoBridgeExportReference)connect_norito_confidential_owner_tag_derive_v3,
    (NoritoBridgeExportReference)connect_norito_connect_decrypt_ciphertext,
    (NoritoBridgeExportReference)connect_norito_connect_derive_keys,
    (NoritoBridgeExportReference)connect_norito_connect_encrypt_envelope,
    (NoritoBridgeExportReference)connect_norito_connect_generate_keypair,
    (NoritoBridgeExportReference)connect_norito_connect_public_from_private,
    (NoritoBridgeExportReference)connect_norito_da_proof_summary,
    (NoritoBridgeExportReference)connect_norito_decode_asset_id_json,
    (NoritoBridgeExportReference)connect_norito_decode_ciphertext_frame,
    (NoritoBridgeExportReference)connect_norito_decode_control_approve_account,
    (NoritoBridgeExportReference)connect_norito_decode_control_approve_permissions_json,
    (NoritoBridgeExportReference)connect_norito_decode_control_approve_proof_json,
    (NoritoBridgeExportReference)connect_norito_decode_control_approve_pub,
    (NoritoBridgeExportReference)connect_norito_decode_control_approve_sig,
    (NoritoBridgeExportReference)connect_norito_decode_control_approve_sig_alg,
    (NoritoBridgeExportReference)connect_norito_decode_control_close,
    (NoritoBridgeExportReference)connect_norito_decode_control_kind,
    (NoritoBridgeExportReference)connect_norito_decode_control_open_app_metadata_json,
    (NoritoBridgeExportReference)connect_norito_decode_control_open_network_id,
    (NoritoBridgeExportReference)connect_norito_decode_control_open_permissions_json,
    (NoritoBridgeExportReference)connect_norito_decode_control_open_pub,
    (NoritoBridgeExportReference)connect_norito_decode_control_ping,
    (NoritoBridgeExportReference)connect_norito_decode_control_pong,
    (NoritoBridgeExportReference)connect_norito_decode_control_reject,
    (NoritoBridgeExportReference)connect_norito_decode_envelope_json,
    (NoritoBridgeExportReference)connect_norito_decode_envelope_kind,
    (NoritoBridgeExportReference)connect_norito_decode_signed_transaction_json,
    (NoritoBridgeExportReference)connect_norito_decode_transaction_receipt_json,
    (NoritoBridgeExportReference)connect_norito_detached_transaction_scaffold_finalize_ed25519_v1,
    (NoritoBridgeExportReference)connect_norito_detached_transaction_scaffold_inspect_v1,
    (NoritoBridgeExportReference)connect_norito_encode_account_onboarding_plan_body_v1,
    (NoritoBridgeExportReference)connect_norito_encode_burn_signed_transaction,
    (NoritoBridgeExportReference)connect_norito_encode_burn_signed_transaction_alg,
    (NoritoBridgeExportReference)connect_norito_encode_ciphertext_frame,
    (NoritoBridgeExportReference)connect_norito_encode_claim_identifier_signed_transaction,
    (NoritoBridgeExportReference)connect_norito_encode_claim_identifier_signed_transaction_alg,
    (NoritoBridgeExportReference)connect_norito_encode_control_approve_ext,
    (NoritoBridgeExportReference)connect_norito_encode_control_approve_ext_with_alg,
    (NoritoBridgeExportReference)connect_norito_encode_control_close,
    (NoritoBridgeExportReference)connect_norito_encode_control_open_ext,
    (NoritoBridgeExportReference)connect_norito_encode_control_ping,
    (NoritoBridgeExportReference)connect_norito_encode_control_pong,
    (NoritoBridgeExportReference)connect_norito_encode_control_reject,
    (NoritoBridgeExportReference)connect_norito_encode_envelope_control_close,
    (NoritoBridgeExportReference)connect_norito_encode_envelope_control_reject,
    (NoritoBridgeExportReference)connect_norito_encode_envelope_sign_request_raw,
    (NoritoBridgeExportReference)connect_norito_encode_envelope_sign_request_tx,
    (NoritoBridgeExportReference)connect_norito_encode_envelope_sign_result_err,
    (NoritoBridgeExportReference)connect_norito_encode_envelope_sign_result_ok,
    (NoritoBridgeExportReference)connect_norito_encode_envelope_sign_result_ok_with_alg,
    (NoritoBridgeExportReference)connect_norito_encode_governance_cast_plain_ballot_signed_transaction,
    (NoritoBridgeExportReference)connect_norito_encode_governance_cast_plain_ballot_signed_transaction_alg,
    (NoritoBridgeExportReference)connect_norito_encode_governance_cast_zk_ballot_signed_transaction,
    (NoritoBridgeExportReference)connect_norito_encode_governance_cast_zk_ballot_signed_transaction_alg,
    (NoritoBridgeExportReference)connect_norito_encode_governance_propose_deploy_v1_signed_transaction,
    (NoritoBridgeExportReference)connect_norito_encode_governance_propose_deploy_v1_signed_transaction_alg,
    (NoritoBridgeExportReference)connect_norito_encode_governance_update_plain_conviction_signed_transaction_alg,
    (NoritoBridgeExportReference)connect_norito_encode_mint_signed_transaction,
    (NoritoBridgeExportReference)connect_norito_encode_mint_signed_transaction_alg,
    (NoritoBridgeExportReference)connect_norito_encode_multisig_register_signed_transaction,
    (NoritoBridgeExportReference)connect_norito_encode_multisig_register_signed_transaction_alg,
    (NoritoBridgeExportReference)connect_norito_encode_register_zk_asset_signed_transaction,
    (NoritoBridgeExportReference)connect_norito_encode_register_zk_asset_signed_transaction_alg,
    (NoritoBridgeExportReference)connect_norito_encode_remove_key_value_signed_transaction,
    (NoritoBridgeExportReference)connect_norito_encode_remove_key_value_signed_transaction_alg,
    (NoritoBridgeExportReference)connect_norito_encode_set_key_value_signed_transaction,
    (NoritoBridgeExportReference)connect_norito_encode_set_key_value_signed_transaction_alg,
    (NoritoBridgeExportReference)connect_norito_encode_transfer_instruction_box,
    (NoritoBridgeExportReference)connect_norito_encode_transfer_instruction_frame_v1,
    (NoritoBridgeExportReference)connect_norito_encode_transfer_signed_transaction,
    (NoritoBridgeExportReference)connect_norito_encode_transfer_signed_transaction_alg,
    (NoritoBridgeExportReference)connect_norito_free,
    (NoritoBridgeExportReference)connect_norito_kagemusha_wallet_activity_v1,
    (NoritoBridgeExportReference)connect_norito_kagemusha_wallet_close_v1,
    (NoritoBridgeExportReference)connect_norito_kagemusha_wallet_credit_status_v1,
    (NoritoBridgeExportReference)connect_norito_kagemusha_wallet_enrollment_v1,
    (NoritoBridgeExportReference)connect_norito_kagemusha_wallet_execute_v1,
    (NoritoBridgeExportReference)connect_norito_kagemusha_wallet_review_v1,
    (NoritoBridgeExportReference)connect_norito_kagemusha_wallet_execute_reviewed_v1,
    (NoritoBridgeExportReference)connect_norito_kagemusha_wallet_discard_review_v1,
    (NoritoBridgeExportReference)connect_norito_kagemusha_wallet_fold_v1,
    (NoritoBridgeExportReference)connect_norito_kagemusha_wallet_load_original_validate_v1,
    (NoritoBridgeExportReference)connect_norito_kagemusha_wallet_install_runtime_v1,
    (NoritoBridgeExportReference)connect_norito_kagemusha_wallet_open_begin_v1,
    (NoritoBridgeExportReference)connect_norito_kagemusha_wallet_open_cancel_v1,
    (NoritoBridgeExportReference)connect_norito_kagemusha_wallet_open_finish_v1,
    (NoritoBridgeExportReference)connect_norito_kagemusha_wallet_request_status_v1,
    (NoritoBridgeExportReference)connect_norito_kagemusha_wallet_resume_v1,
    (NoritoBridgeExportReference)connect_norito_kagemusha_wallet_retry_v1,
    (NoritoBridgeExportReference)connect_norito_kagemusha_wallet_revision_v1,
    (NoritoBridgeExportReference)connect_norito_kagemusha_wallet_setup_v1,
    (NoritoBridgeExportReference)connect_norito_kagemusha_wallet_snapshot_v1,
    (NoritoBridgeExportReference)connect_norito_keypair_from_seed,
    (NoritoBridgeExportReference)connect_norito_parliament_timed_ovn_ballot_from_proof_v1,
    (NoritoBridgeExportReference)connect_norito_parliament_timed_ovn_registration_from_proof_v1,
    (NoritoBridgeExportReference)connect_norito_parliament_timed_ovn_verify_casting_proof_page_v1,
    (NoritoBridgeExportReference)connect_norito_parliament_timed_ovn_verify_casting_proof_v1,
    (NoritoBridgeExportReference)connect_norito_private_settlement_audit_approval_response_verify_v1,
    (NoritoBridgeExportReference)connect_norito_private_settlement_auditor_capsule_response_verify_with_request_v1,
    (NoritoBridgeExportReference)connect_norito_private_settlement_committee_proof_response_verify_v1,
    (NoritoBridgeExportReference)connect_norito_public_key_from_private,
    (NoritoBridgeExportReference)connect_norito_retail_fee_assessment_decode_v1,
    (NoritoBridgeExportReference)connect_norito_retail_fee_assessment_marker_v1,
    (NoritoBridgeExportReference)connect_norito_retail_fee_intent_hash_v1,
    (NoritoBridgeExportReference)connect_norito_secp256k1_public_key,
    (NoritoBridgeExportReference)connect_norito_secp256k1_sign,
    (NoritoBridgeExportReference)connect_norito_secp256k1_verify,
    (NoritoBridgeExportReference)connect_norito_sign_detached,
    (NoritoBridgeExportReference)connect_norito_sm2_compute_za,
    (NoritoBridgeExportReference)connect_norito_sm2_default_distid,
    (NoritoBridgeExportReference)connect_norito_sm2_keypair_from_seed,
    (NoritoBridgeExportReference)connect_norito_sm2_public_key_multihash,
    (NoritoBridgeExportReference)connect_norito_sm2_public_key_prefixed,
    (NoritoBridgeExportReference)connect_norito_sm2_sign,
    (NoritoBridgeExportReference)connect_norito_sm2_verify,
    (NoritoBridgeExportReference)connect_norito_sorafs_local_fetch,
    (NoritoBridgeExportReference)connect_norito_sorafs_reference_build_signed_orderbook_order_cancel,
    (NoritoBridgeExportReference)connect_norito_sorafs_reference_build_signed_orderbook_order_request,
    (NoritoBridgeExportReference)connect_norito_sorafs_reference_build_signed_orderbook_settlement_receipt,
    (NoritoBridgeExportReference)connect_norito_sorafs_reference_derive_orderbook_order_id,
    (NoritoBridgeExportReference)connect_norito_sorafs_reference_sign_orderbook_payload,
    (NoritoBridgeExportReference)connect_norito_sorafs_reference_validate_appeal_finance_cancel_asset_lock_json,
    (NoritoBridgeExportReference)connect_norito_sorafs_reference_validate_bundle_json,
    (NoritoBridgeExportReference)connect_norito_sorafs_reference_validate_governance_dag_block_json,
    (NoritoBridgeExportReference)connect_norito_sorafs_reference_validate_governance_dag_head_chain_json,
    (NoritoBridgeExportReference)connect_norito_sorafs_reference_validate_governance_json,
    (NoritoBridgeExportReference)connect_norito_sorafs_reference_validate_hedging_json,
    (NoritoBridgeExportReference)connect_norito_sorafs_reference_validate_orderbook_json,
    (NoritoBridgeExportReference)connect_norito_sorafs_reference_validate_pdp_bundle_json,
    (NoritoBridgeExportReference)connect_norito_sorafs_reference_validate_pdp_challenge_proof_json,
    (NoritoBridgeExportReference)connect_norito_sorafs_reference_validate_pdp_commitment_challenge_json,
    (NoritoBridgeExportReference)connect_norito_sorafs_reference_validate_pdp_payload_json,
    (NoritoBridgeExportReference)connect_norito_sorafs_reference_validate_pop_json,
    (NoritoBridgeExportReference)connect_norito_verify_committed_transaction_inclusion_v1,
    (NoritoBridgeExportReference)connect_norito_verify_detached,
    (NoritoBridgeExportReference)iroha_privacy_compiled_profile_catalog_v1,
    (NoritoBridgeExportReference)iroha_privacy_exact12_fixture_bundle_v1,
    (NoritoBridgeExportReference)iroha_privacy_free_buffer,
    (NoritoBridgeExportReference)iroha_privacy_validate_compiled_profile_catalog_v1,
    (NoritoBridgeExportReference)iroha_privacy_validate_exact12_capability_manifest_v1,
    (NoritoBridgeExportReference)iroha_privacy_validate_exact12_fixture_bundle_v1,
    (NoritoBridgeExportReference)soranet_mldsa_generate_keypair,
    (NoritoBridgeExportReference)soranet_mldsa_parameters,
    (NoritoBridgeExportReference)soranet_mldsa_sign,
    (NoritoBridgeExportReference)soranet_mldsa_verify,
};

size_t iroha_norito_bridge_retain_exports(void) {
    const size_t count = sizeof(required_exports) / sizeof(required_exports[0]);
    for (size_t index = 0; index < count; ++index) {
        if (required_exports[index] == NULL) {
            return 0;
        }
    }
    return count;
}
