//! Exact classification of every `iroha_core` function that the State inventory scan
//! finds by its signature: a function or method with a State or World receiver or reader
//! argument and a hash-bearing return value. A reader is `State`, `World` or the owner of
//! another registry field (the transaction storage, the block-hash journal, the trigger
//! set, the canonical runtime) with its handles and reader traits, or a table or cell
//! handle.
//!
//! Each entry names the source, the function and the number of matching functions of that
//! name in the source. A new, renamed or moved match fails `state_table_inventory_tests`
//! until it is listed here under the commitment it computes or serves, under an
//! application accumulator, or with its reviewed use.

use super::{UseOwner, domains::Use};

/// One function that reads State and returns a hash-bearing value, and what owns it.
pub(super) struct StateHashFunction {
    pub(super) path: &'static str,
    pub(super) name: &'static str,
    /// Number of matching functions of this name in the source.
    pub(super) count: usize,
    pub(super) owner: UseOwner,
}

const BLOCK_HASH: &str = "Reads committed block hashes or the hash of the current block header: authenticated history and block identity, not a digest of State content";
const RECORD_IDENTITY: &str = "Returns the identifier, content hash or stored digest of one record, transaction or message: no digest over a table or cell";
const DERIVED_SEED: &str =
    "Derives a sampling seed or an identifier from committed records or from the current block";
const EXPECTED_VALUE: &str = "Canonical hash of one State value (the protected runtime catalog parameter) that a lane lifecycle transaction names as its expected value and that the status endpoint serves";
const TEST_ONLY: &str =
    "Table accessors and fixtures compiled for tests or under a test-only feature";
const CERTIFIED_IDENTITY: &str = "Carries the certified block identity and R of a committed height (the execution tip or a finality proof): it binds the listed roots and digests no State content of its own";
const ORIGINAL_WIRE_FENCE: &str = "Hashes or returns the exact original native block-wire prefix identity used only to invalidate a local finality-proof cursor; no State root or independent finality authority";
const BLOCK_PROOF: &str =
    "Merkle proofs of a transaction entrypoint and its result inside their block: block content";
const TABLE_ACCESSOR: &str = "Borrows a table whose key type is the content hash of one record (a pin manifest, contract bytecode): a table accessor that computes no digest";

const fn function(
    path: &'static str,
    name: &'static str,
    count: usize,
    owner: UseOwner,
) -> StateHashFunction {
    StateHashFunction {
        path,
        name,
        count,
        owner,
    }
}

/// Every function of `iroha_core` that the signature scan matches, in ascending order of
/// source and name.
pub(super) const STATE_HASH_FUNCTIONS: &[StateHashFunction] = &[
    function(
        "crates/iroha_core/src/beacon.rs",
        "active_global_threshold_beacon_session_id_v1",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/beacon.rs",
        "verified_persisted_global_threshold_beacon_governance_seed_v1",
        1,
        UseOwner::Other(Use::Seed, DERIVED_SEED),
    ),
    function(
        "crates/iroha_core/src/governance/parliament/planner.rs",
        "verified_pulse",
        1,
        UseOwner::Other(Use::Seed, DERIVED_SEED),
    ),
    function(
        "crates/iroha_core/src/kagemusha_wallet_v1/wsv.rs",
        "transaction_hash",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/query/musubi_pin_outbox/mod.rs",
        "consume_attempt",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/query/native_receipts.rs",
        "fee_evidence_block_proof",
        1,
        UseOwner::Roots(&["execution_witness_roots", "fee_evidence_record_root"]),
    ),
    function(
        "crates/iroha_core/src/query/native_receipts.rs",
        "fee_evidence_record_proof",
        1,
        UseOwner::Roots(&["execution_witness_roots", "fee_evidence_record_root"]),
    ),
    function(
        "crates/iroha_core/src/query/native_receipts.rs",
        "fee_evidence_window_proof",
        1,
        UseOwner::Roots(&["execution_witness_roots", "fee_evidence_record_root"]),
    ),
    function(
        "crates/iroha_core/src/query/native_receipts.rs",
        "parliament_casting_proof",
        1,
        UseOwner::Roots(&[
            "execution_witness_roots",
            "parliament_casting_snapshot_root",
        ]),
    ),
    function(
        "crates/iroha_core/src/query/native_receipts.rs",
        "private_dataspace_record_proof",
        1,
        UseOwner::Roots(&["execution_witness_roots"]),
    ),
    function(
        "crates/iroha_core/src/query/native_receipts.rs",
        "validation_fee_policy_witness",
        1,
        UseOwner::Roots(&["execution_witness_roots", "validation_fee_policy_snapshot"]),
    ),
    function(
        "crates/iroha_core/src/query/native_receipts/amx_read.rs",
        "complete",
        1,
        UseOwner::Roots(&["execution_witness_roots"]),
    ),
    function(
        "crates/iroha_core/src/query/topology_authority.rs",
        "digest",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/code.rs",
        "fetch_instance_binding",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/code.rs",
        "register_code_bytes",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/asset.rs",
        "bound_retail_identity",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/asset.rs",
        "context",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/asset.rs",
        "resolve_transcript_identity",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/asset.rs",
        "transcript_identity",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/game.rs",
        "retain_execution_verification",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/multisig.rs",
        "invalidate_outstanding_proposals",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/musubi.rs",
        "canonical_finalized_hash",
        1,
        UseOwner::Other(Use::Record, BLOCK_HASH),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/musubi.rs",
        "execution_hash",
        1,
        UseOwner::Other(Use::Record, BLOCK_HASH),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/musubi/pin_outbox.rs",
        "consume_origin",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/sccp/commitment.rs",
        "commit_block",
        1,
        UseOwner::Accumulator("sccp_message_accumulator"),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/sccp/commitment.rs",
        "history_root_and_size",
        1,
        UseOwner::Accumulator("sccp_message_accumulator"),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/sccp/commitment.rs",
        "leaf_hash",
        1,
        UseOwner::Accumulator("sccp_message_accumulator"),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/sccp/governance.rs",
        "pinnable_generation",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/sccp/light_clients.rs",
        "verify_source_proof",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/sccp/outbound.rs",
        "record_outbound_message",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/sccp/outbound.rs",
        "write_planned",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/sccp/read.rs",
        "block_leaf_hashes",
        1,
        UseOwner::Accumulator("sccp_message_accumulator"),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/sccp/read.rs",
        "control_proof",
        1,
        UseOwner::Accumulator("sccp_message_accumulator"),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/sccp/read.rs",
        "leaf_paths",
        1,
        UseOwner::Accumulator("sccp_message_accumulator"),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/sccp/read.rs",
        "message_proof",
        1,
        UseOwner::Accumulator("sccp_message_accumulator"),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/sccp/roster.rs",
        "install",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/sccp/subjects.rs",
        "block_hash",
        1,
        UseOwner::Other(Use::Record, BLOCK_HASH),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/sccp/subjects.rs",
        "statement_digest",
        1,
        UseOwner::Accumulator("sccp_message_accumulator"),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/sccp/subjects.rs",
        "statement_digest_of",
        1,
        UseOwner::Accumulator("sccp_message_accumulator"),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/settlement/atomic.rs",
        "validate_atomic_intent",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/soracloud.rs",
        "current_signed_transaction_hash",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/soracloud.rs",
        "verify_soracloud_fhe_input_admission_proof",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/sorafs.rs",
        "read_repair_indexed_task",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/triggers/set.rs",
        "contracts",
        2,
        UseOwner::Other(Use::Record, TABLE_ACCESSOR),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/triggers/set.rs",
        "get_original_contract_with_code_hash",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/triggers/set_authority_capture.rs",
        "capture_action_authority_table",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/triggers/set_authority_capture.rs",
        "capture_by_call_authority_table",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/triggers/set_authority_capture.rs",
        "capture_contracts_authority_table",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/triggers/set_authority_capture.rs",
        "capture_data_authority_table",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/triggers/set_authority_capture.rs",
        "capture_pipeline_authority_table",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/triggers/set_authority_capture.rs",
        "capture_time_authority_table",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/triggers/set_contract_capture.rs",
        "capture_frozen_contracts_authority_table",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/triggers/set_contract_capture/actions.rs",
        "capture_frozen_action_authority_table",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/world.rs",
        "election_vk_commitment",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/world.rs",
        "encode_and_validate_bridge_proof",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/world.rs",
        "exact_due_parliament_certificate_context_v1",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/world.rs",
        "parliament_finalized_pulse_seed_v1",
        1,
        UseOwner::Other(Use::Seed, DERIVED_SEED),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/isi/world.rs",
        "resolve_vk_commitment",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/ivm.rs",
        "active_runtime_abi_hash",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/ivm/host.rs",
        "axt_policy_snapshot_from_state",
        1,
        UseOwner::Roots(&["axt_policy_snapshot"]),
    ),
    function(
        "crates/iroha_core/src/smartcontracts/ivm/host.rs",
        "derive_axt_policy_snapshot_from_directory",
        1,
        UseOwner::Roots(&["axt_policy_snapshot"]),
    ),
    function(
        "crates/iroha_core/src/snapshot.rs",
        "try_write_snapshot_payload_with_limit_locked",
        1,
        UseOwner::Roots(&["state_snapshot_chunk_root"]),
    ),
    function(
        "crates/iroha_core/src/snapshot.rs",
        "try_write_snapshot_with_limit_and_policy",
        1,
        UseOwner::Roots(&["state_snapshot_chunk_root"]),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "active_global_beacon_key_session",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "axt_execution_policy_snapshot",
        3,
        UseOwner::Roots(&["axt_policy_snapshot"]),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "axt_policy_snapshot",
        4,
        UseOwner::Roots(&["axt_policy_snapshot"]),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "block_proofs_for_entry",
        1,
        UseOwner::Other(Use::BlockContent, BLOCK_PROOF),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "captured_fastpq_transcript_sources",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "committed_block_hash_for_proof",
        1,
        UseOwner::Other(Use::Record, BLOCK_HASH),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "compute_confidential_feature_digest",
        1,
        UseOwner::Roots(&["confidential_feature_digest"]),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "compute_vk_set_hash_from_statuses_at_height",
        1,
        UseOwner::Roots(&["confidential_feature_digest"]),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "direct_execution_identity",
        1,
        UseOwner::Other(Use::Seed, DERIVED_SEED),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "drain_batch_transfer_outcomes",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "drain_transfer_transcripts",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "drain_transfer_transcripts_with_pending",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "durable_block_hash",
        1,
        UseOwner::Other(Use::Record, BLOCK_HASH),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "execution_axt_policy_snapshot",
        2,
        UseOwner::Roots(&["axt_policy_snapshot"]),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "execution_policy_digest_v1",
        2,
        UseOwner::Roots(&["execution_policy_digest"]),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "execution_policy_digest_with_runtime_policies_v1",
        1,
        UseOwner::Roots(&["execution_policy_digest"]),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "expected_confidential_digest",
        1,
        UseOwner::Roots(&["confidential_feature_digest"]),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "first",
        1,
        UseOwner::Other(Use::Record, BLOCK_HASH),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "get",
        1,
        UseOwner::Other(Use::Record, BLOCK_HASH),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "hash_at",
        9,
        UseOwner::Other(Use::Record, BLOCK_HASH),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "lane_incarnation",
        1,
        UseOwner::Other(Use::Seed, DERIVED_SEED),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "lane_incarnation_at_height",
        3,
        UseOwner::Other(Use::Seed, DERIVED_SEED),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "lane_incarnations_snapshot",
        1,
        UseOwner::Other(Use::Seed, DERIVED_SEED),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "lane_relay_committee_seed_from_sources",
        1,
        UseOwner::Other(Use::Seed, DERIVED_SEED),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "last",
        1,
        UseOwner::Other(Use::Record, BLOCK_HASH),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "latest_block_hash",
        2,
        UseOwner::Other(Use::Record, BLOCK_HASH),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "latest_block_hash_fast",
        1,
        UseOwner::Other(Use::Record, BLOCK_HASH),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "next_lifecycle_transition_seed",
        1,
        UseOwner::Other(Use::Seed, DERIVED_SEED),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "pin_manifests_mut_for_testing",
        3,
        UseOwner::Other(Use::Test, TEST_ONLY),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "prev_block_hash",
        2,
        UseOwner::Other(Use::Record, BLOCK_HASH),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "private_settlement_pool_head_v1",
        1,
        UseOwner::Accumulator("private_settlement_pool_roots"),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "publish_query_projection_checkpoint",
        1,
        UseOwner::Roots(&["query_projection_payload_hash"]),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "publish_query_projection_checkpoint_from_archives",
        1,
        UseOwner::Roots(&["query_projection_payload_hash"]),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "query_projection_checkpoint_snapshot",
        1,
        UseOwner::Roots(&["query_projection_payload_hash"]),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "rebuild_axt_policies_from_space_directory",
        1,
        UseOwner::Roots(&["axt_policy_snapshot"]),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "rebuild_space_directory_bindings",
        1,
        UseOwner::Roots(&["axt_policy_snapshot"]),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "refresh_axt_policies_from_directory",
        3,
        UseOwner::Roots(&["axt_policy_snapshot"]),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "require_transfer_transcript_identity",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "soracloud_hf_shared_lease_pools_mut_for_testing",
        1,
        UseOwner::Other(Use::Test, TEST_ONLY),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "soracloud_hf_sources_mut_for_testing",
        1,
        UseOwner::Other(Use::Test, TEST_ONLY),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "soracloud_mailbox_messages_mut_for_testing",
        1,
        UseOwner::Other(Use::Test, TEST_ONLY),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "soracloud_runtime_receipts_mut_for_testing",
        1,
        UseOwner::Other(Use::Test, TEST_ONLY),
    ),
    function(
        "crates/iroha_core/src/state.rs",
        "verify_next_height_threshold_key_lifecycle_certificate_v1",
        1,
        UseOwner::Other(Use::Record, BLOCK_HASH),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/cell_snapshot.rs",
        "capture_once",
        1,
        UseOwner::Roots(&["state_cell_digest_slice"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/frozen_account_aliases.rs",
        "capture",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/frozen_account_identity.rs",
        "capture",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/frozen_account_rekeys.rs",
        "capture",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/frozen_asset_definitions.rs",
        "capture",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/frozen_assets.rs",
        "capture",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/frozen_contract_aliases.rs",
        "capture",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/frozen_contract_subjects.rs",
        "capture",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/frozen_domain_ownership.rs",
        "capture",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/frozen_escrows.rs",
        "capture",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/frozen_nfts_rwas.rs",
        "capture_nfts",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/frozen_nfts_rwas.rs",
        "capture_rwas",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/frozen_proofs.rs",
        "capture",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/frozen_repo_agreements.rs",
        "capture",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/frozen_trigger_actions.rs",
        "capture",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/frozen_trigger_contracts.rs",
        "capture",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/frozen_validation_fee_proposals.rs",
        "capture",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/frozen_verifying_keys.rs",
        "capture",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/grouped_capture.rs",
        "capture_account_rekey_records_once",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/grouped_capture.rs",
        "capture_asset_definitions_once",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/grouped_capture.rs",
        "capture_assets_once",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/grouped_capture.rs",
        "capture_escrows_once",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/grouped_capture.rs",
        "capture_nfts_once",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/grouped_capture.rs",
        "capture_repo_agreements_once",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/grouped_capture.rs",
        "capture_rwas_once",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/grouped_capture.rs",
        "finish_account_rekey_records_encoding",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/grouped_capture.rs",
        "finish_asset_definition_encoding",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/grouped_capture.rs",
        "finish_assets_encoding",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/grouped_capture.rs",
        "finish_escrows_encoding",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/grouped_capture.rs",
        "finish_nfts_encoding",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/grouped_capture.rs",
        "finish_repo_agreements_encoding",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/grouped_capture.rs",
        "finish_rwas_encoding",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/native_capture.rs",
        "capture_account_alias_table_once",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/native_capture.rs",
        "capture_accounts_table_once",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/native_capture.rs",
        "capture_domains_table_once",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/native_capture.rs",
        "finish_alias_encoding",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/table_capture.rs",
        "capture_actual_state_tables_once",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/table_capture.rs",
        "capture_trigger_action_once",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/table_capture.rs",
        "capture_trigger_by_call_once",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/table_capture.rs",
        "capture_trigger_contracts_once",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/table_capture.rs",
        "capture_trigger_data_once",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/table_capture.rs",
        "capture_trigger_pipeline_once",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/table_capture.rs",
        "capture_trigger_time_once",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/table_capture/aggregate.rs",
        "capture_tables_once",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/table_capture/capture_macros.rs",
        "frozen",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/table_capture/frozen.rs",
        "capture_original_table_once",
        1,
        UseOwner::Roots(&["state_table_substrate"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/transaction_membership.rs",
        "capture_from_storage",
        1,
        UseOwner::Roots(&["state_table_substrate", "transaction_membership_root"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/transaction_membership.rs",
        "capture_membership_group_once",
        1,
        UseOwner::Roots(&["state_table_substrate", "transaction_membership_root"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/transaction_membership.rs",
        "capture_observed",
        1,
        UseOwner::Roots(&["state_table_substrate", "transaction_membership_root"]),
    ),
    function(
        "crates/iroha_core/src/state/authority_registry/complete/transaction_membership.rs",
        "capture_transaction_membership_tables_once",
        1,
        UseOwner::Roots(&["state_table_substrate", "transaction_membership_root"]),
    ),
    function(
        "crates/iroha_core/src/state/canonical_runtime.rs",
        "active_incarnations",
        1,
        UseOwner::Other(Use::Seed, DERIVED_SEED),
    ),
    function(
        "crates/iroha_core/src/state/committed_hash_journal.rs",
        "committed_block_hash_at_height",
        1,
        UseOwner::Other(Use::Record, BLOCK_HASH),
    ),
    function(
        "crates/iroha_core/src/state/committed_hash_journal.rs",
        "committed_block_hashes_snapshot",
        1,
        UseOwner::Other(Use::Record, BLOCK_HASH),
    ),
    function(
        "crates/iroha_core/src/state/deserialize_core.rs",
        "nexus_from_snapshot_runtime",
        1,
        UseOwner::Other(Use::Seed, DERIVED_SEED),
    ),
    function(
        "crates/iroha_core/src/state/deserialize_world_musubi_source_traits.rs",
        "source_musubi_locations_by_pin",
        1,
        UseOwner::Other(Use::Record, TABLE_ACCESSOR),
    ),
    function(
        "crates/iroha_core/src/state/deserialize_world_musubi_source_traits.rs",
        "source_pin_manifests",
        1,
        UseOwner::Other(Use::Record, TABLE_ACCESSOR),
    ),
    function(
        "crates/iroha_core/src/state/execution_commitment_test_support.rs",
        "execution_commitment_for_testing",
        1,
        UseOwner::Other(Use::Test, TEST_ONLY),
    ),
    function(
        "crates/iroha_core/src/state/fastpq_quantity_capture.rs",
        "validate_quantity_retirement_invocation",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/state/native_execution_tip.rs",
        "validate_native_execution_authorization",
        1,
        UseOwner::Other(Use::ResultBinding, CERTIFIED_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/state/native_execution_tip/finalized_world.rs",
        "predecessor_world_receipt_once",
        1,
        UseOwner::Roots(&["world_state_root"]),
    ),
    function(
        "crates/iroha_core/src/state/native_lane_state.rs",
        "sumeragi_lane_state_commitment",
        1,
        UseOwner::Roots(&["native_lane_state_commitment"]),
    ),
    function(
        "crates/iroha_core/src/state/retail_contract_state_snapshot.rs",
        "capture_local_retail_contract_state_v1",
        1,
        UseOwner::Roots(&["retail_contract_state_map_root"]),
    ),
    function(
        "crates/iroha_core/src/state/runtime_catalog.rs",
        "runtime_catalog_hash",
        1,
        UseOwner::Other(Use::Precondition, EXPECTED_VALUE),
    ),
    function(
        "crates/iroha_core/src/state/runtime_catalog.rs",
        "runtime_catalog_root_from_world",
        1,
        UseOwner::Other(Use::Precondition, EXPECTED_VALUE),
    ),
    function(
        "crates/iroha_core/src/state/storage_transactions/block/membership_root.rs",
        "capture_committed_root",
        1,
        UseOwner::Roots(&["transaction_membership_root"]),
    ),
    function(
        "crates/iroha_core/src/state/storage_transactions/block/membership_root.rs",
        "prepare_membership_root",
        1,
        UseOwner::Roots(&["transaction_membership_root"]),
    ),
    function(
        "crates/iroha_core/src/state/storage_transactions/block/membership_root.rs",
        "publish_with_membership_root",
        2,
        UseOwner::Roots(&["transaction_membership_root"]),
    ),
    function(
        "crates/iroha_core/src/state/world_projection.rs",
        "net_state_delta",
        1,
        UseOwner::Roots(&["world_net_delta_fold"]),
    ),
    function(
        "crates/iroha_core/src/state/world_projection.rs",
        "publication_state_delta",
        1,
        UseOwner::Roots(&["world_net_delta_fold"]),
    ),
    function(
        "crates/iroha_core/src/state/world_state_accumulator.rs",
        "run",
        1,
        UseOwner::Roots(&["world_state_root"]),
    ),
    function(
        "crates/iroha_core/src/state/world_state_accumulator.rs",
        "state_transition",
        1,
        UseOwner::Roots(&["world_state_root"]),
    ),
    function(
        "crates/iroha_core/src/state/world_state_accumulator.rs",
        "verify_world_state_accumulator",
        1,
        UseOwner::Roots(&["world_state_root"]),
    ),
    function(
        "crates/iroha_core/src/state/world_state_accumulator.rs",
        "world_state_transition",
        1,
        UseOwner::Roots(&["world_state_root"]),
    ),
    function(
        "crates/iroha_core/src/sumeragi/certified_chain.rs",
        "instance",
        1,
        UseOwner::Other(Use::Seed, DERIVED_SEED),
    ),
    function(
        "crates/iroha_core/src/sumeragi/certified_chain.rs",
        "proof_source_cut",
        1,
        UseOwner::Other(Use::Record, ORIGINAL_WIRE_FENCE),
    ),
    function(
        "crates/iroha_core/src/sumeragi/evidence.rs",
        "committed_evidence_prune_keys_from_state",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/sumeragi/executor.rs",
        "for_state",
        1,
        UseOwner::Other(Use::ResultBinding, CERTIFIED_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/sumeragi/finality.rs",
        "build_proof",
        1,
        UseOwner::Other(Use::ResultBinding, CERTIFIED_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/sumeragi/finality.rs",
        "current_prefix_source",
        1,
        UseOwner::Other(Use::Record, ORIGINAL_WIRE_FENCE),
    ),
    function(
        "crates/iroha_core/src/sumeragi/finality.rs",
        "proof",
        1,
        UseOwner::Other(Use::ResultBinding, CERTIFIED_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/sumeragi/finality.rs",
        "proof_from_chain",
        1,
        UseOwner::Other(Use::ResultBinding, CERTIFIED_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/sumeragi/genesis_meta.rs",
        "staged_genesis_execution_policy_hash",
        1,
        UseOwner::Roots(&["execution_policy_digest"]),
    ),
    function(
        "crates/iroha_core/src/sumeragi/genesis_meta.rs",
        "staged_genesis_nexus_amx_context_hash",
        1,
        UseOwner::Roots(&["nexus_amx_context_digest"]),
    ),
    function(
        "crates/iroha_core/src/sumeragi/test_chain.rs",
        "validate_fixture_genesis_policy",
        1,
        UseOwner::Other(Use::Test, TEST_ONLY),
    ),
    function(
        "crates/iroha_core/src/sumeragi/test_chain/genesis_policy.rs",
        "staged_genesis_policies",
        1,
        UseOwner::Other(Use::Test, TEST_ONLY),
    ),
    function(
        "crates/iroha_core/src/tle_release/casting.rs",
        "derive_parliament_timed_ovn_casting_snapshot_v1",
        1,
        UseOwner::Roots(&["parliament_casting_snapshot_root"]),
    ),
    function(
        "crates/iroha_core/src/tx.rs",
        "authenticated_signed_replay_alias",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/tx.rs",
        "canonical_carrier_membership_hashes",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/tx.rs",
        "sealed_reveal_execution_key",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/validation_fee.rs",
        "retained_enacted_validation_fee_account_reference",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/validation_fee.rs",
        "retained_enacted_validation_fee_asset_reference",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/validation_fee.rs",
        "retained_enacted_validation_fee_asset_reference_in",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/validation_fee.rs",
        "retained_enacted_validation_fee_asset_reference_matching",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/validation_fee.rs",
        "retained_enacted_validation_fee_proposals",
        1,
        UseOwner::Other(Use::Record, RECORD_IDENTITY),
    ),
    function(
        "crates/iroha_core/src/validation_fee_rewards/head_tree.rs",
        "receipt_head_membership",
        1,
        UseOwner::Roots(&["retail_fee_receipt_head_root"]),
    ),
    function(
        "crates/iroha_core/src/validation_fee_rewards/head_tree.rs",
        "receipt_head_root",
        1,
        UseOwner::Roots(&["retail_fee_receipt_head_root"]),
    ),
];
