//! Exact classification of every domain literal that the State inventory scan discovers
//! and that is not a commitment over State content.
//!
//! Each literal is listed as written in the source (escapes are not interpreted). No entry
//! matches a prefix: a new literal fails `state_table_inventory_tests` until it is listed
//! here with its use, or under a commitment in `ROOTS` or an application accumulator.

/// What a domain literal is used for when it is not a commitment over State content.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(super) enum Use {
    /// Domain tag of the execution result, the certified block identity or a lane result.
    ResultBinding,
    /// Key of an execution-witness family.
    WitnessKey,
    /// Commitment over a block's or a transaction's own content.
    BlockContent,
    /// Identifier, content hash, statement or signing preimage of one record or message.
    Record,
    /// Expected-value hash of one State value named by a transaction or a State record.
    Precondition,
    /// Sampling seed or derived identifier.
    Seed,
    /// Schema, wire, backend, parameter or storage-key name: not a hash domain.
    Name,
    /// Binding of a node-local artifact that holds no State content.
    LocalArtifact,
    /// Test input or fixture.
    Test,
}

impl Use {
    /// The name of the use in the inventory.
    pub(super) const fn name(self) -> &'static str {
        match self {
            Self::ResultBinding => "result_binding",
            Self::WitnessKey => "witness_key",
            Self::BlockContent => "block_content",
            Self::Record => "record",
            Self::Precondition => "precondition",
            Self::Seed => "seed",
            Self::Name => "name",
            Self::LocalArtifact => "local_artifact",
            Self::Test => "test",
        }
    }
}

/// One reviewed use and the exact literals it covers.
pub(super) struct OtherDomains {
    pub(super) usage: Use,
    pub(super) reason: &'static str,
    pub(super) literals: &'static [&'static str],
}

/// Every discovered domain literal that no commitment and no application accumulator owns.
pub(super) const OTHER_DOMAINS: &[OtherDomains] = &[
    OtherDomains {
        usage: Use::Seed,
        reason: "KAGEMUSHA ledger lookup identifiers: a fixed custody-index key and derived reserve-asset, reserve-definition and pending-publication keys. They address exact identities in the committed ledger; they neither commit State contents nor establish finality, signing authority or completion",
        literals: &[
            r"iroha:kagemusha:ledger-custody-index:v1\0",
            r"iroha:kagemusha:pending-publication:v1\0",
            r"iroha:kagemusha:reserve-asset:v1\0",
            r"iroha:kagemusha:reserve-definition:v1\0",
        ],
    },
    OtherDomains {
        usage: Use::ResultBinding,
        reason: "Domain tags of the execution result R, of the certified block identity and of lane results: they bind the listed roots and the fields of the listed protocol carriers, and commit no State content of their own",
        literals: &[
            r"iroha/sumeragi/certified-block/v1",
            r"iroha/sumeragi/lane/result/v1",
            r"iroha/sumeragi/result/v1",
        ],
    },
    OtherDomains {
        usage: Use::WitnessKey,
        reason: "Fixed keys and key prefixes of execution-witness families (listed under witness_families): keys of witnessed writes, not digests",
        literals: &[
            r"\0iroha:fastpq:ordinary-source-statements:v1",
            r"\0iroha:fee-evidence:root:v1",
            r"\0iroha:parliament:timed-ovn:casting-contexts:v1",
            r"\0iroha:validation-fee:policy-registry:v1",
            r"\xd4iroha:validation-fee:policy-registry:v1",
            r"\xd5iroha:parliament:timed-ovn:casting-contexts:v1",
            r"\xd7iroha:fastpq:ordinary-source-statements:v1",
            r"\xd8iroha:sccp:state-delta:v1",
        ],
    },
    OtherDomains {
        usage: Use::BlockContent,
        reason: "Merkle and hash domains over a block's or a transaction's own content: transaction and result trees, data-availability commitments and pin intents, FASTPQ source entries, source statements and ordered quantity effects of one block",
        literals: &[
            r"fastpq:execution-effects:v1:context|",
            r"fastpq:execution-effects:v1:effect|",
            r"fastpq:execution-effects:v1:empty|",
            r"fastpq:execution-effects:v1:source|",
            r"fastpq:execution-effects:v1:statement|",
            r"fastpq:execution-effects:v1:step|",
            r"fastpq:v1:ordering",
            r"iroha:da-ingest-request:content:v1\0",
            r"iroha:da-ingest-request:v1\0",
            r"iroha:da:commitment-merkle:commitment:v1\0",
            r"iroha:da:commitment-merkle:internal:v1\0",
            r"iroha:da:commitment-merkle:leaf:v1\0",
            r"iroha:da:pin-intent-merkle:commitment:v1\0",
            r"iroha:da:pin-intent-merkle:internal:v1\0",
            r"iroha:da:pin-intent-merkle:leaf:v1\0",
            r"iroha:da:pin-scope:v1\0",
            r"iroha:fastpq:execution-quantity-key:v1\0",
            r"iroha:fastpq:future-governance-release:shape:v1",
            r"iroha:fastpq:native-fx-authorization:v1",
            r"iroha:fastpq:ordinary-source-statements:empty:v1\0",
            r"iroha:fastpq:original-retirement:v1\0",
            r"iroha:fastpq:quantity-authorization:v1\0",
            r"iroha:fastpq:source-execution-entries:v1\0",
            r"iroha:fastpq:source-inventory:public-transcripts:v1\0",
            r"iroha:fastpq:supply-authorization:v1",
            r"iroha:fastpq:unanchored-transfer-diagnostic:v1|",
            r"iroha:fastpq:v1:authority|",
            r"iroha:merkle:internal:v1\x00",
            r"iroha:merkle:leaf:v1\x00",
        ],
    },
    OtherDomains {
        usage: Use::Record,
        reason: "Fingerprints of the signed genesis consensus configuration and parameters, computed from the genesis block and not from State",
        literals: &[
            r"iroha:native-config:v1",
            r"iroha:sumeragi:v1:consensus-parameters-fingerprint:v1\0",
        ],
    },
    OtherDomains {
        usage: Use::Record,
        reason: "Signing, attestation and transport domains of consensus and network messages (finality attestations, consensus evidence, key-lifecycle certificates, peer trust and gossip, BLS proof-of-possession suites)",
        literals: &[
            r"bls-iroha3:npos-sumeragi:v1",
            r"bls-iroha3:permissioned-sumeragi:v1",
            r"iroha-peer-trust:v2\0",
            r"iroha.consensus.threshold-key-lifecycle.qc.v1\0",
            r"iroha:native-consensus-evidence:v1\0",
            r"iroha:sumeragi-finality-attestation:v1\0",
        ],
    },
    OtherDomains {
        usage: Use::Record,
        reason: "Signing digest of the complete prospective validator-seat readiness context and its exact canonical occupant: network, frozen preparation attempt, target epoch and bounds, ordered BLS generation identity, seat index and installed target beacon session/transcript. The adaptive share-possession challenge wraps this digest under its separate beacon domain; authenticated transition state supplies preparation, credentials and activation authority, and this record digest authenticates no State opening",
        literals: &[r"iroha:validator-seat-readiness:v1"],
    },
    OtherDomains {
        usage: Use::Precondition,
        reason: "Expected-value hashes of one State value that a transaction or a State record names (lane catalog, lane incarnations, runtime catalog, dataspace catalog, fee-sponsor vault snapshot): execution recomputes and compares them, and the value itself is an entry of the keyed State root",
        literals: &[
            r"iroha.nexus.fee-sponsor-vault.allocation-claim.v1",
            r"iroha.nexus.fee-sponsor-vault.source-state.v1",
            r"iroha:nexus:dataspace-catalog:v1\0",
            r"iroha:nexus:lane-catalog:v1\0",
            r"iroha:nexus:lane-incarnations:v1\0",
            r"iroha:nexus:runtime-catalog:v1\0",
            r"nexus-fee-relay:sponsor-vault-policy:v1",
        ],
    },
    OtherDomains {
        usage: Use::Seed,
        reason: "Sampling seeds, election and committee seeds and derived identifiers: lane incarnations and lane committee ranks, relay committees, validator seats, generated asset, RWA and escrow identifiers, invocation call hashes, routing and AMX plan identities",
        literals: &[
            r"gov:parliament:body:agenda:v1",
            r"gov:parliament:body:confirmation_jury:v1",
            r"gov:parliament:body:coordination:v1",
            r"gov:parliament:body:fma:v1",
            r"gov:parliament:body:interest:v1",
            r"gov:parliament:body:mpc:v1",
            r"gov:parliament:body:oversight:v1",
            r"gov:parliament:body:policy_jury:v1",
            r"gov:parliament:body:review:v1",
            r"gov:parliament:body:rules:v1",
            r"iroha/native-lane-authority-selection/v1",
            r"iroha/sumeragi/lane/committee-rank/v1",
            r"iroha/sumeragi/lane/incarnation/v1",
            r"iroha:beacon-sortition:v1:parliament:agenda|",
            r"iroha:beacon-sortition:v1:parliament:confirmation_jury|",
            r"iroha:beacon-sortition:v1:parliament:coordination|",
            r"iroha:beacon-sortition:v1:parliament:fma|",
            r"iroha:beacon-sortition:v1:parliament:interest|",
            r"iroha:beacon-sortition:v1:parliament:mpc|",
            r"iroha:beacon-sortition:v1:parliament:oversight|",
            r"iroha:beacon-sortition:v1:parliament:policy_jury|",
            r"iroha:beacon-sortition:v1:parliament:review|",
            r"iroha:beacon-sortition:v1:parliament:rules|",
            r"iroha:contract-address:v1",
            r"iroha:direct-execution:v1\0",
            r"iroha:lane-relay:committee-member:v1",
            r"iroha:lane-relay:committee-seed:v1",
            r"iroha:lane-relay:test-entropy:v1",
            r"iroha:multisig-contract-trigger:v2\0",
            r"iroha:native-amx-plan:v1",
            r"iroha:native-amx-transfer:v1",
            r"iroha:native-permissioned-leader:v1",
            r"iroha:nexus:lane-incarnation:config:v1\0",
            r"iroha:nexus:lane-incarnation:lifecycle:v1\0",
            r"iroha:nexus:lane-incarnation:static:v2\0",
            r"iroha:nexus:lane-incarnation:synthetic-header:v1\0",
            r"iroha:numeric-movement-context:v1\0",
            r"iroha:pipeline-invocation:v1\0",
            r"iroha:routing-plan:v1",
            r"iroha:rwa:id:v1|",
            r"iroha:sccp:admission-key:v1",
            r"iroha:sccp:v1:route-escrow",
            r"iroha:sumeragi:lane:stake-account:v1\0",
            r"iroha:sumeragi:lane:stake-tenure:v1\0",
            r"iroha:time-invocation:v1\0",
            r"iroha:time-trigger:execution:v1\0",
            r"iroha:trigger-use:action:v1\0",
            r"iroha:tx-gossip-target-seed:v2\0",
            r"iroha:validator-committee-beacon-session:v1",
            r"iroha:validator-election:v1",
            r"iroha:validator-seat:v1",
            r"sumeragi:npos-committee-seat:v1\0",
        ],
    },
    OtherDomains {
        usage: Use::Seed,
        reason: "Threshold-beacon and TLE ceremony, pulse and seed domains: DKG messages, pulse identities, runtime share imports and sampling seeds",
        literals: &[
            r"iroha.beacon.world-test-session.v1\0",
            r"iroha.global-beacon.genesis-attempt.v1\0",
            r"iroha.global-beacon.genesis-session.v1\0",
            r"iroha.global-beacon.local-seat-publication.v1\0",
            r"iroha.global-threshold-beacon.dkg-dealer-commitment.v1\0",
            r"iroha.global-threshold-beacon.dkg-dealer.v1\0",
            r"iroha.global-threshold-beacon.dkg-encrypted-share-hash.v1\0",
            r"iroha.global-threshold-beacon.dkg-events.v1\0",
            r"iroha.global-threshold-beacon.dkg-private-edge.v1\0",
            r"iroha.global-threshold-beacon.dkg-recipient-key-hash.v1\0",
            r"iroha.global-threshold-beacon.dkg-recipient-key.v1\0",
            r"iroha.global-threshold-beacon.dkg-share-acceptance.v1\0",
            r"iroha.global-threshold-beacon.governance-seed.v1\0",
            r"iroha.global-threshold-beacon.lane-relay-seed.v1\0",
            r"iroha.global-threshold-beacon.npos-successor-seed.v1\0",
            r"iroha.global-threshold-beacon.prepared-seat-readiness.v1\0",
            r"iroha.global-threshold-beacon.pulse-id.v1\0",
            r"iroha.global-threshold-beacon.pulse-payload.v1\0",
            r"iroha.global-threshold-beacon.runtime-share-import.v1\0",
            r"iroha.parliament.tle-release.runtime-share-import.v1\0",
            r"iroha.runtime-consensus-threshold.public-inventory.v1",
            r"iroha.runtime_provider_broker.v1.consensus_threshold.global_beacon_public_inventory",
            r"iroha.runtime_provider_broker.v1.consensus_threshold.global_beacon_signer_credential",
        ],
    },
    OtherDomains {
        usage: Use::LocalArtifact,
        reason: "Bindings of node-local files and process state that hold block, consensus or configuration data (Kura eviction files, bound-progress appends, the storage path of a lane instance, the node-configuration identity): no State field is digested",
        literals: &[
            r"iroha/sumeragi/node-configuration/v1\0",
            r"iroha:kura:bound-progress-append-intent:v1\0",
            r"iroha:kura:bound-progress-append:v1\0",
            r"iroha:kura:eviction-file:v1\0",
            r"iroha:kura:lane-storage-instance:v1\0",
        ],
    },
    OtherDomains {
        usage: Use::LocalArtifact,
        reason: "Framing of the journal witness of the telemetry status classifier: a digest of a bounded suffix of the committed block-hash journal (heights and header hashes of the history field state.block_hashes), compared inside one process. It digests authenticated history and no canonical State entry, and it is never stored or carried",
        literals: &[r"iroha:telemetry:classified-journal:v1\0"],
    },
    OtherDomains {
        usage: Use::Seed,
        reason: "Digests of the consensus projection of one lane configuration and of the lane catalog. They are compared for equality inside one process, to decide which lanes reset, and they are inputs of the static, configuration and lifecycle derivations of the lane incarnation, the identifier that State stores per lane. The two digests themselves are never stored or carried",
        literals: &[
            r"iroha:merge:lane-config:v2\0",
            r"iroha:merge:lane-consensus-catalog:v1\0",
        ],
    },
    OtherDomains {
        usage: Use::Name,
        reason: "Schema descriptor domain of the specified keyed State commitment (sumeragi.md section 16.1) and the root domain of its test-only reference oracle; no root is built from them before G.3",
        literals: &[
            r"iroha:state-keyed-commitment:reference-oracle:root:v1\0",
            r"iroha:state-keyed-commitment:schema:v1\0",
        ],
    },
    OtherDomains {
        usage: Use::Name,
        reason: "Semantic codec identities of registry fields and their components: schema names, not hash domains",
        literals: &[
            r"iroha:state:content-stripe-layout:v1",
            r"iroha:state:content:v1",
            r"iroha:state:crypto:v1",
            r"iroha:state:executor-semantic:v1",
            r"iroha:state:fraud-monitoring-attester:v1",
            r"iroha:state:fraud_monitoring:v1",
            r"iroha:state:governance-vk-ref:v1",
            r"iroha:state:governance:v1",
            r"iroha:state:lane-manifest-bound-catalog-row:v1",
            r"iroha:state:lane-manifest-privacy-commitment:v1",
            r"iroha:state:lane-manifest-rules:v1",
            r"iroha:state:lane-manifest-runtime-upgrade:v1",
            r"iroha:state:lane-manifest-source-content:v1",
            r"iroha:state:lane-manifest-source-entry:v1",
            r"iroha:state:lane-manifest-source:v1",
            r"iroha:state:lane-manifest-status:v1",
            r"iroha:state:lane-manifest-validator-binding:v1",
            r"iroha:state:lane_compliance:v1",
            r"iroha:state:lane_manifests:v1",
            r"iroha:state:musubi-availability-authority:v1",
            r"iroha:state:musubi-directory-authority:v1",
            r"iroha:state:musubi-resolver-authority:v1",
            r"iroha:state:nexus:v1",
            r"iroha:state:oracle-economics:v1",
            r"iroha:state:oracle-governance:v1",
            r"iroha:state:oracle-twitter-binding:v1",
            r"iroha:state:oracle-vote-thresholds:v1",
            r"iroha:state:oracle:v1",
            r"iroha:state:parliament-timed-ovn:v1",
            r"iroha:state:parliament-tle-key-lifecycle:v1",
            r"iroha:state:pipeline-gas-rate:v1",
            r"iroha:state:pipeline-gas:v1",
            r"iroha:state:pipeline:v1",
            r"iroha:state:runtime-lane-catalog:v1",
            r"iroha:state:runtime-upgrade-provenance:v1",
            r"iroha:state:settlement-router:v1",
            r"iroha:state:settlement:v1",
            r"iroha:state:sorafs-penalty-policy:v1",
            r"iroha:state:sorafs-pin-approval-signer:v1",
            r"iroha:state:sorafs-pin-policy:v1",
            r"iroha:state:sorafs-telemetry-policy:v1",
            r"iroha:state:trigger-by-call-action:v1",
            r"iroha:state:trigger-contract-bytecode:v1",
            r"iroha:state:trigger-data-action:v1",
            r"iroha:state:trigger-pipeline-action:v1",
            r"iroha:state:trigger-time-action:v1",
            r"iroha:state:viral-incentives:v1",
            r"iroha:state:zk-confidential:v1",
            r"iroha:state:zk-halo2:v1",
            r"iroha:state:zk-pipa-r:v1",
            r"iroha:state:zk-proof-retention:v1",
            r"iroha:state:zk-sccp:v1",
            r"iroha:state:zk-stark:v1",
            r"iroha:state:zk-verification-gas:v1",
            r"iroha:state:zk-verifying-key-ref:v1",
            r"iroha:state:zk:v1",
            r"musubi.v0.aliases",
            r"world.smart_contract_state.retail_day_v1",
        ],
    },
    OtherDomains {
        usage: Use::Name,
        reason: "Instruction, proposal and wire-schema identifiers, custom-parameter identifiers, metadata keys and capability names: names, not hash domains",
        literals: &[
            r"autoscale.committee_v1",
            r"gas.parity.v1",
            r"instruction.log.v1",
            r"instruction.upgrade.v1",
            r"iroha.asset.retail_day.activate.v1",
            r"iroha.asset.retail_day.identity.bind.v1",
            r"iroha.asset.retail_day.monetary_movement.v1",
            r"iroha.bpng.retail-identity.v1",
            r"iroha.consensus.threshold-key-lifecycle.apply.v1",
            r"iroha.faucet.claim.consumed.key.v1\0",
            r"iroha.kagemusha.wallet.ledger.v1",
            r"iroha.offline.kagemusha.recursive_release.cancel.v1",
            r"iroha.offline.kagemusha.recursive_release.deactivate.v1",
            r"iroha.offline.kagemusha.recursive_release.enable.v1",
            r"iroha.offline.kagemusha.taira_canary.authorize.v1",
            r"iroha.offline.kagemusha.taira_canary.record.v1",
            r"iroha.private_dataspace.anchor.v1",
            r"iroha.private_dataspace.register.v1",
            r"iroha.private_settlement.abort_atomic_bundle.v1",
            r"iroha.private_settlement.activate_pool.v1",
            r"iroha.private_settlement.finalize_atomic_bundle.v1",
            r"iroha.private_settlement.register_atomic_prepare.v1",
            r"iroha.private_settlement.rotate_pool_policy.v1",
            r"iroha.sccp.bridge_key.v1",
            r"iroha.sccp.other.v1",
            r"iroha.streaming.snapshot.v1",
            r"iroha.sumeragi.amx.begin.v1",
            r"iroha.sumeragi.amx.prepare.v1",
            r"iroha.sumeragi.amx.register_dataspace.v1",
            r"iroha.sumeragi.amx.register_participant.v1",
            r"iroha.sumeragi.amx.relay_global_handoff.v1",
            r"iroha.sumeragi.amx.relay_handoff.v1",
            r"iroha.sumeragi.amx.relay_prepared.v1",
            r"iroha.sumeragi.amx.settle.v1",
            r"iroha.tx.submission.receipt@v1",
            r"iroha.validation_fee_rewards.release_verified.v1",
            r"iroha.validation_fee_rewards.verified.v1",
            r"iroha.wire_schema.v1\0",
            r"iroha.zk-lane.task.v1",
            r"iroha:asset_issuer_usage_policy_v1",
            r"iroha:created_via",
            r"iroha:da-ingest-admission-policy:v1\0",
            r"iroha:da_ingest_admission_policy_v1",
            r"iroha:default_account_admission_policy",
            r"iroha:domain_asset_usage_policy_v1",
            r"iroha:fx_corridor_policies",
            r"iroha:hijiri_account_risk_v1:",
            r"iroha:hijiri_parameters_v1",
            r"iroha:kiso:test:soranet-transport:v1",
            r"iroha:kotodama:error-schema:v1\0",
            r"iroha:multisig_home_domain",
            r"iroha:validation_fee_governance_keyset_v1",
            r"iroha:validation_fee_policy_registry_v1",
            r"iroha:validation_fee_policy_v1",
            r"iroha_core.ivm_host.alias_contract_cases.v1",
            r"policy.v1",
            r"referendum.v1",
            r"v1/status",
        ],
    },
    OtherDomains {
        usage: Use::Name,
        reason: "Proof-backend, circuit, protocol-profile, cipher-suite, ABI, model and parameter-set identifiers and command names: names, not hash domains of a commitment over State content",
        literals: &[
            r"-v1",
            r"abi-v1",
            r"agenda-sortition-blake3-v1",
            r"anonymous-pgc-k-out-of-n-v1",
            r"artifact-v1",
            r"ballot-v1",
            r"baseline-v1",
            r"baseline-v2",
            r"bfv-affine-v1",
            r"bfv-programmed-v1",
            r"build-anonymous-pgc-action-v1",
            r"build-bootle-lantern-action-v1",
            r"build-fcmp-action-v1",
            r"build-ivm-private-note-action-v1",
            r"build-jindo-action-v1",
            r"build-orchard-action-v1",
            r"build-pq-masp-action-v1",
            r"build-vega-action-v1",
            r"build-verange-action-v1",
            r"build-zk-ace-action-v1",
            r"defi-oracle-attestation-v1",
            r"executor-preverify-v1",
            r"explicit-governed-registration-and-activation-v1",
            r"fastpq-state-transition-stark-v1",
            r"fhe/bfv-rns/v1",
            r"finance-v1",
            r"governance-v1",
            r"governance-v2",
            r"governed-fhe-material-v1",
            r"halo2/ipa/ivm-execution-v1",
            r"halo2/ipa/ivm-replay-binding-v1",
            r"halo2/ipa:ivm-execution-v1",
            r"halo2/ipa:ivm-replay-binding-v1",
            r"halo2/ipa:unknown-native-v1",
            r"pipa-r/pasta/confidential-transfer-v1",
            r"pipa-r/pasta/confidential-unshield-change-v1",
            r"pipa-r/pasta/confidential-unshield-full-v1",
            r"halo2/pasta/ipa-pasta-cycle-v1",
            r"halo2/pasta/ipa/ivm-execution-v1",
            r"halo2/pasta/ipa/ivm-replay-binding-v1",
            r"halo2/pasta/ipa/kaigi-authorization-v1",
            r"halo2/pasta/ipa/kaigi-roster-v1",
            r"halo2/pasta/ipa/kaigi-usage-v1",
            r"halo2/pasta/ipa/vote-bool-commit-merkle8-v1",
            r"halo2/pasta/ivm-execution-v1",
            r"halo2/pasta/ivm-replay-binding-v1",
            r"halo2/pasta/ivm-replay-binding-v1/",
            r"halo2/pasta/ivm-replay-binding-v1\0",
            r"halo2/pasta/ivm_execution_v1",
            r"halo2/pasta/kaigi-authorization-v1",
            r"halo2/pasta/kaigi-authorization-v1/",
            r"halo2/pasta/kaigi-roster-v1",
            r"halo2/pasta/kaigi-usage-v1",
            r"halo2/unknown-native-v1",
            r"hkdf-sha3-512-prf-v1",
            r"host-batch-v1",
            r"identifier-receipt-attestation-v1",
            r"iroha-bootle-lantern-anoncred-v1",
            r"iroha-election-v1",
            r"iroha-ivm-private-note-stark-v1",
            r"iroha-jindo-polynomial-commitment-v1",
            r"iroha-kaigi-first-release-v1",
            r"iroha-musubi-instructions-v1",
            r"iroha-musubi-sdk-v1",
            r"iroha-native-amx-custody-v1",
            r"iroha-native-asset-escrow-v1",
            r"iroha-peer-gossip-v1",
            r"iroha-privacy-exact12-v1",
            r"iroha-soranet-vpn-lease-v1",
            r"iroha-zk-ams-v1",
            r"iroha-zk-x509-stark-p256-v1",
            r"ivm-replay-binding-v1",
            r"ivm-v1",
            r"kaigi-authorization-v1",
            r"kaigi-roster-v1",
            r"kaigi-usage-v1",
            r"ml-kem-1024-xchacha20-poly1305-v1",
            r"ml-kem-768-xchacha20-poly1305-v1",
            r"monero-fcmp-plus-plus-v1",
            r"native-goldilocks-sha3-384-stark-fri-v1",
            r"numeric-v1",
            r"orchard-halo2-actions-v1",
            r"other-v1",
            r"pepper-social-v1",
            r"pipa-r/ipa/pasta/kaigi-authorization-v1",
            r"pipa-r/ipa/pasta/kaigi-usage-v1",
            r"pipa-r/pasta/kaigi-authorization-v1",
            r"pipa-r/pasta/kaigi-usage-v1",
            r"pipa-r/pasta/kaigi-usage-v1/",
            r"policy-v1",
            r"poseidon-x7-goldilocks-6x64-v1",
            r"pq-masp-stark-v1",
            r"privacy-exact12-catalog-v1",
            r"risk-model-v1",
            r"schema:voting:halo2:v1",
            r"schema:voting:stark:v1",
            r"schema:voting:v1",
            r"schema:voting:v2",
            r"settlement-v1",
            r"settlement-v3",
            r"sis-hints-anoncred-pq-v0",
            r"stark-fri-sha3-384-goldilocks-v1",
            r"stark/fri-v2",
            r"stark/fri/../zk_ace_pq_authorization_v1",
            r"stark/fri/./zk_ace_pq_authorization_v1",
            r"stark/fri/.zk_ace_pq_authorization_v1",
            r"stark/fri/poseidon-x7-goldilocks-6x64-v1",
            r"stark/fri/poseidon-x7-goldilocks-6x64-v1.:zk_ace",
            r"stark/fri/poseidon-x7-goldilocks-6x64-v1/",
            r"stark/fri/poseidon-x7-goldilocks-6x64-v1/:zk_ace",
            r"stark/fri/poseidon-x7-goldilocks-6x64-v1/extra",
            r"stark/fri/poseidon-x7-goldilocks-6x64-v1:.zk_ace",
            r"stark/fri/poseidon-x7-goldilocks-6x64-v1:/zk_ace",
            r"stark/fri/poseidon-x7-goldilocks-6x64-v1:curve-test",
            r"stark/fri/poseidon-x7-goldilocks-6x64-v1:dummy-circuit",
            r"stark/fri/poseidon-x7-goldilocks-6x64-v1:generic_binding_v1",
            r"stark/fri/poseidon-x7-goldilocks-6x64-v1:host-batch-v1",
            r"stark/fri/poseidon-x7-goldilocks-6x64-v1:not-a-ballot-circuit",
            r"stark/fri/poseidon-x7-goldilocks-6x64-v1:not-a-tally-circuit",
            r"stark/fri/poseidon-x7-goldilocks-6x64-v1:public_relation_v1",
            r"stark/fri/poseidon-x7-goldilocks-6x64-v1:update-curve",
            r"stark/fri/poseidon-x7-goldilocks-6x64-v1:vote-ballot",
            r"stark/fri/poseidon-x7-goldilocks-6x64-v1:vote-tally",
            r"stark/fri/poseidon-x7-goldilocks-6x64-v1:weak-rehydrated-key",
            r"stark/fri/poseidon-x7-goldilocks-6x64-v1:zk-ace",
            r"stark/fri/poseidon-x7-goldilocks-6x64-v1\0",
            r"stark/fri/poseidon-x7-goldilocks-6x64-v1\nforged",
            r"stark/fri/sha256_goldilocks.v1",
            r"stark/unknown-native-v1",
            r"taira-privacy-release-evidence-v1",
            r"tally-v1",
            r"vega-existing-credential-zk-v1",
            r"verange-transparent-range-v1",
            r"zk-ace-pq-authorization-v1",
        ],
    },
    OtherDomains {
        usage: Use::Name,
        reason: "Prefixes and derivations of State storage keys (contract-state paths and reserved native key spaces) and of local file names: keys of rows, not commitments",
        literals: &[
            r"blocks.data.eviction-v1",
            r"blocks.index.eviction-v1",
            r"committed.replay.v1",
            r"da_ingest_quota_v1/",
            r"da_ingest_quota_v1/authority/",
            r"faucet_claim_consumed_v1/",
            r"iroha.fastpq.balance-key.v1",
            r"retail_day_activation_v1/",
            r"retail_day_identity_v1/",
            r"retail_day_monetary_operation_v1/",
            r"retail_day_policy_v1/",
            r"retail_day_usage_v1/",
            r"retail_fee_control_v1/",
            r"retail_fee_control_v1/sweep_cursor",
            r"retail_fee_heads_v1/",
            r"retail_fee_receipts_v1/",
            r"retail_fee_receipts_v1/test",
            r"retail_fee_sequence_v1/",
            r"retail_fee_v1/",
            r"sc/contract/sorafs_reserve_state_v1",
            r"sns/auto_renew_cursor/v1",
            r"sorafs_pin_accounting_v1/authority/",
            r"sorafs_pin_accounting_v1/expiry/",
            r"sorafs_pin_accounting_v1/global",
            r"sorafs_pin_accounting_v1/lineage/",
            r"sorafs_pin_accounting_v1/status/",
            r"user/sorafs_reserve_state_v1",
        ],
    },
    OtherDomains {
        usage: Use::Record,
        reason: "Identifiers, content hashes, intent digests and signing preimages of one application record, transaction plan or message (settlement and repo intents, NFT and game custody, Hijiri risk records, staking records, retail fee receipts, alias attestations, jurisdiction attestations, contract artifacts, RAM-LFE receipts, IVM statements)",
        literals: &[
            r"iroha.ivm-proved.transaction-intent-digest.v1",
            r"iroha.ivm.execution-statement.v1",
            r"iroha.ram_lfe.v1.opening",
            r"iroha.ram_lfe.v1.receipt",
            r"iroha.retail_fee.account_state.v1",
            r"iroha.retail_fee.payment_intent.v1",
            r"iroha.retail_fee.receipt.v1",
            r"iroha.retail_fee.receipt_chain.v1",
            r"iroha.sealed_tx.v1",
            r"iroha.staking.pending_unbond.v1\0",
            r"iroha.staking.public_lane_candidate.v1",
            r"iroha.staking.public_lane_peer_binding.v1",
            r"iroha.staking.reward_record.v1\0",
            r"iroha.validation_fee.payout_lifecycle.seal.v1",
            r"iroha.validation_fee.policy.parliament.v1",
            r"iroha/sumeragi/amx/transaction/v1",
            r"iroha:account-onboarding-plan-receipt:v1\0",
            r"iroha:alias-lifecycle-transaction-plan-body:v1\0",
            r"iroha:alias-transaction-plan-body:v1\0",
            r"iroha:alias:attestation:v1",
            r"iroha:conditional-escrow-evidence:v1\0",
            r"iroha:contract-lifecycle-transition:v1\0",
            r"iroha:fx-corridor:escrow-account:v1",
            r"iroha:game:custody:v1",
            r"iroha:game:session:v1\0",
            r"iroha:hijiri:account-risk-id:v1\0",
            r"iroha:hijiri:account-risk:v1\0",
            r"iroha:hijiri:fee-quote:v1\0",
            r"iroha:hijiri:parameters:v1\0",
            r"iroha:ivm:contract-artifact:v1\0",
            r"iroha:ivm:queued-call-hash:v1|",
            r"iroha:jurisdiction:attestation:v1\x00",
            r"iroha:jurisdiction:sdn:commitment:v1\x00",
            r"iroha:nft-market:v1:owner-reservation:exact-terms:atomic-payment:immutable-content:height-expiry:one-shot",
            r"iroha:nft:custody:v1",
            r"iroha:nft:exact-price-offer:v1\0",
            r"iroha:private-dataspace:record:v1\0",
            r"iroha:repo:initiation-intent:v1\0",
            r"iroha:repo:maturity-intent:v1\0",
            r"iroha:retail_fee:assessment:v1:",
            r"iroha:settlement:atomic-intent:v1\0",
            r"iroha:settlement:dvp-intent:v1\0",
            r"iroha:settlement:pvp-intent:v1\0",
            r"iroha:sns:native-maintenance-source:v1",
        ],
    },
    OtherDomains {
        usage: Use::Record,
        reason: "Content commitments of one complete supplied Kotodama source inventory and its exact admitted contract manifest, recorded in the native compilation receipt draft: hashes of these immutable input records, not digests computed from State tables",
        literals: &[
            r"iroha.contract.native-source-inventory.v1\0",
            r"iroha.contract.native-source-manifest.v1\0",
        ],
    },
    OtherDomains {
        usage: Use::Record,
        reason: "Digest of a supplied alias frontier snapshot event payload; no node code computes it from State",
        literals: &[r"iroha:alias:frontier:v1|"],
    },
    OtherDomains {
        usage: Use::Record,
        reason: "AXT handle, anchor, receipt and spend-intent digests and derived asset-incarnation identifiers: each hashes one record of one transaction",
        literals: &[
            r"iroha:axt:anchored-spend:handle:digest:v1\0",
            r"iroha:axt:anchored-spend:issuer-signature:v1\0",
            r"iroha:axt:anchored-spend:proof:digest:v1\0",
            r"iroha:axt:asset-handle-issuer:v1\0",
            r"iroha:axt:asset-incarnation:v1\0",
            r"iroha:axt:desc:v1\0",
            r"iroha:axt:finalized-spend-anchor:digest:v1\0",
            r"iroha:axt:genesis-asset-incarnation:v1\0",
            r"iroha:axt:ordered-transaction-wire-set:v1\0",
            r"iroha:axt:proof-cache:v1",
            r"iroha:axt:remote-spend-intent:v1\0",
            r"iroha:axt:source-success-receipt:digest:v1\0",
            r"iroha:axt:source-transfer-occurrence:digest:v1\0",
            r"iroha:axt:source-transfer:digest:v1\0",
        ],
    },
    OtherDomains {
        usage: Use::Record,
        reason: "Governance and Parliament identifiers, proposal and transition wire names, and fingerprints of the components of one governance record: the roster, candidate, assignment, ballot and expected-head 'roots' are flat fingerprints stored in that record, and the registration-corpus commitment digests the records held in the same lifecycle value",
        literals: &[
            r"iroha.governance.attempt.id.v1",
            r"iroha.governance.certificate.id.v1",
            r"iroha.governance.effect_preimage.v1",
            r"iroha.governance.parliament.assignment.id.v1",
            r"iroha.governance.parliament.assignment_plan.root.v1",
            r"iroha.governance.parliament.attempt.create.v1",
            r"iroha.governance.parliament.automatic_execution_outcome.digest.v1",
            r"iroha.governance.parliament.ballot_attempt.id.v1",
            r"iroha.governance.parliament.ballot_failure.root.v1",
            r"iroha.governance.parliament.ballot_participant.hash.v1",
            r"iroha.governance.parliament.ballot_result.root.v1",
            r"iroha.governance.parliament.body_election_attempt.id.v1",
            r"iroha.governance.parliament.body_instance.id.v1",
            r"iroha.governance.parliament.candidate.root.v1",
            r"iroha.governance.parliament.execution_failure.root.v1",
            r"iroha.governance.parliament.expected_head.root.v1",
            r"iroha.governance.parliament.lifecycle_transition.digest.v1",
            r"iroha.governance.parliament.lifecycle_transition.other.v1",
            r"iroha.governance.parliament.logical_beacon_session.id.v1",
            r"iroha.governance.parliament.public_finding_endorsement.root.v1",
            r"iroha.governance.parliament.roster.root.v1",
            r"iroha.governance.parliament.sortition_request.id.v1",
            r"iroha.governance.parliament.tle_session.id.v1",
            r"iroha.governance.parliament.transition.submit.v1",
            r"iroha.governance.proposal.contract_emergency_hold.v1",
            r"iroha.governance.proposal.contract_lifecycle.v1",
            r"iroha.governance.proposal.deploy_contract.v1",
            r"iroha.governance.proposal.global_data_trigger_permission.v1",
            r"iroha.governance.proposal.musubi_registry_governance.v1",
            r"iroha.governance.proposal.runtime_upgrade.v1",
            r"iroha.governance.proposal.sccp_route_governance.v1",
            r"iroha.governance.proposal.sorafs_provider_governance.v1",
            r"iroha.governance.proposal.validation_fee_payout_lifecycle.v1",
            r"iroha.governance.proposal.validation_fee_policy.v1",
            r"iroha.governance.subject.id.v1",
            r"iroha.ministry.policy-jury.ballot.commitment.v1",
            r"iroha:gov:nullifier:v1",
            r"iroha:parliament:timed-ovn:registration-corpus:v1\0",
        ],
    },
    OtherDomains {
        usage: Use::Record,
        reason: "KAGEMUSHA wallet-wire domain prefix and wallet advance provider-contract identity: these name or hash one application record or message",
        literals: &[
            r"iroha:kagemusha:wallet:v1:",
            r"kagemusha-advance-journal-marker-v1",
        ],
    },
    OtherDomains {
        usage: Use::Record,
        reason: "Musubi registry instruction identifiers, release and attestation digests and signing preimages",
        literals: &[
            r"iroha.musubi.archive-id.v1",
            r"iroha.musubi.namespace-binding.v1",
            r"iroha.musubi.namespace-delegation.signature.v1",
            r"iroha.musubi.parliament-action.v1",
            r"iroha.musubi.provider-bundle-attestation-set.digest.v1",
            r"iroha.musubi.provider-bundle-attestation.digest.v1",
            r"iroha.musubi.provider-bundle-attestation.signature.v1",
            r"iroha.musubi.release-digest.v1",
            r"iroha.musubi.search-query.v1",
            r"iroha.musubi.seed-ingress-receipt.signature.v1",
            r"iroha.musubi.semantic-release-digest.v1",
            r"iroha.musubi.signed_fixtures.owner.v1",
            r"iroha.musubi.v1.alias.register",
            r"iroha.musubi.v1.archive.register",
            r"iroha.musubi.v1.archive_location.add",
            r"iroha.musubi.v1.archive_location.retire",
            r"iroha.musubi.v1.namespace_binding.register",
            r"iroha.musubi.v1.package_member.accept",
            r"iroha.musubi.v1.package_member.invitation.revoke",
            r"iroha.musubi.v1.package_member.invite",
            r"iroha.musubi.v1.package_member.remove",
            r"iroha.musubi.v1.package_member.set_role",
            r"iroha.musubi.v1.package_metadata.set",
            r"iroha.musubi.v1.parliament.alias_retarget",
            r"iroha.musubi.v1.parliament.artifact_takedown",
            r"iroha.musubi.v1.parliament.package_recover",
            r"iroha.musubi.v1.parliament.registry_policy.set",
            r"iroha.musubi.v1.pin_outbox.advance",
            r"iroha.musubi.v1.pin_outbox.check",
            r"iroha.musubi.v1.provider_bundle_attestation.register",
            r"iroha.musubi.v1.release.publish",
            r"iroha.musubi.v1.release_digest.assert",
            r"iroha.musubi.v1.release_yank.set",
            r"iroha.musubi.verification-lock.v1",
            r"musubi-v1",
        ],
    },
    OtherDomains {
        usage: Use::Record,
        reason: "Privacy-engine instruction identifiers, statements, policy and issuer records, release evidence and signing preimages: each names or hashes one record, statement or message",
        literals: &[
            r"0\0zk-ace-pq-authorization-v1\0pq-qrom\0",
            r"10\0iroha-ivm-private-note-stark-v1\0pq-qrom\0",
            r"11\0pq-masp-stark-v1\0pq-qrom\0",
            r"1\0anonymous-pgc-k-out-of-n-v1\0classical-rom\0",
            r"2\0verange-transparent-range-v1\0classical-rom\0",
            r"3\0iroha-zk-ams-v1\0classical-rom\0",
            r"4\0vega-existing-credential-zk-v1\0classical-rom\0",
            r"5\0iroha-zk-x509-stark-p256-v1\0classical-rom\0",
            r"6\0iroha-jindo-polynomial-commitment-v1\0pq-qrom\0",
            r"7\0iroha-bootle-lantern-anoncred-v1\0pq-qrom\0",
            r"8\0orchard-halo2-actions-v1\0classical-rom\0",
            r"9\0monero-fcmp-plus-plus-v1\0classical-rom\0",
            r"iroha.privacy.bootstrap_orchard_pool.v1",
            r"iroha.privacy.bootstrap_pgc_accounts.v1",
            r"iroha.privacy.bootstrap_proof_managed_pool.v1",
            r"iroha.privacy.bootstrap_zk_ams_registry.v1",
            r"iroha.privacy.compiled-profile-catalog.v1",
            r"iroha.privacy.exact12-capability-manifest.v1",
            r"iroha.privacy.exact12-deployment-qualification.v1",
            r"iroha.privacy.exact12-qualification-record.v1",
            r"iroha.privacy.exact12-release-manifest.v1",
            r"iroha.privacy.exact12-typed-fixture-bundle.v1",
            r"iroha.privacy.exact12-typed-fixture-row.v1",
            r"iroha.privacy.exact12.catalog.v1\0",
            r"iroha.privacy.monero-fcmp-plus-plus.output-id.v1",
            r"iroha.privacy.native-consensus-binding.v1",
            r"iroha.privacy.pgc-runtime-test-rng.v1",
            r"iroha.privacy.proof-envelope.v1",
            r"iroha.privacy.proof.v1",
            r"iroha.privacy.publish_root.v1",
            r"iroha.privacy.register_bootle_lantern_issuer_policy.v1",
            r"iroha.privacy.register_exact12_qualification.v1",
            r"iroha.privacy.register_protocol_activation.v1",
            r"iroha.privacy.register_vega_issuer.v1",
            r"iroha.privacy.register_zk_ace_policy.v1",
            r"iroha.privacy.register_zk_x509_certificate_policy.v1",
            r"iroha.privacy.register_zk_x509_crl.v1",
            r"iroha.privacy.register_zk_x509_trust_anchor.v1",
            r"iroha.privacy.release.anonymous-pgc.account-root-effect.v1",
            r"iroha.privacy.release.anonymous-pgc.bootstrap-public-statement.v1",
            r"iroha.privacy.release.anonymous-pgc.public-statement.v1",
            r"iroha.privacy.release.evidence.internal-seed.v1",
            r"iroha.privacy.release.evidence.purpose-seed.v1",
            r"iroha.privacy.release.evidence.rng06.v1",
            r"iroha.privacy.release.evidence.rng09.v1",
            r"iroha.privacy.release.fcmp-plus-plus.compiled-profile-tuple.v1",
            r"iroha.privacy.release.fcmp-plus-plus.context-hash.v1",
            r"iroha.privacy.release.fcmp-plus-plus.public-statement.v1",
            r"iroha.privacy.release.ivm-private-note.bound-statement.v1",
            r"iroha.privacy.release.network-action.seed.v1",
            r"iroha.privacy.release.orchard.public-statement.v1",
            r"iroha.privacy.release.ordered-public-statements.v1",
            r"iroha.privacy.release.pq-masp.bound-statement.v1",
            r"iroha.privacy.release.verange.public-statement.v1",
            r"iroha.privacy.release.zk-ams.authoritative-prestate-lineage.v1",
            r"iroha.privacy.release.zk-x509-public-statement-and-resource-shape.v1",
            r"iroha.privacy.revoke_bootle_lantern_issuer_policy.v1",
            r"iroha.privacy.revoke_vega_issuer.v1",
            r"iroha.privacy.revoke_zk_ace_policy.v1",
            r"iroha.privacy.revoke_zk_x509_certificate_policy.v1",
            r"iroha.privacy.revoke_zk_x509_crl.v1",
            r"iroha.privacy.revoke_zk_x509_trust_anchor.v1",
            r"iroha.privacy.rotate_bootle_lantern_issuer_policy.v1",
            r"iroha.privacy.rotate_vega_issuer.v1",
            r"iroha.privacy.rotate_zk_ace_policy.v1",
            r"iroha.privacy.rotate_zk_x509_certificate_policy.v1",
            r"iroha.privacy.rotate_zk_x509_crl.v1",
            r"iroha.privacy.rotate_zk_x509_trust_anchor.v1",
            r"iroha.privacy.schedule_consensus_policy_tightening.v1",
            r"iroha.privacy.schedule_protocol_limits_tightening.v1",
            r"iroha.privacy.signed-submission-hash.v1",
            r"iroha.privacy.statement.v1",
            r"iroha.privacy.submit_proof.v1",
            r"iroha.privacy.transaction-intent-digest.v1",
            r"iroha.privacy.transition_protocol_lifecycle.v1",
            r"iroha.privacy.vega.issuer-record.sha256-frame.v1",
            r"iroha.privacy.zk-ace.authorization-statement.v1",
            r"iroha.privacy.zk-ace.policy-digest-material.v1",
            r"iroha.privacy.zk-ace.public-inputs.v1",
            r"iroha.taira.privacy_action_driver_request.v1\0",
            r"iroha.taira.privacy_action_driver_seed.v1\0",
            r"iroha.taira.public-reset.generated-path.v1",
            r"iroha.taira.verange_qualification_setup_identity.v1\0",
            r"iroha.taira.verange_qualification_setup_seed.v1\0",
            r"iroha.zk-x509.crl.der.v1",
            r"iroha.zk-x509.crl.issuer-spki.v1",
            r"iroha.zk-x509.sha256.frame.v1",
            r"iroha:privacy:bootle-lantern:issuer-parameter:v1",
            r"iroha:privacy:bootle-lantern:issuer-policy:v1",
            r"iroha:privacy:exact12-capability-manifest:v1",
            r"iroha:privacy:exact12:abi-v1-syscall-list:v1",
            r"iroha:privacy:exact12:audit-bundle:v1",
            r"iroha:privacy:exact12:audit-signature:v1",
            r"iroha:privacy:exact12:deployment-qualification:v1",
            r"iroha:privacy:exact12:deployment-roster:v1",
            r"iroha:privacy:exact12:deployment-signature:v1",
            r"iroha:privacy:exact12:medium-disposition:v1",
            r"iroha:privacy:exact12:release-artifact-set:v1",
            r"iroha:privacy:exact12:release-manifest:v1",
            r"iroha:privacy:exact12:release-signature:v1",
            r"iroha:privacy:ivm-private-note:action:v1",
            r"iroha:privacy:native-consensus-binding:v1",
            r"iroha:privacy:orchard-pool-bootstrap:v1",
            r"iroha:privacy:pgc-account-bootstrap:v1",
            r"iroha:privacy:pgc-bootstrap-proof:v1",
            r"iroha:privacy:proof-managed-pool-bootstrap:v1",
            r"iroha:privacy:security-claim:v1",
            r"iroha:privacy:statement:v1",
            r"iroha:privacy:vega:issuer-record:v1",
            r"iroha:privacy:zk-ace:policy-record:v1",
            r"iroha:privacy:zk-ams:issuer-policy-record:v1",
            r"iroha:privacy:zk-ams:phc:v1",
            r"iroha:privacy:zk-ams:registry-bootstrap:v1",
            r"iroha:privacy:zk-ams:registry-record:v1",
            r"iroha:privacy:zk-x509:certificate-policy-record:v1",
            r"iroha:privacy:zk-x509:crl-record:v1",
            r"iroha:privacy:zk-x509:trust-anchor-record:v1",
            r"iroha:zk-ace:pq-authorization:v1",
        ],
    },
    OtherDomains {
        usage: Use::Record,
        reason: "Private-settlement bundle, receipt, approval, audit and signing domains: each hashes or signs one settlement record",
        literals: &[
            r"iroha:nexus:private-settlement:abort-carrier-instruction:v1\0",
            r"iroha:nexus:private-settlement:abort-receipt:v1\0",
            r"iroha:nexus:private-settlement:approvals:v1\0",
            r"iroha:nexus:private-settlement:asset-binding:v1\0",
            r"iroha:nexus:private-settlement:audit-approval-acknowledgement-attestation:v1\0",
            r"iroha:nexus:private-settlement:audit-approval-acknowledgement:v1\0",
            r"iroha:nexus:private-settlement:audit-approval:v1\0",
            r"iroha:nexus:private-settlement:audit-capsule:v1\0",
            r"iroha:nexus:private-settlement:audit-plaintext:v1\0",
            r"iroha:nexus:private-settlement:audit-policy:v1\0",
            r"iroha:nexus:private-settlement:auditor-key:v1\0",
            r"iroha:nexus:private-settlement:auditor-view-attestation:v1\0",
            r"iroha:nexus:private-settlement:auditor-view:v1\0",
            r"iroha:nexus:private-settlement:authoritative-height-expiry:v1\0",
            r"iroha:nexus:private-settlement:authority:v1\0",
            r"iroha:nexus:private-settlement:availability-certificate:v1\0",
            r"iroha:nexus:private-settlement:availability-signature:v1\0",
            r"iroha:nexus:private-settlement:bundle-id:v1\0",
            r"iroha:nexus:private-settlement:carrier-instruction:v1\0",
            r"iroha:nexus:private-settlement:commit-bundle:v1\0",
            r"iroha:nexus:private-settlement:delta:v1\0",
            r"iroha:nexus:private-settlement:durable-availability:v1\0",
            r"iroha:nexus:private-settlement:fee-intent:v1\0",
            r"iroha:nexus:private-settlement:finalized-receipt:v1\0",
            r"iroha:nexus:private-settlement:global-receipt:v1\0",
            r"iroha:nexus:private-settlement:manifest:v1\0",
            r"iroha:nexus:private-settlement:output-view-key-authorization:v1\0",
            r"iroha:nexus:private-settlement:participant-phase-signature:v1\0",
            r"iroha:nexus:private-settlement:payer-input-authorization:v1\0",
            r"iroha:nexus:private-settlement:persisted-sidecar:v1\0",
            r"iroha:nexus:private-settlement:pool-governance:v1\0",
            r"iroha:nexus:private-settlement:prepare-lock-carrier-instruction:v1\0",
            r"iroha:nexus:private-settlement:prepared-bundle:v1\0",
            r"iroha:nexus:private-settlement:proof-binding:v1\0",
            r"iroha:nexus:private-settlement:proof:v1\0",
            r"iroha:nexus:private-settlement:reimbursement-terms:v1\0",
            r"iroha:nexus:private-settlement:sidecar:v1\0",
            r"iroha:nexus:private-settlement:statement:v1\0",
            r"iroha:nexus:private-settlement:verified-leg:v1\0",
        ],
    },
    OtherDomains {
        usage: Use::Record,
        reason: "SoraFS, SoraNet, Soracloud and Taikai custody, gateway, token, moderation, repair, order-book, reputation-journal and topology records, identifiers and signing preimages",
        literals: &[
            r"fastpq:v1:moderation",
            r"ipfs:bag/id@v1",
            r"iroha.soracloud.fhe.governed_material.v1",
            r"iroha.sorafs.auto-replication.test-provider.v1\0",
            r"iroha.sorafs.final-promotion-account.custody-control.v1\0",
            r"iroha.sorafs.final-promotion-account.custody-request.v1\0",
            r"iroha.sorafs.final-promotion-account.transaction-payload.v1\0",
            r"iroha.sorafs.final-promotion.authority-request.v1\0",
            r"iroha.sorafs.final-promotion.custody-control.v1\0",
            r"iroha.sorafs.final-promotion.operation.v1\0",
            r"iroha.sorafs.final-promotion.reservation.v1\0",
            r"iroha.sorafs.gateway.lease.v1\0",
            r"iroha.sorafs.gateway.request.v1\0",
            r"iroha.sorafs.gateway.token.v1\0",
            r"iroha.sorafs.moderation.ballot.commitment.v1",
            r"iroha.sorafs.provider-admission.council-policy.v1\0",
            r"iroha.sorafs.provider-admission.native-history.v1\0",
            r"iroha.sorafs.release-manifest.custody-control.v1\0",
            r"iroha.sorafs.stream-token.authority-request.v1\0",
            r"iroha.sorafs.stream-token.custody-control.v1\0",
            r"iroha.sorafs.stream-token.custody-request.v1\0",
            r"iroha.sorafs.stream-token.gateway-instruction.v1\0",
            r"iroha.sorafs.stream-token.gateway-mutation.v1\0",
            r"iroha.sorafs.stream-token.gateway-pending-readback.v1\0",
            r"iroha.sorafs.stream-token.gateway-policy-record.v1\0",
            r"iroha.sorafs.stream-token.gateway-policy.v1\0",
            r"iroha.sorafs.stream-token.gateway-write.v1\0",
            r"iroha.sorafs.stream-token.gateway-writes-start.v1\0",
            r"iroha.sorafs.stream-token.operation-record.v1\0",
            r"iroha.sorafs.stream-token.reservation.v1\0",
            r"iroha.sorafs.token-reputation.intent.v1\0",
            r"iroha.sorafs.token-reputation.recipe.v1\0",
            r"iroha.sorafs.token-reputation.source.v1\0",
            r"iroha.sorafs.topology.control.v1\0",
            r"iroha.sorafs.topology.history.v1\0",
            r"iroha.sorafs.topology.key-tombstone.v1\0",
            r"iroha.sorafs.topology.operation.v1\0",
            r"iroha.sorafs.topology.reservation.v1\0",
            r"iroha.sorafs.topology.transition.v1\0",
            r"iroha.sorafs.v1.provider_admission.initialize",
            r"iroha.sorafs.v1.publication.assert",
            r"iroha.soranet.privacy.collector-id.v1\0",
            r"iroha.soranet.vpn.account-hash.v1",
            r"iroha.soranet.vpn.helper-network-policy.v1",
            r"iroha.soranet.vpn.helper-ticket.signature.v1",
            r"iroha.soranet.vpn.signed-session-receipt-hash.v1",
            r"iroha.soranet.vpn.tariff-meter.v1",
            r"iroha.soranet.vpn.usage-voucher-hash.v1",
            r"iroha.soranet.vpn.usage-voucher.v1",
            r"iroha.taikai.anchor-receipt.v1",
            r"iroha:soracloud:runtime-provenance:v1\x00",
            r"iroha:sorafs:test-reserve-custody:v1",
            r"soracloud.inrou.placement-incarnation.v1",
            r"soracloud.service.config.snapshot.v1",
            r"soracloud.service.secret.snapshot.v1",
            r"soracloud:hf-shared-lease-pool-id:v1",
            r"soracloud:hf-source-id:v1",
            r"soracloud:local-read-receipt:v1",
            r"soracloud:ordered-mailbox-executor:v1",
            r"soracloud:ordered-mailbox-receipt:v1",
            r"soracloud:ordered-mailbox-result:v1",
            r"soracloud:service-lease-state:v1",
            r"soracloud:service-mailbox-message:v1",
            r"sorafs-appeal-cancel-asset-lock-v1",
            r"sorafs.citizen-bond.snapshot.v1",
            r"sorafs.moderation.appeal-deposit-state-key.v1",
            r"sorafs.moderation.appeal-intake.v1",
            r"sorafs.moderation.appeal-proof-token-state-key.v1",
            r"sorafs.moderation.case-state-key.v1",
            r"sorafs.moderation.challenge-state-key.v1",
            r"sorafs.moderation.juror-state-key.v1",
            r"sorafs.moderation.ledger-policy.v1",
            r"sorafs.moderation.local-runner.policy-digest.v1",
            r"sorafs.moderation.local.panel-roster-hash.v1",
            r"sorafs.moderation.pop-challenge.v1",
            r"sorafs.moderation.pop-nullifier-state-key.v1",
            r"sorafs.moderation.pop-presentation-binding.v1",
            r"sorafs.moderation.pop-proof-payload.v1",
            r"sorafs.moderation.pop-snapshot.v1",
            r"sorafs.moderation.sortition-record.v1",
            r"sorafs.moderation.sortition-score.v1",
            r"sorafs.moderation.sortition-seed.v1",
            r"sorafs.orderbook.admission-policy.v1",
            r"sorafs.orderbook.order-escrow-id.v1",
            r"sorafs.orderbook.owner-nonce-state.v1",
            r"sorafs.orderbook.settlement-escrow-id.v1",
            r"sorafs.pi.archive.retention.v1.0",
            r"sorafs.pop.credential-payload-commitment.v1",
            r"sorafs.pop.issuer-policy.v1",
            r"sorafs.pop.registry-audit.v1",
            r"sorafs.pop.registry-payload.v1",
            r"sorafs.pop.revocation-nonce-commitment.v1",
            r"sorafs.proof-outcome.signer-policy.v1\0",
            r"sorafs.repair.action-digest.v1",
            r"sorafs.repair.ledger-appeal-id.v1",
            r"sorafs.repair.ledger-idempotency-key.v1",
            r"sorafs.repair.ledger-task-id.v1",
            r"sorafs.repair.ticket-state-key.v1",
            r"sorafs.reputation.finalized-archive.retention-request.v1",
            r"sorafs.reputation.journal.authority-policy.v1",
            r"sorafs.reputation.journal.event-id.v1",
            r"sorafs.reputation.journal.source.por.v1",
            r"sorafs.reputation.journal.source.provider-dispute.v1",
            r"sorafs.reputation.journal.source.stream-token.v1",
            r"sorafs.reputation.stream-token.exact-header.v1",
            r"sorafs.reputation.stream-token.gateway-id.v1",
            r"sorafs.reputation.stream-token.request-context.v1",
            r"sorafs.reputation.stream-token.request-nonce.v1",
            r"sorafs.reputation.stream-token.validation-id.v1",
            r"sorafs.reserve.authority-policy.v1",
            r"sorafs.rp.archive.retention.v1.0",
            r"sorafs:auto-replication-order:v1",
            r"sorafs:moderation:committee-aggregate:v1",
            r"sorafs:moderation:model-behaviour:v1",
            r"sorafs:moderation:provenance-entry:v1",
            r"sorafs:moderation:repro-body:v1",
            r"sorafs:moderation:signed-result:v1",
            r"sorafs:moderation:trust-policy:v1",
            r"soranet-vpn-address-slot-v1",
            r"soranet-vpn-lease-id-v1",
            r"soranet-vpn-operator-quote-v1",
            r"soranet-vpn-relay-session-receipt-v1",
            r"soranet-vpn-session-id-v1",
            r"soranet.ticket.body.blinded_cid.v1",
            r"soranet.ticket.body.issuer_id.v1",
            r"soranet.ticket.body.max_uses.v1",
            r"soranet.ticket.body.metadata.v1",
            r"soranet.ticket.body.node.v1",
            r"soranet.ticket.body.policy_flags.v1",
            r"soranet.ticket.body.salt_epoch.v1",
            r"soranet.ticket.body.scope.v1",
            r"soranet.ticket.body.valid_after.v1",
            r"soranet.ticket.body.valid_until.v1",
        ],
    },
    OtherDomains {
        usage: Use::Test,
        reason: "Test inputs, fixtures and test-network evidence compiled for tests or behind a test-only feature; never a consensus input",
        literals: &[
            r"fixtures/privacy/exact12_typed_fixture_bundle_v1.norito.b64",
            r"fixtures/privacy/exact12_v1.tsv",
            r"iroha-demo-kaigi-chain-signal/v1",
            r"iroha.test-network.parliament-beacon.dealers.v1\0",
            r"iroha.test-network.parliament-beacon.session.v1\0",
            r"iroha.test-network.parliament-beacon.successor-session.v1\0",
            r"iroha.test-network.parliament-tle.dealers.v1\0",
            r"iroha.test-network.parliament-tle.event.v1\0",
            r"iroha.test-network.parliament-tle.session.v1\0",
            r"iroha.test.concrete_instruction.v1",
            r"iroha:contract-subject:hash-to-point:v1:",
            r"iroha:test-network:private-settlement:staged-lock-evidence:v1\0",
            r"iroha:test:cutover",
            r"iroha:test:genesis-a",
            r"iroha:test:genesis-b",
            r"iroha:test:hshake",
            r"kaigi-authorization-v1-tests",
            r"lineage-v5",
            r"test:cell:v1",
            r"test:old-layout:v1",
            r"test:other-cell:v1",
            r"test:required:v1",
            r"torii-proxy-v1-roundtrip",
        ],
    },
];
