//! Genuine ordinary Guard key generation and original proofs for release qualification.
//!
//! This module is a child of `generation`, gated to tests/the real proof harness.
//! Generated bytes are data. They install no Native wallet, attest no phone and grant
//! no signed release or monetary authority.

use super::super::{
    DigestV1,
    ordinary_guard_circuit::{
        ORDINARY_GUARD_PUBLIC_INSTANCE_COUNT_V1, OrdinaryGuardWitnessV1,
        build_ordinary_app_guard_ep_v1, build_ordinary_app_guard_eq_v1,
    },
    ordinary_issuer_config::OrdinaryIssuerTableV1,
};
use super::*;

/// Canonical role material stays owned through the complete generated pair lifetime.
pub(crate) struct GeneratedOrdinaryGuardEqV1 {
    pub(crate) _parameters: Arc<[u8]>,
    pub(crate) _proving_key: Arc<[u8]>,
    pub(crate) _verifying_key: Arc<[u8]>,
    pub(crate) _base_params: BaseCircuitParams,
    pub(crate) protocol: PlonkProtocol<EqAffine>,
    pub(crate) protocol_digest: [u8; 32],
    pub(crate) instances: Vec<Fp>,
    pub(crate) proof: Vec<u8>,
    pub(crate) history: KagemushaEqAccumulatorV1,
}

/// Retain the same Ep role originals alongside its authenticated proof and history.
pub(crate) struct GeneratedOrdinaryGuardEpV1 {
    pub(crate) _parameters: Arc<[u8]>,
    pub(crate) _proving_key: Arc<[u8]>,
    pub(crate) _verifying_key: Arc<[u8]>,
    pub(crate) _base_params: BaseCircuitParams,
    pub(crate) protocol: PlonkProtocol<EpAffine>,
    pub(crate) protocol_digest: [u8; 32],
    pub(crate) instances: Vec<Fq>,
    pub(crate) proof: Vec<u8>,
    pub(crate) history: KagemushaEpAccumulatorV1,
}

pub(crate) struct GeneratedOrdinaryGuardPairV1 {
    pub(crate) eq: GeneratedOrdinaryGuardEqV1,
    pub(crate) ep: GeneratedOrdinaryGuardEpV1,
}

/// Execute the complete production Guard relation, using an explicitly selected
/// issuer table. Qualification fixtures may supply public mathematical originals;
/// they cannot manufacture an authenticated release or an installed financial owner.
/// Shipping release construction must derive this table from its independently
/// authenticated release, as the production prover does.
pub(crate) fn generate_ordinary_guard_pair_v1(
    witness: OrdinaryGuardWitnessV1<'_>,
    provider_policy_root: DigestV1,
    issuer_table: &OrdinaryIssuerTableV1,
    recovery_seed: &KagemushaRecoverySeedV1,
) -> Result<GeneratedOrdinaryGuardPairV1, KagemushaArtifactGenerationErrorV1> {
    let eq_parameters = canonical_kagemusha_eq_parameters_v1();
    let ep_parameters = canonical_kagemusha_ep_parameters_v1();
    let eq_circuit = build_ordinary_app_guard_eq_v1(
        &eq_parameters,
        &witness,
        provider_policy_root,
        issuer_table,
    )
    .map_err(KagemushaArtifactGenerationErrorV1::CircuitBuild)?;
    let eq_base_params = eq_circuit.params().base;
    let eq_instances = eq_circuit.builder.assigned_instances[0]
        .iter()
        .map(|value| *value.value())
        .collect::<Vec<_>>();
    require_width(&eq_instances)?;
    let eq_pk = keygen_pk_with_helper_resource_preflight_consuming_v1(
        &eq_parameters,
        eq_circuit,
        KagemushaPastaParityV1::Eq,
        "ordinary Guard",
        "ordinary Guard proving key",
    )?;
    let eq_protocol = compile(
        &eq_parameters,
        eq_pk.get_vk(),
        snark_verifier::system::halo2::Config::ipa()
            .with_num_instance(vec![ORDINARY_GUARD_PUBLIC_INSTANCE_COUNT_V1]),
    );
    let eq_protocol_digest =
        native_parent_protocol_digest_v1(&eq_protocol, KagemushaPastaParityV1::Eq)
            .map_err(KagemushaArtifactGenerationErrorV1::CircuitBuild)?;
    let eq_circuit = build_ordinary_app_guard_eq_v1(
        &eq_parameters,
        &witness,
        provider_policy_root,
        issuer_table,
    )
    .map_err(KagemushaArtifactGenerationErrorV1::CircuitBuild)?;
    if !same_base_params(&eq_circuit.params().base, &eq_base_params)
        || eq_circuit.builder.assigned_instances[0]
            .iter()
            .map(|value| *value.value())
            .collect::<Vec<_>>()
            != eq_instances
    {
        return Err(KagemushaArtifactGenerationErrorV1::CircuitBuild(
            "ordinary Guard Eq key/proof relation differs".into(),
        ));
    }
    let eq_proof = create_eq_proof_with_key_v1(
        &eq_parameters,
        &eq_pk,
        eq_circuit,
        &eq_instances,
        KagemushaProofRecoveryPhaseV1::OrdinaryAppGuard,
        recovery_seed,
    )?;
    let eq_current = KagemushaEqAccumulatorV1::from_native(
        &verify_eq_succinct_protocol(&eq_parameters, &eq_protocol, &eq_proof, &eq_instances)
            .map_err(KagemushaArtifactGenerationErrorV1::CircuitBuild)?,
    )
    .map_err(|error| KagemushaArtifactGenerationErrorV1::CircuitBuild(error.to_string()))?;
    decide_kagemusha_eq_accumulator_v1(&eq_parameters, &eq_current)
        .map_err(|error| KagemushaArtifactGenerationErrorV1::CircuitBuild(error.to_string()))?;
    let (eq_parameter_bytes, eq_pk_bytes, eq_vk_bytes) = build_generated_helper_parity(
        KagemushaPastaParityV1::Eq,
        "ordinary Guard",
        &eq_parameters,
        eq_pk,
    )?;

    halo2_proofs::release_allocator_slack();
    let ep_circuit = build_ordinary_app_guard_ep_v1(
        &ep_parameters,
        &witness,
        provider_policy_root,
        issuer_table,
    )
    .map_err(KagemushaArtifactGenerationErrorV1::CircuitBuild)?;
    let ep_base_params = ep_circuit.params().base;
    let ep_instances = ep_circuit.builder.assigned_instances[0]
        .iter()
        .map(|value| *value.value())
        .collect::<Vec<_>>();
    require_width(&ep_instances)?;
    let ep_pk = keygen_pk_with_helper_resource_preflight_consuming_v1(
        &ep_parameters,
        ep_circuit,
        KagemushaPastaParityV1::Ep,
        "ordinary Guard",
        "ordinary Guard proving key",
    )?;
    let ep_protocol = compile(
        &ep_parameters,
        ep_pk.get_vk(),
        snark_verifier::system::halo2::Config::ipa()
            .with_num_instance(vec![ORDINARY_GUARD_PUBLIC_INSTANCE_COUNT_V1]),
    );
    let ep_protocol_digest =
        native_parent_protocol_digest_v1(&ep_protocol, KagemushaPastaParityV1::Ep)
            .map_err(KagemushaArtifactGenerationErrorV1::CircuitBuild)?;
    let ep_circuit = build_ordinary_app_guard_ep_v1(
        &ep_parameters,
        &witness,
        provider_policy_root,
        issuer_table,
    )
    .map_err(KagemushaArtifactGenerationErrorV1::CircuitBuild)?;
    if !same_base_params(&ep_circuit.params().base, &ep_base_params)
        || ep_circuit.builder.assigned_instances[0]
            .iter()
            .map(|value| *value.value())
            .collect::<Vec<_>>()
            != ep_instances
    {
        return Err(KagemushaArtifactGenerationErrorV1::CircuitBuild(
            "ordinary Guard Ep key/proof relation differs".into(),
        ));
    }
    let ep_proof = create_ep_proof_with_key_v1(
        &ep_parameters,
        &ep_pk,
        ep_circuit,
        &ep_instances,
        KagemushaProofRecoveryPhaseV1::OrdinaryAppGuard,
        recovery_seed,
    )?;
    let ep_current = KagemushaEpAccumulatorV1::from_native(
        &verify_ep_succinct_protocol(&ep_parameters, &ep_protocol, &ep_proof, &ep_instances)
            .map_err(KagemushaArtifactGenerationErrorV1::CircuitBuild)?,
    )
    .map_err(|error| KagemushaArtifactGenerationErrorV1::CircuitBuild(error.to_string()))?;
    decide_kagemusha_ep_accumulator_v1(&ep_parameters, &ep_current)
        .map_err(|error| KagemushaArtifactGenerationErrorV1::CircuitBuild(error.to_string()))?;
    let (ep_parameter_bytes, ep_pk_bytes, ep_vk_bytes) = build_generated_helper_parity(
        KagemushaPastaParityV1::Ep,
        "ordinary Guard",
        &ep_parameters,
        ep_pk,
    )?;
    let eq_history = initial_kagemusha_eq_accumulator_v1(&eq_parameters)
        .map_err(|error| KagemushaArtifactGenerationErrorV1::CircuitBuild(error.to_string()))?;
    let ep_history = initial_kagemusha_ep_accumulator_v1(&ep_parameters)
        .map_err(|error| KagemushaArtifactGenerationErrorV1::CircuitBuild(error.to_string()))?;
    Ok(GeneratedOrdinaryGuardPairV1 {
        eq: GeneratedOrdinaryGuardEqV1 {
            _parameters: eq_parameter_bytes,
            _proving_key: eq_pk_bytes,
            _verifying_key: eq_vk_bytes,
            _base_params: eq_base_params,
            protocol: eq_protocol,
            protocol_digest: eq_protocol_digest,
            instances: eq_instances,
            proof: eq_proof,
            history: eq_history,
        },
        ep: GeneratedOrdinaryGuardEpV1 {
            _parameters: ep_parameter_bytes,
            _proving_key: ep_pk_bytes,
            _verifying_key: ep_vk_bytes,
            _base_params: ep_base_params,
            protocol: ep_protocol,
            protocol_digest: ep_protocol_digest,
            instances: ep_instances,
            proof: ep_proof,
            history: ep_history,
        },
    })
}

fn require_width<F>(instances: &[F]) -> Result<(), KagemushaArtifactGenerationErrorV1> {
    if instances.len() != ORDINARY_GUARD_PUBLIC_INSTANCE_COUNT_V1 {
        return Err(KagemushaArtifactGenerationErrorV1::CircuitBuild(
            "ordinary Guard public original width differs".into(),
        ));
    }
    Ok(())
}
