crate::sumeragi::v2_lifecycle_coordinator::source_contract_test!(recovered_wal_sign_open_is_opaque_precommit_checked_and_runner_inert);
crate::sumeragi::v2_lifecycle_coordinator::source_contract_test!(durable_validate_async_handoff_surface_is_move_only_scheduler_free_and_inert);
crate::sumeragi::v2_lifecycle_coordinator::source_contract_test!(durable_validate_wait_dispatch_is_move_only_single_entry_and_unwired);
crate::sumeragi::v2_lifecycle_coordinator::source_contract_test!(durable_validate_volatile_completion_is_atomic_move_only_and_unwired);
crate::sumeragi::v2_lifecycle_coordinator::source_contract_test!(certified_fetch_dequeue_commit_requires_the_durable_token);
crate::sumeragi::v2_lifecycle_coordinator::source_contract_test!(recovered_decision_apply_scheduler_attestation_stays_closed_and_io_bounded);
crate::sumeragi::v2_lifecycle_coordinator::source_contract_test!(recovered_decision_apply_terminal_settlement_is_exact_and_post_fsync_infallible);
crate::sumeragi::v2_lifecycle_coordinator::source_contract_test!(recovered_next_wal_vote_completion_stays_closed_and_attests_its_ready_pair);
