[package]
name = "iroha_kagami"     # Translates to teacher, the exemplar, the looking glass.
autobins = false

edition.workspace = true
version.workspace = true
authors.workspace = true

description = "A tool used to generate cryptographic keys, docs, the schema and genesis block."

license.workspace = true

[lints]
workspace = true

[dependencies]
norito = { workspace = true, default-features = false, features = ["node-codec"] }
iroha_executor_data_model.workspace = true
iroha_data_model = { workspace = true, default-features = false, features = ["application-model", "privacy-exact12-conformance"] }
iroha_crypto = { workspace = true, default-features = false, features = ["node-crypto"] }
iroha_schema_gen.workspace = true
iroha_primitives.workspace = true
iroha_genesis.workspace = true
iroha_test_samples.workspace = true
iroha_version.workspace = true
iroha_schema.workspace = true
iroha_core = { workspace = true, features = ["node", "iroha-core-tests"], default-features = false }
iroha_config.workspace = true

iroha_swarm = { path = "../iroha_swarm" }

clap = { workspace = true, features = ["derive"] }
clap-markdown = "0.1.5"
owo-colors = { workspace = true, features = ["supports-colors"] }
color-eyre.workspace = true
derive_more.workspace = true
toml = { version = "0.9.8" }

tiny-keccak.workspace = true
blake3.workspace = true
hex = { workspace = true }
base64.workspace = true
rand = { workspace = true }
tempfile = { workspace = true }
zeroize = { version = "1.8.2", default-features = false, features = ["alloc", "std"] }
inquire = "0.9.1"

[target.'cfg(unix)'.dependencies]
libc = "0.2.177"
rustix = { version = "1.1.4", features = ["fs", "process"] }

[features]
dev-tools = []
gost = ["iroha_crypto/gost"]
sm = ["iroha_crypto/sm"]

[[bin]]
name = "kagami"
path = "src/main.rs"

[[bin]]
name = "iroha_authenticated_tool_controller"
path = "src/bin/iroha_authenticated_tool_controller.rs"
required-features = ["dev-tools"]

[[example]]
name = "codec_samples"
path = "samples/codec/generate.rs"
