//! Immutable compiler-captured identities for this source owner’s existing codecs.

#[test]
fn captured_codec_schema_identities() {
    crate::captured_schema_tests::assert_bidirectional::<super::FeeSponsorProgramId>(
        "iroha_data_model::nexus::fee_sponsor_program::FeeSponsorProgramId",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FeeSponsorProgramRevisionKey>(
        "iroha_data_model::nexus::fee_sponsor_program::FeeSponsorProgramRevisionKey",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FeeSponsorProgramLifecycle>(
        "iroha_data_model::nexus::fee_sponsor_program::FeeSponsorProgramLifecycle",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FeeSponsorEligibility>(
        "iroha_data_model::nexus::fee_sponsor_program::FeeSponsorEligibility",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FeeSponsorRuleEffect>(
        "iroha_data_model::nexus::fee_sponsor_program::FeeSponsorRuleEffect",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FeeSponsorNativeInstructionSelector>(
        "iroha_data_model::nexus::fee_sponsor_program::FeeSponsorNativeInstructionSelector",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FeeSponsorMultisigOperation>(
        "iroha_data_model::nexus::fee_sponsor_program::FeeSponsorMultisigOperation",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FeeSponsorMultisigSelector>(
        "iroha_data_model::nexus::fee_sponsor_program::FeeSponsorMultisigSelector",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FeeSponsorContractSelector>(
        "iroha_data_model::nexus::fee_sponsor_program::FeeSponsorContractSelector",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FeeSponsorIvmSelector>(
        "iroha_data_model::nexus::fee_sponsor_program::FeeSponsorIvmSelector",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FeeSponsorRuleSelector>(
        "iroha_data_model::nexus::fee_sponsor_program::FeeSponsorRuleSelector",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FeeSponsorRule>(
        "iroha_data_model::nexus::fee_sponsor_program::FeeSponsorRule",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FeeSponsorAssetBudget>(
        "iroha_data_model::nexus::fee_sponsor_program::FeeSponsorAssetBudget",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FeeSponsorProgramRevision>(
        "iroha_data_model::nexus::fee_sponsor_program::FeeSponsorProgramRevision",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FeeSponsorProgramActivation>(
        "iroha_data_model::nexus::fee_sponsor_program::FeeSponsorProgramActivation",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FeeSponsorProgram>(
        "iroha_data_model::nexus::fee_sponsor_program::FeeSponsorProgram",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FeeSponsorEnrollmentKey>(
        "iroha_data_model::nexus::fee_sponsor_program::FeeSponsorEnrollmentKey",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FeeSponsorEnrollment>(
        "iroha_data_model::nexus::fee_sponsor_program::FeeSponsorEnrollment",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FeeSponsorVaultKey>(
        "iroha_data_model::nexus::fee_sponsor_program::FeeSponsorVaultKey",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FeeSponsorVault>(
        "iroha_data_model::nexus::fee_sponsor_program::FeeSponsorVault",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FeeSponsorBlockBudgetWindow>(
        "iroha_data_model::nexus::fee_sponsor_program::FeeSponsorBlockBudgetWindow",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FeeSponsorProgramEpochBudgetWindow>(
        "iroha_data_model::nexus::fee_sponsor_program::FeeSponsorProgramEpochBudgetWindow",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::FeeSponsorBeneficiaryEpochBudgetWindow,
    >("iroha_data_model::nexus::fee_sponsor_program::FeeSponsorBeneficiaryEpochBudgetWindow");
    crate::captured_schema_tests::assert_bidirectional::<super::FeeSponsorBudgetWindow>(
        "iroha_data_model::nexus::fee_sponsor_program::FeeSponsorBudgetWindow",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FeeSponsorBudgetCounterKey>(
        "iroha_data_model::nexus::fee_sponsor_program::FeeSponsorBudgetCounterKey",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FeeSponsorBudgetCounter>(
        "iroha_data_model::nexus::fee_sponsor_program::FeeSponsorBudgetCounter",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FeeDebitSource>(
        "iroha_data_model::nexus::fee_sponsor_program::FeeDebitSource",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FeeRejectionCode>(
        "iroha_data_model::nexus::fee_sponsor_program::FeeRejectionCode",
    );
}
