//! Exact `GET /v1/sumeragi/lanes` JSON and canonical framed Norito vectors for SDK parity.
//!
//! Every row is one complete response body: the ordered lane list the node serves
//! (`specs/sumeragi_lanes.md` §8). SDKs parse the JSON column; the Norito column is the
//! `application/x-norito` body of the same response.
use iroha_crypto::{Algorithm, Hash, KeyPair, bls_normal_pop_prove};
use iroha_data_model::{
    parameter::system::SumeragiParameters,
    sumeragi::{
        BeaconHorizonStatusV1, PROTOCOL_VERSION, SumeragiFootprint, SumeragiHaltReason,
        SumeragiStatus,
    },
    sumeragi_lanes::{
        SumeragiLaneFrontier, SumeragiLaneMember, SumeragiLaneRecord, SumeragiLaneStatus,
    },
};
use iroha_model_base::{
    peer::PeerId,
    topology::{DataSpaceId, LaneId},
};

/// Header line of `fixtures/sumeragi/native_lanes_v1.tsv`.
pub const HEADER: &str =
    "# Generated by kotlin-fixture-gen native-sumeragi-lanes-v1; name\tjson\tcanonical_norito_hex";

/// Print the fixture file.
pub fn emit() {
    println!("{HEADER}");
    for line in rows() {
        println!("{line}");
    }
}

/// The fixture rows (without the header), each checked to round-trip in Rust.
pub fn rows() -> Vec<String> {
    let committee = committee();
    let running = SumeragiLaneStatus {
        record: SumeragiLaneRecord {
            lane: LaneId::new(1),
            dataspace: DataSpaceId::new(0),
            incarnation: [0x11; 32],
            params: SumeragiParameters::default(),
            committee: committee.clone(),
            created_at: 40,
            active_from: 42,
            closing: None,
            anchor_freshness: 16,
            merged: SumeragiLaneFrontier {
                height: 7,
                block_hash: [0x22; 32],
                result: [0x33; 32],
            },
            merged_at: 57,
            rescued: 0,
        },
        instance: Some(instance(&committee, None)),
    };
    let pending = SumeragiLaneStatus {
        record: SumeragiLaneRecord {
            lane: LaneId::new(16),
            dataspace: DataSpaceId::new(u64::MAX),
            incarnation: [0x44; 32],
            params: SumeragiParameters::default(),
            committee: committee.clone(),
            created_at: 60,
            active_from: 62,
            closing: None,
            anchor_freshness: 16,
            merged: SumeragiLaneFrontier::default(),
            merged_at: 62,
            rescued: u64::MAX,
        },
        instance: None,
    };
    let closing = SumeragiLaneStatus {
        record: SumeragiLaneRecord {
            lane: LaneId::new(u32::MAX),
            dataspace: DataSpaceId::new(7),
            incarnation: [0xFE; 32],
            params: SumeragiParameters::default(),
            committee: committee.clone(),
            created_at: 3,
            active_from: 5,
            closing: Some(u64::MAX),
            anchor_freshness: u64::MAX,
            merged: SumeragiLaneFrontier {
                height: u64::MAX,
                block_hash: [0xAB; 32],
                result: [0xCD; 32],
            },
            merged_at: u64::MAX,
            rescued: 9,
        },
        instance: Some(instance(
            &committee,
            Some(SumeragiHaltReason::PublicationRecoveryRequired(u64::MAX)),
        )),
    };
    vec![
        row("empty", &[]),
        row("running_lane", std::slice::from_ref(&running)),
        row("mixed_lanes", &[running, pending, closing]),
    ]
}

/// Four pinned BLS-normal members in canonical (ascending peer) order, each with its actual
/// proof of possession.
fn committee() -> Vec<SumeragiLaneMember> {
    let mut members = (41_u8..45)
        .map(|seed| {
            let pair = KeyPair::from_seed(vec![seed; 32], Algorithm::BlsNormal);
            SumeragiLaneMember {
                peer: PeerId::new(pair.public_key().clone()),
                pop: bls_normal_pop_prove(pair.private_key()).expect("BLS-normal lane member PoP"),
            }
        })
        .collect::<Vec<_>>();
    members.sort();
    members
}

/// A lane instance status whose leader, proxy tail and signer are committee members.
fn instance(
    committee: &[SumeragiLaneMember],
    halted: Option<SumeragiHaltReason>,
) -> SumeragiStatus {
    let key = |index: usize| Some(committee[index].peer.public_key().clone());
    SumeragiStatus {
        protocol_version: PROTOCOL_VERSION,
        config_fingerprint: Hash::new(b"native-lanes-sdk-lane-consensus-config"),
        beacon_horizon: Some(BeaconHorizonStatusV1 {
            epoch_length_blocks: 0,
            next_required_pulse_height: None,
            active_session_id: None,
            session_covers_next_pulse: false,
            local_provider_ready: false,
        }),
        instance: [0x5A; 32],
        height: 8,
        view: 1,
        stage: 1,
        leader: key(0),
        proxy_tail: key(3),
        high_qc_view: Some(0),
        level: 0,
        start_level: 0,
        t_retx_ms: 250,
        committed_height: 7,
        applied_height: 7,
        awaiting: false,
        signer: key(1),
        unanchored: false,
        abstaining: false,
        halted,
        footprint: SumeragiFootprint {
            votes: 3,
            timeouts: 0,
            blocks: 1,
            exec_entries: 1,
            wants: 0,
            pending_apply: 0,
            sync_entries: 0,
            sync_bytes: 0,
            peers: 4,
            recent_headers: 7,
            configs: 2,
            cert_cache: 1,
            evidence_keys: 0,
            probe: u64::MAX,
        },
    }
}

/// Render one fixture row: the exact response body is the owned `Vec` the handler serves.
fn row(name: &str, lanes: &[SumeragiLaneStatus]) -> String {
    let lanes = lanes.to_vec();
    let json = norito::json::to_json(&lanes).expect("native lanes JSON");
    let wire = norito::encode_canonical(&lanes).expect("native lanes canonical frame");
    let decoded: Vec<SumeragiLaneStatus> =
        norito::decode_canonical(&wire).expect("Rust exact frame roundtrip");
    assert_eq!(decoded, lanes);
    let decoded_json: Vec<SumeragiLaneStatus> =
        norito::json::from_str(&json).expect("Rust JSON roundtrip");
    assert_eq!(decoded_json, lanes);
    format!("{name}\t{json}\t{}", hex::encode(wire))
}

#[cfg(test)]
mod tests {
    use super::{HEADER, rows};

    const COMMITTED: &str = include_str!("../../../fixtures/sumeragi/native_lanes_v1.tsv");

    #[test]
    fn committed_lane_fixture_matches_current_rust_records() {
        let mut lines = COMMITTED.lines();
        assert_eq!(lines.next(), Some(HEADER), "fixture header changed");
        let committed = lines.map(str::to_owned).collect::<Vec<_>>();
        assert_eq!(
            committed,
            rows(),
            "fixtures/sumeragi/native_lanes_v1.tsv drifted from the Rust lane status DTO; \
             regenerate it with `cargo run -p kotlin-fixture-gen --features dev-tools -- \
             native-sumeragi-lanes-v1 > fixtures/sumeragi/native_lanes_v1.tsv`"
        );
    }
}
