//! Exact native status JSON and canonical framed Norito vectors for SDK parity.
use iroha_crypto::{Algorithm, Hash, KeyPair};
use iroha_data_model::sumeragi::{
    BeaconHorizonStatusV1, PROTOCOL_VERSION, SumeragiFootprint, SumeragiHaltReason, SumeragiStatus,
};

pub(super) fn emit() {
    let key = KeyPair::from_seed(vec![23; 32], Algorithm::BlsNormal)
        .public_key()
        .clone();
    let mut status = SumeragiStatus {
        protocol_version: PROTOCOL_VERSION,
        config_fingerprint: Hash::new(b"native-status-sdk-consensus-config"),
        beacon_horizon: Some(BeaconHorizonStatusV1 {
            epoch_length_blocks: 10,
            next_required_pulse_height: Some(19),
            active_session_id: Some([0xAB; 32]),
            session_covers_next_pulse: true,
            local_provider_ready: true,
        }),
        instance: [0xCD; 32],
        height: 15,
        view: u64::MAX,
        stage: 2,
        leader: Some(key.clone()),
        proxy_tail: Some(key.clone()),
        high_qc_view: Some(u64::MAX),
        level: u32::MAX,
        start_level: 1,
        t_retx_ms: u64::MAX,
        committed_height: 14,
        applied_height: 13,
        awaiting: false,
        signer: Some(key),
        unanchored: false,
        abstaining: false,
        halted: None,
        footprint: SumeragiFootprint {
            votes: u64::MAX,
            timeouts: 1,
            blocks: 2,
            exec_entries: 3,
            wants: 4,
            pending_apply: 5,
            sync_entries: 6,
            sync_bytes: 7,
            peers: 8,
            recent_headers: 9,
            configs: 10,
            cert_cache: 11,
            evidence_keys: 12,
            probe: 13,
        },
    };
    println!(
        "# Generated by kotlin-fixture-gen native-sumeragi-status-v1; name\tjson\tcanonical_norito_hex"
    );
    row("validator", &status);
    status.beacon_horizon = None;
    status.leader = None;
    status.proxy_tail = None;
    status.high_qc_view = None;
    status.signer = None;
    status.awaiting = true;
    status.abstaining = true;
    row("observer", &status);
    for (name, reason) in [
        (
            "safety_record_corrupt",
            SumeragiHaltReason::SafetyRecordCorrupt,
        ),
        (
            "safety_record_inconsistent",
            SumeragiHaltReason::SafetyRecordInconsistent,
        ),
        (
            "safety_violation",
            SumeragiHaltReason::SafetyViolation(u64::MAX),
        ),
        (
            "apply_diverged",
            SumeragiHaltReason::ApplyDiverged(u64::MAX),
        ),
        (
            "publication_recovery_required",
            SumeragiHaltReason::PublicationRecoveryRequired(u64::MAX),
        ),
        ("driver_anomaly", SumeragiHaltReason::DriverAnomaly),
    ] {
        status.halted = Some(reason);
        row(name, &status);
    }
}

fn row(name: &str, status: &SumeragiStatus) {
    let json = norito::json::to_json(status).expect("native status JSON");
    let wire = norito::encode_canonical(status).expect("native status canonical frame");
    let decoded: SumeragiStatus =
        norito::decode_canonical(&wire).expect("Rust exact frame roundtrip");
    assert_eq!(&decoded, status);
    let decoded_json: SumeragiStatus = norito::json::from_str(&json).expect("Rust JSON roundtrip");
    assert_eq!(&decoded_json, status);
    println!("{name}\t{json}\t{}", hex::encode(wire));
}
