//! Immutable compiler-captured identities for this source owner’s existing codecs.

#[test]
fn captured_codec_schema_identities() {
    crate::captured_schema_tests::assert_bidirectional::<super::OrderbookAdmissionPolicyV1>(
        "iroha_data_model::sorafs::orderbook::OrderbookAdmissionPolicyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OrderbookAdmissionPolicyRecord>(
        "iroha_data_model::sorafs::orderbook::OrderbookAdmissionPolicyRecord",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OrderbookOrderStatusV1>(
        "iroha_data_model::sorafs::orderbook::OrderbookOrderStatusV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OrderbookBidEscrowBindingV1>(
        "iroha_data_model::sorafs::orderbook::OrderbookBidEscrowBindingV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OrderbookOrderRecord>(
        "iroha_data_model::sorafs::orderbook::OrderbookOrderRecord",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OrderbookCancellationRecord>(
        "iroha_data_model::sorafs::orderbook::OrderbookCancellationRecord",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OrderbookOwnerNonceRecord>(
        "iroha_data_model::sorafs::orderbook::OrderbookOwnerNonceRecord",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OrderbookSettlementReceiptRecord>(
        "iroha_data_model::sorafs::orderbook::OrderbookSettlementReceiptRecord",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OrderbookTradeRecord>(
        "iroha_data_model::sorafs::orderbook::OrderbookTradeRecord",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OrderbookSettlementChannelStatusV1>(
        "iroha_data_model::sorafs::orderbook::OrderbookSettlementChannelStatusV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OrderbookSettlementChannelRecord>(
        "iroha_data_model::sorafs::orderbook::OrderbookSettlementChannelRecord",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OrderbookSettlementRangeRecord>(
        "iroha_data_model::sorafs::orderbook::OrderbookSettlementRangeRecord",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OrderbookSettlementIndexRecord>(
        "iroha_data_model::sorafs::orderbook::OrderbookSettlementIndexRecord",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OrderbookLedgerStatusV1>(
        "iroha_data_model::sorafs::orderbook::OrderbookLedgerStatusV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OrderbookFinalizedCursorV1>(
        "iroha_data_model::sorafs::orderbook::OrderbookFinalizedCursorV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OrderbookOrderPageV1>(
        "iroha_data_model::sorafs::orderbook::OrderbookOrderPageV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OrderbookSettlementReceiptPageV1>(
        "iroha_data_model::sorafs::orderbook::OrderbookSettlementReceiptPageV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OrderbookTradePageV1>(
        "iroha_data_model::sorafs::orderbook::OrderbookTradePageV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OrderbookSettlementChannelPageV1>(
        "iroha_data_model::sorafs::orderbook::OrderbookSettlementChannelPageV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OrderbookFinalizedEventCursorV1>(
        "iroha_data_model::sorafs::orderbook::OrderbookFinalizedEventCursorV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OrderbookFinalizedEventV1>(
        "iroha_data_model::sorafs::orderbook::OrderbookFinalizedEventV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OrderbookFinalizedEventPageV1>(
        "iroha_data_model::sorafs::orderbook::OrderbookFinalizedEventPageV1",
    );
}
