//! Immutable compiler-captured identities for this source owner’s existing codecs.

const CASES: &[crate::captured_schema_tests::Case] = &[
    crate::captured_schema_tests::Case::bidirectional::<super::OrderbookAdmissionPolicyV1>(
        "iroha_data_model::sorafs::orderbook::OrderbookAdmissionPolicyV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OrderbookAdmissionPolicyRecord>(
        "iroha_data_model::sorafs::orderbook::OrderbookAdmissionPolicyRecord",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OrderbookOrderStatusV1>(
        "iroha_data_model::sorafs::orderbook::OrderbookOrderStatusV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OrderbookBidEscrowBindingV1>(
        "iroha_data_model::sorafs::orderbook::OrderbookBidEscrowBindingV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OrderbookOrderRecord>(
        "iroha_data_model::sorafs::orderbook::OrderbookOrderRecord",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OrderbookCancellationRecord>(
        "iroha_data_model::sorafs::orderbook::OrderbookCancellationRecord",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OrderbookOwnerNonceRecord>(
        "iroha_data_model::sorafs::orderbook::OrderbookOwnerNonceRecord",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OrderbookSettlementReceiptRecord>(
        "iroha_data_model::sorafs::orderbook::OrderbookSettlementReceiptRecord",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OrderbookTradeRecord>(
        "iroha_data_model::sorafs::orderbook::OrderbookTradeRecord",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OrderbookSettlementChannelStatusV1>(
        "iroha_data_model::sorafs::orderbook::OrderbookSettlementChannelStatusV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OrderbookSettlementChannelRecord>(
        "iroha_data_model::sorafs::orderbook::OrderbookSettlementChannelRecord",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OrderbookSettlementRangeRecord>(
        "iroha_data_model::sorafs::orderbook::OrderbookSettlementRangeRecord",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OrderbookSettlementIndexRecord>(
        "iroha_data_model::sorafs::orderbook::OrderbookSettlementIndexRecord",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OrderbookLedgerStatusV1>(
        "iroha_data_model::sorafs::orderbook::OrderbookLedgerStatusV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OrderbookFinalizedCursorV1>(
        "iroha_data_model::sorafs::orderbook::OrderbookFinalizedCursorV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OrderbookOrderPageV1>(
        "iroha_data_model::sorafs::orderbook::OrderbookOrderPageV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OrderbookSettlementReceiptPageV1>(
        "iroha_data_model::sorafs::orderbook::OrderbookSettlementReceiptPageV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OrderbookTradePageV1>(
        "iroha_data_model::sorafs::orderbook::OrderbookTradePageV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OrderbookSettlementChannelPageV1>(
        "iroha_data_model::sorafs::orderbook::OrderbookSettlementChannelPageV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OrderbookFinalizedEventCursorV1>(
        "iroha_data_model::sorafs::orderbook::OrderbookFinalizedEventCursorV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OrderbookFinalizedEventV1>(
        "iroha_data_model::sorafs::orderbook::OrderbookFinalizedEventV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::OrderbookFinalizedEventPageV1>(
        "iroha_data_model::sorafs::orderbook::OrderbookFinalizedEventPageV1",
    ),
];

#[test]
fn captured_codec_schema_identities() {
    for case in CASES {
        case.check();
    }
}
