//! Immutable compiler-captured identities for this source owner’s existing codecs.

#[test]
fn captured_codec_schema_identities() {
    crate::captured_schema_tests::assert_bidirectional::<super::SoraContainerRuntimeV1>(
        "iroha_data_model::soracloud::SoraContainerRuntimeV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraInrouGuestIsaV1>(
        "iroha_data_model::soracloud::SoraInrouGuestIsaV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::SoraPublishedInrouGuestImageArtifactV1,
    >("iroha_data_model::soracloud::SoraPublishedInrouGuestImageArtifactV1");
    crate::captured_schema_tests::assert_bidirectional::<super::SoraInrouGuestImageV1>(
        "iroha_data_model::soracloud::SoraInrouGuestImageV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraInrouManifestV1>(
        "iroha_data_model::soracloud::SoraInrouManifestV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraNetworkPolicyV1>(
        "iroha_data_model::soracloud::SoraNetworkPolicyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraNetworkAllowlistEntryV1>(
        "iroha_data_model::soracloud::SoraNetworkAllowlistEntryV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraCapabilityPolicyV1>(
        "iroha_data_model::soracloud::SoraCapabilityPolicyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraResourceLimitsV1>(
        "iroha_data_model::soracloud::SoraResourceLimitsV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraLifecycleHooksV1>(
        "iroha_data_model::soracloud::SoraLifecycleHooksV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraConfigExportV1>(
        "iroha_data_model::soracloud::SoraConfigExportV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraConfigExportTargetV1>(
        "iroha_data_model::soracloud::SoraConfigExportTargetV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::CanonicalRequestSignatureWitnessV1>(
        "iroha_data_model::soracloud::CanonicalRequestSignatureWitnessV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::CanonicalRequestWitnessV1>(
        "iroha_data_model::soracloud::CanonicalRequestWitnessV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraContainerManifestV1>(
        "iroha_data_model::soracloud::SoraContainerManifestV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraRouteVisibilityV1>(
        "iroha_data_model::soracloud::SoraRouteVisibilityV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraTlsModeV1>(
        "iroha_data_model::soracloud::SoraTlsModeV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraRouteTargetV1>(
        "iroha_data_model::soracloud::SoraRouteTargetV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraRolloutPolicyV1>(
        "iroha_data_model::soracloud::SoraRolloutPolicyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraContainerManifestRefV1>(
        "iroha_data_model::soracloud::SoraContainerManifestRefV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraServiceExecutionPlaneV1>(
        "iroha_data_model::soracloud::SoraServiceExecutionPlaneV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraLeaseVolumeKindV1>(
        "iroha_data_model::soracloud::SoraLeaseVolumeKindV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraLeaseVolumeBindingV1>(
        "iroha_data_model::soracloud::SoraLeaseVolumeBindingV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraHttpServiceEconomicsV1>(
        "iroha_data_model::soracloud::SoraHttpServiceEconomicsV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraServiceLeaseClockV1>(
        "iroha_data_model::soracloud::SoraServiceLeaseClockV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraServiceLeaseStatusV1>(
        "iroha_data_model::soracloud::SoraServiceLeaseStatusV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraServiceLeaseReporterAssignmentV1>(
        "iroha_data_model::soracloud::SoraServiceLeaseReporterAssignmentV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraServiceLeaseEgressCheckpointV1>(
        "iroha_data_model::soracloud::SoraServiceLeaseEgressCheckpointV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraServiceLeaseUsageAuditV1>(
        "iroha_data_model::soracloud::SoraServiceLeaseUsageAuditV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::SoraServiceLeaseReportingEpochRolloverV1,
    >("iroha_data_model::soracloud::SoraServiceLeaseReportingEpochRolloverV1");
    crate::captured_schema_tests::assert_bidirectional::<super::SoraServiceLeaseStateV1>(
        "iroha_data_model::soracloud::SoraServiceLeaseStateV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraServiceLeaseVolumeStateV1>(
        "iroha_data_model::soracloud::SoraServiceLeaseVolumeStateV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraStateScopeV1>(
        "iroha_data_model::soracloud::SoraStateScopeV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraStateMutabilityV1>(
        "iroha_data_model::soracloud::SoraStateMutabilityV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraStateEncryptionV1>(
        "iroha_data_model::soracloud::SoraStateEncryptionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraStateBindingV1>(
        "iroha_data_model::soracloud::SoraStateBindingV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraServiceHandlerClassV1>(
        "iroha_data_model::soracloud::SoraServiceHandlerClassV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraCertifiedResponsePolicyV1>(
        "iroha_data_model::soracloud::SoraCertifiedResponsePolicyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraArtifactKindV1>(
        "iroha_data_model::soracloud::SoraArtifactKindV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraArtifactRefV1>(
        "iroha_data_model::soracloud::SoraArtifactRefV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraMailboxContractV1>(
        "iroha_data_model::soracloud::SoraMailboxContractV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraServiceHandlerV1>(
        "iroha_data_model::soracloud::SoraServiceHandlerV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraInrouPlacementTargetV1>(
        "iroha_data_model::soracloud::SoraInrouPlacementTargetV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraServiceManifestV1>(
        "iroha_data_model::soracloud::SoraServiceManifestV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AgentUpgradePolicyV1>(
        "iroha_data_model::soracloud::AgentUpgradePolicyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AgentToolCapabilityV1>(
        "iroha_data_model::soracloud::AgentToolCapabilityV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AgentSpendLimitV1>(
        "iroha_data_model::soracloud::AgentSpendLimitV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AgentApartmentManifestV1>(
        "iroha_data_model::soracloud::AgentApartmentManifestV1",
    );
}
