//! Immutable compiler-captured identities for this source owner’s existing codecs.

#[test]
fn captured_codec_schema_identities() {
    crate::captured_schema_tests::assert_bidirectional::<super::SoraInrouHostCapabilityRecordV1>(
        "iroha_data_model::soracloud::SoraInrouHostCapabilityRecordV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraInrouReplicaHostAvailabilityV1>(
        "iroha_data_model::soracloud::SoraInrouReplicaHostAvailabilityV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraInrouReplicaPlacementV1>(
        "iroha_data_model::soracloud::SoraInrouReplicaPlacementV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraInrouServicePlacementRecordV1>(
        "iroha_data_model::soracloud::SoraInrouServicePlacementRecordV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraHfSourceRecordV1>(
        "iroha_data_model::soracloud::SoraHfSourceRecordV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraHfSharedLeaseStatusV1>(
        "iroha_data_model::soracloud::SoraHfSharedLeaseStatusV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraHfSharedLeaseMemberStatusV1>(
        "iroha_data_model::soracloud::SoraHfSharedLeaseMemberStatusV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraHfSharedLeaseActionV1>(
        "iroha_data_model::soracloud::SoraHfSharedLeaseActionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraHfSharedLeaseQueuedWindowV1>(
        "iroha_data_model::soracloud::SoraHfSharedLeaseQueuedWindowV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraHfSharedLeasePoolV1>(
        "iroha_data_model::soracloud::SoraHfSharedLeasePoolV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraHfSharedLeaseMemberV1>(
        "iroha_data_model::soracloud::SoraHfSharedLeaseMemberV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraHfSharedLeaseAuditEventV1>(
        "iroha_data_model::soracloud::SoraHfSharedLeaseAuditEventV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraModelArtifactAuditEventV1>(
        "iroha_data_model::soracloud::SoraModelArtifactAuditEventV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraAgentApartmentActionV1>(
        "iroha_data_model::soracloud::SoraAgentApartmentActionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraAgentRuntimeStatusV1>(
        "iroha_data_model::soracloud::SoraAgentRuntimeStatusV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraAgentWalletSpendRequestV1>(
        "iroha_data_model::soracloud::SoraAgentWalletSpendRequestV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraAgentWalletDailySpendEntryV1>(
        "iroha_data_model::soracloud::SoraAgentWalletDailySpendEntryV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraAgentMailboxMessageV1>(
        "iroha_data_model::soracloud::SoraAgentMailboxMessageV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraAgentArtifactAllowRuleV1>(
        "iroha_data_model::soracloud::SoraAgentArtifactAllowRuleV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraAgentAutonomyRunRecordV1>(
        "iroha_data_model::soracloud::SoraAgentAutonomyRunRecordV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraAgentPersistentStateV1>(
        "iroha_data_model::soracloud::SoraAgentPersistentStateV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraAgentApartmentRecordV1>(
        "iroha_data_model::soracloud::SoraAgentApartmentRecordV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraAgentApartmentAuditEventV1>(
        "iroha_data_model::soracloud::SoraAgentApartmentAuditEventV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraAppInfraActionV1>(
        "iroha_data_model::soracloud::SoraAppInfraActionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraAppStaticSiteBindingV1>(
        "iroha_data_model::soracloud::SoraAppStaticSiteBindingV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraAppRouteProjectionV1>(
        "iroha_data_model::soracloud::SoraAppRouteProjectionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraAppInfraServiceRefV1>(
        "iroha_data_model::soracloud::SoraAppInfraServiceRefV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraAppInfraManifestV1>(
        "iroha_data_model::soracloud::SoraAppInfraManifestV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::SoraAppInfraExactCurrentRevisionPreconditionV1,
    >("iroha_data_model::soracloud::SoraAppInfraExactCurrentRevisionPreconditionV1");
    crate::captured_schema_tests::assert_bidirectional::<super::SoraAppInfraMutationPreconditionV1>(
        "iroha_data_model::soracloud::SoraAppInfraMutationPreconditionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraAppInfraStateV1>(
        "iroha_data_model::soracloud::SoraAppInfraStateV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraAppInfraAuditEventV1>(
        "iroha_data_model::soracloud::SoraAppInfraAuditEventV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraServiceAuditEventV1>(
        "iroha_data_model::soracloud::SoraServiceAuditEventV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraServiceHealthStatusV1>(
        "iroha_data_model::soracloud::SoraServiceHealthStatusV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraServiceRuntimeStateV1>(
        "iroha_data_model::soracloud::SoraServiceRuntimeStateV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraInrouReplicaRuntimeStateV1>(
        "iroha_data_model::soracloud::SoraInrouReplicaRuntimeStateV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraServiceMailboxMessageV1>(
        "iroha_data_model::soracloud::SoraServiceMailboxMessageV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::SoraRuntimeDeterministicValidatorHostV1,
    >("iroha_data_model::soracloud::SoraRuntimeDeterministicValidatorHostV1");
    crate::captured_schema_tests::assert_bidirectional::<super::SoraOrderedMailboxStateMutationV1>(
        "iroha_data_model::soracloud::SoraOrderedMailboxStateMutationV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraOrderedMailboxResultV1>(
        "iroha_data_model::soracloud::SoraOrderedMailboxResultV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraRuntimeReceiptV1>(
        "iroha_data_model::soracloud::SoraRuntimeReceiptV1",
    );
}
