//! Immutable compiler-captured identities for this source owner’s existing codecs.

const CASES: &[crate::captured_schema_tests::Case] = &[
    crate::captured_schema_tests::Case::bidirectional::<super::SoraServiceLifecycleActionV1>(
        "iroha_data_model::soracloud::SoraServiceLifecycleActionV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<
        super::SoraServiceExactCurrentRevisionPreconditionV1,
    >("iroha_data_model::soracloud::SoraServiceExactCurrentRevisionPreconditionV1"),
    crate::captured_schema_tests::Case::bidirectional::<super::SoraServiceMutationPreconditionV1>(
        "iroha_data_model::soracloud::SoraServiceMutationPreconditionV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SoraStateMutationOperationV1>(
        "iroha_data_model::soracloud::SoraStateMutationOperationV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SoraRolloutStageV1>(
        "iroha_data_model::soracloud::SoraRolloutStageV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SoraServiceRolloutStateV1>(
        "iroha_data_model::soracloud::SoraServiceRolloutStateV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SoraServiceDeploymentStateV1>(
        "iroha_data_model::soracloud::SoraServiceDeploymentStateV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SoraServiceConfigEntryV1>(
        "iroha_data_model::soracloud::SoraServiceConfigEntryV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SoraServiceSecretEntryV1>(
        "iroha_data_model::soracloud::SoraServiceSecretEntryV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SoraServiceConfigMutationV1>(
        "iroha_data_model::soracloud::SoraServiceConfigMutationV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SoraServiceSecretMutationV1>(
        "iroha_data_model::soracloud::SoraServiceSecretMutationV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SoraServiceStateEntryV1>(
        "iroha_data_model::soracloud::SoraServiceStateEntryV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SoraDecryptionRequestRecordV1>(
        "iroha_data_model::soracloud::SoraDecryptionRequestRecordV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SoraTrainingJobStatusV1>(
        "iroha_data_model::soracloud::SoraTrainingJobStatusV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SoraTrainingJobActionV1>(
        "iroha_data_model::soracloud::SoraTrainingJobActionV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SoraTrainingJobRecordV1>(
        "iroha_data_model::soracloud::SoraTrainingJobRecordV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SoraTrainingJobAuditEventV1>(
        "iroha_data_model::soracloud::SoraTrainingJobAuditEventV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SoraModelRegistryV1>(
        "iroha_data_model::soracloud::SoraModelRegistryV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SoraModelWeightActionV1>(
        "iroha_data_model::soracloud::SoraModelWeightActionV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SoraModelProvenanceKindV1>(
        "iroha_data_model::soracloud::SoraModelProvenanceKindV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SoraModelProvenanceRefV1>(
        "iroha_data_model::soracloud::SoraModelProvenanceRefV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SoraUploadedModelPackageFormatV1>(
        "iroha_data_model::soracloud::SoraUploadedModelPackageFormatV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SoraUploadedModelPricingPolicyV1>(
        "iroha_data_model::soracloud::SoraUploadedModelPricingPolicyV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SoraUploadedModelBundleV1>(
        "iroha_data_model::soracloud::SoraUploadedModelBundleV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SoraModelWeightVersionRecordV1>(
        "iroha_data_model::soracloud::SoraModelWeightVersionRecordV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SoraModelWeightAuditEventV1>(
        "iroha_data_model::soracloud::SoraModelWeightAuditEventV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SoraModelArtifactActionV1>(
        "iroha_data_model::soracloud::SoraModelArtifactActionV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::SoraModelArtifactRecordV1>(
        "iroha_data_model::soracloud::SoraModelArtifactRecordV1",
    ),
];

#[test]
fn captured_codec_schema_identities() {
    for case in CASES {
        case.check();
    }
}
