//! Immutable compiler-captured identities for this source owner’s existing codecs.

#[test]
fn captured_codec_schema_identities() {
    crate::captured_schema_tests::assert_bidirectional::<super::FheSchemeV1>(
        "iroha_data_model::soracloud::FheSchemeV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FheParamLifecycleV1>(
        "iroha_data_model::soracloud::FheParamLifecycleV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FheParamSetV1>(
        "iroha_data_model::soracloud::FheParamSetV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FheDeterministicRoundingModeV1>(
        "iroha_data_model::soracloud::FheDeterministicRoundingModeV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::BfvRefreshTranscriptModeV1>(
        "iroha_data_model::soracloud::BfvRefreshTranscriptModeV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::BfvCiphertextBoundModeV1>(
        "iroha_data_model::soracloud::BfvCiphertextBoundModeV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::BfvRotationRefreshTranscriptV1>(
        "iroha_data_model::soracloud::BfvRotationRefreshTranscriptV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::BfvBootstrapRefreshTranscriptV1>(
        "iroha_data_model::soracloud::BfvBootstrapRefreshTranscriptV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::BfvEvaluationKeyRefreshTranscriptV1>(
        "iroha_data_model::soracloud::BfvEvaluationKeyRefreshTranscriptV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FheExecutionPolicyV1>(
        "iroha_data_model::soracloud::FheExecutionPolicyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FheGovernanceBundleV1>(
        "iroha_data_model::soracloud::FheGovernanceBundleV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoracloudFhePolicyReferenceV1>(
        "iroha_data_model::soracloud::SoracloudFhePolicyReferenceV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::SoracloudFheGovernancePermissionScopeV1,
    >("iroha_data_model::soracloud::SoracloudFheGovernancePermissionScopeV1");
    crate::captured_schema_tests::assert_bidirectional::<super::SoracloudFheGovernedMaterialV1>(
        "iroha_data_model::soracloud::SoracloudFheGovernedMaterialV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoracloudFhePolicyVersionLifecycleV1>(
        "iroha_data_model::soracloud::SoracloudFhePolicyVersionLifecycleV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoracloudFhePolicyVersionStateV1>(
        "iroha_data_model::soracloud::SoracloudFhePolicyVersionStateV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoracloudFhePolicyRecordV1>(
        "iroha_data_model::soracloud::SoracloudFhePolicyRecordV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoracloudFheInputAdmissionProofV1>(
        "iroha_data_model::soracloud::SoracloudFheInputAdmissionProofV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoracloudFhePublicKeyProofV1>(
        "iroha_data_model::soracloud::SoracloudFhePublicKeyProofV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoracloudFheBootstrapKeyProofV1>(
        "iroha_data_model::soracloud::SoracloudFheBootstrapKeyProofV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::SoracloudFheFullBootstrapExecutionProofV1,
    >("iroha_data_model::soracloud::SoracloudFheFullBootstrapExecutionProofV1");
    crate::captured_schema_tests::assert_bidirectional::<super::SecretEnvelopeEncryptionV1>(
        "iroha_data_model::soracloud::SecretEnvelopeEncryptionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SecretEnvelopeV1>(
        "iroha_data_model::soracloud::SecretEnvelopeV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::CiphertextStateMetadataV1>(
        "iroha_data_model::soracloud::CiphertextStateMetadataV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::CiphertextStateRecordV1>(
        "iroha_data_model::soracloud::CiphertextStateRecordV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FheJobOperationV1>(
        "iroha_data_model::soracloud::FheJobOperationV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FheJobInputRefV1>(
        "iroha_data_model::soracloud::FheJobInputRefV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FheJobSpecV1>(
        "iroha_data_model::soracloud::FheJobSpecV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::DecryptionAuthorityModeV1>(
        "iroha_data_model::soracloud::DecryptionAuthorityModeV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::DecryptionAuthorityPolicyV1>(
        "iroha_data_model::soracloud::DecryptionAuthorityPolicyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::DecryptionRequestV1>(
        "iroha_data_model::soracloud::DecryptionRequestV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::CiphertextQueryMetadataLevelV1>(
        "iroha_data_model::soracloud::CiphertextQueryMetadataLevelV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::CiphertextQuerySpecV1>(
        "iroha_data_model::soracloud::CiphertextQuerySpecV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::CiphertextInclusionProofV1>(
        "iroha_data_model::soracloud::CiphertextInclusionProofV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::CiphertextQueryResultItemV1>(
        "iroha_data_model::soracloud::CiphertextQueryResultItemV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::CiphertextQueryResponseV1>(
        "iroha_data_model::soracloud::CiphertextQueryResponseV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraDeploymentBundleV1>(
        "iroha_data_model::soracloud::SoraDeploymentBundleV1",
    );
}
