//! Immutable compiler-captured identities for this source owner’s existing codecs.

#[test]
fn captured_codec_schema_identities() {
    crate::captured_schema_tests::assert_bidirectional::<super::SoraServiceLifecycleActionV1>(
        "iroha_data_model::soracloud::SoraServiceLifecycleActionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::SoraServiceExactCurrentRevisionPreconditionV1,
    >("iroha_data_model::soracloud::SoraServiceExactCurrentRevisionPreconditionV1");
    crate::captured_schema_tests::assert_bidirectional::<super::SoraServiceMutationPreconditionV1>(
        "iroha_data_model::soracloud::SoraServiceMutationPreconditionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraStateMutationOperationV1>(
        "iroha_data_model::soracloud::SoraStateMutationOperationV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraRolloutStageV1>(
        "iroha_data_model::soracloud::SoraRolloutStageV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraServiceRolloutStateV1>(
        "iroha_data_model::soracloud::SoraServiceRolloutStateV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraServiceDeploymentStateV1>(
        "iroha_data_model::soracloud::SoraServiceDeploymentStateV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraServiceConfigEntryV1>(
        "iroha_data_model::soracloud::SoraServiceConfigEntryV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraServiceSecretEntryV1>(
        "iroha_data_model::soracloud::SoraServiceSecretEntryV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraServiceConfigMutationV1>(
        "iroha_data_model::soracloud::SoraServiceConfigMutationV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraServiceSecretMutationV1>(
        "iroha_data_model::soracloud::SoraServiceSecretMutationV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraServiceStateEntryV1>(
        "iroha_data_model::soracloud::SoraServiceStateEntryV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraDecryptionRequestRecordV1>(
        "iroha_data_model::soracloud::SoraDecryptionRequestRecordV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraTrainingJobStatusV1>(
        "iroha_data_model::soracloud::SoraTrainingJobStatusV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraTrainingJobActionV1>(
        "iroha_data_model::soracloud::SoraTrainingJobActionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraTrainingJobRecordV1>(
        "iroha_data_model::soracloud::SoraTrainingJobRecordV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraTrainingJobAuditEventV1>(
        "iroha_data_model::soracloud::SoraTrainingJobAuditEventV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraModelRegistryV1>(
        "iroha_data_model::soracloud::SoraModelRegistryV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraModelWeightActionV1>(
        "iroha_data_model::soracloud::SoraModelWeightActionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraModelProvenanceKindV1>(
        "iroha_data_model::soracloud::SoraModelProvenanceKindV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraModelProvenanceRefV1>(
        "iroha_data_model::soracloud::SoraModelProvenanceRefV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraUploadedModelPackageFormatV1>(
        "iroha_data_model::soracloud::SoraUploadedModelPackageFormatV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraUploadedModelPricingPolicyV1>(
        "iroha_data_model::soracloud::SoraUploadedModelPricingPolicyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraUploadedModelBundleV1>(
        "iroha_data_model::soracloud::SoraUploadedModelBundleV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraModelWeightVersionRecordV1>(
        "iroha_data_model::soracloud::SoraModelWeightVersionRecordV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraModelWeightAuditEventV1>(
        "iroha_data_model::soracloud::SoraModelWeightAuditEventV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraModelArtifactActionV1>(
        "iroha_data_model::soracloud::SoraModelArtifactActionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SoraModelArtifactRecordV1>(
        "iroha_data_model::soracloud::SoraModelArtifactRecordV1",
    );
}
