name: NoritoDemo
options:
  bundleIdPrefix: tech.iroha
settings:
  configs:
    Debug:
      ONLY_ACTIVE_ARCH: YES
packages:
  IrohaSwift:
    path: ../../../IrohaSwift
targets:
  NoritoDemo:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - Sources
    resources:
      - ../../../fixtures/sdk/pos/manifest_v1.json
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: tech.iroha.NoritoDemo
      SWIFT_VERSION: 5.9
      INFOPLIST_FILE: Sources/Info.plist
    dependencies:
      - package: IrohaSwift
  NoritoDemoTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - Tests
    settings:
      INFOPLIST_FILE: Tests/Info.plist
    dependencies:
      - target: NoritoDemo
      - package: IrohaSwift
