[package]
name = "executor_custom_data_model"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true

[dependencies]
iroha_executor_data_model.workspace = true
iroha_data_model = { workspace = true, features = ["application-model", "fault_injection"], default-features = false }
iroha_schema.workspace = true

norito = { workspace = true, default-features = false, features = ["base-codec"] }

[dev-dependencies]
base64 = { workspace = true }
iroha_crypto = { workspace = true, features = ["consensus"], default-features = false }
