//! Immutable compiler-captured identities for this source owner’s existing codecs.

#[test]
fn captured_codec_schema_identities() {
    crate::captured_schema_tests::assert_bidirectional::<super::AliasRegistryRoutingActivationV1>(
        "iroha_data_model::alias_setup::AliasRegistryRoutingActivationV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AliasDataspaceBootstrapGrantV1>(
        "iroha_data_model::alias_setup::AliasDataspaceBootstrapGrantV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AccountAliasName>(
        "iroha_data_model::alias_setup::AccountAliasName",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ResolvedDataSpaceV1>(
        "iroha_data_model::alias_setup::ResolvedDataSpaceV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ResolvedDomainV1>(
        "iroha_data_model::alias_setup::ResolvedDomainV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ResolvedAccountAliasV1>(
        "iroha_data_model::alias_setup::ResolvedAccountAliasV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AccountProvisionV1>(
        "iroha_data_model::alias_setup::AccountProvisionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AccountAliasRoleV1>(
        "iroha_data_model::alias_setup::AccountAliasRoleV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AliasDataSpaceIntentV1>(
        "iroha_data_model::alias_setup::AliasDataSpaceIntentV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AliasDomainIntentV1>(
        "iroha_data_model::alias_setup::AliasDomainIntentV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AliasAccountIntentV1>(
        "iroha_data_model::alias_setup::AliasAccountIntentV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AliasIntentV1>(
        "iroha_data_model::alias_setup::AliasIntentV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AliasLeaseAcquisitionV1>(
        "iroha_data_model::alias_setup::AliasLeaseAcquisitionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AliasQuoteGuardV1>(
        "iroha_data_model::alias_setup::AliasQuoteGuardV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AliasSetupPlanRequestV1>(
        "iroha_data_model::alias_setup::AliasSetupPlanRequestV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AliasTargetV1>(
        "iroha_data_model::alias_setup::AliasTargetV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AliasAutoRenewConfigV1>(
        "iroha_data_model::alias_setup::AliasAutoRenewConfigV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AliasAutoRenewStateV1>(
        "iroha_data_model::alias_setup::AliasAutoRenewStateV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AliasLeaseRenewPlanRequestV1>(
        "iroha_data_model::alias_setup::AliasLeaseRenewPlanRequestV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AliasAutoRenewPlanRequestV1>(
        "iroha_data_model::alias_setup::AliasAutoRenewPlanRequestV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AliasLifecycleOperationV1>(
        "iroha_data_model::alias_setup::AliasLifecycleOperationV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AliasLifecyclePlanDispositionV1>(
        "iroha_data_model::alias_setup::AliasLifecyclePlanDispositionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AliasPlanDispositionV1>(
        "iroha_data_model::alias_setup::AliasPlanDispositionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AliasLeaseQuoteV1>(
        "iroha_data_model::alias_setup::AliasLeaseQuoteV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AliasPlanResourceV1>(
        "iroha_data_model::alias_setup::AliasPlanResourceV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AliasFramedInstructionV1>(
        "iroha_data_model::alias_setup::AliasFramedInstructionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AliasAssetTotalV1>(
        "iroha_data_model::alias_setup::AliasAssetTotalV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AliasSetupStatusV1>(
        "iroha_data_model::alias_setup::AliasSetupStatusV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AliasSetupValidationPhaseV1>(
        "iroha_data_model::alias_setup::AliasSetupValidationPhaseV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AliasSetupSeverityV1>(
        "iroha_data_model::alias_setup::AliasSetupSeverityV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AliasSetupDiagnosticV1>(
        "iroha_data_model::alias_setup::AliasSetupDiagnosticV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AliasSetupReportV1>(
        "iroha_data_model::alias_setup::AliasSetupReportV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AliasPlanAnchorV1>(
        "iroha_data_model::alias_setup::AliasPlanAnchorV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AliasTransactionPlanBodyV1>(
        "iroha_data_model::alias_setup::AliasTransactionPlanBodyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AliasTransactionPlanV1>(
        "iroha_data_model::alias_setup::AliasTransactionPlanV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AliasLifecycleTransactionPlanBodyV1>(
        "iroha_data_model::alias_setup::AliasLifecycleTransactionPlanBodyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AliasLifecycleTransactionPlanV1>(
        "iroha_data_model::alias_setup::AliasLifecycleTransactionPlanV1",
    );
}
