//! Immutable compiler-captured identities for this source owner’s existing codecs.

#[test]
fn captured_codec_schema_identities() {
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyZkX509DisclosedAttributeV1>(
        "iroha_data_model::privacy::PrivacyZkX509DisclosedAttributeV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::IrohaZkX509StarkP256StatementV1>(
        "iroha_data_model::privacy::IrohaZkX509StarkP256StatementV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyJindoFieldElementV1>(
        "iroha_data_model::privacy::PrivacyJindoFieldElementV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyJindoLatticeCommitmentV1>(
        "iroha_data_model::privacy::PrivacyJindoLatticeCommitmentV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::IrohaJindoPolynomialCommitmentStatementV1,
    >("iroha_data_model::privacy::IrohaJindoPolynomialCommitmentStatementV1");
    crate::captured_schema_tests::assert_bidirectional::<super::BootleLanternAttributeValueV1>(
        "iroha_data_model::privacy::BootleLanternAttributeValueV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::BootleLanternPolynomialV1>(
        "iroha_data_model::privacy::BootleLanternPolynomialV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::BootleLanternIssuerPublicMatrixV1>(
        "iroha_data_model::privacy::BootleLanternIssuerPublicMatrixV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::BootleLanternAllowedAttributeValuesV1,
    >("iroha_data_model::privacy::BootleLanternAllowedAttributeValuesV1");
    crate::captured_schema_tests::assert_bidirectional::<super::BootleLanternIssuerPolicyLifecycleV1>(
        "iroha_data_model::privacy::BootleLanternIssuerPolicyLifecycleV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::BootleLanternIssuerPolicyV1>(
        "iroha_data_model::privacy::BootleLanternIssuerPolicyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::BootleLanternDisclosedAttributeV1>(
        "iroha_data_model::privacy::BootleLanternDisclosedAttributeV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::IrohaBootleLanternAnoncredStatementV1,
    >("iroha_data_model::privacy::IrohaBootleLanternAnoncredStatementV1");
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyValueBalanceDirectionV1>(
        "iroha_data_model::privacy::PrivacyValueBalanceDirectionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyValueBalanceV1>(
        "iroha_data_model::privacy::PrivacyValueBalanceV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyOrchardActionV1>(
        "iroha_data_model::privacy::PrivacyOrchardActionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OrchardHalo2ActionsStatementV1>(
        "iroha_data_model::privacy::OrchardHalo2ActionsStatementV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::MoneroFcmpPlusPlusStatementV1>(
        "iroha_data_model::privacy::MoneroFcmpPlusPlusStatementV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::IrohaIvmPrivateNoteStarkStatementV1>(
        "iroha_data_model::privacy::IrohaIvmPrivateNoteStarkStatementV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyPqAuthorizationProfileV1>(
        "iroha_data_model::privacy::PrivacyPqAuthorizationProfileV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyPqNoteEncryptionProfileV1>(
        "iroha_data_model::privacy::PrivacyPqNoteEncryptionProfileV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PqMaspStarkStatementV1>(
        "iroha_data_model::privacy::PqMaspStarkStatementV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyStatementV1>(
        "iroha_data_model::privacy::PrivacyStatementV1",
    );
}
