//! Immutable compiler-captured identities for this source owner’s existing codecs.

#[test]
fn captured_codec_schema_identities() {
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyP256PointV1>(
        "iroha_data_model::privacy::PrivacyP256PointV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyP256CiphertextV1>(
        "iroha_data_model::privacy::PrivacyP256CiphertextV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyPolicyNamespaceV1>(
        "iroha_data_model::privacy::PrivacyPolicyNamespaceV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyPoolNamespaceV1>(
        "iroha_data_model::privacy::PrivacyPoolNamespaceV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::PrivacyIssuerRegistryPolicyNamespaceV1,
    >("iroha_data_model::privacy::PrivacyIssuerRegistryPolicyNamespaceV1");
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyTrustAnchorNamespaceV1>(
        "iroha_data_model::privacy::PrivacyTrustAnchorNamespaceV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyTrustAnchorPolicyNamespaceV1>(
        "iroha_data_model::privacy::PrivacyTrustAnchorPolicyNamespaceV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyParameterNamespaceV1>(
        "iroha_data_model::privacy::PrivacyParameterNamespaceV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyIssuerPolicyNamespaceV1>(
        "iroha_data_model::privacy::PrivacyIssuerPolicyNamespaceV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyPoolProgramNamespaceV1>(
        "iroha_data_model::privacy::PrivacyPoolProgramNamespaceV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyNamespaceScopeV1>(
        "iroha_data_model::privacy::PrivacyNamespaceScopeV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyNamespaceV1>(
        "iroha_data_model::privacy::PrivacyNamespaceV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyRootManagementV1>(
        "iroha_data_model::privacy::PrivacyRootManagementV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyRootRoleV1>(
        "iroha_data_model::privacy::PrivacyRootRoleV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyRootPublicationV1>(
        "iroha_data_model::privacy::PrivacyRootPublicationV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyOrchardPoolBootstrapV1>(
        "iroha_data_model::privacy::PrivacyOrchardPoolBootstrapV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyFcmpOutputTupleV1>(
        "iroha_data_model::privacy::PrivacyFcmpOutputTupleV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyFcmpTreeRootV1>(
        "iroha_data_model::privacy::PrivacyFcmpTreeRootV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyFcmpInputPublicV1>(
        "iroha_data_model::privacy::PrivacyFcmpInputPublicV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyFcmpEncryptedOutputV1>(
        "iroha_data_model::privacy::PrivacyFcmpEncryptedOutputV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyFcmpPoolBootstrapV1>(
        "iroha_data_model::privacy::PrivacyFcmpPoolBootstrapV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyIvmPrivateNotePoolBootstrapV1>(
        "iroha_data_model::privacy::PrivacyIvmPrivateNotePoolBootstrapV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyPqMaspPoolBootstrapV1>(
        "iroha_data_model::privacy::PrivacyPqMaspPoolBootstrapV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyProofManagedPoolBootstrapV1>(
        "iroha_data_model::privacy::PrivacyProofManagedPoolBootstrapV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyPgcAccountV1>(
        "iroha_data_model::privacy::PrivacyPgcAccountV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyPgcBootstrapProofBytesV1>(
        "iroha_data_model::privacy::PrivacyPgcBootstrapProofBytesV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyPgcAccountBootstrapV1>(
        "iroha_data_model::privacy::PrivacyPgcAccountBootstrapV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyConsensusLimitsV1>(
        "iroha_data_model::privacy::PrivacyConsensusLimitsV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyConsensusPolicyTighteningV1>(
        "iroha_data_model::privacy::PrivacyConsensusPolicyTighteningV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyConsensusPolicyV1>(
        "iroha_data_model::privacy::PrivacyConsensusPolicyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyProposedLifecycleV1>(
        "iroha_data_model::privacy::PrivacyProposedLifecycleV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyActiveLifecycleV1>(
        "iroha_data_model::privacy::PrivacyActiveLifecycleV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacySuspendedLifecycleV1>(
        "iroha_data_model::privacy::PrivacySuspendedLifecycleV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyRetiredLifecycleV1>(
        "iroha_data_model::privacy::PrivacyRetiredLifecycleV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyProtocolLifecycleV1>(
        "iroha_data_model::privacy::PrivacyProtocolLifecycleV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacySecurityClaimV1>(
        "iroha_data_model::privacy::PrivacySecurityClaimV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AnonymousPgcActivationLimitsV1>(
        "iroha_data_model::privacy::AnonymousPgcActivationLimitsV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::VeRangeActivationLimitsV1>(
        "iroha_data_model::privacy::VeRangeActivationLimitsV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ZkAmsActivationLimitsV1>(
        "iroha_data_model::privacy::ZkAmsActivationLimitsV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::JindoActivationLimitsV1>(
        "iroha_data_model::privacy::JindoActivationLimitsV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::OrchardActivationLimitsV1>(
        "iroha_data_model::privacy::OrchardActivationLimitsV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::FcmpActivationLimitsV1>(
        "iroha_data_model::privacy::FcmpActivationLimitsV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::IvmPrivateNoteActivationLimitsV1>(
        "iroha_data_model::privacy::IvmPrivateNoteActivationLimitsV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PqMaspActivationLimitsV1>(
        "iroha_data_model::privacy::PqMaspActivationLimitsV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyProtocolActivationLimitsV1>(
        "iroha_data_model::privacy::PrivacyProtocolActivationLimitsV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyProtocolLimitsTighteningV1>(
        "iroha_data_model::privacy::PrivacyProtocolLimitsTighteningV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyProtocolActivationRecordV1>(
        "iroha_data_model::privacy::PrivacyProtocolActivationRecordV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyCompiledProfileSnapshotV1>(
        "iroha_data_model::privacy::PrivacyCompiledProfileSnapshotV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::PrivacyCompiledStatementSchemaErrorV1,
    >("iroha_data_model::privacy::PrivacyCompiledStatementSchemaErrorV1");
    crate::captured_schema_tests::assert_bidirectional::<
        super::PrivacyCompiledProfileUnavailableReasonV1,
    >("iroha_data_model::privacy::PrivacyCompiledProfileUnavailableReasonV1");
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyCompiledProfileResultV1>(
        "iroha_data_model::privacy::PrivacyCompiledProfileResultV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyCompiledProfileCatalogRowV1>(
        "iroha_data_model::privacy::PrivacyCompiledProfileCatalogRowV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyCompiledProfileCatalogV1>(
        "iroha_data_model::privacy::PrivacyCompiledProfileCatalogV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyCapabilityRowV1>(
        "iroha_data_model::privacy::PrivacyCapabilityRowV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyCapabilitySnapshotV1>(
        "iroha_data_model::privacy::PrivacyCapabilitySnapshotV1",
    );
}
