//! Immutable compiler-captured identities for this source owner’s existing codecs.

#[test]
fn captured_codec_schema_identities() {
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyStatementContextV1>(
        "iroha_data_model::privacy::PrivacyStatementContextV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyNativeConsensusBindingV1>(
        "iroha_data_model::privacy::PrivacyNativeConsensusBindingV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyEncryptedOutputV1>(
        "iroha_data_model::privacy::PrivacyEncryptedOutputV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyZkAcePolicyLifecycleV1>(
        "iroha_data_model::privacy::PrivacyZkAcePolicyLifecycleV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyZkAcePolicyDigestMaterialV1>(
        "iroha_data_model::privacy::PrivacyZkAcePolicyDigestMaterialV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyZkAcePolicyRecordV1>(
        "iroha_data_model::privacy::PrivacyZkAcePolicyRecordV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ZkAcePqAuthorizationStatementV1>(
        "iroha_data_model::privacy::ZkAcePqAuthorizationStatementV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::AnonymousPgcKOutOfNStatementV1>(
        "iroha_data_model::privacy::AnonymousPgcKOutOfNStatementV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyVeRangeBitLengthV1>(
        "iroha_data_model::privacy::PrivacyVeRangeBitLengthV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::VeRangeTransparentRangeStatementV1>(
        "iroha_data_model::privacy::VeRangeTransparentRangeStatementV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyZkAmsRegistryBootstrapV1>(
        "iroha_data_model::privacy::PrivacyZkAmsRegistryBootstrapV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyZkAmsPersonhoodCredentialV1>(
        "iroha_data_model::privacy::PrivacyZkAmsPersonhoodCredentialV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyZkAmsPhcCanonicalPayloadV1>(
        "iroha_data_model::privacy::PrivacyZkAmsPhcCanonicalPayloadV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyZkAmsAdmissionAnchorV1>(
        "iroha_data_model::privacy::PrivacyZkAmsAdmissionAnchorV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyZkAmsBatchAdmissionV1>(
        "iroha_data_model::privacy::PrivacyZkAmsBatchAdmissionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyZkAmsProvisionAccountV1>(
        "iroha_data_model::privacy::PrivacyZkAmsProvisionAccountV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyZkAmsActionV1>(
        "iroha_data_model::privacy::PrivacyZkAmsActionV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::IrohaZkAmsStatementV1>(
        "iroha_data_model::privacy::IrohaZkAmsStatementV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyCredentialDocumentTypeV1>(
        "iroha_data_model::privacy::PrivacyCredentialDocumentTypeV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyVegaMdlNamespaceV1>(
        "iroha_data_model::privacy::PrivacyVegaMdlNamespaceV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyVegaMdlDigestAlgorithmV1>(
        "iroha_data_model::privacy::PrivacyVegaMdlDigestAlgorithmV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyVegaMdlSignatureAlgorithmV1>(
        "iroha_data_model::privacy::PrivacyVegaMdlSignatureAlgorithmV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyVegaIssuerRecordLifecycleV1>(
        "iroha_data_model::privacy::PrivacyVegaIssuerRecordLifecycleV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyVegaIssuerRecordV1>(
        "iroha_data_model::privacy::PrivacyVegaIssuerRecordV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyVegaMdlDateV1>(
        "iroha_data_model::privacy::PrivacyVegaMdlDateV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::VegaExistingCredentialStatementV1>(
        "iroha_data_model::privacy::VegaExistingCredentialStatementV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyX509KeyUsageV1>(
        "iroha_data_model::privacy::PrivacyX509KeyUsageV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyX509ExtendedKeyUsageV1>(
        "iroha_data_model::privacy::PrivacyX509ExtendedKeyUsageV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyZkX509RecordLifecycleV1>(
        "iroha_data_model::privacy::PrivacyZkX509RecordLifecycleV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyZkX509TrustAnchorRecordV1>(
        "iroha_data_model::privacy::PrivacyZkX509TrustAnchorRecordV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::PrivacyZkX509CertificatePolicyRecordV1,
    >("iroha_data_model::privacy::PrivacyZkX509CertificatePolicyRecordV1");
    crate::captured_schema_tests::assert_bidirectional::<super::PrivacyZkX509CrlRecordV1>(
        "iroha_data_model::privacy::PrivacyZkX509CrlRecordV1",
    );
}
