chain = "00000000-0000-0000-0000-000000000000"
network_id_file = "/run/iroha/genesis.expected_hash"
torii_url = "http://127.0.0.1:8080/"

[basic_auth]
web_login = "nexus_operator"
password = "nexus_password"

[account]
domain = "wonderland.universal"
public_key = "ed0120CE7FA46C9DCE7EA4B125E2E36BDB63EA33073E7590AC92816AE1E861B7048B03"
private_key_file = "/run/secrets/iroha/nexus-operator-account-private-key"

[connect]
# Root directory for Connect queue diagnostics and evidence export. Defaults to `~/.iroha/connect`.
# queue_root = "/home/nexus/.iroha/connect"
