//! Structured logging primitives shared between the supervisor and UI layers.
//!
//! Each peer exposes a log stream that delivers structured events for both
//! stdout/stderr lines and lifecycle notifications such as automatic restarts.

use std::{
    fmt,
    sync::Arc,
    time::{Duration, SystemTime, UNIX_EPOCH},
};

use tokio::sync::broadcast;

/// Identifies the source of a log entry.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LogStreamKind {
    /// Captured from the process `stdout`.
    Stdout,
    /// Captured from the process `stderr`.
    Stderr,
    /// Supervisor lifecycle/meta event.
    System,
}

impl fmt::Display for LogStreamKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            LogStreamKind::Stdout => write!(f, "stdout"),
            LogStreamKind::Stderr => write!(f, "stderr"),
            LogStreamKind::System => write!(f, "system"),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn emit_line_broadcasts_event() {
        let stream = PeerLogStream::new("peer0");
        let mut receiver = stream.subscribe();
        stream.emit_line(LogStreamKind::Stdout, "hello world");
        let event = receiver.try_recv().expect("line event available");
        match event {
            PeerLogEvent::Line {
                alias,
                kind,
                message,
                ..
            } => {
                assert_eq!(alias.as_ref(), "peer0");
                assert_eq!(kind, LogStreamKind::Stdout);
                assert_eq!(message, "hello world");
            }
            other => panic!("expected line event, got {other:?}"),
        }
    }

    #[test]
    fn emit_lifecycle_broadcasts_event() {
        let stream = PeerLogStream::new("peer1");
        let mut receiver = stream.subscribe();
        stream.emit_lifecycle(LifecycleEvent::Started { attempt: 0 });
        let event = receiver.try_recv().expect("lifecycle event available");
        match event {
            PeerLogEvent::Lifecycle {
                alias,
                event: LifecycleEvent::Started { attempt },
                ..
            } => {
                assert_eq!(alias.as_ref(), "peer1");
                assert_eq!(attempt, 0);
            }
            other => panic!("expected lifecycle event, got {other:?}"),
        }
    }
}

/// Events emitted on a peer log stream.
#[derive(Debug, Clone)]
pub enum PeerLogEvent {
    /// A line captured from the peer process.
    Line {
        /// Logical peer alias (`peer0`, `peer1`, …).
        alias: Arc<str>,
        /// Source stream (stdout/stderr).
        kind: LogStreamKind,
        /// Timestamp when the line was captured (milliseconds since Unix epoch).
        timestamp_ms: u128,
        /// Captured line (without trailing newline).
        message: String,
    },
    /// Lifecycle metadata generated by the supervisor.
    Lifecycle {
        /// Logical peer alias.
        alias: Arc<str>,
        /// Event payload.
        event: LifecycleEvent,
        /// Timestamp when the lifecycle change occurred.
        timestamp_ms: u128,
    },
}

/// Lifecycle events reported through the log stream.
#[derive(Debug, Clone)]
pub enum LifecycleEvent {
    /// Peer process successfully started.
    Started { attempt: usize },
    /// Peer process exited (gracefully or otherwise).
    Exited {
        /// Exit code (if available).
        code: Option<i32>,
        /// Whether the status was successful.
        success: bool,
    },
    /// Supervisor scheduled a restart attempt after a crash.
    RestartScheduled {
        /// Restart attempt (1-based).
        attempt: usize,
        /// Delay before the restart in milliseconds.
        delay_ms: u64,
    },
    /// Restart attempt completed successfully.
    RestartSucceeded { attempt: usize },
    /// Restart attempt failed during launch.
    RestartFailed {
        /// Attempt number.
        attempt: usize,
        /// Error message describing the failure.
        error: String,
    },
    /// Restart sequence aborted because the maximum attempts were exhausted.
    RestartAborted { attempt: usize },
    /// Peer was stopped explicitly by the operator.
    StoppedByUser,
}

fn now_ms() -> u128 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or(Duration::ZERO)
        .as_millis()
}

/// Broadcast-backed peer log stream.
#[derive(Clone, Debug)]
pub struct PeerLogStream {
    alias: Arc<str>,
    sender: broadcast::Sender<PeerLogEvent>,
}

impl PeerLogStream {
    /// Create a new log stream for the supplied peer alias.
    pub fn new(alias: impl Into<String>) -> Self {
        let (sender, _) = broadcast::channel(256);
        Self {
            alias: Arc::<str>::from(alias.into()),
            sender,
        }
    }

    /// Logical alias associated with this log stream.
    pub fn alias(&self) -> &str {
        &self.alias
    }

    /// Subscribe to events emitted by the peer log stream.
    pub fn subscribe(&self) -> broadcast::Receiver<PeerLogEvent> {
        self.sender.subscribe()
    }

    /// Emit a stdout/stderr line.
    pub fn emit_line(&self, kind: LogStreamKind, message: impl Into<String>) {
        let _ = self.sender.send(PeerLogEvent::Line {
            alias: self.alias.clone(),
            kind,
            timestamp_ms: now_ms(),
            message: message.into(),
        });
    }

    /// Emit a lifecycle event.
    pub fn emit_lifecycle(&self, event: LifecycleEvent) {
        let _ = self.sender.send(PeerLogEvent::Lifecycle {
            alias: self.alias.clone(),
            event,
            timestamp_ms: now_ms(),
        });
    }
}
