//! Immutable compiler-captured identities for this source owner’s existing codecs.

const CASES: &[crate::captured_schema_tests::Case] = &[
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaAggregateStateCommitmentV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaAggregateStateCommitmentV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaPastaStateCommitmentV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaPastaStateCommitmentV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaPairedProofV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaPairedProofV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaHardwarePlatformClassV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaHardwarePlatformClassV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaHardwareProfileV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaHardwareProfileV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaHardwareCredentialV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaHardwareCredentialV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaCreditOpeningV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaCreditOpeningV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaEncryptedCreditPurposeV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaEncryptedCreditPurposeV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaEncryptedCreditAadV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaEncryptedCreditAadV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaEncryptedCreditEnvelopeV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaEncryptedCreditEnvelopeV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaOperationKindV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaOperationKindV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaLifecycleBindingV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaLifecycleBindingV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaTrustedCommitTimeV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaTrustedCommitTimeV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaMonotonicLeaseV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaMonotonicLeaseV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaCommitEvidenceV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaCommitEvidenceV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaOutboxReservationV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaOutboxReservationV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaHardwareTerminalBodyV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaHardwareTerminalBodyV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaCommitCertificateV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaCommitCertificateV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaPaymentProofV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaPaymentProofV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaRedemptionProofV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaRedemptionProofV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaPaymentRequestV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaPaymentRequestV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaPaymentOutputV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaPaymentOutputV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaPaymentV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaPaymentV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaInboxReceiptV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaInboxReceiptV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaAcknowledgementV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaAcknowledgementV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaMintAuthorizationContextV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaMintAuthorizationContextV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaMintAuthorizationStatementV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaMintAuthorizationStatementV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaMintAuthorizationV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaMintAuthorizationV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaMintCreditStatementV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaMintCreditStatementV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaMintCreditV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaMintCreditV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaRedemptionStatementV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaRedemptionStatementV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaRedemptionVoucherV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaRedemptionVoucherV1",
    ),
    crate::captured_schema_tests::Case::serialize::<super::LiabilityPoolPreimageV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::LiabilityPoolPreimageV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::HardwareProfileIdPreimageV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::HardwareProfileIdPreimageV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::KagemushaPeerCreditContextV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::KagemushaPeerCreditContextV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<super::MintCreditOpeningCommitmentPreimageV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::MintCreditOpeningCommitmentPreimageV1",
    ),
    crate::captured_schema_tests::Case::bidirectional::<
        super::RecipientCredentialCommitmentPreimageV1,
    >("iroha_data_model::kagemusha::kagemusha_v1::RecipientCredentialCommitmentPreimageV1"),
    crate::captured_schema_tests::Case::serialize::<super::HardwareCredentialIdPreimageV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::HardwareCredentialIdPreimageV1",
    ),
    crate::captured_schema_tests::Case::serialize::<super::HardwareCredentialSigningPreimageV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::HardwareCredentialSigningPreimageV1",
    ),
    crate::captured_schema_tests::Case::serialize::<super::InboxReceiptPreimageV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::InboxReceiptPreimageV1",
    ),
    crate::captured_schema_tests::Case::serialize::<super::AcknowledgementSigningPreimageV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::AcknowledgementSigningPreimageV1",
    ),
    crate::captured_schema_tests::Case::serialize::<super::MintCreditIdPreimageV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::MintCreditIdPreimageV1",
    ),
    crate::captured_schema_tests::Case::serialize::<super::MintLifecycleContextPreimageV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::MintLifecycleContextPreimageV1",
    ),
    crate::captured_schema_tests::Case::serialize::<super::RedemptionIdPreimageV1>(
        "iroha_data_model::kagemusha::kagemusha_v1::RedemptionIdPreimageV1",
    ),
];

#[test]
fn captured_codec_schema_identities() {
    for case in CASES {
        case.check();
    }
}
