extends = ["config.base.toml", "run-1-config.layer-0.toml", "run-1-config.layer-1.toml", "run-1-config.layer-2.toml"]

[genesis]
file = "/Users/takemiyamakoto/dev/iroha/integration_tests/tmp/test_network_commit_cert/irohad_test_network_dKM41K/deep_camel/run-1-genesis.nrt"
