//! ADNL-TCP liteclient tests for `iroha_sccp_rpc::ton`.
//!
//! An in-process mock liteserver implements the server side of the ADNL-TCP
//! handshake independently (Ed25519 private scalar, AES-256-CTR, SHA-256
//! framing) and replays `liteServer.*` answers recorded from a TON mainnet
//! liteserver (`fixtures/sccp/rpc/ton/transport`), matching every request
//! byte-for-byte against the recorded one. A handshake and framing vector
//! generated by an independent implementation pins the client's bytes.
//! Synthetic misbehaviour (liteserver errors, stalls, bad checksums, bad
//! packet sizes, foreign query ids, mismatched answers, refused handshakes)
//! drives failover. Nothing here touches the network.

use std::{
    collections::BTreeMap,
    fs,
    io::{Read as _, Write as _},
    net::{IpAddr, SocketAddr, SocketAddrV4, TcpListener, TcpStream},
    num::NonZeroU32,
    path::{Path, PathBuf},
    sync::{
        Arc, Mutex,
        atomic::{AtomicBool, AtomicUsize, Ordering},
    },
    thread::{self, JoinHandle},
    time::{Duration, Instant},
};

use aes::{
    Aes256,
    cipher::{KeyIvInit, StreamCipher},
};
use curve25519_dalek::edwards::CompressedEdwardsY;
use ed25519_dalek::SigningKey;
use iroha_config::parameters::actual::SccpTonLiteserver;
use iroha_sccp_rpc::{
    endpoints::{Backoff, FailoverPolicy, Sleeper},
    ton::{
        AccountId, AdnlConnection, AdnlError, BlockId, BlockIdExt, LiteAnswer, LiteClient,
        LiteClientConfig, LiteClientError, LiteQuery, LiteServer, LiteServerSet, LookupKey, Stage,
        WaitMasterchainSeqno,
        adnl::{
            self, ADNL_MESSAGE_ANSWER, ADNL_MESSAGE_QUERY, AdnlMessage, HandshakeSecrets,
            SessionCiphers, TCP_PING, TCP_PONG,
        },
        schema::{
            self, BlockLink, MasterchainInfo, SHARD_FULL, SignatureSet, TransactionList, method_id,
        },
        tl::{TlReader, TlWriter},
    },
};
use norito::json::Value;
use sha2::{Digest, Sha256};

type Cipher = ctr::Ctr128BE<Aes256>;

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/sccp/rpc/ton/transport")
}

fn fixture_json(name: &str) -> Value {
    let path = fixtures_dir().join(name);
    let text =
        fs::read_to_string(&path).unwrap_or_else(|error| panic!("{}: {error}", path.display()));
    norito::json::parse_value(&text).expect("fixture JSON")
}

fn hex_field(value: &Value, field: &str) -> Vec<u8> {
    hex::decode(
        value
            .get(field)
            .and_then(Value::as_str)
            .unwrap_or_else(|| panic!("missing `{field}`")),
    )
    .expect("hex")
}

fn array<const N: usize>(bytes: &[u8]) -> [u8; N] {
    bytes.try_into().expect("fixed-size field")
}

/// One recorded exchange: the `data` of `liteServer.query` and the raw answer.
#[derive(Clone)]
struct Exchange {
    request: Vec<u8>,
    answer: Vec<u8>,
}

struct Recording {
    index: Value,
    exchanges: BTreeMap<String, Exchange>,
}

impl Recording {
    fn load() -> Self {
        let index = fixture_json("recorded.json");
        let exchanges = index
            .get("exchanges")
            .and_then(Value::as_object)
            .expect("exchanges")
            .iter()
            .map(|(name, entry)| {
                let answer_path = fixtures_dir().join(
                    entry
                        .get("answer")
                        .and_then(Value::as_str)
                        .expect("answer path"),
                );
                let answer = fs::read(&answer_path).expect("answer file");
                assert_eq!(
                    entry
                        .get("answer_bytes")
                        .and_then(Value::as_u64)
                        .and_then(|bytes| usize::try_from(bytes).ok()),
                    Some(answer.len()),
                    "{name}"
                );
                (
                    name.clone(),
                    Exchange {
                        request: hex_field(entry, "request"),
                        answer,
                    },
                )
            })
            .collect();
        Self { index, exchanges }
    }

    fn exchange(&self, name: &str) -> &Exchange {
        self.exchanges
            .get(name)
            .unwrap_or_else(|| panic!("no recorded exchange `{name}`"))
    }

    fn decode<T: LiteAnswer>(&self, name: &str) -> T {
        T::decode_answer(&self.exchange(name).answer).expect("recorded answer decodes")
    }

    fn number(&self, field: &str) -> u64 {
        self.index
            .get(field)
            .and_then(Value::as_u64)
            .unwrap_or_else(|| panic!("missing `{field}`"))
    }

    fn account(&self) -> AccountId {
        let text = self
            .index
            .get("account")
            .and_then(Value::as_str)
            .expect("account");
        let (workchain, address) = text.split_once(':').expect("raw address");
        AccountId {
            workchain: workchain.parse().expect("workchain"),
            address: array(&hex::decode(address).expect("hex")),
        }
    }

    /// Replays by exact request bytes; anything else gets a non-failover
    /// `liteServer.error` naming the request.
    fn handler(self: &Arc<Self>) -> Handler {
        let recording = Arc::clone(self);
        Arc::new(move |data: &[u8]| {
            recording
                .exchanges
                .values()
                .find(|exchange| exchange.request == data)
                .map_or_else(
                    || {
                        Reply::Answer(lite_error(
                            -999,
                            &format!("unrecorded {}", hex::encode(data)),
                        ))
                    },
                    |exchange| Reply::Answer(exchange.answer.clone()),
                )
        })
    }
}

fn lite_error(code: i32, message: &str) -> Vec<u8> {
    let mut writer = TlWriter::boxed(schema::id::ERROR);
    writer.i32(code).bytes(message.as_bytes()).expect("bytes");
    writer.finish()
}

// ---------------------------------------------------------------------------
// Mock liteserver (independent server-side ADNL-TCP)
// ---------------------------------------------------------------------------

/// What the mock does with one query.
#[derive(Clone)]
enum Reply {
    /// Answer with these TL bytes.
    Answer(Vec<u8>),
    /// Send `tcp.ping`, require the client's `tcp.pong`, then answer.
    PingThenAnswer(Vec<u8>),
    /// Answer under a query id the client never sent.
    ForeignQueryId(Vec<u8>),
    /// Answer with a corrupted checksum.
    CorruptChecksum(Vec<u8>),
    /// Send only an encrypted size field announcing this many bytes.
    AnnounceSize(u32),
    /// Answer, then close the connection.
    AnswerThenClose(Vec<u8>),
    /// Send the first half of the answer packet, then close.
    Truncate(Vec<u8>),
    /// Stay silent for this long, then close.
    Stall(Duration),
}

type Handler = Arc<dyn Fn(&[u8]) -> Reply + Send + Sync>;

#[derive(Default)]
struct Stats {
    connections: AtomicUsize,
    handshakes: AtomicUsize,
    pings: AtomicUsize,
    queries: Mutex<Vec<Vec<u8>>>,
    handshake_packets: Mutex<Vec<Vec<u8>>>,
}

impl Stats {
    fn queries(&self) -> Vec<Vec<u8>> {
        self.queries.lock().expect("stats").clone()
    }
}

struct MockLiteServer {
    address: SocketAddr,
    public_key: [u8; 32],
    stats: Arc<Stats>,
    stop: Arc<AtomicBool>,
    accept: Option<JoinHandle<()>>,
}

impl MockLiteServer {
    fn start(key: SigningKey, handler: Handler) -> Self {
        Self::start_with(key, handler, false)
    }

    /// `close_on_handshake`: read the handshake and close without confirming.
    fn start_with(key: SigningKey, handler: Handler, close_on_handshake: bool) -> Self {
        let listener = TcpListener::bind("127.0.0.1:0").expect("bind mock liteserver");
        let address = listener.local_addr().expect("mock address");
        let stats = Arc::new(Stats::default());
        let stop = Arc::new(AtomicBool::new(false));
        let public_key = key.verifying_key().to_bytes();
        let accept = {
            let stats = Arc::clone(&stats);
            let stop = Arc::clone(&stop);
            thread::spawn(move || {
                for stream in listener.incoming() {
                    if stop.load(Ordering::SeqCst) {
                        break;
                    }
                    let Ok(stream) = stream else { continue };
                    stats.connections.fetch_add(1, Ordering::SeqCst);
                    let stats = Arc::clone(&stats);
                    let handler = Arc::clone(&handler);
                    let key = key.clone();
                    thread::spawn(move || {
                        serve(stream, &key, &handler, &stats, close_on_handshake);
                    });
                }
            })
        };
        Self {
            address,
            public_key,
            stats,
            stop,
            accept: Some(accept),
        }
    }

    /// The `<ipv4>:<port>:<base64 key>` configuration entry.
    fn entry(&self) -> String {
        let IpAddr::V4(ip) = self.address.ip() else {
            panic!("the mock listens on IPv4");
        };
        SccpTonLiteserver {
            address: SocketAddrV4::new(ip, self.address.port()),
            public_key: self.public_key,
        }
        .to_string()
    }

    fn server(&self) -> LiteServer {
        LiteServer::new(self.address, self.public_key).expect("mock liteserver")
    }
}

impl Drop for MockLiteServer {
    fn drop(&mut self) {
        self.stop.store(true, Ordering::SeqCst);
        let _ = TcpStream::connect(self.address);
        if let Some(accept) = self.accept.take() {
            let _ = accept.join();
        }
    }
}

/// The server's session: decrypts what the client sends, encrypts replies.
struct ServerSession {
    receive: Cipher,
    send: Cipher,
    nonce_counter: u8,
}

impl ServerSession {
    fn seal(&mut self, payload: &[u8]) -> Vec<u8> {
        self.nonce_counter = self.nonce_counter.wrapping_add(1);
        let nonce = [self.nonce_counter; 32];
        let size = u32::try_from(payload.len() + 64).expect("packet size");
        let mut packet = size.to_le_bytes().to_vec();
        packet.extend_from_slice(&nonce);
        packet.extend_from_slice(payload);
        let checksum = Sha256::digest(&packet[4..]);
        packet.extend_from_slice(&checksum);
        self.send.apply_keystream(&mut packet);
        packet
    }

    fn open(&mut self, stream: &mut TcpStream) -> Option<Vec<u8>> {
        let mut size = [0_u8; 4];
        stream.read_exact(&mut size).ok()?;
        self.receive.apply_keystream(&mut size);
        let size = usize::try_from(u32::from_le_bytes(size)).expect("size");
        assert!((64..=1 << 24).contains(&size), "client packet size {size}");
        let mut body = vec![0_u8; size];
        stream.read_exact(&mut body).ok()?;
        self.receive.apply_keystream(&mut body);
        let (content, checksum) = body.split_at(size - 32);
        assert_eq!(
            Sha256::digest(content).as_slice(),
            checksum,
            "client checksum"
        );
        Some(content[32..].to_vec())
    }
}

/// The server half of the handshake, derived from the Ed25519 private scalar.
fn accept_handshake(packet: &[u8; 256], key: &SigningKey) -> Option<ServerSession> {
    let mut id_preimage = adnl::PUB_ED25519.to_le_bytes().to_vec();
    id_preimage.extend_from_slice(key.verifying_key().as_bytes());
    if packet[..32] != Sha256::digest(&id_preimage)[..] {
        return None;
    }
    let client = CompressedEdwardsY(array(&packet[32..64]))
        .decompress()?
        .to_montgomery();
    let shared = client.mul_clamped(key.to_scalar_bytes()).to_bytes();
    let hash = &packet[64..96];
    let mut handshake_key = [0_u8; 32];
    handshake_key[..16].copy_from_slice(&shared[..16]);
    handshake_key[16..].copy_from_slice(&hash[16..]);
    let mut iv = [0_u8; 16];
    iv[..4].copy_from_slice(&hash[..4]);
    iv[4..].copy_from_slice(&shared[20..]);
    let mut params = packet[96..].to_vec();
    Cipher::new(&handshake_key.into(), &iv.into()).apply_keystream(&mut params);
    assert_eq!(Sha256::digest(&params).as_slice(), hash, "params hash");
    let cipher = |key: &[u8], iv: &[u8]| {
        Cipher::new(
            &<[u8; 32]>::try_from(key).expect("key").into(),
            &<[u8; 16]>::try_from(iv).expect("iv").into(),
        )
    };
    Some(ServerSession {
        receive: cipher(&params[32..64], &params[80..96]),
        send: cipher(&params[0..32], &params[64..80]),
        nonce_counter: 0,
    })
}

fn serve(
    mut stream: TcpStream,
    key: &SigningKey,
    handler: &Handler,
    stats: &Stats,
    close_on_handshake: bool,
) {
    let _ = stream.set_nonblocking(false);
    let mut packet = [0_u8; 256];
    if stream.read_exact(&mut packet).is_err() {
        return;
    }
    stats
        .handshake_packets
        .lock()
        .expect("stats")
        .push(packet.to_vec());
    if close_on_handshake {
        return;
    }
    // A handshake for another key is dropped, as a liteserver does.
    let Some(mut session) = accept_handshake(&packet, key) else {
        return;
    };
    stats.handshakes.fetch_add(1, Ordering::SeqCst);
    if stream.write_all(&session.seal(&[])).is_err() {
        return;
    }
    while let Some(payload) = session.open(&mut stream) {
        let mut reader = TlReader::new(&payload);
        match reader.u32().expect("constructor") {
            TCP_PING => {
                stats.pings.fetch_add(1, Ordering::SeqCst);
                let random_id = reader.i64().expect("ping id");
                let _ = stream.write_all(&session.seal(&adnl::encode_ping(TCP_PONG, random_id)));
            }
            ADNL_MESSAGE_QUERY => {
                let query_id = reader.int256().expect("query id");
                let query = reader.bytes().expect("query");
                reader.finish().expect("one query");
                let (wait, request) = schema::unwrap_query(query).expect("liteServer.query");
                let mut data = Vec::new();
                if let Some(wait) = wait {
                    data.extend_from_slice(&schema::id::WAIT_MASTERCHAIN_SEQNO.to_le_bytes());
                    data.extend_from_slice(&wait.seqno.to_le_bytes());
                    data.extend_from_slice(&wait.timeout_ms.to_le_bytes());
                }
                data.extend_from_slice(&request);
                stats.queries.lock().expect("stats").push(data.clone());
                if !reply(&mut stream, &mut session, &query_id, handler(&data)) {
                    return;
                }
            }
            other => panic!("unexpected client message {other:#x}"),
        }
    }
}

fn answer_message(query_id: &[u8; 32], answer: &[u8]) -> Vec<u8> {
    let mut writer = TlWriter::boxed(ADNL_MESSAGE_ANSWER);
    writer.int256(query_id).bytes(answer).expect("bytes");
    writer.finish()
}

/// Acts out one reply; returns whether the connection stays open.
fn reply(
    stream: &mut TcpStream,
    session: &mut ServerSession,
    query_id: &[u8; 32],
    reply: Reply,
) -> bool {
    match reply {
        Reply::Answer(answer) => stream
            .write_all(&session.seal(&answer_message(query_id, &answer)))
            .is_ok(),
        Reply::PingThenAnswer(answer) => {
            let _ = stream.write_all(&session.seal(&adnl::encode_ping(TCP_PING, 4242)));
            let pong = session.open(stream).expect("client pong");
            assert_eq!(pong, adnl::encode_ping(TCP_PONG, 4242));
            stream
                .write_all(&session.seal(&answer_message(query_id, &answer)))
                .is_ok()
        }
        Reply::ForeignQueryId(answer) => {
            let _ = stream.write_all(&session.seal(&answer_message(&[0xEE; 32], &answer)));
            true
        }
        Reply::CorruptChecksum(answer) => {
            let mut packet = session.seal(&answer_message(query_id, &answer));
            let last = packet.len() - 1;
            packet[last] ^= 0x80;
            let _ = stream.write_all(&packet);
            true
        }
        Reply::AnnounceSize(size) => {
            let mut field = size.to_le_bytes();
            session.send.apply_keystream(&mut field);
            let _ = stream.write_all(&field);
            thread::sleep(Duration::from_millis(200));
            false
        }
        Reply::AnswerThenClose(answer) => {
            let _ = stream.write_all(&session.seal(&answer_message(query_id, &answer)));
            false
        }
        Reply::Truncate(answer) => {
            let packet = session.seal(&answer_message(query_id, &answer));
            let _ = stream.write_all(&packet[..packet.len() / 2]);
            false
        }
        Reply::Stall(duration) => {
            thread::sleep(duration);
            false
        }
    }
}

fn signing_key(label: &str) -> SigningKey {
    SigningKey::from_bytes(&Sha256::digest(label.as_bytes()).into())
}

// ---------------------------------------------------------------------------
// Client helpers
// ---------------------------------------------------------------------------

#[derive(Default)]
struct RecordingSleeper(Mutex<Vec<Duration>>);

impl Sleeper for RecordingSleeper {
    fn sleep(&self, duration: Duration) {
        self.0.lock().expect("sleeper").push(duration);
    }
}

fn config(request_timeout: Duration) -> LiteClientConfig {
    LiteClientConfig {
        connect_timeout: Duration::from_secs(5),
        request_timeout,
        keepalive_interval: Duration::from_secs(90),
        ..LiteClientConfig::default()
    }
}

fn policy(rounds: u32) -> FailoverPolicy {
    FailoverPolicy::new(
        NonZeroU32::new(rounds).expect("nonzero"),
        Backoff::new(Duration::from_millis(1), Duration::from_millis(2), 5),
    )
}

fn client(servers: &[&MockLiteServer], config: LiteClientConfig, rounds: u32) -> LiteClient {
    let set = LiteServerSet::new(servers.iter().map(|server| server.server())).expect("servers");
    LiteClient::new(set, config, policy(rounds)).with_sleeper(Arc::new(RecordingSleeper::default()))
}

fn replay_server(recording: &Arc<Recording>, label: &str) -> MockLiteServer {
    MockLiteServer::start(signing_key(label), recording.handler())
}

fn masterchain_block(recording: &Recording) -> BlockIdExt {
    recording
        .decode::<schema::BlockHeader>("lookup_block_seqno")
        .id
}

fn key_block(recording: &Recording) -> BlockIdExt {
    recording
        .decode::<schema::BlockHeader>("lookup_key_block_seqno")
        .id
}

// ---------------------------------------------------------------------------
// Handshake vector
// ---------------------------------------------------------------------------

fn vector_secrets(vector: &Value) -> HandshakeSecrets {
    HandshakeSecrets::from_parts(
        array(&hex_field(vector, "client_ephemeral_scalar")),
        array(&hex_field(vector, "handshake_params")),
    )
}

#[test]
fn handshake_vector_matches_the_independent_reference() {
    let vector = fixture_json("adnl_handshake_vector.json");
    let seed: [u8; 32] = array(&hex_field(&vector, "server_ed25519_seed"));
    let server_public: [u8; 32] = array(&hex_field(&vector, "server_ed25519_public"));
    assert_eq!(
        SigningKey::from_bytes(&seed).verifying_key().to_bytes(),
        server_public
    );
    assert_eq!(
        adnl::key_id(&server_public).to_vec(),
        hex_field(&vector, "server_key_id")
    );
    let secrets = vector_secrets(&vector);
    assert_eq!(
        secrets.client_public().to_vec(),
        hex_field(&vector, "client_ed25519_public")
    );
    assert_eq!(
        secrets
            .shared_secret(&server_public)
            .expect("shared")
            .as_bytes()
            .to_vec(),
        hex_field(&vector, "shared_secret")
    );
    let handshake = adnl::client_handshake(&server_public, &secrets).expect("handshake");
    assert_eq!(
        handshake.packet.to_vec(),
        hex_field(&vector, "handshake_packet")
    );
}

#[test]
fn framing_vector_matches_the_independent_reference() {
    let vector = fixture_json("adnl_handshake_vector.json");
    let server_public: [u8; 32] = array(&hex_field(&vector, "server_ed25519_public"));
    let handshake =
        adnl::client_handshake(&server_public, &vector_secrets(&vector)).expect("handshake");

    // The first client packet: a getMasterchainInfo query.
    let query_id: [u8; 32] = array(&hex_field(&vector, "query_id"));
    let request = LiteQuery::GetMasterchainInfo.encode().expect("request");
    let payload = adnl::encode_query(
        &query_id,
        &schema::wrap_query(&request, None).expect("wrap"),
    )
    .expect("query");
    assert_eq!(payload, hex_field(&vector, "client_frame_payload"));
    let mut ciphers = handshake.ciphers;
    let limit = adnl::DEFAULT_MAX_PACKET_BYTES;
    let sealed = ciphers
        .seal(
            &array(&hex_field(&vector, "client_frame_nonce")),
            &payload,
            limit,
        )
        .expect("seal");
    assert_eq!(sealed, hex_field(&vector, "client_frame_encrypted"));

    // The server's confirmation and answer, on one continuous stream.
    let mut incoming = std::io::Cursor::new(hex_field(&vector, "server_frames_encrypted"));
    assert_eq!(
        ciphers.open(&mut incoming, limit).expect("confirmation"),
        Vec::<u8>::new()
    );
    let answer_payload = ciphers.open(&mut incoming, limit).expect("answer");
    let payloads = vector
        .get("server_frame_payloads")
        .and_then(Value::as_array)
        .expect("payloads");
    assert_eq!(
        hex::encode(&answer_payload),
        payloads[1].as_str().expect("hex")
    );
    let AdnlMessage::Answer {
        query_id: answered,
        answer,
    } = AdnlMessage::parse(&answer_payload).expect("answer message")
    else {
        panic!("expected an answer");
    };
    assert_eq!(answered, query_id);
    let info = MasterchainInfo::decode_answer(&answer).expect("masterchain info");
    assert!(info.last.is_masterchain());

    // Keep-alive continues both streams.
    let random_id = vector
        .get("ping_random_id")
        .and_then(Value::as_i64)
        .expect("ping id");
    let ping = ciphers
        .seal(
            &array(&hex_field(&vector, "client_ping_nonce")),
            &adnl::encode_ping(TCP_PING, random_id),
            limit,
        )
        .expect("ping");
    assert_eq!(ping, hex_field(&vector, "client_ping_encrypted"));
    let reply = ciphers
        .open(
            &mut std::io::Cursor::new(hex_field(&vector, "server_pong_encrypted")),
            limit,
        )
        .expect("pong");
    assert_eq!(
        AdnlMessage::parse(&reply).expect("pong"),
        AdnlMessage::Pong(random_id)
    );

    // The server side reads the same session with swapped streams.
    let mut server = SessionCiphers::server(&array(&hex_field(&vector, "handshake_params")));
    assert_eq!(
        server
            .open(
                &mut std::io::Cursor::new(hex_field(&vector, "client_frame_encrypted")),
                limit
            )
            .expect("server reads the query"),
        payload
    );
}

#[test]
fn handshake_vector_drives_a_session_end_to_end() {
    let vector = fixture_json("adnl_handshake_vector.json");
    let seed: [u8; 32] = array(&hex_field(&vector, "server_ed25519_seed"));
    let recording = Arc::new(Recording::load());
    let server = MockLiteServer::start(SigningKey::from_bytes(&seed), recording.handler());
    let secrets = vector_secrets(&vector);
    let deadline = Instant::now() + Duration::from_secs(10);
    let mut connection = AdnlConnection::connect_with_secrets(
        server.address,
        &server.public_key,
        &secrets,
        deadline,
        adnl::DEFAULT_MAX_PACKET_BYTES,
    )
    .expect("handshake with the vector secrets");
    assert_eq!(
        server.stats.handshake_packets.lock().expect("stats")[0],
        hex_field(&vector, "handshake_packet")
    );
    let request = LiteQuery::GetMasterchainInfo.encode().expect("request");
    let answer = connection
        .query(&schema::wrap_query(&request, None).expect("wrap"), deadline)
        .expect("answer");
    assert_eq!(answer, recording.exchange("get_masterchain_info").answer);
    connection.ping(deadline).expect("pong");
    assert_eq!(server.stats.pings.load(Ordering::SeqCst), 1);
}

// ---------------------------------------------------------------------------
// Recorded mainnet exchanges
// ---------------------------------------------------------------------------

/// Checks that every query the mock saw matched a recording byte for byte,
/// over one session.
fn assert_replayed(
    server: &MockLiteServer,
    recording: &Recording,
    client: &LiteClient,
    count: usize,
) {
    let queries = server.stats.queries();
    assert_eq!(queries.len(), count);
    assert!(queries.iter().all(|query| {
        recording
            .exchanges
            .values()
            .any(|exchange| &exchange.request == query)
    }));
    assert_eq!(server.stats.connections.load(Ordering::SeqCst), 1);
    assert!(client.is_connected());
}

#[test]
fn recorded_lookups_replay_through_typed_queries() {
    let recording = Arc::new(Recording::load());
    let server = replay_server(&recording, "replay lookups");
    let client = client(&[&server], config(Duration::from_secs(10)), 1);

    let info = client.get_masterchain_info().expect("masterchain info");
    assert_eq!(
        u64::from(info.last.seqno),
        recording.number("masterchain_last_seqno")
    );
    assert_eq!(info.init.workchain, -1);

    let seqno = u32::try_from(recording.number("masterchain_block_seqno")).expect("seqno");
    let header = client
        .lookup_block(BlockId::masterchain(seqno), LookupKey::Seqno)
        .expect("lookup by seqno");
    assert_eq!(header.id.seqno, seqno);
    assert!(!header.header_proof.is_empty());
    let block = header.id;

    // By time and by logical time, as recorded.
    let utime_request = &recording.exchange("lookup_block_utime").request;
    let utime = u32::from_le_bytes(array(&utime_request[24..28]));
    assert_eq!(
        client
            .lookup_block(BlockId::masterchain(0), LookupKey::Utime(utime))
            .expect("lookup by utime")
            .id,
        block
    );
    let lt_request = &recording.exchange("lookup_block_lt").request;
    let lt = u64::from_le_bytes(array(&lt_request[24..32]));
    assert_eq!(
        client
            .lookup_block(BlockId::masterchain(0), LookupKey::Lt(lt))
            .expect("lookup by lt")
            .id,
        block
    );
    assert_eq!(client.get_block_header(block, 0).expect("header").id, block);
    assert_replayed(&server, &recording, &client, 5);
}

#[test]
fn recorded_proofs_replay_through_typed_queries() {
    let recording = Arc::new(Recording::load());
    let server = replay_server(&recording, "replay proofs");
    let client = client(&[&server], config(Duration::from_secs(10)), 1);
    let block = masterchain_block(&recording);

    // A key-block hop and the proofs between the key block and the block.
    let key = key_block(&recording);
    let previous_key = recording
        .decode::<schema::BlockHeader>("lookup_prev_key_block_seqno")
        .id;
    assert_eq!(
        u64::from(previous_key.seqno),
        recording.number("prev_key_block_seqno")
    );
    let hop = client
        .get_block_proof(previous_key, Some(key))
        .expect("key-block hop");
    assert!(hop.complete);
    assert_eq!(hop.steps.len(), 1);
    let BlockLink::Forward(link) = &hop.steps[0] else {
        panic!("a key-block hop is a forward link");
    };
    assert!(link.to_key_block);
    assert_eq!((link.from, link.to), (previous_key, key));
    // Mainnet signs under simplex consensus; the set names the session of the
    // key block's catchain.
    let SignatureSet::Simplex(simplex) = &link.signatures else {
        panic!("mainnet key blocks carry simplex signature sets");
    };
    assert!(!simplex.candidate.is_empty());
    assert_ne!(simplex.session_id, [0; 32]);
    assert!(!link.signatures.signatures().is_empty());
    assert!(
        link.signatures
            .signatures()
            .iter()
            .all(|signature| signature.signature.len() == 64)
    );
    let forward = client
        .get_block_proof(key, Some(block))
        .expect("forward proof");
    assert_eq!(forward.to, block);
    let backward = client
        .get_block_proof(block, Some(key))
        .expect("backward proof");
    let BlockLink::Back(back) = &backward.steps[0] else {
        panic!("a proof to an older block is a back link");
    };
    assert!(back.to_key_block);
    assert!(!back.state_proof.is_empty());

    let data = client.get_block(block).expect("block");
    assert_eq!(&data.data[..4], &[0xb5, 0xee, 0x9c, 0x72]);
    let config = client
        .get_config_params(0, key, vec![34, 28, 15])
        .expect("config");
    assert!(!config.config_proof.is_empty());
    assert_replayed(&server, &recording, &client, 5);
}

#[test]
fn recorded_account_queries_replay_through_typed_queries() {
    let recording = Arc::new(Recording::load());
    let server = replay_server(&recording, "replay accounts");
    let client = client(&[&server], config(Duration::from_secs(10)), 1);
    let block = masterchain_block(&recording);

    let account = recording.account();
    let state = client.get_account_state(block, account).expect("state");
    assert!(!state.state.is_empty());

    // Discovery: the account's recent transactions, then one of them.
    let lt = recording.number("transaction_lt");
    let hash: [u8; 32] = array(&recording.exchange("get_transactions").request[52..84]);
    let list: TransactionList = client
        .get_transactions(3, account, lt, hash)
        .expect("transactions");
    assert_eq!(list.ids.len(), 3);
    assert!(list.ids.iter().all(|id| id.workchain == account.workchain));
    let transaction = client
        .get_one_transaction(list.ids[0], account, lt)
        .expect("transaction");
    assert_eq!(transaction.id, list.ids[0]);
    assert!(!transaction.transaction.is_empty());
    let shard_proof = client
        .get_shard_block_proof(list.ids[0])
        .expect("shard block proof");
    assert!(shard_proof.masterchain_id.is_masterchain());
    assert!(!shard_proof.links.is_empty());

    // A get-method with the result only, and with every optional part.
    let jetton_data = method_id("get_jetton_data");
    assert_eq!(jetton_data, recording.number("method_id_get_jetton_data"));
    let result = client
        .run_smc_method(
            4,
            block,
            account,
            jetton_data,
            schema::EMPTY_VM_STACK_BOC.to_vec(),
        )
        .expect("get-method");
    assert_eq!(result.exit_code, 0);
    assert!(result.result.is_some());
    assert!(result.proof.is_none());
    let full = client
        .run_smc_method(
            0x1F,
            block,
            account,
            jetton_data,
            schema::EMPTY_VM_STACK_BOC.to_vec(),
        )
        .expect("get-method with proofs");
    assert_eq!(full.result, result.result);
    assert!(full.shard_proof.is_some() && full.proof.is_some() && full.state_proof.is_some());
    assert!(full.init_c7.is_some() && full.lib_extras.is_some());

    assert!(client.get_time().expect("time").now > 1_700_000_000);
    assert_replayed(&server, &recording, &client, 7);
}

#[test]
fn raw_answers_are_verbatim_and_waits_are_prefixed() {
    let recording = Arc::new(Recording::load());
    let server = replay_server(&recording, "raw");
    let client = client(&[&server], config(Duration::from_secs(10)), 1);
    let raw = client
        .query_raw(&LiteQuery::GetMasterchainInfo, None)
        .expect("raw answer");
    assert_eq!(raw, recording.exchange("get_masterchain_info").answer);

    let waiting = &recording.exchange("wait_masterchain_seqno_get_time");
    let seqno = u32::from_le_bytes(array(&waiting.request[4..8]));
    let timeout_ms = u32::from_le_bytes(array(&waiting.request[8..12]));
    let wait = WaitMasterchainSeqno { seqno, timeout_ms };
    assert_eq!(
        client
            .query_raw(&LiteQuery::GetTime, Some(wait))
            .expect("raw answer"),
        waiting.answer
    );
    let time: schema::CurrentTime = client
        .query(&LiteQuery::GetTime, Some(wait))
        .expect("typed answer");
    assert!(time.now > 1_700_000_000);
}

#[test]
fn lite_server_errors_are_typed_and_fail_over_by_code() {
    let recording = Arc::new(Recording::load());
    let first = replay_server(&recording, "errors first");
    let second = replay_server(&recording, "errors second");
    let client = client(&[&first, &second], config(Duration::from_secs(10)), 1);

    // A rejected external message is an answer: the second server is not asked.
    let error = client
        .send_message(vec![0, 1, 2])
        .expect_err("rejected message");
    let LiteClientError::LiteServer { error: answer, .. } = &error else {
        panic!("unexpected {error:?}");
    };
    assert_eq!(answer.code, 0);
    assert!(answer.message.contains("cannot deserialize bag-of-cells"));
    assert_eq!(second.stats.connections.load(Ordering::SeqCst), 0);

    // "Not ready" (651) moves on to the next liteserver, which knows no more.
    let missing = &recording.exchange("error_block_not_found").request;
    let seqno = u32::from_le_bytes(array(&missing[20..24]));
    let error = client
        .lookup_block(BlockId::masterchain(seqno), LookupKey::Seqno)
        .expect_err("unknown block");
    let LiteClientError::Exhausted { failures } = &error else {
        panic!("unexpected {error:?}");
    };
    assert_eq!(failures.len(), 2);
    assert_eq!(error.lite_server_error().map(|error| error.code), Some(651));
    assert!(error.to_string().contains("651"));
    // liteServer.error answers keep the sessions open.
    assert_eq!(first.stats.connections.load(Ordering::SeqCst), 1);
    assert_eq!(second.stats.connections.load(Ordering::SeqCst), 1);
}

// ---------------------------------------------------------------------------
// Failover
// ---------------------------------------------------------------------------

#[test]
fn failover_moves_to_the_next_liteserver_and_sticks() {
    let recording = Arc::new(Recording::load());
    let not_ready = MockLiteServer::start(
        signing_key("not ready"),
        Arc::new(|_: &[u8]| Reply::Answer(lite_error(651, "block is not applied"))),
    );
    let healthy = replay_server(&recording, "healthy");
    let client = client(&[&not_ready, &healthy], config(Duration::from_secs(10)), 1);
    let block = masterchain_block(&recording);
    assert_eq!(client.get_block(block).expect("failover").id, block);
    assert_eq!(client.servers().preferred(), 1);
    assert_eq!(not_ready.stats.queries().len(), 1);
    // The next query starts at the liteserver that answered.
    client.get_masterchain_info().expect("preferred server");
    assert_eq!(not_ready.stats.queries().len(), 1);
    assert_eq!(healthy.stats.queries().len(), 2);
    assert_eq!(healthy.stats.connections.load(Ordering::SeqCst), 1);
    // Rotation moves the start back to the first server.
    client.servers().rotate_preferred();
    client.get_masterchain_info().expect("after rotation");
    assert_eq!(not_ready.stats.queries().len(), 2);
}

#[test]
fn timeouts_fail_over_and_drop_the_session() {
    let recording = Arc::new(Recording::load());
    let stalled = MockLiteServer::start(
        signing_key("stalled"),
        Arc::new(|_: &[u8]| Reply::Stall(Duration::from_secs(2))),
    );
    let healthy = replay_server(&recording, "after stall");
    let client = client(&[&stalled, &healthy], config(Duration::from_millis(300)), 1);
    let started = Instant::now();
    let info = client.get_masterchain_info().expect("second liteserver");
    assert!(info.last.is_masterchain());
    assert!(started.elapsed() < Duration::from_secs(2));

    // With the stalled server alone every round times out.
    let alone = self::client(&[&stalled], config(Duration::from_millis(200)), 2);
    let error = alone.get_time().expect_err("stalled");
    let LiteClientError::Exhausted { failures } = &error else {
        panic!("unexpected {error:?}");
    };
    assert_eq!(failures.len(), 2);
    assert!(failures.iter().all(|failure| matches!(
        failure.error,
        LiteClientError::Adnl {
            stage: Stage::Query,
            error: AdnlError::Timeout,
            ..
        }
    )));
    assert!(!alone.is_connected());
}

/// A single-server client whose only attempt fails; returns that failure.
fn only_failure(server: &MockLiteServer, config: LiteClientConfig) -> (LiteClientError, bool) {
    let client = client(&[server], config, 1);
    let error = client.get_time().expect_err("attempt fails");
    let connected = client.is_connected();
    (error.last_failure().clone(), connected)
}

#[test]
fn checksum_and_framing_negatives_break_the_session() {
    let time = {
        let mut writer = TlWriter::boxed(schema::id::CURRENT_TIME);
        writer.u32(1_790_000_000);
        writer.finish()
    };
    let cases: Vec<(Reply, AdnlError, LiteClientConfig)> = vec![
        (
            Reply::CorruptChecksum(time.clone()),
            AdnlError::Checksum,
            config(Duration::from_secs(5)),
        ),
        (
            Reply::AnnounceSize(10),
            AdnlError::PacketTooShort { size: 10 },
            config(Duration::from_secs(5)),
        ),
        (
            Reply::AnnounceSize(1 << 20),
            AdnlError::PacketTooLarge {
                size: 1 << 20,
                limit: 4096,
            },
            config(Duration::from_secs(5)).with_max_packet_bytes(4096),
        ),
        (
            Reply::Truncate(time.clone()),
            AdnlError::Closed,
            config(Duration::from_secs(5)),
        ),
    ];
    for (index, (behaviour, expected, config)) in cases.into_iter().enumerate() {
        let server = MockLiteServer::start(
            signing_key(&format!("framing {index}")),
            Arc::new(move |_: &[u8]| behaviour.clone()),
        );
        let (error, connected) = only_failure(&server, config);
        match (&error, &expected) {
            (LiteClientError::Adnl { stage, error, .. }, expected) => {
                assert_eq!(*stage, Stage::Query, "case {index}");
                assert_eq!(error, expected, "case {index}");
                assert!(!connected, "case {index}: the session must be dropped");
            }
            _ => panic!("case {index}: unexpected {error:?}"),
        }
    }

    // An answer to a query the client never sent.
    let foreign = MockLiteServer::start(
        signing_key("foreign query id"),
        Arc::new(move |_: &[u8]| Reply::ForeignQueryId(time.clone())),
    );
    let (error, connected) = only_failure(&foreign, config(Duration::from_secs(5)));
    assert!(
        matches!(
            error,
            LiteClientError::Adnl {
                error: AdnlError::Protocol(_),
                ..
            }
        ),
        "{error:?}"
    );
    assert!(!connected);
}

#[test]
fn refused_handshakes_fail_over() {
    let recording = Arc::new(Recording::load());
    // The server holds another key than the one configured: it drops the
    // handshake for the unknown key id.
    let impostor = MockLiteServer::start(signing_key("real key"), recording.handler());
    let wrong_key = LiteServer::new(
        impostor.address,
        signing_key("configured key").verifying_key().to_bytes(),
    )
    .expect("server");
    // A server that reads the handshake and closes.
    let closing = MockLiteServer::start_with(signing_key("closing"), recording.handler(), true);
    let healthy = replay_server(&recording, "healthy after refusals");
    let servers =
        LiteServerSet::new([wrong_key, closing.server(), healthy.server()]).expect("servers");
    let client = LiteClient::new(servers, config(Duration::from_secs(5)), policy(1));
    client.get_masterchain_info().expect("third liteserver");
    assert_eq!(client.servers().preferred(), 2);
    assert_eq!(impostor.stats.handshakes.load(Ordering::SeqCst), 0);
    assert_eq!(
        impostor
            .stats
            .handshake_packets
            .lock()
            .expect("stats")
            .len(),
        1
    );
    assert_eq!(closing.stats.handshakes.load(Ordering::SeqCst), 0);

    // Alone, a refused handshake is a connect-stage failure.
    let alone = LiteClient::new(
        LiteServerSet::parse(&[&closing.entry()]).expect("servers"),
        config(Duration::from_secs(5)),
        policy(1),
    );
    let error = alone.get_time().expect_err("refused");
    assert!(
        matches!(
            error.last_failure(),
            LiteClientError::Adnl {
                stage: Stage::Connect,
                error: AdnlError::Closed,
                ..
            }
        ),
        "{error:?}"
    );
}

#[test]
fn mismatched_answers_fail_over() {
    let recording = Arc::new(Recording::load());
    let key_header = recording.exchange("lookup_key_block_seqno").answer.clone();
    let wrong_type = recording.exchange("get_masterchain_info").answer.clone();
    // Answers `getBlock` with masterchain info and everything else with the
    // key block's header.
    let liar = MockLiteServer::start(
        signing_key("liar"),
        Arc::new(move |data: &[u8]| {
            if data[..4] == schema::id::GET_BLOCK.to_le_bytes() {
                Reply::Answer(wrong_type.clone())
            } else {
                Reply::Answer(key_header.clone())
            }
        }),
    );
    let healthy = replay_server(&recording, "honest");
    let client = client(&[&liar, &healthy], config(Duration::from_secs(5)), 1);
    let block = masterchain_block(&recording);
    assert_eq!(client.get_block_header(block, 0).expect("header").id, block);
    client.servers().rotate_preferred();
    assert_eq!(client.get_block(block).expect("block").id, block);

    let liar_alone = self::client(&[&liar], config(Duration::from_secs(5)), 1);
    let error = liar_alone
        .get_block_header(block, 0)
        .expect_err("another block");
    assert!(
        matches!(
            error.last_failure(),
            LiteClientError::InvalidResponse { detail, .. } if detail.contains("another block")
        ),
        "{error:?}"
    );
    let error = liar_alone.get_block(block).expect_err("wrong answer type");
    assert!(
        matches!(
            error.last_failure(),
            LiteClientError::InvalidResponse { detail, .. } if detail.contains("liteServer.blockData")
        ),
        "{error:?}"
    );
    // A malformed answer does not break the session.
    assert!(liar_alone.is_connected());
}

// ---------------------------------------------------------------------------
// Keep-alive
// ---------------------------------------------------------------------------

#[test]
fn keep_alive_probes_idle_sessions_and_reconnects() {
    let recording = Arc::new(Recording::load());
    let server = replay_server(&recording, "keep-alive");
    let eager = LiteClientConfig {
        keepalive_interval: Duration::ZERO,
        ..config(Duration::from_secs(5))
    };
    let client = client(&[&server], eager, 1);
    assert!(!client.keep_alive().expect("no session"));
    client.get_masterchain_info().expect("first query");
    assert_eq!(server.stats.pings.load(Ordering::SeqCst), 0);
    // Reusing an idle session probes it first.
    client.get_time().expect("second query");
    assert_eq!(server.stats.pings.load(Ordering::SeqCst), 1);
    assert!(client.keep_alive().expect("probe"));
    assert_eq!(server.stats.pings.load(Ordering::SeqCst), 2);
    assert_eq!(server.stats.connections.load(Ordering::SeqCst), 1);
    client.disconnect();
    assert!(!client.is_connected());
    client.get_time().expect("reconnects");
    assert_eq!(server.stats.connections.load(Ordering::SeqCst), 2);

    // A session the server closed fails its probe and is replaced.
    let info = recording.exchange("get_masterchain_info").answer.clone();
    let closing = MockLiteServer::start(
        signing_key("closes after answering"),
        Arc::new(move |_: &[u8]| Reply::AnswerThenClose(info.clone())),
    );
    let client = self::client(&[&closing], eager, 1);
    client.get_masterchain_info().expect("first session");
    client.get_masterchain_info().expect("second session");
    assert_eq!(closing.stats.connections.load(Ordering::SeqCst), 2);
    let _ = client.get_masterchain_info();
    let error = client.keep_alive().expect_err("closed session");
    assert!(matches!(
        error,
        LiteClientError::Adnl {
            stage: Stage::KeepAlive,
            ..
        }
    ));
    assert!(!client.is_connected());
}

#[test]
fn server_pings_during_a_query_are_answered() {
    let recording = Arc::new(Recording::load());
    let info = recording.exchange("get_masterchain_info").answer.clone();
    let server = MockLiteServer::start(
        signing_key("pinging server"),
        Arc::new(move |_: &[u8]| Reply::PingThenAnswer(info.clone())),
    );
    let client = client(&[&server], config(Duration::from_secs(5)), 1);
    let info = client.get_masterchain_info().expect("answer after ping");
    assert_eq!(
        u64::from(info.last.seqno),
        recording.number("masterchain_last_seqno")
    );
}

#[test]
fn configured_lists_reach_the_mock() {
    let recording = Arc::new(Recording::load());
    let server = replay_server(&recording, "configured");
    let set = LiteServerSet::parse(&[&server.entry()]).expect("entry");
    assert_eq!(set.servers()[0].address(), server.address);
    assert_eq!(set.servers()[0].key_id(), &adnl::key_id(&server.public_key));
    let client = LiteClient::new(set, config(Duration::from_secs(5)), policy(1));
    let shard = BlockIdExt {
        workchain: 0,
        shard: SHARD_FULL,
        seqno: 1,
        root_hash: [0; 32],
        file_hash: [0; 32],
    };
    assert!(matches!(
        client.get_block_proof(shard, None),
        Err(LiteClientError::InvalidRequest(_))
    ));
    assert_eq!(server.stats.connections.load(Ordering::SeqCst), 0);
    client.get_masterchain_info().expect("answer");
}
