//! Bounded balanced production of complete source intervals using original keys.
//!
//! The installed leaf sequence fixes the complete tree. Each merge is imported
//! against its compiled source and exact child keys. Only verifier metadata is
//! retained; original proving tables are loaded for the active node. Odd levels
//! retain their last node without padding or inventing a proof. The terminal
//! relation must still require the complete
//! program boundaries and join this interval to its other authenticated sources.

use std::collections::BTreeMap;

use ff::PrimeField;
use iroha_pasta::{Ep, Eq, Fp};
use iroha_plonk::{
    ProverConfig, ProverRandomness, keys::pk::artifact::ReadConfig, pcs::ipa::PinnedParams,
};
use iroha_plonk_recursion::FoldConfig;

use super::{
    SourceMergeCircuit, SourceNodeEvidence, SourcePairPlan, SourceVerifier,
    checkpoint::{self, ProofCheckpointStore},
    producer::{Error, OriginalArtifact, Prover},
};

/// Maximum leaves in one original bounded arithmetic or byte-scan program.
/// Native chain history is accumulated separately and is not limited by this bound.
pub const MAX_PROGRAM_LEAVES: usize = 4096;

/// Exact source-qualified wrapper identity for original merge-artifact lookup.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct SourceIdentity {
    /// Exact canonical descriptor identity.
    pub descriptor: [u8; 32],
    /// Original fixed-key transcript identity under that descriptor.
    pub key: [u8; 32],
}
impl SourceIdentity {
    fn of(source: &SourceVerifier) -> Result<Self, Error> {
        Ok(Self {
            descriptor: *source.verifier.binding().digest(),
            key: source
                .key
                .kagemusha_digest(source.verifier.binding())
                .map_err(|_| Error::Artifact)?
                .to_repr(),
        })
    }
}

/// Original artifact loaded by the installation owner for one active node.
/// The loader can read it from storage; the tree does not retain these buffers.
/// The loader must bound its storage reads before allocating these vectors;
/// import limits check the returned originals and cannot limit caller allocation.
#[derive(Clone, Debug)]
pub struct OriginalBytes {
    /// Canonical original descriptor bytes.
    pub descriptor: Vec<u8>,
    /// Independently selected canonical original verifying key.
    pub verifying_key: Vec<u8>,
    /// Original proving tables, never generated by the runtime producer.
    pub proving_key: Vec<u8>,
}
impl OriginalBytes {
    fn borrowed(&self) -> OriginalArtifact<'_> {
        OriginalArtifact {
            descriptor: &self.descriptor,
            verifying_key: &self.verifying_key,
            proving_key: &self.proving_key,
        }
    }
}

/// Original source and mandatory wrapper artifacts from the installation owner.
#[derive(Clone, Debug)]
pub struct OriginalPair {
    /// Original Eq source tables and independently selected descriptor/key.
    pub source: OriginalBytes,
    /// Original Ep wrapper tables and independently selected descriptor/key.
    pub wrapper: OriginalBytes,
}
impl OriginalPair {
    fn byte_length(&self) -> Result<usize, Error> {
        [&self.source, &self.wrapper]
            .into_iter()
            .flat_map(|a| {
                [
                    a.descriptor.len(),
                    a.verifying_key.len(),
                    a.proving_key.len(),
                ]
            })
            .try_fold(0usize, |total, n| {
                total.checked_add(n).ok_or(Error::Artifact)
            })
    }
}

/// Explicit installation bounds for the complete tree, in addition to each key.
#[derive(Clone, Copy, Debug)]
pub struct TreeImportConfig {
    /// Bounds and working-cache policy for an individual original key import.
    pub key: ReadConfig,
    /// Maximum distinct ordered child-key pairs retained as verifier metadata.
    pub maximum_keys: usize,
    /// Maximum total original descriptor/VK/PK bytes across distinct pairs.
    /// This is an artifact-inventory bound, not a process-memory measurement.
    pub maximum_original_bytes: usize,
}

/// Independent proof randomness and fold salts for one actual tree node.
#[derive(Debug)]
pub struct NodeRandomness<'a> {
    /// Salt for the hard four-Pallas fold inside the source circuit.
    pub inner_salt: Fp,
    /// Salt for the mandatory full-Vesta wrapper fold.
    pub outer_salt: [u8; 32],
    /// Actual source proof randomness.
    pub source: ProverRandomness<'a>,
    /// Actual wrapper proof randomness.
    pub wrapper: ProverRandomness<'a>,
}
struct Merge {
    children: [usize; 2],
    plan: SourcePairPlan,
    identity: [SourceIdentity; 2],
    source: SourceVerifier,
}

/// Immutable original-key tree for one complete fixed leaf sequence.
/// It supplies interval evidence only, never standalone monetary authority.
pub struct IntervalTree {
    leaf_count: usize,
    merges: Vec<Merge>,
    root: SourceVerifier,
    pallas: PinnedParams<Ep>,
    vesta: PinnedParams<Eq>,
    import: ReadConfig,
}
fn topology(leaves: usize) -> Result<Vec<[usize; 2]>, Error> {
    if !(2..=MAX_PROGRAM_LEAVES).contains(&leaves) {
        return Err(Error::Input);
    }
    let mut level: Vec<usize> = (0..leaves).collect();
    let mut merges = Vec::with_capacity(leaves - 1);
    while level.len() > 1 {
        let mut next = Vec::with_capacity(level.len().div_ceil(2));
        for pair in level.chunks(2) {
            if pair.len() == 1 {
                next.push(pair[0]);
            } else {
                next.push(leaves + merges.len());
                merges.push([pair[0], pair[1]]);
            }
        }
        level = next;
    }
    Ok(merges)
}
impl IntervalTree {
    /// Import the exact complete balanced tree, reusing repeated child-key pairs.
    /// `artifacts` reads independently installed originals for the ordered child
    /// identities. Every returned key is checked against the compiled source;
    /// no runtime key generation, padding leaves or unqualified keys are accepted.
    /// # Errors
    /// Wrong bounds, parameter profile, artifact/source/key mismatch or resource refusal.
    pub fn from_original_artifacts(
        leaf_sources: Vec<SourceVerifier>,
        mut artifacts: impl FnMut([SourceIdentity; 2]) -> Result<OriginalPair, Error>,
        pallas: PinnedParams<Ep>,
        vesta: PinnedParams<Eq>,
        config: TreeImportConfig,
    ) -> Result<Self, Error> {
        if pallas.k() != 16
            || vesta.k() != 16
            || config.maximum_keys == 0
            || config.maximum_original_bytes == 0
        {
            return Err(Error::Artifact);
        }
        let leaf_count = leaf_sources.len();
        let shape = topology(leaf_count)?;
        let mut sources = leaf_sources;
        let mut cache = BTreeMap::<[SourceIdentity; 2], SourceVerifier>::new();
        let mut original_bytes = 0usize;
        let mut merges = Vec::with_capacity(shape.len());
        for children in shape {
            let selected = children.map(|i| sources[i].clone());
            let identity = [
                SourceIdentity::of(&selected[0])?,
                SourceIdentity::of(&selected[1])?,
            ];
            let plan = SourcePairPlan::new(selected, &pallas).map_err(|_| Error::Artifact)?;
            let source = if let Some(source) = cache.get(&identity) {
                source.clone()
            } else {
                if cache.len() >= config.maximum_keys {
                    return Err(Error::Artifact);
                }
                let blank =
                    SourceMergeCircuit::for_source(plan.clone()).map_err(|_| Error::Artifact)?;
                let original = artifacts(identity)?;
                original_bytes = original_bytes
                    .checked_add(original.byte_length()?)
                    .filter(|n| *n <= config.maximum_original_bytes)
                    .ok_or(Error::Artifact)?;
                let prover = Prover::from_original_artifacts(
                    &blank,
                    original.source.borrowed(),
                    original.wrapper.borrowed(),
                    pallas.clone(),
                    vesta.clone(),
                    config.key,
                )?;
                let source = prover.qualified_source()?;
                cache.insert(identity, source.clone());
                source
            };
            sources.push(source.clone());
            merges.push(Merge {
                children,
                plan,
                identity,
                source,
            });
        }
        let root = sources.pop().ok_or(Error::Artifact)?;
        Ok(Self {
            leaf_count,
            merges,
            root,
            pallas,
            vesta,
            import: config.key,
        })
    }
    /// Exact original number of leaves; every one must be supplied in order.
    pub const fn leaf_count(&self) -> usize {
        self.leaf_count
    }
    /// Original source-qualified root to install in the enclosing relation.
    pub fn qualified_source(&self) -> SourceVerifier {
        self.root.clone()
    }
    /// Prove every real merge and retain all carried claims on both curves.
    /// Each input proof is fully checked under its originally installed leaf key
    /// when consumed. No native decoded result or accepted boolean replaces it.
    /// Consumed child evidence is released, bounding the live proof working set.
    /// Each node reloads and qualifies its original tables, checks the same mounted
    /// source identity, proves, and releases those tables before the next node.
    /// # Errors
    /// Missing, reordered, discontinuous or invalid source evidence, failed proofs/folds.
    pub fn prove<'a>(
        &self,
        leaves: Vec<SourceNodeEvidence>,
        mut artifacts: impl FnMut([SourceIdentity; 2]) -> Result<OriginalPair, Error>,
        mut randomness: impl FnMut(usize) -> Result<NodeRandomness<'a>, Error>,
        proof_config: ProverConfig,
        fold_config: &FoldConfig,
        mut checkpoints: Option<&mut dyn ProofCheckpointStore>,
    ) -> Result<SourceNodeEvidence, Error> {
        if leaves.len() != self.leaf_count {
            return Err(Error::Input);
        }
        let mut evidence = leaves.into_iter().map(Some).collect::<Vec<_>>();
        for (index, merge) in self.merges.iter().enumerate() {
            let [left, right] = merge.children;
            let children = [
                evidence[left].take().ok_or(Error::Input)?,
                evidence[right].take().ok_or(Error::Input)?,
            ];
            let entropy = randomness(index)?;
            let circuit = SourceMergeCircuit::prepare(
                merge.plan.clone(),
                children,
                &self.vesta,
                entropy.inner_salt,
                fold_config,
            )
            .map_err(|_| Error::Proof)?;
            if let Some(store) = &mut checkpoints
                && let Some(proof) = checkpoint::restore(
                    *store,
                    &merge.source,
                    *circuit.endpoints(),
                    &self.vesta,
                    proof_config.msm_budget,
                )?
            {
                evidence.push(Some(proof));
                continue;
            }
            let original = artifacts(merge.identity)?;
            let prover = Prover::from_original_artifacts(
                &circuit,
                original.source.borrowed(),
                original.wrapper.borrowed(),
                self.pallas.clone(),
                self.vesta.clone(),
                self.import,
            )?;
            if SourceIdentity::of(&prover.qualified_source()?)?
                != SourceIdentity::of(&merge.source)?
            {
                return Err(Error::Artifact);
            }
            let proof = prover.prove(
                &circuit,
                entropy.outer_salt,
                entropy.source,
                entropy.wrapper,
                proof_config,
            )?;
            if let Some(store) = &mut checkpoints {
                checkpoint::retain(
                    *store,
                    &merge.source,
                    &proof,
                    &self.vesta,
                    proof_config.msm_budget,
                )?;
            }
            evidence.push(Some(proof));
        }
        evidence.pop().flatten().ok_or(Error::Proof)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn balanced_tree_consumes_every_original_once_in_order_without_padding() {
        for leaves in [
            2,
            3,
            4,
            5,
            33,
            35,
            43,
            83,
            515,
            1084,
            2561,
            MAX_PROGRAM_LEAVES,
        ] {
            let shape = topology(leaves).unwrap();
            assert_eq!(shape.len(), leaves - 1);
            let mut ranges = (0..leaves).map(|i| (i, i + 1)).collect::<Vec<_>>();
            let mut uses = vec![0; 2 * leaves - 1];
            for [left, right] in shape {
                assert!(left < ranges.len() && right < ranges.len());
                assert_eq!(ranges[left].1, ranges[right].0);
                ranges.push((ranges[left].0, ranges[right].1));
                uses[left] += 1;
                uses[right] += 1;
            }
            assert_eq!(ranges.last(), Some(&(0, leaves)));
            assert!(uses[..uses.len() - 1].iter().all(|n| *n == 1));
            assert_eq!(uses.last(), Some(&0));
        }
        for invalid in [0, 1, MAX_PROGRAM_LEAVES + 1, usize::MAX] {
            assert!(topology(invalid).is_err());
        }
    }
}
