name: Build iroha2-ci image

on:
  workflow_dispatch:
    inputs:
      IROHA2_CI_DOCKERFILE:
        required: true
        default: Dockerfile.build

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push iroha2-ci image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
        with:
          push: true
          tags: hyperledger/iroha2-ci:nightly-2025-05-08
          labels: commit=${{ github.sha }}
          file: ${{ github.event.inputs.IROHA2_CI_DOCKERFILE }}
          # This context specification is required
          context: .
