//! Immutable compiler-captured identities for this source owner’s existing codecs.

#[test]
fn captured_codec_schema_identities() {
    crate::captured_schema_tests::assert_bidirectional::<super::ConsensusGenesisParams>(
        "iroha_data_model::block::consensus::ConsensusGenesisParams",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ConsensusGenesisModeParams>(
        "iroha_data_model::block::consensus::ConsensusGenesisModeParams",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::NposGenesisParams>(
        "iroha_data_model::block::consensus::NposGenesisParams",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::CertPhase>(
        "iroha_data_model::block::consensus::CertPhase",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiV2EquivocationEvidence>(
        "iroha_data_model::block::consensus::SumeragiV2EquivocationEvidence",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::Evidence>(
        "iroha_data_model::block::consensus::Evidence",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::EvidencePenaltyStatus>(
        "iroha_data_model::block::consensus::EvidencePenaltyStatus",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::EvidenceRecord>(
        "iroha_data_model::block::consensus::EvidenceRecord",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiMembershipStatus>(
        "iroha_data_model::block::consensus::SumeragiMembershipStatus",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiMembershipMismatchStatus>(
        "iroha_data_model::block::consensus::SumeragiMembershipMismatchStatus",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiLaneCommitment>(
        "iroha_data_model::block::consensus::SumeragiLaneCommitment",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiDataspaceCommitment>(
        "iroha_data_model::block::consensus::SumeragiDataspaceCommitment",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiCommittedLaneBlock>(
        "iroha_data_model::block::consensus::SumeragiCommittedLaneBlock",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiLanePayloadOwnership>(
        "iroha_data_model::block::consensus::SumeragiLanePayloadOwnership",
    );
    crate::captured_schema_tests::assert_serialize::<super::LaneBlockProposalPreimage>(
        "iroha_data_model::block::consensus::LaneBlockProposalPreimage",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::LaneBlockDescriptorV1>(
        "iroha_data_model::block::consensus::LaneBlockDescriptorV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::LaneBlockProposalPayloadHintV1>(
        "iroha_data_model::block::consensus::LaneBlockProposalPayloadHintV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::LaneBlockProposalV1>(
        "iroha_data_model::block::consensus::LaneBlockProposalV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::LaneBlockVoteBodyV1>(
        "iroha_data_model::block::consensus::LaneBlockVoteBodyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::LanePayloadAvailabilityBodyV1>(
        "iroha_data_model::block::consensus::LanePayloadAvailabilityBodyV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::LanePayloadAvailabilityQcV1>(
        "iroha_data_model::block::consensus::LanePayloadAvailabilityQcV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::LaneBlockQcV1>(
        "iroha_data_model::block::consensus::LaneBlockQcV1",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::LaneBlockCertificateV1>(
        "iroha_data_model::block::consensus::LaneBlockCertificateV1",
    );
    crate::captured_schema_tests::assert_serialize::<super::LanePayloadOwnershipSubjectPreimage>(
        "iroha_data_model::block::consensus::LanePayloadOwnershipSubjectPreimage",
    );
    crate::captured_schema_tests::assert_serialize::<super::LanePayloadOwnershipPreimage>(
        "iroha_data_model::block::consensus::LanePayloadOwnershipPreimage",
    );
    crate::captured_schema_tests::assert_serialize::<super::LanePayloadOwnershipRbcPreimage>(
        "iroha_data_model::block::consensus::LanePayloadOwnershipRbcPreimage",
    );
    crate::captured_schema_tests::assert_serialize::<super::LaneBlockDescriptorPreimage>(
        "iroha_data_model::block::consensus::LaneBlockDescriptorPreimage",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::LaneSettlementReceipt>(
        "iroha_data_model::block::consensus::LaneSettlementReceipt",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::NexusFeeScheduleInputs>(
        "iroha_data_model::block::consensus::NexusFeeScheduleInputs",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::NexusFeeReceipt>(
        "iroha_data_model::block::consensus::NexusFeeReceipt",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::NativeAmxPhase>(
        "iroha_data_model::block::consensus::NativeAmxPhase",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::NativeAmxAttestationBodyV2>(
        "iroha_data_model::block::consensus::NativeAmxAttestationBodyV2",
    );
    crate::captured_schema_tests::assert_serialize::<super::NativeAmxAttestationQcV2>(
        "iroha_data_model::block::consensus::NativeAmxAttestationQcV2",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::NativeAmxAttestationQcV2Wire>(
        "iroha_data_model::block::consensus::NativeAmxAttestationQcV2Wire",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::NativeAmxLegRecordV2>(
        "iroha_data_model::block::consensus::NativeAmxLegRecordV2",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::NativeAmxReceipt>(
        "iroha_data_model::block::consensus::NativeAmxReceipt",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::LaneLiquidityProfile>(
        "iroha_data_model::block::consensus::LaneLiquidityProfile",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::LaneVolatilityClass>(
        "iroha_data_model::block::consensus::LaneVolatilityClass",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::LaneSwapMetadata>(
        "iroha_data_model::block::consensus::LaneSwapMetadata",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::LaneBlockCommitment>(
        "iroha_data_model::block::consensus::LaneBlockCommitment",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiRuntimeUpgradeHook>(
        "iroha_data_model::block::consensus::SumeragiRuntimeUpgradeHook",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiLaneGovernance>(
        "iroha_data_model::block::consensus::SumeragiLaneGovernance",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiMissingBlockFetchStatus>(
        "iroha_data_model::block::consensus::SumeragiMissingBlockFetchStatus",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiKuraStoreStatus>(
        "iroha_data_model::block::consensus::SumeragiKuraStoreStatus",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiViewChangeCauseStatus>(
        "iroha_data_model::block::consensus::SumeragiViewChangeCauseStatus",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiValidationRejectStatus>(
        "iroha_data_model::block::consensus::SumeragiValidationRejectStatus",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiPeerKeyPolicyStatus>(
        "iroha_data_model::block::consensus::SumeragiPeerKeyPolicyStatus",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::SumeragiConsensusMessageHandlingEntry,
    >("iroha_data_model::block::consensus::SumeragiConsensusMessageHandlingEntry");
    crate::captured_schema_tests::assert_bidirectional::<
        super::SumeragiConsensusMessageHandlingStatus,
    >("iroha_data_model::block::consensus::SumeragiConsensusMessageHandlingStatus");
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiVoteValidationDropEntry>(
        "iroha_data_model::block::consensus::SumeragiVoteValidationDropEntry",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::SumeragiVoteValidationDropReasonCount,
    >("iroha_data_model::block::consensus::SumeragiVoteValidationDropReasonCount");
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiVoteValidationDropPeerEntry>(
        "iroha_data_model::block::consensus::SumeragiVoteValidationDropPeerEntry",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiVoteValidationDropStatus>(
        "iroha_data_model::block::consensus::SumeragiVoteValidationDropStatus",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiConsensusCapsStatus>(
        "iroha_data_model::block::consensus::SumeragiConsensusCapsStatus",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiWorkerQueueDepths>(
        "iroha_data_model::block::consensus::SumeragiWorkerQueueDepths",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiWorkerQueueTotals>(
        "iroha_data_model::block::consensus::SumeragiWorkerQueueTotals",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiWorkerQueueDiagnostics>(
        "iroha_data_model::block::consensus::SumeragiWorkerQueueDiagnostics",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiWorkerLoopStatus>(
        "iroha_data_model::block::consensus::SumeragiWorkerLoopStatus",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiCommitInflightStatus>(
        "iroha_data_model::block::consensus::SumeragiCommitInflightStatus",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiCommitPipelineStatus>(
        "iroha_data_model::block::consensus::SumeragiCommitPipelineStatus",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiRoundGapStatus>(
        "iroha_data_model::block::consensus::SumeragiRoundGapStatus",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiCommitQuorumStatus>(
        "iroha_data_model::block::consensus::SumeragiCommitQuorumStatus",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiQcStatus>(
        "iroha_data_model::block::consensus::SumeragiQcStatus",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiNposRepairCoverageStatus>(
        "iroha_data_model::block::consensus::SumeragiNposRepairCoverageStatus",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiSafetyHaltStatus>(
        "iroha_data_model::block::consensus::SumeragiSafetyHaltStatus",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiLaneBlockSessionStatus>(
        "iroha_data_model::block::consensus::SumeragiLaneBlockSessionStatus",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiProposalGateStatus>(
        "iroha_data_model::block::consensus::SumeragiProposalGateStatus",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiNposDiagnostics>(
        "iroha_data_model::block::consensus::SumeragiNposDiagnostics",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiPipelineExecutionStatus>(
        "iroha_data_model::block::consensus::SumeragiPipelineExecutionStatus",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiAutonomousLaneExecutionStage>(
        "iroha_data_model::block::consensus::SumeragiAutonomousLaneExecutionStage",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::SumeragiAutonomousLaneExecutionStuckReason,
    >("iroha_data_model::block::consensus::SumeragiAutonomousLaneExecutionStuckReason");
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiAutonomousLaneExecution>(
        "iroha_data_model::block::consensus::SumeragiAutonomousLaneExecution",
    );
    crate::captured_schema_tests::assert_bidirectional::<
        super::SumeragiNativeAmxParticipantApplicationState,
    >("iroha_data_model::block::consensus::SumeragiNativeAmxParticipantApplicationState");
    crate::captured_schema_tests::assert_bidirectional::<
        super::SumeragiNativeAmxParticipantApplication,
    >("iroha_data_model::block::consensus::SumeragiNativeAmxParticipantApplication");
    crate::captured_schema_tests::assert_bidirectional::<super::SumeragiDiagnosticsStatus>(
        "iroha_data_model::block::consensus::SumeragiDiagnosticsStatus",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ExecKv>(
        "iroha_data_model::block::consensus::ExecKv",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ExecWitness>(
        "iroha_data_model::block::consensus::ExecWitness",
    );
    crate::captured_schema_tests::assert_bidirectional::<super::ExecWitnessMsg>(
        "iroha_data_model::block::consensus::ExecWitnessMsg",
    );
}
