#!/usr/bin/env python3
"""Record the CPython runtime path used by `iroha_python_rs`.

This helper mirrors the discovery logic in `build.rs`: it tries the explicit
environment overrides first and then queries the selected interpreter via
`sysconfig`. When a library path is found the script writes it into
`iroha_python_rs/python-runtime-path`, replacing any existing value.

Usage:
    python python/iroha_python/scripts/update_python_runtime_path.py
"""

from __future__ import annotations

import os
import sys
import sysconfig
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
OVERRIDE_PATH = REPO_ROOT / "python/iroha_python/iroha_python_rs/python-runtime-path"


def runtime_path_from_env() -> str | None:
    return os.environ.get("IROHA_PYTHON_RUNTIME_PATH")


def runtime_path_from_sysconfig() -> str | None:
    candidates: list[str] = []

    def push(value: str | None) -> None:
        if value:
            candidates.append(os.path.realpath(value))

    lib_name = sysconfig.get_config_var("LDLIBRARY") or sysconfig.get_config_var("PY3LIBRARY")
    lib_dir = sysconfig.get_config_var("LIBDIR") or sysconfig.get_config_var("LIBPL")
    if lib_name and lib_dir:
        push(os.path.join(lib_dir, lib_name))
    if lib_name and os.path.isabs(lib_name):
        push(lib_name)

    framework = sysconfig.get_config_var("PYTHONFRAMEWORK")
    install_dir = sysconfig.get_config_var("PYTHONFRAMEWORKINSTALLDIR")
    version = sysconfig.get_config_var("VERSION")
    if framework and install_dir:
        versions_dir = os.path.join(install_dir, "Versions")
        if version:
            push(os.path.join(versions_dir, version, framework))
        push(os.path.join(versions_dir, "Current", framework))

    libpython = sysconfig.get_config_var("LIBPYTHON")
    if libpython:
        push(libpython)

    for candidate in candidates:
        if candidate and os.path.exists(candidate):
            return candidate
    return None


def discover_runtime_path() -> str | None:
    return runtime_path_from_env() or runtime_path_from_sysconfig()


def main() -> int:
    path = discover_runtime_path()
    if not path:
        print("Unable to determine CPython runtime path; set IROHA_PYTHON_RUNTIME_PATH.", file=sys.stderr)
        return 1

    lines = [f"# Autogenerated by update_python_runtime_path.py for Python {sys.version.split()[0]}\n", f"{path}\n"]
    OVERRIDE_PATH.write_text("".join(lines), encoding="utf-8")
    print(f"Wrote {path} -> {OVERRIDE_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
